# Apr 25

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week. Sadly, another far too busy week; one with several executive orders aimed at education; leadership changes at the NSF; actions by numerous college presidents and system leaders; ...

## Letters/Statements

* Chancellor Matos-Rodriguez emails CUNY faculty and staff about Standing Together.

> At the start of the Spring semester, I emphasized the importance of standing together and upholding the values of our University in uncertain times. We have since seen a series of federal actions that have affected CUNY and higher education significantly.

* The UFS Executive Committee write a statement Together We Stand.

* Hunter Resolution for Mutual Defense passed our Senate by more than 96%!


* Public Statement: A Call for Constructive Engagement by AAC&U

[https://www.aacu.org/newsroom/a-call-for-constructive-engagement](https://www.aacu.org/newsroom/a-call-for-constructive-engagement)

Signatories include Chancellor Matos-Rodriguez and presidents/deans from the GC, Hunter, Hostos, CSI, and BMCC, MEC,  York, Queens

* Big Ten university faculties push for defense compact against Trump

[https://wapo.st/3EDjyYi](https://wapo.st/3EDjyYi)


* Progressive Caucus: Open Letter to New York City College and University Presidents

[https://docs.google.com/document/d/1h9AatjXiICGMKQgWIeUMOtlc5dNOEUZCUFfwHEBy8pc/edit?tab=t.0](https://docs.google.com/document/d/1h9AatjXiICGMKQgWIeUMOtlc5dNOEUZCUFfwHEBy8pc/edit?tab=t.0)

(thanks VAC)

## Resources

* American Historical Association Statements on Academic Freedom and International Scholars (Thanks EST)

[https://www.historians.org/why-history-matters/aha-advocacy/resources-for-foreign-scholars/?_zs=30dma&_zl=5RoT4](https://www.historians.org/why-history-matters/aha-advocacy/resources-for-foreign-scholars/?_zs=30dma&_zl=5RoT4)


## How best to describe the times we are in

* NYTimes: Welcome to Trump’s Mafia State

[https://www.nytimes.com/2025/04/21/opinion/trump-universities-mafia-state.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/21/opinion/trump-universities-mafia-state.html?smid=nytcore-ios-share&referringSource=articleShare)

> The pretexts that the administration is using have to do with D.E.I. and antisemitism. The real reasons, I think, are anti-intellectualism and greed, and the fact that Trump is building a mafia state.

> Now, a mafia state is an absolutely centralized system in which one person, the patron, the don, distributes money and power. And so in order to build a mafia state, such an aspiring patron needs to strip other agents of their money and power.

> And it has the ability to, if not bankrupt universities — it certainly has the ability to bankrupt universities that don’t have significant endowments, which is most of them.

> The only way for universities to really address this is to come to terms with the fact that there is no way for them, with this administration, to keep their federal money.

* For more on the steps the administration has signaled it might do to gain obesiance, this AAUP white paper from 2024 offers much insight (shared by VC):

[https://www.aaup.org/file/Manufacturing_Backlash_final_1.pdf](https://www.aaup.org/file/Manufacturing_Backlash_final_1.pdf)

> we have witnessed what one scholar correctly called an “unusually brazen series of challenges to academic freedom,” unleashed by conservative activists and a “national-level political machine” ... to undermine academic freedom and university autonomy.

Including academic gag orders seeking to ban the teaching of “critical race theory” (CRT);  shuttering academic programs; dismantling institutional efforts to increase diversity, equity, and inclusion; weaken tenure protections for faculty; undermined the accreditation process; establish academic programs, centers, and whole schools designed to teach conservative content;

>  As this white paper demonstrates, however, this legislation is largely the outgrowth of efforts by right-wing and libertarian think tanks, working closely with Republican politicians, to manufacture a culture-war backlash against educators and academic institutions ...  as part of a well-organized and well-funded backlash that seeks to roll back the political, social, and cultural gains made in the wake of the Black Lives Matter movement  increased queer and trans visibility.

* NYTimes: Trump Is Insatiable

[https://www.nytimes.com/2025/04/22/opinion/trump-harvard.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/22/opinion/trump-harvard.html?smid=nytcore-ios-share&referringSource=articleShare)

< In order to function effectively, Democracies depend on the ability of the electorate to make what Jackson calls “informed choices.” In this context, Jackson writes, “Knowledge institutions — including universities, the truth-oriented press, government offices with data collection or scientific responsibilities — are crucial for constitutional democracies.”

## Academic freedom

* Trump’s DOJ Claims Academic Journals Hold “Partisan” Stance in Scientific Debates – Mother Jones

[https://www.motherjones.com/politics/2025/04/trump-doj-academic-journals-scientific-debates-chest-journal/](https://www.motherjones.com/politics/2025/04/trump-doj-academic-journals-scientific-debates-chest-journal/)


> The publisher of CHEST, a prestigious, peer-reviewed medical journal focused on respiratory health, received a letter from the Trump administration seeking information about how its editors handle scientific controversies and “competing viewpoints.” Some medical professionals see the missive as an attempt to stifle academic freedom.

## Free Speech

* Anti-DEI Guidance Letter Put On Hold, for Now

[https://www.insidehighered.com/news/government/politics-elections/2025/04/24/education-departments-anti-dei-guidance-blocked](https://www.insidehighered.com/news/government/politics-elections/2025/04/24/education-departments-anti-dei-guidance-blocked)

> Federal judges in New Hampshire and Maryland handed down the rulings after finding plaintiffs in the two separate lawsuits were likely to succeed in proving that the Feb. 14 Dear Colleague letter violated procedural standards and the First Amendment. Prior to the orders, colleges and K-12 schools that failed to comply with the letter risked their federal funding

> “Although the 2025 letter does not make clear what exactly it prohibits, it makes at least one thing clear: schools should not come close to anything that could be considered ‘DEI,’ lest they be deemed to have guessed wrong,” the New Hampshire judge wrote. And since loss of federal grants could cripple institutions, “it is predictable—if not obvious—that [they] will eliminate all vestiges of DEI to avoid even the possibility of funding termination,” regardless of whether it is an example of executive overreach.

## ICE

* Mahmoud Khalil: What does my detention by ICE say about America?

[https://wapo.st/4czL2dT](https://wapo.st/4czL2dT)

* Detained Tufts student must be transferred to Vermont, judge rules

[https://www.washingtonpost.com/nation/2025/04/19/judge-tufts-student-rumeysa-ozturk-vermont-ice/](https://www.washingtonpost.com/nation/2025/04/19/judge-tufts-student-rumeysa-ozturk-vermont-ice/)

* Fearing Trump’s Visa Crackdown, College Students Race to Scrub Op-Eds - WSJ

[https://www.wsj.com/us-news/education/trump-student-visas-newspaper-op-eds-61595294](https://www.wsj.com/us-news/education/trump-student-visas-newspaper-op-eds-61595294)


## Funding cuts

* Weekly NIH Funding Opportunities and Notices for April 18, 2025

> (none)

(Thanks MP)

* Updates on NSF Priorities | NSF - National Science Foundation

[https://www.nsf.gov/updates-on-priorities](https://www.nsf.gov/updates-on-priorities)

>  Research projects with more narrow impact limited to subgroups of people based on protected class or characteristics do not effectuate NSF priorities.

> 3. What types of awards are being terminated?
> Awards that are not aligned with NSF's priorities have been terminated, including but not limited to those on diversity, equity, and inclusion (DEI) and misinformation/disinformation.

* National Science Foundation Terminates Hundreds of Active Research Awards - The New York Times

[https://www.nytimes.com/2025/04/22/science/trump-national-science-foundation-grants.html](https://www.nytimes.com/2025/04/22/science/trump-national-science-foundation-grants.html)

> The grant supported Dr. Fiesler’s research on building A.I. literacy. She received no official explanation for why the grant was being terminated more than a year ahead of its scheduled end. But Dr. Fiesler speculated that it had something to do with the word “misinformation” in the award’s abstract.

> In a statement on Friday, the N.S.F. said that its grant cancellations were not in violation of the temporary restraining order. When asked by The Times to provide clarification on the legality of the grant cancellations, the agency declined to comment.

> Last Thursday, the magazine Nature reported that all new research grants by the agency had been frozen, as ordered by the Department of Government Efficiency, or DOGE. The N.S.F. declined to confirm the freezing of new awards or what role, if any, DOGE had in the action.

* NSF Director Resigns

[https://www.insidehighered.com/news/quick-takes/2025/04/25/nsf-director-panchanathan-resigns](https://www.insidehighered.com/news/quick-takes/2025/04/25/nsf-director-panchanathan-resigns)

>  His resignation comes less than one week after he issued sweeping priority changes—including terminating funding for projects that focus on diversity, equity and inclusion or combating misinformation—at the independent agency that funds billions of dollars to nonmedical university research each year.

> “I believe that I have done all I can to advance the mission of the agency and feel that it is time to pass the baton to new leadership,” Panchanathan wrote in a resignation letter, first reported by Science. “I am deeply grateful to the presidents for the opportunity to serve our nation.”

> Under Panchanathan’s leadership, the NSF’s stated priorities have included increasing diversity in the STEM workforce, forming industry partnerships, job creation and broadening research opportunities for smaller universities and community colleges.

* Trump is destroying 100 years of competitive advantage in 100 days

[https://www.washingtonpost.com/opinions/2025/04/25/us-losing-competitive-edge-science/](https://www.washingtonpost.com/opinions/2025/04/25/us-losing-competitive-edge-science/)

> All three of these forces are now being reversed. The Trump administration is at war with the country’s leading universities, threatening them with hostile takeovers and withholding billions of dollars in research funding. America’s crown jewels of science, the National Institutes of Health and the National Science Foundation, are being gutted.


* CUNY's Research on Vaccine Misinformation Halted by Trump Administration | THE CITY — NYC News


[https://www.thecity.nyc/2025/04/24/cuny-layoffs-vaccine-research-funding-cuts-misinformation-trump/](https://www.thecity.nyc/2025/04/24/cuny-layoffs-vaccine-research-funding-cuts-misinformation-trump/)

> But a day later, on March 11, the NIH terminated a $3.3 million project led by Nash [CUNY faculty member who provided sage advice and was widely cited during the pandemic] that studied whether or not brief digital messages could increase COVID-19 vaccine uptake among adults with mental health issues like anxiety and depression.

> “We’re looking at letting people go, furloughing them, people losing their health insurance and people losing their opportunity to do the kind of work that they signed up to do,” Nash said.

> “We’re doing our best to see them through, if they’re finishing their degree with us this year, getting them through to the end,” he added. “Our dean has also offered to try and help where he can. But CUNY is not a university with deep pockets. We don’t have an endowment that we can draw on for these kinds of things.”

In the Chancellor's "Stand Together" email we have:

> We are evaluating how changes to funding from the National Institutes of Health, Department of Energy and other federal agencies will impact our research and programming. Cuts in NIH reimbursements, for example, for operational costs of research and training are being challenged in court, but should they be carried out we estimate that CUNY would receive only about 35% of our expected $12.7 million payment on currently active grants. In addition, 61 CUNY research projects have been subject to stop-work orders from federal agencies.

* Florida’s Own DOGE Reviews Faculty Research, Grants

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/04/25/floridas-own-doge-reviewing-faculty-research-grants](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/04/25/floridas-own-doge-reviewing-faculty-research-grants)

> Earlier this month, the Florida DOGE asked public college and university presidents to provide an account—by the end of last week—of “all research published by staff” over the last six years, including “Papers and drafts made available to the public or in online academic repositories for drafts, preprints, or similar materials.”

> “If not contained therein, author’s name, title, and position at the institution” must be provided, according to the letters the presidents received. The letters didn’t say what this and other requests were for.

> The Florida DOGE also requested information on all grants awarded to institutions over the last six years, asking for each institution’s policy on allocating grants “for purposes of indirect cost recovery, including procedures for calculation.” Further, it requested an account of “all filled and vacant positions held by any employee with a non-instructional role.”

> By the end of April, Florida’s public institutions must also provide the “Length of research associated” with each research publication, funding sources associated with the research and any “publications about the research” from the researcher or institution. In addition, the state DOGE is requesting funding sources for each institution’s noninstructional positions and the names of the nonstudent employees administering the grants.

> And that may not be the end of the DOGE demands...


## Accreditation

*  “Trump to Sign Executive Order Targeting University Accreditors”

[https://www.wsj.com/us-news/education/trump-accreditors-executive-order-universities-4e4366cc?mod=djemalertNEWS](https://www.wsj.com/us-news/education/trump-accreditors-executive-order-universities-4e4366cc?mod=djemalertNEWS)

(Thanks to DAM for this link).

> "Revoking accreditation is an existential threat for these universities,” said Andrew Gillen, a research fellow at the Cato Institute. “If you lose Pell grants and lose student loans, for most colleges that means you’re done.”

> Some conservatives have called for stronger changes to the watchdog function of higher education, including proposals to make schools accountable for the federal loans their students take out. Right now, schools aren’t penalized if graduates default on loans.

* NYTimes: Trump Signs Executive Order Targeting College Accreditors

[https://www.nytimes.com/2025/04/23/us/politics/trump-executive-order-university-accreditors.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/23/us/politics/trump-executive-order-university-accreditors.html?smid=nytcore-ios-share&referringSource=articleShare)

(Along with many others which will prove equally troubling if found legal)

> “The federal government has long stayed away from any involvement in a college’s curriculum or hiring, and current law prohibits this kind of intrusion into academic affairs,” Mr. Shireman [a senior fellow at the Century Foundation] said, adding that the executive order “steps far across this line.”


> Mr. Trump also signed executive orders to encourage the use of artificial intelligence in schools, promote private-sector partnerships with historically Black colleges and universities, and increase the number of apprenticeships in skilled trade jobs. Another order instructed his administration to make it more difficult for universities to obscure details of foreign funding.

> Two other orders focused on student discipline, which has been a political flashpoint for the past decade.

> One order was to ensure that disciplinary policies were not based on D.E.I. policies. Another restricts the use of the so-called disparate impact rule, which civil rights groups have long said is an important tool for showing discrimination against minorities.

* Trump orders changes to civil rights rules, college accreditation

[https://wapo.st/42L5uEa](https://wapo.st/42L5uEa)

* The EO

[https://www.whitehouse.gov/presidential-actions/2025/04/reforming-accreditation-to-strengthen-higher-education/](https://www.whitehouse.gov/presidential-actions/2025/04/reforming-accreditation-to-strengthen-higher-education/)



* Accreditors Sound Off on Executive Order

[https://www.insidehighered.com/news/government/politics-elections/2025/04/25/accreditors-sound-executive-order](https://www.insidehighered.com/news/government/politics-elections/2025/04/25/accreditors-sound-executive-order)

* Middle States issues and Advocacy Alert

[https://www.msche.org/2025/04/23/advocacy-alert-executive-order-regarding-accreditation/](https://www.msche.org/2025/04/23/advocacy-alert-executive-order-regarding-accreditation/)

> – The Order directs the Secretary of Education to hold higher education “accreditors” accountable, including through denial, monitoring, suspension, or termination of accreditation recognition, for accreditors’ poor performance or violations of federal civil rights law.

(One might reasonably see this as groundwork to suspend existing accreditors and replace them with more adminstration friendly/industry unfriendly accreditors)

> – The Order mandates the Secretary of Education realign accreditation with student-focused principles by:

> – Prioritizing intellectual diversity among faculty in order to advance academic freedom, intellectual inquiry, and student learning.

(Viewpoint diversity is perhaps better know as affirmative action for underrepresented political view points)



## Other EOs

* EO on foreign monies

[https://www.whitehouse.gov/presidential-actions/2025/04/transparency-regarding-foreign-influence-at-american-universities/](https://www.whitehouse.gov/presidential-actions/2025/04/transparency-regarding-foreign-influence-at-american-universities/)


* With the U.S. cracking down on student loan payments, is college still worth it?

[https://www.washingtonpost.com/business/2025/04/25/student-loan-payments-collections-college-affordability/](https://www.washingtonpost.com/business/2025/04/25/student-loan-payments-collections-college-affordability/)

This columnists answer: community college for the win

## Behind the curtain

* Trump’s destructive war on academia

[https://www.washingtonpost.com/opinions/2025/04/19/trump-harvard-irs-nixon-universities/](https://www.washingtonpost.com/opinions/2025/04/19/trump-harvard-irs-nixon-universities/)

> President Donald Trump has launched a public blitzkrieg against Harvard. On Monday, he froze $2.2 billion in federal funding after the university rejected a far-reaching list of contradictory demands, including the hiring of an external auditor to evaluate the “viewpoint diversity” of its students, faculty, staff and leadership. On Wednesday, Treasury asked the IRS to consider revoking Harvard’s tax-exempt status. (Donations to the university could dry up if they’re not tax-deductible.) Next, the Department of Homeland Security threatened to revoke Harvard’s ability to host international students, who make up 27 percent of the student body. In the coming months, Trump and congressional allies hope to impose devastating taxes on university endowment funds — Vice President Vance has suggested as high as 35 percent — and plan to scrutinize their investments in China and clean energy.

> Academic freedom is worth defending. In the long term, this might require colleges to reduce their dependence on federal dollars. In the short term, schools should stick together to resist Trump’s unlawful dictates on what they teach and whom they hire. It is heartening that Harvard’s defiance is already helping to stiffen the backbones of college administrators elsewhere.

## Bent

### Cornell

* NYTimes: Cornell Cancels Kehlani Performance Over Her Stance on the War in Gaza

[https://www.nytimes.com/2025/04/23/nyregion/kehlani-cornell-concert-replaced.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/23/nyregion/kehlani-cornell-concert-replaced.html?smid=nytcore-ios-share&referringSource=articleShare)

## Unbent

* Trump and Vance fear universities for a reason

[https://wapo.st/4juE7ow](https://wapo.st/4juE7ow)

* President Trump has tested his authority with such force that other institutions—universities, law firms and many lawmakers—have started to fight back

[https://www.wsj.com/politics/policy/trump-authority-resistance-law-firms-universities-424632ae?st=ZS9Wx4&reflink=article_gmail_share](https://www.wsj.com/politics/policy/trump-authority-resistance-law-firms-universities-424632ae?st=ZS9Wx4&reflink=article_gmail_share)

* Can Colleges Survive Trump's Cuts

[https://www.chronicle.com/article/can-colleges-survive-trumps-cuts](https://www.chronicle.com/article/can-colleges-survive-trumps-cuts)

> The cost of Trump’s proposals could exceed $100 million per year for dozens of institutions, according to analysis by the economist Phillip Levine. And yet the Trump administration has gone even further by withholding nearly all federal grant funding from some elite institutions. Columbia University tried to preserve $400 million in federal funding by agreeing to a list of onerous federal demands that get into the minutiae of academic governance, but even that has not satisfied the federal government.

>  Blue-state public flagship universities are likely the next target, and even institutions that avoid such politicized attention are likely to suffer from structural cuts in federal grants and contracts. These cuts have happened so suddenly that some universities began to take action immediately in order to preserve cash flow, a key lesson from the pandemic. But this is also a longer-term financial issue as 45 months remain in the Trump administration, and there is no guarantee that federal funding returns to normal in 2029.

(Of the 4 steps suggested, only "Conduct layoffs and hiring and spending freezes" appears applicable to CUNY.)

> To this point, the federal government has promised that financial aid to students, the largest source of federal funding to most universities, will not be affected by cuts elsewhere in the Department of Education. But it is possible that the federal government tries to selectively pull federal financial-aid eligibility,

* NYTimes: Trump Tried to Derail Our Work. We Banded Together, and Moved Forward.

[https://www.nytimes.com/2025/04/22/opinion/earth-day-nature-report-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/22/opinion/earth-day-nature-report-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

Inspiring story of environmental scientists banding together despite federal action.

> Somewhere between the desert horizon and the chorus of the U2 song “Stuck in a Moment You Can’t Get Out Of” looping in my mind, it hit me: I had to shake off the despair and get myself together. The project needed to continue. And so with encouragement from friends and mentors, my collaborators and I began reaching out — to potential partners, funders and publishers.

> What we found wasn’t just financial support. It was energy. It was courage. People understood the urgency and the opportunity. And together, we began to reimagine the work not just as a continuation of what had been cut short but also as something new and more alive. A rigorous, independent effort to tell the story of nature in America.

### Harvard

* Trump’s freeze on $2.2 billion to Harvard provided no proof of wrongdoing

[https://www.washingtonpost.com/education/2025/04/17/harvard-trump-grant-freeze-antisemitism/](https://www.washingtonpost.com/education/2025/04/17/harvard-trump-grant-freeze-antisemitism/)

* NYTimes: Trump Officials Blame Mistake for Setting Off Confrontation With Harvard

[https://www.nytimes.com/2025/04/18/business/trump-harvard-letter-mistake.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/18/business/trump-harvard-letter-mistake.html?smid=nytcore-ios-share&referringSource=articleShare)

(Sure...)

* Harvard pushes back on claim that Trump team mistakenly sent demand letter

[https://www.washingtonpost.com/education/2025/04/19/harvard-trump-letter-mistake-unauthorized/](https://www.washingtonpost.com/education/2025/04/19/harvard-trump-letter-mistake-unauthorized/)


* NYTimes: In Trump Attack on Harvard, Punishment Before Proof

[https://www.nytimes.com/2025/04/18/us/trump-harvard-legal-process.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/18/us/trump-harvard-legal-process.html?smid=nytcore-ios-share&referringSource=articleShare)

* The Trump administration has grown so furious with Harvard that it is planning to pull an additional $1 billion of the school’s funding for health research


[https://www.wsj.com/us-news/education/trump-administration-irate-at-harvard-will-pull-additional-1-billion-in-funding-8c209113?st=54dT6c&reflink=article_gmail_share](https://www.wsj.com/us-news/education/trump-administration-irate-at-harvard-will-pull-additional-1-billion-in-funding-8c209113?st=54dT6c&reflink=article_gmail_share)

> The government’s set of demands was mistakenly sent a day earlier than the task force intended, but its contents weren’t an error, people familiar with the task force said. The administration stands behind the letter with the demands, a White House spokesman said. The New York Times earlier reported that a government official said the letter was sent mistakenly.


* Education Dept. Seeks Records From Harvard Related to Foreign Gifts and Contracts

[https://www.insidehighered.com/news/quick-takes/2025/04/21/education-department-seeks-records-harvard](https://www.insidehighered.com/news/quick-takes/2025/04/21/education-department-seeks-records-harvard)

> The department said Friday that its review of Harvard’s disclosures showed they were “incomplete and inaccurate.” As a result, the department requested records related to all of Harvard’s foreign gifts and contracts and procedures related to complying with Section 117, the federal law that requires the disclosures.

* Harvard School of Public Health Begins Layoffs As Trump Slashes Funding

[https://www.thecrimson.com/article/2025/4/18/hsph-layoffs/](https://www.thecrimson.com/article/2025/4/18/hsph-layoffs/)

> HSPH spokesperson Stephanie Simon wrote in a statement that the school is facing a “significant budget crisis” and is taking a targeted approach to fiscal austerity by working to “identify strategic priorities and make sustainable budget cuts.”

> “Unfortunately, this will lead to layoffs,” Simon wrote.

> The school is also exiting their leases on two buildings and evaluating their agreements with other buildings to cut expenses “by consolidating onto our core campus,” according to Simon.

* NYTimes: Harvard Sues Trump Administration Over Threats to Cut Funding

[https://www.nytimes.com/2025/04/21/us/harvard-lawsuit-trump-administration.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/21/us/harvard-lawsuit-trump-administration.html?smid=nytcore-ios-share&referringSource=articleShare)



### Columbia

* NYTimes: Protesters Chain Themselves to Columbia Gates, Calling for Activists’ Release

[https://www.nytimes.com/2025/04/21/us/politics/columbia-protests-khalil-mahdawi-ice.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/21/us/politics/columbia-protests-khalil-mahdawi-ice.html?smid=nytcore-ios-share&referringSource=articleShare)



## Blowback

* NYTimes: Losing International Students Could Devastate Many Colleges

[https://www.nytimes.com/2025/04/19/us/losing-international-students-could-devastate-many-colleges.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/19/us/losing-international-students-could-devastate-many-colleges.html?smid=nytcore-ios-share&referringSource=articleShare)

* Trump’s Funding Freezes Halt Medical Research, Deaf Education Training

[https://www.insidehighered.com/news/faculty-issues/research/2025/04/21/trump-admin-cuts-halt-medical-research-deaf-ed-training](https://www.insidehighered.com/news/faculty-issues/research/2025/04/21/trump-admin-cuts-halt-medical-research-deaf-ed-training)

> “This work would have the potential to bring new therapies to patients with these fatal diseases,” said D’Armiento, who also serves as chair of Columbia’s University Senate Executive Committee. She questioned why the government would cancel the funding; it was paying her to conduct research it wanted and benefiting from the fact that Columbia provides her research infrastructure and pays about 80 percent of her salary.

* How Europe is quietly stealing America’s scientists

[https://www.politico.com/newsletters/politico-nightly/2025/04/24/how-europe-is-quietly-stealing-americas-scientists-00308988](https://www.politico.com/newsletters/politico-nightly/2025/04/24/how-europe-is-quietly-stealing-americas-scientists-00308988)

> Across the EU, an effort is underway to capitalize on the U.S. brain drain, hoping to tap into the exodus of intellectual talent from universities and the federal government. European universities are courting top American scientists and researchers en masse with offers of “academic asylum.” The European Research Council has doubled the funding it offers researchers to move to the continent to €2 million ($2.3 million). A bloc of 12 EU nations are working together to fast-track visas, Horizon Europe grants, and relocation stipends in an effort to poach U.S. brainpower in accordance with their own strategic priorities.

(Scientists leaving Germany in 1939 was one of three reasons for the growth in US research accomplishments in the Zakaria op-ed https://www.washingtonpost.com/opinions/2025/04/25/us-losing-competitive-edge-science/)

## Alternate Reality

* White House Partners With Hillsdale for Lecture Series

[https://www.insidehighered.com/news/quick-takes/2025/04/25/white-house-partners-hillsdale-lecture-series](https://www.insidehighered.com/news/quick-takes/2025/04/25/white-house-partners-hillsdale-lecture-series)

> The Trump administration also worked with Hillsdale at the end of the president’s first term. In early 2017, Hillsdale officials were part of a commission, chaired by Arnn, that produced the 1776 Report, a widely ridiculed document that academics dismissed as unserious scholarship. Critics argued the 1776 Report provided a whitewashed view of American history, omitted Native Americans entirely and had multiple citation issues.

>  (Hillsdale, a private, Christian institution in Michigan, does not accept federal financial aid.)


* Coming to a theater near you...

[https://www.whitehouse.gov/lab-leak-true-origins-of-covid-19/](https://www.whitehouse.gov/lab-leak-true-origins-of-covid-19/)

## Coming attractions

* U.S. Texts Barnard Employees and Asks if They Are Jewish

[https://www.nytimes.com/2025/04/23/nyregion/barnard-faculty-eeoc-text-jewish.html](https://www.nytimes.com/2025/04/23/nyregion/barnard-faculty-eeoc-text-jewish.html)

> Serena Longley, Barnard’s general counsel, acknowledged in an email to the faculty members that Barnard had provided the commission with the personal contact information of staff members to give them the opportunity to participate. “Participation in the survey is voluntary,” she wrote.

* Many Jews say Trump is politicizing the fight against antisemitism

[https://www.washingtonpost.com/politics/2025/04/25/antisemitism-trump-jews-israel/](https://www.washingtonpost.com/politics/2025/04/25/antisemitism-trump-jews-israel/)

> "Antisemitism is real and it requires robust, constructive solutions,” said Amy Spitalnick, CEO of the Jewish Council for Public Affairs. “What’s happening now, though, is exploiting the Jewish community’s legitimate and real concerns about antisemitism to undermine rule of law, due process, educational institutions and our democracy.”

:::

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.
