# Apr 11

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week. Sadly, there is too much to track faithfully and the pace seems to be increasing. VAC also directs you to And of course this from Chronicle: [https://www.chronicle.com/article/tracking-trumps-higher-ed-agenda](https://www.chronicle.com/article/tracking-trumps-higher-ed-agenda).


## Days of action


## Letters

* PSC Immigration Support Petition (Open letter)

[https://psc-cuny.org/issues/immigrant-solidarity-working-group/tell-cuny-no-ice-dhs-on-campus/](https://psc-cuny.org/issues/immigrant-solidarity-working-group/tell-cuny-no-ice-dhs-on-campus/)

* We Must Leverage the Strength of Our Institutions and Stand Together (open letter)

[https://sites.google.com/view/we-must-leverage-the-strength/home?fbclid=IwZXh0bgNhZW0CMTEAAR0BKiP0-e72KjvApm6tuzHu2FOkUkt_0tlDorehtfp5Qa4rkcpPcFJDIAU_aem_20HkljjBmAVl71WCCUbxIw](https://sites.google.com/view/we-must-leverage-the-strength/home?fbclid=IwZXh0bgNhZW0CMTEAAR0BKiP0-e72KjvApm6tuzHu2FOkUkt_0tlDorehtfp5Qa4rkcpPcFJDIAU_aem_20HkljjBmAVl71WCCUbxIw)

(Thanks to PP)

* We Must Leverage the Strength of Our Institutions and Stand Together

[https://sites.google.com/view/we-must-leverage-the-strength/home](https://sites.google.com/view/we-must-leverage-the-strength/home)

[https://academeblog.org/2025/04/01/faculty-letter-calls-for-interuniversity-defense-of-higher-education/](https://academeblog.org/2025/04/01/faculty-letter-calls-for-interuniversity-defense-of-higher-education/)

(Letter; blog post from AAUP about this letter. Thanks TR)

> However, the Trump administration is weaponizing these legitimate investigations as a pretext for an unprecedented federal attack on higher education. The administration’s recent actions—including its letter to Columbia University's Board of Trustees and its illegal detention and threatened deportation of a student green card holder who has not been charged with a crime—go far beyond enforcing civil rights law. These measures threaten free speech, due process, and the very foundations of inquiry and unrestricted exploration of ideas on which academic institutions are built.

## Public statements by Colleges and Universities

* Teachers College (Thanks CW)

[https://connect.tc.columbia.edu/emailviewonwebpage.aspx?erid=31352001&trid=9d7252b8-ce40-4517-ab56-82b2a86577c3](https://connect.tc.columbia.edu/emailviewonwebpage.aspx?erid=31352001&trid=9d7252b8-ce40-4517-ab56-82b2a86577c3)

## Academic Freedom

* Add John Jay to the list of campuses speaking out about academic freedom violations by endorsing the UFS Letter in Defense of Academic Freedom.

[https://www.dropbox.com/scl/fo/my5g55jprx5o64r4vzus0/AO9WLNUUIorJRhgTO1SupgY?rlkey=zvsqtp7ev781y4rqqjti8xaho&e=1&dl=0](https://www.dropbox.com/scl/fo/my5g55jprx5o64r4vzus0/AO9WLNUUIorJRhgTO1SupgY?rlkey=zvsqtp7ev781y4rqqjti8xaho&e=1&dl=0)


## Shared governance

* Ohio Budget Bill Could Enact Even More Higher Ed Changes

[https://www.insidehighered.com/news/quick-takes/2025/04/08/ohio-budget-bill-could-enact-even-more-higher-ed-changes](https://www.insidehighered.com/news/quick-takes/2025/04/08/ohio-budget-bill-could-enact-even-more-higher-ed-changes)

> The latest version of an Ohio state budget bill includes numerous provisions that could impact public colleges and universities—including a line saying that, in curricular decisions, all feedback by a faculty senate, “or comparable representative body, is **advisory**.”

> House Bill 96 stresses that institutions’ boards of trustees would have the “final, overriding authority to approve or reject any establishment or modification” of any “courses, general education requirements, and degree programs.” It also stresses that boards would have “unilateral and ultimate authority to establish new academic programs, schools, colleges, institutes, departments, and centers.”

> Sara Kilpatrick, executive director of the Ohio Conference of the American Association of University Professors, said it’s already “ultimately under the boards’ responsibilities to have the final say in really anything.” But, she said, “I think that this is specifically language that’s designed to sideline faculty and to potentially politicize program and curriculum offerings.”



## DEI

* My Book, "White Too Long," Banned from US Naval Academy

[https://www.whitetoolong.net/p/my-book-white-too-long-banned-from?utm_campaign=post&showWelcomeOnShare=true](https://www.whitetoolong.net/p/my-book-white-too-long-banned-from?utm_campaign=post&showWelcomeOnShare=true)

## Funding cuts

* NYTimes: Judge Permanently Bars N.I.H. From Limiting Medical Research Funding

[https://www.nytimes.com/2025/04/04/us/politics/nih-medical-research-funding.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/04/us/politics/nih-medical-research-funding.html?smid=nytcore-ios-share&referringSource=articleShare)

> Judge Kelley had consistently agreed, ruling repeatedly that the policy appeared unnecessarily reckless and would inflict serious harm on important medical research. After initially barring the Trump administration from implementing the change in February, she extended her order twice while the lawsuit played out.


* NYTimes: The N.E.H. Does What Republicans Always Wanted. DOGE Slashed It Anyway.

[https://www.nytimes.com/2025/04/07/opinion/humanities-cuts-tennessee-neh-doge.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/07/opinion/humanities-cuts-tennessee-neh-doge.html?smid=nytcore-ios-share&referringSource=articleShare)

> The N.E.H. is one of the least-known of the federal agencies, but its work reaches a huge number of Americans, including those in Republican districts. It awards grants that fund research fellowships, programs at museums and historic sites, website development and documentary filmmaking, among a host of other projects related to the public humanities. But it also disburses a great chunk of its appropriation — some $65 million of an annual budget of roughly $210 million — directly to nonprofit humanities councils in all 50 states, the District of Columbia and five territories.

* Staff cuts begin at NEH, threatening humanities programs across U.S.


[https://www.washingtonpost.com/entertainment/art/2025/04/10/neh-staff-cuts-reduction-in-force/](https://www.washingtonpost.com/entertainment/art/2025/04/10/neh-staff-cuts-reduction-in-force/)


* Trump Presents Harvard With an Ultimatum for Federal Funds

[https://www.insidehighered.com/news/government/politics-elections/2025/04/04/trump-sets-demands-harvard-must-meet-regain-federal](https://www.insidehighered.com/news/government/politics-elections/2025/04/04/trump-sets-demands-harvard-must-meet-regain-federal)

> The ultimatum came just three days after the president’s Joint Task Force to Combat Anti-Semitism notified the university it had been placed under review for its alleged failure to protect Jewish students and faculty from discrimination. If the case follows the precedent set at other universities, Harvard and its affiliate medical institutions could lose up to $9 billion in federal grants and contracts if they do not comply.

> Sources say the move is driven less by true concern about antisemitism on campus than by the government’s desire to abolish diversity efforts and hobble higher ed institutions it deems too “woke.” This week alone, the administration has retracted funds from Brown and Princeton Universities. Before that, it targeted the University of Pennsylvania and Columbia University and opened dozens of civil rights investigations at other colleges, all of which are ongoing.

(Also https://www.chronicle.com/article/trump-demands-harvard-eradicate-dei-to-preserve-its-federal-funding)

* NYTimes: Columbia’s Former Leader Faced Contentious Interview After Resigning

[https://www.nytimes.com/2025/04/07/nyregion/columbia-president-armstrong-federal-deposition.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/07/nyregion/columbia-president-armstrong-federal-deposition.html?smid=nytcore-ios-share&referringSource=articleShare)

> The hearing transcript provided an inside glimpse of the tension between Columbia and representatives of the Trump administration’s multiagency antisemitism task force, which is investigating at least 10 universities in an effort to root out what it sees as disturbing antisemitic activity on campuses.

* NYTimes: Trump Administration Freezes $1 Billion for Cornell and $790 Million for Northwestern, Officials Say

[https://www.nytimes.com/2025/04/08/us/politics/cornell-northwestern-university-funds-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/08/us/politics/cornell-northwestern-university-funds-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> The moves are the latest and largest in a rapidly escalating campaign against elite American universities that has resulted in billions in federal funds being suspended or put under review in just over a month. Other schools that have had funds threatened include Brown, Columbia, Harvard, the University of Pennsylvania and Princeton.

> Northwestern, a Big Ten university, is the first non-Ivy League school to have funding from the Trump administration targeted under investigations of alleged discrimination. The university issued a “progress report” last week that highlighted its efforts to protect Jewish students, including mandatory antisemitism training for all students, faculty and staff.

Also reported on here

[https://www.wsj.com/us-news/education/trump-team-to-freeze-nearly-2-billion-at-cornell-and-northwestern-universities-2e13a88a?st=BJbjFN&reflink=article_gmail_share](https://www.wsj.com/us-news/education/trump-team-to-freeze-nearly-2-billion-at-cornell-and-northwestern-universities-2e13a88a?st=BJbjFN&reflink=article_gmail_share)

and elsewhere

* NYTimes: Trump Has Targeted These Universities. Why?

[https://www.nytimes.com/article/trump-university-college.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/article/trump-university-college.html?smid=nytcore-ios-share&referringSource=articleShare)

> Critics of the administration have not hesitated to point out that all of those schools are in states — or, in George Washington’s case, a federal district — that voted for the Democratic ticket in 2024.

* Through emails and social media, colleges discover federal funds are frozen

[https://www.washingtonpost.com/education/2025/04/11/elite-colleges-trump-federal-funding-freeze-email/](https://www.washingtonpost.com/education/2025/04/11/elite-colleges-trump-federal-funding-freeze-email/)


* NSF, NIH Slash Support for Early-Career Scientists

[https://www.insidehighered.com/news/quick-takes/2025/04/10/nsf-nih-slash-support-early-career-scientists](https://www.insidehighered.com/news/quick-takes/2025/04/10/nsf-nih-slash-support-early-career-scientists)

> On Tuesday, Nature reported the NSF Graduate Research Fellowship Program awarded 1,000 fellowships—fewer than half of the record-setting 2,555 fellowship offers it made in 2023, and the second-smallest number of awards since 2008.

> Over the past two weeks, the NIH has also canceled numerous institutional and individual training grants, including many that support scientists from underrepresented communities, according to The Transmitter.

* NIH Freezes Millions More in Funding for Columbia

[https://www.insidehighered.com/news/government/politics-elections/2025/04/09/nih-freezes-millions-more-funding-columbia](https://www.insidehighered.com/news/government/politics-elections/2025/04/09/nih-freezes-millions-more-funding-columbia)

> But after the university agreed to enact various reforms the Trump administration demanded to address alleged antisemitism on campus, it appeared a reprieve was in order. Education Secretary Linda McMahon said last month that she believed Columbia was “on the right track” toward final negotiations to unfreeze the research funds.

> Instead, the Trump administration has gone in the opposite direction, cutting off even more research funding. According to Science, the NIH froze Columbia’s funding Monday at the direction of the U.S. Department of Health and Human Services. NIH is reportedly not only blocking new funding but also ceasing payments for work on existing projects. In addition, the agency will require prior approval to tap existing disbursements.

## DOE

* NYTimes: When Trump Is Done, What Will Remain of Public Education?

[https://www.nytimes.com/2025/04/08/opinion/trump-k-12-education.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/08/opinion/trump-k-12-education.html?smid=nytcore-ios-share&referringSource=articleShare)

A longer piece on the history of the DOE and education in US history

> America’s story is one of progress, which has rarely been obtained simply through good will. It has to be enforced. Fights for equality have been messy, and quite bloody at times. Understanding that history is important so as not to repeat it. Still, shortly before leaving office in 2020, Mr. Trump established the President’s Advisory 1776 Commission, in part a rebuttal to the 1619 Project, as a way for the administration to write its own version of American history.

> The president’s vision to take a sledgehammer to the Department of Education’s ability to function will cause student suffering. The founders believed that education was critical to the full experience of citizenship; it was where students learned arts, sciences, humanities and how to engage with one another. But putting that vision into place left the nation with a system where inequities — in content and classroom composition — were left in place.

> America began to undo those inequities, and the department protected that progress. Now, less than three months into Mr. Trump’s second presidency, the administration has done everything in its power, and some things beyond its authority, to ensure we are equal no more.

## ICE

* Trump cancels dozens of international student visas at UC, Stanford - Los Angeles Times


[https://www.latimes.com/california/story/2025-04-05/trump-administration-cancels-international-student-visas-university-of-california-stanford](https://www.latimes.com/california/story/2025-04-05/trump-administration-cancels-international-student-visas-university-of-california-stanford)

> At UC San Diego, Chancellor Pradeep Khosla said in a campus message late Friday that five students had their visas revoked. He said the university received the notification “without warning.” Khosla said a sixth student was “detained at the border, denied entry and deported to their home country.”

> A University of California statement said that “several” campuses had students who lost their visa status but did not offer more details.

* Trump Admin Broadens Scope of Student Visa Terminations


[https://www.insidehighered.com/news/global/international-students-us/2025/04/08/trump-admin-broadens-scope-student-visa](https://www.insidehighered.com/news/global/international-students-us/2025/04/08/trump-admin-broadens-scope-student-visa)

> Inside Higher Ed uncovered dozens of visa terminations that have not been reported elsewhere, many of them at regional public universities and small private colleges.


* CUNY is not immune

There are reports that over 20 CUNY students have had SEVIS visa issues (Student and Exchange Visitor Program)

[https://ny1.com/nyc/all-boroughs/education/2025/04/09/department-of-homeland-security-revokes-student-visas-at-cuny-and-fordham--schools-say](https://ny1.com/nyc/all-boroughs/education/2025/04/09/department-of-homeland-security-revokes-student-visas-at-cuny-and-fordham--schools-say)

[https://www.nydailynews.com/2025/04/09/trump-administration-cancels-dozens-of-student-visas-at-nyu-cuny-other-ny-schools/](https://www.nydailynews.com/2025/04/09/trump-administration-cancels-dozens-of-student-visas-at-nyu-cuny-other-ny-schools/)

* Tracking Trump’s Actions on Student Visas


[https://www.chronicle.com/article/tracking-trumps-actions-on-student-visas](https://www.chronicle.com/article/tracking-trumps-actions-on-student-visas)

* With secret moves against international students, feds spread fear


[https://www.washingtonpost.com/politics/2025/04/09/international-student-visas-revoked-trump-deportation-fears/](https://www.washingtonpost.com/politics/2025/04/09/international-student-visas-revoked-trump-deportation-fears/)


## Bent

* NYTimes: Columbia Displays More Aggressive Posture in Dealing With Demonstrators

[https://www.nytimes.com/2025/04/04/nyregion/columbia-security-protesters-removed.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/04/nyregion/columbia-security-protesters-removed.html?smid=nytcore-ios-share&referringSource=articleShare)

> A new, more assertive stance was on display on Wednesday, as the university’s officers intervened to stop a daylong demonstration of students, most of whom were Jewish, who had chained themselves to the campus’s wrought-iron gates.

> Moving to end the protest, public safety officers cut or untangled the students from their chains at about 11:15 p.m., and then physically picked them up before escorting them from campus. The officers carried at least one student off the lawn, according to video posted on social media and student interviews.


* How conservatives are using Columbia as a ‘test case’ to enforce Trump’s agenda


[https://wapo.st/43EUxWX](https://wapo.st/43EUxWX)

This is an important analysis of the playbook being employed and it references what appears to be another Chris Rufo type.

> Critical of college admissions, diversity, equity and inclusion policies, and campus protests that he lambasted as pro-Hamas, Max Eden, then a senior fellow at the American Enterprise Institute, wrote an outline that presaged what was to come in the new Trump administration. He singled out Columbia as the top target.

>  “To scare universities straight,” Eden wrote in the Washington Examiner [https://www.aei.org/op-eds/a-comprehensive-guide-to-overhauling-higher-education/] , Education Secretary Linda McMahon “should start by taking a prize scalp. She should simply destroy Columbia University.”

> On the day the administration canceled the federal funding to the school, a senior Trump administration official, speaking on the condition of anonymity because they were not authorized to speak publicly, described Columbia as a “test case” for using funding to pressure colleges to comply with Trump’s ideology.

> “We’re going to bankrupt these universities,” Leo Terrell, leader of the recently formed Justice Department task force on antisemitism, said on Fox News after the cuts to Columbia were announced.

> “They are targeting private institutions of education and attempting to police and control speech, political expression and thought. And that is truly unprecedented,” said Orion Danjuma, counsel at Protect Democracy, which is representing the unions alongside the law firm Altshuler Berzon. “Columbia is the testing ground for this. It’s a canary in the coal mine.”

> Other changes are not an exact match to the administration’s demands. The university is not abolishing its judicial board that oversees disciplinary cases as requested. But it will remove students from participating and give the provost oversight. It is not putting the Middle East, South Asian and African Studies department in academic receivership for five years as the administration wanted. That academic department will undergo a review by the provost’s office.

> “This was planned,” said Reinhold Martin, president of Columbia’s chapter of the AAUP. “We’ve seen the script. The assault on Columbia is going according to that script.”


As for the Eden piece here are his talking points:

> **Cutting Off Federal Funding** -- Columbia was, perhaps, the worst offender in indulging the pro-Hamas campus radicals. The Education Department’s Office for Civil Rights should initiate a compliance review of every single decision Columbia made. To do that, OCR would need the identities of every single foreign student who supported the protests, actions the Trump administration could deem material support of a terrorist organization. Border czar Tom Homan could then revoke every single one of the foreign protesting students’ visas. If Columbia doesn’t cooperate, McMahon could cut off its research grant funding.



> **Removing Foreign Money from Higher Education** -- And while the Trump administration is looking into Columbia, the Justice Department should thoroughly explore indicting former Columbia President Lee Bollinger for fraud if he, through commission or omission, played a role in Columbia’s submission of inaccurate data to US News and World Report. Bollinger submitted the data to boost Columbia’s rank in the report. Once the true data were reported, Columbia’s rank fell from second to 18th. College presidents regard Bollinger as perhaps the greatest college leader of the 21st century. He should be regarded as the worst. Perhaps the college presidents could learn a valuable lesson from the sight of him in an orange jumpsuit.


> The second target should be the University of California, Los Angeles. UCLA’s ...

> **Enforcing Students for Fair Admissions v. Harvard**; he first step should be forcing Harvard University to comply. Right after the decision was issued, Harvard all but publicly vowed to do everything in its power to violate the spirit of the Supreme Court’s ruling and the 14th Amendment on which it was based. McMahon should initiate a never-ending compliance review to ensure that Harvard follows the law. ... If OCR finds a shred of evidence of racial discrimination, Harvard should lose its Title IV funds. I

> And so many other universities have essentially forfeited the privilege of picking their own professors.

> The University of Washington and UIC should be forced to pay back wages to every single white applicant they declined to hire over a DEI statement and hire as many as would still like to work there. ... However, it could demand all documents and correspondence on hiring in every university faculty department that implemented DEI statements. It could then train an artificial intelligence model to sort through the records and flag likely discrimination. Trump staffers could then send internal, FOIA-able correspondence regarding hot spots of likely discrimination. ... Enterprising trial attorneys could team up with starving adjunct professors, and universities could be liable for hundreds of millions of dollars in settlement fees. That would teach them a painful lesson: Hiring based on race rather than academic merit comes at a very high cost.

> **How Trump can Destroy DEI on Campus** -- it’s all stereotyping. DEI violates the equal protection clause of the 14th Amendment when stereotyping is institutionalized and promoted in an educational institution receiving federal funding — or so the Trump administration should hold and enforce. ... To assure compliance with the 14th Amendment, McMahon could task accreditors with ensuring that students aren’t forced to take DEI-infused courses to graduate. This would, essentially, take Florida’s policy of removing DEI from general education requirements national. When students aren’t forced to take these courses, far fewer will, and the radical Marxists will lose students and influence. ... McMahon could also champion college students’ First Amendment rights by forcing colleges to dismantle their so-called “Bias Reporting Systems.” More than half of colleges encourage students to snitch on each other for saying something “biased,” and students suspected of wrong speak are then hauled in front of a campus tribunal of DEI administrators.

> **Shaking Up College Accreditation** -- Trump suggested he would simply fire all the existing accreditors. That could prove prohibitively difficult. But Trump could easily decimate the worst of them: the Southern Association of Colleges and Schools. ... Trump could also easily expedite the approval of additional accreditors. These accreditors could provide a much more streamlined, cost-effective, outcomes-oriented paradigm than the existing set. They could also specialize in helping to launch new colleges, such as the University of Austin, and even newer ones that no one has dreamed up yet. Musk University? Thiel Technical College?

> **A New Kind of Public College** What about the American Academy? Experts laughed when Trump proposed launching a new, federally backed college. But former President George Washington wanted one. ... At absolute minimum, the American Academy could offer a two-year, high-quality core curriculum, and sympathetic states could mandate their flagship universities accept transfer credit. The Universities of Florida, Georgia, Alabama, and the like could hoover up students who might otherwise have spent far bigger bucks on a private university with a similar prestige level.

> These are just some ideas, and they’re just mine. And, of course, there’s far more the next Trump Education Department should and can do — it just wouldn’t be prudent to broadcast those ideas ahead of time, lest universities take defensive measures.


* Trump Administration Wants to Install Federal Oversight of Columbia University - The Wall Street Journal. (Thanks KB)

[https://www.wsj.com/us-news/education/columbia-consent-decree-trump-federal-funding-2f4c4690?st=nRCE68](https://www.wsj.com/us-news/education/columbia-consent-decree-trump-federal-funding-2f4c4690?st=nRCE68)

> A consent decree would be a major escalation of how the federal government normally resolves education-related civil-rights issues. Typically after federal lawyers investigate and find evidence that civil rights were violated, schools enter voluntary agreements to change their practices. The federal government has little ability to enforce such agreements. The Biden administration entered into such voluntary agreements over antisemitism concerns with Brown University and Rutgers.

> Columbia could fight the move in court; the Justice Department would need to prove that the arrangement is warranted. But a court case could take years, and Columbia would likely lose federal funding in the interim—and might ultimately lose. Opposing the move would also open the school up to required depositions and legal fact-finding, which could keep the school’s campus politics in the spotlight.



## Unbent

* NYTimes: A Playbook for Standing Up to President Trump

[https://www.nytimes.com/2025/04/06/opinion/trump-law-firms-universities.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/06/opinion/trump-law-firms-universities.html?smid=nytcore-ios-share&referringSource=articleShare)


> These institutions do not have to capitulate to Mr. Trump. They have a realistic path to defeating his intimidation.

> Yes, Mr. Trump has adopted a more extreme approach to executive power in his second term. He has won some early policy victories, and he will win more. Nonetheless, he faces real constraints on his power. Indeed, the most likely path to American autocracy depends on not only a power-hungry president but also the voluntary capitulation of a cowed civil society. It depends on the mistaken belief that a president is invincible. Anybody who has dealt with a schoolyard bully should recognize this principle: The illusion of invincibility is often his greatest asset.

* NYTimes: Obama Calls for Universities to Stand Up for Core Values

[https://www.nytimes.com/2025/04/04/us/politics/obama-trump-college-speech.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/04/us/politics/obama-trump-college-speech.html?smid=nytcore-ios-share&referringSource=articleShare)

> Former President Barack Obama, in a campus speech on Thursday, urged universities to resist attacks from the federal government that violate their academic freedom.

> He also said schools and students should engage in self-reflection about speech environments on their campuses.

* Eisgruber signals that Princeton will not make concessions (Thanks KB)

[https://www.dailyprincetonian.com/article/2025/04/princeton-news-adpol-eisgruber-university-concessions-bloomberg-interview](https://www.dailyprincetonian.com/article/2025/04/princeton-news-adpol-eisgruber-university-concessions-bloomberg-interview)

> “We would look at ways to potentially reallocate endowment funding, which would involve very difficult choices, but at the end of the day, what would happen here and elsewhere is that less research would get done, and that would be a bad thing,” he said.

> Eisgruber also emphasized the need for universities to act together in response to governmental funding cuts.

> “I think it’s important for universities to stand shoulder to shoulder as we go forward,” he said.

See also this podcast

[https://podcasts.apple.com/us/podcast/the-university-president-willing-to-fight-trump/id1200361736?i=1000702847509](https://podcasts.apple.com/us/podcast/the-university-president-willing-to-fight-trump/id1200361736?i=1000702847509)

(which was shared by MOO to the mailing list)

* NYTimes: New York Warns Trump It Will Not Comply With Public School D.E.I. Order (Thanks VAC)

[https://www.nytimes.com/2025/04/04/us/politics/new-york-trump-dei-order.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/04/us/politics/new-york-trump-dei-order.html?smid=nytcore-ios-share&referringSource=articleShare)

* Boards Must Fight for Institutional Independence (opinion)

[https://www.insidehighered.com/opinion/views/2025/04/08/boards-must-fight-institutional-independence-opinion](https://www.insidehighered.com/opinion/views/2025/04/08/boards-must-fight-institutional-independence-opinion)

> The future of higher education depends on boards of higher education. The 1966 Statement on Government of Colleges and Universities makes it clear that “The governing board has a special obligation to ensure that the history of the college or university shall serve as a prelude and inspiration to the future … When ignorance or ill will threaten the institution or any part of it, the governing board must be available for support. In grave crises, it will be expected to serve as a champion.”


## Vindictiveness

* NYTimes: List: Who Trump Has Targeted for Retribution

[https://www.nytimes.com/interactive/2025/04/07/us/trump-revenge-list.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/interactive/2025/04/07/us/trump-revenge-list.html?smid=nytcore-ios-share&referringSource=articleShare)

* This Professor Is Committed to Rooting Out DEI From Higher Ed, One Program at a Time

[https://www.chronicle.com/article/the-diversity-detective](https://www.chronicle.com/article/the-diversity-detective)

> In 2020, students, alumni, and law professors tried — unsuccessfully — to get Jacobson fired for a series of blog posts they perceived as creating a hostile learning environment for Black students.

> Jacobson manages four websites, publishes a weekly podcast, has written op-eds in The New York Times, and has been featured on Fox News more than 10 times. He has mobilized dozens of professors from across the country to track on his website criticalrace.org hundreds of social-justice statements, staff diversity trainings, and courses he says indoctrinate students with false ideas about American racism. His site has been cited more than 170 times by mainstream-media outlets.

> The Legal Insurrection Foundation, Jacobson’s nonprofit, collected $1.2 million in revenue from donations and grants in 2023, according to tax filings. It’s not clear who has donated to his cause.

> This past December, Jacobson filed a complaint to OCR against the University of Rhode Island for offering more than 31 scholarships exclusively given to minority students. Mentioned in the complaint was the Miya Brophy-Baermann scholarship, which provides $1,500 to speech-language-pathology students who are racial minorities, men, or the first in their families to attend college.


## Blowback

* NYTimes: America’s Brightest Minds Will Walk Away

[https://www.nytimes.com/2025/04/03/opinion/young-american-scientists.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/03/opinion/young-american-scientists.html?smid=nytcore-ios-share&referringSource=articleShare)

> Many young researchers say they are having to choose between staying in the United States and staying in science. America shouldn’t take scientific progress in medicine, artificial intelligence, energy and more for granted. If the youngest, brightest minds aren’t soon reassured that the United States can support their work — and that scientific inquiry will be protected from political interference — they will walk away.

* NYTimes: Trump Is Selling Jews a Dangerous Lie

[https://www.nytimes.com/2025/04/07/opinion/trump-jewish-antisemitism-wesleyan.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/07/opinion/trump-jewish-antisemitism-wesleyan.html?smid=nytcore-ios-share&referringSource=articleShare)

(Wesleyan President speaks out, again)

> With an administration seemingly determined to do everything, everywhere, all at once, discerning its true priorities can sometimes be challenging. But on this one point, Donald Trump wants no ambiguity: “My promise to Jewish Americans is this,” he said on the campaign trail. “With your vote, I will be your defender, your protector, and I will be the best friend Jewish Americans have ever had in the White House.”

> As the first Jewish president of a formerly Methodist university, I find no comfort in the Trump administration’s embrace of my people, on college campuses or elsewhere. Jew hatred is real, but today’s anti-antisemitism isn’t a legitimate effort to fight it. It’s a cover for a wide range of agendas that have nothing to do with the welfare of Jewish people.

## Coming attractions

* NYTimes: Vandalism of Muslim Prayer Room at N.Y.U. Is Investigated as Hate Crime

[https://www.nytimes.com/2025/04/04/nyregion/vandalism-muslim-prayer-room-nyu.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/04/nyregion/vandalism-muslim-prayer-room-nyu.html?smid=nytcore-ios-share&referringSource=articleShare)

(I have heard about conflicts at such rooms at CUNY)

* Conservatives Seize the Moment to Remake Higher Ed

[https://www.insidehighered.com/news/governance/executive-leadership/2025/04/09/conservatives-seize-moment-remake-higher-ed](https://www.insidehighered.com/news/governance/executive-leadership/2025/04/09/conservatives-seize-moment-remake-higher-ed)

> Pidluzny (DOE deputy chief of staff for policy and programs)  took aim at accreditors as well.

> “Our accountability systems are also badly broken. It’s almost impossible to start a new university today largely because of our accreditation system. And universities that underperform are allowed to go on underperforming with few consequences,” he said.

> (Speculation is rife that an executive order reshaping accreditation will be issued this month.)

>  First, he argued for the need to reorient the enforcement of civil rights on campus, which he said the department has begun to do by holding universities accountable for harassment, discrimination and specifically antisemitism.

> Pidluzny also said that ED must “reorient federal investments away from ideology, back to the advancement of learning and teaching excellence”

> And he argued for a “new vision” of funding universities and holding them accountable.

----

Links: Some of these links are available to CUNY faculty, not all. For example, the Chronicle.com is available through your library, but the link above does not assume you are logged on so.

Any Washington Post link with a shortened url is a  gift article; but there are only so many a month to gift.

I tried to use [https://12ft.io](https://12ft.io) to create links, but that is not very reliable. Ditto with the wayback machine at [https://web.archive.org](https://web.archive.org).
