# Apr 4

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week. Sadly, there is too much to track faithfully and the pace seems to be increasing.

## Days of action

* SSJ Emergency Faculty Townhall (4/3) (Scholars for Social Justice)

[https://us02web.zoom.us/webinar/register/WN_VmK3TVTVRJOae5wUO95EZA#/registration](https://us02web.zoom.us/webinar/register/WN_VmK3TVTVRJOae5wUO95EZA#/registration)


* Kill the cuts (Labor for Higher Education) (4/8) -- thanks Kimora

[https://airtable.com/appMQQqeVbCYe7DJM/pagJwN43Y1R1v0dlL/form](https://airtable.com/appMQQqeVbCYe7DJM/pagJwN43Y1R1v0dlL/form)

[https://www.killthecuts.org/?link_id=2&can_id=127bffecb752852b771f344a52f4e76c&source=email-today-aaup-member-meeting-to-kill-the-cuts-and-defend-higher-ed-3&email_referrer=email_2677743&email_subject=nationwide-higher-ed-protests-on-april-8-join-the-planning-call-tomorrow&&](https://www.killthecuts.org/?link_id=2&can_id=127bffecb752852b771f344a52f4e76c&source=email-today-aaup-member-meeting-to-kill-the-cuts-and-defend-higher-ed-3&email_referrer=email_2677743&email_subject=nationwide-higher-ed-protests-on-april-8-join-the-planning-call-tomorrow&&)

* We are higher ed (Not sure who this is)

[https://www.wearehighered.org/events](https://www.wearehighered.org/events)

(lists some events on 4/5, 4/8, /4/17)

* AAUP: 4/17 fight for higher education

[https://www.dayofactionforhighered.org/](https://www.dayofactionforhighered.org/)


* TEACH-IN: Academic Freedom, Resistance, and Empowerment
Tuesday, April 8, 2025
12:30 – 2:00 PM
Lehman College
Leonard Lief Library
Periodicals Room – Concourse level

FEATURING

Rhyse Weiss, FIRE Foundation for Individual Rights and Expression
Ellen Schrecker, Yeshiva University
Rodrigo Patta Sa Motta, Federal University Minas Gerais, Brazil
Brandon Begarly, Research Administration and Strategy, Lehman College

(Thanks BE)


## Letters

* National Academies letter on Science

[https://docs.google.com/document/d/13gmMJOMsoNKC4U-A8rhJrzu_xhgS51PEfNMPG9Q_cmE/edit?tab=t.0](https://docs.google.com/document/d/13gmMJOMsoNKC4U-A8rhJrzu_xhgS51PEfNMPG9Q_cmE/edit?tab=t.0)

> The undersigned are elected members of the National Academies of Sciences, Engineering, and Medicine, representing some of the nation’s top scientists, engineers, and medical researchers. We are speaking out as individuals.

> The quest for truth—the mission of science—requires that scientists freely explore new questions and report their findings honestly, independent of special interests. The administration is engaging in censorship, destroying this independence.  It is using executive orders and financial threats to manipulate which studies are funded or published, how results are reported, and which data and research findings the public can access. The administration is blocking research on topics it finds objectionable, such as climate change, or that yields results it does not like, on topics ranging from vaccine safety to economic trends.

> We call on the administration to cease its wholesale assault on U.S. science, and we urge the public to join this call.

* Harvard faculty letter

(https://docs.google.com/document/d/1DkzY8JnLyC8-vhPk2-RXfrLKvYbDjJ2ugAQBmCDQIk0/edit?tab=t.0)

* Constitutional law scholars letter on Columbia

[https://www.nybooks.com/online/2025/03/20/a-statement-from-constitutional-law-scholars-on-columbia/](https://www.nybooks.com/online/2025/03/20/a-statement-from-constitutional-law-scholars-on-columbia/)

* UCLA Law Faculty letter

[https://sites.google.com/view/letter-ucla-law-students](https://sites.google.com/view/letter-ucla-law-students)

* "Not in our name" open letter

[https://docs.google.com/document/u/0/d/e/2PACX-1vRt_jMNTlIH7ABX_s7fQFuspYWf_yN2OGzfbrVzhNoO87YWlCyPQzhaq2VcWYDGYvWJRfLq7lNtpnd4/pub?pli=1&urp=gmail_link](https://docs.google.com/document/u/0/d/e/2PACX-1vRt_jMNTlIH7ABX_s7fQFuspYWf_yN2OGzfbrVzhNoO87YWlCyPQzhaq2VcWYDGYvWJRfLq7lNtpnd4/pub?pli=1&urp=gmail_link)

(Thanks VAC)

## Senate resolutions

* Resolution to Establish a Mutual Defense Compact for the Universities of the Big Ten Academic Alliance in Defense of Academic Freedom, Institutional Integrity, and the Research Enterprise

[https://senate.rutgers.edu/wp-content/uploads/2025/03/Resolution-to-Establish-a-Mutual-Defense-Compact-for-the-Universities-of-the-Big-Ten-Academic-Alliance-in-Defense-of-Academic-Freedom-Institutional-Integrity-and-the-Research.pdf](https://senate.rutgers.edu/wp-content/uploads/2025/03/Resolution-to-Establish-a-Mutual-Defense-Compact-for-the-Universities-of-the-Big-Ten-Academic-Alliance-in-Defense-of-Academic-Freedom-Institutional-Integrity-and-the-Research.pdf)

This is the NATO style of defense, when the come for one, they come for all. (Thanks PL)

## CUNY

* Brian Lehrer's show hadCUNY colleagues respond (Thanks BE)


“Trump's targeting of the press is directly affecting us as students of journalism and as active journalists. Our school is, thankfully, making more of an effort to protect us more than Columbia's J School has, but the fear and pressures remain. Our international students are especially impacted because of threats to their VISAs, but it feels like we are all on the frontlines. As a community-focused health and addiction journalist, I feel a growing sense of urgency in the face of impending doom every day. It is scary."

- Willa, Brooklyn, CUNY Newmark Graduate School for Journalism

“Because I work with an historically large Hispanic student population, policies like the attempted recission of DACA has created an anxious atmosphere among many of our undocumented students. Under some of our previous college presidents, our enrollment of students from other countries was pretty good. Now under the Trump administration, changes in visa policies will more than likely discourage international students from enrolling.”

- LaRoi, Queens, Bronx Community College



## FOE/Academic Freedom

* Utah Lawmakers Mandate a University Refocus Gen-Ed Courses on Civics and Viewpoint Diversity

[https://www.chronicle.com/article/utah-lawmakers-mandate-a-university-refocus-gen-ed-courses-on-civics-and-viewpoint-diversity](https://www.chronicle.com/article/utah-lawmakers-mandate-a-university-refocus-gen-ed-courses-on-civics-and-viewpoint-diversity)

> Under a new law, signed by Republican Gov. Spencer Cox on Monday, Utah State University will create an independent academic unit called the “Center for Civic Excellence” that will serve as a new general-education hub. The gen-ed curriculum itself, which faculty will control, must be revised to help students “understand opposing points of view” and ponder “enduring questions of meaning, purpose, and value.” The center is a pilot program that lawmakers want to expand to other Utah colleges in the coming years.

* No Noncitizen Professor at My Institution Can Speak About Politics Ever Again

[https://www.chronicle.com/article/no-noncitizen-professor-at-my-institution-can-speak-about-politics-ever-again](https://www.chronicle.com/article/no-noncitizen-professor-at-my-institution-can-speak-about-politics-ever-again)

> Two months into Trump’s second term, [Jason] Stanley has decided to leave Yale for the University of Toronto. He will follow two prominent colleagues, Timothy Snyder and Marci Shore, both history professors, to Toronto’s Munk School of Global Affairs and Public Policy.

> There’s a complete failure to see that the far right is not trying to have a debate. They’re not trying to have an argument. The ‘institutional neutrality’ stuff, it’s a strategy. There’s no reasonable conversation that’s being had.

> They have a set of strategies to take down our institutions. The main part is to get all these concerned liberals on board, to trick them, because they don’t realize they’re going to come for the institutions no matter what. You want to show to the right wing that you’re a reasonable liberal, you can debate them. But they don’t care.

> I saw mistake after mistake. It’s not going to affect me, but no noncitizen professor at my institution can speak about politics ever again. Half my colleagues are not U.S. citizens. They can never speak about politics again.

* Legal Industry Responses to Fascist Attacks Tracker (Public) - Google Drive


[https://docs.google.com/spreadsheets/d/1J_bcoMqt46L05As7GN4ZqH4j6XKeI-Dm4ytJPRFtrwo/htmlview?gid=287708862#gid=287708862](https://docs.google.com/spreadsheets/d/1J_bcoMqt46L05As7GN4ZqH4j6XKeI-Dm4ytJPRFtrwo/htmlview?gid=287708862#gid=287708862)

(This is an excellent census of firms and reactions. Thanks VAC)

## Funding

* Trump Administration to Review Billions in Grants to Harvard - Bloomberg

[https://www.bloomberg.com/news/articles/2025-03-31/trump-administration-to-review-billions-in-grants-to-harvard](https://www.bloomberg.com/news/articles/2025-03-31/trump-administration-to-review-billions-in-grants-to-harvard)

[https://www.insidehighered.com/news/government/politics-elections/2025/03/31/trump-investigates-harvards-federal-funding](https://www.insidehighered.com/news/government/politics-elections/2025/03/31/trump-investigates-harvards-federal-funding)

[https://www.chronicle.com/article/trump-administration-to-review-9-billion-in-federal-funding-to-harvard](https://www.chronicle.com/article/trump-administration-to-review-9-billion-in-federal-funding-to-harvard)

> The Trump administration has threatened universities’ grants and contracts not only over allegations of antisemitism but also over transgender athletes’ participation in sports. The administration has paused $175 million in federal funding to the University of Pennsylvania amid an investigation into its athletics policies. And it temporarily paused more than $100 million in funding to the University of Maine system after the state’s Democratic governor, Janet Mills, said she would not observe the president’s executive order on transgender athletes, which does not carry the force of law.



* NYTimes: Professors Pushed Harvard to Resist Trump. Now Billions Are on the Line.

[https://www.nytimes.com/2025/04/01/us/republicans-harvard-funding.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/01/us/republicans-harvard-funding.html?smid=nytcore-ios-share&referringSource=articleShare)

(NY Times blaming the victims in the headline...again)


> “The sharks circle when they smell blood in the water,” said Kenneth Roth, a former director of Human Rights Watch and a fellow at Harvard, who wants Harvard to fight better to allow robust debate and academic freedom.

>“That every-man-for-themselves response is about to cost us our democracy,” said Dr. Levitsky, who studies authoritarian regimes.

> As President Trump’s inauguration approached, Harvard hired Ballard Partners, a lobbying firm with deep ties to Mr. Trump. On the first full day of the Trump presidency, the university announced it was adopting a highly debated definition of antisemitism — which labels certain criticisms of Israel, such as calling its existence racist, as antisemitic — a move encouraged by the new administration but slammed by free speech advocates.

* NYTimes: Trump Pauses Dozens of Federal Grants to Princeton

[https://www.nytimes.com/2025/04/01/us/trump-federal-grants-princeton.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/01/us/trump-federal-grants-princeton.html?smid=nytcore-ios-share&referringSource=articleShare)

> The Trump administration moved this week to suspend dozens of federal grants to Princeton University, the fourth Ivy League school that has seen its financial support from Washington reduced or explicitly threatened since March.

> According to Princeton’s most recent financial report, the university received more than $455 million through government grants and contracts during the fiscal year that ended in June 2024. That money accounted for roughly 18 percent of the university’s revenues.


* Who Is on Trump’s Antisemitism Task Force?

[https://www.insidehighered.com/news/government/politics-elections/2025/04/02/who-trumps-antisemitism-task-force?utm_source=Inside+Higher+Ed&utm_campaign=d776e1ff03-DNU_2021_COPY_02&utm_medium=email&utm_term=0_1fcbc04421-d776e1ff03-197464749&mc_cid=d776e1ff03&mc_eid=50634a26f0](https://www.insidehighered.com/news/government/politics-elections/2025/04/02/who-trumps-antisemitism-task-force?utm_source=Inside+Higher+Ed&utm_campaign=d776e1ff03-DNU_2021_COPY_02&utm_medium=email&utm_term=0_1fcbc04421-d776e1ff03-197464749&mc_cid=d776e1ff03&mc_eid=50634a26f0)


* Staff and Funding Cuts at the NEH Loom


[https://www.insidehighered.com/news/government/politics-elections/2025/04/03/staff-and-funding-cuts-neh-loom](https://www.insidehighered.com/news/government/politics-elections/2025/04/03/staff-and-funding-cuts-neh-loom)

> Humanities advocates don’t know exactly how large the cuts to NEH’s approximately 180-person staff or $78.25 million grant budget will be, but they note that “patterns at other agencies” provide a solid hint. The impact on colleges and universities, they say, would be crushing.

* Researchers, Higher Ed Union Fight NIH Grant Terminations

[https://www.insidehighered.com/news/government/science-research-policy/2025/04/02/researchers-higher-ed-union-fight-nih-grant](https://www.insidehighered.com/news/government/science-research-policy/2025/04/02/researchers-higher-ed-union-fight-nih-grant)

> Individual university researchers, a public health advocacy organization and a union representing more than 120,000 higher education workers are suing the National Institutes of Health after the agency terminated more than $2.4 billion in grants it claims support “non-scientific” projects that “no longer” effectuate agency priorities.

* NYTimes: The Next Generation of American Scientists Is Losing Faith

[https://www.nytimes.com/2025/04/03/opinion/young-american-scientists.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/03/opinion/young-american-scientists.html?smid=nytcore-ios-share&referringSource=articleShare)

> Most American scientists understood a second Trump term was unlikely to be friendly to their kind, but few anticipated such a rapid bulldozing. The N.I.H. — the largest public funder of biomedical and behavioral research in the world — announced it would slash funding to universities for overhead, or indirect, costs, which often covers laboratories’ operational needs.  ...The agency has lost nearly one-fourth of its 18,000 employees because of job cuts, buyouts and some employees’ choosing early retirement, according to reporting by NPR.

* NYTimes: I Led Harvard’s Medical School, and I Fear for What’s to Come

[https://www.nytimes.com/2025/04/04/opinion/harvard-medicine-higher-education.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/04/opinion/harvard-medicine-higher-education.html?smid=nytcore-ios-share&referringSource=articleShare)

* NYTimes: Trump Administration Sends Harvard a List of Demands to Protect Federal Funds

[https://www.nytimes.com/2025/04/03/us/politics/trump-harvard-funding-demands.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/03/us/politics/trump-harvard-funding-demands.html?smid=nytcore-ios-share&referringSource=articleShare)

> In both instances, the government asked Harvard and Columbia to impose bans, with few exemptions, on masking.

> The Trump administration also pressured the universities to intensify efforts to hold student groups “accountable,” cease admissions practices based on race, color or national origin and revamp policies on campus protests.

> it said that Harvard’s “programs and departments that fuel antisemitic harassment must be reviewed and necessary changes made to address bias, improve viewpoint diversity, and end ideological capture.”

* NYTimes: Trump Administration Set to Pause $510 Million for Brown University

[https://www.nytimes.com/2025/04/03/us/trump-administration-brown-university-funding-pause.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/03/us/trump-administration-brown-university-funding-pause.html?smid=nytcore-ios-share&referringSource=articleShare)


This adds Brown to the list that includes now: Columbia, Princeton, Harvard, UPenn

## ICE / deportations

* A militant Zionist group threatens activists online with a ‘deport list’

[https://www.washingtonpost.com/technology/2025/03/29/zionist-palestinians-deportations-x/](https://www.washingtonpost.com/technology/2025/03/29/zionist-palestinians-deportations-x/)

> Almost six weeks before federal immigration officials detained Columbia University graduate student Mahmoud Khalil, a group called Betar US said on its X account that it had put the pro-Palestinian activist on “our deport list.”

* ICE Revoking Students’ Immigration Statuses Without Their or the University’s Knowledge


[https://zeteo.com/p/ice-manually-revoking-university-students-residency-status-middle-east](https://zeteo.com/p/ice-manually-revoking-university-students-residency-status-middle-east)

> Three university officials, who were given anonymity so they could speak freely, across the country report that, in recent days, student residency statuses in the Student and Exchange Visitor Information System – SEVIS, a database where residency statuses of foreign students are managed – are being changed without their knowledge.

[This source is not well known, here is a similar article from inside higher ed]

[https://www.insidehighered.com/news/global/international-students-us/2025/04/03/how-trump-wreaking-havoc-student-visa-system](https://www.insidehighered.com/news/global/international-students-us/2025/04/03/how-trump-wreaking-havoc-student-visa-system)

* ICE tracker

[https://public.tableau.com/app/profile/danielleharlow/viz/UnitedStatesDisappearedTracker/Map](https://public.tableau.com/app/profile/danielleharlow/viz/UnitedStatesDisappearedTracker/Map)

(Shared from the FGL list)

* NYTimes: Unmarked Vans. Secret Lists. Public Denunciations. Our Police State Has Arrived.

[https://www.nytimes.com/2025/04/02/opinion/trump-ice-immigrants.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/02/opinion/trump-ice-immigrants.html?smid=nytcore-ios-share&referringSource=articleShare)

> [CUNY Faculty write] When the range of factors that can get a person arrested stretches from political speech to a paperwork error, we are in territory described by the Russian saying, “Give us a person and we’ll find the infraction.”

> The state appears to have outsourced surveillance ... Last Friday, mere minutes after Columbia announced the name of its new interim president, Claire Shipman, an entity that calls itself Documenting Jew Hatred on Campus addressed Shipman on X: “We have identified faculty members” who, the group believes, should be purged. The self-appointed enforcers are vigilant. This, too, is a hallmark of a secret-police state.

* NYTimes: Cornell Student Facing Deportation Felt Drawn to Protest

[https://www.nytimes.com/2025/03/28/us/cornell-student-deportation-protest.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/03/28/us/cornell-student-deportation-protest.html?smid=nytcore-ios-share&referringSource=articleShare)



## Bent

* NYTimes: How Colleges Are Cracking Down on Students Now

[https://www.nytimes.com/2025/03/29/us/universities-students-search-warrants.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/03/29/us/universities-students-search-warrants.html?smid=nytcore-ios-share&referringSource=articleShare)

> After reviewing security footage, the university police obtained warrants to search a student’s car and cellphone. The investigator found photos of the statue covered in paint, and the student was charged with two counts of criminal mischief.

(On April 14th, the board will vote on the use of body-worn cameras by select peace officers with policies related to data retention and data sharing inherited from other policies, and perhaps in need of review.)

* NYTimes: Leaders of Harvard’s Middle Eastern Studies Center Will Leave

[https://www.nytimes.com/2025/03/28/us/leaders-of-harvards-middle-eastern-studies-center-will-leave.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/03/28/us/leaders-of-harvards-middle-eastern-studies-center-will-leave.html?smid=nytcore-ios-share&referringSource=articleShare)

> The university has also been under pressure from Republicans to be more welcoming to conservative viewpoints.

* Montreal doctor says NYU cancelled her presentation

[https://www.ctvnews.ca/montreal/article/climate-of-fear-montreal-doctor-says-nyu-cancelled-her-presentation/](https://www.ctvnews.ca/montreal/article/climate-of-fear-montreal-doctor-says-nyu-cancelled-her-presentation/)

> A couple of the slides in her presentation touched on the casualties in Gaza during the Israel-Hamas war as well as the cuts at the United States Agency for International Development (USAID). Liu said she was told the slides about Gaza “could be perceived as antisemitic” while the USAID section might be perceived as “anti governmental.”

> Liu, who was already in New York when she got the call, offered to make edits to those slides but then three hours later, after some deliberations, she said the university apologized and said they had to cancel.

> A McGill University professor told CTV News last week that he cancelled three visits to the U.S. due to the current political climate and what he believes is the “breakdown of the rule of law” south of the border. He said other colleagues are also avoiding visits to the U.S.

Also reported on at the NY Times:

[https://www.nytimes.com/2025/04/02/nyregion/nyu-doctor-speech-canceled.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/02/nyregion/nyu-doctor-speech-canceled.html?smid=nytcore-ios-share&referringSource=articleShare)

## Unbent

* NYTimes: I’m Cornell’s President. We’re Not Afraid of Debate and Dissent.

[https://www.nytimes.com/2025/03/31/opinion/ideas-universities-controversey-protest.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/03/31/opinion/ideas-universities-controversey-protest.html?smid=nytcore-ios-share&referringSource=articleShare)

> If Cornell were a business, we might have called the event a failure: The news coverage displayed only the disruption, and ignored the rest. Fortunately for our students, Cornell is not a business. We are a university. And universities, despite rapidly escalating political, legal and financial risks, cannot afford to cede the space of public discourse and the free exchange of ideas.

* NYTimes: If Powerful Places Like Harvard Don’t Stand Up to Trump, Who Can?

[https://www.nytimes.com/2025/04/03/opinion/larry-summers-harvard-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/03/opinion/larry-summers-harvard-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> But the Trump administration is not acting in good faith in its purported antisemitism concerns, nor is it following the law in its approach to universities.

> Universities facing those threats should make clear they are willing to negotiate with government officials only over matters covered by statute and through the procedures laid out in the law.

> [Though, not really a faculty senate champion] That will not happen through universities’ usual deliberative processes, which give too much power to faculty members who have political agendas. It will require strong, determined leaders backed by confident and competent trustees.

## Blowback

* Columbia University’s President Resigns - The New York Times

[https://www.nytimes.com/2025/03/28/us/columbia-universitys-president-resigns.html](https://www.nytimes.com/2025/03/28/us/columbia-universitys-president-resigns.html)

* NYTimes: Columbia Campus Occupation Could Have Ended Without Police, Report Says

[https://www.nytimes.com/2025/04/01/nyregion/columbia-protests-police.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/01/nyregion/columbia-protests-police.html?smid=nytcore-ios-share&referringSource=articleShare)

> The new details of the final hours of the occupation of Hamilton Hall on April 30 were among the key revelations of the 335-page report, which was written by a group within the senate, a Columbia policymaking body that includes faculty members, students and administrators, with faculty in the majority. The senate is independent from the administration and has been critical of its protest response.

## Coming attractions

* ‘It reminds you of a fascist state’: Smithsonian Institution braces for Trump rewrite of US history

[https://www.theguardian.com/us-news/2025/mar/30/smithsonian-institution-trump-executive-order](https://www.theguardian.com/us-news/2025/mar/30/smithsonian-institution-trump-executive-order)

> “It is a five-alarm fire for public history, science and education in America,” said Samuel Redman, a history professor at the University of Massachusetts Amherst. “While the Smithsonian has faced crisis moments in the past, it has not been directly attacked in quite this way by the executive branch in its long history. It’s troubling and quite scary.”

> As in so many other ways, however, Trump’s second term is a whole different beast. The president believes there has been a “concerted and widespread effort to rewrite our nation’s history, replacing objective facts with a distorted narrative driven by ideology rather than truth”, according to the White House executive order.

* 400 Books Removed From Naval Academy Library

[https://www.insidehighered.com/news/quick-takes/2025/04/03/400-books-removed-naval-academy-library](https://www.insidehighered.com/news/quick-takes/2025/04/03/400-books-removed-naval-academy-library)

> That list included The Autobiography of Martin Luther King Jr., Einstein on Race and Racism, and a biography of Jackie Robinson. A list of the books that were ultimately removed has not been released.


* NYTimes: ‘What Is Our Country Becoming?’ Four Columnists Map Out Where Trump Is Taking America.

[https://www.nytimes.com/2025/04/04/opinion/trump-ice-detentions.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/04/opinion/trump-ice-detentions.html?smid=nytcore-ios-share&referringSource=articleShare)

(A sad, but informative conversation including CUNY's J-School member)

> Gessen: When universities and individual researchers lose funding because the White House doesn’t like their academic policies or because their grant applications include words like “diversity” (even if it’s “genetic diversity”), we have entered a period when the speech space is rapidly shrinking.

* NYTimes: The Failed Ideas That Drive Elon Musk

[https://www.nytimes.com/2025/04/04/opinion/elon-musk-doge-technocracy.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/04/opinion/elon-musk-doge-technocracy.html?smid=nytcore-ios-share&referringSource=articleShare)

(An origin story on Elon Musk)

> Mr. Musk’s grandfather was also a flamboyant leader of the political movement known as technocracy. Leading technocrats proposed replacing democratically elected officials and civil servants — indeed, all of government — with an army of scientists and engineers under what they called a technate.

:::

Links: Some of these links are available to CUNY faculty, not all. For example, the Chronicle.com is available through your library, but the link above does not assume you are logged on so.

Any Washington Post link with a shortened url is a  gift article; but there are only so many a month to gift.

I tried to use [https://12ft.io](https://12ft.io) to create links, but that is not very reliable. Ditto with the wayback machine at [https://web.archive.org](https://web.archive.org).
