# Apr 18

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

## Letters/Statements

* Queensborough Community College joint statement: CALL FOR ACTION Affirming Academic Freedom and Access to Higher Education

> We encourage our colleagues and our administration to continue along with us :
> 1. To refuse to comply with illegal governmental overreach that undermines a university’s academic decision-making and self-governance. ...

* A statement from the Board of Directors of the American Academy of Arts & Sciences. (Thanks VAC)

[https://www.amacad.org/news/board-statement-values-april-2025](https://www.amacad.org/news/board-statement-values-april-2025)

> We oppose reckless funding cuts and restrictions that imperil the research enterprise of our universities, hospitals, and laboratories, which contribute enormously to our prosperity, health, and national security. We condemn efforts to censor our scholarly and cultural institutions, to curtail freedom of the press, and to purge inquiry or ideas that challenge prevailing policies. We vigorously support the independence of the judiciary and the legal profession, and oppose actions and threats intended to erode that independence and, in turn, the rule of law.

* University protests blast Trump’s attacks on funding, speech and international students

[https://apnews.com/article/university-protests-trump-cuts-international-students-cc4313738823ac84de96abfdd35a6f71](https://apnews.com/article/university-protests-trump-cuts-international-students-cc4313738823ac84de96abfdd35a6f71)

## Freedom of Speech

* Under Trump, freedom of speech in universities takes on a new meaning (From BE)

[https://www.npr.org/2025/04/11/nx-s1-5349477/under-trump-freedom-of-speech-in-universities-takes-on-a-new-meaning](https://www.npr.org/2025/04/11/nx-s1-5349477/under-trump-freedom-of-speech-in-universities-takes-on-a-new-meaning)



> “A professor who's had to keep his views on transgender rights secret under Biden now shares his opinions freely without fear of retaliation, college Republicans from UC Berkeley describe how the election of President Trump has cleared a path for them to speak their minds more freely, and Ibram Kendi, who has dedicated his life work to race, explains what the war against DEI means for his area of study.”

* Palestinian Columbia student detained by ICE at citizenship interview

[https://www.washingtonpost.com/immigration/2025/04/14/columbia-mohsen-mahdawi-arrested-ice/](https://www.washingtonpost.com/immigration/2025/04/14/columbia-mohsen-mahdawi-arrested-ice/)


## Funding cuts

* DOGE takes over federal grants website, wresting control of billions

[https://www.washingtonpost.com/politics/2025/04/11/doge-controls-federal-grant-postings/](https://www.washingtonpost.com/politics/2025/04/11/doge-controls-federal-grant-postings/)

> But a DOGE engineer recently deleted many federal officials’ permissions to post grant opportunities, without informing them that their permissions had been removed, the people said. Now the responsibility of posting these grant opportunities is poised to rest with DOGE — and if its employees delay those postings or stop them altogether, “it could effectively shut down federal-grant making,” said one federal official who spoke on the condition of anonymity to describe internal operations.

* Trump administration to pull Maine K-12 funding over trans athletes dispute

[https://www.washingtonpost.com/politics/2025/04/11/maine-education-trump-janet-mills/](https://www.washingtonpost.com/politics/2025/04/11/maine-education-trump-janet-mills/)

Not higher ed related, but shows the willingness to break everything:

> The move prompted a swift response from the Trump administration’s Department of Education, which promptly said it would cut all federal K-12 funding to Maine and refer its investigation into the state’s education agency to the Justice Department “for further enforcement action.”



* Energy Department reduces funding for grants to colleges and universities

[https://www.washingtonpost.com/education/2025/04/12/trump-cuts-department-of-energy/](https://www.washingtonpost.com/education/2025/04/12/trump-cuts-department-of-energy/)

(Same story, cut overhead...)

* NYTimes: What Is Actually the Point of Treating the N.I.H. Like This?

[https://www.nytimes.com/2025/04/11/opinion/nih-scientists-staffing-cuts.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/11/opinion/nih-scientists-staffing-cuts.html?smid=nytcore-ios-share&referringSource=articleShare)

> So when it’s all over, if the crown jewel of biomedical research — the enterprise that gave us the human genome sequence, Covid vaccines and treatments for cancer and H.I.V. and obesity — has been destroyed, what will have been the point?

* NIH Funding Opportunities (this week, from MP)

> (none)

As in nothing being offered for funding. The cherry on top is notice of

> The purpose of this notice is to announce that effective immediately, NOT-OD-24-117 "Notice of Information: Research Opportunities Centering the Health of Women Across the HIV Research Continuum", is expired.

(cf. [https://grants.nih.gov/grants/guide/WeeklyIndexMobile.cfm?WeekEnding=2025-04-11](https://grants.nih.gov/grants/guide/WeeklyIndexMobile.cfm?WeekEnding=2025-04-11))

* These 77 Colleges Have the Most to Lose From Trump’s Cuts

[https://www.chronicle.com/article/these-77-colleges-have-the-most-to-lose-from-trumps-cuts](https://www.chronicle.com/article/these-77-colleges-have-the-most-to-lose-from-trumps-cuts)

(CUNY not here, though I'd guess it would be if treated as a system.)

> These cuts will have lasting effects on these institutions and will reverberate through society. They will hamper the investments these colleges make in the leaders of our next generation. Advances in medicine, science, and technology will slow. The negative effect on economic activity will be substantial. And the economic opportunity that these institutions offer to lower-income students will be limited. None of this is in our nation’s interest. Why are we doing this?

* NYTimes: What to Know as Trump Freezes Federal Funds for Harvard and Other Universities

[https://www.nytimes.com/2025/04/15/us/politics/trump-university-funding-harvard.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/15/us/politics/trump-university-funding-harvard.html?smid=nytcore-ios-share&referringSource=articleShare)


> “If Harvard had not taken this stand,” Ted Mitchell, the president of the American Council of Education, told The New York Times, “it would have been nearly impossible for other institutions to do so.”

* The president wants to balance U.S. trade deficits? He can’t do it without this industry he hates.

[https://wapo.st/4jm94vB](https://wapo.st/4jm94vB)

> President Donald Trump says he wants to reduce our trade deficit. Yet he’s destroying one of our winningest exports: higher education.

> Colleges and universities are among America’s most competitive international exporters. In dollar terms, last year, the United States sold more educational services to the rest of the world than it sold in natural gas and coal combined.

(Thanks BE for this!)

* We have laws in this country

[https://www.msnbc.com/katy-tur/watch/-we-have-laws-in-this-country-harvard-law-professor-reacts-to-trump-admin-s-funding-freeze-237481541636](https://www.msnbc.com/katy-tur/watch/-we-have-laws-in-this-country-harvard-law-professor-reacts-to-trump-admin-s-funding-freeze-237481541636)

> Harvard Law School Professor Nikolas Bowie and MSNBC Legal Correspondent Lisa Rubin join Katy Tur to break down the importance of Harvard standing up to the Trump administration.

(Thanks *again* to BE for this!)

* NYTimes: Leading Nutrition Scientist Departs N.I.H., Citing Censorship

[https://www.nytimes.com/2025/04/16/well/kevin-hall-nutrition-retirement-nih-censorship-rfk-maha.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/16/well/kevin-hall-nutrition-retirement-nih-censorship-rfk-maha.html?smid=nytcore-ios-share&referringSource=articleShare)

> “We experienced what amounts to censorship and controlling of the reporting of our science,” Dr. Hall said, adding that he was worried that if he stayed, officials might also interfere with the design and execution of his studies. “That would make me hate my job every day,” he added.

* Internal budget document reveals extent of Trump health program cuts - The Washington Post

[https://www.washingtonpost.com/health/2025/04/16/hhs-budget-cut-trump/](https://www.washingtonpost.com/health/2025/04/16/hhs-budget-cut-trump/)

> The proposal would reduce the more than $47 billion budget of the NIH to $27 billion — a roughly 40 percent cut. It would consolidate NIH’s 27 institutes and centers into just eight. Some of its institutes and centers would be eliminated, including the National Institute on Minority Health and Health Disparities and the National Institute of Nursing Research.

> The proposal would cut the CDC’s budget by about 44 percent, from $9.2 billion to about $5.2 billion, and would eliminate all of the agency’s chronic disease programs and domestic HIV work. The chronic disease programs being eliminated include work on heart disease, obesity, diabetes and smoking cessation.

* What to Know About Trump’s Funding Threats to Colleges

[https://www.insidehighered.com/news/government/politics-elections/2025/04/18/what-know-about-trumps-funding-threats-colleges](https://www.insidehighered.com/news/government/politics-elections/2025/04/18/what-know-about-trumps-funding-threats-colleges)

> The cuts don’t follow any typical investigative process and sometimes lack clear explanations or legal justifications. And such an aggressive ad hoc strategy is one that that many higher education lawyers, policy analysts and administrators say could reshape postsecondary education for years to come.


## Visas

* Some foreign students fear speaking out as visa cancellations rise

[https://www.washingtonpost.com/education/2025/04/12/international-students-visas-revoke-fear/](https://www.washingtonpost.com/education/2025/04/12/international-students-visas-revoke-fear/)

A rush to delete social media...

* NYTimes: A Columbia Activist Sought Middle Ground on Gaza. The U.S. Detained Him.

[https://www.nytimes.com/2025/04/16/nyregion/columbia-activist-mahdawi-ice-palestinian.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/16/nyregion/columbia-activist-mahdawi-ice-palestinian.html?smid=nytcore-ios-share&referringSource=articleShare)

> “This is a person who stands for precisely the values we want to raise up at this moment of such starkness and such blindness and such division and polarization,” said Mr. Myers, who formerly led the New Israel Fund, a philanthropic organization for progressive Jewish people. “This person constitutes a bridge, and we’ve torn that bridge down instead of embracing it.”


## Behind the curtain

* A new task force formed to combat antisemitism on campus is rattling university administrators by using funding threats to force broader changes.

[https://www.wsj.com/us-news/education/anti-semitism-task-force-who-247c234e?st=WjSewF&reflink=article_gmail_share](https://www.wsj.com/us-news/education/anti-semitism-task-force-who-247c234e?st=WjSewF&reflink=article_gmail_share)

Another article detailing the small group of people chosen to weaponize behaviours

> We are going to choke off the money to schools that aid the Marxist assault on our American heritage and on Western civilization itself


## Unbent

* NYTimes: This Is How Universities Can Escape Trump’s Trap, If They Dare

[https://www.nytimes.com/2025/04/14/opinion/trump-higher-education.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/14/opinion/trump-higher-education.html?smid=nytcore-ios-share&referringSource=articleShare)


> Slashing and burning its way through the National Institutes of Health, the National Endowment for the Humanities, the Wilson Center, the United States Institute of Peace, the Smithsonian, and others, the administration has shown that it considers knowledge production worthless. In the rare areas where the president — or perhaps Elon Musk — may see value in research, the emergent mafia state is almost certain to distribute funds to its friends. One shudders to think what universities would have to do to fit themselves into that category.

> So this is my radical proposal for universities: Act like universities, not like businesses. Spend your endowments. Accept more, not fewer students. Open up your campuses and expand your reach not by buying real estate but by bringing education to communities. Create a base. Become a movement.

* NYTimes: Trump’s Threats Force Institutions to Choose: Cut a Deal or Fight Back

[https://www.nytimes.com/2025/04/16/us/politics/trump-universities-law-firms-deals.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/16/us/politics/trump-universities-law-firms-deals.html?smid=nytcore-ios-share&referringSource=articleShare)

> At Harvard, hundreds, including Mr. Bowie, rallied to call on the school to stand up to the Trump administration’s demands, while hundreds of faculty members signed a letter urging Harvard to condemn Mr. Trump’s attempt to remake higher education.

> At Yale, nearly 1,000 faculty members signed a letter calling on their leaders to resist Mr. Trump’s demands. And the president of M.I.T. spoke out against the Trump administration’s treatment of its international students.

* NYTimes: It’s Time to Protect America From America’s President

[https://www.nytimes.com/2025/04/16/opinion/trump-harvard-abrego-garcia.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/16/opinion/trump-harvard-abrego-garcia.html?smid=nytcore-ios-share&referringSource=articleShare)

< All this illuminates an administration that is not only authoritarian but also reckless; this is vandalism of the American project. That is why this moment is a test of our ability to step up and protect our national greatness from our national leader.

* NYTimes: Time for a Civic Uprising

[https://www.nytimes.com/2025/04/17/opinion/trump-harvard-law-firms.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/17/opinion/trump-harvard-law-firms.html?smid=nytcore-ios-share&referringSource=articleShare)

David Brooks drops the partisan digs and gets right at it:

> Trumpism is threatening all of that. It is primarily about the acquisition of power — power for its own sake. It is a multifront assault to make the earth a playground for ruthless men, so of course any institutions that might restrain power must be weakened or destroyed. Trumpism is about ego, appetite and acquisitiveness and is driven by a primal aversion to the higher elements of the human spirit — learning, compassion, scientific wonder, the pursuit of justice.

> These are not separate battles. This is a single effort to undo the parts of the civilizational order that might restrain Trump’s acquisition of power. And it will take a concerted response to beat it back.

> Slowly, many of us are realizing that we need to band together. But even these efforts are insular and fragmented.

> Let’s take the universities. I’ve been privileged to teach at American universities off and on for nearly 30 years and I get to visit a dozen or two others every year. These are the crown jewels of American life. They are hubs of scientific and entrepreneurial innovation. In a million ways, the scholars at universities help us understand ourselves and our world.


### Harvard

* Harvard’s President Says the University Will Not Comply With Trump’s Demands

[https://www.chronicle.com/article/harvards-president-says-the-university-will-not-comply-with-trumps-demands](https://www.chronicle.com/article/harvards-president-says-the-university-will-not-comply-with-trumps-demands)

> Garber said that the directives violate Harvard’s First Amendment rights, exceed the federal government’s Title VI authority, and threaten the university’s values.

* The American Association of University Professors and its chapter at Harvard University sued the Trump administration Friday in an attempt to block the administration’s policy changes and review of nearly $9 billion in federal funding.

[https://actionnetwork.org/user_files/user_files/000/122/747/original/File_Stamped_Complaint.pdf](https://actionnetwork.org/user_files/user_files/000/122/747/original/File_Stamped_Complaint.pdf)

* NYTimes: Trump Administration Will Freeze $2 Billion After Harvard Refuses Demands

[https://www.nytimes.com/2025/04/14/us/harvard-trump-reject-demands.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/14/us/harvard-trump-reject-demands.html?smid=nytcore-ios-share&referringSource=articleShare)

* Stanford president and provost back Harvard in funding fight

[https://stanforddaily.com/2025/04/15/levin-martinez-back-harvard-president/](https://stanforddaily.com/2025/04/15/levin-martinez-back-harvard-president/)

* Yale too

[https://thehill.com/homenews/education/5250248-harvard-receives-support-from-yale-stanford/](https://thehill.com/homenews/education/5250248-harvard-receives-support-from-yale-stanford/)

* NYTimes: Why Harvard Decided to Fight Trump

[https://www.nytimes.com/2025/04/15/us/why-harvard-resisted-trumps-demands.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/15/us/why-harvard-resisted-trumps-demands.html?smid=nytcore-ios-share&referringSource=articleShare)

> “No government — regardless of which party is in power — should dictate what private universities can teach, whom they can admit and hire, and which areas of study and inquiry they can pursue,” Harvard’s president, Alan M. Garber, wrote in an open letter on Monday.

* By saying ‘no’ to Trump, Harvard saves its soul

[https://www.washingtonpost.com/opinions/2025/04/15/harvard-trump-grants-david-ignatius/](https://www.washingtonpost.com/opinions/2025/04/15/harvard-trump-grants-david-ignatius/)

> What’s really going on in this battle for Harvard’s soul? Martin Wolf of the Financial Times argued recently that Trump, like Mao Zedong in China more than 50 years ago, has embarked on a “cultural revolution” that seeks “to overthrow the bureaucratic and cultural elites” that are anchored in the nation’s great universities.

> Liberal professors aren’t yet forced to wear dunce caps or work in “reeducation camps” in farms and factories. Maybe that’s next. For the moment, a salute to “Fair Harvard,” and how it’s living the motto, veritas.

* IRS making plans to rescind Harvard’s tax-exempt status | CNN Politics

[https://www.cnn.com/2025/04/16/politics/irs-harvard-tax-exempt-status/index.html](https://www.cnn.com/2025/04/16/politics/irs-harvard-tax-exempt-status/index.html)

> Tax Exempt Status is totally contingent on acting in the PUBLIC INTEREST!” Trump posted on Truth Social on Tuesday.

(Ed. the AAUP says in 1940 "Institutions of higher education are conducted for the common good...")

Also

[https://www.washingtonpost.com/business/2025/04/16/trump-harvard-tax-exempt-irs/](https://www.washingtonpost.com/business/2025/04/16/trump-harvard-tax-exempt-irs/)

* NYTimes: With Harvard Threat, Trump Tries to Bend the I.R.S. to His Will

[https://www.nytimes.com/2025/04/18/us/politics/trump-irs.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/18/us/politics/trump-irs.html?smid=nytcore-ios-share&referringSource=articleShare)


* Donald Trump Tries to Run Harvard


[https://www.wsj.com/opinion/donald-trump-harvard-funding-conditions-constitution-congress-c26040f8?st=7rCN8r&reflink=article_gmail_share](https://www.wsj.com/opinion/donald-trump-harvard-funding-conditions-constitution-congress-c26040f8?st=7rCN8r&reflink=article_gmail_share)

> The Supreme Court has repeatedly held that the government may not use federal benefits or funds to coerce parties to surrender their constitutional rights. This is what the Administration is doing by demanding Harvard accede to “viewpoint diversity.”

> The Administration is also overstepping its authority by imposing sweeping conditions on funds that weren’t spelled out by Congress. The Justices held in Cummings (2022) that “if Congress intends to impose a condition on the grant of federal moneys, it must do so unambiguously” to ensure the recipient “voluntarily and knowingly accept[ed] the terms.”


* What Harvard Has Set the Stage For

[https://www.nytimes.com/2025/04/16/opinion/harvard-university-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/16/opinion/harvard-university-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

(Thanks EI)

> With these words, Harvard became the first university to officially resist the administration’s abusive intimidation, and it is urgent that it not be the only one. Its actions, supported in recent weeks in statements by other academic leaders, including the presidents of Princeton and Wesleyan, light the way forward on a vital path to fighting President Trump’s war on the independence of higher education.

> If universities accept Mr. Trump’s terms, on the other hand, the consequence would be far greater, undermining the very purpose of an independent institution.

* Harvard Had No Choice

[https://www-chronicle-com.csi.ezproxy.cuny.edu/article/harvard-had-no-choice](https://www-chronicle-com.csi.ezproxy.cuny.edu/article/harvard-had-no-choice)

> Thus, its decision deserves either praise for courage or condemnation for foolhardiness. I choose praise — in no small part because, as we have already seen with Columbia, capitulation to President Trump’s demands brings only more demands. There’s no point in selling your soul if all you receive in exchange is a worthless IOU.

>  The anti-intellectual ideologues (no, that’s not an oxymoron) running education policy within and adjacent to the White House do not wish to reform higher education; they want to break it.

### Columbia

* NYTimes: If You’re Boycotting Columbia, Your Priorities Are All Wrong

[https://www.nytimes.com/2025/04/16/opinion/columbia-university-boycott-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/16/opinion/columbia-university-boycott-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> Then came the circular firing squad. By mid-April, 2,000 people and more than 75 organizations, most of them faculty groups, had signed onto a boycott of our events, and said they would refuse to work with Columbia scholars, like myself, a vice dean, who hold administrative positions.

> One of the main organizers of the boycott, the City University of New York anthropologist Gary Wilder, has struggled to explain this strange form of solidarity.

But

> Columbia would not allow any government to deny professors their rightful role in personnel decisions or to dictate the content of our curricula. Nor would we collaborate with government agents intent on deporting our students and faculty members simply because they exercised their First Amendment rights. At no point did our leadership concede any of these essential principles, which is surely why Columbia has been under Department of Justice investigation “for harboring and concealing illegal aliens on its campus.”

> Now that Harvard University has decided to defy the Trump administration, the stage is set for an epic struggle, one that has already defied the expectations of cynics on both sides. After being presented with new demands, Columbia is refusing to comply. No thanks to our fair-weather friends, our acting president, Claire Shipman, has vowed to reject any agreement in which “the government dictates what we teach, research or who we hire” as well as one that would “require us to relinquish our independence and autonomy as an educational institution.” Columbia alumni are rallying in support.

> The greatness of American universities is at risk because anti-intellectuals are undermining the foundation of academic excellence: the ability of teachers and researchers to work without political micromanagement in the pursuit of truth, even when these truths are unpopular. Colleges and universities should join a mutual defense pact, as faculty members at several universities, including Rutgers and Indiana University have proposed. If we speak with one voice, we can better articulate the essential importance of universities to the American way of life.

> We have now seen that the Trump administration manages the economy with the same expertise and competence it manages higher education, and as a result we might begin to rally the American people. If, instead, academics choose to boycott colleagues rather than stand with them, they become accomplices in the very assault on academic freedom they wish to oppose.



### Cornell

* Cornell Sues DOE for ‘Unlawful’ Cuts to Indirect Costs for Research Grants - The Cornell Daily Sun

[https://www.cornellsun.com/article/2025/04/breaking-cornell-sues-doe-following-1-billion-funding-freeze](https://www.cornellsun.com/article/2025/04/breaking-cornell-sues-doe-following-1-billion-funding-freeze)


* ACE and others file lawsuite to prevent DOE cuts

[https://storage.courtlistener.com/recap/gov.uscourts.mad.283318/gov.uscourts.mad.283318.1.0.pdf](https://storage.courtlistener.com/recap/gov.uscourts.mad.283318/gov.uscourts.mad.283318.1.0.pdf)

### Brown

* Brown Takes Out $300 Million Loan

[https://www.insidehighered.com/news/quick-takes/2025/04/17/brown-takes-out-300-million-loan](https://www.insidehighered.com/news/quick-takes/2025/04/17/brown-takes-out-300-million-loan)

> Both Harvard University and Princeton University announced in recent weeks that they were issuing bonds. Harvard, which is issuing $750 million in bonds, told Inside Higher Ed the move was about “contingency planning for a range of financial circumstances.”


## Coming attractions

* College financial aid hit with glitches, delays due to federal staffing cuts

[https://www.washingtonpost.com/education/2025/04/14/student-loans-financial-aid-glitches-education-department-layoffs/](https://www.washingtonpost.com/education/2025/04/14/student-loans-financial-aid-glitches-education-department-layoffs/)

* America and Its Universities Need a New Social Contract

[https://www.theatlantic.com/ideas/archive/2025/04/stem-academia-universities-citizenship-civics/682384/?gift=yCYg0MdUGpnvquf3En3lpoYhve6SrZ9EDluTXteFkaI&utm_source=copy-link&utm_medium=social&utm_campaign=share](https://www.theatlantic.com/ideas/archive/2025/04/stem-academia-universities-citizenship-civics/682384/?gift=yCYg0MdUGpnvquf3En3lpoYhve6SrZ9EDluTXteFkaI&utm_source=copy-link&utm_medium=social&utm_campaign=share)

(Thanks BE for the gift link)

> Since taking office, the Trump administration has been working to dismantle the global order and the nation’s core institutions, including its cultural ones, to strip them of their power. The future of the nation’s universities is very much at stake. This is not a challenge that can be met with purely defensive tactics. We must do what should have been done long ago: find our way to a new social contract between universities and the American people.

*  This is a good analysis of the nefarious political and ideological sources of the current attacks on higher education, writ-large (Thanks DM)

[https://www.insidehighered.com/news/government/politics-elections/2025/04/15/how-trumps-early-actions-compare-project-2025?utm_source=Inside+Higher+Ed&utm_campaign=af0a9e0e99-DNU_2021_COPY_03&utm_medium=email&utm_term=0_1fcbc04421-af0a9e0e99-197389885&mc_cid=af0a9e0e99](https://www.insidehighered.com/news/government/politics-elections/2025/04/15/how-trumps-early-actions-compare-project-2025?utm_source=Inside+Higher+Ed&utm_campaign=af0a9e0e99-DNU_2021_COPY_03&utm_medium=email&utm_term=0_1fcbc04421-af0a9e0e99-197389885&mc_cid=af0a9e0e99)

 Bottom line: it’s one of the most transparent attempts to deregulate, privatize, and commodify higher learning.

* Webb telescope detects a possible signature of life on a distant world

[https://www.washingtonpost.com/science/2025/04/16/alien-life-exoplanet-webb-telescope/](https://www.washingtonpost.com/science/2025/04/16/alien-life-exoplanet-webb-telescope/)

(A golden visa for only 0.05 Galactic Credit Standard)

* Women, minorities fired in purge of NIH science review boards

[https://www.washingtonpost.com/science/2025/04/16/women-and-minorities-fired-nih-board-science/](https://www.washingtonpost.com/science/2025/04/16/women-and-minorities-fired-nih-board-science/)

> Thirty-eight of 43 experts cut last month from the boards that review the science and research that happens in laboratories at the National Institutes of Health are female, Black or Hispanic, according to an analysis by the chairs of a dozen of the boards

> "So I can only assume, based on the demographics, that it looks like they targeted women and people of color.”

* At Least 10 Florida Universities Have Signed ICE Agreements

[https://www.insidehighered.com/news/government/state-policy/2025/04/16/least-10-florida-universities-have-signed-ice-agreements](https://www.insidehighered.com/news/government/state-policy/2025/04/16/least-10-florida-universities-have-signed-ice-agreements)

> At least 10 Florida public universities have struck agreements with the federal government authorizing campus police to question and detain undocumented immigrants.

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library.
