# Aug 15

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

Thanks to MP, JC, BE, ... for sharing links and notes.

## Letters

* University of California: Stand Up For Our Values [UCLA Faculty Association]

[https://tinyurl.com/ucstandup](https://tinyurl.com/ucstandup)

(Thanks JC)

> We demand in the strongest possible terms that the University of  California demonstrate our strength as the world’s largest university  system and reject the malicious demands of the Trump administration. We demand that the UC name these demands as what they are: efforts to erode the strength of American higher education. Each university that falters legitimates the Trump administration’s attacks on all of our institutions of higher education and we must stand up now. To protect  our democracy we must protect our universities. Only when academic  workers and the community as a whole collectively organize can we fight back against the threat to our campuses and our democracy.

* Tell the Supreme Court: No Stay. Hands off NIH

[https://scienceandfreedomalliance.substack.com/p/tell-the-supreme-court-no-stay-hands](https://scienceandfreedomalliance.substack.com/p/tell-the-supreme-court-no-stay-hands)

> What can we do now? The Supreme Court responds to public pressure. We can speak out in every venue available. Tell the Supreme Court the public is watching. Let’s demand: No Stay. And demand the Court and Trump administration keep their Hands Off NIH.


## Alliances

## Statements

## Protests

## Zoom calls

## Op eds

## How best to describe the times we are in

* The Harvard-Trained Lawyer Behind Trump’s Fight Against Top Universities

[https://www.nytimes.com/2025/08/11/us/politics/harvard-trump-may-mailman.html?unlocked_article_code=1.dU8.vteF.QtBACD](https://www.nytimes.com/2025/08/11/us/politics/harvard-trump-may-mailman.html?unlocked_article_code=1.dU8.vteF.QtBACD)

(Thanks VAC. Does her training somehow give her a pass?)

> Ms. Mailman, a 37-year-old Harvard-trained lawyer, is the most important, least-known person behind the administration’s relentless pursuit of the nation’s premier universities. The extraordinary effort has found seemingly endless ways to pressure schools into submission, including federal funding, student visas and civil rights investigations.

> The aggressive tactics could have far-reaching implications for the future of academic freedom, the admissions practices at the most competitive colleges and the global reputations for some of the crown jewels of the nation’s university system.

> Ms. Mailman wrote the executive orders Mr. Trump signed on his first day in office that redefined the federal government’s stance on sex to acknowledge only two genders and dismantled policies aimed at promoting diversity, equity and inclusion.

> She had a direct hand in the effort to prevent Harvard from enrolling international students, which unnerved the university’s leadership and student body and which a court has temporarily halted.

> “If you normalize the use of federal power like this, then academic freedom is just a memory and universities become political footballs and no longer useful instruments in the search for truth,” said Adam Goldstein, the vice president of strategic initiatives at the Foundation for Individual Rights and Expression, a free speech group.

> Ms. Mailman’s work with the group [Independent Women’s Law Center], where she is returning after leaving the White House, landed her on the “hate and extremism” section of the website for GLAAD, one of the country’s leading L.G.B.T.Q. advocacy groups.

* The Elite-University Presidents Who Despise One Another Inside the civil war between the Ivy League and the South

[https://www.theatlantic.com/ideas/archive/2025/08/trump-university-presidents/683803/?gift=h1dV60W2A3Fojj_roXuAogWNo-lbRL6rAgNsbk4Qj-o&utm_source=copy-link&utm_medium=social&utm_campaign=share](https://www.theatlantic.com/ideas/archive/2025/08/trump-university-presidents/683803/?gift=h1dV60W2A3Fojj_roXuAogWNo-lbRL6rAgNsbk4Qj-o&utm_source=copy-link&utm_medium=social&utm_campaign=share)

(Thanks BE!)

> Princeton has largely escaped the president’s wrath, even though Eisgruber has become a leader of what you might call the academic resistance: a group of university leaders who believe that Trump’s criticisms of the sector are a pretext for eliminating academic freedom. And, in part because Eisgruber is one of the longest-serving Ivy League presidents and has a supportive board behind him, he has become vocally, if diplomatically, critical of other university presidents who he believes go too far to meet Trump’s demands.

> Those other university officials—led by Washington University’s Andrew Martin and Vanderbilt’s Daniel Diermeier, the chancellors who sparred with Eisgruber on the panel—make up the reformist camp. They accept some of Trump’s complaints and believe that the best path forward for higher education is to publicly commit to a kind of voluntary, modified de-wokeification. They argue that some campuses (in, say, Cambridge and Morningside Heights) and departments (much of the humanities) have leaned too far into leftist ideology and allowed anti-Semitism to fester under the guise of protesting Israeli policies. They want the American public to know that they are different from the Ivies. And they think that higher education needs new representation if it’s going to regain the country’s trust.


> The divide between the reformer and resistance camps is not merely about strategy; it’s about the nature of the threat to higher education. Members of the resistance group conceive of Trump as a unique—and ultimately passing—problem: If they can survive his presidency, they’ll be safe. This seems to have led them to resist making deep, lasting changes.

> The reformers think the resistance presidents are delusional for believing that their problems will go away when Trump does. They see the president’s attacks as symptomatic of a larger issue. Polling shows that confidence in American higher education has cratered in recent years, especially among Republicans. “The fundamental fact here is that we have never been in worse shape in my lifetime,” Diermeier told me. The reformer presidents, who tend to be in red or purple states, think the resistance leaders are trapped in liberal echo chambers. “It’s clear that the bipartisan support has eroded,” Martin told me. “It’s really misguided to think that what’s happening in higher education is a blip and that we’re going to return to where we were before.”


## Shared governance

* Texas State U System Lets Law End Faculty Senates, for Now

[https://www.insidehighered.com/news/quick-takes/2025/08/11/texas-state-u-system-lets-law-end-faculty-senates-now](https://www.insidehighered.com/news/quick-takes/2025/08/11/texas-state-u-system-lets-law-end-faculty-senates-now)

> Faculty senates across the seven Texas State University system institutions will dissolve Sept. 1, but the system’s Board of Regents plans to approve new ones, a system spokesperson says.

> Under a new Texas law, only a public college or university’s governing board, such as the Board of Regents, can create a faculty council or senate. If a board keeps one, Senate Bill 37 further says the university president gets to pick the “presiding officer, associate presiding officer, and secretary” and prescribe how the senate conducts meetings.

> Also, unless the board decides otherwise, faculty senates must shrink to no more than 60 members. Those 60 must include at least two representatives from each of the colleges and schools that comprise the university—including what the law describes vaguely as “one member appointed by the president or chief executive officer of the institution,” with the rest elected by the faculty of the particular school or college. This could mean half of a senate would be chosen by the president, barring an exemption by the board.

## Academic freedom

* Academic Freedom under attack:

[https://www.insidehighered.com/opinion/views/2025/08/12/shocking-cancellation-special-journal-issue-opinion](https://www.insidehighered.com/opinion/views/2025/08/12/shocking-cancellation-special-journal-issue-opinion)

(Thanks to BE for this)

> The Harvard Educational Review was set to release a special issue this summer focusing on education and Palestine. The topic, commissioned in early 2024, was timely in the wake of Israel’s onslaught on Gaza, which rights groups and other experts have concluded is a genocide, and aligned with the journal’s commitment to publishing research that tackles the most pressing issues facing education. The articles had been accepted, edited and contracted. The special issue had already been promoted at major education conferences and on the back cover of the spring issue of the HER. But suddenly, Harvard pulled the plug.

> As recently reported in The Guardian, the Harvard Education Publishing Group (HEPG), which publishes the Review, abruptly and unilaterally decided to cancel the forthcoming special issue.

> ... the scrapping of this special issue marks a worrying escalation. It suggests that even those universities that are outspoken about their liberal values are ready to stifle academics’ legitimate criticism of Israeli policies and practices. Make no mistake: Anticipatory censorship of this kind is a hallmark of the governmental overreach that authoritarian regimes around the world are known for. As a growing number of higher education institutions adopt the IHRA definition of antisemitism, we fear we will see more and more examples of the suppression of academic freedom.

(Also)

[https://www.theguardian.com/education/2025/jul/22/harvard-educational-review-palestine-issue-cancelled](https://www.theguardian.com/education/2025/jul/22/harvard-educational-review-palestine-issue-cancelled)

> “The field of education has an important role to play in supporting students, educators, and policymakers in contextualizing what has been happening in Gaza with histories and continuing impacts of occupation, genocide, and political contestations,” the journal’s editors wrote in their call for abstracts.

> But on 9 June, the Harvard Education Publishing Group, the journal’s publisher, abruptly canceled the release. In an email to the issue’s contributors, the publisher cited “a number of complex issues”, shocking authors and editors alike, the Guardian has learned.

> ...the cancellation of an entire issue of an academic journal, which has not been previously reported, is a remarkable new development in a mounting list of examples of censorship of pro-Palestinian speech.

> “If the universities – or in this case a university press – are not willing to stand up for what is core to their mission, I don’t know what they’re doing. What’s the point?” said Thea Abu El-Haj, a Palestinian-American anthropologist of education at Barnard College, the women’s school affiliated with Columbia University, who was one of the solicited authors.

## Freedom of expression

### Anti-woke/anti-DEI is simply racism

* Judge Keeps Alabama’s Anti-DEI Law in Place for Now

[https://www.insidehighered.com/news/quick-takes/2025/08/15/judge-keeps-alabamas-anti-dei-law-place-now](https://www.insidehighered.com/news/quick-takes/2025/08/15/judge-keeps-alabamas-anti-dei-law-place-now)

> Ruling in part that professors lack First Amendment protections in the classroom, a federal judge denied an effort from college faculty and students in Alabama to block a 2024 state law that banned diversity, equity and inclusion programs as well as the teaching of so-called divisive concepts.

>  For instance, he ruled that the professors aren’t protected by the First Amendment because their “in-class instruction constitutes government speech.”

> Furthermore, Proctor wrote, based on other rulings in the U.S. Court of Appeals for the 11th Circuit, “when there is a dispute about what is taught in the classroom, the university’s interests outweigh those of a professor, and the professor’s interest in academic freedom and free speech do not displace the university’s interest inside the classroom.”



## Visas

* Trump “Chipping Away” at DACA and Other Protections

[https://www.insidehighered.com/news/government/politics-elections/2025/08/14/trump-chipping-away-daca-and-other-protections](https://www.insidehighered.com/news/government/politics-elections/2025/08/14/trump-chipping-away-daca-and-other-protections)

> Tricia McLaughlin, assistant press secretary at the Department of Homeland Security, recently told the undocumented immigrants brought to the U.S. as children known as Dreamers, who have for years participated in the Deferred Action for Childhood Arrivals program, to self-deport.

> Her comments contradict those made by President-elect Donald Trump in a December interview with Meet the Press. He said then that he’d willingly work with Democrats on a plan to keep Dreamers in the country.

> This conflicting rhetoric is emblematic of the tenuous position Dreamers, including thousands of college students, have occupied for years, uncertain whether past protections and legal promises will hold. Today, most of the country’s roughly 400,800 undocumented students don’t have DACA status. But the Presidents’ Alliance on Higher Education and Immigration estimates about 119,000 are eligible for the program based on 2022 data.

> Earlier this year, a three-judge panel for the U.S. Court of Appeals for the Fifth Circuit unanimously affirmed a 2023 district court order that deemed DACA unlawful, but the judges also issued a stay, leaving the status quo unchanged for now

> Pacheco said that now the government is doing a “very methodical, surgical” unwinding of Dreamers’ rights. For example, the administration revoked DACA recipients’ eligibility for Affordable Care Act health insurance. Some Dreamers with DACA status, including students, have been detained by law enforcement.

> Diego Sánchez, director of policy and strategy at the Presidents’ Alliance, said in a recent webinar that he worries the administration’s coordinated attack on DACA, and Dreamers over all, could signal a larger-scale war on the policy. He believes it’s a “very real concern right now” that the Trump administration could try to end DACA through the formal rule-making process—posting a proposed rule for public feedback, then issuing a regulation to phase out the program.

> Pacheco believes higher ed institutions over all are “one of the biggest lines of defense for students.” College officials can have plans in place for potential ICE visits and insist that law enforcement show warrants if they come looking for undocumented students, she said, and the fact of being a student, if they’re detained, can elicit public sympathy. And campuses have networks of alumni who can “rally around” them.

> “One of the safest places where they can be is in a classroom, in an institution of higher learning,” Pacheco said.


## Loss of expertise

## Funding cuts

* New executive order puts all grants under political control - Ars Technica

[https://arstechnica.com/science/2025/08/new-executive-order-puts-all-grants-under-political-control/](https://arstechnica.com/science/2025/08/new-executive-order-puts-all-grants-under-political-control/)

> The order also instructs agencies to formalize the ability to cancel previously awarded grants at any time if they're considered to "no longer advance agency priorities." Until a system is in place to enforce the new rules, agencies are forbidden from starting new funding programs.

> In short, the new rules would mean that all federal science research would need to be approved by a political appointee who may have no expertise in the relevant areas, and the research can be canceled at any time if the political winds change. It would mark the end of a system that has enabled US scientific leadership for roughly 70 years.

> The head of OMB, Russell Vought, has been heavily involved in trying to cut science funding, including a recent attempt to block all grants made by the National Institutes of Health.

> Another expectation? That grants will go to people who adhere to the administration's vision of "gold standard science," something the administration itself has abandoned when it was inconvenient.

> An optimistic view would be that the panels of experts that evaluate grants will end up being left with the final say over funding. However, the order specifically calls on appointees not to defer to peer review. "Senior appointees and their designees shall not ministerially ratify or routinely defer to the recommendations of others in reviewing funding opportunity announcements or discretionary awards, but shall instead use their independent judgment," it reads. "Nothing in this order shall be construed to discourage or prevent the use of peer review methods to evaluate proposals for discretionary awards or otherwise inform agency decision making, provided that peer review recommendations remain advisory and are not ministerially ratified, routinely deferred to, or otherwise treated as de facto binding by senior appointees or their designees."

(also)

[https://www.insidehighered.com/news/government/science-research-policy/2025/08/13/trump-order-puts-politics-above-peer-review](https://www.insidehighered.com/news/government/science-research-policy/2025/08/13/trump-order-puts-politics-above-peer-review)

> The executive order says senior appointees must review grants, and it demands awards be easier to terminate. Research groups say it undermines science.

### NSF

### NIH

* NIH Guide: Weekly Index for August 15, 2025

[https://grants.nih.gov/grants/guide/WeeklyIndexMobile.cfm?WeekEnding=2025-15-08](https://grants.nih.gov/grants/guide/WeeklyIndexMobile.cfm?WeekEnding=2025-15-08)

(MP points out that the week prior had ... no new funding opportunities; just a notice of early termination)

* Gender Data Would Be Off-Limits Under Proposed NIH Policy

[https://www.chronicle.com/article/gender-data-would-be-off-limits-under-proposed-nih-policy?utm_source=Iterable&utm_medium=email&utm_campaign=campaign_14569808_nl_Academe-Today_date_20250813](https://www.chronicle.com/article/gender-data-would-be-off-limits-under-proposed-nih-policy?utm_source=Iterable&utm_medium=email&utm_campaign=campaign_14569808_nl_Academe-Today_date_20250813)

> The National Institutes of Health is moving to prohibit scientists from collecting data about gender, according to a draft policy obtained by The Chronicle, as part of President Trump’s order to end federal recognition of transgender people and others who identify as a gender that doesn’t align with their sex assigned at birth.

### NEH

### NEA


### DOE

### Fulbright

## Federal Agencies

### DOE/OCR

## Congressional actions

## State actions

* Texas Lawmakers Create Overseer to Ensure Colleges Follow Laws

[https://www.insidehighered.com/news/governance/state-oversight/2025/08/11/texas-lawmakers-create-overseer-make-colleges-follow](https://www.insidehighered.com/news/governance/state-oversight/2025/08/11/texas-lawmakers-create-overseer-make-colleges-follow)

> Texas Republicans, like those in other red states in recent years, have overhauled aspects of public higher education in ways that have raised concerns about the future of academic freedom for faculty and institutional autonomy for colleges and universities. They’ve banned diversity, equity and inclusion efforts; reduced the faculty’s role in university decision-making; and mandated curriculum reviews, among other changes.

> But Senate Bill 37, which Gov. Greg Abbott signed into law in June, added something the other states’ laws lack: It created an ombudsman position tasked with ensuring institutions follow SB 37 and the earlier DEI ban, which took effect in 2024.

> “The ombudsman shall serve as the director of compliance and monitoring,” the law says.

> Further, students and employees can complain about violations of certain provisions of SB 37 itself. These provisions include, among others, the requirements that institutions regularly review their general ed curricula, that institutional presidents pick the presiding officers of faculty senates, that faculty elected to senates only serve two years in a row and then must take at least two years off, that only top university leaders or their designees can “be involved in decisionmaking” regarding faculty grievances and faculty discipline, and that faculty can’t have “final decisionmaking authority” on hiring other faculty or administrative leaders.

> If the ombudsman concludes that an institution is violating such provisions, and the university doesn’t make changes that satisfy the official, the ombudsman can recommend that the Legislature bar the institution from spending state money “until the institution’s governing board certifies compliance and the state auditor confirms.”

> “The governor now has a thought police he controls,” Evans [Brian Evans, president of the Texas American Association of University Professors] added. He said the ombudsman has “the ability to compel anybody they want to be interrogated and investigated … This is really incredible power.”

> Emily Berman, vice president of the Texas AAUP-AFT’s University of Houston chapter, expects the ombudsman to “dig and dig and dig and dig—whether or not there’s anything to find there.”

## Institutional assaults

### Accreditation

* Community College Accreditor Adopts ROI Metric

[https://www.insidehighered.com/news/quick-takes/2025/08/12/community-college-accreditor-adopts-roi-metric](https://www.insidehighered.com/news/quick-takes/2025/08/12/community-college-accreditor-adopts-roi-metric)

> The Accrediting Commission for Community and Junior Colleges is launching new tools to give members of the public more insights into student outcomes at the institutions under its purview.

> Those tools include dashboards with different student achievement data points as well as a new metric to gauge return on investment. Like the Western Association of Schools and Colleges Senior College and University Commission, ACCJC is planning to measure ROI using price–to–earnings premium. Developed in part by Third Way and the College Futures Foundation, the earnings premium tracks how long it takes for graduates from different programs to recover educational costs.

### Admissions

NYTimes: Trump Escalates a Fight Over How to Measure Merit in American Education

[https://www.nytimes.com/2025/08/08/us/trump-merit-affirmative-action-colleges.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/08/us/trump-merit-affirmative-action-colleges.html?smid=nytcore-ios-share&referringSource=articleShare)

> Colleges will face even more intense scrutiny over their admissions practices as the administration pushes them to rely more heavily on quantitative measures, which experts say could result in wealthier, less diverse student populations at elite universities.

> Under the new order, the information will be reported publicly in a federal database called the Integrated Postsecondary Education Data System, or IPEDS.

* Dept. of Ed Clarifies What Race-Based Data Must Be Reported

[https://www.insidehighered.com/news/quick-takes/2025/08/14/dept-ed-clarifies-what-race-based-data-must-be-reported](https://www.insidehighered.com/news/quick-takes/2025/08/14/dept-ed-clarifies-what-race-based-data-must-be-reported)

> A draft of the proposal, which will officially be published Friday on the Federal Register, states that certain institutions will be required to collect and report comprehensive data about their admissions decisions going back five years. It must be broken down by race and sex and include students' high school GPA, test scores, time of application (early decision, early access or regular decision) and financial aid status, among other things.

> However, the new survey component, which the Department of Education is calling the Admissions and Consumer Transparency Supplement, will not affect all colleges and universities—just four-year institutions that use “selective college admissions,” as they “have an elevated risk of noncompliance with the civil rights laws,” officials wrote in the notice.


### Harvard

* Exclusive: Harvard patents targeted by Trump administration | Reuters

[https://www.reuters.com/legal/government/harvard-patents-targeted-by-trump-administration-2025-08-08/](https://www.reuters.com/legal/government/harvard-patents-targeted-by-trump-administration-2025-08-08/)

> The Trump administration on Friday ordered a comprehensive review of Harvard University's federally funded research programs, and threatened to take title to or grant licenses from the school's lucrative portfolio of patents.

> In a letter to University President Alan Garber and obtained by Reuters, Commerce Secretary Howard Lutnick accused Harvard of breaching its legal and contractual requirements tied to the research programs and patents.

> As of July 1, 2024, Harvard held more than 5,800 patents, opens new tab, and had more than 900 technology licenses with over 650 industry partners, according to a university website.

* Trump is not happy with the judge hearing Harvard’s lawsuits : NPR

[https://www.npr.org/2025/08/08/nx-s1-5495486/trump-harvard-judge-lawsuits](https://www.npr.org/2025/08/08/nx-s1-5495486/trump-harvard-judge-lawsuits)

(Would you believe this:)

> Shortly after Burroughs presided over a July hearing for Harvard's lawsuit over federal funding cuts, the president took to Truth Social and called her a "Trump-hating Judge," adding that she's "a TOTAL DISASTER."

* NYTimes: Harvard and White House Move Toward Potential Landmark Settlement

[https://www.nytimes.com/2025/08/11/us/trump-harvard-settlement-negotiations.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/11/us/trump-harvard-settlement-negotiations.html?smid=nytcore-ios-share&referringSource=articleShare)

(I still hope this reporting by Blider, Schmidt, and Bender based on four people familiar is just spin put out by the govt. side of this shakedown)

> Harvard University and the Trump administration are nearing a potentially landmark legal settlement that would see Harvard agree to spend $500 million in exchange for the restoration of billions of dollars in federal research funding, according to four people familiar with the deliberations.

> But under the framework coming together, Harvard would agree to spend $500 million on vocational and educational programs and research, three of the people said. That figure, currently penciled in to be paid out over years, would meet a demand from President Trump that Harvard spend more than double what Columbia University agreed last month to pay. It would also satisfy Harvard’s wish that it not pay the government directly, as Columbia is doing.

> Harvard would also make commitments to continue its efforts to combat antisemitism on campus, two of the people said.

> In return, Harvard — one of the largest recipients in higher education of federal research money — would see its research funding restored and avoid the appointment of a monitor, a condition the school has demanded as a way to preserve its academic independence, according to two of the people.

> The Trump administration would also end its widening number of investigations into the university, including ones conducted by the Justice Department and another inquiry that the Commerce Department announced on Friday. The deal would also stop attempts by the Trump administration to block Harvard from enrolling thousands of international students, according to three of the people.

> A settlement between the White House and the nation’s oldest and wealthiest university would reverberate throughout academia and could shape how other schools respond to Mr. Trump’s tactics.

> But with the beginning of the school year approaching, negotiators have accepted that they will have to pay $500 million to strike a deal, and instead focused on how payments would be structured.

> May Mailman, a White House adviser driving the negotiations with top universities, suggested in a recent interview that Harvard’s inclination to provide data surrounding its consideration of race in admissions would be a factor in the government’s willingness to sign off on a deal.


### Columbia

* Where Is Columbia’s $200-Million Settlement Going, Exactly?

[https://www.chronicle.com/article/where-is-columbias-200-million-settlement-going-exactly](https://www.chronicle.com/article/where-is-columbias-200-million-settlement-going-exactly)

(Still waiting for procurement to give access here...)

* Community College Research Collateral Damage in Columbia Fight

[https://www.insidehighered.com/news/institutions/community-colleges/2025/08/13/community-college-research-collateral-damage](https://www.insidehighered.com/news/institutions/community-colleges/2025/08/13/community-college-research-collateral-damage)

> The Community College Research Center, an independent organization based at Columbia University’s Teachers College, found out in March that four of its grants totaling at about $12 million were immediately cancelled, despite being multiple years into their grant cycles. The remaining grant money expected from the Institute of Education Sciences amounted to at least $3.5 million. Four half-completed research projects relied on the funding. Now CCRC leaders are scrambling to find ways to continue the work.

> The canceled grants funded two efforts focused on pandemic recovery, including a study into a program at Virginia community colleges to support adults earning short-term credentials in high-demand fields. CCRC researchers were also using IES money to evaluate the Federal Work-Study program and for a fellowship that placed doctoral students in apprenticeships at education agencies and nonprofits. Teachers College has agreed to take over funding for the fellowship program for at least the upcoming academic year.



### Indiana

### UCLA

* Trump Wants U.C.L.A. to Pay $1 Billion to Restore Its Research Funding - The New York Times

[https://www.nytimes.com/2025/08/08/us/trump-ucla-research-funding-deal.html](https://www.nytimes.com/2025/08/08/us/trump-ucla-research-funding-deal.html)

> The Trump administration is seeking more than $1 billion from the University of California, Los Angeles, to restore hundreds of millions of dollars in federal research funding that the government halted, according to a draft of a settlement agreement reviewed by The New York Times.

> The proposal calls for the university to make a $1 billion payment to the U.S. government and to contribute $172 million to a claims fund that would compensate victims of civil rights violations.

> The University of California’s president, James B. Milliken, said in a statement on Friday that the university had “just received a document from the Department of Justice and is reviewing it.” He added, “As a public university, we are stewards of taxpayer resources, and a payment of this scale would completely devastate our country’s greatest public university system as well as inflict great harm on our students and all Californians.”

> Mr. Newsom suggested the University of California would not bow to the federal government. “I will fight like hell to make sure that doesn’t happen,” said Mr. Newsom, an ex officio member of the university’s board of regents. “There’s principles. There’s right and wrong, and we’ll do the right thing, and what President Trump is doing is wrong, and everybody knows it.”

(Also)

[https://www.cnn.com/2025/08/08/politics/ucla-trump-administration-settlement](https://www.cnn.com/2025/08/08/politics/ucla-trump-administration-settlement)

[https://www.latimes.com/california/story/2025-08-08/trump-seeking-1-billion-fine-from-ucla-over-antisemitism-allegations](https://www.latimes.com/california/story/2025-08-08/trump-seeking-1-billion-fine-from-ucla-over-antisemitism-allegations)

* UCLA should not bend 'on their knees' to Trump in grant talks, Newsom says - Los Angeles Times

[https://www.latimes.com/california/story/2025-08-07/newsom-ucla-trump-grant-freeze-negotiations-antisemitism](https://www.latimes.com/california/story/2025-08-07/newsom-ucla-trump-grant-freeze-negotiations-antisemitism)

* ‘Extortion’: Newsom Threatens to Sue After Trump Fines UCLA $1 Billion | KQED

[https://www.kqed.org/news/12051521/extortion-newsom-threatens-to-sue-after-trump-fines-ucla-1-billion](https://www.kqed.org/news/12051521/extortion-newsom-threatens-to-sue-after-trump-fines-ucla-1-billion)

* NYTimes: Trump Administration Violated Order on U.C.L.A. Grant Terminations, Judge Says

[https://www.nytimes.com/2025/08/12/us/politics/ucla-grant-nsf-science-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/12/us/politics/ucla-grant-nsf-science-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> Judge Rita F. Lin ordered the National Science Foundation to restore grants awarded to the university, which she said had been suspended in defiance of the court.

> “N.S.F. claims that it could simply turn around the day after the preliminary injunction” and freeze “funding on every grant that had been ordered reinstated, so long as that action was labeled as a ‘suspension’ rather than a ‘termination,’” she wrote. “This is not a reasonable interpretation.”

> Judge Lin said that the Trump administration’s freezing of university grants appeared designed more to suspend research the Trump administration has associated with liberal causes than to sincerely address concerns about racism or antisemitism.

> In a related case focused on grants from the National Institutes of Health, a federal judge in Massachusetts described the cancellations of those grants as discriminatory toward racial and sexual minorities and driven by animus toward vulnerable groups. He similarly ordered that funding restored in an impassioned ruling from the bench in June.

(Also)

[https://www.insidehighered.com/news/faculty-issues/research/2025/08/14/federal-judge-orders-nsf-reinstate-suspended-ucla-grants](https://www.insidehighered.com/news/faculty-issues/research/2025/08/14/federal-judge-orders-nsf-reinstate-suspended-ucla-grants)



## George Washington

* DOJ Claims George Washington U Violated Federal Civil Rights Law

[https://www.insidehighered.com/news/quick-takes/2025/08/13/doj-george-washington-u-violated-federal-civil-rights-law](https://www.insidehighered.com/news/quick-takes/2025/08/13/doj-george-washington-u-violated-federal-civil-rights-law)

> The four-page letter signals that George Washington could be the next university in the Trump administration’s crosshairs.

> Harmeet Dhillon, the assistant attorney general for the civil rights division, wrote in the letter that the department plans to enforce its findings unless the university agrees to a voluntary resolution agreement to address the agency’s concerns. She didn’t detail what such an agreement would entail or what enforcement might look like.


### Others

* UChicago Reducing, Freezing Ph.D. Admissions for Multiple Humanities Programs

[https://www.insidehighered.com/news/business/academic-programs/2025/08/14/uchicago-freezing-phd-admissions-multiple-programs](https://www.insidehighered.com/news/business/academic-programs/2025/08/14/uchicago-freezing-phd-admissions-multiple-programs)

> In a Tuesday email that Inside Higher Ed obtained, Arts and Humanities dean Deborah Nelson told faculty, staff and Ph.D. students, “We will accept a smaller overall Ph.D. cohort across seven departments: Art History, Cinema and Media Studies, East Asian Languages and Civilizations, English Language and Literature, Linguistics, Music (composition), and Philosophy.” The university didn’t tell Inside Higher Ed how many fewer Ph.D. students would be accepted across those departments.

> “Other departments will pause admissions,” Nelson wrote.

> UChicago, which faces debt issues, has become yet another example of well-known universities freezing or scaling back Ph.D. admissions and programs amid financial pressures and other factors. In November, before Trump retook the presidency, Boston University said it was pausing accepting new Ph.D. students in a dozen humanities and social sciences programs, including philosophy, English and history. In February, the Universities of Pennsylvania and Pittsburgh announced pauses, following other institutions.

> But UChicago’s reductions for language programs also reflect a broader trend of universities scaling back foreign language education offerings. In 2023, West Virginia University became infamous in academe for its leaders’ decision to eliminate all foreign language degrees.

## The long game


## Blowback

* NYTimes: As Trump Pushes International Students Away, Asian Schools Scoop Them Up

[https://www.nytimes.com/2025/08/14/business/us-international-students-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/14/business/us-international-students-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> It’s a quandary facing many young people around the world. According to the United Nations, 6.9 million people studied outside their home country in 2022. The United States has long attracted the most foreign students, 1.1 million in the 2023-24 academic year.

> Major international education search platforms, including IDP and Keystone Education Group, have detected a marked decline in student interest in American programs. Among academic administrators polled by the Institute of International Education this spring, more than usual reported drops in international applications for the coming year.

> These are not the first signs that American higher education is losing its dominant position. For years, countries in Asia have been strengthening their universities and marketing them to students around the world. With more appealing alternatives, the Trump administration’s hostile stance may hasten the decline in U.S. higher education pre-eminence.

> South Korea’s latest target was set in 2023: 300,000 international students by 2027. For 2026, Seoul was named the top city for international students in the closely followed Quacquarelli Symonds World University Rankings.

> They took guidance from a similar effort in Japan, which had about 337,000 foreign students last year and is aiming for 400,000 by 2033.


* U.S. scientists are seeing their research upended

[https://www.washingtonpost.com/opinions/2025/08/14/scientists-cuts-grants-trump-research/](https://www.washingtonpost.com/opinions/2025/08/14/scientists-cuts-grants-trump-research/)

> The reality is more troubling than headlines might suggest. Since the start of the second Trump administration, I have heard from colleagues in the medical research community about their experiences. Many are afraid to speak openly but want the public to understand the effects of these policy decisions on the future of science. I am sharing some of their stories here, while respecting their wishes to omit details that would identify them.

> A microbiologist at a major Midwestern university told me about supervising a postdoctoral researcher whose NIH funding was terminated in the spring. A court later ordered the money to be reinstated, but the postdoc has yet to receive it.

> “I am supporting her for now so that she can pay her bills and keep her health insurance,” the supervisor told me. “My postdoc is trying to hold out hope that her career can be salvaged, but it has caused an extreme amount of stress.”

> A graduate of a respected MD-PhD program and a competitive residency and research fellowship told me a similar story. They were on track to successfully launching a lab and supervising graduate students and postdocs. However, in response to diminished funding, many universities have instituted hiring freezes, and deeper cuts are expected. Some have even rescinded offers to prospective researchers. “Nobody is hiring, and who knows how long in the future this will extend?” the person said.

> In addition, the NIH institute this scientist typically relies on for funding might vanish altogether under a proposed reorganization that would consolidate the agency’s 27 institutes and centers into just eight. “There’s so much uncertainty, it’s just devastating,” said the scientist, who is now actively applying for jobs in the private sector.

> Only one of the scientists I talked with agreed to be named: Natoshia Cunningham, a clinical psychologist and associate professor in the department of family medicine at Michigan State University. Her husband, who was a senior scientist at the National Institute for Occupational Safety and Health, saw his research group decimated and has gone to work for a family construction business.

> Cunningham describes the situation in academic research as “walking through a battlefield and there’s just all these bombs that are going off at all times all around me.” She recently learned that her study on lupus, an autoimmune condition, will not be funded next year. A colleague’s work on birth outcomes among Black mothers already has been terminated.

> Everyone I spoke with lamented the politicization of science and research. The HIV researcher, like so many other scientists, was working to improve lives. “And now ‘science’ has become a bad word,” this person said. “People talk about research as if it’s some kind of corrupt waste of money as opposed to a path forward for all of us to be healthier.”



## Coming attractions?


## Tracking projects


* Tracking Key Lawsuits Against the Trump Administration

[https://www.insidehighered.com/news/government/politics-elections/2025/08/12/tracking-key-lawsuits-against-trump-administration](https://www.insidehighered.com/news/government/politics-elections/2025/08/12/tracking-key-lawsuits-against-trump-administration)

> Of the 41 included in our searchable database, judges have ruled against the administration in two-thirds of the cases so far.


## AI misdeeds

* Online Learning: Past the Tipping Point

[https://www.insidehighered.com/news/tech-innovation/teaching-learning/2025/08/13/surveys-are-wake-call-colleges-improve-online-ed](https://www.insidehighered.com/news/tech-innovation/teaching-learning/2025/08/13/surveys-are-wake-call-colleges-improve-online-ed)

> This year is primed to be a pivotal one for online learning, with the number of undergraduates studying fully online surpassing that of peers studying fully in person for the first time.

> AI integration lacks strategic coordination, with few institutions represented having a unified or coordinated plan. This echoes findings from Inside Higher Ed’s 2025 Survey of Campus Chief Technology/Information Officers. Some 57 percent of chief online learning officers in the new CHLOE survey also reported that uneven access to AI tools is affecting at least some learners.

> At same time, the report found that the online education marketplace is increasingly competitive, especially among private four-year institutions and community colleges.

> “As more institutions enter the space, differentiation and program quality are becoming strategic imperatives,” the authors wrote. (On revenue-sharing, they found models directing funds to “both academic units and central offices are best positioned to incentivize growth and sustain support infrastructure.”)

> In a related finding, institutional investment in nondegree offerings such as certificates and microcredentials has surged, with 65 percent of respondents reporting some or major investment in these products—up from 29 percent in 2018–19. This is especially true for community colleges, where online strategies center on nondegree pathways, according to the survey.


## And just because it is fun

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library--BUT they currently aren't (procurement issues). I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
