# Aug 29

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week. (This doesn't attempt to speak to other slides downward towards authoritarianism, but this week that speaks for itself.)

Thanks for KK, BE, and VC for sharing links this week.

## Conferences

* Scholars at Risk US Mid-Atlantic Regional Conference

[https://www.scholarsatrisk.org/event/sar-us-midatlantic-conference/](https://www.scholarsatrisk.org/event/sar-us-midatlantic-conference/)

> I am writing on behalf of Scholars at Risk (SAR), a network of 650+ institutions around the world dedicated to protecting threatened scholars and promoting academic freedom. Please see a brief primer on SAR's work attached below for your reference.

> We would greatly appreciate your sharing of the following information regarding our upcoming SAR US Mid-Atlantic Regional Conference, taking place October 9-10 at New York University with interested members of the CUNY University Faculty Senate (UFS).

> The event, titled “Working Together to Protect Scholars and Promote Academic Freedom,” will feature SAR programming on both local and global responses to pressures on academic freedom. The meeting will offer networking opportunities, reflections on responses to attacks on higher education in both the US and worldwide, the launch of SAR’s Free to Think 2025 report, and most notably, the launch of SAR’s 25th Anniversary year themed “Truth Matters.”

## Op eds

* NYTimes: Trump Isn’t Fixing America’s Campuses. He’s Bleeding Them Dry.

[https://www.nytimes.com/2025/08/25/opinion/trump-colleges-universities.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/25/opinion/trump-colleges-universities.html?smid=nytcore-ios-share&referringSource=articleShare)

(Another story that take too long to get to the point and only gets there to say there are problems, but... still)

> But what Trump and his allies are doing is no targeted effort to correct that. It’s a sweeping, indiscriminate, performative smackdown of elite institutions by a crew trying to solidify its power under the banner of anti-elitism. It doesn’t attempt to usher those institutions from a place of bias and extremism to one of neutrality and moderation. It answers excess with excess, orthodoxy with orthodoxy, censorship with censorship. And it disregards the damage it’s doing.

> Because that’s what’s happening now. With debatable authority and without any consultation with Congress, Trump is using the suspension of federal grants, threats of further cuts and demands that schools essentially pay fines for their supposed transgressions to get them to do as he pleases. That’s not a discussion; it’s intimidation. That’s not accountability; it’s extortion. He extracted $200 million from Columbia. He’s reportedly looking for $500 million from Harvard and more than $1 billion from U.C.L.A. Why these targets? They’re politically juicy. These sums? They’re attention-grabbing. He’s staging a show of force. A spectacle of punishment.

> And an illogical one at that. His and his allies’ principal grievances are with professors and courses in the humanities, in the social sciences, which are the realms where white supremacy and structural racism are studied. So they’re slowing money to … Alzheimer’s research? Gumming up or dragging down investigations into the causes and treatments of other diseases? Slashing studies of sea-level rise and flooding because they trigger “climate anxiety”? How does that fight antisemitism? It’s the DOGE approach, sadistic and sloppy: Inflict pain with no regard for what and who are really being hurt, because the true goal is to assert dominance, shrink others’ influence and please your supporters by destroying something in particular that they’ve decided to hate and smashing the status quo in general.

## How best to describe the times we are in

* NYTimes: The Typical College Student Is Not Who You Think It Is

[https://www.nytimes.com/2025/08/25/us/us-typical-college-student.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/25/us/us-typical-college-student.html?smid=nytcore-ios-share&referringSource=articleShare)

(The typical student looks a lot like a typical CUNY student)

> 43 percent of undergraduates attend community college

> About 75 percent of community college students are enrolled part time

> 20 percent of all undergraduate students are parents

> 1.4 million undergraduate students with children are single mothers

> 10.3 million students take at least some classes online

> 26 percent of students take classes exclusively online

> 25 percent of all undergraduate students live with their parents

> The average student is $19,000 in debt

> 10.8 million students owe more than $44,000

> Two-thirds of student loan debt belong to women

> About a third of all undergraduate students received a Pell Grant

> 41 million people attended college but never graduated


* Too many college students

[https://www.washingtonpost.com/opinions/2025/08/27/college-students-degrees-jobs/](https://www.washingtonpost.com/opinions/2025/08/27/college-students-degrees-jobs/)

(Thanks BE. The old right wing way of trying to rationalize the unrational, if you ask me)

> Since 1990, college enrollment has increased by 6 million students (29 percent). Reasons for this include government tuition subsidies and “college for everyone” rhetoric. And “degree inflation”: irrational requirements for job applicants.

>  In 1990, 9 percent of secretaries and administrative professionals had bachelor’s degrees; today, 33 percent do, and a higher proportion of job listings require applicants to have one. This “paper ceiling” is especially egregious in state and local governments, where 63 percent of those earning between $40,000 and $60,000 have bachelor’s degrees or higher. Only 28 percent of such earners in the private sector do.

> A recent report from the Burning Glass Institute and the Strada Education Foundation says 52 percent of recent college graduates are underemployed: in jobs not using their college learning. Meanwhile there are 750,000 industrial jobs unfilled.

> Economist Arnold Kling [Cato Institute type] says that despite the limited “natural demand” for college education (“students who are excited by academic subjects”), graduate schools continue to churn out more PhDs (almost 60,000 in 2022) than the growth of undergraduate enrollment justifies. So, artificial student demand must be stimulated. Kling says “colleges adapt by offering dumbed-down courses and grade inflation.

> And by teachers teaching less. Hess and Richard B. Keck, also of AEI [Also center right], say light teaching loads have become badges of professional status — and require schools to rely on teaching by graduate students or part-time adjunct instructors.

## Shared governance

* University of Texas System ends faculty senates to comply with SB 37

[https://www.statesman.com/news/education/article/university-texas-system-faculty-senate-abolish-20822502.php](https://www.statesman.com/news/education/article/university-texas-system-faculty-senate-abolish-20822502.php)

(Thanks KK!)

> Faculty senates — a long-standing advisory body of elected members that helps university leadership on curriculum, policy and programs — will no longer exist at University of Texas institutions starting Sept. 1, after the UT System Board of Regents on Thursday approved compliance with Senate Bill 37.

> Chairman Kevin Eltife said the board will "take their time" deciding if faculty senates compliant with the law will be reinstated to university campuses, and may not be needed at all 14 campuses.

> In the meantime, the board authorizes university presidents to create "faculty advisory groups" for leaders to consult as needed and to complete the essential work previously done by the faculty senate.

> Sen. Brandon Creighton, R-Conroe, authored SB 37 to give regents more control following complaints from conservatives that the institution's faculty have become too liberal or "woke."

## Freedom of expression

* Ohio State Restricts Decorations in Public Dorm Spaces

[https://www.insidehighered.com/news/quick-takes/2025/08/27/ohio-state-restricts-decorations-public-dorm-spaces](https://www.insidehighered.com/news/quick-takes/2025/08/27/ohio-state-restricts-decorations-public-dorm-spaces)

> The move comes partly in response to SB1, a higher ed law Ohio passed in March that prohibits DEI, requires institutions to “demonstrate intellectual diversity” and mandates institutional neutrality on “controversial” subjects such as climate change, electoral politics, foreign policy, immigration, marriage and abortion.

> Students took to Reddit to pan the new decorating rules, with one commenter posting, “SB1 and university leadership has sucked the life out of literally everything.”

* FEMA employees put on leave after criticizing Trump administration in open letter

[https://www.washingtonpost.com/climate-environment/2025/08/26/fema-employees-leave-trump-administration-letter/](https://www.washingtonpost.com/climate-environment/2025/08/26/fema-employees-leave-trump-administration-letter/)

> The Trump administration placed more than 30 Federal Emergency Management Agency employees on leave Tuesday after they signed an open letter of dissent about the agency’s leadership, according to people familiar with the situation and documents reviewed by The Washington Post.

### Title VI

* How Leo Terrell Is Helping Trump “Root Out” Antisemitism on College Campuses — ProPublica

[https://www.propublica.org/article/leo-terrell-universities-lawsuits-antisemitism](https://www.propublica.org/article/leo-terrell-universities-lawsuits-antisemitism)

> Terrell, meanwhile, rebranded himself as “Leo 2.0,” complete with red Trump-style caps he offered for sale online. Leo 1.0 had slammed Trump for cozying up to white supremacists, blamed him for a surge in violent attacks on Jews and donated to Democrats. Leo 2.0? He attacked “DEI nonsense,” compared Black Lives Matter to ISIS and declared the 2020 election was “stolen from President Trump and America!”

> In January, Terrell was rewarded for his loyalty when President-elect Trump, praising him as a “highly respected civil rights attorney and political analyst” with an “incredibly successful career,” named him senior counsel to the assistant attorney general for civil rights in the Justice Department. Terrell assumed his marquee role a month later: as head of the multiagency Task Force to Combat Anti-Semitism.

> But his zealous conversion and penchant for media bombast made him a perfect bullhorn for the task force’s actual mission: to strong-arm colleges into stripping away any vestige of “wokeness” in their hiring, admissions, classes and research.

> In service of that goal, the government has abandoned due process in favor of media warfare, preemptive declarations of guilt and freezes on billions in critical federal funding.

> So far, the campaign has been effective. To preserve hundreds of millions of dollars in federal grants and contracts, Columbia and Brown have struck deals with the administration that cost them $220 million and $50 million, respectively, and go far beyond pledging tougher action to combat antisemitism. Columbia agreed to open academic programs and admissions decisions to outside monitoring. Brown pledged to ban transgender women from single-sex spaces and women’s sports. Harvard has sued the administration to try to unfreeze $2.6 billion in federal research funds, but it’s also trying to negotiate a settlement. Meanwhile, colleges nationwide are eliminating any remaining vestiges of diversity, equity and inclusion programs and shuttering multicultural centers lest the government come after them.

> The portrait that emerged is dramatically at odds with Trump’s description of a “highly respected” and “incredibly successful” attorney. Peers in civil rights law said they always considered Terrell a minor player. Documents reveal a distinctly mixed legal track record, marred by malpractice suits, client disputes and mishandling a criminal case so badly that a federal appeals court lambasted his work as “woeful.”

(And you were hoping for something beyond woeful. Also)

* Why the Unlikely Leader of Trump’s Antisemitism Task Force May Be the Perfect Man for the Job

[https://www.chronicle.com/article/the-improbable-warrior https://www.chronicle.com/article/the-improbable-warrior?utm_source=Iterable&utm_medium=email&utm_campaign=campaign_14759912_nl_Academe-Today_date_20250828](https://www.chronicle.com/article/the-improbable-warrior https://www.chronicle.com/article/the-improbable-warrior?utm_source=Iterable&utm_medium=email&utm_campaign=campaign_14759912_nl_Academe-Today_date_20250828)

## Visas

* After Texas relents, Trump seeks to widen ban on in-state tuition for noncitizens

[https://www.washingtonpost.com/education/2025/08/25/in-state-tuition-undocumented-students-texas/](https://www.washingtonpost.com/education/2025/08/25/in-state-tuition-undocumented-students-texas/)

> HOUSTON — Tens of thousands of undocumented students at public universities and community colleges in Texas are facing uncertainty and astronomically higher bills this fall after the Trump administration and state officials struck a deal to deny them in-state tuition.

> The Justice Department is similarly seeking to end tuition breaks in several other states for students who are residents there but do not have legal status.

> The administration later filed separate lawsuits on the same issue against Kentucky, Minnesota and Oklahoma. Currently, 23 states and the District of Columbia have laws or policies that grant in-state tuition to undocumented students.

* Visa Delays Persist, Causing Some Students to Defer to Spring

[https://www.insidehighered.com/news/global/international-students-us/2025/08/27/international-students-face-visa-issues-fall](https://www.insidehighered.com/news/global/international-students-us/2025/08/27/international-students-face-visa-issues-fall)

> This week marked the start of the semester for hundreds of colleges across the U.S. But many international students, plagued by difficulty getting visa appointments and unusually high rates of visa denials, are still unsure if they’ll be able to attend college in the U.S. this year.

> At the University of Maryland Baltimore County, a midsize public university that has a student body composed of about 15 percent international students, international Ph.D. and undergraduate students appear to be largely unaffected by visa issues. But the rate of visa issuance for master’s students is only about half what it has been in previous years, according to David Di Maria, UMBC’s vice provost for global engagement

* rump Deals A New Immigration Blow To International Students

[https://www.forbes.com/sites/stuartanderson/2025/08/28/trump-deals-a-new-immigration-blow-to-international-students/](https://www.forbes.com/sites/stuartanderson/2025/08/28/trump-deals-a-new-immigration-blow-to-international-students/)

> The Trump administration has proposed a new rule to limit international students to fixed periods of entry, making enrolling at U.S. universities more precarious. Educators warn that if Trump officials finalize the rule, fewer international students will come to America. The regulation represents the most recent action by the Trump administration restricting international students and should be viewed in that context. Immigration data for July 2025 showed a significant decline in the arrival of international students compared to the same period a year earlier, including a drop of almost 50% for students from India. The proposed rule will increase bureaucracy and red tape for employers by including an unrelated measure to eliminate deference to prior findings of fact in adjudications.

> White House Deputy Chief of Staff Stephen Miller and U.S. Citizenship and Immigration Services Director Joseph Edlow have indicated they do not want international students to remain and work in the United States after completing their coursework. The proposed rule has a 30-day comment period. Barring litigation blocking the rule, it is expected to become final before the Fall 2026 academic year.

> The four-year limit will likely be insufficient for many international students. The National Center for Education Statistics reports a median of 52 months (4.3 years) for completing a bachelor’s degree. The National Science Foundation reports a median of 5.7 years for completing a Ph.D.

* NYTimes: International Student Enrollments Stay Steady at Columbia and Princeton

[https://www.nytimes.com/2025/08/29/us/international-students-race-affirmative-action-princeton-columbia.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/29/us/international-students-race-affirmative-action-princeton-columbia.html?smid=nytcore-ios-share&referringSource=articleShare)

> But Black student enrollment is lower at the two universities after years of turmoil in elite higher education.

> Columbia’s Black and Hispanic enrollment was similar to last year, when the percentage of Black students saw significant declines in the wake of the court ruling. At Princeton, where Black enrollment had not previously seen much change, the university reported a notable drop in Black enrollment this year, even as the percentage of Hispanic admits remained stable.

## Funding cuts

* The State of Independent Technology Research 2025

[https://independenttechresearch.org/citr-report-2025/](https://independenttechresearch.org/citr-report-2025/)

[https://independenttechresearch.org/wp-content/uploads/2025/08/The-State-of-Independent-Technology-Research-Power-in-Numbers.pdf](https://independenttechresearch.org/wp-content/uploads/2025/08/The-State-of-Independent-Technology-Research-Power-in-Numbers.pdf)

> Yet still today, more than thirty-five years after the invention of the Web, over 20 years since the dawn of social media, and on the brink of rapid technological advances in AI, the public still has a shocking lack of clarity about the impacts that technology is having on society. Basic questions about how these systems are designed, what data trains them, and whether they will deepen inequality or enable liberation remain largely unanswered. Much of the research that does exist comes from within the tech industry itself, conducted by employees who sign nondisclosure agreements and whose findings can be suppressed or ignored by corporate executives.

> Incomplete data access fundamentally undermines the breadth and depth of social media research. When researchers can only see what users clicked on, liked, or shared, they miss the vast majority of content that appeared in users' feeds but went unnoticed. This creates a distorted picture, almost like trying to understand a movie by only watching the scenes that made audiences applaud. Without seeing the content landscape, researchers cannot accurately assess whether harmful content is being effectively moderated or simply ignored, how algorithmic recommendations are truly personalized or systematically biased, or how information flows through social networks.

* DOJ Deems Definition of HSIs Unconstitutional, Won’t Defend

[https://www.insidehighered.com/news/institutions/minority-serving-institutions/2025/08/22/doj-deems-definition-hsis](https://www.insidehighered.com/news/institutions/minority-serving-institutions/2025/08/22/doj-deems-definition-hsis)

> The country’s roughly 600 Hispanic-serving institutions are in peril of losing hundreds of millions of dollars annually from the federal government, after the Department of Justice said it won’t defend the program against a lawsuit alleging the way HSIs are currently defined is unconstitutional. The suit challenges the requirement that a college or university’s undergraduate population must be at least a quarter Hispanic to receive HSI funding.

(CUNY has several such institutions)

> The Washington Free Beacon, a conservative outlet, first reported on the letter Friday. The DOJ subsequently provided Inside Higher Ed with the letter but gave no further comment or interviews.

(The Free Beacon is always being given such scoops, hmm such dilligent reporting)

> “There are proposals to the Department of Education right now that they said they were going to allocate,” Santiago [co-founder and chief executive officer of Excelencia in Education] said, noting that the program was set to dole out more than $350 million this fiscal year—money that institutions use for faculty development, facilities and other purposes.

> “The value of a program like this has really been investing in institutions that have a high concentration of low-income, first-generation students,” Santiago said.

* Trump’s Funding Freezes Against Universities in 5 Charts

[https://www.insidehighered.com/news/government/2025/08/28/trumps-funding-freezes-against-universities-5-charts](https://www.insidehighered.com/news/government/2025/08/28/trumps-funding-freezes-against-universities-5-charts)

> “All told, the tradeoff put to Harvard and other universities is clear: Allow the Government to micromanage your academic institution or jeopardize the institution’s ability to pursue medical breakthroughs, scientific discoveries, and innovative solutions,” the university’s lawyers wrote in the initial complaint.

> Although only a few institutions have been affected, Fansmith said other college presidents should be concerned that they could face a similar penalty. Supporting a transgender student or having policies that the administration disagrees with could trigger a freeze, he added.

> “What [Trump officials] have shown is they will not follow the rules and the laws in a way that gives you some sense of what compliance actually looks like, because it’s irrelevant,” he said.


### NIH

* Opinion | Trump Is Defunding Medical Research. It Could Cost You Your Life. - The New York Times

[https://www.nytimes.com/2025/08/24/opinion/trump-defunding-medical-research.html](https://www.nytimes.com/2025/08/24/opinion/trump-defunding-medical-research.html)

> Dr. Kamila Naxerova is trying to understand how cancer spreads in the body. Dr. Rachael Sirianni is trying to find new ways to deliver drugs for childhood brain cancer. Dr. David Ho is trying to make breakthroughs in H.I.V. research.

> These researchers and so many others worked to ensure that Americans had access to the best medical treatments available and that they had first access to those treatments. That is, they worked until Trump administration gutted funding to the National Institutes of Health and froze grants to universities across the country. You can put a dollar amount on how much has been saved, but the cost of what has been lost is incalculable.

* Former NIH chief calls research cuts “careless” and “heartless” | AAMC

[https://www.aamc.org/news/former-nih-chief-calls-research-cuts-careless-and-heartless](https://www.aamc.org/news/former-nih-chief-calls-research-cuts-careless-and-heartless)

(Old story from June that popped across my screen)

> Collins retired in February 2025, issuing a statement that praised NIH-funded research and its staff as “individuals of extraordinary intellect and integrity, selfless and hard-working.” In a subsequent interview with “60 Minutes,” Collins called the environment at the NIH this year “untenable,” citing limits on scientific communication, firing of staff, and halts to new projects enforced by political directives.

> Yes, it’s hard for people to understand the importance of basic science. I think the best way to deal with that is to talk about examples.

> I’ll reflect on my experience with cystic fibrosis research. The effort to try to do something for that almost-uniformly fatal disease started as a basic science enterprise to try to discover the nature of the gene that is misspelled. That was a hard slog back in the 1980s. Nobody would have supported [research into it] except NIH.

> Now, 30 years after the gene discovery, young people with cystic fibrosis are planning for retirement instead of an early funeral.

* SCOTUS Ruling Has “Bleak Implications” for Researchers

[https://www.insidehighered.com/news/government/science-research-policy/2025/08/25/scotus-ruling-has-bleak-implications-researchers](https://www.insidehighered.com/news/government/science-research-policy/2025/08/25/scotus-ruling-has-bleak-implications-researchers)

> Researchers sued the NIH in April and got a win in June when a federal district court judge in Massachusetts ordered the agency to reinstate the grants immediately. Although the NIH has since reinstated many of those grants, Scott Delaney, an epidemiologist at Harvard University and former lawyer who’s been tracking grant cancellations, told Inside Higher Ed that after Thursday’s ruling those reinstated grants will “almost certainly” be re-terminated. If that happens, “I don’t think they’ll get their money back.”

> “Nobody has that kind of time. The nature of research is that you can’t just stop and restart it many months later,” said Delaney. “Folks have already had to do that once and many aren’t able to—they’ve had to lay off staff and lost contact with study participants. This additional delay probably renders the research unviable going forward.”

> “Make no mistake: This was a decision critical to the future of the nation, and the Supreme Court made the wrong choice,” the Association of American Medical Colleges said in a statement. “History will look upon these mass NIH research grant terminations with shame. The Court has turned a blind eye to this grievous attack on science and medicine, and we call upon Congress to take action to restore the rule of law at NIH.”

> He added that Justice Ketanji Brown Jackson’s dissent sums up his interpretation of the ruling’s implications. “This is Calvinball jurisprudence with a twist,” Jackson wrote. “Calvinball has only one rule: There are no fixed rules. We seem to have two: That one, and this Administration always wins."

* NIH Publisher Fee Cap Plan ‘Not Comprehensive Enough,’ Critics Say

[https://www.insidehighered.com/news/government/science-research-policy/2025/08/27/nih-publisher-fee-cap-plan-not-comprehensive](https://www.insidehighered.com/news/government/science-research-policy/2025/08/27/nih-publisher-fee-cap-plan-not-comprehensive)

> The agency, which is the nation’s largest funder of biomedical research, wants to do that by capping—or potentially disallowing—the amount of money it gives to NIH-funded researchers who want to make their work publicly accessible by paying publishers article processing charges. A July 30 request for information memo outlined five potential options, which the NIH says are all aimed at balancing the “feasibility of providing research results with maximizing the use of taxpayer funds to support research.”

> Jay Bhattacharya, director of the NIH, has said the policy could be a mechanism for ending what he sees as the “perverse incentives” driving the $19 billion for-profit academic publishing industry and making it “much harder for a small number of scientific elite to say what’s true and false.”

### HHS

* HHS Ends Minority Biomedical Research Support Program

[https://www.insidehighered.com/news/quick-takes/2025/08/27/hhs-ends-minority-biomedical-research-support-program](https://www.insidehighered.com/news/quick-takes/2025/08/27/hhs-ends-minority-biomedical-research-support-program)

> The Health and Human Services Department has terminated the Minority Biomedical Research Support program, which provided colleges and universities grants to increase the number of minority faculty, students and investigators conducting biomedical research.

> STAT reported the move earlier. Rochelle Newman, a University of Maryland psychologist who used the grant to pay undergraduate researchers and train them, told STAT that “cutting of these programs means that an entire generation of students will end up being lost to science.”

### DOE

* Federal Grants for Area Studies and Foreign Language at Risk

[https://www.insidehighered.com/news/faculty-issues/research/2025/08/25/federal-grants-area-studies-and-foreign-language-risk](https://www.insidehighered.com/news/faculty-issues/research/2025/08/25/federal-grants-area-studies-and-foreign-language-risk)

> For 67 years, the Department of Education has administered grants to universities to create centers devoted to foreign languages and area studies, a field focused on the study of the culture of a particular area or region. Now, those centers are under fire by the Trump administration, which has not released the funding the grantees expected to receive in July.

> The grants support what are known as National Resource Centers, which were originally developed as a national security tool to help the U.S. increase its international expertise in the midst of the Cold War and the aftermath of Soviet Union's 1957 launch of Sputnik. Since then, their purpose has shifted with the times, now focusing not only on producing scholars but also on community outreach and collaboration with K–12 schools.

> The funding cuts appear to be caused by the Office of Management and Budget; records show that the agency has not approved appropriations for programs formerly housed in IFLE, including the NRC program, as well as the Foreign Language and Area Studies fellowships, which fund scholarships and stipends for undergraduate and graduate students studying these disciplines. In total, about $85 million was appropriated for IFLE programs for FY 2025–26, including $60 million for NRCs and FLAS.

* Dems Claim ED Is Making It Harder for Students to File Financial Aid Complaints

[https://www.insidehighered.com/news/quick-takes/2025/08/26/its-more-difficult-file-student-aid-complaints-dems-say](https://www.insidehighered.com/news/quick-takes/2025/08/26/its-more-difficult-file-student-aid-complaints-dems-say)

> “ED is covering up its attempts to make [the Office of Federal Student Aid] less responsive to millions of students, families, and borrowers who rely on the agency to lower the cost of attending college and protect them from loan servicer misconduct,” the senators wrote. “We urge you to immediately act on our findings by streamlining the ‘Submit a Complaint’ process and restoring FSA’s workforce so borrowers can get the help they need.”

> In the letter, Warren states that she told FSA in March that the button for submitting online complaints had been “hidden.” The department responded in April that the button had just been moved from the top of the webpage to the footer and relabeled as “submit feedback.”  The department added that no employees who handle technical functions of the aid applications of loan servicing had been laid off, and while some employees that handle complaints were, the remaining employees will “still be responding” to future complaints.

> But the Democrats say they tested those claims and found the department’s reassurances were misleading. Although the department did move and rename the complaint button, it also added a series of four extra navigation clicks that must be made before the user actually reaches the webpage where they can file a complaint. (Inside Higher Ed checked the website and verified these steps. You can see screenshots of the process below.)

* Agencies Share New Guidance on Foreign Threats at U.S. Colleges

[https://www.insidehighered.com/news/quick-takes/2025/08/27/agencies-share-guidance-foreign-threats-us-colleges](https://www.insidehighered.com/news/quick-takes/2025/08/27/agencies-share-guidance-foreign-threats-us-colleges)

> Warning American colleges and universities about increasing foreign threats to research, a group of federal intelligence agencies and the Education Department released new guidance this week outlining how the institutions can better protect themselves.

> For example, the 40-page “Safeguarding Academia” bulletin in part encourages colleges and researchers to be transparent about who else is involved in a research project, noting that failing to disclose foreign collaborations could lead to sanctions. The agencies urged researchers to do their due diligence on any potential collaborators and outlined other cybersecurity best practices.

## State actions

* New York Passes Law Requiring Title VI Coordinators

[https://www.insidehighered.com/news/quick-takes/2025/08/28/new-york-passes-law-requiring-title-vi-coordinators](https://www.insidehighered.com/news/quick-takes/2025/08/28/new-york-passes-law-requiring-title-vi-coordinators)

> “By placing Title VI coordinators on all college campuses, New York is combating antisemitism and all forms of discrimination head-on,” she said in the press release. “No one should fear for their safety while trying to get an education. It’s my top priority to ensure every New York student feels safe at school, and I will continue to take action against campus discrimination and use every tool at my disposal to eliminate hate and bias from our school communities.”

> The State University of New York system had already mandated each of its campuses to bring on a Title VI coordinator by the fall 2025 semester.



## Institutional assaults

### Admissions

* The Trump administration is warning schools against using application essays, geography and other “unlawful proxies” for race to achieve diverse student bodies

[https://www.wsj.com/us-news/education/trumps-next-fight-with-universities-racial-proxies-in-admissions-c8677633?st=c9YJRf&reflink=article_gmail_share](https://www.wsj.com/us-news/education/trumps-next-fight-with-universities-racial-proxies-in-admissions-c8677633?st=c9YJRf&reflink=article_gmail_share)

> In late July, Attorney General Pam Bondi warned in a memo against using “unlawful proxies” for race—such as geography or applicant essays on overcoming hardships—in admissions. Soon after, the U.S. Education Department announced it would require universities to report new data on applicants, broken down by race, to “ensure race-based preferences are not used.”

> “There’s an effort to say that the law is something that it’s not. There’s an effort to say that it’s illegal to seek to have a diverse student body,” said Peter McDonough, general counsel for the American Council on Education, a university lobbying group.

> “Nothing in this opinion should be construed as prohibiting universities from considering an applicant’s discussion of how race affected his or her life,” Roberts added. However, “universities may not simply establish through application essays or other means the regime we hold unlawful today.”

> The University of California system has been complying with California’s ban on affirmative action for decades, said spokesman Omar Rodriguez. “At the same time, we remain committed to expanding access for all qualified students,” he said.

### Accreditation

* Watch out for middle states

(Thanks BE)

> Trouble at Columbia (non-compliance warning on Standard 2); trouble at KBCC (required to submit extensive suplemental material on budget); 3) trouble at Matropolitan College (non-compliance show cause based on not meeting Standard 4---Planning, resources, and Institutional improvement

### Harvard

* At Harvard, Trump administration cuts hit young scientists hard

[https://www.washingtonpost.com/education/2025/08/24/harvard-grad-students-research-cuts/](https://www.washingtonpost.com/education/2025/08/24/harvard-grad-students-research-cuts/)

> The cuts and uncertainty could disrupt the science pipeline and threaten experiments targeting cancer, autism, quantum physics, military robotics and hundreds of other realms, including Scully’s work in systems biology. At Harvard, more than 700 graduate students and nearly 800 postdoctoral researchers get their salaries, stipends or tuition support from federally funded research, according to court documents. Early-career researchers such as Scully are most at risk.

> People are panicking, said Henri Garrison-Desany, who was a research fellow in public health at Harvard but amid hiring and funding freezes spent this summer teaching yoga. “I’m just really sad about how much it is turning research back decades in the span of months,” he said, “and really derailing people’s careers.”

> The government had been a trusted partner, said Elisabeth Stelson, a postdoctoral research fellow at Harvard’s school of public health, but it now seems to be harming the things scientists care about most.

> People are watching years of their life’s work evaporate so quickly, she said. “We feel like the lost generation.”

* NYTimes: Harvard Is Making Changes Trump Officials Want, Even Without a Deal

[https://www.nytimes.com/2025/08/23/us/harvard-changes-academic-freedom-trump-deal.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/23/us/harvard-changes-academic-freedom-trump-deal.html?smid=nytcore-ios-share&referringSource=articleShare)

> But it has also taken a host of steps that align with the White House’s desires, checking off items on the administration’s detailed menu, which have ranged from eliminating diversity offices to ousting program leaders. In some cases, students and faculty members worry, the new, Trump-inspired policies may interfere with the freedom of expression that is central to the university’s mission.

> President Trump and his appointees have made their attack on Harvard a totem for the changes they want to see across America’s elite universities, using the government’s blunt power to force compliance in a manner never before seen. Universities across the country are watching closely, to see what Harvard might do and what it might be willing to sacrifice, as they seek a way forward for their own campuses.

> The Trump administration’s demands included eliminating diversity, equity and inclusion programs. In April, Harvard renamed its Office of Equity, Diversity, Inclusion and Belonging, which is now called the Office for Community and Campus Life. More recently, Harvard also took down websites for its Foundation for Intercultural and Race Relations, as well as websites for companion offices for gay and female students, and said they were merging them into a new, single center.

> The government has also sought leadership shake-ups in certain departments, including the Center for Middle Eastern Studies, after Jewish alumni and others accused the programs of sponsoring antisemitic programming. Harvard removed two of the center’s leaders, including Cemal Kafadar, a leading Turkish scholar, in March.

> And Trump officials asked for an end to Harvard’s partnership with Birzeit University, a top Palestinian college in the West Bank. Harvard said it had suspended the relationship and had struck up new ones with institutions in Israel.

> The A.A.U.P. is, for now, pressing forward with its own lawsuit against the Trump administration, even as Harvard would be likely to resolve, as part of any deal with the White House, the two federal court cases it filed. One seeks the restoration of $2.2 billion in funding that has been frozen or withdrawn by the federal government. Another opposes the Trump administration’s efforts to block international students.

* Will the Supreme Court’s Ruling on Research Grants Sink Harvard’s Lawsuit Against Trump?

[https://www.chronicle.com/article/will-the-supreme-courts-ruling-on-research-grants-sink-harvards-lawsuit-against-trump](https://www.chronicle.com/article/will-the-supreme-courts-ruling-on-research-grants-sink-harvards-lawsuit-against-trump)


### Columbia

* NYTimes: Columbia Got Most of Its Research Funding Back. The Damage Goes Deeper.

[https://www.nytimes.com/2025/08/25/nyregion/columbia-trump-federal-money-returned.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/25/nyregion/columbia-trump-federal-money-returned.html?smid=nytcore-ios-share&referringSource=articleShare)

> While hundreds of millions of dollars in frozen federal research funding has been restored, a smaller subset of grants in areas that are out of favor with the White House, including transgender health, have not. Columbia’s School of Public Health and medical center remain in austerity mode, with fewer slots for Ph.D. students and hiring delays caused by the original suspension of funding.

> And looming over the deal, researchers said, is a bleak national outlook for federal science funding, making some scientists feel as if they dodged a bullet only to face the possibility of a firing squad.

> An Aug. 7 executive order signed by President Trump, for example, requires additional review of federal scientific grant awards to ensure that they are “consistent with agency priorities and the national interest.” The White House has also proposed a 40 percent cut to the budget of the National Institutes of Health, the main source of medical research funding from the federal government, although a Senate committee has resisted the steep reduction.

> Still, the overall funding picture means that some damage cannot be contained. As Washington debates the cuts to science funding, Columbia and other research universities have instituted hiring freezes, cut expenses and reduced the number of students they will educate.

### Brown

* NYTimes: Law Firm Pressures Brown University to Erase Research on Anti-Wind Groups

[https://www.nytimes.com/2025/08/25/climate/brown-university-offshore-wind-marzulla.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/25/climate/brown-university-offshore-wind-marzulla.html?smid=nytcore-ios-share&referringSource=articleShare)

> A law firm representing opponents of offshore wind farms is demanding that Brown University retract research that details links between the fossil fuel industry and anti-wind groups.

> The demands come at a precarious time for the nation’s universities, which have become targets of a pressure campaign conducted by the Trump administration. Last month, Brown struck a deal with the government to restore lost federal research funding and end investigations into alleged discrimination.

> The Trump administration is trying to stop the country’s nascent wind industry, a source of energy that President Trump has disparaged since he failed to stop an offshore wind farm from being built within view of one of his Scottish golf courses.

> Marzulla Law L.L.C. is representing several groups that are fighting offshore wind, including Green Oceans, a nonprofit organization that is trying to overturn federal permits for Revolution Wind, a 65-turbine wind farm off the coast of Rhode Island.

> In an Aug. 11 letter to Brown’s general counsel, Mr. Marzulla objected to research published by the Climate and Development Lab at Brown that found that Green Oceans had spread misinformation about climate change and operated as part of “a fossil-fuel-funded disinformation network.”

> J. Timmons Roberts, who leads the Climate and Development Lab, said in an interview that his students had found that groups fighting offshore wind “have chosen to get in bed with some of the most anti-environment and anti-climate actors.” He called the letter “strategic harassment to shut me up and waste my time and make me more cautious.”

### George Mason

* Ed Dept. Says George Mason Violated Civil Rights Law

[https://www.insidehighered.com/news/quick-takes/2025/08/22/ed-dept-says-george-mason-violated-civil-rights-law](https://www.insidehighered.com/news/quick-takes/2025/08/22/ed-dept-says-george-mason-violated-civil-rights-law)

(Say Uncle)

> Gregory Washington, president of Virginia’s George Mason University, must apologize to the university community for “promoting unlawful discriminatory practices” in order to resolve allegations that the institution violated civil rights law, the Department of Education announced Friday.

> Acting Assistant Secretary for Civil Rights Craig Trainor said the unlawful practices began shortly after the murder of George Floyd, when Washington called on faculty and administrators to expunge campus of “racist vestiges” by “intentionally discriminat[ing] on the basis of race.”

> In addition to an apology, the Education Department is demanding that GMU post that statement “prominently” to the university’s website, remove any contrary statements from the past and revise campus policies to prevent future race-based programming. It also wants the institution to begin an annual training session for all individuals involved in recruitment, hiring, promotion or tenure decisions to emphasize the ban on racial consideration and provide records documenting compliance whenever they are requested moving forward.

(Also)

[https://www.chronicle.com/article/education-dept-finds-faculty-diversity-efforts-at-george-mason-u-were-discriminatory](https://www.chronicle.com/article/education-dept-finds-faculty-diversity-efforts-at-george-mason-u-were-discriminatory)

* George Mason Must Not Comply With the Government’s Demands (opinion)

[https://www.insidehighered.com/opinion/views/2025/08/25/george-mason-must-not-comply-governments-demands-opinion](https://www.insidehighered.com/opinion/views/2025/08/25/george-mason-must-not-comply-governments-demands-opinion)

> The message to George Mason, where I was a professor of public policy for nearly two decades, is clear: Equity is now presented as a civil rights violation.

> Title VI was meant to prevent discrimination, not to penalize institutions for recognizing that diversity matters. With courts allowing the consideration of diversity as one factor among many in holistic decisions, OCR’s stance appears to be a politically motivated shift away from long-standing interpretations—not a clear enforcement of the law. Just last week, a federal judge “struck down two Trump administration actions aimed at eliminating diversity, equity and inclusion programs at the nation’s schools and universities,” the Associated Press reported.

> Most alarming in OCR’s proposed resolutions is the demand for a personal apology from the university’s first Black president. Washington, who called for eliminating racist legacies on campus, is now being compelled to apologize for doing just that. This isn’t simply an institutional issue—it’s a deeply symbolic act that resembles public shaming of a leader of color for advocating inclusion. It evokes the disturbing history of targeting minority leaders through law and policy.

> Here again, ideology replaces impartial curation. A common thread emerges: Whether in higher education or national museums, diversity and sincere historical reflection are viewed not as civic strengths but as transgressions. Institutional autonomy and academic governance are being subordinated to partisan narratives.

> Universities must remain havens of reasoned inquiry, honest history and inclusive excellence. When federal agencies start dictating not only policy but the exact language leaders must use, we enter coercive territory.

> This moment is a clarion call for universities. Yesterday, it was the University of Pennsylvania and Harvard, dragged through headline-grabbing investigations. It was New College of Florida, where political appointees dismantled DEI programs and faculty governance. It was the University of Virginia, accused by the Department of Justice of defying federal antidiscrimination laws. Today it is Mason. Tomorrow, it could be UCLA, Michigan, Wisconsin or any other institution that values diversity, equity and academic freedom. No campus—public or private, flagship or regional—should assume it is immune.

> George Mason should reject the department’s findings and oppose this injustice. Capitulation is not compliance; it’s surrender.


* GMU President Rejects OCR Findings

[https://www.insidehighered.com/news/quick-takes/2025/08/25/gmu-president-refuses-apologize-rejects-ocr-findings](https://www.insidehighered.com/news/quick-takes/2025/08/25/gmu-president-refuses-apologize-rejects-ocr-findings)

> In a letter to GMU's board Monday, Washington’s attorney, Douglas F. Gansler, alleged that OCR cut its fact-finding efforts short and only interviewed two university deans before reaching the conclusions the Department of Education published Friday. Gansler wrote that “OCR’s letter contains gross mischaracterizations of statements made by Dr. Washington and outright omissions” related to the university’s DEI practices.

> Gansler also accused OCR of selectively interpreting various remarks by Washington, the first Black president in GMU’s history.

> “To be clear, per OCR’s own findings, no job applicant has been discriminated against by GMU, nor has OCR attempted to name someone who has been discriminated against by GMU in any context. Therefore, it is a legal fiction for OCR to even assert or claim that there has been a Title VI or Title IX violation here,” Gansler wrote in a 10-page letter.

(Also)

[https://www.chronicle.com/article/gmu-president-refuses-to-apologize-for-diversity-efforts-calls-ed-dept-claims-absurd](https://www.chronicle.com/article/gmu-president-refuses-to-apologize-for-diversity-efforts-calls-ed-dept-claims-absurd)

(and)

[https://www.washingtonpost.com/education/2025/08/25/george-mason-president-refuses-apology-dei/](https://www.washingtonpost.com/education/2025/08/25/george-mason-president-refuses-apology-dei/)


* Virginia Democrats reject more of Youngkin’s picks for college boards

[https://www.washingtonpost.com/dc-md-va/2025/08/28/schools-youngkin-virginia-george-mason/](https://www.washingtonpost.com/dc-md-va/2025/08/28/schools-youngkin-virginia-george-mason/)

> A panel of Virginia senators on Thursday rejected more of Gov. Glenn Youngkin’s picks to serve on college boards, intensifying a showdown between the administration and lawmakers and plunging the state’s institutions of higher education into legal limbo.

> Members of the state Senate’s Privileges and Elections committee voted 6 to 8 along party lines against 14 people who the Republican governor nominated to sit on governing boards at George Mason University, the University of Virginia and the Virginia Military Institute.

> Democrats have now refused to seat a total of 22 people in two months on college boards based on concerns about their qualifications, backgrounds and intentions. The senators have said appointees that the committee rejects can no longer serve on the boards, an argument disputed by the state’s top Republicans.

> The Thursday vote by Senate Democrats could have broad implications at George Mason in Northern Virginia, which is left with only six confirmed members on its 16-seat board. The bylaws for the governing board require eight members to constitute a quorum.

### Others

* Howard President Steps Down, Former President Appointed Interim

[https://www.insidehighered.com/news/quick-takes/2025/08/25/howard-president-steps-down-former-president-appointed-interim](https://www.insidehighered.com/news/quick-takes/2025/08/25/howard-president-steps-down-former-president-appointed-interim)

> University officials declined to comment about why Vinson is leaving only two years after he took up the helm

> But the past year has also brought its share of challenges. In May, the Trump administration proposed cutting Howard’s federal funding by $64 million in fiscal year 2026, bringing it back to its 2021 funding level.



## Blowback

* NYTimes: Purging ‘Equity’ Programs, G.O.P. Defunded Its Own Roads

[https://www.nytimes.com/2025/08/26/us/politics/republicans-transportation-grants.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/26/us/politics/republicans-transportation-grants.html?smid=nytcore-ios-share&referringSource=articleShare)

> When the Biden administration created a grant program three years ago to fund transportation projects explicitly dedicated to promoting “neighborhood access and equity,” officials in St. George, Utah, saw an opportunity. ...

> All told, funding was yanked back for 55 projects, 19 of which had been set to be built in Republican congressional districts, according to federal data obtained by The New York Times. They included rebuilding highways, new underpasses and overpasses, and pedestrian and bike trails. The biggest included in G.O.P.-held districts included $147 million to design and build a 30-mile trail in Jacksonville, Fla., represented by Representative Aaron Bean; and $74.9 million to rebuild a highway in Missoula, Mont., represented by Representative Ryan Zinke; and the project in St. George, represented by Representative Celeste Maloy.



## Tracking projects

* SCIMaP -- map of impact of NIH cuts

[https://scienceimpacts.org/](https://scienceimpacts.org/)



## AI misdeeds

* Fewer Young People See Math Skills as Very Important in Work

[https://www.insidehighered.com/news/student-success/academic-life/2025/08/25/fewer-young-people-see-math-skills-very-important](https://www.insidehighered.com/news/student-success/academic-life/2025/08/25/fewer-young-people-see-math-skills-very-important)

> Tabanli said it can be hard to convince many Gen Z and Alpha students that math content is necessary for their daily lives, in part because access to information is so convenient and they can perform calculations on their phones or online.

> One reason a young adult might not rate math skills highly is because many students face undue math anxiety or a skepticism about their own ability to do math, falling into the belief that they’re not “math people,” Tabanli said.

> In response, Tabanli believes professors should help students apply computational skills to their daily lives or link content to other classes to encourage students to invest in their math learning. While this may be an additional step for a faculty member to take, Tabanli considers it a disservice to neglect this connection.

* There is one way for colleges to defeat AI cheating—and it’s every student’s worst nightmare. Blue books are back.

[https://www.wsj.com/business/chatgpt-ai-cheating-college-blue-books-5e3014a6?st=4HNgEb&reflink=article_gmail_share](https://www.wsj.com/business/chatgpt-ai-cheating-college-blue-books-5e3014a6?st=4HNgEb&reflink=article_gmail_share)

> Students outsourcing their assignments to AI and cheating their way through college has become so rampant, so quickly, that it has created a market for a product that helps professors ChatGPT-proof school. As it turns out, that product already exists. In fact, you’ve probably used it. You might even dread it.

> It’s called a blue book.

> The mere thought of that exam booklet with a blue cover and blank pages is enough to make generations of college kids clam up—and make their hands cramp up.

> But inexpensive pamphlets of stapled paper have become a surprisingly valuable tool for teachers at a time when they need all the help they can get.

> All of which explains how a paper company in Pennsylvania has unexpectedly found itself on the front lines of the classroom AI wars.

## And just because it is fun

* CUNY Plans to Buy Manhattan Campus

[https://www.insidehighered.com/news/quick-takes/2025/08/29/cuny-plans-buy-manhattan-campus](https://www.insidehighered.com/news/quick-takes/2025/08/29/cuny-plans-buy-manhattan-campus)

(Thanks VC!)

> CUNY is purchasing 101,542 square feet across three floors in the shared building, which officials told Bloomberg they intend to use as a temporary site for the Hunter-Bellevue School of Nursing amid ongoing construction projects. The sale will require approval from bondholders as well as Metropolitan College’s accreditor, the Middle States Commission on Higher Education.

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
