# Aug 22

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

Thanks to JC for sharing links this week!

## Heads up

* 4 dead as Legionnaires’ disease continues to spread in NYC

(City College was tested and tests were negative)

[https://thehill.com/homenews/state-watch/5454048-deadly-legionnaires-disease-spreading-nyc/amp/](https://thehill.com/homenews/state-watch/5454048-deadly-legionnaires-disease-spreading-nyc/amp/)

(This is Marshak building.)

> Legionnaires’ disease is a type of pneumonia that is caused by Legionella bacteria, which grow in warm water and spread through building water systems. The city’s outbreak has been linked to cooling towers, which use water and a fan to cool buildings.

> Health officials disclosed Thursday that 12 cooling towers within Harlem buildings tested positive for the bacteria. Those affected include Harlem Hospital, a city health clinic, a popular retail center on 125th Street, a CUNY college science building and the Harlem condo center on Lenox Avenue.

* Test results

[https://www.ccny.cuny.edu/presidentsoffice/blog/notice-legionella-negative-test-results-marshak-building-cooling-tower](https://www.ccny.cuny.edu/presidentsoffice/blog/notice-legionella-negative-test-results-marshak-building-cooling-tower)

> We are pleased to inform that the test results were negative for legionella bacteria. This confirms that the cooling tower system is in compliance with The New York CITY Department of Health and mental Hygiene (NYC DOHMH) requirements and poses no health risk to building occupants or the community.

## Letters

> Fight Cuts, Defend Higher Education at the University of Oregon

[https://actionnetwork.org/petitions/fight-cuts-defend-higher-education-at-the-university-of-oregon](https://actionnetwork.org/petitions/fight-cuts-defend-higher-education-at-the-university-of-oregon)

(Thanks JC)

> ... The anticipated layoffs also appear to have a disproportionate impact on the Humanities, which are key to a liberal arts education that teaches critical thinking, effective self-expression, and a multiplicity of perspectives. ...


## How best to describe the times we are in

* Opinion | They’re Killing the Humanities On Purpose

[https://www.chronicle.com/article/theyre-killing-the-humanities-on-purpose](https://www.chronicle.com/article/theyre-killing-the-humanities-on-purpose)

* NYTimes: Trump Is Playing at Being a Wartime President

[https://www.nytimes.com/2025/08/19/opinion/trump-intrusion-lincoln-roosevelt.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/19/opinion/trump-intrusion-lincoln-roosevelt.html?smid=nytcore-ios-share&referringSource=articleShare)

(Much here in T. Edsall's piece applies to higher education)

> Culturally, Trump is seeking to redefine the boundaries of public discourse: pressuring universities, elevating grievance politics and reshaping federal agencies to reflect ideological loyalty rather than expertise or experience.

> For Sean Wilentz, a historian at Princeton, the word “intrusive” fails to capture the full scope of Trump’s agenda. Writing by email, Wilentz argued that Trump "has intimidated major institutions of civil society, including universities, major law firms, and the corporate media, to bend them to his will. He has deployed the military for political purposes. He has militarized ICE and turned it into nation’s largest law enforcement force, accountable only to himself and Stephen Miller, thus laying the basis for a police state. ..."

> For Trump, the rule of law is not a principle of democratic government; it is a speed bump on the road to exercising unilateral authority. In his own mind, he is on a path to the ultimate in gold-plated power.



## Shared governance

* Tex. Boards Abolish Faculty Senates, Create Toothless Councils

[https://www.insidehighered.com/news/faculty-issues/shared-governance/2025/08/22/tex-boards-abolish-faculty-senates-create](https://www.insidehighered.com/news/faculty-issues/shared-governance/2025/08/22/tex-boards-abolish-faculty-senates-create)

> The University of Texas System Board of Regents voted Thursday to disband the system’s long-standing faculty senates in compliance with Senate Bill 37, the sweeping Texas higher education law that gives university boards and presidents control over faculty governing bodies.

> The UT board also voted Thursday to create faculty advisory groups, which will “perform the work of faculty governance bodies”—such as reviewing degree requirements, suggesting curricular changes, coordinating campus events and revising the faculty handbook—while keeping all decision-making power in the hands of the administration.

> But the groups won’t give the faculty independent representation or any real power. In accordance with SB 37, the board bylaws now state, “a faculty council is advisory only and may not be delegated the final decision-making authority on any matter.”

> Even as university governing boards design their toothless, SB 37–compliant groups, two professors at the University of Houston on Monday unveiled what they’re calling the Faux Faculty Senate. “I know that people feel that faculty senates are kind of arcane … but it’s a part of civil society,” said David Mazella, an associate professor in the English Department at the University of Houston and president-elect of the faux senate. “[SB 37] is an antidemocratic bill that essentially eliminates the faculty voice in order for the state to directly control what we do.”



## Academic freedom

* ‘Higher Ed Alone Cannot Save Democracy’ -- interview with AAUP leader

[https://www.insidehighered.com/news/faculty-issues/labor-unionization/2025/08/19/aaup-president-higher-ed-alone-cannot-save#](https://www.insidehighered.com/news/faculty-issues/labor-unionization/2025/08/19/aaup-president-higher-ed-alone-cannot-save#)

(Thanks JC)

> Q: We’re now more than six months into Trump’s second administration. What is the current state of academic freedom?

> A: It’s being washed over by an administration that has no respect, or even probably understanding, of the concept. We’re seeing massive infringement of academic freedom at the individual level. But then, it’s also the academic freedom of institutions.

> I never expected the Trump administration to take a democracy, or the health of American society, to heart, because they’re grifters and they’re in it for their own personal power and their own personal wealth. But I did not expect that they would be so outlandishly intent on destroying a sector that’s so important to the fundamental values and power of American society.

> Vance and Trump and [Christopher] Rufo and Stephen Miller and the ilk that run our government are fascist in a 21st-century variant—not operating within the constructs of our society, [but] trying to rip those constructs down.

> [Secondly,] we sued the Trump administration on our own six times. With our AFT [American Federation of Teachers] as our [union] affiliate … probably another three or four times.

> They’re doing so many things that are so obviously unconstitutional and illegal, and so we’re trying to use the courts to slow them down.

> The third [tactic]—and you’ll see more of this, but you’ve probably been watching and seen it throughout the spring of last year—is getting our people into the streets, fighting back, offering a different vision. This has primarily happened in response to the NIH, NSF cuts.

> The fourth area is that we need to offer … a countervision of higher education to the Trump vision, which is higher education ideologically controlled by the federal government, in its most extreme form, as well as the complete destruction of our biomedical research infrastructure and our research over all.

> We’re working on a policy vision that will move us into the midterms … a counterimaginary of higher ed to the imaginary that’s been developed by the Trump administration, by Chris Rufo, one where we’re all Marxist ideologues indoctrinating our students.

> The last area is that we’re supporting the development of organizing at the campus level to challenge and hold our administrations accountable, whether supporting the mutual aid defense compact projects that [have] mushroomed across higher ed, or supporting the fights at campus levels around academic freedom and freedom of speech, or any other number of things that we’re doing to support faculty at the campus level, to get their administrations to hold firm and not to bow to the Trump administration’s demands before they even make them.


## Freedom of expression

* NYTimes: A Critic of Universities Is Rallying to Defend Them in the Trump Era

[https://www.nytimes.com/2025/08/22/arts/fire-freedom-expression-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/22/arts/fire-freedom-expression-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> The Foundation for Individual Rights and Expression, an increasingly prominent free-speech organization, has long been known as a fierce opponent of campus political correctness. Since its founding in 1999, it has been celebrated for defending conservatives and other dissidents from the prevailing liberal culture at America’s universities.

> So when the group announced a lawsuit this month challenging the Trump administration’s efforts to deport noncitizen students who expressed pro-Palestinian views, some admirers were dismayed.



### Anti-woke/anti-DEI is simply racism

* Federal District Judge Rules Against Trump’s Anti-DEI Orders

[https://www.insidehighered.com/news/quick-takes/2025/08/18/federal-district-judge-rules-against-trumps-anti-dei-orders](https://www.insidehighered.com/news/quick-takes/2025/08/18/federal-district-judge-rules-against-trumps-anti-dei-orders)

> In her opinion, Gallagher focused less on the legality of the attempt to ban DEI itself, but rather the process through which the president and secretary of education tried to do so.

> “This court takes no view as to whether the policies at issue in this case are good or bad, prudent or foolish, fair or unfair. But, at this stage too, it must closely scrutinize whether the government went about creating and implementing them in the manner the law requires. Here, it did not,” the judge wrote. “By leapfrogging important procedural requirements, the government has unwittingly run headfirst into serious constitutional problems.”

> That said, she did explain the ways Trump's policy violated the Constitution, saying, “The government cannot proclaim that it ‘will no longer tolerate’ speech it dislikes because of its ‘motivating ideology’—that is a ‘blatant’ and ‘egregious’ violation of the First Amendment.”

> Since the Education Department’s anti-DEI guidance was enjoined, the Trump administration has made other attempts to block the same academic practices. Most recently, the Department of Justice published a nine-page memo that stated that DEI is unlawful and discriminatory.

(See)

[https://www.insidehighered.com/news/government/2025/07/30/doj-declares-slew-dei-practices-unlawful-memo](https://www.insidehighered.com/news/government/2025/07/30/doj-declares-slew-dei-practices-unlawful-memo)



* Colleges Rushed to Comply With Trump’s Anti-DEI Guidance. A Judge Just Struck It Down. Now What?

[https://www.chronicle.com/article/colleges-rushed-to-comply-with-trumps-anti-dei-guidance-a-judge-just-struck-it-down-now-what](https://www.chronicle.com/article/colleges-rushed-to-comply-with-trumps-anti-dei-guidance-a-judge-just-struck-it-down-now-what)

> U.S. District Judge Stephanie Gallagher, a Trump appointee, ruled on Thursday that the U.S. Education Department acted unlawfully when it issued two guidance documents telling institutions to dismantle DEI programs or risk losing federal funding.

* NYTimes: In Trump’s Ideal Picture of America, Diversity Is Taboo

[https://www.nytimes.com/2025/08/21/us/politics/trump-diversity-black-americans.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/21/us/politics/trump-diversity-black-americans.html?smid=nytcore-ios-share&referringSource=articleShare)

> Over the past seven months, Mr. Trump’s words and actions have revealed what he sees as an ideal picture of the United States, in which the concept of diversity is taboo; the traditional power centers in America — white and wealthy men — get the benefit of the doubt; immigrants are suspect or unwelcome; and people of color must set their grievances and outrage aside.

> In the view of his critics, Mr. Trump has used the power of the federal government to promote a vision of America that not only challenges the legitimacy of the Black experience, but also demeans and dehumanizes people of color. In the process, they say, he has elevated and even endorsed a version of American culture that venerates a white-dominated society of old, and casts the history and reality of race in the United States as unwelcome or suspiciously “woke.”

> In the first months of his second term, Mr. Trump has abandoned core tenets of the Civil Rights Act of 1964. The Pentagon has ordered military leaders to review all books in their libraries that address racism and sexism. The administration announced this week that it would begin screening immigrants seeking to live or work in the United States for “anti-American ideologies.” Mr. Trump has banned almost every refugee from entering the country, with the exception of white South African farmers who federal officials have said would better assimilate into the United States.

> Federal agencies have obscured published references to the contributions of Black heroes, from the Tuskegee Airmen who fought in the military, to Harriet Tubman, who guided enslaved people along the Underground Railroad. He has accused the Smithsonian Institution of incorporating “divisive, race-centered ideology” in its exhibits on race.

> Several of Mr. Trump’s appointees have amplified extremist views, including on official social media accounts. The Department of Homeland Security in June shared a poster that called for reporting “foreign invaders,” an image that was originally shared by a podcaster who hosts a Christian nationalist show and calls himself a supporter of the “Old American Right.” The host has said the concept affirms “the domination and pre-eminence of the European-derived peoples, their institutions and their way of life.”


* Mizzou Calls Black 2 Class Event Example of “Discrimination”

[https://www.insidehighered.com/news/students/diversity/2025/08/21/mizzou-calls-black-2-class-event-discrimination](https://www.insidehighered.com/news/students/diversity/2025/08/21/mizzou-calls-black-2-class-event-discrimination)

> Mizzou President Mun Choi added in a statement that “when holding events using university facilities, student organizations must avoid excluding individuals based on race.”

> This follows a similar dispute last year, when the university changed the name of a similar LBC event from the Welcome Black BBQ to the Welcome Black and Gold BBQ, a nod to the university’s colors. This year, LBC declined to participate, letting university officials know in July.

> “Let’s be clear,” the student group [LBC] wrote. “These actions are a deliberate act of erasure … Recreational spaces for students of all identities are CRUCIAL.”


## Visas

* Many U.S. Colleges May Close Without Immigrants And International Students, Report Finds

[https://www.forbes.com/sites/stuartanderson/2025/08/14/many-colleges-may-close-without-immigrants-and-international-students/](https://www.forbes.com/sites/stuartanderson/2025/08/14/many-colleges-may-close-without-immigrants-and-international-students/)

> “Without immigrants, international students and the children of immigrants, the undergraduate student population in America would be almost 5 million students smaller in 2037 than 2022, or about two-thirds of its current size, while the graduate student population would be at least 1.1 million students smaller, or only about 60% of its current size,” according to the NFAP study.

> America’s population shifts portend hardship for U.S. colleges and universities and the communities surrounding them. That means their future may rest on whether U.S. policymakers adopt welcoming immigration policies or Trump officials follow through on an anti-immigration agenda. The Trump administration has adopted what educators see as aggressive measures against international students, including compelling Columbia University to reduce its “dependence” on international students. The administration has also set a goal of deporting one million or more immigrants.

* Trump administration has revoked 6,000 student visas, official says - The Washington Post

[https://www.washingtonpost.com/education/2025/08/19/student-visas-revoked-6000-trump/](https://www.washingtonpost.com/education/2025/08/19/student-visas-revoked-6000-trump/)

> A department spokesperson said in an email that it has revoked more than 6,000 student visas, of which about 4,000 were for crimes including assault, driving under the influence and burglary.

> Between 200 and 300 student visas were revoked because of “support for terrorism,” the official said, without elaborating. Trump administration officials have accused students of supporting terrorism by participating in pro-Palestinian activism in several high-profile cases this year.

> It was not immediately clear whether the students whose visas were revoked because of alleged law violations had been convicted of any crimes.

* NYTimes: Trump’s Tactics Mean Many International Students Won’t Make It to Campus

[https://www.nytimes.com/2025/08/20/us/trump-visa-vetting-international-students.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/20/us/trump-visa-vetting-international-students.html?smid=nytcore-ios-share&referringSource=articleShare)

> Between the federal government’s heightened vetting of student visas and President Trump’s travel ban, the number of international students newly enrolled in American universities seems certain to drop — by a lot.

> There were about a million international students studying in the United States a year ago, according to figures published by the State Department. Data on international student enrollment is not expected to be released until the fall. But higher education is already feeling the pain and deeply worried about the fallout.

> In China and India, there have been few visa appointments available for students in recent months, and sometimes none at all, according to the Association of International Educators, also known as NAFSA, a professional organization. If visa problems persist, new international student enrollment in American colleges could drop by 30 to 40 percent overall this fall, a loss of 150,000 students, according to the group’s analysis.

* More Barriers on the Horizon for International Students

[https://www.insidehighered.com/news/global/international-students-us/2025/08/20/more-barriers-horizon-international-students](https://www.insidehighered.com/news/global/international-students-us/2025/08/20/more-barriers-horizon-international-students)

> The Trump administration is planning to limit how long international students can remain in the U.S., likely mirroring a plan proposed at the end of Trump’s first term with the same name, advocacy groups and immigration attorneys say.

> The regulations are expected to replace “duration of status,” a 1991 rule that allows international students to remain in the country as long as they are enrolled at a college or university. In 2020, the administration proposed limiting that time to just four years—a period shorter than most Ph.D. programs and shorter than the average student takes to complete a bachelor’s degree—though it would have allowed students to apply for extensions. Students from certain countries, including those the administration said were state sponsors of terrorism and those with high overstay rates, would have been afforded just two years.

## Funding cuts

* Trump budget officials claim sweeping spending power from Congress, records show

[https://www.washingtonpost.com/business/2025/08/19/trump-budget-congress-impoundment/](https://www.washingtonpost.com/business/2025/08/19/trump-budget-congress-impoundment/)

> The Trump administration is asserting authority to withhold billions of dollars from low-income housing services, education assistance, medical research grants and other programs approved by Congress, according to public documents released Monday.

> The new practices — which increase the leverage and power of budget chief Russell Vought — are likely to reignite a clash over the administration’s power to freeze dollars approved by Congress, usurping authority that the legislative branch has under the Constitution. The power struggle dates to President Donald Trump’s first term, when his refusal to release congressionally approved money for Ukraine helped spark a House impeachment, from which he was acquitted in the Senate.

> The agency’s newly released documents, made public under the court order, show Trump’s budget office is imposing litmus tests on releasing money — demanding plans from agencies to show they are following guidance Trump has laid out in executive actions, such as avoiding spending on diversity programs. While Trump has authority to issue those directives, experts say they do not, under law, carry the same weight as congressional actions.

* We deny the government’s motion

[https://www.documentcloud.org/documents/26070574-ucresearcherstayca9082125/](https://www.documentcloud.org/documents/26070574-ucresearcherstayca9082125/)

>  the district court [for the Northern District of California] issued a class-wide preliminaryinjunction ordering three government agencies to reinstate research grants theagencies had terminated pursuant to certain Executive Orders. The governmentappealed and moved for a partial stay pending appeal of the preliminaryinjunction.

### NIH

* NIH Director Orders Review of All Current, Planned Research

[https://www.insidehighered.com/news/quick-takes/2025/08/19/nih-director-orders-review-all-current-planned-research](https://www.insidehighered.com/news/quick-takes/2025/08/19/nih-director-orders-review-all-current-planned-research)

> The National Institutes of Health’s director ordered employees to “conduct an individualized review of all current and planned research activities,” including active grants and funding opportunity announcements, according to images of a document provided to Inside Higher Ed. The review comes amid concerns that the NIH won’t distribute all of its allocated grant money by the time the federal fiscal year ends Sept. 30, meaning those dollars will return to the U.S. Treasury.

> The document images, provided by a source who wished to remain anonymous due to fear of retaliation, show that NIH director Jay Bhattacharya sent the memo Friday and that the review is effective immediately. According to the memo, “relevant NIH personnel” must review grants, funding opportunity announcements, contracts, contract solicitations, applications for new and competing renewal awards, intramural research and research training programs, cooperative agreements, and “other transactions.”

* NYTimes: Trump Administration Updates: Supreme Court Rules N.I.H. Grants for Disfavored Research Can Be Cut

[https://www.nytimes.com/live/2025/08/21/us/trump-news?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/live/2025/08/21/us/trump-news?smid=nytcore-ios-share&referringSource=articleShare)

* SCOTUS Says NIH Doesn’t Have to Restore Canceled Grants

[https://www.insidehighered.com/news/government/science-research-policy/2025/08/21/scotus-says-nih-doesnt-have-restore-canceled](https://www.insidehighered.com/news/government/science-research-policy/2025/08/21/scotus-says-nih-doesnt-have-restore-canceled)

> The United States Supreme Court is allowing the National Institutes of Health to cut nearly $800 million in grants, though it left the door open for the researchers to seek relief elsewhere.

(Can't blame this one on Roberts)

> “The reason is straightforward,” Kavanaugh wrote. “The core of plaintiffs’ suit alleges that the government unlawfully terminated their grants. That is a breach of contract claim. And under the Tucker Act, such claims must be brought in the Court of Federal Claims, not federal district court.”


(also)

[https://www.chronicle.com/article/tracking-trumps-higher-ed-agenda](https://www.chronicle.com/article/tracking-trumps-higher-ed-agenda)

## Federal Agencies

### DOE/OCR

* Under Trump, the Education Dept. has flipped its civil rights mission

[https://www.washingtonpost.com/education/2025/08/18/trump-education-department-civil-rights/](https://www.washingtonpost.com/education/2025/08/18/trump-education-department-civil-rights/)

> The Education Department’s Office for Civil Rights is so short-staffed that some attorneys have as many as 300 cases, making it impossible to devote attention to most of them, current and former employees said. Fewer cases are being closed, and 90 percent of those resolved were dismissed, typically without an investigation, up from 80 percent last year, according to data obtained by The Washington Post.

> At the same time, under Trump, the civil rights office has announced investigations of at least 99 schools, often based on news coverage or complaints from conservative groups. As of early August, the administration had launched 27 directed investigations, probes that are opened without an outside complaint, court filings show.

> Now, the office has opened several investigations into whether programs aimed at addressing inequities amount to illegal discrimination in favor of those students. Forty-five colleges, for instance, are being investigated for working with the PhD Project, a program that has tried to boost the number of Black, Hispanic and Native American students who earn doctorates in business.

> About half of the civil rights office’s employees were laid off in March as part of a deep cut to the Education Department’s staff. Seven of 12 regional offices were closed including the Cleveland office. The remaining five offices also lost personnel due in part to incentive programs that paid people to resign or retire early.

> “We have been left with thousands of cases that need to be reassigned and need to be handled by a small group of people,” said one attorney, whose caseload increased fivefold.

## Institutional assaults

### Harvard

* NYTimes: Trump Wants Universities to Show Him the Money, or No Deal

[https://www.nytimes.com/2025/08/19/us/politics/trump-universities-financial-penalties.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/19/us/politics/trump-universities-financial-penalties.html?smid=nytcore-ios-share&referringSource=articleShare)

(Again we see this reporting from the same trio of writers)

> The emerging agreement with Harvard would see the school spend $500 million, owing to Mr. Trump’s demand that the university spend more than double what Columbia agreed to pay.

(But we also see some other framing)

> Critics have likened Mr. Trump’s methods to extortion.

> owing to Mr. Trump’s demand that the university spend more than double what Columbia agreed to pay.

> How Mr. Trump arrives at his figures for financial penalties is not entirely clear, but he has suggested that challenging his administration as Harvard did raises the stakes. He noted in May that Columbia had taken itself off “the hot seat” by negotiating with the government without availing itself to legal remedies. Harvard sued the administration, leading to many weeks of acrimony before talks restarted.

> “Every time they fight, they lose another $250 million,” Mr. Trump said of Harvard in the spring.

> “Harvard has to understand, the last thing I want to do is hurt them,” he added. “They’re hurting themselves. They’re fighting.”

(How to spin this as anything systematic and just is impossible it seems)

> The White House has not publicly explained the formula for the U.C.L.A. demand.

> But officials from several universities have privately described feeling as if they had little choice but to take Mr. Trump’s demands seriously, no matter how exorbitant they seem, given the government’s leverage in funding medical, national security and other research that schools perform.

> Mr. Trump appears to have a limited interest in the finer details of the financial settlements. He has not insisted, for instance, that universities write checks to the Treasury Department — Brown University will spend $50 million on state work force development programs — and there is no evidence that Mr. Trump has sought to direct money to pursuits like his presidential library. But government officials have made clear there is little room to haggle over the price tags.

> Gov. Gavin Newsom and other state officials were even sharper in their response, condemning the demand as “a billion-dollar political shakedown from the pay-to-play president” and “disgusting political extortion.” Mr. Newsom indicated he would sue.

### University of Chicago

* UChicago Lost Money on Crypto, Then Froze Research When Federal Funding Was Cut

[https://stanfordreview.org/uchicago-lost-money-on-crypto-then-froze-research-when-federal-funding-was-cut/](https://stanfordreview.org/uchicago-lost-money-on-crypto-then-froze-research-when-federal-funding-was-cut/)

> On January 28, hours after the Trump administration announced the first round of grant cancellations (which was later scaled back before being renewed last week), UChicago administrators sent out an alarming directive to researchers at the school:

> “We are requesting that all University researchers working on federal grants temporarily suspend their non-personnel spending on [sic] federal grants as much as possible during this period of substantial uncertainty. For example, do not make any additional spending commitments, purchase new supplies or equipment, start new experiments, embark on funded travel, etc.”

> UChicago has since walked back their directive, sending a clarifying email that researchers could resume normal spending, unless they’d received a specific directive otherwise. However, behind the scenes, the situation remains dire: Labs have received orders to downsize, faculty are being paid out to retire early, and fear and uncertainty pervade the academic community.

> UChicago’s financial position is clear: Unlike near-peer institutions, its endowment is not large enough to sustain its spending and debt. The university carries nearly $6 billion in debt while running annual budget deficits exceeding $200 million, all on an endowment three times smaller than Stanford’s. To compensate, the university has focused on expanding lucrative certification programs, increasing donations, raising tuitions, and cutting costs, though many faculty and students viscerally disagree with the administration on which costs to cut.

> Possibly the most notorious example is the university’s foray into cryptocurrency. Four sources, as well as widespread campus rumors, allege that the university lost tens of millions investing in crypto around 2021. Given UChicago’s extraordinary 37.6% endowment gain that year, far beyond what conventional investments would have yielded, it’s likely they took significant risks. But if those gambles paid off in the short term, they quickly unraveled. ... UChicago’s endowment remains lower today than in 2021.

(See from last week "UChicago Reducing, Freezing Ph.D. Admissions for Multiple Humanities Programs")

(Also )

 https://www.chronicle.com/newsletter/the-review/2025-08-18


* More UChicago Ph.D. Programs Will Pause Admissions

[https://www.insidehighered.com/news/admissions/graduate/2025/08/21/more-uchicago-phd-programs-will-pause-admissions](https://www.insidehighered.com/news/admissions/graduate/2025/08/21/more-uchicago-phd-programs-will-pause-admissions)

> The University of Chicago’s Arts and Humanities Division is now pausing new Ph.D. student admissions for the 2026–27 academic year across all departments except philosophy and one program within the music department. The move expands on last week's announcement from the dean that about half of all departments would pause admissions, while the rest would reduce the number of admissions.

> The departments that won’t be accepting Ph.D. students now include art history, cinema and media studies, classics, comparative literature, East Asian languages and civilizations, English language and literature, Germanic studies, linguistics, Middle Eastern studies, Romance languages and literatures, Slavic languages and literatures, and South Asian languages and civilizations, plus the music department’s ethnomusicology and history and theory of music programs.

> The Social Sciences Division has also announced it will not admit Ph.D. students into four programs in 2026-27: anthropology, political economy, social thought, and conceptual and historical studies of science. The UChicago Crown Family School of Social Work, Policy and Practice had earlier announced it was pausing Ph.D. admissions and the Harris School of Public Policy said it was pausing admissions for the Harris Ph.D. (in public policy studies), the political economy Ph.D. and the master of arts in public policy with certificate in research methods.

### Haverford

> DOE investigates Haverford

[https://www.inquirer.com/education/us-education-department-investigation-haverford-college-20250820.html](https://www.inquirer.com/education/us-education-department-investigation-haverford-college-20250820.html)

(Thanks JC. Sadly this is behind a paywall, but by now we could have AI write the script. Ha, a little googling shows this:)

[https://www.ed.gov/about/news/press-release/us-department-of-education-initiates-title-vi-investigation-haverford-college-allegedly-tolerating-anti-semitic-harassment](https://www.ed.gov/about/news/press-release/us-department-of-education-initiates-title-vi-investigation-haverford-college-allegedly-tolerating-anti-semitic-harassment)


> This investigation comes amid credible reports ... “Like many other institutions of higher education, Haverford College is alleged to have ... said Acting Assistant Secretary for Civil Rights Craig Trainor. ... During President Raymond’s Congressional testimony, she claimed that there is “no room for discrimination” at Haverford but failed to give a concrete example of an action taken to combat alleged anti-Semitic harassment ...

## Blowback

* NYTimes: How College Financial Troubles Could Reshape the Student Experience

[https://www.nytimes.com/2025/08/12/us/college-financial-troubles-student-experience.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/12/us/college-financial-troubles-student-experience.html?smid=nytcore-ios-share&referringSource=articleShare)

> Colleges are eliminating or consolidating programs, sometimes dozens of them on a single campus. The University of North Carolina at Chapel Hill is planning to more than halve its financial aid budget for out-of-state students. From coast to coast, graduate schools are admitting fewer applicants.

> The financial squeeze comes just as demographic trends point toward plunging enrollments in the coming years that could force further belt-tightening.

> Although months may pass before some of the most drastic shifts take effect, students and administrators alike are facing uncertainty over how much a school could potentially change over the course of a semester, much less an entire degree program.

> Some of the turmoil traces directly to the Trump administration, which has been seeking to punish a clutch of elite schools. It is also, more broadly, trying to transform the financial ties between Washington and the nation’s colleges.

* A ‘Great Defection’ threatens to empty universities and colleges of top teaching talent

[https://hechingerreport.org/a-great-defection-threatens-to-empty-universities-and-colleges-of-top-teaching-talent/](https://hechingerreport.org/a-great-defection-threatens-to-empty-universities-and-colleges-of-top-teaching-talent/)

(Thanks JC!)

> With higher education under political assault, and opportunities as well as job security diminished by enrollment declines, Cossette felt burnt out and disillusioned. So she quit her hard-won job as an assistant professor of American government at a small private college in Maryland and used the skills she’d learned to go into business for herself as a freelance copy editor.

> Now Cossette is hearing from other newly minted Ph.D.s and tenured faculty who want out — so many, she’s expanded her business to help them leave academia, as she did.

> An exodus appears to be under way of Ph.D.s and faculty generally, who are leaving academia in the face of political, financial and enrollment crises. It’s a trend federal data and other sources show began even before Trump returned to the White House.

> As for faculty, more than a third of provosts reported higher-than-usual turnover last year, in a survey by Hanover Research and the industry publication Inside Higher Ed. That was before the turmoil of this late winter and spring.

> “People who can get out will get out,” said L. Maren Wood, director and CEO of the Center for Graduate Career Success,

> “You’re basically knee-capping that younger generation, which undermines the intergenerational dynamism that takes place in higher education. And that trickles down into the classroom,” said Isaac Kamola, an associate professor of political science at Trinity College and head of the Center for the Defense of Academic Freedom at the American Association of University Professors, or AAUP.

## AI misdeeds

* Rise of the Incompetents (opinion)

[https://www.insidehighered.com/opinion/views/2025/08/22/rise-incompetents-opinion](https://www.insidehighered.com/opinion/views/2025/08/22/rise-incompetents-opinion)

> In one of the articles I found myself scrolling, John Villasenor, writing for the Brookings Institution, suggested that LLMs would lead to “the democratization of good writing.” I was surprised to see that description. The ChatGPT-produced assignments I see on a weekly basis are rarely mistakable for “good.”

(The USS also believes AI will democratize learning)

> More to the point, research suggests that uniform style and content will not produce a level playing field of competent writers but, more likely, a ceiling of barely capable thinkers. In a study published by Nature Human Behaviour, researchers discovered that “reliance on ChatGPT … reduces the diversity of ideas in a pool of ideas,” to the degree that “94 percent of ideas from those who used ChatGPT ‘shared overlapping concepts.’”

> Of course, the choices don’t end there. I also decided how to approach the topic; what references to pull; how to order my paragraphs (both before and after I wrote them); what idioms, metaphors and introductory language to use; where to place hooks and callbacks; what to title the piece; and how to utilize grammar and punctuation to express my sassy indignation. These are vital skills for students to practice, not because they’re required in every profession, but because they emphasize executive function and cognitive reasoning. Writers are responsible for what they write, speakers for what they say, leaders for what they decide and voters for whom they elect. This in and of itself is reason enough to teach actual writing.

> Both thematically and practically, this partnership, forged in campaign contributions, public appearances and the elimination of internal dissent (see: Jeff Bezos and The Washington Post), represents a threat to the university system. The Trump White House, intent on canceling research grants, deporting students and revoking accreditation, has very clearly demonstrated its opposition to “the elites” of academia. Ignorant consumers, like ignorant voters, are easier to manipulate, and ignorance thrives when education falters.

> The falseness of LLM-generated content is a perfect fit for the reality-rejecting ethos of the Trump administration. Back in April, the White House was accused of outsourcing its world-altering tariff calculations to ChatGPT. In May, the Health and Human Services secretary, Robert F. Kennedy Jr., published a report that experts discovered was filled with what appeared to be AI-generated false citations.


----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library--but there are *still* procurement issues! I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
