# Aug 1

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

Thanks to ES, VAC, JC, BE, KK, MP for helping out with the digest this week.

And now the come for faculty senates .... (See George Mason)

## Testimony on the hill

* The Review: Georgetown president says 'we police' the faculty. What?

[https://www.chronicle.com/newsletter/the-review/2025-07-28](https://www.chronicle.com/newsletter/the-review/2025-07-28)

(Thanks BE!!)

> “As in earlier rounds of hearings, the leaders tried hard to depict their institutions as eager to quash any sign of the putative scourge of anti-Jewish hatred on campus….[ Interim President of Georgetown Robert M. Groves said] that, since the October 7 attacks, Georgetown has ‘learned that we need to adapt to changing circumstances, almost continuously.’”

> “A congressional hearing is presumably one such circumstance; Groves had to adapt in real time to North Carolina Republican Virginia Foxx’s campaign against a Georgetown faculty member’s [ Jonathan A.C. Brown’s] right to extramural political speech. [ Brown is cited for his tweet saying, “I hope Iran does some symbolic strike on a [US military] base.”]

> “As far as academic freedom goes, this isn’t remotely an edge case. Brown’s speech is obviously protected. He is commenting both as a scholar of the region (one who is careful, indeed, to note the limits of his own expertise) and as a citizen about a major geopolitical event.”

> “Jonathan A.C. Brown is being investigated by Georgetown and condemned by Congress precisely for “speech in the public domain.” Given the susceptibility of campus discourse on the Middle East to Congressional censure, it is hard not to hear, in Groves’s blithe assurance that he and his fellow administrators ‘police’ their professors, something more intrusive than the rhetoric of academic rights and responsibilities.”


## Letters

* AAUP Letter Supports CUNY Law Professor Ramzi Kassem

[https://www.aaup.org/news/aaup-letter-supports-cuny-law-professor-ramzi-kassem](https://www.aaup.org/news/aaup-letter-supports-cuny-law-professor-ramzi-kassem)

> These accusations are outrageous. Any discipline leveled against Professor Kassem for his representation of Mr. Khalil would violate AAUP standards on academic freedom and tenure and the terms of CUNY’s faculty labor contract. Even more critically, such discipline would contravene Professor Kassem’s constitutionally-protected speech and association. Federal courts have interpreted the First Amendment to protect the right of faculty to engage in an “independent and uninhibited exchange of ideas” as well as the right of the university to engage in “autonomous decisionmaking” free of legislative or, for that matter, judicial control.1 Courts have interpreted the First Amendment to prohibit efforts by the government to “usurp” the right of academic institutions to “determine [for themselves] who may teach” or “what may be taught.” Professor Kassem’s representation of Mr. Khalil as part of his clinical practice falls squarely within these protections.

> The National AAUP stands in staunch support of Professor Ramzi Kassem’s academic and constitutional freedoms, and we will continue to closely watch CUNY’s defense of its faculty.

[https://www.aaup.org/sites/default/files/2025-07/Letter-AAUP-CUNY-July-2025.pdf](https://www.aaup.org/sites/default/files/2025-07/Letter-AAUP-CUNY-July-2025.pdf)

(The NYS AAUP has also written a letter regarding personnel decisions at Brooklyn College.)

## How best to describe the times we are in

* on the Conservative Playbook (2023-2024)

[https://www.nytimes.com/2023/12/10/us/universities-antisemitism-conservatives-liberals.html?searchResultPosition=13](https://www.nytimes.com/2023/12/10/us/universities-antisemitism-conservatives-liberals.html?searchResultPosition=13)

[https://www.nytimes.com/2024/01/02/us/harvard-president-campus-antisemitism-conservatives.html?searchResultPosition=14](https://www.nytimes.com/2024/01/02/us/harvard-president-campus-antisemitism-conservatives.html?searchResultPosition=14)

[https://www.nytimes.com/interactive/2024/01/20/us/dei-woke-claremont-institute.html?searchResultPosition=16](https://www.nytimes.com/interactive/2024/01/20/us/dei-woke-claremont-institute.html?searchResultPosition=16)

(Thanks ES!)

* A Year of Challenges and Uncertainty, as Told Through Data

[https://www.chronicle.com/article/a-year-of-challenges-and-uncertainty-as-told-through-data](https://www.chronicle.com/article/a-year-of-challenges-and-uncertainty-as-told-through-data)

(Many charts)

> More Than Half of States Have Proposed Anti-DEI Legislation

> The Pace of Bills Introduced and Passed Increased in 2025

> Where Changes to DEI Efforts Took Place

> Federal Dollars Make Up 12% of Higher Ed’s Revenue

> Federal Funding Contributes Over $60 billion in R&D to Higher Ed

> Colleges Are Clustered in High-Cost Areas

> Rising Costs Have Led to Lower Take-Home Pay

> In Application Growth, HBCUs Outpace Other Colleges

> Colleges Have Not Returned to Requiring Tests

## Academic freedom

* Kentucky Professor Calling for Global War to End Israel Removed From Teaching

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/07/28/ky-prof-calling-war-against-israel-pulled-teaching](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/07/28/ky-prof-calling-war-against-israel-pulled-teaching)

> The professor’s website urges nations to attack Israel to stop a genocide. His university president suggested he was “calling for the destruction of a people based on national origin.”

> “These activities may create a hostile environment for Jewish members of the university community or otherwise constitute harassment as defined by the Supreme Court,” Thro wrote. “The university has concerns that your actions may violate Title VI of the Civil Rights Act of 1964, the equivalent state laws, and various university policies.”

> Title VI prohibits discrimination based on shared ancestry, including antisemitism.

> But the letter didn’t provide further details, such as what conference conduct or writings the university was concerned about, or how university officials became aware of this expression.

* NYTimes: Judge Bars Trump Administration From Punishing 2 Law Professors for I.C.C. Work

[https://www.nytimes.com/2025/07/30/us/politics/trump-icc-lawyers.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/30/us/politics/trump-icc-lawyers.html?smid=nytcore-ios-share&referringSource=articleShare)

* NYTimes: Army Secretary Orders West Point to Pull Appointment of Former Biden Official

[https://www.nytimes.com/2025/07/30/us/politics/army-secretary-west-point-trump-loomer.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/30/us/politics/army-secretary-west-point-trump-loomer.html?smid=nytcore-ios-share&referringSource=articleShare)

## Freedom of expression

* Ideology in the Classroom: How Faculty at US Universities Navigate Politics and Pedagogy Amid Federal Pressure Over Viewpoint Diversity and Antisemitism

[https://scholarworks.brandeis.edu/esploro/outputs/report/9924494190801921](https://scholarworks.brandeis.edu/esploro/outputs/report/9924494190801921)

(Thanks JC)

> Findings
> * Most faculty identify as politically liberal but have a wide range of views on controversial political issues.
> * Only a minority of faculty are politically active on issues related to climate change, racism in America, Donald Trump and American democracy, Russia-Ukraine, or the Israel-Palestine conflict.
> * Many faculty members are concerned about the consequences of holding liberal political
views.
> * Many contentious issues that dominate news headlines do not come up often in college classes.
> * When teaching about contentious topics, most faculty say they would present arguments from a variety of perspectives and encourage students to make up their own minds.
> * The vast majority of faculty do not endorse statements widely considered to be antisemitic.

### Anti-woke/anti-DEI is simply racism

* Western Kentucky U. Reviews Syllabi to Ensure ‘Alternative Viewpoints’ Due to Anti-DEI Law

[https://www.chronicle.com/article/tracking-higher-eds-dismantling-of-dei](https://www.chronicle.com/article/tracking-higher-eds-dismantling-of-dei)

>  Western Kentucky University established a committee to review around 50 course syllabi “to confirm that alternative viewpoints are presented alongside dominant perspectives"; adopted a viewpoint-neutrality policy; and barred faculty and staff from attending diversity, equity and inclusion specific conferences or trainings.

* Justice Department Declares DEI Unlawful

[https://www.insidehighered.com/news/government/2025/07/30/doj-declares-slew-dei-practices-unlawful-memo](https://www.insidehighered.com/news/government/2025/07/30/doj-declares-slew-dei-practices-unlawful-memo)

> More than three months after a federal court struck down an Education Department directive that barred any practices that consider race at colleges across the country, the Department of Justice declared Wednesday that diversity, equity and inclusion practices are unlawful and “discriminatory.”

> But the agency’s memo goes even further than ED’s guidance, suggesting that programs that rely on what they describe as stand-ins for race, like recruitment efforts that focus on majority-minority geographic areas, could violate federal civil rights laws. The directive applies to any organization that receives federal funds, and DOJ officials warned that engaging in potentially unlawful practices could lead to a loss in grant funding.

> Lynn Pasquerella, president of the American Association of Colleges and Universities, said that the memo is “another example of governmental overreach into academic freedom, institutional autonomy and shared governance that conditions federal funding on ideological alignment with the administration’s viewpoints.”

## Funding cuts

* As Trump Upends Funding for Research, These Scholars Turn to GoFundMe

[https://www.chronicle.com/article/as-trump-upends-funding-for-research-these-scholars-turn-to-gofundme](https://www.chronicle.com/article/as-trump-upends-funding-for-research-these-scholars-turn-to-gofundme)

(Thanks BE!)

> “As the once-stable compact between universities and the federal government founders, some scholars are looking elsewhere for money.”

> For example: The mother of Danielle DiFranco, a Ph.D. candidate in Joyce A. Schroeder breast-cancer research lab at the University of Arizona suggested starting a GoFundMe campaign because “family members would likely be willing to chip in to support her research, particularly since several relatives have had breast cancer.”

> “’It was odd to me, because I don’t really think of our research lab as a place that would need charity,’ DiFranco said, noting that campaigns on GoFundMe often benefit individuals or families facing medical crises, natural disasters, or other emergencies.”

> “It’s a long-running joke among academics waiting for news on their grant proposals: ‘If it’s not funded,’ they say, ‘we’ll just have a bake sale.’”

> “… crowdfunding in academe isn’t an entirely new notion. The University of Illinois at Urbana-Champaign in 2016 created an online FAQ page on best practices for crowdfunding research.”

> “Experiment, a science-specific fund-raising site, has been around since 2012 and has raised more than $12 million in support of 1,351 different projects. It’s an all-or-nothing funding platform, meaning that donors are only charged if the project reaches its fund-raising goal, and it also sends proceeds directly to the institutions its researchers are affiliated with.”

* By cutting science, the Defense Department is eating its seed corn

(Thanks MP!)

[https://www.defensenews.com/opinion/2025/07/24/by-cutting-science-the-defense-department-is-eating-its-seed-corn/](https://www.defensenews.com/opinion/2025/07/24/by-cutting-science-the-defense-department-is-eating-its-seed-corn/)

> We are in a long-term strategic competition with China that has diplomatic, economic, and military components. To be effective, diplomacy must be backed up by economic and military strength. In our era of rapidly advancing technology, both economic and military strength are directly dependent on investments in early-stage, enabling technologies.

> This competition is a marathon, not a sprint, and to prevail we have to invest with that in mind. While the Trump administration’s cuts to science in general have been noted, less attention has been paid to the Defense Department’s proposed science and technology funding levels.

> We cannot afford to be complacent about our technological superiority. We are well past the point where China can be thought of as a future or emerging challenge.

> In the face of this challenge, the Trump administration has proposed a Fiscal Year 2026 budget that reduces funding for enabling technologies – the mix of basic, applied, and advanced technology budget accounts – by over 10% from Fiscal Year 2025 levels, which themselves are roughly flat relative to 2024.

* Senate Appropriators Reject Trump’s Deep Education Cuts

[https://www.insidehighered.com/news/government/student-aid-policy/2025/08/01/senate-appropriators-reject-trumps-education-dept](https://www.insidehighered.com/news/government/student-aid-policy/2025/08/01/senate-appropriators-reject-trumps-education-dept)

> Senate Republicans are planning to protect the Pell Grant program, keeping the maximum grant award at $7,395 for the coming academic year, despite the Trump administration’s proposal to lower it to $5,710.

> It also set new staffing standards for the recently gutted Department of Education, increased funding for medical research by $400 million and rejected the National Institutes of Health’s attempt to cap indirect research cost reimbursements at 15 percent.

> Over all, the Department of Education is going to receive $79 billion and the NIH will get $48.7 billion. In comparison, Trump had requested $66.7 billion for ED and $27.5 billion for NIH.

> “These are not the bills I would have written on my own, but nonetheless they represent serious bipartisan work to make some truly critical investments in our country and families’ future,” said Sen. Patty Murray, a Washington Democrat and ranking member of the committee. Still, she added, this is only half the battle. “The fact of the matter is we have an administration right now that is intent on ignoring Congress, breaking the law and doing everything it can without transparency to dismantle programs and agencies.”

### NIH

* Lawsuit Over NIH Grant Funding Heads to Supreme Court

[https://www.insidehighered.com/news/quick-takes/2025/07/25/lawsuit-over-nih-grant-funding-heads-supreme-court](https://www.insidehighered.com/news/quick-takes/2025/07/25/lawsuit-over-nih-grant-funding-heads-supreme-court)

> The Trump administration has taken its fight over grants awarded by the National Institutes of Health to the Supreme Court, requesting permission Thursday to finalize millions of dollars in award cuts, CBS News reported.

* The Trump administration has put a halt on billions in new research grants flowing from the National Institutes of Health, setting up a battle with lawmakers

[https://www.wsj.com/politics/policy/trump-administration-puts-new-chokehold-on-billions-in-health-research-funding-19660215?st=V7YMhi&reflink=article_gmail_share](https://www.wsj.com/politics/policy/trump-administration-puts-new-chokehold-on-billions-in-health-research-funding-19660215?st=V7YMhi&reflink=article_gmail_share)

* Trump administration halts, then releases, NIH research funding

[https://www.washingtonpost.com/politics/2025/07/29/trump-administration-nih-funding/](https://www.washingtonpost.com/politics/2025/07/29/trump-administration-nih-funding/)

> The halt stemmed from a footnote in an Office of Management and Budget document, according to an email sent to NIH staff Tuesday afternoon by the NIH’s associate director for budget, Neil Shapiro. The OMB gave the NIH its “full-year apportionment” of congressionally mandated funds, Shapiro wrote, but included a footnote limiting what the NIH could spend the money on.

> Finance officials within the agency “interpreted this footnote to permit NIH obligations only for salaries, administrative expenses, and Clinical Center expenses,” Shapiro wrote. But research money including “research grant, R & D contract, or training awards cannot be issued during this pause,” Shapiro wrote.

> If the money had not later been unfrozen, the move would have affected about $15 billion in federal funds, according to the office of Sen. Patty Murray (Washington), the top Democrat on the Senate Appropriations Committee.

* NIH director says cuts aim to reduce ‘ideological research,’ focus on health

[https://www.washingtonpost.com/health/2025/07/29/nih-trump-bhattacharya-budget/](https://www.washingtonpost.com/health/2025/07/29/nih-trump-bhattacharya-budget/)

> In June, NIH staffers issued the Bethesda Declaration, now signed by 484 employees, some named, others anonymous. The declaration said that on Bhattacharya’s watch, the Trump administration has forced the NIH “to politicize research by halting high-quality, peer reviewed grants and contracts.” The declaration also accused the administration of “censoring critical research” on subjects including health disparities, health effects of climate change and gender identity.

> “Making America healthy again,” he said in a recent one-hour interview with The Washington Post, “involves deprioritizing research that doesn’t have a chance of making America healthy, [such as] a lot of ideological research that I think served to create a perception that the NIH is a political organization rather than the scientific organization it actually is.”

(...)

* Abrupt Pause, Unpause of Grants Doesn’t End NIH Funding Concerns

[https://www.insidehighered.com/news/government/science-research-policy/2025/07/31/abrupt-pause-unpause-grants-doesnt-end-nih](https://www.insidehighered.com/news/government/science-research-policy/2025/07/31/abrupt-pause-unpause-grants-doesnt-end-nih)

> But before the night was over, the Trump administration appeared to reverse course. In an updated article citing unnamed sources, the Journal reported that unnamed “senior White House officials intervened.” (OMB is part of the executive branch.) The Journal said officials at the Health and Human Services Department, which includes NIH, fought the pause for days, but OMB only relented after the newspaper published its initial story Tuesday.


### NEH

* Federal Judge Blocks Cancellation of NEH Grants

[https://www.insidehighered.com/news/quick-takes/2025/07/28/federal-judge-blocks-cancellation-neh-grants](https://www.insidehighered.com/news/quick-takes/2025/07/28/federal-judge-blocks-cancellation-neh-grants)

> Afederal judge in New York has blocked the Trump administration's cancellation of $175 million in National Endowment for the Humanities grants allegedly related to diversity, equity and inclusion; gender ideology; or “environmental justice.”

> In a ruling issued Friday, Judge Colleen McMahon of the U.S. District Court in the Southern District of New York, said the agency violated the First Amendment in ordering the cancellation of grants “based on the recipients’ perceived viewpoint, in an effort to drive such views out of the marketplace of ideas.”

> Last week Judge McMahon determined that the plaintiffs “demonstrated a likelihood of success on the merits of their claim” and ordered the government to release funding for the impacted grants while litigation continues.

## Institutional assaults

* The Professors Who Supported the Student Deportation Frenzy

[https://www.dropsitenews.com/p/documenting-jew-hatred-campus-professors-student-deportations-betar-canary-mission?r=q0z6x&utm_campaign=post&utm_medium=web](https://www.dropsitenews.com/p/documenting-jew-hatred-campus-professors-student-deportations-betar-canary-mission?r=q0z6x&utm_campaign=post&utm_medium=web)

(Thanks JC)

> Throughout November and into December, the DJHC account continued celebrating the prospect of student deportations. And on December 5, a couple months before such deportations began in earnest, Jeffrey Lax—chair of the business department at Kingsborough College at the City University of New York (CUNY)—joined the advisory board of DJHC. S.A.F.E. Campus, an organization that Lax had founded in 2023, was already serving as DJHC’s fiscal sponsor, which allowed the newer group to receive tax-exempt donations.

> On the DHJC board of advisors, Lax is joined by prominent pro-Israel agitator and former Columbia business professor Shai Davidai, who has long been trying to penalize pro-Palestine voices at the university, and who has also participated in a Columbia alumni WhatsApp group where members aimed to identify student protesters and call for their expulsion, firing, or deportation. And Lax and Davidai are only the most prominent of a handful of campus affiliates backing such groups. Drop Site News’ reporting reveals that current and former instructors at least four schools across the northeastern U.S. have publicly supported Betar, DJHC, and Canary Mission. A few of their names appeared on the GoFundMe page for Betar’s fundraising push last fall and winter.

### Harvard

* NYTimes: Harvard’s Powerful Leader Faces Intense Scrutiny in Trump Fight

[https://www.nytimes.com/2025/07/26/us/harvard-penny-pritzker.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/26/us/harvard-penny-pritzker.html?smid=nytcore-ios-share&referringSource=articleShare)

> As Harvard and the government negotiate to end a conflict with billions of dollars on the line, some ask whether Penny Pritzker, the head of the school’s governing board, should step down.

(And just who are "some")

> In the high-stakes negotiations between the Trump administration and Harvard University, the White House and a growing number of people at Harvard have at least one shared goal. They want Penny Pritzker, the head of the university’s top governing board, out.

(Others include Mr. Ackman, Linda McMahon, so not so many...)

* The quiet academic leading Harvard’s fight against Trump

[https://www.washingtonpost.com/education/2025/07/25/alan-garber-harvard-president-trump-administration/](https://www.washingtonpost.com/education/2025/07/25/alan-garber-harvard-president-trump-administration/)

> Garber, now president of Harvard, will need all his reserves of equanimity — and his commitment to a range of viewpoints on campus — as he leads the nation’s oldest private university through a historic confrontation with the president of the United States.

> Now Harvard is facing an even greater crisis. President Donald Trump has lashed out at colleges and universities for alleged antisemitism and is seeking to force profound changes in higher education. The government has targeted Harvard, freezing billions in federal research funding, launching a flurry of investigations and attempting to block international students and scholars from the university. Harvard is challenging the administration’s actions in court as unlawful intrusions on its autonomy.

> Harvard’s decision to fight the government stands in stark contrast to the path taken by Columbia University, which announced Wednesday that it had reached a deal with the Trump administration.

> As Garber weighs the choices ahead, his horizon goes far beyond Trump and this administration, colleagues say. “He is thinking about Harvard in 2125,” said Alison Frank Johnson, a professor of history at Harvard who has known Garber for more than a decade. “He’s thinking about protecting the university over the very long term.”

* Trump puts pressure on Harvard and others to pay up, after Columbia deal

[https://www.washingtonpost.com/education/2025/07/25/harvard-columbia-university-trump-deal/](https://www.washingtonpost.com/education/2025/07/25/harvard-columbia-university-trump-deal/)

(Thanks VAC)

> The administration is seeking payments from the University of Michigan as well as Northwestern, Cornell and Brown universities, in an effort to make deals similar to the $200 million agreement announced Wednesday with Columbia University.

> The financial dragnet could impact dozens of other colleges and universities that are also facing — or were threatened with — investigations by the Trump administration, the White House said.

(Also)

[https://www.wsj.com/us-news/education/harvard-columbia-trump-white-house-fines-payment-deal-settlement-d61aa9c6](https://www.wsj.com/us-news/education/harvard-columbia-trump-white-house-fines-payment-deal-settlement-d61aa9c6)

* NYTimes: Harvard Is Said to Be Open to Spending Up to $500 Million to Resolve Trump Dispute

[https://www.nytimes.com/2025/07/28/us/politics/trump-harvard-payment.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/28/us/politics/trump-harvard-payment.html?smid=nytcore-ios-share&referringSource=articleShare)

(I didn't believe the 200M for Columbia, and will double down on that belief here...)

> Harvard University has signaled a willingness to meet the Trump administration’s demand to spend as much as $500 million to end its dispute with the White House as talks between the two sides intensify, four people familiar with the negotiations said.

> According to one of the people, Harvard is reluctant to directly pay the federal government, but negotiators are still discussing the exact financial terms.

> President Trump has privately demanded that Harvard pay far more than Columbia. The people who described the talks and the dynamics surrounding them spoke on the condition of anonymity to discuss confidential negotiations.

(Yes, who is on background here...)

> Although the two sides have made progress toward a deal, Harvard is also skeptical of Columbia’s agreement to allow an outside monitor to oversee its sweeping arrangement with the government. Harvard officials have signaled that such a requirement for their own settlement could be a redline as a potential infringement on the university’s academic freedom.

> Penn agreed to apologies and policy changes but no financial penalties. But the administration has been eyeing Harvard’s wealth for months, and Trump aides believe that the university is able to pay much more than Columbia did.

(And why is ability to pay the key factor ...)

* NYTimes: Harvard Will Share Employee Forms With Federal Government

[https://www.nytimes.com/2025/07/29/us/politics/harvard-employee-forms-trump-administration.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/29/us/politics/harvard-employee-forms-trump-administration.html?smid=nytcore-ios-share&referringSource=articleShare)

> The government can request the employment eligibility verification forms related to citizenship and immigration status as a matter of course, but Harvard was surprised to receive such a voluminous demand.

> The government’s request was broad — it asked for the I-9 forms for all Harvard employees, as well as anyone else employed by the university over the previous year — but not altogether unusual. Federal officials have long had, and used, the authority to scrutinize the records, and the Trump administration has routinely harnessed that power in recent months.

> Harvard’s human resources office said Tuesday that it was not “at this time” giving the government access to forms completed by people who were in jobs “only open to students” as it weighed whether an educational privacy law protected those documents. Otherwise, the university said, it “intends to comply with federal law and accordingly will provide the requested records.”

> Harvard, though, suggested it was surprised by the scale of the request, noting that “the government does not ordinarily ask an employer to disclose all of its employees’ Form I-9s and their supporting materials.”

* HHS Accuses Harvard of Thwarting Investigations

[https://www.insidehighered.com/news/quick-takes/2025/08/01/hhs-accuses-harvard-thwarting-investigations](https://www.insidehighered.com/news/quick-takes/2025/08/01/hhs-accuses-harvard-thwarting-investigations)

> The U.S. Department of Health and Human Services said in a letter to Harvard president Alan Garber that it was referring the civil rights investigation to the U.S. Department of Justice, which it is permitted to do in cases where “compliance under Title VI cannot be obtained voluntarily.”

> The letter, written by Paula Stannard, director of the HHS Office for Civil Rights, also referenced legal actions taken by Harvard, which has fought back against frozen federal research funding and other matters.

* Under Pressure From Trump, the Accreditor Overseeing Harvard Proposes Nixing DEI Standards

[https://www.chronicle.com/article/under-pressure-from-trump-the-accreditor-overseeing-harvard-proposes-nixing-dei-standards](https://www.chronicle.com/article/under-pressure-from-trump-the-accreditor-overseeing-harvard-proposes-nixing-dei-standards)

### Columbia

* Columbia agreed to a monitor, stoking fears about independence

[https://www.washingtonpost.com/education/2025/07/26/columbia-university-settlement-monitor/](https://www.washingtonpost.com/education/2025/07/26/columbia-university-settlement-monitor/)

> To critics, the deal represents an unprecedented governmental intrusion into the affairs of a private university that could erode the independence of universities across the country. The White House has said it sees this agreement as a template for other schools that it is investigating for allegations of antisemitism and racial discrimination.

> Much of the oversight will relate to diversity, equity and inclusion, as the Trump administration seeks to stamp out any effort by Columbia to increase racial diversity in its student body, faculty or staff. The monitor will also be charged with assuring that university programs do not promote “unlawful DEI goals” — a term that is not defined.

> Under the agreement, Columbia is required to provide the monitor with detailed information about the race of students who are admitted and rejected, including grade point averages and standardized test scores broken down by race. All data related to faculty and administrative staff hiring and promotion practices must be provided to the monitor annually, and hiring data will be subject to a “comprehensive audit.”



### George Mason

* Fresh Air: The Shifting Landscape Of Higher Education

[https://www.npr.org/2025/07/24/1256157824/higher-education-george-mason](https://www.npr.org/2025/07/24/1256157824/higher-education-george-mason)

> So why are they now investigating George Mason University? ProPublica education reporter Katherine Mangan tells us why GMU's president thinks it's driven by a backlash to DEI efforts.

* On the Media:

[https://www.wnycstudios.org/podcasts/otm](https://www.wnycstudios.org/podcasts/otm)

>  [19:23] Host Micah Loewinger speaks with Katherine Mangan, a senior writer at The Chronicle of Higher Education, about the recent investigations launched into George Mason University by the Trump administration, and the media campaign that followed suit.

* George Mason U. Faculty Rally Around Their Besieged President. They May Be His Only Support.

[https://www.chronicle.com/article/george-mason-u-faculty-rally-around-their-besieged-president-they-may-be-his-only-support](https://www.chronicle.com/article/george-mason-u-faculty-rally-around-their-besieged-president-they-may-be-his-only-support)

> George Mason University’s Faculty Senate has ramped up its support of the university’s president, Gregory Washington, as the institution faces four federal investigations that some observers believe are designed to force his ouster. Washington is contending with a hostile Board of Visitors and no protection from the state’s attorney general.

> The Faculty Senate is demanding that the board provide the “strongest defense possible” of Washington, George Mason’s first Black president, and the university’s diversity initiatives, as the Justice and Education Departments probe whether GMU has engaged in race-based hiring and discriminatory admissions practices and failed to address antisemitism.

> “President Washington has shown every indication of consistently and faithfully exercising compliance with evolving directives from federal and Commonwealth authorities,” the resolution states. “Evidence, truth, and due process should be the foundation for all decisions, not allegations that have not been fully investigated.”

* Faculty Support of George Mason’s President Draws Federal Investigation

[https://www.nytimes.com/2025/07/28/us/justice-department-george-mason-faculty-senate-investigation.html](https://www.nytimes.com/2025/07/28/us/justice-department-george-mason-faculty-senate-investigation.html)

(Thanks JC and KK)

> Professors quickly published a resolution supporting their president and the university’s efforts around diversity.

> Now, Justice Department officials say they will investigate the faculty, too.

> In a letter sent on Friday, the Trump administration said it would seek drafts of the faculty resolution, all written communications among the Faculty Senate members who drafted the resolution, and all communications between those faculty members and the office of the university’s president, Gregory Washington.

> Free speech advocates quickly denounced the move as an attack on academic freedom.

> Faculty senate resolutions are positions taken by a university’s elected faculty body, like the one at George Mason. They typically carry no force and normally attract little notice beyond the campus newspaper. But these are not normal times for higher education.

> Solon Simmons, a sociologist who is president of the Faculty Senate, called the government’s inquiry “flabbergasting.”

> “None of us has any idea why the Department of Justice is so interested in a matter of local academic shared governance,” Dr. Simmons wrote in an email.

> “An outcome the Board committed to was to ‘faculty and staff demographics that mirror student demographics,’” Dr. Simmons said. “It is not our language, it is theirs.”

> ”While FIRE would prefer governing bodies such as faculty senates remain neutral on issues of political contention,” she said, “the federal government’s actions represent the latest in a pattern of shakedowns against colleges and universities that will certainly chill faculty speech.”

* DOJ to review staff texts, emails after faculty praise of GMU president

[https://www.washingtonpost.com/educat](https://www.washingtonpost.com/educat)

* Three takeaways from what DOJ told UVA


[https://www.insidehighered.com/news/government/2025/07/29/what-doj-letters-uva-say-about-trump-attack-higher-ed](https://www.insidehighered.com/news/government/2025/07/29/what-doj-letters-uva-say-about-trump-attack-higher-ed)

(Thanks VAC)


> In a series of seven letters obtained by Inside Higher Ed via an open records request, Dhillon and other Department of Justice officials laid out their increasingly aggressive case that the university was at risk of losing federal funding, just as Ivy League institutions like Harvard and Columbia Universities had in the months prior for allegations of antisemitism. The Cavalier Daily first published the letters in full.

> Taken together, the letters sent between April 11 and June 17 were used to launch what the DOJ called an investigation but that legal experts say is among the latest instances in an all-out pressure campaign against higher education.

> But now, with similar investigations launched against George Mason University (also located in Virginia), many onlookers view these letters as a template for how President Trump will continue to leverage federal funding to impose his priorities on colleges and universities across the country—altering who is admitted and what is taught and by whom. Higher education experts say it’s an aggressive tactic that will create a climate of uncertainty for years to come.

* Judge Removes Youngkin’s University Board Picks

[https://www.insidehighered.com/news/government/state-policy/2025/07/30/judge-removes-youngkins-university-board-picks](https://www.insidehighered.com/news/government/state-policy/2025/07/30/judge-removes-youngkins-university-board-picks)

> Republican governor Glenn Youngkin was overruled Tuesday as a Virginia circuit court ordered eight of his nominees be removed from their posts on three public universities’ boards, the Associated Press reported and court records confirm.

> But Youngkin and his attorney general, Jason Miyares, instructed board chairs to proceed in welcoming the nominees as members, citing a provision in the state Constitution that says all gubernatorial appointees must be approved by the General Assembly.

* Gregory Washington’s Gamble---The president of George Mason — and faculty leaders — may be punished for defending university policies.

[https://www.chronicle.com/article/gregory-washingtons-gamble](https://www.chronicle.com/article/gregory-washingtons-gamble)

* NYTimes: George Mason President Holds Job After Attacks on His Diversity Views

[https://www.nytimes.com/2025/08/01/us/george-masons-president-gregory-washington-republicans-diversity.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/01/us/george-masons-president-gregory-washington-republicans-diversity.html?smid=nytcore-ios-share&referringSource=articleShare)

> At a closed-door meeting that lasted more than three hours on Friday, a  board packed with conservative appointees of the state’s Republican governor, Glenn Youngkin, had convened to discuss the president’s fate. They emerged without making any moves to remove the president for the moment.

> Though the board did not take action on Dr. Washington’s job, during the open-door session, its members passed a resolution that supported a “merit-based approach” to student success and faculty and staff hiring, ordered cooperation with the federal government’s investigations, and prohibited requiring diversity statements in hiring.

(Also)

[https://www.washingtonpost.com/education/2025/08/01/george-mason-president-raise-dei-resolution/](https://www.washingtonpost.com/education/2025/08/01/george-mason-president-raise-dei-resolution/)

> GMU board approves DEI resolution, 1.5 percent raise for embattled president.

(Also)

[https://www.chronicle.com/article/in-a-plot-twist-george-masons-politically-embattled-president-gets-a-raise](https://www.chronicle.com/article/in-a-plot-twist-george-masons-politically-embattled-president-gets-a-raise)


### Duke

Trump Administration Freezes $108 Million in Funds to Duke University - The New York Times

[https://www.nytimes.com/2025/07/29/us/politics/trump-duke-university-frozen-funding-discrimination.html](https://www.nytimes.com/2025/07/29/us/politics/trump-duke-university-frozen-funding-discrimination.html)

> Duke University is the latest high-profile school, from Columbia University to Harvard, that the Trump administration has targeted and stripped of a large amount of federal funding, based on vague accusations that the university abets antisemitism or supports diversity, equity and inclusion programs. The move comes amid a wider pressure campaign from the Trump administration to shift the ideological tilt of American higher education.

> The university is weighing layoffs amid a budget crunch. It’s considering about $350 million in cuts, amounting to roughly 10 percent of its budget. In a video message last month, Duke’s president, Vincent E. Price, said the university was trying to sort out proposals from the federal government “that have quite dire implications for the university.”

### Brown

* Brown University Makes a Deal With the White House to Restore Funding - The New York Times

[https://www.nytimes.com/2025/07/30/us/brown-university-makes-a-deal-with-the-white-house-to-restore-funding.html](https://www.nytimes.com/2025/07/30/us/brown-university-makes-a-deal-with-the-white-house-to-restore-funding.html)

> The university, which is in Providence, R.I., secured a pledge from the government that the deal would not be used “to dictate Brown’s curriculum or the content of academic speech.” The Trump administration is also required to restore millions of dollars in federal research funding that it had blocked in recent months, and Brown avoided the naming of an independent monitor to oversee the deal.

> Dr. Paxson appeared to sense the prospect of a backlash, even as she promoted the agreement, devoting more than 350 words of her letter to explain why Brown had elected to negotiate.

> Before her school came under such direct pressure from the White House, Dr. Paxson was more vocal than many higher education leaders about the Trump administration’s tactics against prominent universities. In March, she said that the administration’s “demands raise new and previously unthinkable questions about the future of academic freedom and self-governance for those that are committed to continuing to serve this country as leading research institutions.”



(Also)

[https://www.insidehighered.com/news/government/politics-elections/2025/07/30/brown-strikes-deal-trump-administration](https://www.insidehighered.com/news/government/politics-elections/2025/07/30/brown-strikes-deal-trump-administration)

[https://www.chronicle.com/article/brown-u-s-deal-with-trump-restores-research-funding-without-paying-a-government-fine](https://www.chronicle.com/article/brown-u-s-deal-with-trump-restores-research-funding-without-paying-a-government-fine)

[https://www.nytimes.com/2025/07/30/us/brown-trump-deal-university-funding.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/30/us/brown-trump-deal-university-funding.html?smid=nytcore-ios-share&referringSource=articleShare)

[https://www.wsj.com/us-news/education/brown-trump-deal-federal-funds-research-50-million-25b1e8bd?st=5T1JB4&reflink=article_gmail_share](https://www.wsj.com/us-news/education/brown-trump-deal-federal-funds-research-50-million-25b1e8bd?st=5T1JB4&reflink=article_gmail_share)


### Others

* NYTimes: University of California Settles With Jewish Students Over U.C.L.A. Protests

[https://www.nytimes.com/2025/07/29/us/ucla-jewish-students-settlement.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/29/us/ucla-jewish-students-settlement.html?smid=nytcore-ios-share&referringSource=articleShare)

> In the lawsuit, three Jewish students and a Jewish professor said that the university had countenanced antisemitic behavior at a tent encampment set up in 2024 by protesters demonstrating against the war in Gaza.

> The plaintiffs said the university had not intervened when protesters prevented students who were wearing Jewish symbols like a star of David or the Israeli flag or a skullcap from crossing campus. The university even provided the barricades used to keep people out and stationed security guards on campus who sent Jewish students away instead of helping them get through, the court papers said.

> The settlement, announced Tuesday, will require the university to give $6.45 million, including legal fees, to the plaintiffs and to charitable entities. The money will also support the university’s own efforts to combat antisemitism and support the Jewish community on campus.

> Just hours after the settlement was announced, the Department of Justice said it had found U.C.L.A. in violation of civil rights law and the equal protection clause of the 14th Amendment for failing to adequately respond to complaints of “severe, pervasive and objectively offensive harassment and abuse” of Jewish and Israeli students during the protest encampment in the spring of 2024.

> The department sent a 10-page letter to Dr. Michael V. Drake, president of the University of California, laying out the evidence it had reviewed, including the lawsuit. It said that the department was now looking to enter into a voluntary resolution agreement with U.C.L.A. or go to court.

## Blowback

* NYTimes: Saving for College Once Felt Essential. Some Parents Are Rethinking Their Plans.

[https://www.nytimes.com/2025/07/26/business/529-parents-saving-college.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/26/business/529-parents-saving-college.html?smid=nytcore-ios-share&referringSource=articleShare)

> For generations, 529 college savings plans were a no-brainer for most parents wanting to start a college fund. They are tax-advantaged and primarily used to pay for higher education expenses. The accounts can be used for a range of education-related expenses, not just college tuition, like books, private K-12 tuition and more. If funds go unused, the account can be transferred to another beneficiary, like a sibling or a grandchild.

> But now, some parents are pumping the brakes on the accounts and rethinking how they plan to save for their children’s future. With growing uncertainty around the value of higher education, and a fear of locking funds into something their child may not use, many of these parents are looking for flexible plans that don’t tie their money exclusively to higher education.

* Nearly 600 Duke Employees Take Buyouts

[https://www.insidehighered.com/news/quick-takes/2025/07/28/nearly-600-duke-employees-take-buyouts](https://www.insidehighered.com/news/quick-takes/2025/07/28/nearly-600-duke-employees-take-buyouts)

> Nearly 600 employees have accepted buyouts at Duke University, opting into a voluntary separation incentive program prompted by threats to federal research funding, WRAL reported.

> Duke officials said they also plan to start involuntary layoffs in August, even though 599 staff members took buyouts. Another 250 faculty members are also reportedly considering opting in.


## AI misdeeds

* The LOADing Act

[https://www.nysenate.gov/legislation/bills/2023/S7543/amendment/A](https://www.nysenate.gov/legislation/bills/2023/S7543/amendment/A)

(Thanks RS! This promises to put some guardrails in place on the use of automated decision making and safeguards for employment.)

* Guidelines for the Use of AI in AGB (Association of Governing Boards) Work

[https://agb.org/wp-content/uploads/2024/06/Guidelines-for-the-Use-of-AI-in-AGB-Work-June-2024.pdf](https://agb.org/wp-content/uploads/2024/06/Guidelines-for-the-Use-of-AI-in-AGB-Work-June-2024.pdf)

(Many, including)

> UNDERSTAND THESE RISKS

> 1. AI Limitations: Recognize that AI tools can make mistakes, provide inaccurate information, and even make things up. All uses of AI require human oversight, decision-making, and final approval following internal SOPs.

> 2. Ethics and Fairness: Be aware that AI is trained on human data and can incorporate human biases.

> 3. AI and Intellectual Property: When you feed content into certain AI generators, that content may become publicly available. Once you enter content, it is no longer under our control. For example, some paid and free versions of OpenAI’s ChatGPT are trained on user inputs. AGB IP entered into these tools may become part of the public knowledge base.


* Faculty Latest Targets of Big Tech’s AI-ification of Higher Ed

[https://www.insidehighered.com/news/faculty-issues/learning-assessment/2025/08/01/faculty-are-latest-targets-higher-eds-ai](https://www.insidehighered.com/news/faculty-issues/learning-assessment/2025/08/01/faculty-are-latest-targets-higher-eds-ai)

> The AI-ification of Canvas is just one of the latest examples of the technology’s infiltration of higher education amid predictions that the technology will reshape and shrink the job market for new college graduates.



## The media

* Under Siege From Trump and Musk, a Top Liberal Group Falls Into Crisis - The New York Times

[https://www.nytimes.com/2025/07/25/us/politics/media-matters-musk-crisis.html](https://www.nytimes.com/2025/07/25/us/politics/media-matters-musk-crisis.html)


* FCC to Appoint a Babysitter to Make Sure CBS Isn't Anti-Trump

[https://gizmodo.com/fcc-to-appoint-a-babysitter-to-make-sure-cbs-isnt-anti-trump-2000634566](https://gizmodo.com/fcc-to-appoint-a-babysitter-to-make-sure-cbs-isnt-anti-trump-2000634566)



* departures-from-wapo

[https://www.politico.com/f/?id=00000198-3fd2-dab1-a3bf-ffd7dc3d0000&nname=playbook&nid=0000014f-1646-d88f-a1cf-5f46b7bd0000&nrid=0000015b-3fd2-d88f-adfb-7fd7bdf20000](https://www.politico.com/f/?id=00000198-3fd2-dab1-a3bf-ffd7dc3d0000&nname=playbook&nid=0000014f-1646-d88f-a1cf-5f46b7bd0000&nrid=0000015b-3fd2-d88f-adfb-7fd7bdf20000)

## And just because it is fun

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
