# Aug 8

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

Thanks for VAC, JC for flagging important items this week.

A couple of important executive orders related to higher education are introduced this week. While not law, these give cover for an administration to use all the levers it controls to gain compliance. These are related to reporting of admissions data and oversight of federal grantmaking, which is sure to change the already tipped over playing board for grants.

## Testimony on the hill

* CUNY chancellor discusses recent testimony on antisemitism

[https://spectrumlocalnews.com/nys/watertown/in-focus-shows/2025/08/02/cuny-chancellor-discusses-recent-testimony-on-antisemitism](https://spectrumlocalnews.com/nys/watertown/in-focus-shows/2025/08/02/cuny-chancellor-discusses-recent-testimony-on-antisemitism)

(Sorry, didn't watch this but is teased by "CUNY Chancellor Felix Matos Rodriguez talked about his experience testifying before Congress and shared details on how CUNY is changing its hate response system to make students feel safer and recognized more efficiently.")

## Brooklyn College

* Brooklyn College Faces Backlash Over Fired Faculty

[https://www.bkreader.com/policy-government/brooklyn-college-faces-backlash-over-fired-faculty-11022225](https://www.bkreader.com/policy-government/brooklyn-college-faces-backlash-over-fired-faculty-11022225)

> More than 150 City University of New York faculty and staff rallied at Brooklyn College Thursday to demand the reinstatement of four faculty members in what the union says was due to their public advocacy for Palestinian rights.

> “CUNY administrators have investigated faculty for the terms in which they discuss the war in Gaza in their classes, limited the time, place and manner for exercising the right to free expression on campus, invited police violence against non-violent student protestors, and even fired faculty in apparent retribution for their political activism," James Davis, president of the Professional Staff Congress said in a statement. "Universities must stand against fascism, not accommodate it. Our fired colleagues have been denied due process and must be reinstated immediately."

> "Brooklyn College does not make personnel decisions based on political belief but based on conduct. As this is an ongoing personnel matter, we are unable to comment further," a spokesperson for Brooklyn College said in a statement.

## Alliances

* The Only Hope Is Total and Unrelenting Resistance

[https://www.chronicle.com/article/an-open-letter-from-arne-duncan](https://www.chronicle.com/article/an-open-letter-from-arne-duncan)

> Every university must join together to stop Trump, urges Arne Duncan.

## Statements

* Protesting CUNY for Letting 4 Adjunct Faculty Go over Palestinian Rights and Suspending a Student

[https://www.juancole.com/2025/08/protesting-letting-suspending.html](https://www.juancole.com/2025/08/protesting-letting-suspending.html)

> We write on behalf of the Middle East Studies Association of North America (MESA) and its Committee on Academic Freedom to express our grave concern at recent decisions and statements made by your office and by the leaderships and human resources teams at Brooklyn College, City Tech, John Jay College of Criminal Law and City University of New York (CUNY) School of Law. T


## Zoom calls

* Who’s Afraid of the Big Bad Bill: Higher Ed Fights Back

[https://us06web.zoom.us/webinar/register/WN_SwJINs5xRWOzxQarIH1OvA#/registration](https://us06web.zoom.us/webinar/register/WN_SwJINs5xRWOzxQarIH1OvA#/registration)

> Join us for our upcoming webinar “Who’s Afraid of the Big Bad Bill: Higher Ed Fights Back” on Monday, August 18th at 7:30 pm et, 6:30 ct, 5:30 mt and 4:30 pt. We’ll be joined by Sara Garcia, a policy analyst for Senator Bernie Sanders on the Health, Education, Labor and Pensions Committee (HELP). Sara will walk us through the parts of the bill that will affect higher education and discuss what’s possible in terms of pushing back. A representative from the Debt Collective will discuss how the myriad changes to student lending will affect student borrowers and we will end with discussion and call to act in the fall with our colleagues across the country and fight back against the attacks on higher education in the United States. Feel free to invite friends, colleagues, students, or other like-minded organizations. This event is closed to the press. More information will be forthcoming.

(Thanks JC)

## Op eds

* NYTimes: Is There a Smart Way to Cede Power to Donald Trump?

[https://www.nytimes.com/2025/08/05/opinion/trump-havard-brown-universities.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/05/opinion/trump-havard-brown-universities.html?smid=nytcore-ios-share&referringSource=articleShare)

(Not as dumb as the headline makes you believe)

## Funding cuts

* NYTimes: Judge Declines to Order Trump Administration to Restore Research Cuts

[https://www.nytimes.com/2025/08/01/nyregion/nsf-trump-stem-research-cuts.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/01/nyregion/nsf-trump-stem-research-cuts.html?smid=nytcore-ios-share&referringSource=articleShare)

> A federal judge in New York declined in a ruling on Friday to order the Trump administration to restore hundreds of millions of dollars in terminated funding that had been awarded to research institutions by the National Science Foundation.

> The ruling came in a lawsuit filed in May in which a coalition of 16 states argued that the grants were critical to maintaining the United States as a leader in science, technology, engineering and math, or STEM, subjects, and that the cuts were “in complete derogation of the policies and priorities set by Congress.”

> “This evidence powerfully undermines plaintiffs’ argument that the priority directive renders this class of projects categorically ineligible for funding,” wrote Judge Cronan, who was nominated to the federal bench by President Trump in 2019 and confirmed the following year.

* Improving Oversight of Federal Grantmaking – The White House

[https://www.whitehouse.gov/presidential-actions/2025/08/improving-oversight-of-federal-grantmaking/](https://www.whitehouse.gov/presidential-actions/2025/08/improving-oversight-of-federal-grantmaking/)

(OMB---R. Vought---means to evaluate grant awards for political alignment, not merit)

>  pre-issuance review of discretionary awards to ensure that the awards are consistent with applicable law, agency priorities, and the national interest,

> Agency heads shall designate one or more senior appointees to review discretionary awards on an annual basis for consistency with agency priorities and substantial progress.

> Until such time as the process specified in subsection (a) of this section is in place, agencies shall not issue any new funding opportunity announcements without prior approval from the senior appointee designated

> Discretionary awards must, where applicable, demonstrably advance the President’s policy priorities.

>  Discretionary awards shall not be used to fund, promote, encourage, subsidize, or facilitate:  racial preferences ... denial by the grant recipient of the sex binary in humans or the notion that sex is a chosen or mutable characteristic; ... illegal immigration ... any other initiatives that compromise public safety or promote anti-American values.

>  All else being equal, preference for discretionary awards should be given to institutions with lower indirect cost rates.

>  Discretionary grants should be given to a broad range of recipients rather than to a select group of repeat players.  Research grants should be awarded to a mix of recipients likely to produce immediately demonstrable results and recipients with the potential for potentially longer-term, breakthrough results, in a manner consistent with the funding opportunity announcement.

>  To the extent institutional affiliation is considered in making discretionary awards, agencies should prioritize an institution’s commitment to rigorous, reproducible scholarship over its historical reputation or perceived prestige.

>  As to science grants, agencies should prioritize institutions that have demonstrated success in implementing Gold Standard Science.

(This is a May 23 executive order)

[https://www.whitehouse.gov/presidential-actions/2025/05/restoring-gold-standard-science/](https://www.whitehouse.gov/presidential-actions/2025/05/restoring-gold-standard-science/)

* Trump Puts Political Appointees in Charge of Federal Grant Decisions

[https://www.insidehighered.com/news/quick-takes/2025/08/08/trump-political-appointees-charge-grant-decisions](https://www.insidehighered.com/news/quick-takes/2025/08/08/trump-political-appointees-charge-grant-decisions)

### NSF

### NIH

* Trump Administration Illegally Withheld N.I.H. Funding, Watchdog Finds

[https://www.nytimes.com/2025/08/05/us/politics/trump-gao-nih-funding.html](https://www.nytimes.com/2025/08/05/us/politics/trump-gao-nih-funding.html)

> It was the fifth time that the Government Accountability Office, a nonpartisan legislative agency, faulted President Trump and his top aides for rearranging the budget in defiance of Congress. From February to June, investigators estimated, the N.I.H. awarded $8 billion less for research and other grants than it had a year earlier.

> The findings underscored the real stakes in the growing clash between the Trump administration and Congress over the power of the purse. Since returning to office, Mr. Trump has adopted an expansive view of his authority to recalibrate the federal ledger as he sees fit, even though the Constitution gives lawmakers the power to tax and spend.

* How Many Times Can Science Funding Be Canceled?

[https://www.theatlantic.com/health/archive/2025/08/nih-funding-whiplash/683773/](https://www.theatlantic.com/health/archive/2025/08/nih-funding-whiplash/683773/)


> Last week, the National Institutes of Health finally got some good news. A Senate subcommittee voted, with support from both parties, to increase the agency’s $48 billion budget—a direct rebuke to the Trump administration’s proposed budget

> But inside the agency, officials could not wholeheartedly celebrate. Its political leadership has shredded the NIH playbook so thoroughly, current and former NIH officials told me, that even at current funding levels they are unable to perform their core work of vetting and powering some of the best scientific research around the world.

### NEH

* NYTimes: Humanities Endowment Funds Trump’s Priorities After Ending Old Grants

[https://www.nytimes.com/2025/08/05/arts/national-endowment-for-the-humanities-trump-grants.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/05/arts/national-endowment-for-the-humanities-trump-grants.html?smid=nytcore-ios-share&referringSource=articleShare)

> The National Endowment for the Humanities abruptly canceled virtually all of its existing grants in April, citing a desire to pivot to “the president’s agenda.” Now it has announced its largest round of grants since, $34.8 million in funding for 97 projects across the country that helps show what that means.

> The grants include many focused on presidents, statesmen and canonical authors, including $10 million to the University of Virginia — which the agency said was the largest grant in its history — that will support the “expedited completion” of editorial work on papers relating to the Declaration of Independence, the American Revolution and the Founding era.

> None of the new grants are explicitly related to L.G.B.T.Q. issues. And while there are several projects about prominent female figures, including Emily Dickinson and Marianne Moore, only one appears to take a broader look at gender and women’s history: a $700,000 grant to City Lore, a media company in New York, to support a documentary about female reporters during the Vietnam War.

## Federal Agencies

### DOE/OCR

* NYTimes: Trump Amps Up an Obama Strategy to Crack Down on Colleges

[https://www.nytimes.com/2025/08/06/us/politics/trump-universities-title-ix-vi-obama.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/06/us/politics/trump-universities-title-ix-vi-obama.html?smid=nytcore-ios-share&referringSource=articleShare)

> To show they are serious about stamping out campus antisemitism, some of the nation’s top universities are adding a powerful position to their administrative ranks.

> The position has a modest sounding title: Title VI coordinator. The responsibilities, however, are significant: to oversee and ensure compliance with Title VI of the Civil Rights Act, which prohibits discrimination in federally funded programs “on the ground of race, color or national origin” and also covers Jews, Arab Muslims and other religious groups.

> But some legal experts warn that expanding Title VI oversight could lead universities into contentious thickets over defining antisemitic speech and adjudicating complaints of harassment. The end result, they say, could set new limits for permissible forms of expression, chilling speech on the quad and in the classroom.

> Historically, Title IX authorized the government to monitor whether educational institutions — not students — were engaged in discriminatory conduct.

> But in a pivotal shift, the Education Department’s Office of Civil Rights published new guidance for institutions in 2011. The office said that for institutions to remain in compliance with Title IX — and eligible for federal funds — they were required to thoroughly investigate and adjudicate sexual assault allegations with a disciplinary process and a standard of evidence that many critics said favored accusers. An institution’s investigative process, the guidance said, would be subject to federal review.


## State actions

* When the Legislature Kills Your Department

[https://www.chronicle.com/article/when-the-legislature-kills-your-department](https://www.chronicle.com/article/when-the-legislature-kills-your-department)

(Thanks VAC)

## Institutional assaults

### Accreditation

* Western Accreditor Launches New ROI Tool

[https://www.insidehighered.com/news/quick-takes/2025/08/06/western-accreditor-launches-new-roi-tool](https://www.insidehighered.com/news/quick-takes/2025/08/06/western-accreditor-launches-new-roi-tool)

> WSCUC officials said the PEP metric will help universities, students and lawmakers better understand how specific programs compare within institutions and to national benchmarks. The change comes as the federal government looks to require all programs to pass an earnings test in order to qualify for federal student loans.


### Admissions

* NYTimes: Columbia and Brown to Disclose Admissions and Race Data in Trump Deal

[https://www.nytimes.com/2025/08/05/nyregion/columbia-brown-admissions-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/05/nyregion/columbia-brown-admissions-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> As part of the settlements struck with two Ivy League universities in recent weeks, the Trump administration will gain access to the standardized test scores and grade point averages of all applicants, including information about their race, a measure that could profoundly alter competitive college admissions.

> The release of such data has been on the wish list of conservatives who are searching for evidence that universities are dodging a 2023 Supreme Court decision barring the consideration of race in college admissions, and will probably be sought in the future from many more of them.

> But college officials and experts who support using factors beyond test scores worry that the government — or private groups or individuals — will use the data to file new discrimination charges against universities and threaten their federal funding.

* NYTimes: Trump Administration Live Updates: President Orders Closer Scrutiny of College Admissions Data

[https://www.nytimes.com/live/2025/08/07/us/trump-news?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/live/2025/08/07/us/trump-news?smid=nytcore-ios-share&referringSource=articleShare)

> Admissions data: Mr. Trump signed a memorandum requiring colleges to submit admissions data to the federal government to verify that they have ended race-conscious policies. The directive comes as the administration takes aim at the ideological and racial balance of the higher education system and could profoundly alter competitive college admissions.

(Also)

[https://www.nytimes.com/2025/08/07/us/politics/trump-schools-race-data.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/07/us/politics/trump-schools-race-data.html?smid=nytcore-ios-share&referringSource=articleShare)

(Also)

[https://www.insidehighered.com/news/admissions/traditional-age/2025/08/07/trump-orders-colleges-supply-data-race-admissions](https://www.insidehighered.com/news/admissions/traditional-age/2025/08/07/trump-orders-colleges-supply-data-race-admissions)

> What resources are in place to enforce the new requirements remains to be seen. Earlier this year the administration razed the staff at the Department of Education who historically collected and analyzed institutional data. Only three staff members remain in the National Center for Education Statistics, which operates IPEDS.

> “I will say something that my members in the higher education community cannot say. What the Trump administration is really saying is that you will be punished if you do not admit enough white students to your institution,” Angel B. Pérez, CEO of the National Association for College Admission Counseling, told Inside Higher Ed.

(Also)

[https://www.chronicle.com/article/trump-begins-hunt-for-bogeyman-in-admissions-data](https://www.chronicle.com/article/trump-begins-hunt-for-bogeyman-in-admissions-data)


### Harvard

* Under Pressure From Trump, the Accreditor Overseeing Harvard Proposes Nixing DEI Standards

[https://www.chronicle.com/article/under-pressure-from-trump-the-accreditor-overseeing-harvard-proposes-nixing-dei-standards](https://www.chronicle.com/article/under-pressure-from-trump-the-accreditor-overseeing-harvard-proposes-nixing-dei-standards)

> The accreditor that oversees Harvard University said Friday that it’s considering removing language from its standards that refers to diversity, equity, and inclusion.

> The New England Commission of Higher Education — which accredits more than 200 colleges, primarily in the Northeast — is one of several major institutional accreditors that are reconsidering if and how members should demonstrate how they’re meeting diversity goals.

* Democrats Plan to Probe Harvard if It Complies With Trump

[https://www.insidehighered.com/news/quick-takes/2025/08/04/democrats-plan-probe-harvard-if-it-complies-trump](https://www.insidehighered.com/news/quick-takes/2025/08/04/democrats-plan-probe-harvard-if-it-complies-trump)

> The letter—led by Rep. Sam Liccardo and Sen. Adam Schiff, Democrats from California, and Sen. Chris Van Hollen, a Democrat from Maryland—was sent just days after The New York Times reported Harvard is willing to pay up to $500 million to end its months-long dispute with the Trump administration over the way it handled alleged incidents of campus antisemitism and other grievances.

> “We are alarmed that Harvard would contemplate a settlement of this magnitude under apparent political pressure,” the Democrats wrote in the letter first obtained by Axios. “Any such agreement may warrant rigorous Congressional oversight and inquiry.”

> The Democratic lawmakers added that this “rigorous” examination would be necessary, as the Trump administration has repeatedly made “unjustified political threats” and interfered with the governance of independent institutions.

> To acquiesce would make Harvard “complicit in the erosion of fundamental democratic principles,” the letter stated.

* Harvard President Garber Tells Faculty He Is Not Considering a $500 Million Deal With Trump | News | The Harvard Crimson

[https://www.thecrimson.com/article/2025/8/3/garber-500-million-trump/](https://www.thecrimson.com/article/2025/8/3/garber-500-million-trump/)

> Harvard President Alan M. Garber ’76 has told faculty that a deal with the Trump administration is not imminent and denied that the University is considering a $500 million settlement, according to three faculty members familiar with the matter.

> The University is seriously considering resolving its dispute with the White House through the courts rather than a negotiated settlement, Garber said, according to the three faculty members.

* NYTimes: Trump’s Deal-Making With Other Elite Schools Scrambles Harvard Negotiations

[https://www.nytimes.com/2025/08/04/us/politics/harvard-trump-brown.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/04/us/politics/harvard-trump-brown.html?smid=nytcore-ios-share&referringSource=articleShare)

> The university was open to spending $500 million, but a $50 million settlement with Brown has prompted new debates in Cambridge.

(Who is the source of this reporting is not detailed...)

> The terms stunned officials at Harvard, who marveled that another Ivy League school got away with paying so little, according to three people familiar with the deliberations. But Harvard officials also bristled over how their university, after months of work to address antisemitism on campus and with a seeming advantage in its court fight against the government, was facing a demand from Mr. Trump to pay 10 times more.

> The people who discussed the deliberations spoke on the condition of anonymity because they did not want to be identified discussing talks that are supposed to remain confidential.


### Columbia

* Research Funding Starts to Flow Back to Columbia, Brown

[https://www.insidehighered.com/news/government/politics-elections/2025/08/01/research-funding-starts-flow-back-columbia-brown https://www.insidehighered.com/news/government/politics-elections/2025/08/01/research-funding-starts-flow-back-columbia-brown](https://www.insidehighered.com/news/government/politics-elections/2025/08/01/research-funding-starts-flow-back-columbia-brown https://www.insidehighered.com/news/government/politics-elections/2025/08/01/research-funding-starts-flow-back-columbia-brown)

(Watch this space...my over/under is 2 months until we see something different)

### UCLA

NYTimes: Trump Administration Is Freezing Over $300 Million for U.C.L.A.

[https://www.nytimes.com/2025/08/01/us/politics/trump-cuts-ucla-funding-federal-research.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/01/us/politics/trump-cuts-ucla-funding-federal-research.html?smid=nytcore-ios-share&referringSource=articleShare)

> The federal government is freezing over $300 million in research funds for the University of California, Los Angeles, over claims of antisemitism and bias at the institution, according to its chancellor and Trump administration documents.

> The Trump administration paused the research funding as part of an investigation by the government’s antisemitism task force, two administration officials said. The freeze included about $240 million in research grants from the Health and Human Services Department and the N.I.H., $81 million from the N.S.F. and $18.2 million from the Energy Department, a White House spokeswoman said.

> On Tuesday, the university agreed to pay more than $6 million to settle a lawsuit from Jewish students and a professor who said that the university had allowed a hostile protest on campus. After the settlement was announced, the Department of Justice separately said that it had found the university violated civil rights laws by failing to respond to students’ complaints of antisemitism.

* With Grant Cuts, Trump Pressures UCLA to Make Deal

[https://www.insidehighered.com/news/faculty-issues/2025/08/04/grant-cuts-trump-pressures-ucla-make-deal https://www.insidehighered.com/news/faculty-issues/2025/08/04/grant-cuts-trump-pressures-ucla-make-deal](https://www.insidehighered.com/news/faculty-issues/2025/08/04/grant-cuts-trump-pressures-ucla-make-deal https://www.insidehighered.com/news/faculty-issues/2025/08/04/grant-cuts-trump-pressures-ucla-make-deal)

> The letter didn’t specifically say what the Trump administration wants UC to do now about its alleged failure to handle a pro-Palestine encampment that ended more than a year ago, and that UCLA itself dismantled a week after its creation. The DOJ didn’t provide Inside Higher Ed further information Monday, but U.S. attorney general Pam Bondi’s news release accompanying the DOJ letter suggests the Trump administration wants significant concessions.

> What does the UC system plan to do? A spokesperson deferred comment to UCLA, which also didn’t provide interviews Monday or answer written questions. The UC system spokesperson did forward a statement Friday from system president James B. Milliken, who started in his new job Aug. 1—just after the grant freezes.

> Milliken called “the suspension this week of a large number of research grants and contracts” at UCLA “deeply troubling,” though “not unexpected.”

> Also Friday, California governor Gavin Newsom, a potential 2028 presidential candidate and an ex officio member of the UC Board of Regents, released a statement calling it “a cruel manipulation to use Jewish students’ real concerns about antisemitism on campus as an excuse to cut millions of dollars in grants that were being used to make all Americans safer and healthier.”

> “This is the action of a president who doesn’t care about students, Californians, or Americans who don’t comply with his MAGA ways,” Newsom said.

* 23 Cents Per American: The Price of Destroying Mathematical Research

[https://www.dailykos.com/stories/2025/8/3/2336574/-58-Cents-Per-American-The-Price-of-Destroying-Mathematical-Research](https://www.dailykos.com/stories/2025/8/3/2336574/-58-Cents-Per-American-The-Price-of-Destroying-Mathematical-Research)

> The Trump administration just suspended Terence Tao's NSF grant—not because his research lacks merit, but as collateral damage in a political vendetta against UCLA. If you don't know who Tao is, imagine if they'd cut Einstein's funding in 1915.

> The NSF has slashed basic science funding by over 50% in 2025. Mathematical sciences funding dropped from a 10-year average of $113 million to just $32 million through May. With 350 million Americans, that's 32 cents per person down to 9 cents—a cut of 23 cents per American.

> The result? We're not just cutting mathematical research to save 24 cents per American—we're also using science funding as a political weapon, punishing entire universities and the researchers who work there.

(Thanks JC)

* He’s the ‘Mozart’ of Math and Trump Killed His Funding

[https://www.thebulwark.com/p/terence-tao-ucla-mathematician-mozart-of-math-trump-funding-nsf](https://www.thebulwark.com/p/terence-tao-ucla-mathematician-mozart-of-math-trump-funding-nsf)

* The University of California system agrees to negotiate with Trump after more than $500 million in federal research funds are frozen

[https://www.wsj.com/us-news/education/ucla-trump-university-california-negotiations-public-7ef576d9?st=rsdKeK&reflink=article_gmail_share](https://www.wsj.com/us-news/education/ucla-trump-university-california-negotiations-public-7ef576d9?st=rsdKeK&reflink=article_gmail_share)

> The University of California educates around 300,000 undergraduate and graduate students on its 10 campuses spread across the state.

> UC has said it receives more National Institutes of Health and National Science Foundation funding than any other institution in the country. The system receives almost 6,700 federal grants and contracts totaling $3.85 billion.

> The UC negotiations will be among Milliken’s first acts in his job running the 10-campus system, a position he officially took on Aug. 1 after years at the helm of the University of Texas and other public-school systems.

> These cuts do nothing to address antisemitism,” Milliken said Wednesday of the hundreds of suspended grants to UCLA. The loss of the funds, he said, “would be a death knell for innovative work that saves lives, grows our economy, and fortifies our national security.”

(Also)

[https://www.insidehighered.com/news/government/science-research-policy/2025/08/07/uc-will-dialogue-feds-over-civil-rights](https://www.insidehighered.com/news/government/science-research-policy/2025/08/07/uc-will-dialogue-feds-over-civil-rights)

### UVA

* NYTimes: University of Virginia Appoints Interim President After Ouster

[https://www.nytimes.com/2025/08/04/us/politics/university-virginia-appoints-interim-president.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/04/us/politics/university-virginia-appoints-interim-president.html?smid=nytcore-ios-share&referringSource=articleShare)

> Paul G. Mahoney, a former dean of the law school at the University of Virginia, was named the institution’s interim president on Monday, after his predecessor as president resigned under intense pressure from the Trump administration.

> A member of the Council on Foreign Relations, Mr. Mahoney joined the law school faculty in 1990 after practicing law with the New York firm of Sullivan & Cromwell. He clerked for both Supreme Court Justice Thurgood Marshall, a staunch liberal, and for Judge Ralph K. Winter, Jr., an appellate judge who was regarded as a leading conservative.

## Blowback

* NYTimes: Trump Went to War With the Ivies. Community Colleges Are Being Hit.

[https://www.nytimes.com/2025/08/04/magazine/trump-community-college-anti-dei.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/08/04/magazine/trump-community-college-anti-dei.html?smid=nytcore-ios-share&referringSource=articleShare)

> Since January, the Trump administration has waged war on the nation’s wealthiest and most prestigious universities, freezing billions of dollars in research grants to Harvard and blasting away at Columbia’s institutional autonomy. But collateral damage from these attacks has engulfed schools of all types, including the country’s 1,100 community colleges, which educate about 6.4 million undergraduates each year — roughly 40 percent of the national total and more than twice as many as are enrolled at every highly selective college and university in the country combined.

> Like their four-year counterparts, community colleges are grappling with disappearing federal grants, shuttered D.E.I. offices, eliminated programs, canceled cultural convocations and panicked students and staff. At Delta, many of the grants that fund financial aid for low-income students and the staff that support them have been eliminated or threatened. I went to see the hydraulic-circuit class in part because of how much government funding, a great deal of it federal, it takes to make the teaching possible. It was hardly the only class I could have chosen: Federal funding helps pay not just for heavy machinery used in courses like the one taught by Luna but also, elsewhere on the Delta campus, for the full dental lab for aspiring hygienists; the X-ray machines surrounded by lead-lined walls for radiography students; and the robotic medical mannequins, one that pushed out little baby mannequins and could simulate everything from a breech birth to a health emergency.

> I also came to Delta to meet its president, Mike Gavin, who in this moment of fear and uncertainty has emerged as a kind of spokesman for America’s community colleges as a whole. Gavin heads an improvised coalition of community-college presidents and administrators called Education for All, which, amid the responses to the federal government’s assaults, has been the rare example of collective action among higher-ed leadership.

> Unlike elite universities, community colleges often can’t afford to keep an in-house counsel on payroll, let alone the teams of lawyers who have been advising Ivy League schools on their present predicament. So Education for All members, in addition to offering solidarity and support, provided advice on how their schools could navigate all the hurdles being thrown in front of them.

(Much more in this long piece)

* International Student Enrollment Could Drop 15% by Fall

[https://www.insidehighered.com/news/global/international-students-us/2025/08/05/international-student-enrollment-could-drop-15](https://www.insidehighered.com/news/global/international-students-us/2025/08/05/international-student-enrollment-could-drop-15)

> New international enrollments in the U.S. could drop by as many as 150,000 students in the next year, according to scenario modeling by NAFSA, the association of international educators, and JB International.

> “This analysis … should serve as a clarion call to the State Department that it must act to ensure international students and scholars are able to arrive on U.S. campuses this fall,” said Fanta Aw, executive director and CEO of NAFSA, in a press release. “For the United States to succeed in the global economy, we must keep our doors open to students from around the world.”

* Stanford Plans to Cut 363 Jobs

[https://www.insidehighered.com/news/quick-takes/2025/08/05/stanford-plans-cut-363-jobs](https://www.insidehighered.com/news/quick-takes/2025/08/05/stanford-plans-cut-363-jobs)

> Stanford president Jon Levin and provost Jenny Martinez noted in a letter to campus that the cuts were part of an effort announced last month to reduce $140 million in the general funds budget. They called the layoffs, reported Tuesday, “the product of a challenging fiscal environment shaped in large part by federal policy changes affecting higher education.”

> University officials provided more information in a letter filed with the California Employment Development Department that accompanied the layoff notice. They cited “anticipated changes in federal policy—such as reductions in federal research funding and an increase in the excise tax on investment income” as significant factors driving the reduction of Stanford’s workforce.

* How Trump Forced Cuts at Wealthy Universities

[https://www.insidehighered.com/news/business/cost-cutting/2025/08/07/how-trump-forced-cuts-wealthy-universities](https://www.insidehighered.com/news/business/cost-cutting/2025/08/07/how-trump-forced-cuts-wealthy-universities)

> While sector layoffs are so frequent that Inside Higher Ed has dedicated monthly coverage to rounding up such reductions, those actions are more common at small, cash-strapped colleges or state institutions reeling from budget cuts. But universities with multibillion-dollar endowments have been among those making the deepest cuts in the first half of 2025, often driven by freezes on federal funding that the Trump administration imposed with minimal notice.

> Altogether the layoffs show a sector bracing for a new reality where research funding can be suddenly yanked away with little to no explanation and international and graduate student enrollment, once considered a cash cow, is under threat—prompting institutions in even the highest financial stratosphere to cut costs as they navigate changing policies and a president sharply critical of the sector.

> Thousands Out at Johns Hopkins; Hundreds of Buyouts at Duke; Deep Cuts at Northwestern; The Ax Falls at Stanford; Nearly 180 Layoffs at Columbia; ‘A Day of Loss’ at Boston U; Dozens Laid Off at USC; Unspecified Cuts at Harvard; Likely Layoffs at Brown

* U of Utah Plans to Ax 81 Offerings, Citing New State Law

[https://www.insidehighered.com/news/quick-takes/2025/08/07/u-utah-plans-ax-81-offerings-citing-new-state-law](https://www.insidehighered.com/news/quick-takes/2025/08/07/u-utah-plans-ax-81-offerings-citing-new-state-law)


## Coming attractions?

* Columbia, CUNY Law Professors Beat Trump in Court

[https://www.bloomberglaw.com/public/desktop/document/RonaetalvTrumpetalDocketNo125cv03114SDNYApr152025CourtDocket/1?doc_id=X4HR83K7C2C8G88JPVI1MU7CJNV](https://www.bloomberglaw.com/public/desktop/document/RonaetalvTrumpetalDocketNo125cv03114SDNYApr152025CourtDocket/1?doc_id=X4HR83K7C2C8G88JPVI1MU7CJNV)

> In law, as in life, two wrongs do not make a right.

> Upon his return to office in 2025, President Trump issued Executive Order 14,203 (the “2025 Order”), which is substantially similar to the Order that Judge Failla enjoined over four years ago; in fact, it includes the exact language that she found likely unconstitutional.

> On the merits, the Court concludes that the 2025 Order violates Plaintiffs’ First Amendment rights because it constitutes a content-based regulation of their speech-based activities and cannot survive strict scrutiny.  Accordingly, and for the reasons elaborated below, Plaintiffs’ motion is GRANTED, and they are entitled to a permanent injunction.

## AI misdeeds

* AI is listening to your meetings. Be careful what you say.

[https://www.wsj.com/tech/ai/ai-notetaker-meeting-transcripts-be9bc4cc?st=utffPx&reflink=article_gmail_share](https://www.wsj.com/tech/ai/ai-notetaker-meeting-transcripts-be9bc4cc?st=utffPx&reflink=article_gmail_share)

> AI is listening in on your work meetings—including the parts you don’t want anyone to hear. Before attendees file in, or when one colleague asks another to hang back to discuss a separate matter, AI notetakers may pick up on the small talk and private discussions meant for a select audience, then blast direct quotes to everyone in the meeting.

* Google to Spend $1B on AI Training in Higher Ed

[https://www.insidehighered.com/news/quick-takes/2025/08/07/google-spend-1b-ai-training-higher-ed](https://www.insidehighered.com/news/quick-takes/2025/08/07/google-spend-1b-ai-training-higher-ed)

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library---but I can't get them right now! I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
