# Dec 5

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.


## Academic freedom

* A Conservative Student Got a Zero on Her Paper about Gender. Did She Deserve It?

[https://www.chronicle.com/article/a-conservative-student-got-a-zero-on-her-paper-about-gender-did-she-deserve-it](https://www.chronicle.com/article/a-conservative-student-got-a-zero-on-her-paper-about-gender-did-she-deserve-it)

> Did a student paper arguing for traditional gender roles and identities deserve its failing grade? Or was that mark proof of political bias, and of academe’s hostility to religious conservatives?

> That debate is unspooling at the University of Oklahoma. There, Samantha Fulnecky was recently asked in a psychology course on lifespan development to respond to an academic article. In her short reaction paper, Fulnecky wrote that while the article “discussed peers using teasing as a way to enforce gender norms,” she did “not necessarily see this as a problem,” according to screenshots of her paper that were posted on X by the university’s Turning Point USA chapter. That’s because “God made male and female and made us differently from each other on purpose and for a purpose.”

> Why such a low mark? Her submission does not “answer the questions for this assignment, contradicts itself, heavily uses personal ideology over empirical evidence in a scientific class, and is at times offensive,” an instructor for the course told Fulnecky, according to screenshots of the feedback also shared by the Turning Point chapter. (The instructor, Mel Curth, a graduate student, declined an interview but confirmed a few details over email.)

> At Oklahoma, Fulnecky has filed a complaint alleging discrimination against her for her religious beliefs. “OU has a clear process for reviewing such claims and it has been activated,” the university said in a statement.

> The university also said that the graduate-student instructor, who is unnamed in the statement, is now on administrative leave, and a professor has taken over the course for the rest of the semester.

(Also)

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/12/02/oklahoma-ta-leave-student-claims-religious](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/12/02/oklahoma-ta-leave-student-claims-religious)

[https://www.nytimes.com/2025/12/02/us/oklahoma-bible-essay-gender-teasing-zero.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/12/02/us/oklahoma-bible-essay-gender-teasing-zero.html?smid=nytcore-ios-share)

* Texas Tech Puts Its Anti-Trans Rules In Writing

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/12/02/texas-tech-puts-its-anti-trans-rules-writing](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/12/02/texas-tech-puts-its-anti-trans-rules-writing)

> “Effective immediately, faculty must not include or advocate in any form course content that conflicts with the following standards,” Chancellor Brandon Creighton wrote in the memo to system presidents, which was passed along to faculty members. The standards include specific rules around race and sexuality that were not previously discussed, system faculty members told Inside Higher Ed. The memo also enshrines that the Texas Tech system recognizes only two sexes—male and female.

> Course content related to race and sexuality is now also subject to heightened scrutiny. Although the memo doesn’t ban outright discussion of transgender topics or any topics that suggest there are more than two genders, policies across the country stating that there are only two sexes or genders have been used to restrict transgender rights.

> The memo also outlines a Board of Regents–controlled review process, complete with a flowchart, for courses that include content related to gender identity and sexuality. Although race is mentioned earlier in the memo, it’s unclear whether race-related course content will also be subject to this review.

> Brian Evans, president of the Texas chapter of the American Association of University Professors, criticized the memo Tuesday. “Empowering administrators to censor faculty experts’ teaching decisions does a disservice to the university, its students and the state,” Evans said. “Such a system is inconsistent with long-standing principles of academic freedom, university policy and the First Amendment.”

> Graham Piro, faculty legal defense fund fellow for campus advocacy at the Foundation for Individual Rights and Expression, decried the memo in a statement Tuesday". "...  The memo is also so broadly worded that an overzealous administration could easily punish a professor who seeks to provoke arguments in class or advocates outside the classroom for changes to curricula that reflect developments in teaching... Decades ago, the Supreme Court recognized that the First Amendment ‘does not tolerate laws that cast a pall of orthodoxy over the classroom.’ It instead wrote that ‘truth’ is discovered not by ‘authoritative selection,’ but ‘out of a multitude of tongues.’ These principles are timeless, and Texas Tech should not compromise them, no matter the political winds of the day.”

(Also)

[https://www.chronicle.com/article/at-texas-tech-professors-now-need-permission-to-teach-about-race-and-gender](https://www.chronicle.com/article/at-texas-tech-professors-now-need-permission-to-teach-about-race-and-gender)

* Lawsuit Accuses Hispanic Scholarship Fund of Discrimination

[https://www.insidehighered.com/news/students/financial-aid/2025/12/05/lawsuit-hispanic-scholarship-fund-illegally-discriminates](https://www.insidehighered.com/news/students/financial-aid/2025/12/05/lawsuit-hispanic-scholarship-fund-illegally-discriminates)

> A new lawsuit argues the Hispanic Scholarship Fund—a nonprofit that says it has provided more than $756 million in scholarships over its 50-year history—is illegally restricting its funding to Hispanics and Latinos. The litigation seeks to bar HSF “from knowing or considering ethnicity in any way” in its Scholars Program.

> It’s another example of how the campaign against affirmative action and programs that specifically benefit minorities didn’t end with the 2023 Students for Fair Admissions Supreme Court ruling, which rendered affirmative action in college admissions illegal. The American Alliance was founded by the same man, Edward Blum, who created Students for Fair Admissions, the nonprofit that’s the namesake of the 2023 ruling.

> It’s also another example of a suit that uses an Asian plaintiff and a Reconstruction-era law to attempt to open up a minority-specific scholarship to all races and ethnicities. Earlier this year, the Pacific Legal Foundation cited the Ku Klux Klan Act of 1871, which Congress passed to protect African Americans, to attack a financial aid program that helped only Black students at the University of California, San Diego.



## Freedom of expression

* NYTimes: Judge Dismisses Harvard Antisemitism Lawsuit by a Former Student

[https://www.nytimes.com/2025/12/04/us/harvard-antisemitism-lawsuit.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/12/04/us/harvard-antisemitism-lawsuit.html?smid=nytcore-ios-share)

> A federal judge on Thursday dismissed a discrimination lawsuit filed against Harvard by a former student, who had accused the university of acting with indifference to his complaints about campus protesters who he said had harassed him because he is Jewish.

> Mr. Segev, who is Jewish and a citizen of the United States, Israel and Canada, according to his lawsuit, walked through the protest holding a camera phone. Video of the protest showed that he was quickly surrounded by other students, who yelled “shame!” and tried to block his camera lens with scarves. They formed a scrum, jostled him and forced him to leave.

> In his complaint, Mr. Segev said that he was “physically assaulted by an antisemitic mob,” and that he was yelled at “for being Jewish and Israeli.” Mr. Segev had accused Harvard officials of refusing “to take any reasonable action” to punish the students involved or offer Mr. Segev any redress.

> The lawsuit also accused the university of conducting a “sham investigation” of what happened. It was the key remaining civil case against Harvard related to its handling of pro-Palestinian protests on campus.

> In his ruling, Judge Stearns wrote that “while the court does not condone an assault on a fellow student by campus protesters,” nothing in Mr. Segev’s complaint “plausibly supports the notion that his assailants’ conduct was motivated by race-based antisemitism.”

### Anti-woke/anti-DEI is simply racism

* NYTimes: U. of Alabama Suspends Black and Female Student Magazines, Citing D.E.I. Guidance

[https://www.nytimes.com/2025/12/02/us/u-of-alabama-student-magazines-dei.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/12/02/us/u-of-alabama-student-magazines-dei.html?smid=nytcore-ios-share)


> The University of Alabama on Monday suspended two student magazines — one appealing to women, another to Black students — saying they ran afoul of guidance from the Justice Department on diversity, equity and inclusion programs.

> University officials told staff members at the publications — a women’s lifestyle magazine called Alice and Nineteen Fifty-Six, which encompasses Black culture and student life — that because of shifting federal policy on D.E.I. programs, the university could no longer support them. One official attributed the decision in part to a July memo from Attorney General Pam Bondi, in which she included recommendations on how institutions receiving federal funding could avoid what the Trump administration deemed unlawful D.E.I. practices.

> Kendal Wright, the editor in chief of Nineteen Fifty-Six, said in a statement that she was “devastated but, regrettably, not surprised” by the university’s decision, “based on the current climate of our country.”

> To Gabrielle Gunter, the editor in chief of Alice, it appeared that the university had determined that merely the magazines’ target audiences were enough to warrant their suspensions under the attorney general’s memo. In the meeting, Dr. Hood said that because Alice appeared to be a magazine predominantly “for women, by women,” it didn’t abide by the federal guidance.

> “I thought that because of the First Amendment, the freedom of press, that Alice wouldn’t be affected by any identity-based legislation, or rulings, or memos,” Ms. Gunter said in an interview on Tuesday. “Supposedly, it’s not applicable here.”

(Supposedly...)

(Also)

[https://www.insidehighered.com/news/students/free-speech/2025/12/03/alabama-ends-black-women-focused-student-magazines](https://www.insidehighered.com/news/students/free-speech/2025/12/03/alabama-ends-black-women-focused-student-magazines)

[https://www.chronicle.com/article/a-university-shuts-down-2-campus-magazines-because-they-might-look-like-dei](https://www.chronicle.com/article/a-university-shuts-down-2-campus-magazines-because-they-might-look-like-dei)


## Funding cuts

* NYTimes: The U.S. Is Funding Fewer Grants in Every Area of Science and Medicine

[https://www.nytimes.com/interactive/2025/12/02/upshot/trump-science-funding-cuts.html?smid=nytcore-ios-share](https://www.nytimes.com/interactive/2025/12/02/upshot/trump-science-funding-cuts.html?smid=nytcore-ios-share)

(Great graphics to illustrate)

> There was a catch, however: That money went to fewer grants.

> Which means less research was funded in areas such as aging, diabetes, strokes, cancer and mental health.

> In the past, the N.I.H. typically awarded grants in five annual installments. Researchers could request two more years to spend this money, at no cost.

> Under the new system, the N.I.H. pays up front for four years of work. And researchers can get one more year to spend this money. Which means that they get less money on average, and less time to spend it.

(After reviewing, they conclude this:)

> 1. Fewer grants in every area of science and medicine

> 2. More competition

> 3. A drop in grants mentioning diversity

> 4. Fewer fellowships for future scientists

> The N.S.F. has run a prestigious graduate research fellowship program since 1952. It funds three years of research for around 2,000 of the country’s top science graduate students.  This year, it awarded 536 fewer such fellowships. The government originally planned to eliminate 1,000 fellowships, but later added about 500 more after facing protest from scientists and academics.


## Federal Agencies

### DOE/OCR

* Fate of Accountability for Undergraduate Certificates Likely to Loom Over ED Talks

[https://www.insidehighered.com/news/government/student-aid-policy/2025/12/05/how-talks-over-new-earnings-test-could-ensnare](https://www.insidehighered.com/news/government/student-aid-policy/2025/12/05/how-talks-over-new-earnings-test-could-ensnare)

> Starting next July, colleges and universities’ access to federal student loans will hinge on how much their graduates make after Congress’s new earnings test, known as the Do No Harm standard, takes effect.

> This monumental shift in how the federal government holds degree programs accountable is one that’s years in the making. But when Congress passed the law, one key type of degree program was left out—undergraduate certificates.

> Lawmakers from both parties have long said holding colleges accountable for cost is critical in order to drive down borrower-default rates and protect students from paying high tuition without a guaranteed return on investment. Yet, the very students and programs Republicans left out of the earnings test are expected to face the worst return on investment, studies show.

> In the meantime, education experts are left to wonder what the fate of accountability for certificate programs will be—and tensions remain. For-profit institutions remain critical of gainful employment, calling it an uneven playing field.


## Institutional assaults

* CounterCurrent: The Art of Case Resolution Agreements

[https://mailchi.mp/nas.org/countercurrent-the-art-of-case-resolution-agreements?e=c4cb25fef5](https://mailchi.mp/nas.org/countercurrent-the-art-of-case-resolution-agreements?e=c4cb25fef5)

(Thanks KAB)

> Case resolution agreements are the current tool of choice for the Trump administration when dealing with colleges and universities. The agreements are particularly effective, combining broad institutional reform with financial incentives. Case in point: Northwestern University, which settled with the Trump administration on Friday, agreeing to pay $75 million to restore nearly $1 billion in frozen federal research funds.

> Case resolution strategy, while effective, has potential pitfalls. An excerpt from Waste Land explains their use by the ED upon IHEs, “case resolutions technically are not obligatory rules, so they sidestep both the requirements of the Administrative Procedure Act (1946) and the principle that major policy changes should be made by statutes drafted by elected representatives who are democratically responsible to the people.” While “voluntary” in nature, case resolution agreements in higher education are usually in response to avoiding rigorous legal investigation by the DOJ, ED, and Office of Civil Rights—like Northwestern. It is easier to come to a resolution than face legal battles and loss of funding—which is why “voluntary” is in quotation marks. Thus, case resolution agreements can be effective, but also open concerns about government overreach, particularly when pressuring institutions to sign case resolution agreements.


### Accreditation

* FTC Claims the ABA Is a Monopoly

[https://www.insidehighered.com/news/quick-takes/2025/12/04/ftc-claims-aba-monopoly](https://www.insidehighered.com/news/quick-takes/2025/12/04/ftc-claims-aba-monopoly)

> The Federal Trade Commission accused the American Bar Association of having a “monopoly on the accreditation of American law schools” in a letter to the Texas Supreme Court at a time when the state is considering minimizing the ABA’s oversight of legal education.

> In April, the Texas Supreme Court announced it was looking into eliminating ABA requirements for licensure. Justices wrote in a tentative opinion in the fall that the ABA “should no longer have the final say on whether a law school’s graduates are eligible to sit for the Texas bar exam and become licensed to practice law.”

> n addition to claiming the ABA was a monopoly, they argued it had “rigid and costly requirements” and that it mandates “every law school follow an expensive, elitist model of legal education.”

> Monday’s letter reflects rhetoric from President Donald Trump and his allies who have taken aim at accreditors in recent years. Trump blasted the ABA in an April executive order, accusing it of discrimination for its diversity, equity and inclusion standards. (The ABA suspended DEI standards for accreditation in February, before the executive order.)

### Harvard

* NYTimes: Why Trump and Harvard Have Not Reached a Deal

[https://www.nytimes.com/2025/12/03/us/politics/trump-harvard.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/12/03/us/politics/trump-harvard.html?smid=nytcore-ios-share)

(Also)

[https://www.washingtonpost.com/education/interactive/2025/timeline-trump-harvard/](https://www.washingtonpost.com/education/interactive/2025/timeline-trump-harvard/)

> But Trump administration hard-liners swooped in, arguing inside the White House that the terms were too favorable to Harvard. They pressed the case that at least some of the money should be classified as a fine, payable directly to the federal government. Three key figures have embraced the idea, all of them billionaires: Mr. Trump; the education secretary, Linda McMahon; and Stephen A. Schwarzman, the Blackstone chief executive and Harvard Business School alum, who has emerged as one of the university’s lead negotiators.

> Some view a cash payment as tantamount to a bribe and not commensurate with the accusations about what government officials say the school did wrong. Others think a “fine” would be seen essentially as an admission of guilt, a stigma that similarly stings.

> Moreover, Harvard leaders have been frustrated by the Trump administration’s inconsistent approach to the talks, with evolving demands from the government and a rotating mix of figures driving discussions.

> Similar whiplash has shadowed the administration’s talks with other universities. Earlier this year, for example, Trump administration officials believed they were on the brink of a cash-free deal with Columbia University — until Mr. Trump himself decreed that the university would need to pay a $200 million fine if it wanted a cease-fire with Washington.

> They [Harvard admin] were pleased with the outcome [of a case in September] but skeptical that it would permanently solve Harvard’s plight. Federal research funding is awarded in cycles, and some university leaders fear that Harvard will, in effect, be blacklisted by the administration.

> But university officials also see themselves as guardians of academic freedom and are sensitive to accusations that a deal would make the university — and them — look like sellouts. Those officials are facing tremendous pressure, on the campus and beyond, to hold the line against Mr. Trump, with many in higher education reasoning that if a university as mighty as Harvard caves, there is little hope for others that might want to resist federal pressure.

> But a deal may not guarantee lasting peace. The administration has displayed a willingness to seek more concessions from universities and law firms that have reached settlements with the White House.


### Northwestern

* Northwestern to pay $75 million to end Trump administration probes

[https://www.washingtonpost.com/nation/2025/11/29/northwestern-agreement-trump-funding-freeze-ends/](https://www.washingtonpost.com/nation/2025/11/29/northwestern-agreement-trump-funding-freeze-ends/)

> Officials had vowed greater transparency into university financial holdings and increased support for Middle Eastern, North African and Muslim students, including finding their respective cultural associations a temporary space on campus. That space will no longer be available, the school said in announcing the new deal with the Trump administration. The Deering Meadow Agreement’s landing page on Northwestern’s website had already been removed by Saturday.

> Northwestern will also conduct a campuswide survey within six months that will ask students if they feel safe reporting alleged antisemitism, among other questions.

(Also)

[https://insidehighered.com/news/government/politics-elections/2025/11/29/northwestern-settles-trump-administration](https://insidehighered.com/news/government/politics-elections/2025/11/29/northwestern-settles-trump-administration)

[https://www.chronicle.com/blogs/the-trump-agenda/northwestern-u-will-pay-75-million-to-resolve-trump-investigations](https://www.chronicle.com/blogs/the-trump-agenda/northwestern-u-will-pay-75-million-to-resolve-trump-investigations)


## The long game

> NBC News Survey: One-Third of Americans Say College Is Worth the Cost

[https://www.insidehighered.com/news/quick-takes/2025/12/01/survey-one-third-americans-say-college-worth-cost](https://www.insidehighered.com/news/quick-takes/2025/12/01/survey-one-third-americans-say-college-worth-cost)

## Blowback

* Trump’s attack on DEI may hurt college men, particularly White men

[https://www.washingtonpost.com/education/2025/12/04/trump-dei-ban-college-men/](https://www.washingtonpost.com/education/2025/12/04/trump-dei-ban-college-men/)

> Brown University, one of the most selective institutions in America, attracted nearly 50,000 applicants who vied for just 1,700 freshman seats last year.

> The university accepted nearly equal numbers of male and female prospects, though, like some other schools, it got nearly twice as many female applicants. That math meant it was easier for male students to get in — 7 percent of male applicants were admitted, compared with 4.4 percent of female applicants, university data shows.

> The Trump administration’s policies may soon put an end to that advantage enjoyed by men at some colleges, admissions and higher-education experts say.

> While much of the president’s recent scrutiny of college admissions practices has focused on race, these experts say his ban on diversity, equity and inclusion is likely to hit another underrepresented group of applicants: men, and particularly White men — the largest subset of male college applicants.

> “This drips with irony,” said Ted Mitchell, president of the American Council on Education, or ACE, the nation’s largest association of universities and colleges, who said he expects that colleges and universities will end any consideration of gender in admission. “The idea of males, including White males, being at the short end of the stick all of a sudden would be a truly ironic outcome.”

> “If we were going to eliminate preferences for men, the undergraduate population would skew to 65 percent female overnight,” Mitchell said.

*  The Billion-Dollar Ripple Effect---Trump’s research cuts will damage more than just universities.

[https://www.chronicle.com/article/the-billion-dollar-ripple-effect](https://www.chronicle.com/article/the-billion-dollar-ripple-effect)

> ...deep cuts to federal support for research could be a blow not just to university scientists, but to Xenopus 1 and other companies that work with colleges.

> But less attention has been paid to another potential casualty: the web of businesses that undergird academic science. Dewar [assistant professor of biochemistry] estimates that he spends between one-third and one-half of each grant he’s awarded by the National Institutes of Health and other federal agencies on materials and services from outside vendors.

> A 15-percent cap on indirect costs by the NIH alone could be a $29-million hit to Ann Arbor’s research-and-development supply chain — in addition to lost jobs and reduced household spending — according to an estimate produced for The Chronicle by IMPLAN, a company that provides economic-impact data and analysis. Nationally, the impact could be in the billions of dollars.

> “If that valve gets shut off,” said Bill Mayer, senior vice president for entrepreneurial services at Ann Arbor SPARK, a regional economic-development organization, “it’s massively disruptive.”

> Many of the 8,500 frogs Weymouth ships in an average year go to major American research universities. So far, he hasn’t lost customers, but his wife, Lissett L. Martinez, who handles company finances, said the number of frogs per order has been shrinking as researchers, worried about future grants, conserve their current funds.

## AI misdeeds

* Artificial Intelligence and the Problem of Fakery

[https://academeblog.org/2025/12/03/artificial-intelligence-and-the-problem-of-fakery/](https://academeblog.org/2025/12/03/artificial-intelligence-and-the-problem-of-fakery/)

> The problem stems from a stubborn fact about human nature, namely that the incentives we say we respond to are different from the ones that really move us. Universities, whatever their talk of being on the cutting edge, stake their legitimacy and economic survival on a system of incentives centering on the evaluation of classroom assignments. Following this system, students earn degrees and make their way in the world.

> Yet, such a system never counted on AI, whose real attraction (for most) is providing a simulacrum of honest effort. Saying that one is teaching responsible use and one does not intend to abet cheating misses the point. The urge to avoid exertion and get something for nothing is deeply ingrained. Foreboding about AI on campus is about fakery, plain and simple. Other aspects of AI beyond the academic context may be unsettling or exhilarating, depending on one’s perspective. Yet, in the classroom, authentic effort versus fakery is the central, unavoidable issue.

> Simultaneously, there is another group that also requires urgent attention. This is the, not inconsiderable, number of students who do not like the ongoing dishonesty but precisely because of that are falling into a crisis of their own. The notion that cheating “only hurts oneself” is entirely wrong. If enough people are doing it, it is only a matter of time before more people feel like suckers for making additional effort and taking more intellectual risks. Worse, once they start to suspect that the instructor’s feedback is also AI-generated, the feeling of demoralization grows apace.

## And just because it is fun

* More Colleges Celebrate Gifts From Philanthropist MacKenzie Scott

[https://www.insidehighered.com/news/quick-takes/2025/12/05/more-colleges-celebrate-gifts-philanthropist-mackenzie-scott](https://www.insidehighered.com/news/quick-takes/2025/12/05/more-colleges-celebrate-gifts-philanthropist-mackenzie-scott)

> Scott gave $50 million each to California State University, East Bay, the largest single donation in the university’s history, and to Lehman College, part of the City University of New York system, according to announcements from the institutions on Thursday. (Scott also gifted Lehman College $30 million in 2020 and has given a total of $125 million to campuses across the CUNY system in the last five years.)


----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
