# Dec 19

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

A bit abbreviated this week and next.


## Shared governance

* Faculty Want Answers on Oklahoma’s Suspension Policies

[https://www.insidehighered.com/news/faculty-issues/shared-governance/2025/12/18/faculty-want-answers-oklahomas-suspension-policies](https://www.insidehighered.com/news/faculty-issues/shared-governance/2025/12/18/faculty-want-answers-oklahomas-suspension-policies)


> Through their senate and American Association of University Professors (AAUP) chapter, faculty at the University of Oklahoma are pushing administrators for clarity on the suspension of Mel Curth, a graduate teaching assistant who was put on paid administrative leave last month after a student claimed Curth gave her an unfair grade because she cited the Bible.

> Faculty are also asking the university to strengthen its protection of instructors who are politically targeted or harassed. On Wednesday, the faculty senate voted on a vague resolution that doesn’t mention Curth by name but says that “several situations have left faculty and the greater OU community uncertain about the stability and clarity” of university protections against political meddling in teaching and scholarship. It also calls on the administration to “engage with [the faculty senate executive committee] in a review of our procedures for dealing with contentious issues and politically charged situations.” The result of the vote was not announced as of Wednesday evening.



## Academic freedom

*  The Classroom, Caught on Camera---Professors and students are increasingly worried what they say in class could end up on the internet.

[https://www.chronicle.com/article/the-surveilled-classroom](https://www.chronicle.com/article/the-surveilled-classroom)


(Thanks BE for raising question about existing policy)

> But faculty across the country told The Chronicle there has been a fundamental shift: Certain actors, upset by what happens in the classroom, are increasingly empowered to leverage internet outrage to effect change. A recent case, and a watershed moment to many faculty, was the firing of a Texas A&M University senior lecturer in September after a student’s recording of her lecture went viral on social media. The instructor’s two supervisors were also removed from their administrative roles, and the Texas A&M flagship’s president later resigned.

> Behind the crusade to monitor classrooms sits a well-funded media apparatus encouraging students to keep an eye on their professors.

> Among the first websites to marry the ubiquity of smartphones and social media to a clear partisan agenda was Campus Reform. Launched as a news site in 2012, the publication pays students for stories that “expose leftist bias and abuse.”

> Campus Reform established the playbook for a growing constellation of sites and social-media accounts, such as Turning Point USA’s Professor Watchlist and Canary Mission, that style themselves as “watchdogs.” Now a whole ecosystem, embedded within colleges, exists to churn out anecdotal content to support a narrative that higher education has lost its way.

> In 2021, Florida’s Legislature approved House Bill 233, allowing students to record class lectures not only for their own personal use, but also as “part of a complaint to the university” or as evidence in or preparation for a criminal or civil proceeding. Free-speech advocacy groups sounded alarms.

> A Cornell spokesperson said the university has clear procedures for faculty to follow if they have concerns about a student’s conduct. Cheyfitz, the spokesperson said, hadn’t followed this required process.

* When Everyone Can See Your Syllabus

[https://www.chronicle.com/article/when-everyone-can-see-your-syllabus](https://www.chronicle.com/article/when-everyone-can-see-your-syllabus)

> This summer, Christopher D. Petsko got a public-records request for the syllabus of one of his business courses at the University of North Carolina at Chapel Hill. The requesting group was a spinoff of the Heritage Foundation, a conservative think tank, and on the hunt for terms like “DEI,” “LGBTQ+,” and “antiracism” in materials for a total of 74 courses.

> But UNC-Chapel Hill told Petsko that his syllabus was his intellectual property, so he could choose whether or not to provide it under open-records law. Petsko took to LinkedIn to explain why he wouldn’t be complying, and why others didn’t need to do so, either. Then the Oversight Project, the group that had filed the request, got ahold of his syllabus through other means and declared aspects of it — an essay titled “Dear White Boss,” a podcast called “How to Bust Bias at Work” — to be “DEI garbage.” Critical comments flooded Petsko’s X mentions, and he deleted his account.

> Professors now fear the University of North Carolina system is about to open the door to more politically charged scrutiny. The university is preparing to enact a policy declaring that course syllabi are, in fact, public records. It’s also considering creating a publicly searchable database of information from all syllabi. If adopted, it’d be the latest syllabus-disclosure mandate to fall on public universities in red states, including Texas, Georgia, Indiana, Utah, Ohio, and Florida.

> Under heightened scrutiny over how race, gender, and other politically sensitive subjects are taught, these faculty members worry that right-wing groups and other people could pressure them to take out “unfavorable” readings, or use the information to harass them. The fear alone of any of these things happening, they said, could chill academic freedom. A petition against UNC’s proposal, circulated this month by the American Association of University Professors’ North Carolina chapter, has more than 2,700 signatures.

> Back in August, when the Oversight Project requested more than 70 course syllabi, the UNC flagship said no, citing its stance that a syllabus is the intellectual property of the faculty member who created it. But UNC-Greensboro told faculty around the same time to hand over syllabi to fulfill a similar public-records request, according to the local radio station WUNC. (Stancill, the UNC spokesperson, told The Chronicle that, at the time, individual campuses made their own interpretations as to whether syllabi were faculty-owned.)

> Mike Howell, president of the Oversight Project, said he had been preparing to sue UNC-Chapel Hill until news of its about-face reached him. “This notion that you could treat syllabi as basically the equivalent of copyright and trademark is absurd on its face, and an overextension of privacy law,” he said. Howell said earlier this year that his group has filed more than 100,000 public-records requests and nearly 100 lawsuits nationwide.

*  Is Your Course Content ‘Relevant’ and ‘Necessary’?---Texas Tech faculty are having to scrutinize lessons on race, gender, and even ‘The Great Gatsby.’

[https://www.chronicle.com/article/is-your-course-content-relevant-and-necessary](https://www.chronicle.com/article/is-your-course-content-relevant-and-necessary)

> Every fall, Linda Kornasky uses Walt Whitman’s poem, “A Song of Myself,” in her “American Romantic Literature” class to explore themes of nature, human connection, and LGBTQ identity.

> “His whole approach to poetry is to, as he says, celebrate himself,” said Kornasky, a tenured English professor at Angelo State University. “So the poem is very much something that promotes his own sexual identity.”

> Kornasky may soon need approval from her department chair, provost, and the Board of Regents to keep teaching Whitman’s poem, under a controversial policy set to be enacted next month at all Texas Tech system campuses.

> Under the policy, faculty will no longer be allowed to teach any content that promotes “activism” on issues related to race or sex, imply that one race or sex is “inherently superior” to another, or say that a person can be inherently racist, sexist, or oppressive. All course content that mentions sexual orientation and gender identity will require administrative review.

(Elections have *consequences*)

> Since last year, state legislatures in at least 12 states have passed laws that curtail what can be taught about politics and identity in college courses in response to the belief that faculty are indoctrinating students and prioritizing only leftist viewpoints. Texas’ Senate Bill 37 gives university boards authority to determine what courses can be considered a general-education requirement and creates an office to handle complaints about professors teaching irrelevant material.

(Also)

*  The Man Behind Texas Tech’s Controversial Curriculum Crackdown---Brandon Creighton believes colleges should focus on careers and salaries — not contested ideas about race, gender, and sexuality.

[https://www.chronicle.com/article/the-man-behind-texas-techs-controversial-curriculum-crackdown](https://www.chronicle.com/article/the-man-behind-texas-techs-controversial-curriculum-crackdown)

(Foxes and hen houses)

> Brandon Creighton, chancellor of Texas Tech University system, says that the new policy will help the university system produce degrees of “high value.” Creighton became chancellor in November after he resigned from his position as a state senator. As a Republican legislator, Creighton introduced several bills that banned diversity, equity, and inclusion efforts in public schools and restricted how K-12 teachers and university professors can teach about race and sex. Creighton cites one of the last anti-DEI bills he authored as a senator — SB 37 — as a reason for enforcing the new policy.

## Freedom of expression

* He Went on a Hunger Strike for Palestine. Did He ‘Misuse’ the Classroom?

[https://www.chronicle.com/article/he-went-on-a-hunger-strike-for-palestine-did-he-misuse-the-classroom](https://www.chronicle.com/article/he-went-on-a-hunger-strike-for-palestine-did-he-misuse-the-classroom)

> But Palestine remained on Kao’s [lecturer in the department of electrical engineering and computer sciences] mind. In late August of this year, he began a “starvation diet” of minimal calories to draw attention to Palestinians suffering and dying under famine conditions. This type of expression, Kao believed, was aboveboard. “In my view, what I eat for dinner is my First Amendment right,” he said in an interview with The Chronicle.

> Berkeley disagrees — the university suspended Kao without pay for six months, starting in January. While Kao can advocate for causes he believes in outside the classroom, the lecturer brought his political advocacy into the classroom, argued Benjamin E. Hermalin, the university’s provost, in a letter first reported by the student newspaper.

> According to Hermalin’s letter, Kao had mentioned the strike to students “at least twice” in class. He also cited an email interview that Kao gave to a news outlet called The New Arab published in September, in which Kao said, “With this hunger strike, I hope to bring the starvation here, to Berkeley, in front of my students,” to remind them of Palestinians’ humanity.

(Regents policy 2301 is from 1970)

[https://regents.universityofcalifornia.edu/governance/policies/2301.html](https://regents.universityofcalifornia.edu/governance/policies/2301.html)

>  They are responsible to ensure that public confidence in the University is justified. And they are responsible to see that the University remain aloof from politics and never function as an instrument for the advance of partisan interest. Misuse of the classroom by, for example, allowing it to be used for political indoctrination, for purposes other than those for which the course was constituted, or for providing grades without commensurate and appropriate student achievement, constitutes misuse of the University as an institution.

> it is The Regents' policy that no campus, no academic college, no department, and no instructor distort the instructional process in a manner which deviates from the responsibilities inherent in academic freedom.


* NYTimes: PEN America Elects New President at Fraught Time for Free Speech

[https://www.nytimes.com/2025/12/17/arts/dinaw-mengestu-pen-america-new-president.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/12/17/arts/dinaw-mengestu-pen-america-new-president.html?smid=nytcore-ios-share)

> [Q] In a recent essay, you wrote that PEN America’s defense of free expression is “not rooted in law but in literature and in the singular voice of writers who make it.” What do you mean?

> [A] Many groups advocate for free speech. But it’s the relationship between free expression and literature and writers that makes PEN America’s work so unique. If we lose awareness of how important our culture of literary and artistic production is, our understanding of free expression goes with it. If all those are eroded or devalued, you don’t have to worry about banning any books. They will be so marginal to society they no longer have value.

> [Q] Has the task of defending free expression changed in the second Trump administration?

> [A] Earlier this year, we had a report on all the words that the Trump administration has been trying to erase. That’s one way of calling attention to what is happening. Many voices in the country are unable to speak, afraid to speak. If you want to speak about trans rights, about Palestinian rights — those are really difficult things to talk about if you are in any way vulnerable, say, if you’re an immigrant. But there are some kinds of silencing that aren’t that easy to fight through the courts.


### Anti-woke/anti-DEI is simply racism

* Johns Hopkins U. Pares Back Diversity Programs, Limits Mentoring Efforts Aimed at Minority Students

[https://www.chronicle.com/article/tracking-higher-eds-dismantling-of-dei](https://www.chronicle.com/article/tracking-higher-eds-dismantling-of-dei)

> The Johns Hopkins University has pared back its diversity-related staffing and scrapped many diversity programs, The Baltimore Banner reported. According to former employees in the central diversity office, a three-member team devoted to inclusive-excellence education was laid off, and most other staff members have either resigned or moved to other roles. The chief diversity officer and her deputy left in June.

(Original reporting)

[https://www.thebanner.com/education/higher-education/johns-hopkins-university-diversity-programs-2CQCQZSV2JAM3DVYADYEIWJSPA/](https://www.thebanner.com/education/higher-education/johns-hopkins-university-diversity-programs-2CQCQZSV2JAM3DVYADYEIWJSPA/)


## Funding cuts

### NSF

* NSF Lowers Grant Review Requirements, NIH Hunts for Phrases

[https://www.insidehighered.com/news/quick-takes/2025/12/17/nsf-lowers-grant-review-requirements-nih-hunts-phrases](https://www.insidehighered.com/news/quick-takes/2025/12/17/nsf-lowers-grant-review-requirements-nih-hunts-phrases)

> Two major federal research funding agencies are altering their grant review processes. The National Science Foundation (NSF) is scaling back its reviews of grant proposals, according to a Dec. 1 internal memo that Science obtained and published, while STAT reported that the National Institutes of Health distributed guidance Friday ordering staff to use a “text analysis tool” to search for certain phrases.

> The memo said the changes “enable Program Officers to expedite award and decline decisions,” including by moving away from the “usual three or more reviews” of proposals. It said that, now, “full proposals requiring external review must be reviewed by a minimum of two reviewers or have a minimum of two reviews. An internal review may substitute for one.”

> But another media outlet, NOTUS, published a more critical article on the guidance, saying the “Trump administration is pausing new funding for National Institutes of Health grants that include terms like ‘health equity’ and ‘structural racism,’ pending review.” NOTUS reported that the guidance says new funding won’t be provided to “misaligned” grants until “all areas of non-alignment have been addressed.”


## Federal Agencies

### DOE/OCR

* Pomona College, UC Settle Antisemitism Allegations

[https://www.insidehighered.com/news/quick-takes/2025/12/15/pomona-college-uc-settle-antisemitism-allegations](https://www.insidehighered.com/news/quick-takes/2025/12/15/pomona-college-uc-settle-antisemitism-allegations)

> Both Pomona College and the University of California settled antisemitism allegations last week.

> Pomona’s agreement resolves an antisemitism complaint filed with the Education Department’s Office for Civil Rights in April 2024, amid intense pro-Palestinian protests on the California campus. In the 27-page deal, the private college “acknowledges that many Jewish students experience anti-Zionism as an attack on their Jewish identity, ethnicity, religion, and/or ancestry, which means these students experience anti-Zionism as antisemitism, and the College commits to protect them from such conduct that rises to the level of harassment and discrimination.”

> Among many other things, Pomona promised to add to its trainings and frequently asked questions a warning that “‘Zionist’ is often used as a codeword for ‘Jew,’ and depending on the factual circumstances, may be evidence of antisemitic intent.” It will also warn against “invoking Holocaust imagery or symbols to harass or discriminate” or saying things such as “Zionists control the media.”

> In addition, the college promised programming, including on “the Zionist component of Jewish identity.” In its own investigations of antisemitism complaints it also promises to consider the controversial International Holocaust Remembrance Alliance (IHRA) definition of antisemitism, which says antisemitism “might include the targeting of the state of Israel.”

> But Laura Beltz, policy reform director for the Foundation for Individual Rights and Expression (FIRE), expressed concern that the settlement requires Pomona to push for changes to demonstration policies that would affect all the Claremont Colleges and “may infringe on free speech, depending on how they are adopted.” She particularly noted proposed requirements for advance approvals even for protests that include just a few people, and a proposed mandate that “protests meeting some unspecified threshold of attendees” take place in certain campus locations.

> Also last week, the University of California settled a lawsuit that Yael Nativ, a former visiting faculty member at UC Berkeley, filed in August. Nativ had alleged national origin discrimination, saying a department chair declined her application to continue teaching because she’s Israeli.

> Berkeley’s Office for the Prevention of Harassment and Discrimination had already concluded Nativ was discriminated against. To settle the suit, UC agreed to pay her $60,000, and her attorneys $56,000, and to allow her to teach her course, with pay, in 2026 or 2027. Berkeley chancellor Rich Lyons also promised to apologize to her personally.

> Both complaints were filed by organizations including the Louis D. Brandeis Center for Human Rights Under Law, which filed a swath of Title VI complaints after Oct. 7, 2023.

## Institutional assaults

### Admissions

### Accreditation

* ‘Buckle Up’: Trump Official Pledges to Fix Accreditation

[https://www.insidehighered.com/news/governance/accreditation/2025/12/17/kent-tells-accreditation-panel-buckle](https://www.insidehighered.com/news/governance/accreditation/2025/12/17/kent-tells-accreditation-panel-buckle)

> The Trump administration has cast accreditation as beset by alleged woke priorities, a theme repeated Tuesday along with pledges to shake up the system. Concerns about a supposed pervasive liberal ideology among such bodies prompted an executive order in April that threatened to strip federal recognition from accreditors that require institutions to engage in unlawful diversity practices. The Department of Education is also seeking public comment on accreditation reform, which officials have said is to increase transparency and efficiency, and is planning to update the rules for accreditors next year.

> Tuesday’s meeting began with the election of a new NACIQI chair, a process that required two votes after the 18-member board tied on the first try. After the second vote, Jay Greene, a former senior research fellow at the Heritage Foundation and sharp critic of diversity, equity and inclusion initiatives, was named chair. He was among the five Department of Education appointees named in November.

> Greene promised “to be a fair, even-handed chair” despite the “awkwardness” of the vote, which he won after Jennifer Blum, a Republican appointee abstained after voting against Greene in the election.

> The under secretary [Nicholas Kent] further argued that accreditors have inserted ideological criteria into standards that fuel “discriminatory practices, mandatory DEI requirements, racial preferences in hiring, compulsory sensitivity training and political litmus tests” that “undermine merit” and “chill free speech.” (Most institutional accreditors paused or suspended DEI standards earlier this year following an executive order seeking to crack down on DEI, others never had such standards.)

> “We’re breaking the mold in this administration. We’re doing things differently, we’re conducting negotiated rule makings differently … I think we all agree there are real issues with NACIQI, there are real issues with the accreditation recognition process. We’re going to fix a lot of it,” Kent said. “So everybody, buckle up, we got a lot of work ahead of us.”

### The New School

* ‘We’re Being DOGE-ed’: Sweeping Buyout Plan Rattles the New School’s Faculty

[https://www.chronicle.com/article/were-being-doge-ed-sweeping-buyout-plan-rattles-the-new-schools-faculty](https://www.chronicle.com/article/were-being-doge-ed-sweeping-buyout-plan-rattles-the-new-schools-faculty)

> Several turbulent currents in higher education are colliding on the New School’s Manhattan campus. Like many other colleges, it faces rising expenses and flagging enrollment, which has made its finances precarious. Like some other institutions, it is making faculty cuts quickly and with little or no significant input from professors, a departure from shared-governance ideals. And some faculty members worry that slashing the progressive institution, which was founded as the New School for Social Research in 1919, dovetails with the ongoing backlash against leftism and intellectualism across the country.

> Over the summer, the institution convened five working groups, which included professors, to come up with suggestions on how to improve and restructure the New School. “Let’s recommit to what it is this university is fundamentally about,” Towers said. With its rich tradition of liberal arts and performing and visual arts, he added, the New School seemed ideally poised for “problem solving at its core. It’s design-oriented and innovation-oriented. It’s really focused on contemporary issues facing society.”

> But Varon, who did not sit on any of the committees, said he and other colleagues were uncertain how restructuring would fix their immediate problems. And many faculty members are concerned, he said, “that the budget piece would be addressed through a completely top-down, non-participatory, non-consultative process.”

> Who does the work at the New School may shift after the dust from the changes settles. About one in five of the 2,100 faculty members at the New School are full-time. Parsons has been the economic engine of the New School for several years and operates mostly with part-time faculty — in 2022, only 17 percent of its professors were full-time. At the New School for Social Research, where many of the separation letters were addressed, only 16 percent of its faculty members were part-time.


----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
