# Dec 12

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

## Academic freedom

* NYTimes: How One Student’s Failing Grade Became a Cause Célèbre on the Right

[https://www.nytimes.com/2025/12/06/opinion/college-student-complaints.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/12/06/opinion/college-student-complaints.html?smid=nytcore-ios-share)

> Fulnecky says she is a victim of religious discrimination and lodged a formal complaint with the university. The teaching assistant who gave her the grade has been placed on administrative leave, and the university said in a statement on X that “a formal grade appeals process was conducted. The process resulted in steps to ensure no academic harm to the student from the graded assignments.”

> Culture warriors like Fulnecky and the Oklahoma conservative politicians supporting her are merely taking advantage of a decades-long trend in higher education: Students think they are customers who deserve to be catered to, rather than curious humans who might have something to learn.

> Flaherty cites a 2010 paper called, “The customer isn’t always right: Limitations of ‘customer service’ approaches to education or why Higher Ed is not Burger King,” which has an elegant explanation of the difference between education and a typical consumer transaction. “An education can not be had unless the person being educated is engaged in the process. Lessons can be given, but learning remains the responsibility of the learner. The practice of education is, then, necessarily cooperative; it is not a simple exchange of services for pay.”

> Fulnecky caused a stir, and on Dec. 3, she spoke at a meeting of the Oklahoma Constitutional Principles Affecting Culture Foundation, a conservative think tank. While I can’t say if she learned anything in the classroom, she has certainly memorized the plan for becoming a right-wing heroine.

* Another Okla. Instructor Put On Leave, This Time for ‘Viewpoint Discrimination’

> The University of Oklahoma’s Turning Point USA chapter said its president filed the complaint after a lecturer offered to excuse from class only students who protested in support of another professor.

>  The Director further stated that any student, regardless of viewpoint, would be excused if absent from class today to attend the protest without penalty, and that the lecturer had been replaced, effective immediately, for the remainder of the semester,” officials wrote in a statement Friday. “Classroom instructors have a special obligation to ensure that the classroom is never used to grant preferential treatment based on personal political beliefs, nor to pressure students to adopt particular political or ideological views.”

* After Censoring Again, Weber State Says It Will Be ‘More Nuanced’ in Applying Law

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/12/10/facing-criticism-weber-state-says-it-will-be-more](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/12/10/facing-criticism-weber-state-says-it-will-be-more)

> After multiple censorship controversies over the past two months, Weber State University has announced a “revised approach” to how it enforces a sweeping anti–diversity, equity and inclusion law that the Utah Legislature passed in 2024. But it remains unclear exactly how it will change its actions.

> Weber State made national headlines in October for censoring a conference ironically titled, Redacted: Navigating the Complexities of Censorship. A few days before the conference was to start, an official at the public institution ordered a student presenter to remove all references to DEI from their slides.

> Organizers ended up canceling the event after faculty pulled out in protest. The uncertified employee union held a teach-in instead, but it was also censored.

> That wasn’t the end of Weber State’s speech restrictions. Late last month, Apache writer Darcie Little Badger announced on Bluesky she was withdrawing as keynote speaker at the university’s annual Native Symposium because the university sent her a list of 10 prohibited words and concepts, including “bias,” “oppression” and “racial privilege.”

* IU Prof Suspended for White Supremacy Graphic Returns to Class

[https://www.insidehighered.com/news/quick-takes/2025/12/10/iu-prof-suspended-white-supremacy-graphic-returns-class](https://www.insidehighered.com/news/quick-takes/2025/12/10/iu-prof-suspended-white-supremacy-graphic-returns-class)

> Adams was suspended earlier this fall after a student complained about an iceberg-style graphic that she used in her class to illustrate overt, socially unacceptable forms of white supremacy like lynching and racial slurs, and covert, socially acceptable forms of white supremacy like the school-to-prison pipeline, colorblindness and housing discrimination. The student contacted U.S. Senator Jim Banks, a Republican, who in turn contacted Adams’s dean.

> Adams was removed from class while administrators investigated the student’s complaint. She received a formal sanction from the university, which she is appealing. The university also placed monitors in all of her classes.


## Freedom of expression

* Tenured US professor fired over pro-Palestinian protests contests dismissal | California | The Guardian

[https://www.theguardian.com/us-news/2025/dec/05/tenured-professor-fired-pro-palestinian-protests](https://www.theguardian.com/us-news/2025/dec/05/tenured-professor-fired-pro-palestinian-protests)

> Kil, who is contesting her dismissal, was the second tenured faculty member dismissed from a US public university over pro-Palestinian activism after Steven Salaita, who was fired in 2014 from the University of Illinois over a series of social media posts critical of Israel’s bombing of Gaza that year. Maura Finkelstein, another tenured professor, was fired from Muhlenberg College, a private liberal arts college, following her criticism of Israel’s most recent war in Gaza, while Katherine Franke, a Columbia University law professor and longtime advocate for Palestinian rights was forced out amid what she called a “toxic and hostile environment for legitimate debate around the war in Israel and Palestine”.

> Kil’s firing adds to mounting concerns about academic freedom and campus free speech at a time when universities are facing unprecedented pressure from the Trump administration – but her case also raises questions about faculty’s free speech rights when engaged in so called “extramural” speech outside the classroom.

> The university’s case against Kil stems from a confrontation involving students and a faculty member at a tense February 2024 protest on campus, which she attended. The university also accused Kil of making remarks at a different event that it said encouraged students to stage an encampment in violation of university policy, as well as of eventually participating in such a student-led encampment.

>  “You can’t fire people for their beliefs and expression,” said V Jesse Smith, a union representative. “It’s an infringement on free speech and academic freedom, and as a faculty union, we cannot let this happen.” Kil said she planned to sue the university should the arbitration fail.

> Last June, following an investigation, the university informed Kil that it would dismiss her over alleged violations of university policies, including “time, manner and place” restrictions intended to restrict protests. A faculty committee that reviewed the dismissal confirmed some of the allegations that Kil had violated university policy but concluded that the dismissal was disproportionate and not justified, according to internal documents reviewed by the Guardian.

> But the university president, Cynthia Teniente-Matson, upheld Kil’s dismissal despite the review and rebukes from the American Association of University Professors, Middle East Studies Association and California Scholars for Academic Freedom, among other groups. In a November letter, Teniente-Matson accused Kil of putting “the education and physical safety of our students at serious risk” and of doing so “with intentional disregard for University policies, policies of which you were aware but also that you committed to follow when taking up the position of advisor to a student organization”.

### Anti-woke/anti-DEI is simply racism

* After Suspension, U. of Alabama Alumni Offer to Fund Black-Culture and Women’s-Fashion Student Magazines

[https://www.chronicle.com/article/tracking-higher-eds-dismantling-of-dei](https://www.chronicle.com/article/tracking-higher-eds-dismantling-of-dei)

> Alumni of the University of Alabama at Tuscaloosa offered to cover the printing costs for two student magazines that the university suspended last week. The University of Alabama halted publication of Alice and Nineteen Fifty-Six on December 1, citing new Department of Justice guidance about “unlawful discrimination.” The magazines focus on fashion and Black culture, respectively. MASTHEAD, an alumni group focused on promoting student journalists of color at the University of Alabama, condemned the suspensions and offered to support the publications’ production. “We’d be really excited to try to get these magazines printed for them in the spring, if that’s what the students want to do,” Victor Luckerson, MASTHEAD’s president, told AL.com.


## Visas

* University, ICE Clash Over Details of Student’s Arrest

[https://www.insidehighered.com/news/quick-takes/2025/12/10/university-ice-clash-over-details-students-arrest](https://www.insidehighered.com/news/quick-takes/2025/12/10/university-ice-clash-over-details-students-arrest)

> Augsburg University administrators and federal officials are giving conflicting accounts about what happened when Immigration and Customs Enforcement agents arrested an undocumented student on the private campus over the weekend, The Minneapolis Star Tribune reported.

> On Saturday, ICE agents in an unmarked car followed Jesus Saucedo-Portillo into a parking lot on the Minneapolis campus and attempted to detain him. Campus security and residence hall officials observed the situation and tried to intervene. Soon, more agents arrived, “pointing weapons at the crowd and pushing witnesses back” as students began recording the incident, according to a campuswide email Provost Paula O’Loughlin wrote Saturday evening: “I want to emphasize that the staff and other Augsburg community members who were present followed our protocols.”

> According to the university, when a senior administrator asked to see a judicial warrant, agents said they didn’t have one and eventually arrested Saucedo-Portillo. “It was done on private property, without a warrant,” Paul Pribbenow, president of the university, told the Star Tribune. “From our perspective, that is illegal.”

> A judicial warrant signed by a federal judge is required for officers to enter private property or detain someone there, according to the National Immigration Law Center. ICE arrest warrants are typically signed by immigration officials and agents must get permission to enter private areas.

> However, the Department of Homeland Security has since contested the university’s claims that ICE agents didn’t have an arrest warrant. In a statement Monday, Tricia McLaughlin, assistant secretary of public affairs for DHS, accused the university administrators on the scene of attempting “to obstruct the arrest.”

> The university says its “previous statements about the incident remain unchanged,” a university spokesperson, told the newspaper Tuesday. “When asked to provide a judicial warrant, the agents refused to produce and stated they did not have one, despite being on private property.”


## Funding cuts

* New Model Legislation Aims to Curb ‘Unserious’ Research in Non-STEM Fields

[https://www.chronicle.com/article/new-model-legislation-aims-to-curb-unserious-research-in-non-stem-fields](https://www.chronicle.com/article/new-model-legislation-aims-to-curb-unserious-research-in-non-stem-fields)

> Three right-leaning organizations this month released model state legislation intended to reduce “taxpayer funding for intellectually unserious ‘research’ projects of activist academics” at public institutions. One of them, the Goldwater Institute, has been successful in getting numerous state legislatures to enact laws based on its models outlawing diversity, equity, and inclusion programs.

> The proposal, released with Defending Education and the James G. Martin Center for Academic Renewal, emphasizes what it sees as a need to monitor faculty members in non-STEM fields and the importance of teaching about Western civilization.

(This part is just wacko)

> The model legislation has four parts:

> *  Faculty members who teach a foundational course in Americanism and Western civilization could apply for tenure without having their research evaluated. The model spells out how teaching should be evaluated, including requiring the syllabus to be reviewed and considering the rigor of the courses.
> *  Full-time faculty members teaching in fields outside of STEM or Americanism and Western civilization would be required to teach 18 credit hours per year.
> *  Research outside of STEM fields would be subject to additional scrutiny.
> * Governing boards would be required to approve the posting of any new faculty jobs outside of STEM, Americanism, and Western civilization.


> But critics say the model legislation would be a step in the wrong direction. Todd Wolfson, president of the American Association of University Professors, said in a written statement that the proposal would “devastate higher education by placing scholarly inquiry — especially in the humanities, social sciences, and other non-STEM fields — under direct political control, ideological litmus tests, and a narrow obsession with ‘Western civilization’ and ‘Americanism.’”

> The Goldwater Institute has had recent success with model state legislation, including in 2023 when it proposed, along with the Manhattan Institute, a law banning diversity, equity, and inclusion programs and staff in higher education. Variations of that legislation have been adopted in 29 states, according to The Chronicle’s DEI Legislation Tracker. Several states have also adopted laws inspired by Goldwater’s model legislation from the same year that would ban students from being required to take college classes promoting what it calls ideological activism, including critical race theory and diversity, equity, and inclusion.

> As many states tighten their grip on higher education, watch to see if lawmakers, particularly in red states, take up this model legislation or variations of its theme. In Wisconsin, a new law mandates that faculty members at most University of Wisconsin campuses must teach at least eight courses per year. The new model bill differs in singling out non-STEM faculty members.

(LE shared this link on the topic)

[https://archive.is/20251210183932/https://www.forbes.com/sites/michaeltnietzel/2025/12/09/proposed-model-bill-would-change-college-tenure-teaching--research/](https://archive.is/20251210183932/https://www.forbes.com/sites/michaeltnietzel/2025/12/09/proposed-model-bill-would-change-college-tenure-teaching--research/)

### NIH

* After losing NIH support, cancer researcher struggles to keep lab open : Shots - Health News : NPR

[https://www.npr.org/sections/shots-health-news/2025/12/09/nx-s1-5630892/nih-nci-breast-cancer-research-harvard-joan-brugge](https://www.npr.org/sections/shots-health-news/2025/12/09/nx-s1-5630892/nih-nci-breast-cancer-research-harvard-joan-brugge)

> The next research challenge for Brugge's lab is clear: find ways to detect, isolate and terminate the mutant cells before they have a chance to spread and form tumors.

> "I'm excited about what we're doing right now," Brugge says. "I think we could make a difference, so I don't want to stop."

> But this year, work in Brugge's lab slowed way, way down. In April, her $7 million breast cancer research grant from the National Cancer Institute at the National Institutes of Health (NIH) was frozen, along with virtually all federal money awarded to Harvard researchers.

> Brugge scrambled to secure private funding from foundations and philanthropists. She was then able to reinstate two positions for at least a year — but job applicants are wary. Across the United States, the future of federal funding for cancer research is uncertain.


## Federal Agencies

### DOE/OCR

* Education Dept. Wants to Begin and End Workforce Pell This Week

[https://insidehighered.com/news/government/student-aid-policy/2025/12/08/ed-wants-begin-and-end-workforce-pell-week](https://insidehighered.com/news/government/student-aid-policy/2025/12/08/ed-wants-begin-and-end-workforce-pell-week)

> For instance, the OBBBA [One big "beautiful" bill] says that in order to be eligible for the Workforce Pell, certificate programs must be deemed “in-demand,” “high-skill” or “high-wage.” They also must be proven to have a 70 percent completion rate and a 70 percent job placement rate in a career related to the program and pass an earnings test that compares tuition to the median salary of graduates. And while the Trump administration’s initial proposal addresses those elements, delegating some responsibilities to the states and retaining others for the federal government, multiple policy experts told Inside Higher Ed that often, the line in the sand is not clear enough.

(Among many concerns about process)


* Education Dept. Labels Hundreds of Colleges as ‘Lower Earnings’

[https://www.insidehighered.com/news/government/student-aid-policy/2025/12/09/ed-designates-23-colleges-lower-earnings](https://www.insidehighered.com/news/government/student-aid-policy/2025/12/09/ed-designates-23-colleges-lower-earnings)

> irst-time undergraduates applying for federal student aid will now receive a warning if they indicate interest in an institution where graduates don’t earn more than an adult with a high school diploma.

> The new earnings indicator on the Free Application for Federal Student Aid is aimed at ensuring students have more information about their postsecondary options, Education Department officials said in a news release Monday. Consumer protection advocates generally praised the department’s move, while institutional groups criticized it.

(CUNY is not flagged. Data is at:)

[https://studentaid.gov/data-center/school/earnings](https://studentaid.gov/data-center/school/earnings)


(Also)

[https://www.chronicle.com/blogs/the-trump-agenda/nearly-one-fourth-of-colleges-will-come-with-a-warning-when-students-apply-for-financial-aid](https://www.chronicle.com/blogs/the-trump-agenda/nearly-one-fourth-of-colleges-will-come-with-a-warning-when-students-apply-for-financial-aid)

## Congressional actions

## State actions

## Institutional assaults

* Let’s take a closer look at MIT, one target of Trump’s blunderbuss

[https://www.washingtonpost.com/opinions/2025/12/12/mit-trump-education-universities/](https://www.washingtonpost.com/opinions/2025/12/12/mit-trump-education-universities/)

(George Will can't quite shed his belief in his party, but still notes:)

> The 8 percent tax on MIT’s endowment will cost the university $240 million annually that will not be available to make up for reductions in government research grants. Universities’ endowments fuel upward mobility and combat the stagnation of elites. Taxing endowments mocks conservatism by enfeebling private sector alternatives to government’s domination of social resources.

> Finally, it is almost sublimely hilarious that Trump’s compact forbids universities to “belittle” — wait for it — “conservative ideas.” Such as? Civility? Free trade? Fiscal continence? The separation of powers? The rule of law? Keeping the public and private sectors distinct by not conscripting corporations (Intel, U.S. Steel and others) into the public sector? Government too modest to decree that universities must be “safe spaces” for conservatives (who used to be proud of not being snowflakes)?

> The Trump administration is today’s comprehensive belittler of conservative ideas. Its solicitude for “conservative ideas” will not encompass this one: Many things are beyond government’s proper scope and actual competence. Watching today’s politics toy with an institution of MIT’s complexity and importance is like watching a toddler play with Sèvres porcelain.



### Admissions


* Purdue Allegedly Rejecting Chinese, Other ‘Adversary Nation’ Grad Students

[https://www.insidehighered.com/news/admissions/graduate/2025/12/12/purdue-allegedly-rejecting-chinese-other-grad-students](https://www.insidehighered.com/news/admissions/graduate/2025/12/12/purdue-allegedly-rejecting-chinese-other-grad-students)

> Current and prospective Purdue University graduate students say the institution rejected a slew of Chinese applicants from its grad programs for this academic year. Also, one grad student says the university told grad admissions committees in the past couple of months that it’s highly unlikely to accept students from any “adversary nation” for next year.

> Faculty were told those countries are China, Cuba, Iran, North Korea, Russia and Venezuela, said Kieran Hilmer, a teaching assistant on the leadership committee of Graduate Rights and Our Wellbeing (GROW), a group trying to unionize Purdue grad workers. That list broadly matches the commerce secretary’s catalog of foreign adversaries.

> Hilmer said the university conveyed this prohibition verbally. “They didn’t write any of this down,” he said.

> Multiple heads of graduate admissions committees didn’t respond to Inside Higher Ed’s requests for comment Thursday; one who answered the phone referred a reporter to the press office, which didn’t respond. Emails sent to Office of Graduate Admissions employees went unanswered.

> While Purdue won’t explain what actions it’s taking or why, the U.S. House Select Committee on the Chinese Communist Party said in a September report that it’s been investigating Purdue and five other universities—Stanford and Carnegie Mellon Universities and the Universities of Maryland, Southern California and Illinois at Urbana-Champaign—all year “regarding the presence and research activities of Chinese national students on their campuses.”


### Accreditation

* ED Seeks Public Comment on Accreditation Reform

[https://www.insidehighered.com/news/quick-takes/2025/12/11/ed-seeks-public-comment-accreditation-reform](https://www.insidehighered.com/news/quick-takes/2025/12/11/ed-seeks-public-comment-accreditation-reform)

> Commenters will have 45 days to provide feedback on the following questions:

> * What policies or standards are encouraging innovation or reducing college costs within the postsecondary education sector and should be retained in or added to the new version of the handbook?
> * How can the handbook be designed to be less burdensome?
> * Is the handbook serving its intended purpose?
> * How can it better assist accrediting agencies and associations in evaluating the quality of educational institutions and programs or in applying for federal recognition?
> * How could accreditation standards be updated to incentivize intellectual diversity on campus?
> * What guidance or standards, if any, can the handbook provide to institutions and programs to help achieve this goal?
> * What methods should be incorporated into the handbook to determine appropriate assessment benchmarks, and what data sources or validation methods could be used to ensure those benchmarks reflect student competency?




### Harvard

* I’m a red state governor. What I saw at Harvard surprised me.

[https://www.washingtonpost.com/opinions/2025/12/08/harvard-eric-holcomb-indiana-governor/](https://www.washingtonpost.com/opinions/2025/12/08/harvard-eric-holcomb-indiana-governor/)

> Friends warned me that a den of woke lions would maul me or try to turn me into one of them. Neither happened. I suffered no grievous insults, surrendered none of my conservative principles and witnessed no disruptive behavior on a quiet campus.

(And this is supposed to be surprising? Maybe that a two-time governor believes in deliberate misinformation as a child does in Santa Claus is surprising...)

* Harvard Health and Human Rights Director Stepping Down

[https://www.insidehighered.com/news/quick-takes/2025/12/12/harvard-health-and-human-rights-director-stepping-down](https://www.insidehighered.com/news/quick-takes/2025/12/12/harvard-health-and-human-rights-director-stepping-down)

> The director of Harvard University’s François-Xavier Bagnoud Center for Health and Human Rights will step down in January after seven years at the helm, dean of the Harvard T. H. Chan School of Public Health Andrea Baccarelli announced Tuesday. News of her departure follows months of criticism of the center’s Palestine Program for Health and Human Rights.

> The center’s Palestine Program for Health and Human Rights drew increased scrutiny after Hamas’s Oct. 7, 2023, attack in Israel, including from former Harvard president Larry Summers and New York congresswoman Elise Stefanik. In previous years, the program partnered with Birzeit University in the West Bank, but Harvard declined to renew that partnership in the spring. In their April report on antisemitism on campus, Harvard officials detailed complaints from students about the program’s webinars, in which speakers allegedly “presented a demonizing view of Israel and Israelis.”



###  University of California

*  The Shakedown---How Trump’s Justice Department pressured lawyers to “find” evidence that UCLA had tolerated antisemitism

[https://www.chronicle.com/article/the-shakedown](https://www.chronicle.com/article/the-shakedown)

> )n the morning of Thursday, July 31, James B. Milliken was enjoying a round of golf at the remote Sand Hills club in western Nebraska when his cell phone buzzed.

> Milliken was still days away from taking the helm of the sprawling University of California system, but his new office was on the line with disturbing news: The Trump administration was freezing hundreds of millions of dollars of research funding at the University of California at Los Angeles, UC’s biggest campus. Milliken quickly packed up and made the five-hour drive to Denver to catch the next flight to California.

> He landed on the front lines of one of the most confounding cultural battles waged by the Trump administration.

> In the months since Milliken’s aborted golf game, much has been written about the Trump administration’s efforts to impose its will on UCLA, part of the nation’s largest and most prestigious public-university system. But an investigation by The Chronicle of Higher Education and ProPublica, based on previously unreported documents and interviews with dozens of people involved, reveals the extent to which the government violated legal and procedural norms to gin up its case against the institution. It also surfaced something equally alarming: how the UC system’s deep dependence on federal money inhibited its willingness to resist the legally shaky onslaught, a vulnerability the Trump administration’s tactics brought into sharp focus.

> According to former DOJ insiders, agency political appointees dispatched teams of career civil-rights lawyers to California in March, pressuring them to rapidly “find” evidence backing a preordained conclusion: that the UC system and four of its campuses had illegally tolerated antisemitism, which would violate federal civil-rights statutes.

> The career attorneys eventually recommended a lawsuit against only UCLA, which had been rocked by pro-Palestinian protests in the spring of 2024. But even that case was weak, the lawyers acknowledged in a previously unreported internal memo we obtained. It documented the extensive steps UCLA had already taken to tackle antisemitism, many resulting from a Biden-administration investigation based on the same incidents. The memo also noted there was no evidence that the harassing behavior that peaked during the protests was still happening.

> Nonetheless, investigators sketched out a convoluted legal strategy to justify a new civil-rights complaint against UCLA that several former DOJ lawyers called problematic and ethically dubious. Multiple attorneys who worked on it told us they were relieved they’d left the DOJ before they could be asked to sign it.

> UCLA seemingly had every reason to push back aggressively. Yet UC system leaders have resisted calls from faculty and labor groups to file suit, fearing the many ways the government could retaliate against not only UCLA, but the entire university system, which relies on federal funds for a full one-third of its revenue. The government has opened probes into all 10 UC campuses, including at least seven that target UC-Berkeley alone. “Thankfully, they’ve only fucked with UCLA at this point,” said one UC insider privy to the system’s thinking.

> Some of Trump’s DOJ appointees arrived with UC already in their crosshairs. Harmeet K. Dhillon, Trump’s assistant attorney general for civil rights, had sued UC officials in 2017 on behalf of two conservative student groups, alleging unfair treatment of conservative speakers they wanted to bring to the Berkeley campus. (UC settled the case a year later, agreeing to modify rules for speakers at Berkeley and pay $70,000 in legal costs.) And Trump had named Leo Terrell, the bombastic former Fox News commentator to a top DOJ civil-rights post where he heads the president’s Task Force to Combat Anti-Semitism. A UCLA law-school graduate, Terrell had publicly declared in mid-2024 that his alma mater was “a national embarrassment” over its handling of “criminal antisemitic conduct.” Dhillon and Terrell didn’t respond to requests for comment.

> In early February, just two weeks after Trump took office, his new attorney general, Pam Bondi, issued a series of directives to the DOJ requiring “zealous advocacy” for Trump’s executive orders, attacks on all forms of “illegal DEI,” and aggressive steps to combat antisemitism. Civil-rights actions and investigations involving race and sex discrimination, historically the civil-rights division’s chief focus, were largely abandoned.

> On February 28, Terrell’s task force announced plans to visit 10 U.S. campuses, including UCLA and UC-Berkeley, that were alleged to have illegally failed to protect Jewish students and faculty members, to assess “whether remedial action is warranted.”

> But by then, the new Justice Department leadership had already decided to investigate UC institutions and had already concluded that they were guilty.

> Most significantly, in the waning days of the Biden administration, the UC system had reached a broad civil-rights settlement with the Department of Education resolving investigations into student complaints that UC had tolerated both antisemitism and anti-Arab and anti-Muslim discrimination at UCLA and on four other campuses.

> The settlement required UC to conduct more thorough investigations of alleged harassment and to submit reports on each campus’s handling of discrimination complaints. Government monitoring was to continue until UC “demonstrated compliance” with “all the terms of this agreement.”

> The Trump administration disregarded all that. Even as the employee investigation was underway, it launched a new investigation of the student complaints in early May.

> In the 47-page recommendation memo the UC team sent on May 29 to Dhillon, the assistant attorney general for civil rights, the lawyers spelled out their concerns. “We simply do not have strong evidence that the types of harassing acts that happened through spring 2024 are ongoing” — typically a legal requirement for bringing a complaint, the memo acknowledged. Some of the harassment complaints also involved protected First Amendment speech. And because, “as has been frequently noted,” the investigation had been “truncated” to three months, there hadn’t even been time to review some of the documents UC produced, the memo said.

> On the morning of July 29, two days before Milliken’s interrupted golf game, the University of California resolved what it surely hoped was among the last of the headaches from the 2024 encampment debacle: It announced a $6.45-million settlement of an antisemitism lawsuit brought by three Jewish students and a faculty member who said protesters blocked them from accessing the library and other campus buildings, creating a “Jew exclusion zone,” and that the university did nothing to help them. UC agreed to an extensive list of new actions, and a chunk of the money went to eight organizations that combat antisemitism and support the UCLA Jewish community. The steps the university had taken, a joint statement declared, “demonstrate real progress in the fight against antisemitism.” --- The Trump administration had a different view.

### University of North Carolina

* UNC Professors Must Soon Post Syllabi Publicly

[https://insidehighered.com/news/faculty-issues/academic-freedom/2025/12/12/unc-professors-must-soon-post-syllabi-publicly](https://insidehighered.com/news/faculty-issues/academic-freedom/2025/12/12/unc-professors-must-soon-post-syllabi-publicly)

> Two months after legal teams at University of North Carolina system campuses split over whether syllabi are considered public documents, system president Peter Hans announced plans to adopt a new policy that will answer an unequivocal yes.

> Starting as early as next fall, faculty members at UNC institutions will be required to upload their syllabi to a searchable public database, according to a draft of the policy provided to Inside Higher Ed by student journalists at The Daily Tar Heel. These public syllabi must include the course name, prefix, description, course objectives and student learning outcomes, as well as “a breakdown of how student performance will be assessed, including the grading scale, percentage breakdown of major assignments, and how attendance or participation will affect a student’s final grade.” Faculty must also include any course materials that students are required to purchase.

> “Public university syllabi should be public records, and that will be the official policy of the UNC System,” Hans wrote in a Thursday op-ed in the News & Observer. “We are living through an age of dangerously low trust in some of society’s most important institutions. While support for North Carolina’s public universities remains strong and bipartisan, confidence in higher education generally has dropped in recent years, driven by concerns about value and a perception that some colleges and universities have drifted from their core mission.”

> The draft policy does not explicitly require instructors to list their names on their syllabi and states that “nothing within this regulation shall be construed to require a publicly available syllabus to include the location or time of day at which a course is being held.” This stipulation provides little comfort to faculty members, Boggs [president of the North Carolina American Association of University Professors chapter] said.

> “As many of us have noted, there are many of us who are the only faculty who teach a particular class, and it is very easy to find out when our class is and where our classes are,” she said. “That does not make me feel safer.”

> Hans acknowledged critics’ weaponization of syllabi in his op-ed.


(Article by Peter Hans, who rose to position from being president of the NC CC System)

[https://www.newsobserver.com/opinion/article313599782.html](https://www.newsobserver.com/opinion/article313599782.html)






### University of Texas

* NYTimes: The Conservative Overhaul of the University of Texas Is Underway

[https://www.nytimes.com/2025/12/10/us/university-of-texas-republicans-academic-freedom-faculty.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/12/10/us/university-of-texas-republicans-academic-freedom-faculty.html?smid=nytcore-ios-share)

>  State Republicans have passed laws to curtail what is taught in college classrooms and installed new university administrators with partisan affiliations, among a host of new strategies to remake a public higher education system that they argue has been held hostage to left-leaning ideas and become hostile to conservative ones.

> The University of Texas is one of their main targets.a

> The campus is no longer led by an academic, but a Republican lawyer who worked for the state’s attorney general, Ken Paxton. The president has promised curricular changes, and the system is now conducting an audit of all gender studies courses, after a State House bill passed in May enshrined in state law that there are effectively only two genders. Another piece of legislation, Senate Bill 37, gutted faculty control of universities, tightened a grip on what can be taught and gave appointed governing boards the power to approve academic leaders, including academic deans.

> This fall, the firing of a Texas A&M instructor teaching a gender studies course after a student complained put the university at the center of a national debate over a crackdown on professors’ speech. The instructor’s department head and dean also lost their administrative posts, and eventually, the Texas A&M president resigned.

> Last month, the university system’s regents went even farther than Texas lawmakers, approving a policy that requires courses that teach  “race or gender ideology” to have the approval of the president. The Texas Tech University System has also sought to limit how race and gender are taught in its schools and created a new course approval process.

> Some faculty and students worry lawmakers are trying to turn the University of Texas — a selective school that attracts students from across the country — into a conservative campus.

> “I considered transferring out of U.T.,” said Ms. Gomez [a student], “because if my professors are unable to teach me, and I’m not able to have candid conversations to get a proper education, what am I here for?”

> A recent poll by the student newspaper, The Daily Texan, found that 40 percent of faculty respondents are changing their syllabus or teaching approach to comply with state legislation.


### Others

* Texas Tech Begins to Collect Info on Race, Gender Course Content

[https://insidehighered.com/news/faculty-issues/curriculum/2025/12/11/texas-tech-gathers-info-race-gender-course-content](https://insidehighered.com/news/faculty-issues/curriculum/2025/12/11/texas-tech-gathers-info-race-gender-course-content)

> As promised in a memo from the chancellor earlier this month, some Texas Tech University system faculty members were asked this week to report whether any course they teach “advocates for or promotes” specific race, gender or sexual identities. It is the latest step in a sweeping curricular review focused on limiting discussion of transgender identity, racism and sexuality across the five-campus public system.

> If a faculty member answers yes to any of those questions, they are then prompted to answer, “What is the course material required for? Check all that apply,” and select from the options “professional licensure/certification,” “accreditation,” “patient/client care” and “other.” Faculty must also provide a justification statement to support their response and are asked to “be as specific as possible.”

> “When I filled those forms out, I put ‘no’ for all of my classes, because I do not think talking about any of these issues is advocacy or promotion,” Pierce [Angelo State history department, chair] told Inside Higher Ed. “Also, in my history from the Civil War to present class, there is no way to not talk about Reconstruction, civil rights, the women’s movement. I mean, those are in every textbook … So I don’t feel like I even need to fill out a form saying that I’m going to talk about Reconstruction or civil rights or whatever, because I’m telling people what happened. I’m not advocating for a particular viewpoint.”

> “There’s a deep distrust of higher ed right now across the political spectrum, but particularly on the right,” said Pierce. “There’s this misconception that the professors want to go out and brainwash their students, and I can say, as a history professor, I don’t want my students coming out of my class thinking like I think. I want them to come out of my class thinking for themselves.”

* Youngkin Loses Battle Over Virginia Board Picks

[https://www.insidehighered.com/news/quick-takes/2025/12/11/youngkin-loses-battle-over-board-picks](https://www.insidehighered.com/news/quick-takes/2025/12/11/youngkin-loses-battle-over-board-picks)

> The legal battle over whether Virginia governor Glenn Youngkin’s university board appointees will take their seats is over after a judge set a trial for 2026, Virginia Business reported. Governor-elect Abigail Spanberger will assume office next month, rendering the lawsuit moot.

> The case will be dismissed, shutting down an effort to install the Republican governor’s board picks, many of whom had previously worked for or donated to the GOP and were rejected by Virginia Democrats. Now Spanberger, a Democrat, will be able to name 22 board members that otherwise would have been appointed by Youngkin, giving her the opportunity to shift the political balance of boards away from the right.


## Blowback

*  The Inevitable Rise of Right-Wing DEI---Conservative Christians want safe spaces, too.

[https://www.chronicle.com/article/the-inevitable-rise-of-right-wing-dei](https://www.chronicle.com/article/the-inevitable-rise-of-right-wing-dei)

> Religious orthodoxy, in other words, has come to be defended in the language of DEI. That’s why representatives of the American Association of University Professors, which found that Hamline had violated the punished instructor’s academic freedom, consider their investigation to have “stood against what is often referred to as left ‘cancel culture.’”

> What if the identity politics undergirding “left ‘cancel culture’” was always pretty much the same as the identity politics of offended Christians? What if both are equivalently incompatible with the mission of the university?

> As William F. Buckley perceived with dismay almost 80 years ago, the contemporary American university and the academic freedom it supports are intrinsically secular enterprises. That was true, too, of the university in the 19th-century German-speaking world, where the modern doctrines of academic freedom developed in part to protect professors from suffering fates like that of the philosopher Johann Gottlieb Fichte, who was fired from the University of Jena in 1798 on charges of atheism (inaccurate, as it happened).

> The secular ideal of academic freedom even applies to religiously affiliated colleges — not just informally but as a matter of constitutional law. As the University of Texas law professor David M. Rabban explains in Academic Freedom: From Professional Norm to First Amendment Right (2024), Supreme Court decisions in the 1970s established that insofar as such colleges had adopted the AAUP’s 1940 Statement of Principles of Academic Freedom and Tenure, they were, in the words of one decision, “characterized by an atmosphere of academic freedom rather than religious indoctrination” — and could therefore receive government support without violating the Establishment Clause of the First Amendment.

> The opposition between “academic freedom” and “religious indoctrination” goes back to the early period of the modern American university, a fact which the religiously dogmatic Buckley recognized clearly. That’s why the subtitle to his God and Man at Yale was “The Superstitions of ‘Academic Freedom.’” What Buckley hated was an essential presupposition of the modern academy: that whether the question at issue is the age of the universe, the evolution of humankind, or the construction of gender roles, Biblical warrants have no particular authority. That doesn’t mean, of course, that the study of religious ideas has no place, including from a religious point of view, as in theology. But it does mean that objections like that of the Christian student who got Texas A&M professor Melissa McCoul fired — McCoul’s ideas “go against a lot of people’s religious beliefs” — should carry no weight.

* The New School faces identity crisis amid planned layoffs, reorganization

[https://gothamist.com/news/the-new-school-faces-identity-crisis-amid-planned-layoffs-reorganization](https://gothamist.com/news/the-new-school-faces-identity-crisis-amid-planned-layoffs-reorganization)

(Thanks MC)

> University President Joel Towers plans deep cuts to faculty, staff and programs to close the budget gap. The American Association of University Professors said 40% of full-time faculty members — or 169 academics — have received voluntary separation or early retirement offers, making it the “largest attempted firing of faculty currently taking place in the nation.”

> The problems facing The New School align with those facing much of higher education, including declining enrollment, unrest tied to Israel’s war in Gaza, scrutiny from the federal government and mounting doubts about the value of a college degree.

> But academics there say the stakes are particularly high for the institution, which was founded by dissident intellectuals. In interviews, professors worried that university leaders are using the financial crisis as an excuse for an ideological overhaul that prioritizes professional training programs over the humanities. They said departments and divisions long known as hotbeds of leftist dissent could be gutted.

> “They are trying to radically diminish the power and capacity of the liberal arts divisions, both graduate and undergraduate,” said Rachel Sherman, sociology professor at The New School's Eugene Lang College of Liberal Arts. “It does seem to be designed to minimize the power of the divisions that have historically been more politically motivated.”



## AI misdeeds

* To AI-proof exams, professors turn to the oldest technique of all

[https://www.washingtonpost.com/education/2025/12/12/ai-artificial-intelligence-college-oral-exam/](https://www.washingtonpost.com/education/2025/12/12/ai-artificial-intelligence-college-oral-exam/)

> Across the country, a small but growing number of educators are experimenting with oral exams to circumvent the temptations presented by powerful artificial intelligence platforms such as ChatGPT.

> Such tools can be used to cheat on take-home exams or essays and to complete all manner of assignments, part of a broader phenomenon known as “cognitive off-loading.”

> Hartmann [a professor of religious studies] tells her students that using AI is like bringing a forklift to the gym when your goal is to build muscle. “The classroom is a gymnasium, and I am your personal trainer,” she explains. “I want you to lift the weights.”

> Chin had prohibited the use of AI in the class. But he also knew how good it was at completing the type of coding work he was assigning. Oral exams were a way to test whether students were really learning the course material. During the exam, Chin shows students examples of code written in R, the programming language they’ve been learning all semester, and asks them what it does.

* The LMS Is Dead; Long Live Online Teaching

[https://www.insidehighered.com/opinion/career-advice/teaching/2025/12/12/lms-dead-long-live-online-teaching-opinion](https://www.insidehighered.com/opinion/career-advice/teaching/2025/12/12/lms-dead-long-live-online-teaching-opinion)


> Let me illustrate this point. As in years past, a student logs in to take a quiz. It’s the standard format: multiple-choice questions based on posted readings and online lectures, hosted in Brightspace or some other LMS. The quiz has been polished and labeled and is due by 11:59 p.m., the student’s score to be recorded in the gradebook.

> However, the fall 2025 student, operating in a world filled with autonomous AI tools like Comet and Claude, isn’t really alone. An AI agent has access to the course materials. It knows the textbook. It’s “heard” the lectures. The agent cruises through the questions and receives a 94. But why not 100? Hallucinations have nothing to do with the missing points. The agent missed Question 17, the one that asks, “What image is visible in the top right corner of Slide 9 from Lecture 3?” Question 17 is just a visual trivia question (no alt-text attached), embedded in the middle of a graded assessment.

> The instructor has started slipping in questions like this to catch AI use. Not to teach or to check comprehension, but to beat the bot. The fact that this approach violates Americans With Disabilities Act guidelines didn’t matter. The instructor’s real audience wasn’t the student. It was the machine. We’ve reached the point where visual inaccessibility is a quiz strategy. That’s how desperate the agentic AI–versus–LMS era has become.


> And when it comes to quizzes, even ones demanding written responses, AI can often outperform a rushed, underprepared human. It isn’t thinking, but it’s simulating the appearance of having thought. That’s often enough to get a B, even with an AI-aware instructor burying trip wires.

> Of course, most online instructors already knew that online quizzes were never secure. No one expected them to be. These were open-book, low-stakes assignments designed to reinforce reading and lecture material. They were essentially homework. The idea was that students would work through key concepts and reflect on a few takeaways, not prove mastery.

> Two of the LMS’s most-hyped functions now feel especially outdated: online tests and discussion boards. Once promoted as tools for assessment and engagement, they now feel hopelessly pre-2022. Online tests can be aced by any halfway-trained AI assistant. And discussion boards? They’re filled with perfunctory replies, now often AI-generated, to classmates’ posts. Instructors require a post and two replies. Students comply, and no one reads any of it.


> What will online teaching look like five or 10 years from now? Despite the shiny new AI-enhanced tools Canvas, Brightspace and Blackboard rolled out in 2025, I don’t think any of us really know. It may be that what survives is a harder-to-automate version of online teaching, not a return to the days of Lotus Notes, but a new approach built around real instructor presence, with daily or biweekly check-ins. The simplest approach to creating this presence is one I’ve been using this semester, where I frame my courses like stories, their narratives unfolding over the course of the term. I begin with brief Monday videos, sent via email, announcing, “Here’s what we’re doing this week and why it matters.” I usually end the week with a recap. Redesigning my online assignments to include social annotation and virtual presentations has required more attention. But throughout all of these course redesigns, my LMS has not been central.

> So here we are. The LMS survives, but only as basic infrastructure, as a FERPA-approved system of recordkeeping. But the course, in a sense, lives elsewhere. In Google Docs. In impassioned email exchanges and social annotations. Even in iterative AI “conversations.” But perhaps most powerfully in novel exchanges between instructor and student, such as a hastily recorded video comment (yes, I record those, too) that arrives unexpectedly in a student’s inbox because a draft sparked something real.




## And just because it is fun

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
