# Feb 6

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.


## Academic freedom

* NYTimes: Professors Are Being Watched: ‘We’ve Never Seen This Much Surveillance’

[https://www.nytimes.com/2026/02/04/us/professors-classroom-surveillance-politics.html?smid=nytcore-ios-share](https://www.nytimes.com/2026/02/04/us/professors-classroom-surveillance-politics.html?smid=nytcore-ios-share)

> College professors once taught free from political interference, with mostly their students and colleagues privy to their lectures and book assignments. Now, they are being watched by state officials, senior administrators and students themselves.

> The increased oversight of professors comes as conservatives expand their movement to curb what they say is a liberal tilt in university classrooms. In the last couple of years, they have found sympathetic ears in state legislatures with the power to pressure schools, and their efforts have gained momentum as the Trump administration has made overhauling the politics and culture on campuses a focus.

> “We’ve never seen this much surveillance,” said John White, a University of North Florida education professor who was asked to remove words such as “diversity,” “equity,” “inclusion” and “culture” from his syllabus. He said he changed his syllabus under threat of his course being canceled.

> The scrutiny has been especially intense in departments like gender studies and Middle Eastern studies that touch on contested issues. Some professors say the new rules have turned teaching into a minefield in those disciplines, inviting online trolls looking for keywords and directing online mobs toward professors.

> Jonathan Friedman with PEN America, a free-expression group, said in an interview that posting syllabuses so the public has a better grasp of what occurs in college classrooms may sound innocuous. But “publishing syllabi when it is coupled with this McCarthyist environment is really dangerous,” he said.

> Professors are adapting to the new reality, in some cases looking for ways to provide only the bare minimum of information required or otherwise avoid scrutiny. One professor at a school where faculty must post their course plans said he now effectively has two syllabuses: one he will submit for public posting and another for students. He asked not to be identified for fear of retribution against his institution.

> Isaac Kamola, a Trinity College professor who has studied right-wing websites, said the current surveillance follows efforts by Campus Reform and Charlie Kirk’s Turning Point USA, which began singling out professors for their perceived liberal biases over a decade ago. Turning Point included a “watch list” of professors, leading to a torrent of critical and abusive emails to those who found themselves on it.

> Now that governments and universities are involved, he said, “Everybody is walking on eggshells,” Dr. Kamola said. “Faculty are walking on eggshells. Administrators are walking on eggshells. Students are walking on eggshells. And what you get is the opposite of free speech.”

* Houston University Asks Faculty to Pledge Not to “Indoctrinate” Students

[https://www.insidehighered.com/news/quick-takes/2026/02/06/houston-faculty-must-pledge-not-indoctrinate-students](https://www.insidehighered.com/news/quick-takes/2026/02/06/houston-faculty-must-pledge-not-indoctrinate-students)

> Faculty members in the University of Houston’s College of Liberal Arts and Social Science were asked to sign a three-page memo pledging not to “indoctrinate” their students, the Houston Chronicle reported.

> In a November email to faculty, Houston president Renu Khator wrote that the university’s responsibility is to “give [students] the ability to form their own opinions, not to force a particular one on them. Our guiding principle is to teach them, not to indoctrinate them.” The recent memo, sent by college dean Daniel O’Connor, asks faculty to “document compliance” with Khator’s note. It’s a way to ensure all faculty members are compliant with Texas’s Senate Bill 37, O’Conner told associate English professor María González in a meeting. The law mandates regular reviews of core undergraduate curriculum but does not address indoctrination or what material can or cannot be taught.

> By Feb. 10, faculty must signal their agreement with the following five statements: “A primary purpose of higher education is to enhance critical thinking;” “Our responsibility is to give students the ability to form their own opinions, not to indoctrinate them;” “I understand the definition and attributes of critical thinking;” “I design my courses and course materials to be consistent with the definition and attributes of critical thinking;” and “I use methods of instruction that are intended to enhance students’ critical thinking.”

## Freedom of expression

* In Bay Area, Felony Charges Against Student Protesters Prompt Free Speech Concerns | Bolts

[https://boltsmag.org/stanford-san-francisco-felony-conspiracy-palestine-protesters/ https://boltsmag.org/stanford-san-francisco-felony-conspiracy-palestine-protesters/?_thumbnail_id=8835](https://boltsmag.org/stanford-san-francisco-felony-conspiracy-palestine-protesters/ https://boltsmag.org/stanford-san-francisco-felony-conspiracy-palestine-protesters/?_thumbnail_id=8835)

> In June 2024, after the university refused to hold talks with students about divestment, Gonzalez and a group of fellow students and alumni occupied the president’s office in protest before being arrested and removed by police. Nearly a year later, the district attorney of Santa Clara County, Democrat Jeff Rosen, announced he would file felony vandalism and conspiracy charges against Gonzalez and 11 others, making him the only prosecutor in the country to try a felony case against pro-Palestine student protesters since the campus movement began. “Dissent is American,” Rosen said in a statement announcing the charges. “Speech is protected by the First Amendment. Vandalism is prosecuted under the Penal Code.”

> The trial, which began on Jan. 9, has now entered jury deliberations and a verdict is expected in the coming days. Gonzalez and four fellow defendants who opted to put the case before a jury could receive up to three years in prison and a permanent felony record. The DA is also seeking $329,000 in restitution to Stanford, whose endowment tops $40 billion, following the university’s accusations of extensive property damage. (The defense disputes these claims.) “It would ruin my family financially for the rest of our lives,” Gonzalez told me.

> As Gonzalez’s case plays out, a parallel situation has been unfolding just across the Bay. San Francisco DA Brooke Jenkins, also a Democrat in a liberal county, has pursued felony conspiracy charges against eight pro-Palestine protesters who took over the Golden Gate Bridge during a demonstration in April 2024. The next hearing is Feb. 17. The judge initially declined to downgrade the charges because the bridge administrators were demanding over $160,000 in restitution, but after this demand was dropped in November, the judge has signalled his readiness to reduce the felony charges to misdemeanors.

### Anti-woke/anti-DEI is simply racism

* UVa to Trump: No Illegal DEI Here

[https://www.chronicle.com/article/uva-to-trump-no-illegal-dei-here](https://www.chronicle.com/article/uva-to-trump-no-illegal-dei-here)

> The University of Virginia shuttered its diversity offices, removed language from websites and programs that might suggest racial preferences in hiring or admissions, and stopped participating in some race-specific programs and events in order to assure the Trump administration that it is complying with its interpretation of civil-rights laws.

> Those steps were spelled out in the first quarterly compliance report UVa was required to submit as part of a controversial agreement reached in October with the U.S. Department of Justice.

> Critics of the agreement complained that the public university was jeopardizing its independence by complying with an interpretation of civil-rights law that stretches beyond what the Supreme Court mandated in its 2023 decision ending race-conscious admissions. The Department of Justice’s July guidance on “unlawful discrimination” contends that the high court’s ruling bans a broad range of DEI practices and certain affinity groups and identity-based facilities that many experts consider legal.

> In its own guidance being distributed across campus as part of the agreement, UVa warned that “the word ‘equity,’ and phrases like ‘racial equity,’ have acquired a connotation of expectations about proportionate outcomes.” Messages should be crafted to avoid misunderstanding, it said. Proxies that are intended to achieve the same result are also banned, it warned. “We should avoid language suggesting that programs are targeted at ‘underrepresented’ or ‘disadvantaged’ groups, if the surrounding context would permit the misunderstanding that such words are code for consideration of protected characteristics.”

> “Despite assertions in the report, nothing about this compliance review was truly voluntary,” Walt F. Heinecke, an associate professor in the School of Education and past president of the American Association of University Professors chapter at UVa, wrote in an email to The Chronicle on Friday. It “exemplifies the ongoing surveillance of the university in a process of whitewashing a previously well-functioning, superb, nationally recognized university. The report ignores the climate of fear that the compliance review creates and its real deleterious effects on academic freedom and shared governance.”

*  Diversity Hiring Faces a Reckoning Colleges looked past legal risks. Now they’re paying a price.

[https://www.chronicle.com/article/diversity-hiring-faces-a-reckoning](https://www.chronicle.com/article/diversity-hiring-faces-a-reckoning)

> Kristina M. Johnson’s project was personal. Announcing a goal of hiring 100 underrepresented and nonwhite scholars, Johnson, then president of Ohio State University, drew on her background.

> At the time of Johnson’s address, in February 2021, higher education was awash with similar sentiments. An understanding had taken hold: Despite years of effort, the professoriate was still too white and, in some fields, too male and therefore out of sync with what a demographically diverse student body needed from its instructors.

> Revelations like those at Ohio State have now taken on political significance. The Trump administration is scrutinizing campuses it believes discriminated against white and male applicants. The Department of Justice has accused George Mason University’s president of advocating for race- and sex-based hiring processes (he’s denied wrongdoing). Harvard University fell under the federal microscope after it reported a substantial decline in its proportion of white male tenure-track faculty members over the past decade.

> An Ohio State spokesperson told me that the public records featured in this article were “cherry-picked” from a small number of searches that occurred “years ago.” (Those records were shared by John D. Sailer, director of higher-education policy at the right-wing Manhattan Institute, who first obtained them in 2023 via a public-records request.)


## Federal Agencies

### DOE/OCR

* Trump administration investigating reports Tufts shared student voting data

[https://www.washingtonpost.com/education/2026/02/05/tufts-university-election-investigation/](https://www.washingtonpost.com/education/2026/02/05/tufts-university-election-investigation/)

> The agency said it plans to examine whether Tufts and the National Student Clearinghouse violated the Family Educational Rights and Privacy Act in the way they handled data for a national study of student political engagement.

> John Davisson, deputy director for a national privacy group, the Electronic Privacy Information Center, said the federal educational privacy law is a “critical safeguard.” But he was skeptical about this particular investigation given the administration’s previous efforts to obtain voter data and nudge states to purge their voting rolls.

> “The idea that this investigation is motivated by a genuine concern for privacy and the integrity of elections is far-fetched,” Davisson said.

* Education Dept. Tells Universities Not to Use Student Voting Data

[https://www.insidehighered.com/news/government/politics-elections/2026/02/05/ed-tells-universities-not-use-student-voting-data](https://www.insidehighered.com/news/government/politics-elections/2026/02/05/ed-tells-universities-not-use-student-voting-data)

(Hmm, wonder if college students tend to vote one way...)

> The move—and the department’s new investigations into the National Study of Learning, Voting and Engagement—could impact college student participation in this year’s midterm elections. In a statement, Education Secretary Linda McMahon said that “American colleges and universities should be focused on teaching, learning, and research—not influencing elections.”


## Institutional assaults


### Harvard

* NYTimes: Trump, Changing Course, Throws Harvard Deal Talks Into Chaos

[https://www.nytimes.com/2026/02/03/us/politics/trump-changing-course-throws-harvard-deal-talks-into-chaos.html?smid=nytcore-ios-share](https://www.nytimes.com/2026/02/03/us/politics/trump-changing-course-throws-harvard-deal-talks-into-chaos.html?smid=nytcore-ios-share)

> In the latest example of his mercurial negotiating style, President Trump went from dropping his ask for a $200 million fine to demanding $1 billion from the university.

> Just last week, Mr. Trump privately told negotiators he was willing to drop his demand for a $200 million payment from Harvard  ... Instead of dropping the fine, Mr. Trump said he would demand $1 billion “in damages.” He threatened the school with a criminal investigation.

> Ryan Enos, a government professor at Harvard, said Mr. Trump’s shifting demands seemed to show he was motivated by revenge instead of policy goals. “He’s just looking for a way to win a battle and assert political retribution on an institution that he thinks is defying him,” Mr. Enos said. “This is indicative of a larger story in the country, which is that Trump is flailing politically and looking for ways to assert pressure.”

(Also)

[https://www.insidehighered.com/news/government/politics-elections/2026/02/03/trump-demands-harvard-pay-1-billion](https://www.insidehighered.com/news/government/politics-elections/2026/02/03/trump-demands-harvard-pay-1-billion)

[https://www.chronicle.com/blogs/the-trump-agenda/trump-walked-back-a-demand-for-a-harvard-payment-then-he-doubled-down](https://www.chronicle.com/blogs/the-trump-agenda/trump-walked-back-a-demand-for-a-harvard-payment-then-he-doubled-down)


### Iowa

* A ‘Barrage of Bills’ Would Overhaul Higher Ed in Iowa—If They Actually Pass

[https://www.insidehighered.com/news/governance/state-oversight/2026/02/04/barrage-bills-would-upend-iowa-higher-ed-if-they-pass](https://www.insidehighered.com/news/governance/state-oversight/2026/02/04/barrage-bills-would-upend-iowa-higher-ed-if-they-pass)

> Iowa’s legislative session began roughly three weeks ago, and the state’s House Higher Education Committee and its subcommittees have already advanced sweeping legislation that could threaten universities’ budgets, change who has a vote on the board overseeing public universities, increase direct legislative oversight of these universities, and more.

> The Republican leading these pushes has called gender studies degrees “garbage” and made other criticism of what universities teach. Some faculty have raised concerns that the Legislature is encroaching on the Board of Regents’ authority to oversee institutions, and on faculty’s role in shared governance. If all this legislation passes into law, Iowa would join the ranks of states such as Texas, Florida and Utah in enacting far-reaching conservative overhauls of higher ed in recent years.

> Republicans on the committee have already passed out of committee bills that would:

> * ban tuition increases for resident undergraduate students at the state’s three public universities until July 2031;

> * make the universities liable for 10 percent of students’ defaulted loans;

> * tax public and private institution endowments that exceed $500 million (affecting at least the University of Iowa, Iowa State University and Grinnell College) and directing the revenue to tuition for “high-wage” and “high-demand” jobs;

### Oklahoma

* Tenure Eliminated at Oklahoma Colleges

[https://insidehighered.com/news/faculty-issues/tenure/2026/02/05/tenure-eliminated-oklahoma-colleges](https://insidehighered.com/news/faculty-issues/tenure/2026/02/05/tenure-eliminated-oklahoma-colleges)

> Faculty members at regional public and community colleges in Oklahoma can no longer be granted tenure.

> Oklahoma governor Kevin Stitt decreed the end of tenure in an executive order, effective Thursday. The state has a “constitutional and statutory responsibility to steward taxpayer dollars wisely and ensure public institutions of higher education operate with accountability, transparency, and measurable outcomes,” the order states.

> Public regional universities, which educate more than 54,000 students in the state combined, “shall not grant new lifetime tenure appointments,” the order states. Instead, they may hire faculty under fixed-term, renewable contracts, and the renewals are dependent on professors’ performance, student outcomes, “alignment with workforce and Oklahoma economic needs” and “institutional service.” Faculty members at these institutions who already have tenure may retain it. According to the National Center for Education Statistics, 761 faculty members at Oklahoma regional colleges had tenure in 2024, and 412 faculty members were on the tenure track.

(Also)

[https://www.chronicle.com/article/tenure-will-be-eliminated-at-most-of-oklahomas-public-colleges-governor-says](https://www.chronicle.com/article/tenure-will-be-eliminated-at-most-of-oklahomas-public-colleges-governor-says)


### Texas A&M

* Texas A&M Closes Women’s and Gender Studies Programs

[https://www.insidehighered.com/news/business/academic-programs/2026/01/30/texas-am-closes-womens-and-gender-studies](https://www.insidehighered.com/news/business/academic-programs/2026/01/30/texas-am-closes-womens-and-gender-studies)

> The university has also canceled six classes and asked faculty to remove some course context. One free speech expert said Texas A&M is “staking out turf as the epicenter of higher education censorship nationwide.”

> “[As] part of the broader implementation of the recently updated System policy, we made the difficult decision to begin winding down Women’s and Gender Studies academic programs, including the BA, BS, Graduate Certificate and the Minor,” Alan Sams, Texas A&M’s provost and executive vice president, wrote in a letter to faculty and staff Friday, according to a copy published by KBTX, a local TV news station in College Station, Tex. “This decision is based on the requirements of System policy and limited student interest in the program based on enrollment over the past several years.”

> But free expression advocates and Texas A&M faculty decried the move, which they said was the result of an opaque process and represents another threat to academic freedom.

> “Women’s and Gender Studies at Texas A&M has served generations of Aggies and advanced the core values of the institution throughout its history,” the university’s chapter of the American Association of University Professors wrote in a public statement. “The AAUP remains steadfast in its opposition to Interim President Williams’s draconian decision, which represents a threat to the entire university community by devaluing student degrees, undermining faculty governance, and diminishing its institutional reputation.”

(Also)

[https://www.chronicle.com/article/tracking-higher-eds-dismantling-of-dei](https://www.chronicle.com/article/tracking-higher-eds-dismantling-of-dei)


### Illinois

* ‘Fell the enemies:’ Illini Republicans support ICE amid killings - The Daily Illini

[https://dailyillini.com/news-stories/university-news/student-organizations/2026/02/01/illini-republicans-ice-minnesota/](https://dailyillini.com/news-stories/university-news/student-organizations/2026/02/01/illini-republicans-ice-minnesota/)

> In a post that included a stylized graphic matching a clip of a federal agent shooting and killing Alex Pretti, Illini Republicans stated that they “stand with ICE” amid the killings of Renee Nicole Good and Pretti in Minnesota.

> In a written statement to The DI Monday, Patrick Wade, the University’s Director of Executive Communications and Issues Management, stated that the matter has been reported to the Title VI Office, “which is reviewing reports received about the incident and processing them in accordance with normal protocols.”

> Wade added that hate and intolerance are not aligned with University values.

> He also stated that Registered Student Organizations are autonomous and independent from the University, and the groups are responsible for managing their own affairs.

> “Their social media accounts,” according to Wade, “represent their own views, not those of the university.”




----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
