# Feb 13

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

## Freedom of expression

* After Kirk Comments, UCLA Fires DEI Director

[https://www.insidehighered.com/news/quick-takes/2026/02/09/after-kirk-comments-ucla-fires-dei-director](https://www.insidehighered.com/news/quick-takes/2026/02/09/after-kirk-comments-ucla-fires-dei-director)

> The University of California, Los Angeles, is the latest university to fire an employee for making negative comments about Charlie Kirk after his killing last fall, the Los Angeles Times reported.

> “Given the nature of your role as a Director of Race and Equity, the university has determined that this conduct significantly undermined trust in your leadership and adversely affected the office’s effectiveness and credibility,” read the termination letter, which the L.A. Times obtained a copy of. It cited violations of policies on “workplace violence prevention” for posts that “referenced or appeared to endorse violence or death” and made “demeaning or generalized remarks about demographic groups.”

* N.C. State Fires LGBTQ Pride Employee in Undercover Video

[https://www.insidehighered.com/news/quick-takes/2026/02/09/nc-state-fires-secretly-recorded-lgbtq-pride-employee](https://www.insidehighered.com/news/quick-takes/2026/02/09/nc-state-fires-secretly-recorded-lgbtq-pride-employee)

> North Carolina State University fired the assistant director of its LGBTQ Pride Center on Friday after an anti-DEI activist group secretly recorded him appearing to violate system policies, according to The Raleigh News & Observer.

> This is the fourth UNC system institution to fire an employee after the group, Accuracy in Media, posted videos of them allegedly subverting the system’s mandate to maintain “institutional neutrality” on issues related to social policies or political controversies.


* 12 Arrested at Anti-ICE Protest Outside Columbia

[https://www.insidehighered.com/news/quick-takes/2026/02/09/12-arrested-anti-ice-protest-outside-columbia](https://www.insidehighered.com/news/quick-takes/2026/02/09/12-arrested-anti-ice-protest-outside-columbia)

> A dozen Columbia University students and faculty were arrested Thursday during a protest against U.S. Immigration and Customs Enforcement’s crackdown on immigration, The New York Times reported.

> Other publications, including the student newspaper, The Columbia Spectator, reported only that faculty and students were among the 12 people arrested.

> The protest, organized in part by a group of Columbia faculty and staff called CU Stands Up and the Columbia chapter of the climate activism organization the Sunrise Movement, drew about 150 people, many wearing shirts that read “Sanctuary Campus Now” and “ICE Off Campus.” The 12 were reportedly arrested after they blocked traffic on Broadway, just outside campus, and refused to heed police warnings to move.

("refused to heed police warnings to move" is a rationale for arrest or termination...)

* CUNY Trains Community in Constructive Dialogue

[https://www.insidehighered.com/news/student-success/college-experience/2026/02/13/cuny-trains-community-constructive-dialogue](https://www.insidehighered.com/news/student-success/college-experience/2026/02/13/cuny-trains-community-constructive-dialogue)

Rachel Stephenson, CUNY’s chief transformation officer, who oversees the Constructive Dialogue Initiative, said disagreement and difference are a natural part of campus life, making it important for the university system to proactively enhance communication skills across its community.

* CAIR Report on Islamophobia and Free Speech Rates Columbia U., CUNY as Most Hostile Campuses

[https://www.cair.com/press_releases/cair-report-on-islamophobia-and-free-speech-rates-columbia-u-cuny-as-most-hostile-campuses/](https://www.cair.com/press_releases/cair-report-on-islamophobia-and-free-speech-rates-columbia-u-cuny-as-most-hostile-campuses/)

> Columbia University and CUNY received the lowest scores at 2%, with the University of Michigan, the University of Chicago, and Case Western Reserve University also ranking among the most hostile campuses.

> No campus of the 51 investigated and reported to CAIR by students and faculty earned an “Unhostile” rating. Six campuses were placed “Under Watch,” led by the University of Alabama at 87%. The average score was 37.92%, and nearly 75% of campuses scored below 50%. More than half failed to explicitly identify Islamophobia or anti-Muslim bias in their discrimination policies.

* Is Union Power Growing in Mamdani’s New York? | The Nation

[https://www.thenation.com/article/society/cuny-fired-four-union-power-zohran-mamdani/](https://www.thenation.com/article/society/cuny-fired-four-union-power-zohran-mamdani/)

(Paywall...)

> Following the Mamdani administration’s talks with the CUNY faculty union, three professors have returned to class after losing their jobs for their pro-Palestine activism.

> The decision comes after Mayor Zohran Mamdani’s administration held talks with the Professional Staff Congress, the union that represents over 30,000 CUNY faculty members, according to people familiar with the matter who spoke on the condition of anonymity as they were not authorized to speak on it publicly.

> James Davis, president of the PSC, lauded the news as a “major victory” but cautioned that it is “not complete” in a press release on January 26. “It is important both in terms of restoring these harmed colleagues to their jobs and repudiating the administration’s callous disregard for the academic judgment of faculty, for First Amendment protected speech, and for academic freedom.”

* FAMU Says Censoring the Word ‘Black’ Was a Mistake

[https://www.insidehighered.com/news/quick-takes/2026/02/10/famu-says-censoring-word-black-was-mistake](https://www.insidehighered.com/news/quick-takes/2026/02/10/famu-says-censoring-word-black-was-mistake)

> Florida Agricultural and Mechanical University, a historically Black institution, said it mistakenly objected to its Black Law Students Association using the word “Black” in Black History Month fliers.

> Law student Aaliyah Steward told Orlando’s News 6 she heard “we couldn’t use the word ‘Black’ in Black History Month; we needed to abbreviate it.” The news broadcast then showed a flier that conformed to this, abbreviating it as “BHM.”

(Huh?)

### ICE

* Campus Reform | Hunter College president says ICE barred from campus without legal order

[https://www.campusreform.org/article/hunter-college-president-says-ice-barred-campus-without-legal-order/29396](https://www.campusreform.org/article/hunter-college-president-says-ice-barred-campus-without-legal-order/29396)

(I clicked through so you won't have to..... Nothing to see here)


## Funding cuts



* Congress, Courts Stymie Trump’s Effort to Cap Research Costs

[https://insidehighered.com/news/government/science-research-policy/2026/02/09/congress-courts-stymie-trumps-effort-cap](https://insidehighered.com/news/government/science-research-policy/2026/02/09/congress-courts-stymie-trumps-effort-cap)

> The National Institutes of Health and other federal agencies can’t make any changes to how universities are reimbursed for costs indirectly related to research until at least Sept. 30, under the recently passed budget bills that President Trump signed into law.

> But lawsuits quickly led to court orders that blocked the NIH from capping the rates. And then the National Science Foundation as well as the Energy and Defense Departments also sought to put a 15 percent cap in place—policies that federal judges also blocked. The Trump administration has appealed the decisions, so litigation continues.

> Now, Congress has weighed in as well, blocking any changes to the reimbursement rates for fiscal year 2026, which ends Sept. 30. That legislation led the Energy Department to formally announce that its policy changes related to indirect research costs were no longer in effect. Likewise, a Pentagon official told Inside Higher Ed that “the department is not presently working toward changes to indirect cost rates.” The NIH and NSF didn’t respond to a request for comment.

* How Congress’s Budget Could Hamper Trump ED Agenda

[https://www.insidehighered.com/news/government/politics-elections/2026/02/12/how-congresss-budget-could-hamper-trump-ed-agenda](https://www.insidehighered.com/news/government/politics-elections/2026/02/12/how-congresss-budget-could-hamper-trump-ed-agenda)



### NSF

* NSF Returning Fellowship Applications With Little Explanation

[https://www.insidehighered.com/news/quick-takes/2026/02/13/nsf-returns-fellowship-applications-minimal-reasoning](https://www.insidehighered.com/news/quick-takes/2026/02/13/nsf-returns-fellowship-applications-minimal-reasoning)

> The National Science Foundation has started returning applications for its Graduate Research Fellowship Program to the students who submitted them without review, STAT News and Eos reported.

> Each year about 12,000 graduate and undergraduate students apply to the respected research pipeline program. But it remains unclear how many applications have been returned before they could be reviewed for scientific merit. NSF told at least one applicant that their proposal included research that made them ineligible for the program, with no further explanation, STAT reported. But students and lab leaders say the research should’ve been eligible.

> Grant Witness, an organization established to document disruptions in federal funding, has compiled at least 45 examples of returned applications. And STAT noted that the hundreds of replies to social media posts about the befuddling occurrence suggest that the number of students affected is likely far higher.


## Federal Agencies

### DOE/OCR

* The Trump Administration’s Unconstitutional Crusade Against Civil Rights

[https://www.insidehighered.com/opinion/views/2026/02/09/unconstitutional-crusade-against-civil-rights-opinion](https://www.insidehighered.com/opinion/views/2026/02/09/unconstitutional-crusade-against-civil-rights-opinion)

> s members of the U.S. Department of Education Office for Civil Rights Alumni Collective, a group of former ED-OCR career civil servants, lawyers and managers who served under both Democratic and Republican administrations, we share a common dedication to protecting and advancing the civil and human rights of all persons in the United States, particularly its students. Together, we have hundreds of years of federal administrative experience, as well as expertise in legal and civil rights enforcement.


## Institutional assaults


### UNC

* UNC Administrators Can Now Secretly Record Faculty

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2026/02/11/unc-admin-can-now-officially-secretly-record](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2026/02/11/unc-admin-can-now-officially-secretly-record)

> The new policy prohibits students from recording class without permission but explicitly allows administrators to surveil professors for any “lawful purpose.”

> he University of North Carolina at Chapel Hill recently rolled out a new policy that permits university officials to record classes without notifying the instructor. It’s a practice administrators have used in the past to investigate professors but have now formalized in writing.

> According to the policy, administrators may, with the provost and general counsel’s written permission, record classes or access existing recordings without telling faculty in order to “gather evidence in connection with an investigation into alleged violations of university policy” and “for any other lawful purpose, when authorized in writing by the provost and the office of university counsel, who will consult with the chair of the faculty.”

> Mehdi Shadmehr, an associate professor of public policy at UNC, told Inside Higher Ed the policy is “completely outside any kind of norm.”

### Others

* Virginia Tech Bans University-Funded Identity-Based Graduations

[https://www.insidehighered.com/news/quick-takes/2026/02/12/virginia-tech-bans-university-funded-affinity-graduations](https://www.insidehighered.com/news/quick-takes/2026/02/12/virginia-tech-bans-university-funded-affinity-graduations)

> “The decision aligns with guidance from the U.S. Department of Education’s Office for Civil Rights, which states that federal civil rights law prohibits using race in decisions related to graduation ceremonies and cautions that such practices may be perceived as segregation,” the university said in its announcement. But it’s unclear what guidance it was referencing.



## AI misdeeds

* Remote LSAT Ending Due to Cheating Concerns

[https://www.insidehighered.com/news/quick-takes/2026/02/12/remote-lsat-ending-due-cheating-concerns](https://www.insidehighered.com/news/quick-takes/2026/02/12/remote-lsat-ending-due-cheating-concerns)

> Beginning in August, the LSAT—the required entrance exam for law school admissions—will only be administered in person to protect the “security and integrity” of the test, the Law School Admission Council announced Wednesday.

* Adelphi Student Wins AI Plagiarism Lawsuit

[https://www.insidehighered.com/news/quick-takes/2026/02/11/adelphi-student-wins-ai-plagiarism-lawsuit](https://www.insidehighered.com/news/quick-takes/2026/02/11/adelphi-student-wins-ai-plagiarism-lawsuit)

> An Adelphi University student who was accused of using artificial intelligence on an assignment has won a lawsuit against the institution, Newsday reported, with a federal judge ruling that the finding that he had plagiarized was without merit. The institution will be required to remove the plagiarism charge from his record; Adelphi students can face suspension or expulsion after committing two plagiarism offenses.

> The plagiarism accusation arose from a paper on Christianity and Islam that Newby had written in a World Civilizations 1 class his first semester of college. Turnitin’s AI detector marked the essay as fully AI-written, but Newby ran it through two other detectors that said it was written by a human, court records show.



* NYTimes: A.I. Companies Are Eating Higher Education

[https://www.nytimes.com/2026/02/12/opinion/ai-companies-college-students.html?smid=nytcore-ios-share](https://www.nytimes.com/2026/02/12/opinion/ai-companies-college-students.html?smid=nytcore-ios-share)

(A Dean at Columbia says what must be said)

> Hoping to win recognition as leaders in A.I. or fearful of being left behind, more and more colleges and universities are eagerly partnering with A.I. companies, despite decades of evidence demonstrating the need to test education technology, which often fails to deliver measurable improvements in student learning. A.I. companies are increasingly exerting outsize influence over higher education and using these settings as training grounds to further their goal of creating artificial general intelligence (A.I. systems that can substitute for humans).

> In diplomacy, you know you are dealing with an adversary when it sows division in your ranks. Anthropic, for instance, is demanding exorbitant fees for enterprise accounts and paying “campus ambassadors” to promote the use of its Claude A.I. tools in schools. Other companies promise cash bonuses when students meet marketing goals. That creates conflicts of interest, especially when these paid ambassadors hold elected positions in student government.

> A Columbia undergrad, Roy Lee, bragged about developing an A.I. tool to cheat his way through online tech job interviews. The venture capital firm Andreessen Horowitz expressed admiration for his “bold approach,” explaining that “behind the scenes his moves are rooted in deliberate strategy and intentionality.” The firm helped raise $15 million to help start the company Mr. Lee co-founded, which said it wants to help users “cheat on everything.”

## And just because it is fun

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
