# Feb 20

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

## Freedom of expression

* NYC public law school to host event on Hamas tunnels as ‘resistance to colonization’

[https://www.timesofisrael.com/nyc-public-law-school-to-host-event-on-hamas-tunnels-as-resistance-to-colonization/amp/](https://www.timesofisrael.com/nyc-public-law-school-to-host-event-on-hamas-tunnels-as-resistance-to-colonization/amp/)

> Israel’s consul general in New York, Ofir Akunis, sent a letter to CUNY’s leadership on Wednesday demanding the event’s cancellation.

> “Student-organized events do not reflect the views of the law school or the university,” a spokesperson told The Times of Israel.

(and the rest of the right wing media gets on board)

[https://legalinsurrection.com/2026/02/cuny-law-hosting-lecture-framing-hamas-tunnels-as-anti-colonial-resistance/amp/](https://legalinsurrection.com/2026/02/cuny-law-hosting-lecture-framing-hamas-tunnels-as-anti-colonial-resistance/amp/)

### Anti-woke/anti-DEI is simply racism

* 31 Colleges Agree to End Partnerships With PhD Project

[https://www.insidehighered.com/news/government/2026/02/20/31-colleges-agree-end-partnerships-phd-project](https://www.insidehighered.com/news/government/2026/02/20/31-colleges-agree-end-partnerships-phd-project)

> All but 14 of the 45 universities placed under investigation for participating in the PhD Project and allegedly violating civil rights law have agreed to cease partnering with the organization, the Education Department announced Thursday.

> The Office for Civil Rights launched the investigations last March, arguing that the PhD Project, a nonprofit organization that connects prospective business doctoral candidates from underrepresented backgrounds with academic networks, was “limit[ing] eligibility based on the race of participants.”

> So by supporting or partnering with the PhD Project, OCR accused the universities of violating regulatory guidance from the department as well as Title VI of the Civil Rights Act. (Title VI prohibits discrimination based on race, color, religion, sex or national origin.)

> The announcements about McNair and the PhD Project come just weeks after the Education Department announced that it was dropping its appeal in a lawsuit that challenged the regulatory guidance that spurred these investigations. The guidance document, known as a Dear Colleague letter, declared all race-based scholarships, student support services and programming illegal based on a broad interpretation of the Supreme Court’s 2023 ruling that banned race-based admissions.

> By withdrawing the appeal, the department essentially agreed to an existing ruling from a lower court that blocked the guidance after a judge found it unconstitutional. But that doesn’t mean the administration has given up on its larger goal of ending all race-based programs.

> Since the appeal was withdrawn, the Trump administration has pointed to other guidance from the Department of Justice and the text of Title VI to justify its ongoing actions.

(Energizer bunnies from hell....)

(Also)

[https://www.washingtonpost.com/education/2026/02/19/colleges-cut-ties-diversity-groups/](https://www.washingtonpost.com/education/2026/02/19/colleges-cut-ties-diversity-groups/)

> “It’s terrible,” said Wil Del Pilar, senior vice president with Education Trust, an advocacy group focused on gaps in education for low-income and minority students.

> Groups like the PhD Project and others help provide a pathway into universities and “create a sense of belonging” for groups that have historically been left out, Del Pilar said.

(Also)

[https://www.chronicle.com/blogs/the-trump-agenda/trump-went-after-the-phd-project-now-31-campuses-have-agreed-to-sever-ties-with-it](https://www.chronicle.com/blogs/the-trump-agenda/trump-went-after-the-phd-project-now-31-campuses-have-agreed-to-sever-ties-with-it)

* Kansas May Withhold Millions From Universities With ‘DEI-CRT’ in Gen Ed

[https://www.insidehighered.com/news/diversity/2026/02/18/kansas-may-cut-millions-colleges-dei-gen-ed](https://www.insidehighered.com/news/diversity/2026/02/18/kansas-may-cut-millions-colleges-dei-gen-ed)


> This trend is playing out right now in Kansas, where Republicans are using a budget bill to move forward a host of nonfinancial public higher ed measures that have worried faculty and could mean millions in cuts for public universities. But Republicans, who control both chambers, appear undeterred. The state’s Democratic governor signed a budget bill into law last year that directed colleges to eliminate positions and activities related to “diversity, equity and inclusion.”

> Among other provisions, this year’s legislation, called House Bill 2434, contains a mechanism—with garbled wording—that’s apparently intended to withhold $2 million from each of the state’s six public universities until they prove to the State Finance Council that they don’t “require or constrain students to enroll in a DEI-CRT-related course” to earn a degree.

> The nearly 400-page budget legislation also says that, at each of the public universities, “any tenured faculty member who is placed on a one-year improvement plan during fiscal year 2027 and does not satisfactorily complete” it “is subject to dismissal, reassignment or other personnel actions as determined by the provost.” Explicitly, professors won’t be allowed to receive a second year to improve.

> It’s another example of continued Republican attacks on tenure and what conservatives dub DEI in state after state. But not all anti-DEI legislation is alike, and bills like Kansas’s that would restrict curricula without defining what DEI or CRT means have raised alarm among academic freedom and free speech advocates. Gamal Weheba, president of the Kansas Conference of the American Association of University Professors, said curriculum is the “property of the faculty.”

> “The faculty determine the curriculum—politics should not get in there,” he said. Weheba, a tenured industrial engineering professor at Wichita State University, also accused the Board of Regents of giving in to political pressure. (The regents didn’t respond to a request for comment.)

### ICE

* Reddit, Meta, and Google Voluntarily Gave DHS Info of Anti-ICE Users, Report Says

[https://gizmodo.com/reddit-meta-and-google-voluntarily-gave-dhs-info-of-anti-ice-users-report-says-2000722279](https://gizmodo.com/reddit-meta-and-google-voluntarily-gave-dhs-info-of-anti-ice-users-report-says-2000722279)

> Reddit, Meta, and Google voluntarily “complied with some of the requests” for identifying details of users critical of Immigration and Customs Enforcement (ICE) sent as part of a recent wave of administrative subpoenas the Department of Homeland Security has been distributing to Big Tech the past few months, according to an anonymously sourced New York Times report.

> Administrative subpoenas used for this purpose represent an escalation. This tool, which comes not from a judge but from DHS itself, was formerly reserved for situations like child abductions, according to the Times.

> The users were targeted because their posts “criticized ICE or pointed to the locations of ICE agents,” the Times says.

> Protesters have launched an effort called “Resist and Unsubscribe” targeting ten tech companies they perceive as exceptionally supportive of ICE. That list includes Meta, Google, and Amazon, but not Reddit.


(Original reporting)

[https://www.nytimes.com/2026/02/13/technology/dhs-anti-ice-social-media.html](https://www.nytimes.com/2026/02/13/technology/dhs-anti-ice-social-media.html)

## Institutional assaults

### UNC

* UNC Student Group Illuminates Administration’s Opaque Decisions

[https://www.insidehighered.com/news/students/2026/02/19/unc-student-group-illuminates-administrations-decisions](https://www.insidehighered.com/news/students/2026/02/19/unc-student-group-illuminates-administrations-decisions)

> TransparUNCy’s mission is simple: inform students “who controls your education, how they do it and what they don’t want you to know,” Toby Posel, a senior history major at the University of North Carolina at Chapel Hill, said on a Signal call Feb. 12. Posel describes TransparUNCy as a “political education project” aimed at undergraduates. But faculty members say it’s had a far greater impact: The four-year-old student-run activist group has become one of the public flagship’s most effective watchdogs.

> Faculty and students say UNC administrators and state higher education decision-makers have been tight-lipped about consequential policy changes rolled out at the system’s flagship campus this year – a claim the system administration disputes. Most recently, university officials quietly redrafted and approved a new policy that enshrines administrators’ ability to secretly record faculty teaching their classes.

> In December, the university began to close its six area studies centers with no warning; UNC biology professor Mark Peifer said faculty learned of the news in the student newspaper, The Daily Tar Heel. A week before that, university system president Peter Hans announced that the system would classify syllabi as public documents and require faculty to post them publicly online. He said the practice will help bolster trust in higher education, but it has also led to conservative groups doxing faculty at other institutions for teaching about race, gender and sexuality. TransparUNCy has spread information about all of these policies with their social media and word-of-mouth networks, mobilizing students to respond to them via rallies, petitions and protests.

### University of Texas

* UT Board Policy Asks Faculty to Avoid ‘Controversial’ Topics in Class

[https://www.insidehighered.com/news/faculty-issues/curriculum/2026/02/20/ut-policy-asks-faculty-avoid-controversial-topics](https://www.insidehighered.com/news/faculty-issues/curriculum/2026/02/20/ut-policy-asks-faculty-avoid-controversial-topics)

> The system board did not specify what topics are considered controversial or elaborate on how the policy will be enforced. The language echoes similar restrictions at the Texas A&M and Texas Tech systems.

> Following a public comment period during which all 10 speakers, including Democratic state representative Donna Howard, criticized the policy, the nine-member Board of Regents unanimously passed it without discussion during its regularly scheduled meeting.

> “Our Regents’ Rules affirm the freedom of our faculty to teach his or her subject in the classroom. However, that freedom comes with many responsibilities that faculty must adhere to in order to preserve academic integrity, ensure our students’ rights are protected and comply with state and federal directives,” board chair Kevin Eltife said about the “University of Texas System Expectations of Academic Integrity and Standards for Teaching Controversial Topics” policy Thursday. “An institution’s offerings in its general education core curriculum must include balanced and broad-based courses that allow students appropriate options to meet the general education requirements without a requirement to study unnecessary controversial subjects.”


## Tracking projects

* The Mathematician Lifting the Lid on Trump’s ‘Attacks’

[https://www.insidehighered.com/news/faculty-issues/research/2026/02/19/mathematician-lifting-lid-trumps-attacks](https://www.insidehighered.com/news/faculty-issues/research/2026/02/19/mathematician-lifting-lid-trumps-attacks)

> Unlike many other scientists who made their name at that time, Pagel did not initially train in public health, instead earning a Ph.D. in space physics before later becoming a professor of operational research at University College London with a focus on health care.

> In more recent years, Pagel has pivoted again, using her skills in data tracking and public communication to lift the lid on what is behind Donald Trump’s most egregious policy decisions.

[https://www.trumpactiontracker.info/](https://www.trumpactiontracker.info/)

> Along with her small team of volunteers, she has manually logged almost 2,500 examples that may “pose a threat to American democracy” since January 2025.

> Pagel said her “slow slide” from public health research came from trying to make sense of the sheer volume of actions taken by the White House in those first few months—it quickly became apparent that there was a pattern to what seemed like a “scattergun” approach.

(Time to retire this digest...)

> The White House has largely adopted right-wing mogul Steve Bannon’s tactics of “flooding the zone” to disorient opponents. For Pagel, the tracker is a method of fighting back against that—and a “way to sift through the shit”—because such attacks become normalized very quickly, she said.

> She said the tracker, which is provided largely free from commentary, is a contemporaneous record of what happened that will be useful for both journalists now and historians in the future.

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
