# Jan 23


Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

## Academic freedom

* This Spat Shows Just How Messy Texas A&M’s New Course Reviews Are

[https://www.chronicle.com/article/this-spat-shows-just-how-messy-texas-a-ms-new-course-reviews-are](https://www.chronicle.com/article/this-spat-shows-just-how-messy-texas-a-ms-new-course-reviews-are)

> Over the past six years, Leonard Bright has provoked hours-long discussions in his graduate-level “Ethics of Public Policy” course about the thorniest corners of contemporary politics: What is critical race theory? Is DEI dividing America? Should transgender athletes be allowed to compete in women’s sports?

> So when Bright, a professor at Texas A&M University’s Bush School of Government and Public Service, received an email earlier this month from a department head asking when and how he planned to teach about sexuality in the course, and whether he planned to advocate for race ideology, he knew he was in for a frustrating back-and-forth.

> Under a new Texas A&M systemwide policy, professors are not allowed to advocate for race or gender ideology or teach about topics related to sexual orientation or gender identity unless they can prove to administrators that it’s required for accreditation or career preparation.

> After a series of sharp and, at times, combative email exchanges, administrators decided last week to cancel his class.

> They say Bright was being uncooperative.

> Three days later, Taylor [Administrator] responded that, under university policy, advocacy is teaching or providing course material that “extend learning objectives in a way that requires students to hold certain beliefs, and/or to ridicule certain beliefs.”

## Freedom of expression

* Judge limits government actions against students, scholars in free speech case

[https://www.washingtonpost.com/nation/2026/01/22/free-speech-court-order-trump-administration-protesters/](https://www.washingtonpost.com/nation/2026/01/22/free-speech-court-order-trump-administration-protesters/)

> A federal judge in Boston blocked the Trump administration from retaliating against two groups of scholars and students in a case that he said exposed an “unconstitutional conspiracy” to violate the First Amendment.

> Thursday’s order marks the culmination of a case in which Young previously ruled that the Trump administration’s crackdown was illegal. The government not only violated the free-speech rights of the detained students, Young said, but also sought to chill the same freedoms for thousands of other noncitizens at colleges and universities across the country.

> While Young has issued sweeping denunciations of the administration’s actions — last week he condemned officials’ “breathtaking” violations of freedom of speech — he also has acknowledged the difficulty he faced in reining in its conduct.

> While administration officials repeatedly accused the students of being “terrorist sympathizers” and “Hamas supporters,” no evidence of direct links to terrorism was presented at trial. Internal documents showed officials saying they were unable to use existing anti-terrorism provisions to justify the visa revocations.

> About 10 HSI analysts were diverted to a so-called “tiger team” devoted to the effort, including from units that normally focus on counterterrorism, counterintelligence and cybersecurity. They compiled more than 100 reports on protesters — a first, according to the testimony of the official who oversaw the process.

> The team relied heavily on the website of Canary Mission, an opaque, anonymous pro-Israel group that says it documents individuals who “promote hatred of the USA, Israel and Jews.” It focuses primarily on college campuses.

* Higher Ed Urged to ‘Stand Up’ to Government Attacks

[https://www.insidehighered.com/news/government/politics-elections/2026/01/23/higher-ed-urged-stand-government-attacks](https://www.insidehighered.com/news/government/politics-elections/2026/01/23/higher-ed-urged-stand-government-attacks)

> A free expression lawyer, a university system leader and a civil rights activist were unified in their call to higher ed leaders to “stand up” against violations of First Amendment rights and the stifling of free speech on campuses at the annual meeting of the American Association of Colleges and Universities in Washington, D.C., on Thursday.

> At the opening plenary, the legal director at the Foundation for Individual Rights and Expression, Will Creeley, joined John King, chancellor of the State University of New York, and Maya Wiley, president and CEO of the Leadership Conference on Civil and Human Rights, in condemning institutions that have bent to political pressure. They warned that threats to constitutional rights are no longer a red-state problem.

> King acknowledged his “place of privilege” heading a public institution system under a Democratic governor, but he urged leaders in Republican-led states not to compromise their values. “I have to say, in my view, some folks in leadership roles across the higher education sector have lost their sense of where the line is, and they are complicit in a dismantling, not only of core values in higher education, but frankly of our democracy,” he said.

* A How-To Guide for Handling Campus Speech Controversies

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2026/01/23/how-guide-handling-campus-speech-controversies](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2026/01/23/how-guide-handling-campus-speech-controversies)

> Chemerinsky and Gillman’s second book, aptly named Campus Speech and Academic Freedom (Yale University Press, 2026), addresses complicated questions that aren’t necessarily answered by basic speech principles. For example, what obligation do universities have to cover security fees for controversial speakers? Or, does an institution have a responsibility to protect employees and students who are doxed for online speech?

> Q: Where do you draw the line between the professor’s right to determine their curriculum and the university’s responsibility to prevent a hostile learning environment for students?

> Gillman: Professors in professional settings do have the academic freedom as well-trained, ethical professionals to speak in ways that are consistent with their professional responsibilities. So the classroom, for example, is not a general free speech zone where professors can walk in and say whatever they want. We try to provide lots of examples of case studies where professors said and did some things that some people in the classroom or the larger academic community would have objected to, but nevertheless reflect legitimate judgments of how best to approach the issue.

> It is inevitable that if you give professors freedom of mind, that some of them are going to exercise their professional competency in ways that some people disagree with. So we try to suggest lots of examples where that academic freedom should be protected, but we also try to identify some examples where people were acting in ways that were not consistent with either their academic competence or their professional obligations. Once you understand the basic boundaries and responsibilities of faculty—not just their privileges, but their responsibilities to act in professional ways—we think that’ll help people do a proper assessment and not always just react whenever what a professor says in a classroom is causing some controversy.

> Chemerinsky:  ...  Catherine Lhamon was very outspoken in saying, “Just because it’s speech protected by the First Amendment doesn’t excuse a university from its Title VI obligations.” It’s certainly possible that a professor in class could say things that are deeply offensive to students, and [the students] could say, well, this is creating a hostile environment under Title VI. Then the issue becomes: What should the university’s response be? As Howard said, you start with assessing academic freedom—is it in the scope of professionally acceptable norms? To take a recent example, a professor who would go into a computer science class and use it to discuss his views on Israel and the Middle East, that wouldn’t be protected by academic freedom because it’s not about his teaching his class.




### Anti-woke/anti-DEI is simply racism

* Virginia Democrats target military college’s funding after anti-DEI push

[https://www.washingtonpost.com/dc-md-va/2026/01/20/vmi-state-funding-confederacy-sexism/](https://www.washingtonpost.com/dc-md-va/2026/01/20/vmi-state-funding-confederacy-sexism/)

> The nation’s oldest state-supported military college may face losing public funding as newly empowered Virginia Democrats seek to determine whether it has done enough to root out racism and sexism at the school.


> A resolution filed Tuesday in the House of Delegates would establish a task force with broad authority to investigate whether Virginia Military Institute should continue to receive state tax dollars.

> Until 2020, VMI held a ceremony honoring cadets who fought and died for the Confederacy, a memorial that was since expanded to include all VMI alumni who have died on the field of battle. The institute also long celebrated Stonewall Jackson, who was a professor at the school, before removing his statue the same year. The Lost Cause narrative glorifies the South’s role in the Civil War and asserts it was fought over states’ rights.


* Education Dept. Drops Appeal of Court Order Blocking Anti-DEI Guidance

[https://www.insidehighered.com/news/government/politics-elections/2026/01/22/ed-drops-appeal-order-blocking-anti-dei-guidance](https://www.insidehighered.com/news/government/politics-elections/2026/01/22/ed-drops-appeal-order-blocking-anti-dei-guidance)

> Education Secretary Linda McMahon and her legal team have dropped their appeal of a federal court ruling that blocked the department from requiring colleges to eradicate all race-based curriculum, financial aid and student services or lose federal funding.

> The motion to dismiss was jointly approved by both parties in the case Wednesday, ending a nearly yearlong court battle over the department’s Feb. 14 Dear Colleague letter that declared race-based programming and policies illegal. If institutions didn’t comply within two weeks, department officials threatened to open investigations and rescind federal funding.

> First Amendment advocacy groups and the DEI leaders who remain in higher ed declared it a major victory for public education. Democracy Forward, the legal group that represented educators in the case, went as far as to say that it marks the “final defeat” of Trump’s effort to censor lessons and scrub student support programs.

> “Today’s dismissal confirms what the data shows: government attorneys are having an increasingly difficult time defending the lawlessness of the president and his cabinet,” she said in a news release about the court filing. “When people show up and resist, they win.”

*  Trump Is Allowing Some Anti-DEI Directives to Die. That Likely Won’t Matter for Colleges.

[https://www.chronicle.com/blogs/the-trump-agenda/trump-is-allowing-some-anti-dei-directives-to-die-that-likely-wont-matter-for-colleges](https://www.chronicle.com/blogs/the-trump-agenda/trump-is-allowing-some-anti-dei-directives-to-die-that-likely-wont-matter-for-colleges)

> But the development likely won’t disrupt the Trump administration’s anti-DEI campaign against higher ed.

> In late July, the Department of Justice published a memo making virtually the same points about colleges and DEI. The memo describes a wide range of practices in admissions, hiring, scholarships, campus life, and other areas that, in the government’s eyes, could amount to discrimination and result in a loss of federal funding.

> The Trump administration is using the DOJ memo to pressure colleges to make changes to their diversity efforts. In its recent deal with the federal government, for instance, the University of Virginia agreed to apply the DOJ guidance “as relevant, to the extent consistent with judicial decisions.”


## Visas

* Florida Proposes Banning H-1B Visa Hires Across All Public Universities


[https://www.insidehighered.com/news/quick-takes/2026/01/22/florida-proposes-h-1b-hiring-ban-all-public-universities](https://www.insidehighered.com/news/quick-takes/2026/01/22/florida-proposes-h-1b-hiring-ban-all-public-universities)

> All Florida public universities would be banned from hiring foreign workers on H-1B visas under a policy change that the Florida Board of Governors will consider next week.

> DeSantis complained about professors coming from China, “supposed Palestine” and elsewhere. He said, “We need to make sure our citizens here in Florida are first in line for job opportunities.”



## Funding cuts

* US science after a year of Trump: what has been lost and what remains

[https://www.nature.com/immersive/d41586-026-00088-9/index.html](https://www.nature.com/immersive/d41586-026-00088-9/index.html)

> More than 7,800 research grants terminated or frozen. Some 25,000 scientists and personnel gone from agencies that oversee research. Proposed budget cuts of 35% — amounting to US$32 billion.

> These are just a few of the ways in which Donald Trump has downsized and disrupted US science since returning to the White House last January. As his administration seeks to reshape US research and development, it has substantially scaled back and restricted what science the country pursues and the workforce that runs the federal scientific enterprise.

(Lots of graphics detailing less of everything...)

### NEH

* NEH Pours Millions Into Conservative-Aligned Projects

[https://www.insidehighered.com/news/government/2026/01/20/neh-pours-millions-fehe-network-unc-civic-school-more](https://www.insidehighered.com/news/government/2026/01/20/neh-pours-millions-fehe-network-unc-civic-school-more)

> The National Endowment for the Humanities has announced more than $75 million in awards, including $10 million grants to two public universities with “civics” schools and to an education network headquartered at a conservative think tank.

> The largest NEH awards—$10 million apiece—are going to the University of North Carolina at Chapel Hill, the University of Texas at Austin and the Foundation for Excellence in Higher Education. The New York Times, citing unnamed sources, reported that “many of the large grants” from NEH, including those three, “were noncompetitive, meaning the recipients were selected to apply.”

> The $10 million going to the Foundation for Excellence in Higher Education is for a project dubbed Recovering the Humanities in Service of the University.

> Kelly Hanlon, FEHE’s operations director, said the foundation “does not have any political, ideological or religious affiliation, nor does it fund policy work.” But FEHE is based at—and shares its president with—the Witherspoon Institute, a conservative think tank next to Princeton University’s campus. The FEHE/Witherspoon president, Luis Tellez, became prominent in the fight against same-sex marriage and has long been a leader within Opus Dei, the controversial conservative Roman Catholic group. FEHE has also received millions of dollars from conservative donors.

> Joan Scott, a professor emerita at the Institute for Advanced Study and a member of the AAUP’s Committee A on Academic Freedom and Tenure, said, “It just seems to me that we now have the ideological arm of the Trump administration giving out money to support the production of knowledge in ways that they approve of.”

> “The money goes to various ‘civic institutes’ established specifically to counter teaching that is critical of aspects of American history, of capitalism, etc.,” Scott said. “In a way, the NEH has become a parallel institution to the Koch Foundation.”

(Also)

[https://www.chronicle.com/article/gops-civics-education-push-gets-boost-with-millions-from-trumps-neh](https://www.chronicle.com/article/gops-civics-education-push-gets-boost-with-millions-from-trumps-neh)

### DOE

* Again Defying Trump, Congress Proposes Increasing NIH Budget, Maintaining ED

[https://www.insidehighered.com/news/government/science-research-policy/2026/01/20/congress-proposes-increasing-nih-budget](https://www.insidehighered.com/news/government/science-research-policy/2026/01/20/congress-proposes-increasing-nih-budget)

> The House and Senate appropriations committees have jointly proposed legislation that would generally maintain the Education Department’s funding levels, plus increase the National Institutes of Health’s budget by more than $400 million this fiscal year. It’s the latest in a trend of bipartisan congressional rebukes of President Trump’s call to slash agencies that support higher ed.

> “We were surprised to see the level of funding for the higher education programs actually be increased, in some regards—and be maintained,” said Emmanual Guillory, senior director of government relations at the American Council on Education. “We knew that level funding would be considered a win in this political environment.”


## Federal Agencies

### DOE/OCR

* Report: Education Department Opens Fewer Sexual Violence Investigations

[https://www.insidehighered.com/news/quick-takes/2026/01/21/report-ed-opens-fewer-sexual-violence-investigations](https://www.insidehighered.com/news/quick-takes/2026/01/21/report-ed-opens-fewer-sexual-violence-investigations)

> The Department of Education—once the leading force for cracking down on colleges that mishandled cases of sexual assault and harassment—has now all but given up on sexual violence investigations, a new report from the Associated Press shows.

> Under administrations past, the department’s Office for Civil Rights would take on dozens of new cases each year, AP said, but since Trump took office a year ago Tuesday, it has opened fewer than 10. Meanwhile, it’s accumulated a backlog of more than 25,000 cases.

## Institutional assaults

* NYTimes: Inside Trump’s Campaign to Tame Higher Education

[https://www.nytimes.com/2026/01/21/us/politics/trump-higher-education-2025.html?smid=nytcore-ios-share](https://www.nytimes.com/2026/01/21/us/politics/trump-higher-education-2025.html?smid=nytcore-ios-share)

> Yet the sweeping campaign has provided the country with an early glimpse of a broader crusade of retribution against political rivals and perceived enemies that has become a driving force of Mr. Trump’s second term. In the administration’s view, the approach has yielded enough successes to continue pressing to alter the cultures of universities, which Mr. Trump has derided as factories of “woke” ideology and hostile to his presidency.

> The president managed to chisel away at the independence of the nation’s top universities by pairing investigations with pre-emptive strikes on federal funding for schools. The move has forced college leaders to choose between holding the line on their academic freedom or confronting the costs of resistance.

> Fear of drawing the government’s ire has made professors reluctant to teach concepts that Mr. Trump’s allies contest. Researchers have grown wary that a single word or comment could prompt federal penalties against their universities. Campuses, which regarded themselves as incubators of critical thought and freedom of expression crucial to a healthy democracy, have been reined in, with administrators and students alike on edge.

> The results have pleased Trump aides so much that they are readying a second attempt to persuade universities to sign on to a voluntary “compact” that follows a list of the administration’s principles, officials said. The first version got little traction. The White House is also examining how to enforce individual provisions, regardless of whether schools sign on, said May Mailman, the White House’s senior adviser for special projects.

> Ms. Mailman said Mr. Trump’s pressure campaign on universities had been “far greater than anyone could have expected.”

> “The administration is trying to shut down dissent,” said Corey Brettschneider, a political science professor at Brown University who has studied the role of free speech in democracies. “Universities, because they are a sanctuary for individual and free thought, they’ve become a target.”

> “We were only told to investigate cases that were in blue states, and cases or investigations involving red states or that didn’t involve perceived political enemies of the administration never moved forward,” said Ejaz Baluch Jr., a former Justice Department lawyer who was investigating the University of California when he quit his post in May. “There was no interest in antisemitism unless it involved protests of Israel or the war in Gaza.”

(And much more...)

* ‘N.Y. Times’: Another Version of Trump’s Higher Ed Compact in the Works

[https://www.insidehighered.com/news/quick-takes/2026/01/22/times-new-version-trumps-higher-ed-compact-works](https://www.insidehighered.com/news/quick-takes/2026/01/22/times-new-version-trumps-higher-ed-compact-works)

> Apparently emboldened after cutting deals with several universities last year, Trump administration officials are reworking their controversial compact for higher ed that many institutions rejected outright, The New York Times reported.


### Harvard

* NYTimes: Chinese Universities Surge in Global Rankings as U.S. Schools Slip

[https://www.nytimes.com/2026/01/15/us/harvard-global-ranking-chinese-universities-trump-cuts.html?smid=nytcore-ios-share](https://www.nytimes.com/2026/01/15/us/harvard-global-ranking-chinese-universities-trump-cuts.html?smid=nytcore-ios-share)

> Until recently, Harvard was the most productive research university in the world, according to a global ranking that looks at academic publication.

> That position may be teetering, the most recent evidence of a troubling trend for American academia.

> Harvard recently dropped to No. 3 on the ranking. The schools racing up the list are not Harvard’s American peers, but Chinese universities that have been steadily climbing in rankings that emphasize the volume and quality of research they produce.


### Columbia

* NYTimes: Columbia University’s Strained Peace: Fewer Protests and Sealed Gates

[https://www.nytimes.com/2026/01/19/us/politics/columbia-university-protests-culture-trump.html?smid=nytcore-ios-share](https://www.nytimes.com/2026/01/19/us/politics/columbia-university-protests-culture-trump.html?smid=nytcore-ios-share)

> The gates to Columbia’s main campus in Manhattan swung shut more than two years ago to control volatile protests over the war in Gaza. There was a days-long encampment, a building takeover and arrests by police. Now, entry is permitted only to those who hold Columbia identification and their approved guests.

> Today, the relative quiet at the university — despite its history of uprisings, even within a boisterous anti-Trump New York — is partly a measure of the White House’s success in taming unrest at Columbia and other universities around the country.

> Other students and faculty members say the strained campus peace has cut unacceptably at Columbia’s identity and made the school an example of capitulation to government overreach.

> “Political advocacy has just been tamped down to a remarkable degree,” said Michael Thaddeus, a mathematics professor and vice president of Columbia’s American Association of University Professors chapter. In the fall, he navigated the tighter rules on demonstrations while organizing an event for academic freedom.

> “You can try to spin it in a positive way by saying, well, the campus has calmed down and people can get back to doing their important work,” he said. “But my view is that protest and dissent are part of the essential work of a university.”

### Kansas

* Another State’s Public Universities Are Tightening Post-Tenure Review and Dictating Teaching Loads

[https://www.chronicle.com/article/another-states-public-universities-are-tightening-post-tenure-review-and-dictating-teaching-loads](https://www.chronicle.com/article/another-states-public-universities-are-tightening-post-tenure-review-and-dictating-teaching-loads)

> Faculty members at Kansas’ six public universities will now be subject to stricter post-tenure-review policies that faculty advocates say erode the institution of tenure — and leave it vulnerable to further attacks from state legislators. The Kansas Board of Regents also passed a policy dictating minimum teaching loads and how faculty members should divide their time between teaching, research, and service.

> Meanwhile, all full-time faculty members will be expected to teach a set number of credit hours per semester: six to nine for those at the state’s three research institutions — the University of Kansas, Kansas State University, and Wichita State University — and 12 for professors at the regional institutions — Pittsburg State University, Emporia State University, and Fort Hays State University.

### U Penn

* NYTimes: Penn Calls Government’s Demand for Lists of Jewish Staff ‘Disconcerting’

[https://www.nytimes.com/2026/01/20/us/university-of-pennsylvania-trump-jewish-staff.html?smid=nytcore-ios-share](https://www.nytimes.com/2026/01/20/us/university-of-pennsylvania-trump-jewish-staff.html?smid=nytcore-ios-share)

> The University of Pennsylvania on Tuesday condemned Trump administration investigators for seeking records about Jewish employees, saying in a federal court filing that the request was “disconcerting.”

> The university and the Equal Employment Opportunity Commission have been at odds for months over an investigation into antisemitism at Penn.

> The demand prompted a campus uproar, and in a blistering response on Tuesday, Penn described the request as an “extraordinary and unconstitutional demand.”


### UVA

* U-Va. board leaders resign as Spanberger and Democrats take power

[https://www.washingtonpost.com/dc-md-va/2026/01/16/george-mason-vmi-lawyers-fired-jay-jones/](https://www.washingtonpost.com/dc-md-va/2026/01/16/george-mason-vmi-lawyers-fired-jay-jones/)

> However, Ryan [past president] wrote that Manning later told him that the governor and Sheridan needed him to resign. Ryan said Manning had also heard from the Justice Department that if Ryan did not resign, officials would “bleed UVA white.”

> “Rachel, Porter, and Paul should also take some responsibility for the decision to allow this to happen,” he wrote of his resignation.

* Spanberger Reshapes Virginia Boards on Day One

[https://www.insidehighered.com/news/governance/state-oversight/2026/01/20/spanberger-reshapes-virginia-boards-day-one](https://www.insidehighered.com/news/governance/state-oversight/2026/01/20/spanberger-reshapes-virginia-boards-day-one)

> Freshly sworn into office, Virginia governor Abigail Spanberger appointed 27 new members to three university boards Saturday, effectively reshaping governance at the University of Virginia, George Mason University and Virginia Military Institute.

## Op eds

* NYTimes: One Year of Trump. The Time to Act Is Now, While We Still Can.

[https://www.nytimes.com/2026/01/18/opinion/trump-one-year-later.html?smid=nytcore-ios-share](https://www.nytimes.com/2026/01/18/opinion/trump-one-year-later.html?smid=nytcore-ios-share)

(CUNY's M. Gessen on the shape of things)

> We have become a country whose federal government deploys military and paramilitary forces in the streets of its major cities, terrorizing the residents in the guise of protecting them. A foreign observer taking stock of the United States could describe us as a nation on the brink of civil war. But we can barely keep current the list of cities where troops have been or still are in the streets: Washington, D.C.; Los Angeles; Chicago; Portland, Ore.; Memphis; New Orleans. The number of armed federal agents deployed to Minneapolis may now be five times the size of the city’s police force.

* 4 Takeaways From Trump’s First Year in Office

[https://www.insidehighered.com/news/government/2026/01/20/4-takeaways-trumps-first-year-office](https://www.insidehighered.com/news/government/2026/01/20/4-takeaways-trumps-first-year-office)

> ... few expected the pace and force of the changes the Trump administration quickly embarked on.

> Within a month, Trump officials had threatened colleges’ research funding, started gutting the Institute for Education Sciences, declared race-based programming illegal and unleashed Immigration and Customs Enforcement officers on campuses, among other actions.

> Then, over the next six months, the administration started dismantling the Education Department, cut thousands of research grants that didn’t align with Trump’s priorities, helped oust the University of Virginia’s president and cracked down on international students—deporting some who criticized Israel and revoking the visas of thousands. It also kicked off a targeted pressure campaign on several universities that included freezing billions in federal funding and landmark settlements. All of these measures were necessary, Trump officials repeatedly said, to shake up a system that’s not working for all students and to hold universities accountable, protect national security, curb campus antisemitism and enforce other federal civil rights laws.

> The agenda for the next year so far includes reworking the rules for accreditation, changing who gets grant funding and carrying out sweeping changes to the student loan system and how college programs are held accountable. And officials could always attempt to resurrect the administration’s proposed compact for higher ed, which was resoundingly rejected in the fall.

> "I think that the year has been one of fear and chaos, and nobody does well in an environment of fear or chaos,” said Ted Mitchell, president of the American Council on Education. “By and large, I think, higher education has suffered. But the suffering is really more emotional than anything else.”

> Here’s what sources tell us they’ve learned about higher ed under Trump 2.0 ...
> * The federal government–higher ed relationship is not sacrosanct.
> * Trump followed through on his campaign pledges.
> * Colleges have felt the impact of Trump’s policies and reconsidered their approach.
> * Higher ed is bracing for fundamental change.


## AI misdeeds

* NYTimes: A.I. Is Coming to Class. These Professors Want to Ease Your Worries.

[https://www.nytimes.com/2026/01/17/nyregion/ai-college-classes.html?smid=nytcore-ios-share](https://www.nytimes.com/2026/01/17/nyregion/ai-college-classes.html?smid=nytcore-ios-share)

(The Times found a few supporters...)

> “Students tend to use it in our classrooms to do the work that we are here to teach them how to do,” she [first-year writing program director at Barnard] said. “And it is very, very bad at that work.”

> But she has made an exception for Professor Breyer, who is determined to see if he can use A.I. to supplement, not short-circuit, the efforts of students as they study academic writing. In that sense, Professor Breyer represents a growing swath of writing and English professors who are trying to find positive uses for a technology that some of their colleagues remain dead set against.

* Survey: Faculty Say AI Is Impactful—but Not In a Good Way

[https://www.insidehighered.com/news/faculty-issues/teaching/2026/01/21/survey-faculty-say-ai-impactful-not-good-way](https://www.insidehighered.com/news/faculty-issues/teaching/2026/01/21/survey-faculty-say-ai-impactful-not-good-way)

> Faculty overwhelmingly agree that generative artificial intelligence will have an impact on teaching and learning in higher education, but whether that impact is positive or negative is still up for debate.

> Nine in 10 faculty members say that generative AI will diminish students’ critical thinking skills, and 95 percent say its impact will increase students’ overreliance on AI tools over time, according to a report out today from the American Association of Colleges and Universities and Elon University.

> While most professors—78 percent—said AI-driven cheating is on the rise, they are split about what exactly constitutes cheating. Just over half of faculty said it’s cheating for a student to follow a detailed AI-generated outline when writing a paper, while just under half said it is either a legitimate use of AI or they’re not sure. Another 45 percent of faculty said that using generative AI to edit a paper is a legitimate use of the tool, while the remaining 55 percent said it was illegitimate or they were unsure.

*  Lured by AI, Colleges Are Sleepwalking Into Irrelevance

[https://www.chronicle.com/article/lured-by-ai-colleges-are-sleepwalking-into-irrelevance](https://www.chronicle.com/article/lured-by-ai-colleges-are-sleepwalking-into-irrelevance)

> "Are you thinking of retiring early?” This was the question posed to me last summer by an English professor at a top research university, at a backyard barbecue. His reasoning was blunt: AI can summarize texts, identify arguments, and write entire papers. These days, he said, no student can resist using it.

> AI is unquestionably a world-transforming technology, with many potentially beneficial applications. My concern here is not with the technology itself; rather, it is with the ways AI is being developed and hastily implemented. It is not an organic process: rather it is a deeply ideological one. Technologies are not naturally occurring. They are created. They are designed with specific sets of protocols, and with a particular vision of the world, in mind. In the case of AI, a small group of corporations (or more precisely, a handful of extraordinarily wealthy men), are actively shaping the future of AI while insisting that it cannot be resisted. The rhetoric of inevitability serves a clear function. It forecloses debate, consolidates power, and discourages meaningful constraints, all in the service of the larger goal of gaining cognitive and economic dominance.

> The inevitable AI future, in other words, is a story: a manufactured narrative that legitimizes a particular structure of power.

> The university must step off the inevitability train. Despite prevailing sentiment, our response to AI is not powerless; rather, we can determine whether we preserve our fundamental mission of cultivating critical thinking and independent scholarship or whether we become complicit in our own obsolescence.

> If knowledge production is outsourced to machines, the question will no longer be how to use AI effectively but, rather, what purpose an institution devoted to teaching and learning serves at all. For universities, the stakes could not be higher.


## And just because it is fun

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
