# Jan 2

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

Kinda quiet during this holiday season, but be sure the Grinch's elves are hard at work planning their attacks for next year.

## Academic freedom

* University of Oklahoma removes instructor after grading dispute on gender essay

[https://www.washingtonpost.com/education/2025/12/23/oklahoma-university-gender-essay-bible/](https://www.washingtonpost.com/education/2025/12/23/oklahoma-university-gender-essay-bible/)

> The University of Oklahoma on Monday removed an instructor who gave a student a failing grade on a gender essay last month, in an incident that had prompted debates over religious, gender and academic freedoms.

> The student, Samantha Fulnecky, received a zero for an essay in which she rejected the concept of multiple genders and cited the Bible to support her view that traditional gender roles should not be considered stereotypes.

> “Ms. Curth continues to deny that she engaged in any arbitrary behavior regarding the student’s work, and is considering all of her legal remedies, including appealing this decision by the university,” Brittany M. Stewart said in the statement.

* NYTimes: Texas A&M Will Not Reinstate Lecturer Fired Over Gender Lesson

[https://www.nytimes.com/2025/12/24/us/texas-am-decline-reinstate-fired-faculty-member.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/12/24/us/texas-am-decline-reinstate-fired-faculty-member.html?smid=nytcore-ios-share)

> Texas A&M University has declined to reinstate a faculty member who was fired after she was accused of teaching a course that recognized more than two genders, even after an appeals panel found that the dismissal was not justified.

> The decision to not reinstate the instructor, Melissa McCoul, is expected to set off a court battle touching on academic freedom as President Trump is pressuring universities to embrace his vision for the nation’s campuses.

* Populist Attacks on Academic Freedom: How Populist Leadership Erodes Academic Freedom in Liberal and Electoral Democracies | Perspectives on Politics | Cambridge Core

[https://www.cambridge.org/core/journals/perspectives-on-politics/article/populist-attacks-on-academic-freedom-how-populist-leadership-erodes-academic-freedom-in-liberal-and-electoral-democracies/FB4B535AB73E67D5465DDD83680776D6](https://www.cambridge.org/core/journals/perspectives-on-politics/article/populist-attacks-on-academic-freedom-how-populist-leadership-erodes-academic-freedom-in-liberal-and-electoral-democracies/FB4B535AB73E67D5465DDD83680776D6)

> Abstract: Governments are increasingly targeting academic institutions such as the Central European University in Hungary, Boğaziçi University in Turkey, or CIDE in Mexico. These attacks represent the most visible symptoms of the deterioration of academic freedom. What is the cause of this trend? We argue that populism, being a thin ideology that polarizes the public sphere into virtuous citizens and a corrupt elite while emphasizing the will of the people, has made universities and academics natural targets for leaders who seek to impose a narrative in which only they possess the truth and represent the will of the people. Universities are characterized not only by a pluralism of ideas but also possess an elitist character: these attributes are in direct conflict with the values and vision of populist leaders. To support this argument, we present a global statistical analysis correlating the degree of populism exhibited by executive leaders with the extent of academic freedoms between 2000 and 2021, based on data from the Global Populism Database and V-Dem, and we illustrate our arguments with an in-depth analysis of the case of CIDE in Mexico.

> Mudde (Reference Mudde2004) defines populism as an ideology that views society as divided into two opposing groups—“the pure people” and “the corrupt elite”—and claims that politics should reflect the general “will of the people.” Based on this definition, Mudde argues that two values—elitism and pluralism—conflict with populism. Academic institutions embody these opposing values because their high degree of specialization and freedom of thought and expression necessarily precondition their dedication to fostering knowledge, research, and learning, which by definition cannot be univocal but are plural.

> Although common wisdom associates populism with autocratic rule, we can observe that even in democratic contexts, which rely on freedom of information, academic freedom deteriorates under populist leaders. Using data from the Global Populism Database and controlling for factors such as constitutional protections of academic freedom, polarization, and legislative and judicial constraints on the executive (as included in the V-Dem dataset by Coppedge et al. Reference Coppedge, Gerring, Knutsen, Lindberg, Teorell, Altman, Bernhard, Agnes Cornell and Gastaldi2023), we find that as a populist leader’s rhetoric becomes more extreme, academic freedom significantly decreases. This decline persists even when accounting for a country’s level of liberal democracy, which is supposed to mitigate the harmful effects of populism on democracy

> In-depth accounts of the attacks on academic communities in Mexico illustrate how academic institutions naturally become targets of populist rhetoric and how their academic freedoms suffer for it. They are portrayed as aligned with elite privilege, yet they also embody critical thinking and pluralism, which stand in direct opposition to the Manichean worldview advanced by populist leaders. As a result, they experience attacks on their academic freedoms evidenced by budget cuts, changes in leadership and personnel demotions, and the elimination of research initiatives and programs that were critical of the populist agenda.

> There are many ways to infringe on academic freedom, and even in democracies it can be under attack. For example, in the United States, legislation was passed during the McCarthy era requiring professors to sign loyalty oaths and to testify their ideological commitments, President Nixon had a list of enemies, and President Reagan did what he could to eliminate funding for the social and behavioral sciences. These measures discouraged open discourse and debate (Cole Reference Cole2017). Robert Hutchins, president of the University of Chicago, said this about intimidatory practices during McCarthyism: “The question is not how many professors have been fired for their beliefs, but how many think they might be. The entire teaching profession is intimidated” (as cited in Cole Reference Cole2017, 864).

> We argue that because populist leaders use a narrative that simplifies complex issues, rely on charismatic leadership, and advocate for policies that resonate with popular sentiment, universities and academics become a natural target in their attempt to promote a simplistic and Manichean understanding of the world and to control the flow of information to shape public opinion in their favor. Populist leaders may perceive academic institutions as bastions of liberal or progressive values that they oppose. By targeting academic freedom, they can wage a form of cultural warfare against these values and attempt to reshape societal norms in line with their own worldview. Universities are not only characterized by a pluralism of ideas but also have an elitist character: these two attributes—pluralism and elitism—are in direct conflict with the values and vision of populist leaders.

> Additionally, universities provide a fertile ground for the cultivation of pluralism by encouraging professors and students to explore and debate diverse viewpoints without fear of censorship, guided by principles of rational inquiry and respect for others’ opinions. Furthermore, academic practices help professors and students develop critical thinking skills, making them a natural engine of dissent and informed critique (Lynch Reference Lynch and Lackey2018; Rabban Reference Rabban2024). Pluralism, dissent, and critique are values that come into conflict with populist leaders who aim to control public discourse and reduce it to simplistic solutions derived from a dramatized battle between good and bad, without nuance and a rationale. That is why research universities and the academic freedom that protects their work become a clear target of populist leaders.

(Findings)

> Leaders with higher levels of populist discourse exhibit a statistically significant negative relationship (p < 0.01) with academic freedom. ...

> democracy significantly influences academic freedom. In model 3, the estimate of the liberal democracy index shows a positive and statistically significant relationship (p < 0.01) with the level of academic freedom. ...

> A particularly interesting feature of these findings is that, when analyzing the impact of populism on some phenomenon, it can be challenging to distinguish between the authoritarian tendencies of political leaders and their populist inclinations, because these concepts often overlap. In model 3 we introduce liberal democracy as an alternative control variable. By interpreting liberal democracy as the antithesis of authoritarianism, we can suggest that the adverse effect of populism on academic freedom is independent from that of an authoritarian context characterized by restricted political pluralism, limited freedom of speech and expression, curtailed civil liberties, lack of an independent judiciary, and minimal checks and balances on government power. Returning to the impact of populist leadership, our main independent variable, its statistical significance and coefficient size, even when its coefficient size seems moderate, appear to be unaffected by the inclusion or exclusion of the liberal democracy control. We suggest that these results should be interpreted as evidence of an additional effect that populist discourse has on academic freedom—one that operates independently of the important and broader impact of a regime’s democratic or authoritarian nature (Berggren and Bjørnskov Reference Berggren and Bjørnskov2022; Lott Reference Lott2024), as captured in the liberal democracy index.

> This suggests that academic freedom is inhibited in more polarized contexts.

> Meanwhile, the variables measuring legislative and judicial constraints on the executive do not provide conclusive or consistent evidence of a relationship with academic freedom.

(The article finishes with a case study from Mexico's Andrés Manuel López Obrador (AMLO) very "trumpian" attacks on CIDE, a public research center specializing in the teaching and research of economics.)


## Freedom of expression

* I Counted Trump’s Censorship Attempts. Here’s What I Found.

[https://www.nytimes.com/2025/12/31/opinion/trump-first-amendment-dissent.html?unlocked_article_code=1.A1A.zedM.aJ3rGg2YdJhK&smid=nytcore-ios-share](https://www.nytimes.com/2025/12/31/opinion/trump-first-amendment-dissent.html?unlocked_article_code=1.A1A.zedM.aJ3rGg2YdJhK&smid=nytcore-ios-share)

(A highlight reel of attacks on free speech this past year beginning with this quote from the president)

> “We took the freedom of speech away.”

### Anti-woke/anti-DEI is simply racism

* DOJ Report Declares MSIs Unconstitutional

[https://www.insidehighered.com/news/institutions/minority-serving-institutions/2025/12/22/doj-report-declares-msis](https://www.insidehighered.com/news/institutions/minority-serving-institutions/2025/12/22/doj-report-declares-msis)

> The Department of Justice has declared a slew of Department of Education programs and grants unconstitutional based on the Supreme Court’s decision in Students for Fair Admissions v. Harvard and the University of North Carolina.

> According to a report by the DOJ’s Office of Legal Counsel (OLC), minority-serving institution (MSI) programs are unlawful because they award money to colleges and universities based on the percentage of students of a certain race. The report said such programs “effectively [employ] a racial quota by limiting institutional eligibility to schools with a certain racial composition” and should no longer be funded.

> “Today’s baseless opinion from the Justice Department is wrong, plain and simple. Donald Trump and his Administration are once again attacking the institutions that expand opportunity for millions of aspiring students of all backgrounds. The opinion ignores federal law, including Congress’ bipartisan support for our nation’s Hispanic-Serving Institutions and Minority-Serving Institutions, including more than 100 MSIs in California alone,” Senator Alex Padilla, a California Democrat who chairs the Senate HSI Caucus, wrote in a statement. “Every student deserves access to the American Dream. This unconscionable move by this Administration will harm millions of students who deserve better.”

> Presidents of institutions that could be impacted by the legal decision are also speaking out. Wendy F. Hensel, president of the University of Hawai'i, called the news “disappointing” in a statement to the campus community. UH is an Alaskan Native and Native Hawaiian-serving institution, an Asian American and Native American Pacific Islander-serving institution, and a Native Hawaiian Career and Technical Education grantee; Hensel said these programs are “vital” to UH and the state of Hawai'i.


## Funding cuts

### NIH

* NIH grant policy hurt funding chances for early-career scientists | STAT

[https://www.statnews.com/2025/12/18/nih-early-career-researchers-grant-success-rate-falls/](https://www.statnews.com/2025/12/18/nih-early-career-researchers-grant-success-rate-falls/)

> A Trump administration change to how the National Institutes of Health awards grants has reduced early-stage investigators’ odds of securing funding, new data from the agency show.

> During the 2025 fiscal year, 18.5% of early-stage researchers who applied for grants equivalent to an R01, the agency’s most common type of award, were successful. That’s an 11 percentage point drop compared to the 2023 fiscal year, when the success rate for such applications was 29.8%.



## Institutional assaults

### Harvard

* NYTimes: Trump Administration to Appeal Harvard Funding Case

[https://www.nytimes.com/2025/12/19/us/trump-administration-appeal-harvard-funding-case.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/12/19/us/trump-administration-appeal-harvard-funding-case.html?smid=nytcore-ios-share)

> The Trump administration said late Thursday that it would appeal a ruling that sided with Harvard University in its fight with the government over free speech and billions of dollars in research funding.

> The government began blocking grant payments to Harvard on research projects in the spring, but restarted them soon after the Sept. 3 decision by Judge Allison D. Burroughs of the Federal District Court in Boston. On Thursday, the Justice Department, carrying out a pledge from the White House, said in a terse filing that it would pursue an appeal of that ruling before the U.S. Court of Appeals for the First Circuit.

> As is customary, the government did not use Thursday’s notice to explain the grounds for its appeal, which will also include a related case brought by the American Association of University Professors and other groups. In a statement on Friday, a Harvard spokesman said the university was “confident that the Court of Appeals will affirm the district court’s opinion.”

* NYTimes: Harvard’s New Campus Orthodoxy Is Even More Stifling Than the Old

[https://www.nytimes.com/2025/12/29/opinion/harvards-campus-speech-trump.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/12/29/opinion/harvards-campus-speech-trump.html?smid=nytcore-ios-share)

(By a sophomore at the University)

> That’s not how it’s playing out. Under federal pressure, Harvard and other universities around the country now police academic inquiry according to murkier standards of fairness. The goal, it seems, is to avoid offending anyone, anywhere, across an ever-expanding matrix of identities and standpoints. Rather than dismantling the excesses of the woke era, the new Trump-friendly programs and policies simply repurposed them to serve a different ideological agenda. The result is a new orthodoxy even more stifling than the last.

> Before I was allowed to register for classes this semester, I had to complete a newly designed training video and corresponding online test about Harvard’s nondiscrimination and sexual harassment policies. The video informed me that Harvard uses the definition of antisemitism “endorsed by the International Holocaust Remembrance Alliance” and that the university “considers the examples that accompany the I.H.R.A. definition to the extent that those examples might be useful in determining discriminatory intent.” Some of those examples are preposterously broad, including political arguments about Israel that apply what the group considers to be “double standards.” The Foundation for Individual Rights and Expression, a free-speech advocacy group, has warned that the definition is “vague and overbroad” and that it pressures “schools to police speech.” Double standards? FIRE points out that it’s unclear what constitutes an acceptable single standard.

> In a climate of uncertainty and anxiety, students tiptoe around the issue, afraid of saying the wrong thing. Faculty do, too.

* NYTimes: In Private Letters, Harvard and Trump Administration Escalate Duel

[https://www.nytimes.com/2025/12/24/us/trump-harvard-letters-deal.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/12/24/us/trump-harvard-letters-deal.html?smid=nytcore-ios-share)

> Dr. Garber felt he had made clear in recent negotiations that the university would not agree to pay the federal government to settle a monthslong battle with the Trump administration over antisemitism on campus and other matters.

> But Ms. McMahon’s Saturday message said the opposite. In it, she thanked Dr. Garber for what she portrayed as his commitment to sending $200 million to the government as part of a deal.

> Dr. Garber wrote back to clarify Harvard’s position. But, in response, the administration doubled down, introducing terms that were so far-reaching that university officials saw them as nonstarters

> The episode also underscored the emerging role played by people inside the administration who want to extract more concessions from Harvard. And it raised new questions about whether some of those voices were more interested in preserving the power of the government’s threat against Harvard as a message to other universities than in reaching a settlement with the nation’s wealthiest university.

> But the second paragraph of Dr. Garber’s letter included some pushback.

> “I do need to clarify that, during our recent conversations, I described our work force investment proposal as one for $500 million — not for $300 million in addition to a $200 million cash payment — and conveyed the importance of reaching agreement on other terms,” Dr. Garber wrote. “If we can reach agreement on those other terms, we are prepared to invest $500 million in the work force development programs we discussed and I described.”

> He added that Harvard’s lawyers had no record of the “proposed edits or additions from the Department of Justice,” but said that the university was “committed to continuing our dialogue and restoring and strengthening the partnership between Harvard and the federal government.”

> The government sent revised terms the next day, alarming Harvard officials with seemingly new demands that appeared to encroach on their independence, according to people familiar with the discussions. Harvard privately responded to the government on Tuesday, indicating that the university believed the Trump administration was abruptly seeking to impose new terms and promising a fuller reply after further review.

> Some at the university believe that agreeing to a fine would be tantamount to a bribe

(Others might call this extortion...)


### New College of Florida

* NYTimes: New College of Florida Was Progressive. Then Gov. DeSantis Overhauled It.

[https://www.nytimes.com/2025/12/28/us/new-college-ron-desantis-florida-conservative.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/12/28/us/new-college-ron-desantis-florida-conservative.html?smid=nytcore-ios-share)

(This ridiculous puff piece glossing over the destruction of an institution is brought to you by Anemona Hartocollis---national reporter for The New York Times, covering higher education. I'd quote, but for the most part only the president gets a chance to comment on what a great job he is doing...)


## Op eds

* NYTimes: Trump Is the Jan. 6 President

[https://www.nytimes.com/2025/12/31/opinion/jan-6-anniversary-trump-politics.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/12/31/opinion/jan-6-anniversary-trump-politics.html?smid=nytcore-ios-share)

(Nothing about higher education, but here is the landing:)

> The Jan. 6 era turns five years old on Tuesday. The anniversary will always be a mournful one for America. The nation’s challenge now is to ensure that the day is ultimately viewed as it initially was: as an aberration. Americans must summon the collective will to bring this era to an end and make certain that the violence, lawlessness and injustice of Jan. 6 do not endure.


## Higher Education as a Public Good

* Marginal Returns to Public Universities | The Quarterly Journal of Economics | Oxford Academic

[https://academic.oup.com/qje/advance-article/doi/10.1093/qje/qjaf055/8376650](https://academic.oup.com/qje/advance-article/doi/10.1093/qje/qjaf055/8376650)


> Abstract: This paper studies the returns to enrolling in American public universities by comparing the long-term outcomes of barely admitted versus barely rejected applicants. I use administrative admission records spanning all 35 public universities in Texas, which collectively enroll 10 percent of all American public university students, to systematically identify and employ decentralized cutoffs in SAT/ACT scores that generate discontinuities in admission and enrollment. The typical marginally admitted student gains an additional year of education in the four-year sector, becomes 12 percentage points more likely to ever earn a bachelor’s degree, and eventually earns 8 percent more than their marginally rejected but otherwise identical counterpart. Marginally admitted students pay no additional tuition costs thanks to offsetting grant aid; cost-benefit calculations show internal rates of return of 26 percent for the marginal students themselves, 16 percent for society (which must pay for the additional education), and 7 percent for the government budget. Earnings gains are similar across admitting institutions of varying selectivity, but smaller for students from low-income families, who spend more time enrolled but complete fewer degrees and major in less lucrative fields. Finally, I develop a method to separately identify effects for students on the extensive margin of attending any university versus those on the margin of attending a more selective one, revealing larger effects on the extensive margin.

> Is the marginal American college student a good investment?

> Turning to earnings impacts, I first show that marginal admission causes no change in the likelihood of appearing in the Texas earnings data, assuaging concerns about differential attrition (Foote and Stange, 2022). I then trace out the earnings trajectories of cutoff compliers using several different measures, all yielding a consistent pattern of dynamic effects. Initially, admitted compliers earn less their rejected counterparts, as they are much more likely to be actively enrolled in a four-year program. Year six after application is the crossover age, at which point most of the admitted compliers have finished their college education, entered the workforce full-time, and just started to outearn their rejected counterparts. A statistically and economically substantive earnings premium of 8 percent starts to solidify around eight years out from application and persists thereafter. In terms of ranks, the typical rejected complier ends up around the 50th percentile of their cohort earnings distribution, with admission boosting that rank by 4 percentiles.

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
