# Jul 25

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

Thanks to EI, KW, and VAC for flagging contributions this week.

While the awful Columbia news is hard to miss there are few under the radar pieces here worth paying attention to: a manifesto from the Manhattan Institute and a piece from the Chronicle on how this institute and others have plotted to take down the president at George Mason detailing the game plan. This

## Testimony on the hill

* NYT’s podcast The Daily speaks to how all these so-called antisemitism hearings singling out college presidents are part of Project 2025’s plan to discredit higher education

[https://www.nytimes.com/2025/07/16/podcasts/the-daily/project-esther-antisemitism-heritage-foundation.html](https://www.nytimes.com/2025/07/16/podcasts/the-daily/project-esther-antisemitism-heritage-foundation.html)

(Thanks KW)

* Four CUNY professors say they were fired for supporting Palestine

[https://theintercept.com/2025/07/15/cuny-professors-fired-palestine/](https://theintercept.com/2025/07/15/cuny-professors-fired-palestine/)

(reprinted here)

[https://arabamericannews.com/2025/07/18/four-cuny-professors-say-they-were-fired-for-supporting-palestine/](https://arabamericannews.com/2025/07/18/four-cuny-professors-say-they-were-fired-for-supporting-palestine/)

> At Tuesday’s hearing, Stefanik launched baseless attacks on other CUNY faculty members. She pushed for disciplining law professor Ramzi Kassem on the grounds that he represented Mahmoud Khalil, and Saly Abd Alla, the university’s chief diversity officer, over her past work as a civil rights director for the Council on American-Islamic Relations in Minnesota.

> “Does it concern you that New York taxpayers are paying for the legal defense fund of Mahmoud Khalil?” she asked Matos Rodríguez.

> Matos Rodríguez said he was not familiar with those individual employees, but stressed that any employee who violates CUNY’s rules will be investigated. He said CUNY had no complaints related to Abd Alla and that she is not directly involved with handling cases related to students and faculty.

> Pro-Palestinian protesters repeatedly interrupted the hearing. As Matos Rodríguez spoke, one person yelled, “Israel is burning children alive.” Later in the hearing, another protester also shouted to disrupt Matos Rodríguez’s remarks, prompting Rep. Randy Fine (R-Fla.) to say, “Shut up and get out of here… get out of here you loser.”

> Rep. Alma Adams (D-N.C.) relayed to the chancellor CUNY faculty members’ concerns about professors who were not reappointed despite having fully enrolled classes scheduled for the fall. “As a former professor myself and a department chair — somebody who believes deeply in transparency and fairness — I want to ask you: would you be willing to follow up with my office and provide more information on the policies and procedures that guide faculty appointments and reappointments at CUNY?” she asked. Matos Rodríguez said he was willing to cooperate fully with the committee.

> “These hearings are political theater. That’s all they are,” said David Cole, a Georgetown Law professor who testified in his capacity as an expert on the First Amendment at an earlier hearing in May. “It almost doesn’t matter what the university presidents say… there is no effort to even determine what the truth is, what actually happened, or whether any legal lines have been crossed.”

* CUNY’s Repression of Pro-Palestine Students Continues in Front of Congress

[https://www.thenation.com/article/politics/cuny-house-republicans-hearing-repression/](https://www.thenation.com/article/politics/cuny-house-republicans-hearing-repression/)

> The Professional Staff Congress—CUNY’s staff and faculty union—and many from the greater CUNY community are saying the hearing by House Republicans was really meant to silence CUNY’s advocates for Palestinian human rights. Matos-Rodriguez, they argue, failed to defend those community members, as well as the tenets of free speech and robust, open conversation that are critical components of a thriving academic institution. “It was an egregious abdication of his responsibility as an academic and his responsibility as a leader of an academic institution,” said Heba Gowayed, an associate professor of sociology at Hunter College.

* Stefanik’s latest battle doesn’t fight antisemitism; it attacks due process

[https://thehill.com/opinion/education/5409278-elise-stefanik-targets-cuny-clear/](https://thehill.com/opinion/education/5409278-elise-stefanik-targets-cuny-clear/)

> Stefanik’s latest target has been a legal clinic at the City University of New York School of Law, called CUNY CLEAR, an acronym for Creating Law Enforcement Accountability and Responsibility.

> Whatever the merits of Stefanik’s other accusations, she is absolutely wrong about CUNY CLEAR. Representation of a controversial client is in the best tradition of legal education.

> Outraged that CUNY CLEAR had played a key role in Khalil’s representation, Stefanik called upon Rodriguez to fire the CUNY professor who coordinated the defense.

> Rodriguez was non-committal, promising only to investigate the situation. That was the tactful response, but he missed a teachable moment.

> Although that may never be acceptable to Stefanik, Rodriguez should have explained that representing unpopular clients is what lawyers are supposed to do, and what law students should be taught to do.

> I [Steven Lubet, opinion contributor] agree with almost nothing Khalil stands for, but I believe strongly in due process and fair trials. There is no right to appointed counsel in immigration cases, so Khalil’s representation could only come from organizations such as the ACLU and CLEAR.

## Letters

* NYS AAUP sends letter to BC President

> Dear President Anderson,

> We are writing to express concern about the recent firing and non-renewals of four Brooklyn College adjunct faculty members, recently addressed in statements by the Professional Staff Congress-CUNY and CUNY University Faculty Senate leadership.

> While the Brooklyn College administration and the CUNY Board of Trustees have the power of review and final decision, faculty have primacy in academic decision-making, including matters of faculty status. This principle is clearly established in the 1940 Statement on Government of Colleges and Universities, jointly formulated by the American Association of University Professors, the American Council on Education (ACE), and the Association of Governing Boards of Universities and Colleges (AGB).

> According to the 1940 Statement faculty have primary responsibility in decisions related to: “appointments, reappointments, decisions not to reappoint, promotions, the granting of tenure, and dismissal….The governing board and president should, on questions of faculty status, as in other matters where the faculty has primary responsibility, concur with the faculty judgment except in rare instances and for compelling reasons which should be stated in

> We appreciate this is an ongoing personnel matter and wish to respect the privacy of the faculty members involved. However, it appears that neither these individuals nor the departments that recommended their renewal for the coming academic year have been informed of the reasons for their dismissal or non-renewal. Without stated reasons, faculty cannot effectively respond to the administration, as required by AAUP standards of shared governance.

> If the Brooklyn College administration has not already done so, we encourage you to clearly communicate the reasons for the non-renewals and firing for cause to the individual faculty members and their departments as well as to allow them the opportunity to respond following Brooklyn College governance procedures.

This letter references one sent by the UFS XC and co-chairs of the UFS AF committee:

> Dear President Anderson,

> The University Faculty Senate Executive Committee has been notified of potential academic freedom issues on your campus. It has been reported to us that four adjunct faculty were not reappointed after receiving recommendations from their respective departments and chairpersons. We would hope that the reports of non-reappointment are due to extracurricular political expressions are not the case.

> While the UFS does not represent any faculty in contract compliance manners, we do defend academic freedom vigorously. In particular, we take the lead of the AAUP which in 2018 reaffirmed "That there should be no invidious distinction between those who teach and/or conduct research in higher education, regardless of whether they hold full-time or part-time appointments or whether their appointments are tenured, tenure-track, or contingent. All faculty members should have access to the same due-process protections and procedures."

> Further, we follow the AAUP statement on governance where it states, "The governing board and president should, on questions of faculty status, as in other matters where the faculty have primary responsibility, concur with the faculty judgment except in rare instances and for compelling reasons which should be stated in detail."


* NYTimes: Hundreds of NASA Employees, Past and Present, Sign Letter of Formal Dissent

[https://www.nytimes.com/2025/07/21/science/nasa-formal-dissent-letter-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/21/science/nasa-formal-dissent-letter-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> A public letter from NASA employees on Monday urges leaders of the space agency not to carry out deep cuts sought by the Trump administration.

[https://static01.nyt.com/newsgraphics/documenttools/06e6b87deb245d66/67ef9b90-full.pdf](https://static01.nyt.com/newsgraphics/documenttools/06e6b87deb245d66/67ef9b90-full.pdf)

> “We are compelled to speak up when our leadership prioritizes political momentum over human safety, scientific advancement and efficient use of public resources,” the employees wrote in the letter. It is addressed to Sean Duffy, the secretary of transportation, whom President Trump appointed this month as acting NASA administrator.

> The NASA letter follows similar letters of criticism by federal employees at the National Institutes of Health and the Environmental Protection Agency. Dr. Jay Bhattacharya, the N.I.H. director, said he welcomed respectful dissent, but the E.P.A. placed 144 employees who signed that agency’s letter on leave.

## Statements

* Science and Democracy Under Siege | Union of Concerned Scientists

[https://www.ucs.org/resources/science-and-democracy-under-siege](https://www.ucs.org/resources/science-and-democracy-under-siege)

> The first six months of President Trump’s second term have been characterized by destruction of democratic processes, divisive and vindictive actions, and chaos in federal government agencies.

> Since the Inauguration, the administration has systematically destroyed federal scientific systems. The Trump administration’s actions are not normal. This is an illegal power grab—a wholesale attack on the democratic systems upon which this nation was built.

> Between January 20 and June 30 of this year, we documented 402 attacks on science.

(Executive summary)

[https://www.ucs.org/sites/default/files/2025-07/6-Months-Trump-summary.pdf](https://www.ucs.org/sites/default/files/2025-07/6-Months-Trump-summary.pdf)

(The report has charts on Extreme Rise in Documented Attacks on Science; Staff Cuts in Science Agencies; Steep Decline in New Research Grants Awarded by the National Institutes of Health; Industrial Facilities Eligible for Air Pollution Regulation Exemptions; Disruptions and Terminations of Federal Advisory Committees at Science Agencies; Removal of Government Webpages and Information Related to Climate Change and Environmental Justice; Major Trump Administration Attacks on Climate and Clean Energy Policies and Investments. Off to read the whole thing)

## Op eds

* The Dangers of the Manhattan Statement

[https://www.insidehighered.com/opinion/columns/debatable-ideas/2025/07/22/dangers-manhattan-statement](https://www.insidehighered.com/opinion/columns/debatable-ideas/2025/07/22/dangers-manhattan-statement)

> Something that caught my eye last week was news of a statement calling for even more government control over higher education from a group of conservatives. This comes as the right fully embraces Donald Trump’s authoritarian commands against universities. Developed by Christopher Rufo of the Manhattan Institute, the Manhattan Statement was carefully designed using public polling to create vague, popular-sounding principles (“truth” “freedom of speech” “equality” “civil discourse” “transparency”) that obscure its plan for massive federal control over colleges and repression of dissent.

> The Manhattan Statement is a recipe for tyranny. Even if some people might agree with its goals, what’s important are not the ends but the repressive means used to achieve them. It calls for “a new contract with the universities, which should be written into every grant, payment, loan, eligibility, and accreditation, and punishable by revocation of all public benefit.” We’ve already seen how the Trump regime has terribly, illicitly abused its power over government contracts to punish colleges without due process. The Manhattan Statement would vastly expand this power to include all federal funding and student loans, making every college held hostage for its existence to any demands of the government.

> Instead of pretending that “antisemitism” somehow justified cutting off federal funds in direct defiance of the due process required under Title VI, the Manhattan Statement would provide a wide array of reasons for political ideologues to destroy a college, with its amorphous calls to abolish “ideology” and “activism” and require “swift expulsion” of anyone deemed to violate “civil discourse.”

> In recent years, many conservatives have abandoned their past commitments to free speech and the rejection of federal control over academia. ... It’s disturbing to see so many thoughtful conservatives that I respect joining a call for massive expansion of government control over colleges.

> One of the signers, Representative Virginia Foxx (R-NC), is a member (and former chair) of the House Committee on Education and the Workforce, a sign that the Manhattan Statement is not some theoretical wish list aimed at reforming universities, but a very real political threat that could easily be enforced on colleges in the near future.

> However, even terrible legislation is too slow a process for these conservatives, who write that “we call on the President of the United States to draft a new contract with the universities” with these extraordinary requirements.

> To legitimize government intrusion, the Manhattan Statement invents pure historical fiction

(Well, I'd quote the whole thing, but I'll stop here)

> What the Manhattan Statement claims to be the problem—“a new kind of tyranny—one in which ideology determines truth, and the university functions as a political agent …”—is, in fact, the perfect description of Rufo’s solution. He’s simply taking a deluded fantasy of left-wing tyranny on campus as a justification to impose a very real proposal for right-wing tyranny.

* NYTimes: I Watched It Happen in Hungary. Now It’s Happening Here.

[https://www.nytimes.com/2025/07/23/opinion/hungary-viktor-orban.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/23/opinion/hungary-viktor-orban.html?smid=nytcore-ios-share&referringSource=articleShare)

> After years watching Hungary suffocate under the weight of its democratic collapse, I came to understand that the real danger of a strongman isn’t his tactics; it’s how others, especially those with power, justify their acquiescence.

> Hungarians with little power or privilege to lose would occasionally protest. But those with power remained reliably, pliably silent.

> The American officials and academics who, like me, lived in Hungary during this period would often tell ourselves stories to explain this submissiveness: that docility is rooted in Hungary’s oppressive Communist past, that its democracy was simply too young to withstand a strongman.

> Then I returned to the United States, and what I’ve witnessed over these past months at home has exposed those stories as wishful thinking.

> Here, too, powerful people are responding to authoritarian advances just as their Hungarian counterparts have — not with defiance, but with capitulation, convinced that they can maintain their independence and stay above the fray.

> The lesson of Hungary is this: We cannot claim to care about democracy only when it costs nothing. President Trump, like Mr. Orban, no doubt believes that everyone can be bought. America’s elites are proving him right. There is a Hungarian phrase I heard often: “Van az a penz” — “There’s always a price.”



## Shared governance

* Report: Faculty Often Missing From University Decisions on AI

[https://www.insidehighered.com/news/faculty-issues/shared-governance/2025/07/22/faculty-often-missing-university-decisions-ai](https://www.insidehighered.com/news/faculty-issues/shared-governance/2025/07/22/faculty-often-missing-university-decisions-ai)

(Thanks VAC)

> The findings come more than a year after a group of practitioners and researchers wrote the AI Bill of Rights for Educators, which included a call for faculty agency in making choices about “whether, when, and how to use AI based on learning goals, student populations/learning contexts and pedagogical judgment.” But the AAUP’s survey suggests that most colleges and universities aren’t upholding that tenet of AI governance.

[https://engageai.org/wp-content/uploads/sites/125/2025/04/An-AI-Bill-of-Rights-for-Educators-Revision-2025.03.28-2.pdf](https://engageai.org/wp-content/uploads/sites/125/2025/04/An-AI-Bill-of-Rights-for-Educators-Revision-2025.03.28-2.pdf)

> “Many colleges and universities currently have no meaningful shared governance mechanisms around technology,” read the AAUP’s report. “[T]he explosion of AI has highlighted the need for such mechanisms among faculty members at individual institutions and across the higher education workforce.”

> “People are terrified of the onslaught of uncritical AI narratives and partnerships across many sectors, and what it means for the future,” Britt Paris, co-author of the report and associate professor of library and information science at Rutgers University, said in an email to Inside Higher Ed. “But in talking with higher education workers across the country, we on the committee have seen that AI in higher education is barely even functional and tech companies view higher education as a cash cow to exploit.”

> To avoid some of those potential downsides, the report recommended that universities gather input from faculty, staff and students before making deals with tech companies—and write liability clauses into the contracts they do procure. It also called for institutions to give faculty members, staff and students the right to opt-out of technology use without negatively affecting their working or learning conditions, as well as allowing faculty to challenge the implementation of certain ed tech products if the benefit isn’t clear.


## Freedom of expression

* College Employees in Kansas Can’t List Pronouns in Emails

[https://www.insidehighered.com/news/diversity/sex-gender/2025/07/24/kansas-colleges-say-employees-cant-list-pronouns-emails](https://www.insidehighered.com/news/diversity/sex-gender/2025/07/24/kansas-colleges-say-employees-cant-list-pronouns-emails)

> Kansas public university leaders have ordered employees to remove “gender-identifying pronouns or gender ideology” from their email signatures. The officials say they’re complying with new state prohibitions against diversity, equity and inclusion.

> SB 125 also specifically requires the secretary to certify that agencies have “removed gender identifying pronouns or gender ideology from email signature blocks on state employee’s [sic] email accounts and any other form of communication.” The law doesn’t define DEI or gender ideology.

> Ross Marchand, program counsel at the Foundation for Individual Rights and Expression, told Inside Higher Ed the new Kansas law is unconstitutional.

> On Tuesday, the University of Kansas’s chancellor, provost and chief health sciences officer wrote to KU’s campuses that “all employees shall comply with this directive by removing gender-identifying pronouns and personal pronoun series from their KU email signature blocks, webpages and Zoom/Teams screen IDs, and any other form of university communications.”

> The leaders also warned against efforts to circumvent the ban. “Your KU email account is your only official means for sending emails related to your employment at the university,” they wrote. “Do not use an alternate third-party service, such as Gmail, to conduct university business or communications.”

### Anti-woke/anti-DEI is simply racism

* The Manhattan Statement on Higher Education

[https://manhattan.institute/article/the-manhattan-statement-on-higher-education](https://manhattan.institute/article/the-manhattan-statement-on-higher-education)

(If others didn't take them seriously, there would be no reason to read this. A sampling of their "facts" follows)

> The universities have capitulated to the radical Left’s “long march through the institutions,” which has converted them into laboratories of ideology, rather than institutions oriented toward truth.

> The universities have built enormous “diversity, equity, and inclusion” bureaucracies that discriminate on the basis of race and violate the fundamental principle of equality—that high prize which was inscribed in the Declaration of Independence and codified into law with the Fourteenth Amendment and the Civil Rights Act.

> The universities have contributed to a new kind of tyranny, with publicly funded initiatives designed to advance the cause of digital censorship, public health lockdowns, child sex-trait modification, race-based redistribution, and other infringements on America’s long-standing rights and liberties.

> The universities have corrupted faculty hiring practices with racial quotas, ideological filters, and diversity statements, which function as loyalty oaths to the Left and have virtually eliminated conservative scholars from the prestige institutions.

> The universities have degraded the liberal arts with reductive ideologies that no longer aim to preserve and discover what is highest in man, but to unleash resentments against Western civilization, from the Greeks and Romans, to the English and the Americans.

(The chaser)

> To that end, we call on the President of the United States to draft a new contract with the universities, which should be written into every grant, payment, loan, eligibility, and accreditation, and punishable by revocation of all public benefit:

(These include)

> The universities must uphold the highest standard of civil discourse, with swift and significant penalties, including suspension and expulsion, for anyone who would disrupt speakers, vandalize property, occupy buildings, call for violence, or interrupt the operations of the university.

> The universities must provide transparency about their operations and, at the end of each year, publish complete data on race, admissions, and class rank; employment and financial returns by major; and campus attitudes on ideology, free speech, and civil discourse.



## Visas

* This new $250 visa fee applies to international student visas too.

[https://www.cnbc.com/2025/07/18/visa-integrity-fee-what-to-know-about-new-travel-fee-to-enter-the-us-.html](https://www.cnbc.com/2025/07/18/visa-integrity-fee-what-to-know-about-new-travel-fee-to-enter-the-us-.html)

(Thanks JC)

> The fee will be at least $250 during the U.S. fiscal year 2025, which runs from Oct. 1, 2024, to Sept. 30, 2025. However, the secretary of Homeland Security is free to set the fee higher, according to the provision.

* A Trial Over Campus Protest Ends with Conflicting Views of Foreign Students’ Free-Speech Rights

[https://www.chronicle.com/article/a-trial-over-campus-protest-ends-with-conflicting-views-of-foreign-students-free-speech-rights](https://www.chronicle.com/article/a-trial-over-campus-protest-ends-with-conflicting-views-of-foreign-students-free-speech-rights)

> Government lawyers dismissed allegations of an ideologically motivated campaign to detain and deport campus protesters on Monday, comparing assertions that the Trump administration curtailed the free-speech rights of noncitizens to the fictional character Don Quixote.

> Plaintiffs, including the American Association of University Professors and the Middle East Studies Association, argue that the March arrests of pro-Palestinian activists on student visas and green cards led other international students and scholars to think twice about speaking out on controversial issues. Academics testified that they had rewritten syllabi, withdrawn op-eds, and canceled research trips out of fear that they, too, could face retribution for expressing political opinions.

> “The goal is to chill speech, to silence students and scholars who wish to express pro-Palestinian views,” Alexandra Conlon, a lawyer for the academic groups, said during closing arguments. “It is stifling dissent.”

> But Ethan B. Kanter, another lawyer representing the Trump administration, countered that noncitizens’ speech rights are “context dependent.” As an example, he pointed to federal campaign-finance law, which prohibits donations from foreign nationals. The U.S. Supreme Court has ruled that campaign spending is protected speech under the First Amendment. The campaign restrictions underscore that “not in every instance” do noncitizens have “equivalent rights,” Kanter said.

> Armstrong was questioned in particular about Rümeysa Öztürk, a Tufts University graduate student whose visa revocation he directly approved. He said an op-ed critical of Israel that she co-authored was “not a key factor” in his decision. Yet the article was the only specific support he provided as evidence of her “activity and association” with Students for Justice in Palestine...Armstrong also testified that he did not recall being given “any concrete guidance” about what constitutes antisemitism, and he said did not know of formal training given to other State Department officials who reviewed protesters’ cases.

> Armstrong was part of at least 20 conversations with officials in the White House, Department of Homeland Security, and other agencies, including with Stephen Miller, deputy White House chief of staff and the president’s top adviser on immigration.

* NYTimes: Trump’s Student Arrests, and the Lawsuit Fighting Them, Tread New Ground

[https://www.nytimes.com/2025/07/22/us/politics/trump-student-arrests-immigration-trial.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/22/us/politics/trump-student-arrests-immigration-trial.html?smid=nytcore-ios-share&referringSource=articleShare)

> The four veteran immigration agents who recently took the stand in federal court had at least two things in common. All were career law enforcement officials. And none could remember ever being asked to make arrests like the ones they carried out earlier this year.

> The men said they acted on orders handed down from Secretary of State Marco Rubio’s office in March to detain several noncitizen students, including a doctoral student from Tufts University whose arrest was captured on video and garnered significant attention. Mr. Rubio had abruptly revoked their legal status, which cleared them for detention by immigration agents, citing a rarely used law.

* NYTimes: State Dept. Opens Investigation Into Harvard’s Use of International Visas

[https://www.nytimes.com/2025/07/23/us/politics/state-department-trump-harvard.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/23/us/politics/state-department-trump-harvard.html?smid=nytcore-ios-share&referringSource=articleShare)

## Funding cuts

* Inside the powerful task force spearheading Trump’s assault on colleges, DEI

[https://www.washingtonpost.com/education/2025/07/18/antisemitism-task-force-dei-universities-trump/](https://www.washingtonpost.com/education/2025/07/18/antisemitism-task-force-dei-universities-trump/)

> The administration established the task force in February to counter what it describes as widespread failure by universities to protect Jewish students since the start of campus protests against the Israel-Gaza war. In reality, many of the task force’s unprecedented demands and punishments have nothing to do with antisemitism. Instead, they seek hiring and programming changes to strip long-standing conservative targets including DEI and a liberal worldview from higher education.

> “It’s self-evident it’s not about antisemitism,” said Yehuda Kurtzer, president of the Shalom Hartman Institute, a Jerusalem-based research and educational center focused on world Jewish life and pluralism. “Why would that have anything to do with cutting funding for research? It’s about conservative fears of higher education, and antisemitism is an excuse.”

> The work — which at times has ignored legal norms and procedures — is driven by the task force, made up of senior officials in the Justice, Education, and Health and Human Services departments, as well as the little-known General Services Administration. Since almost the start of Trump’s second term, they have invoked both antisemitism and DEI in a quest to transform the culture of campuses and stamp out what many Republicans see as outright hostility to conservative values, discourse and thought.

> One task force member said it makes sense to create a “global settlement” with universities that would encompass a range of alleged violations. Task force investigations sometimes start out examining allegations of antisemitism, this person said, but then identify what members see as other concerns, such as race-conscious admissions, which the Supreme Court has ruled are unconstitutional.

> To push colleges to comply, the administration has frozen billions of dollars in federal funding to at least six highly selective universities — notably Harvard and Columbia, which have seen the highest-profile federal cuts — but also Cornell, Northwestern, Brown and Princeton.

> One targeted school, Brown University, said its funding was cut without “any formal notification or explanation” from the federal government and “in spite of Brown’s cooperation with multiple government reviews and our compliance with the law.”

> The public face is Leo Terrell ... Terrell posts on social media throughout the day, echoing some of the right’s most incendiary and baseless claims. He also rails against diversity, equity and inclusion, often simply posting “I hate DEI” and tagging people of color with whom he disagrees as DEI hires. ... He’s also echoed antisemitic comments...Multiple people said Terrell has little experience in the type of legal work the task force is undertaking and is not involved in its day-to-day legal strategy.

> Much of the task force’s work is being shepherded by lower-profile senior administration officials: Tom Wheeler and Sean Keveney, the acting general counsels of the departments of Education and Health and Human Services, and Gruenbaum from the General Services...Harmeet Dhillon directly oversees the group’s work...Dhillon and her political team scour social media to identify instances of antisemitism and determine what investigations to launch.

> The legal basis for the crackdown on universities centers on Title VI of the Civil Rights Act, which prohibits discrimination on the basis of race, color or national origin in programs or activities — including universities — that receive federal funding.  ... Under the law, she said, “withdrawal of federal funds is treated as a last resort action.” ... In several high-profile cases, the Trump task force has skipped all these steps.

* NYTimes: Fired D.E.I. Administrator Sues the University of Michigan

[https://www.nytimes.com/2025/07/17/us/university-michigan-lawsuit-dei-firing-rachel-dawson.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/17/us/university-michigan-lawsuit-dei-firing-rachel-dawson.html?smid=nytcore-ios-share&referringSource=articleShare)

> In her lawsuit, filed on Monday in the U.S. District Court for the Eastern District of Michigan, Ms. Dawson painted a starkly different version of events. And she said that there was racial bias in what she called the unusual process that the public university used to investigate the complaint and in its decision to side with her accusers.

> “Historically, Black women have been subjected to stereotypes that portray them as confrontational or untrustworthy,” Ms. Dawson wrote during a disciplinary review, according to her lawsuit.

> In her lawsuit, Ms. Dawson said she was approached in March 2024 at an American Association of Colleges and Universities diversity conference by the two professors who accused the University of Michigan of fostering an antisemitic climate. Ms. Dawson’s suit says she disagreed with the women and explained the university’s efforts to combat antisemitism, including the creation of a center for that purpose. The women, the suit says, asked if she believed Palestinians had a right to live in the region of the Israeli-Palestinian conflict. She said she did, according to the suit. “This apparently infuriated the two women,” the lawsuit says. “They were so angry that they followed Ms. Dawson out of the room and refused to let her exit the conversation.”

### NSF

* Congress Shows Resistance to Trump’s Plan to Slash Science Budgets

[https://www.insidehighered.com/news/government/science-research-policy/2025/07/21/congress-shows-resistance-trumps-science-budget](https://www.insidehighered.com/news/government/science-research-policy/2025/07/21/congress-shows-resistance-trumps-science-budget)

> Congress’s proposed budgets would preserve more research spending than the president’s. It’s a rare rebuke from Republicans to the White House’s efforts to gut funding for several research support agencies.

> In a July 10 Senate Appropriations Committee meeting, legislators put forth a cut to the National Science Foundation (NSF) of only $16 million compared to the more than $5 billion proposed by Trump. Four days later, a House Appropriations Committee subcommittee suggested slashing $2 billion—less than half of Trump’s proposal.

> He [Roger Pielke, AEI] said the NSF, which focuses on basic research, may be more insulated from political fights than agencies such as the National Oceanic and Atmospheric Administration, which deals with climate science, and the National Institutes of Health, which deals with vaccines. The congressional appropriations committees haven’t yet indicated what they plan to do with Trump’s proposed 38 percent cut to the NIH.

(also)

[https://www.chronicle.com/article/trump-proposed-slashing-the-national-science-foundations-budget-a-key-senate-committee-just-refused](https://www.chronicle.com/article/trump-proposed-slashing-the-national-science-foundations-budget-a-key-senate-committee-just-refused)

> The Senate Committee on Appropriations voted 19-10 on Thursday to keep funding for the National Science Foundation and other federal science agencies nearly intact for the 2026 fiscal year.

* Federal Grant Cuts Don’t Spare Red States, New Report Shows

[https://www.insidehighered.com/news/faculty-issues/research/2025/07/23/feds-axed-grants-across-red-blue-states-report-finds](https://www.insidehighered.com/news/faculty-issues/research/2025/07/23/feds-axed-grants-across-red-blue-states-report-finds)

(Thanks VAC)

> The Trump administration’s cancellation of federal funds for highly selective universities in blue states has drawn national media attention. But a new report from a left-leaning think tank stresses that the federal government isn’t targeting only Harvard and Columbia’s research and innovation grants.

> “Republican- and Democrat-governed states are facing similar impacts relative to their student populations in terms of funding terminated by the administration,” says the Center for American Progress’s report, released today. And no institution is safe, CAP notes.

> “Institutions affected by grant terminations range from some of the country’s largest public universities to private research universities, small liberal arts colleges, and community colleges,” the report says. Land-grant universities and historically Black colleges and universities “have been particularly affected, with more than two-thirds of all land-grant universities and nearly half of all HBCUs targeted for funding terminations.”

### DOE

* Federal investigations target college aid to immigrants and minorities - The Washington Post

[https://www.washingtonpost.com/education/2025/07/23/college-scholarships-investigation-immigrants-minorities/](https://www.washingtonpost.com/education/2025/07/23/college-scholarships-investigation-immigrants-minorities/)

> The inquiry will examine complaints from the conservative Equal Protection Project that the schools engaged in discrimination by allegedly showing a preference for foreign-born students. The schools named in the complaint are the University of Louisville, the University of Nebraska Omaha, the University of Miami, the University of Michigan and Western Michigan University.

> Most of the scholarships in question offer financial support for either undocumented students or those covered by the Deferred Action for Childhood Arrivals, or DACA, program. Neither group is eligible to receive federal grants or loans to attend college, making institutional, state and private grants critical for their ability to access higher education.

> Conservative activists and Republican state leaders have pushed colleges to abandon scholarships earmarked for underrepresented groups, arguing that the same principles underlying the Supreme Court’s ban on colleges considering an applicant’s race as a factor in admissions apply to financial aid.

> The Equal Protection Project, led by Cornell University clinical law professor William Jacobson, has been at the forefront of that movement by filing dozens of complaints against race-conscious scholarships with the Office for Civil Rights. The group has expanded its effort by taking a look at institutional aid provided to foreign-born students.


## Institutional assaults

### Accreditation

* He Helped Lead a Disgraced College Accreditor. Under Trump, He Might Have Another Shot.

[https://www.chronicle.com/article/he-helped-lead-a-disgraced-college-accreditor-under-trump-he-might-have-another-shot](https://www.chronicle.com/article/he-helped-lead-a-disgraced-college-accreditor-under-trump-he-might-have-another-shot)

> A decade ago, over 200 college campuses shuttered in a two-year period, leaving thousands of students in the lurch. ... In 2022, the organization that accredited many of the campuses run by those companies — the Accrediting Council for Independent Colleges and Schools, or ACICS — was effectively shut down by the U.S. Department of Education for not responding to the concerns. The department’s withdrawal of its recognition ended a battle spanning three U.S. presidencies.

> But in higher education as in politics, there’s often déjà vu. Anthony Bieda, a longtime ACICS executive, is back in the accreditation game at a pivotal point in the federal recalibrating of higher ed.

> Bieda is hoping to help shake up the sector with what he described to The Chronicle as a holistic, AI-assisted, anti-woke approach to measuring student success through the National Association for Academic Excellence, or NAAE. He sees metrics like post-graduate earnings as limiting. Instead, the NAAE member institutions will be evaluated based on how their education influences the “formation of the human person.”

> Still, disrupting the accreditation system requires contending with a web of regulations and yearslong processes. And for Bieda’s NAAE to enter the marketplace, colleges will have to buy what it’s selling.

> The Obama administration initially pulled recognition of ACICS in 2016; the Trump administration reinstated it in 2018 after a favorable court ruling. Then, in 2020, a USA Today investigation found that ACICS had accredited a university that was little more than an empty office, with no evidence of enrolled students or employed faculty. In 2021, the Biden administration went after ACICS again; in 2022, the Education Department rejected the accreditor’s appeal and revoked its recognition, this time for good.

### Harvard

* Trump vs. Harvard: A timeline of how the fight escalated

[https://www.washingtonpost.com/education/interactive/2025/timeline-trump-harvard/](https://www.washingtonpost.com/education/interactive/2025/timeline-trump-harvard/)

> The Trump administration’s battle with Harvard University will be aired in court Monday, when a federal judge will hear arguments in the school’s lawsuit challenging the government’s attack on its federal research funding.

> Jan. 9, 2025: Justice Department pick signals focus on Harvard

> Feb. 3: Trump administration alleges antisemitic incidents at university graduations; Trump administration announces formation of its antisemitism task force;
> March 8: Trump task force chair says universities have been ‘hijacked’ by leftists

> March 10: Trump administration investigates 60 schools for alleged antisemitism

> March 31: More than $8.7 billion in funding to Harvard is put under review

(etc.)

* NYTimes: Trump Administration and Harvard Face Crucial Court Test

[https://www.nytimes.com/2025/07/21/us/trump-administration-harvard-hearing.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/21/us/trump-administration-harvard-hearing.html?smid=nytcore-ios-share&referringSource=articleShare)

> Both Harvard and the government are asking Judge Allison D. Burroughs for summary judgment — a ruling that would decide the lawsuit, at least in Judge Burroughs’s court, without a trial.

> Harvard will argue on Monday that the Trump administration is trying to curb its First Amendment rights. Judge Burroughs sided with the university in another significant case, when she ruled on several interim matters related to the government’s effort to block the school from enrolling international students.

> The university’s lawyers argued in a court filing last month that the government’s tactics amounted to “unconstitutional retaliation against Harvard for exercising its First Amendment rights to decide what to teach, to express certain views and to petition the courts to defend itself.”

> Harvard also said that the Trump administration’s hurried approach to cutting funding defied federal law and regulations, and its actions were “arbitrary and capricious.” The school has argued that the government’s decision to cancel funding across disciplines has little connection to the problems it wants to address, including antisemitism.

*Judge Challenges Trump Administration in Hearing on Harvard Funding - The New York Times

[https://www.nytimes.com/2025/07/21/us/trump-administration-harvard-hearing.html](https://www.nytimes.com/2025/07/21/us/trump-administration-harvard-hearing.html)

> In a courtroom in Boston on Monday, a lawyer for Harvard called the Trump administration’s case against the school “cooked up.”

> A federal judge appeared deeply skeptical on Monday of the Trump administration’s efforts to strip Harvard University of billions of dollars in research funding, suggesting the school might prevail in its legal battle against the government.

> Judge Allison D. Burroughs did not issue a ruling during a crucial hearing, which lasted more than two hours in her courtroom in Boston. But she did seem receptive to Harvard’s arguments, as both the school and the government sought to have the case decided in their favor without a trial.

> “You’re saying you can terminate a contract for any and all reasons, even if the reason you’re giving is a violation of the Constitution?” Judge Burroughs asked Mr. Velchik [team Govt] at one point, her doubts made clear by her tone. At another moment, she said, “I don’t think you can justify a contract action based on impermissible suppression of speech.”

> Judge Burroughs seemed to share the worries of Mr. Lehotsky, who said the government was pursuing an “anti-Harvard policy" that would be unlawful under any president.

> “What I’m wrestling with is this idea that the executive branch can decide what is discriminatory or racist,” she said, and then make “these ad hoc decisions without any procedure around it.”

> President Trump, in a social media post after the hearing, called Judge Burroughs “a TOTAL DISASTER, which I say even before hearing her Ruling.”

> He also criticized Harvard, and reiterated promises to end its federal funds. “When she rules against us, we will IMMEDIATELY appeal, and WIN,” he wrote of Judge Burroughs. “Also, the Government will stop the practice of giving many Billions of Dollars to Harvard, much of which had been given without explanation.”

(Yeah, right)

(Also)

[https://www.insidehighered.com/news/quick-takes/2025/07/22/judge-appears-skeptical-harvard-funding-cuts](https://www.insidehighered.com/news/quick-takes/2025/07/22/judge-appears-skeptical-harvard-funding-cuts)

(Also)

[https://www.chronicle.com/article/in-a-key-court-showdown-with-harvard-trump-administration-encounters-a-skeptical-judge](https://www.chronicle.com/article/in-a-key-court-showdown-with-harvard-trump-administration-encounters-a-skeptical-judge)

(Also)


[https://www.washingtonpost.com/education/2025/07/21/trump-harvard-hearing/](https://www.washingtonpost.com/education/2025/07/21/trump-harvard-hearing/)

(Also)

[https://www.wsj.com/us-news/education/harvard-trump-court-lawsuit-analysis-6022851b?st=MuZSoj&reflink=article_gmail_share](https://www.wsj.com/us-news/education/harvard-trump-court-lawsuit-analysis-6022851b?st=MuZSoj&reflink=article_gmail_share)

(But the Journal is going to Journal and has)

> Harvard’s odds to win its Boston court battle look favorable—but the larger war is up in the air.

> Legal analysts say Harvard has a strong case in arguing that the U.S. government improperly cut $2.2 billion in federal funding from the Ivy League school. The federal district judge presiding over a key hearing Monday appeared skeptical of the government’s arguments.

> But President Trump is already threatening to appeal. He has many ways to inflict damage on the university meanwhile, and Harvard’s prospects—should the case end up at the Supreme Court—are less clear.

* “Harvard Creates New Public Service Program as Trump Administration Slashes Federal Jobs.”.


[https://www.nytimes.com/2025/07/17/us/harvard-american-service-fellowship-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/17/us/harvard-american-service-fellowship-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

(Thanks VAC)

> Harvard’s Kennedy School of Government announced on Thursday the creation of a new scholarship program that will fully fund master’s degrees for at least 50 students with significant experience in the public sector, including the military. The one-year program, which will enroll students in fall 2026, is intended to foster careers in public service.

> The pilot program, called the American Service Fellowship, comes as the Trump administration is bulldozing the federal work force, including laying off many career public servants. The administration has dismantled U.S.A.I.D., the humanitarian relief agency, and plans to gut the Education Department.



### Columbia

* NYTimes: Columbia Agrees to $200 Million Fine to Settle Fight With Trump

[https://www.nytimes.com/2025/07/23/nyregion/columbia-trump-funding-deal.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/23/nyregion/columbia-trump-funding-deal.html?smid=nytcore-ios-share&referringSource=articleShare)

> Columbia University will pay a $200 million fine to settle allegations from the Trump administration that it failed to do enough to stop the harassment of Jewish students, part of a sweeping deal reached on Wednesday to restore the university’s federal research funding, according to a statement from the university.

> In exchange for the return of hundreds of millions in research grants, Columbia will also pledge to follow laws banning the consideration of race in admissions and hiring, and follow through on other commitments to reduce antisemitism and unrest on campus that it agreed to in March.

> The deal, which settles more than a half-dozen open civil rights investigations into the university, will be overseen by an independent monitor agreed to by both sides who will report to the government on its progress every six months. Columbia will also pay $21 million to settle investigations brought by the U.S. Equal Employment Opportunity Commission.



(Also)

[https://apnews.com/article/columbia-trump-deal-00eef5dca9f003e593d2cb151f5cce17](https://apnews.com/article/columbia-trump-deal-00eef5dca9f003e593d2cb151f5cce17)

[https://www.washingtonpost.com/education/2025/07/23/trump-columbia-university-agreement-federal-funding/](https://www.washingtonpost.com/education/2025/07/23/trump-columbia-university-agreement-federal-funding/)

[https://www.insidehighered.com/news/governance/trustees-regents/2025/07/23/columbia-settles-trump-administration https://www.insidehighered.com/news/governance/trustees-regents/2025/07/23/columbia-settles-trump-administration](https://www.insidehighered.com/news/governance/trustees-regents/2025/07/23/columbia-settles-trump-administration https://www.insidehighered.com/news/governance/trustees-regents/2025/07/23/columbia-settles-trump-administration)

[https://www.politico.com/news/2025/07/23/columbia-university-reaches-a-settlement-with-trump-administration-00473322](https://www.politico.com/news/2025/07/23/columbia-university-reaches-a-settlement-with-trump-administration-00473322)

[https://www.chronicle.com/article/in-extraordinary-deal-with-trump-columbia-u-agrees-to-pay-200-million-to-restore-funds](https://www.chronicle.com/article/in-extraordinary-deal-with-trump-columbia-u-agrees-to-pay-200-million-to-restore-funds)


* Columbia Expels, Suspends Student Protesters

[https://www.insidehighered.com/news/government/politics-elections/2025/07/22/columbia-expels-suspends-student-protesters https://www.insidehighered.com/news/government/politics-elections/2025/07/22/columbia-expels-suspends-student-protesters](https://www.insidehighered.com/news/government/politics-elections/2025/07/22/columbia-expels-suspends-student-protesters https://www.insidehighered.com/news/government/politics-elections/2025/07/22/columbia-expels-suspends-student-protesters)

> “The sanctions issued on July 21 by the University Judicial Board were determined by a UJB panel of professors and administrators who worked diligently over the summer to offer an outcome for each individual based on the findings of their case and prior disciplinary outcomes,” Columbia officials wrote in an unsigned statement. “While the University does not release individual disciplinary results of any student, the sanctions from Butler Library include probation, suspensions (ranging from one year to three years), degree revocations, and expulsions.”

> Officials added that “disruptions to academic activities” are a violation of university policies.

> Though Columbia did not specify how many students were disciplined, the pro-Palestinian student group CU Apartheid Divest alleged that as many as 80 were expelled or suspended. According to CU Apartheid Divest, disciplinary letters sent to suspended students require them to submit apologies in order to return to campus in one to three years.

(Also)

[https://apnews.com/article/campus-protests-columbia-discipline-trump-administration-f009b90113fe0ba7847c54ffc9197bd1](https://apnews.com/article/campus-protests-columbia-discipline-trump-administration-f009b90113fe0ba7847c54ffc9197bd1)

* The University That Chose Surrender: Columbia’s capitulation proves higher ed can’t save itself.

[https://www-chronicle-com.csi.ezproxy.cuny.edu/article/the-university-that-chose-surrender](https://www-chronicle-com.csi.ezproxy.cuny.edu/article/the-university-that-chose-surrender)

> Hudson Whittaker was a Chicago blues musician who performed under the name Tampa Red. One of his finest compositions, entitled “Don’t Deal with the Devil,” opens with the following warning:

> When you dealin’ with the devil
> Everything you do is wrong
> You’ll drive away your lover
> And keep all your things in pawn…
> Don’t deal with the devil, cuz it ain’t no way to win.

> Columbia’s fundamental error was its failure to recognize that from the moment Max Eden of the American Enterprise Institute wrote, last December, that the Department of Education “should simply destroy Columbia University,” it was engaged not in a negotiation but in a war for survival. One would have thought that the futility of its initial capitulation — no restoration of funds followed by a series of further attacks — would have sent a clear signal, but apparently it did not.

> One has only to read the recent “Manhattan Statement on Higher Education” — likely authored by the indefatigable Christopher Rufo and signed by an anti-woke dream team — to see that the right-wing attack on the autonomy of higher education is just getting started and that neither Columbia nor other universities will be spared further damage.

> The Manhattan Statement is purportedly about reform, but its language — “corrupt,” “nihilism,” “tyranny,” — is the language of revolution. It is somehow unsurprising that “child sex-trait modification” manages to find its way into a description of the evils of higher education. Two hundred million dollars will not stop, will barely slow down, the ideologues at the gates.

NYTimes: Columbia’s Administrators Are Fooling Themselves

[https://www.nytimes.com/2025/07/23/opinion/trump-columbia-deal-professor.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/23/opinion/trump-columbia-deal-professor.html?smid=nytcore-ios-share&referringSource=articleShare)

> In economic history, we teach the 1688 creation of parliamentary supremacy as a solution to what economists call “commitment problems.” In the absence of a third party sufficiently strong to make sure all sides stick to their promises, the powerful can renege on the powerless. The powerless, seeing this, wisely choose to not contract with the powerful. Absolutist rulers are victims of their own lack of restraints; a sovereign who is too powerful cannot get inexpensive credit, because nothing stops the ruler from defaulting on any bond. President Trump, by smashing checks on his authority, has wound up undermining his own ability to make credible deals, including the one just reached with Columbia University, where I teach.

> But this deal is unlikely to end the attacks. The federal government, and this administration, is simply too powerful and too arbitrary to be credibly bargained with. Do we really think this arrangement, however destructive of academic autonomy it is, will prevent the Trump administration from stopping the money again? Anyone who thinks the administration will mutely walk away after the ink is dry needs to look at both the past behavior of autocratic regimes in general and this administration’s in particular.

> It is unsurprising that a coalition of election deniers, Christian nationalists and supplement- and crypto-hawkers would have little regard for academic freedom, scientific progress and learning. It was always a stretch for Columbia to think a good-faith agreement was in the cards, but when the government is too often behaving unchecked by the law, the idea of a binding contract is a fantasy.

* Columbia University Settlement an Unprecedented Disaster | AAUP

[https://www.aaup.org/news/columbia-university-settlement-unprecedented-disaster](https://www.aaup.org/news/columbia-university-settlement-unprecedented-disaster)

> The Columbia University Board of Trustees’ concessions to the Trump administration are a disaster for Columbia students, faculty, and staff, as well as for academic freedom, freedom of speech, and the independence of colleges and universities nationwide. Never in the history of our nation has an educational institution so thoroughly bent to the will of an autocrat. The settlement will only fuel Trump’s authoritarian appetite to control other democratic institutions that could potentially rein him in. This settlement subverts our democracy and capitulates to the Trump plan to target the pillars of our democracy: the judiciary, the free press, and our education systems.

> Allowing the government to monitor and ultimately dictate decisions about the hiring of faculty and admission of students is a stunning breach of the independence of colleges and universities and opens the door for the ideological control this administration so eagerly craves. This is an extremely dangerous precedent that will have tremendous consequences for the sector. Trump has already reached into community colleges, public state schools, small liberal arts colleges, and minority serving institutions to limit the free expression of students and workers. The Columbia settlement will embolden the administration to further clamp down throughout higher education.

> An authoritarian bully will not be satisfied with just one trophy at Columbia University. For higher education to function, students, staff, and faculty must be free to think and speak their minds. All who care about higher education must stand up and fight back against this unprecedented continuing assault. To preserve our democracy, we have no choice. --AAUP president Todd Wolfson

* Columbia Deal a ‘Threat’ to Higher Ed, Experts Warn

[https://www.insidehighered.com/news/government/politics-elections/2025/07/25/columbia-settlement-offers-warning-higher-ed](https://www.insidehighered.com/news/government/politics-elections/2025/07/25/columbia-settlement-offers-warning-higher-ed)

> Columbia’s capitulation “represents the upending of a decades-long partnership between the government and higher education in which colleges and universities nevertheless retained academic freedom, institutional autonomy and shared governance,” said Lynn Pasquerella, president of the American Association of Colleges and Universities. “It signals a rise in authoritarian populism in which higher education is positioned as the enemy in a fight against corrupt, inefficient and elite institutions that are out of touch with the needs of the working class.”

> “Whether you applaud or despise the terms of the deal, the way in which the government is operating, and getting universities like Columbia to make these deals is fundamentally coercive,” said David Pozen, a constitutional law professor at Columbia. “Therefore, it poses a significant threat to the future of higher education as well as the rule of law.”

> “The very real danger is that if elite institutions choose to submit to the authority of the Trump administration, the whole rest of the industry will follow,” said Kevin Carey, vice president of education and work at New America, a left-leaning think tank. “It will be like a stack of dominoes one falling after the other.”

> Will Creeley, legal director of the Foundation for Individual Rights and Expression, said that, in addition to admission practices, this settlement and its “blatant disregard for federal law” will upend academia’s core commitment to fostering First Amendment rights.

> Michael Thaddeus, a Columbia math professor and president of the faculty union chapter, said though administrators insist they won’t allow the government to interfere, that assurance doesn’t mean such acts won’t occur. “Students and scholars at American universities must be free to think and speak their minds,” he wrote in a statement to Inside Higher Ed. “The settlement … risks imperiling this freedom.”

> Pozen, the Columbia law professor, outlined in a blog post Wednesday night how the task force bypassed nearly all statutory requirements of such an investigation. ... “The means being used to push through these reforms are as unprincipled as they are unprecedented,” Pozen wrote. “Higher education policy in the United States is now being developed through ad hoc deals, a mode of regulation that is not only inimical to the ideal of the university as a site of critical thinking but also corrosive to the democratic order and to law itself.”

> Kirsten Weld, a history professor and president of the Harvard faculty union chapter, said she is “very concerned” and rejects any suggestion that Columbia’s settlement should be a “blueprint” for her own institution’s negotiations.

> Ted Mitchell, president of the American Council on Education, also suggested via email that “this cannot be a template for the government’s approach to American higher education.” This administration “reached a conclusion before an investigation and levied a penalty without affording Columbia due process—that is chilling,” he wrote. “This administration must return to following the rule of law.”

* What Columbia’s Settlement Stipulates


[https://www.insidehighered.com/news/governance/executive-leadership/2025/07/24/breaking-down-columbia-us-settlement-trump-admin](https://www.insidehighered.com/news/governance/executive-leadership/2025/07/24/breaking-down-columbia-us-settlement-trump-admin)

> Columbia will see at least a partial restoration of federal research funds.

> The agreement will close pending investigations or compliance reviews related to potential violations of Title VI of the Civil Rights Act of 1964, which prohibits discrimination based on race or national origin. That includes a probe by the U.S. Equal Employment Opportunity Commission into the treatment of Jewish employees at Columbia. Of the $221 million settlement, $21 million will go toward the EEOC complaint.

> Columbia will maintain policies announced in March that deem protests inside of academic buildings and related spaces to be a “direct impediment” to the university’s academic mission.

> The agreement codifies changes to disciplinary processes announced in March, such as placing the University Judicial Board under the Office of the Provost who reports to the president. Students previously served on the board, but now, it will be restricted to faculty and staff members.

> Diversity, equity and inclusion initiatives, a frequent target of the Trump administration, are also included in the agreement. The deal bars Columbia from maintaining “programs that promote unlawful efforts to achieve race-based outcomes, quotas, diversity targets, or similar efforts.”

> The agreement emphasizes merit-based admissions and bars Columbia from giving preference to applicants due to “race, color, or national origin.” It also prevents Columbia from using personal statements, diversity narratives or references to race “to introduce or justify discrimination.”

> Maintaining a senior vice provost to provide greater administrative oversight of Middle East studies (and other regional programs), as initially announced in March, is also part of the agreement.

> As part of the deal, a third-party resolution monitor will police the agreement. Bart Schwartz, co-founder of Guidepost Solutions and former Chief of the Criminal Division of the United States Attorney’s Office for the Southern District of New York, will serve in that role.

> The deal also places restrictions on university hiring processes. Columbia’s agreement will bar the use of “personal statements, diversity narratives, or any applicant reference to racial identity as a means to introduce or justify discriminatory practices in hiring or promotion.” Other unspecified “indirect methods or criteria that serve as a substitute for race conscious hiring or promotion practices” are also prohibited per the deal.

> While some elements of the agreement are new, other parts simply codify prior changes. For example, changes to disciplinary processes, and greater administrative oversight of Middle East studies (and other regional programs) already announced in March are now codified in the deal.

* ‘The Best Day Higher Ed Has Had in a Year’ -- Larry Summers

[https://www.chronicle.com/article/the-best-day-higher-ed-has-had-in-a-year](https://www.chronicle.com/article/the-best-day-higher-ed-has-had-in-a-year)

(Why the led with this take, who knows, I couldn't read it.)

* Columbia Struck a Deal to Save Research Funding. How Do Its Researchers Feel About That?

[https://www.chronicle.com/article/columbia-struck-a-deal-to-save-research-funding-how-do-its-researchers-feel-about-that](https://www.chronicle.com/article/columbia-struck-a-deal-to-save-research-funding-how-do-its-researchers-feel-about-that)

(They lead off with:)

> For Gerard Karsenty, chair of the genetics department, the feeling is one of “joy and relief.” “If this is the price to pay for me to be able to work and my students not to go and sell shoes at Walmart, I think I can live with that,” Karsenty said.

> Dixon-Román’s [Director of the Edmund W. Gordon Institute for Urban and Minority Education at the Teachers College] biggest worry about the agreement lies in an assumption that the federal government will act in good faith. “You’re playing with an administration that has shown bad faith in relation to the rule of law, let alone even other agreements.”


* Tucked Into Columbia’s Deal With Trump: A Restriction on International Enrollments

[https://www.chronicle.com/article/tucked-into-columbias-deal-with-trump-a-restriction-on-international-enrollments](https://www.chronicle.com/article/tucked-into-columbias-deal-with-trump-a-restriction-on-international-enrollments)

> The requirement to study its policies for international admissions is among the terms of Columbia’s 22-page agreement with the government. The provision states that university will ask questions about why international students want to study in the United States as part of the admissions process.

> Columbia also consents to making sure that all students, international and domestic, are “committed to the longstanding traditions of American universities,” including free inquiry, open debate, and the “fundamental values” of equality and respect. It will create training materials so that students understand campus norms and values. The Trump administration has repeatedly suggested that international students have been the leaders and provocateurs behind pro-Palestinian protests that rocked Columbia and other campuses.

* What Columbia Just Threw Away

[https://www.chronicle.com/article/what-columbia-just-threw-away](https://www.chronicle.com/article/what-columbia-just-threw-away)

> And that’s also why I’m outraged by Columbia University’s agreement yesterday with the Trump administration. There’s no other way to put it: Columbia abandoned free and open dialogue — the most fundamental principle of academic life — to save its own skin.

> But here’s the problem: Reasonable people disagree about what kinds of statements and behaviors constitute anti-Jewish hatred. And Columbia has effectively placed that disagreement out of bounds.

> So let’s suppose a professor declares that Israel is committing genocide in Gaza, like the Nazis did in Europe. Would Columbia declare the statement antisemitic and subject the professor to disciplinary action? How about a staff member who says that “Zionism is racism”? Or a student who chants, “From the river to the sea, Palestine must be free”? You might view all of these statements as antisemitic. And depending on who is talking and listening, I might agree with you.

> But I cannot — and will not — abide by a university that restricts our discussion of the matter.

* NYTimes: Columbia Walked a Tightrope on Its Way to a $200 Million Settlement With Trump

[https://www.nytimes.com/2025/07/25/nyregion/how-columbia-reached-a-deal.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/25/nyregion/how-columbia-reached-a-deal.html?smid=nytcore-ios-share&referringSource=articleShare)

> So Ms. Shipman sought what she called the “seeds” of truth in matters cited by the White House, including what it perceived as an academic orthodoxy on campus or an inability to hear other voices. She and Columbia’s other leaders told themselves that they could negotiate a deal with Trump to address things on campus that they agreed were broken, so long as it didn’t cross their red lines and compromise academic freedom.

> NYTimes: Did Columbia’s Deal With Trump Save Its Stature or Sacrifice It?

[https://www.nytimes.com/2025/07/24/nyregion/columbia-trump-deal-reaction.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/24/nyregion/columbia-trump-deal-reaction.html?smid=nytcore-ios-share&referringSource=articleShare)

> From the perspective of one longtime professor, a storied 270-year-old institution had capitulated to a bad-faith pressure campaign.

(Then cue the both sides...and afterwards)

> Lee C. Bollinger, the former president of Columbia, said that putting aside opinions on the university’s strategy, the Trump administration’s actions “cross several very serious, grave lines — legal, constitutional and basic norms.”

> “It’s a very sad moment. There’s no way around it,” Mr. Bollinger said, adding, “You have to come away feeling that this is really a tragedy for higher education and the country.”


* White House touts deal with Columbia as critics decry ‘chilling’ precedent

[https://www.washingtonpost.com/education/2025/07/24/columbia-white-house-deal-implications-impacts/](https://www.washingtonpost.com/education/2025/07/24/columbia-white-house-deal-implications-impacts/)

> Education lawyers and advocates said Columbia’s deal with the White House was a potentially dangerous government intrusion into higher education.

> In agreeing to the deal, the elite Ivy League institution in New York City is entering uncharted territory: It is making an enormous payment to the federal government despite not admitting any wrongdoing while relinquishing a certain measure of oversight to an independent monitor.

> Columbia will pay a further $21 million to Jewish faculty and staff members to settle investigations brought by the U.S. Equal Employment Opportunity Commission. Administration officials called it the largest such settlement ever for victims of antisemitism, and the largest in almost 20 years for any form of discrimination or harassment.

* The deal that the Trump administration struck with Columbia on Wednesday is a blueprint for negotiations with other universities, a White House official said

[https://www.wsj.com/us-news/education/harvard-columbia-trump-white-house-fines-payment-deal-settlement-d61aa9c6?st=kpHHY1&reflink=article_gmail_share](https://www.wsj.com/us-news/education/harvard-columbia-trump-white-house-fines-payment-deal-settlement-d61aa9c6?st=kpHHY1&reflink=article_gmail_share)

> The administration is in talks with several universities, including Cornell, Duke, Northwestern and Brown, the person familiar with the talks said, though it sees striking a deal with Harvard, America’s oldest university, as a key target.
> The White House hopes to extract hundreds of millions of dollars from Harvard, in a deal that would make Columbia’s $200 million payment look like peanuts, the person said.


### UVA

(These come from EI via Rutgers)

* Tim Kaine speaks to students:

[https://www.cavalierdaily.com/article/2025/07/sen-tim-kaine-speaks-to-uva-students-discusses-ryan-resignation-and-more](https://www.cavalierdaily.com/article/2025/07/sen-tim-kaine-speaks-to-uva-students-discusses-ryan-resignation-and-more)



* Letter from 12 Deans to Board of Visitors goes unanswered for two weeks (the article includes a link to the letter sent)

[https://www.cavalierdaily.com/article/2025/07/letter-from-11-deans-to-board-of-visitors-goes-unanswered-for-almost-two-weeks](https://www.cavalierdaily.com/article/2025/07/letter-from-11-deans-to-board-of-visitors-goes-unanswered-for-almost-two-weeks)



* UVA Faculty Senate adopts no confidence vote in Board of Visitors

[https://www.cavalierdaily.com/article/2025/07/uva-faculty-senate-overwhelmingly-adopts-a-no-confidence-vote-in-board-of-visitors](https://www.cavalierdaily.com/article/2025/07/uva-faculty-senate-overwhelmingly-adopts-a-no-confidence-vote-in-board-of-visitors)



A statement by Jewish UVA staff and faculty on antisemitism and DEI at UVA

* https://www.cavalierdaily.com/article/2025/07/a-statement-by-40-jewish-faculty-and-staff-on-antisemitism-and-dei-at-uva

## George Mason

* George Mason President Discriminated Against White People After George Floyd Protests, Justice Dept. Says

(Yup, believe it or not)

[https://www.chronicle.com/article/george-mason-president-discriminated-against-white-people-after-george-floyd-protests-justice-dept-says](https://www.chronicle.com/article/george-mason-president-discriminated-against-white-people-after-george-floyd-protests-justice-dept-says)

> The Justice Department on Thursday launched an investigation into George Mason University and its president, Gregory Washington, to determine if administrators discriminated against white male faculty and job applicants on the basis of race and sex in the aftermath of the George Floyd protests.

> In a June 2020 email, when universities across the country were responding to the murder of George Floyd by looking for ways to address historic racial disparities on their campuses, Washington said he would make changes to the promotion and tenure processes that “recognize the invisible and uncredited emotional labor that people of color expend to learn, teach, discover, and work on campus.”

> The department also cited a June 2022 post from Washington’s X account that celebrated DEI in the hiring process.

* NYTimes: In Virginia, the Attack on University Presidents Widens

[https://www.nytimes.com/2025/07/22/us/virginia-university-presidents-dei-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/22/us/virginia-university-presidents-dei-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

* Trump administration widens probes into Virginia’s largest public university

[https://www.washingtonpost.com/education/2025/07/22/justice-department-george-mason-investigation-dei/](https://www.washingtonpost.com/education/2025/07/22/justice-department-george-mason-investigation-dei/)

* The Plot to Oust the President of George Mason University -- This campaign is not about policy. It’s about power.

[https://www.chronicle.com/article/the-plot-to-oust-the-president-of-george-mason-university](https://www.chronicle.com/article/the-plot-to-oust-the-president-of-george-mason-university)

> Christopher F. Rufo, a senior fellow at the Manhattan Institute and the mastermind behind the moral panic over “critical race theory,” has cemented his reputation as a relentless opponent of diversity, equity, and inclusion in higher education.

> His hostility to DEI is matched by his influence among GOP decision-makers. He has organized campaigns against Claudine Gay, Harvard University’s first Black president, as well as several other Black administrators and faculty members at Harvard and other elite institutions. He helped oust Patricia Okker as president of New College of Florida and advocated for dismantling its Office of Outreach & Inclusive Excellence. Most recently, he led a successful campaign against Santa J. Ono, who was running to be the next president of the University of Florida.

> Rufo’s playbook is now being used against Virginia’s public universities, with Gov. Glenn A. Youngkin, a Republican, setting the table for a federal takedown. Youngkin’s strategy has two main parts. First, he has appointed political ideologues to university governing boards and encouraged them to impose their ideology to remake higher education in Virginia. Second, alongside the attorney general, he has weakened public universities’ ability to respond to federal investigations that threaten the very mission of their institutions.

> We recently watched this play out at the University of Virginia, where Youngkin-appointed board members and conservative alumni groups demanded the removal of all traces of DEI programs from the campus. Then came the Department of Justice investigation led by Harmeet Dhillon, assistant attorney general for the civil-rights division, and her deputy, Gregory W. Brown, both of whom are graduates of UVa. With the board unwilling to defend him and the threat that the university would lose millions of federal dollars, UVa’s president, James E. Ryan, resigned. Existential terror, indeed.

> First, over the past three years, George Mason has faced significant criticism from the staff of the Heritage Foundation’s Center for Education Policy, which has been led by Lindsey M. Burke for over eight years. Recently, Burke was appointed to the U.S. Department of Education. When she was chair of the George Mason board’s Academic Affairs Committee, Burke leveraged criticism from her colleagues at Heritage to justify her ongoing attacks on the university’s curriculum and its commitment to DEI.

> The same strategy was employed to incorporate the International Holocaust Remembrance Alliance’s (IHRA) working definition of antisemitism into George Mason’s nondiscrimination policy without knowledge or input from faculty members. George Mason adopted this contentious definition, which critics argue conflates antisemitism with criticism of the State of Israel, under the influence of Kenneth Marcus, a former member of the university’s Board of Visitors who was appointed by Youngkin. (Marcus’s appointment has since been denied by the Democratic-controlled Virginia Legislature.) Marcus is also credited with facilitating the adoption of the IHRA definition at Harvard and Columbia. His overarching goal is to embed the IHRA definition in university discrimination policies nationwide, silencing criticism of Israel and suppressing speech in support of the Palestinian people.

> On that same day, July 2, City Journal, a publication of the Manhattan Institute, published a column by Ian Kingsbury, a senior fellow at the Educational Freedom Institute, titled “George Mason University’s Disastrous President.” Citing a debunked Heritage-authored anti-DEI study and the Education Department’s threadbare allegations of antisemitism on campus, Kingsbury called for Washington’s ouster.

> The interconnections among the players in this little piece of political theater boggle the mind. For example, the Heritage Foundation’s Jay P. Greene wrote the report, since debunked by George Mason administrators, on “DEI bloat” that Kingsbury cited in his City Journal hit piece. It turns out that Jay Greene was a member of Kingsbury’s doctoral committee, and they frequently collaborate on articles. Greene is also a fellow at the Education Freedom Institute, where Lindsey Burke once served as a board member. Until recently, Greene also worked for Burke at the Heritage Foundation. Around and around we go.

> On July 3, the right-wing site Liberty Unyielding published a critique of George Mason ... On July 4, National Review published a piece by George Leef, director of external affairs at the conservative James G. Martin Center for Academic Renewal, referencing the Liberty Unyielding story ... Based on this circular, self-referential discourse, Bacon’s Rebellion, a conservative political blog run by James A. Bacon, then posted an article predicting that George Mason could be the next university to be investigated by the Department of Justice

> All of this is part of the strategy Rufo laid bare in an interview with Politico — publish relentless character assassination attacks in right-wing media until mainstream outlets feel they can no longer ignore the allegations, however specious or trivial.

> Let’s be clear: This campaign against George Mason and its president isn’t about antisemitism or so-called reverse racism. It’s about political control — plain and simple. ... They don’t want independent thought — they seek obedience.

> This is the Rufo doctrine in action: fabricate a crisis, flood the zone with misinformation, start coordinated media attacks, trigger federal investigations, and force institutions to collapse under the weight of bad-faith pressure. It worked at UVa. They want it to work at George Mason. If we allow it to happen again, we’re not just losing a president — we’re handing over the keys of public higher education to a political movement that views knowledge as a threat and diversity as a sin.



## Hopkins

* America First Legal Urges DOJ to Investigate Hopkins for DEI

[https://www.insidehighered.com/news/quick-takes/2025/07/21/america-first-legal-urges-doj-investigate-hopkins-dei](https://www.insidehighered.com/news/quick-takes/2025/07/21/america-first-legal-urges-doj-investigate-hopkins-dei)

> In a 133-page complaint filed Thursday, the conservative legal group, run by President Trump’s deputy chief of staff, Stephen Miller, urged the DOJ to investigate Johns Hopkins “for its systemic, intentional, and ongoing discrimination within its School of Medicine on the basis of race, sex, ethnicity, national origin, and other impermissible, immutable characteristics under the pretext of ‘diversity, equity, and inclusion’ (‘DEI’) in open defiance” of civil rights laws, Supreme Court precedent and presidential executive orders.

> The America First Legal complaint singles out certain medical school divisions and programs for seeking to recruit a “diverse applicant pool,” including residency programs in gynecology and obstetrics, emergency medicine, dermatology, anesthesiology and critical care.

> “It seems like this is orchestrated,” Washington said in a July 9 interview with The Chronicle. “The same people who are kind of aligned that got rid of Jim Ryan are aligned against me.”

> In Washington’s email on Friday, he maintained that diversity is integral to GMU’s mission. “Any attempt to artificially redefine our diversity, as one of race-based exclusivity, is doomed to fail no matter who ends up being excluded.”


## Blowback

* Staffing Shortages at ED Hurt College Operations

[https://www.insidehighered.com/news/government/student-aid-policy/2025/07/21/how-mass-layoffs-education-dept-affect-colleges](https://www.insidehighered.com/news/government/student-aid-policy/2025/07/21/how-mass-layoffs-education-dept-affect-colleges)

> Before the Department of Education laid off half its staff in March, college financial aid officers on the west coast could typically help a student track down their missing login information for the federal aid application in a matter of minutes.

> But now, due to limited hours of agency operation, tracking down a student’s Federal Student Aid ID can take days or even weeks; an east coast-based help line, which used to be open until 8 p.m. now closes at 3 p.m.—or noon Pacific time, according to Diane Cooper, the senior financial aid officer at Northwest Career College in Las Vegas.

* Congress Cut a Federal Nutrition Program, Jeopardizing Campus Jobs and Community Services

[https://www.chronicle.com/article/congress-cut-a-federal-nutrition-program-jeopardizing-campus-jobs-and-community-services](https://www.chronicle.com/article/congress-cut-a-federal-nutrition-program-jeopardizing-campus-jobs-and-community-services)

> SuperShelf is one of the thousands of initiatives funded by grants from the Department of Agriculture’s Supplemental Nutrition Assistance Program Education, or SNAP-Ed. The One Big Beautiful Bill Act, passed this month, eliminates funding for SNAP-Ed, effective September 30, leaving Durgan and hundreds of researchers and educators scrambling to figure out what these cuts mean for their institutions, and the communities they serve.

> The University of Minnesota announced July 7 that it would not renew the contracts of 59 educators who work in its extension. The federal program isn’t the extension’s only source of funds, but Durgan said she expects more layoffs as the fall approaches. “We served over 173,000 individuals last year with this program and most of it will be ending at the end of September,” Durgan said. “It just will.”

> Jennifer McCaffrey, assistant dean for the family and consumer sciences programs at the University of Illinois Extension, said she expects many partner organizations to suffer because of the cuts to SNAP-Ed. In Illinois, for example, she said SNAP-Ed is the primary distributor of venison. In the most recent hunting season, it sent 25,000 pounds of the game meat to food pantries statewide, feeding nearly 50,000 families. No other organization has the capacity to carry out such a service, she said, meaning a likely increase in both food waste and hunger across the state.

> Beyond the partner organizations themselves, McCaffrey said the state’s overall nutrition and health will suffer as well. The extension used SNAP-Ed funding to carry out initiatives named in the state’s health improvement plan, she added. “So we’re unsure where we’re turning to.”

> Kamaljeet Khaira, director of the University of California CalFresh Healthy Living program, said losing SNAP-Ed came as a shock given the Trump administration’s stated goal of improving Americans’ health.



## AI misdeeds

* NIH to Limit AI Use, Cap P.I. Grant Applications at 6 per Year

[https://www.insidehighered.com/news/faculty-issues/research/2025/07/22/nih-limit-ai-use-cap-grant-applications-6-year](https://www.insidehighered.com/news/faculty-issues/research/2025/07/22/nih-limit-ai-use-cap-grant-applications-6-year)

> The announcement noted that the NIH has “recently observed instances of Principal Investigators submitting large numbers of applications, some of which may have been generated with AI tools,” adding that the use of such tools has enabled some P.I.s “to submit more than 40 distinct applications in a single application submission round.” Michael Lauer, who retired in February as the NIH’s deputy director for extramural research, said he had once seen this happen, Science reported.

* Instructors Will Now See AI Throughout a Widely Used Course Software

[https://www-chronicle-com.csi.ezproxy.cuny.edu/article/instructors-will-now-see-ai-throughout-a-widely-used-course-software](https://www-chronicle-com.csi.ezproxy.cuny.edu/article/instructors-will-now-see-ai-throughout-a-widely-used-course-software)

> On the Canvas platform, faculty members will be able to click an icon that connects them with various AI features aimed at streamlining and aiding instructional workload, like a grading tool, a discussion-post summarizer, and a generator for image alternative text.

> Canvas’s parent company, Instructure, is also in partnership with OpenAI, the maker of ChatGPT, so instructors can use generative-AI technology as part of their assignments.

> Some worry that integrating AI into the grading and course-planning process might eliminate the need for adjunct instructors and could expand class sizes. Ruediger noted that in online courses, there is already “a level of technology mediating between instructors and their students,” a gap that might only widen and make it more difficult for students to know if their instructor has personally evaluated their work.


----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
