# Jul 11

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

Thanks to K, KB, MB, and VAC for sending along great items for this digest.

## Testimony

* "Antisemitism in Higher Education: Examining the Role of Faculty, Funding, and Ideology" testimony is rescheduled

[https://edworkforce.house.gov/calendar/eventsingle.aspx?EventID=412535](https://edworkforce.house.gov/calendar/eventsingle.aspx?EventID=412535)

> Full Committee Hearing; July 15, 2025 - 10:15 AM


* UC Berkeley chancellor is prepping for Capitol Hill grilling

[https://www.berkeleyside.org/2025/07/07/uc-berkeley-chancellor-is-prepping-for-capitol-hill-grilling?utm_medium=email&utm_campaign=1804604d16-EMAIL_](https://www.berkeleyside.org/2025/07/07/uc-berkeley-chancellor-is-prepping-for-capitol-hill-grilling?utm_medium=email&utm_campaign=1804604d16-EMAIL_)

(Thanks K for sharing this lengthy and interesting article about the background for the postponed testimony of the UC Chancellor, the CUNY Chancellor, and campus leader of Georgetown in front of a House subcommittee)

> Ever since President Trump announced in January a crackdown on antisemitism in higher education that included threats to deport pro-Palestinian student protesters, his administration has used that framework to rescind billions of dollars in research money from U.S. universities he claims are not protecting their Jewish students. Trump has demanded that at some universities, the federal government should be allowed to influence student admissions, faculty hiring, and the content of some academic departments. The federal government has already canceled $2.6 billion in research grants to Harvard, $400 million to Columbia University, and millions more to five other universities.

> In a talk at the Berkeley City Club last Wednesday, Lyons addressed the assault on higher education, its impacts on Cal, the balance between free speech and the right for all students to feel safe on campus, and how the UC system is approaching this era, all while it is wondering and waiting if UC will get one of those dreaded “Columbia-Harvard letters” from the administration announcing draconian cuts.

> More cuts may be coming. Leo Terrell, senior counsel at the Department of Justice and head of its antisemitism task force, said in a Fox TV interview in May that there will be “massive lawsuits against [the] UC system. … Expect hate crime charges filed by the federal government. Expect Title VII lawsuits.”

> “Has Berkeley turned a blind eye to antisemitism?” Lyons asked in a hypothetical question to the Berkeley City Club audience. “Have we been deliberately indifferent about antisemitism on campus? No way.”

> But executive orders aren’t law, said Catherine Lhamon, former assistant secretary for civil rights in the U.S. Department of Education, at a journalism conference in May. “Executive orders bind federal agencies about what the president directs those federal agencies to do. They don’t create law.” When asked about Trump’s antisemitism executive order, she added that schools and colleges “have an opportunity to challenge that in court, and they are not bound by the administration’s interpretation.” Llamon was recently named executive director of the Edley Center on Law & Democracy at UC Berkeley Law.

> He [David Cole, a professor at Georgetown Law] told the committee that antisemitism only violates Title VI in narrow circumstances: When the speech is targeting an individual’s Jewish identity and when the speech is so severe, pervasive and objectively offensive that it denies equal access to an education.

> “That’s a very high standard,” Cole said in the hearing. “It’s almost never been met in the case law.”

> “To be honest, and with all due respect, the hearings this committee held on this same subject last year are reminiscent not of a fair trial of any sort, but of the kind of hearings the House Committee on Un-American Activities used to hold,”  Cole said in his testimony. “And I think we can all agree that the HUAC hearings were both a big mistake and a major intrusion on the First Amendment rights of Americans.”

> The House committee wants to know if the widespread protests against Israel’s war in Gaza were authentic or were orchestrated by outside forces.

## Protests

* PSC Resolution Condemns Retaliatory Firing of CUNY Faculty

[https://psc-cuny.org/news-events/week/psc-condemns-retaliatory-firing-of-cuny-faculty-retro-for-part-timers/](https://psc-cuny.org/news-events/week/psc-condemns-retaliatory-firing-of-cuny-faculty-retro-for-part-timers/)

(The UFS XC and chairs of the AF committee also sent a letter to the Brooklyn College President).

(The PSC Academic Freedom Committee has sent two letters)


* CUNY suspends student activist leader, fires four faculty members in escalation of repression against Palestine activism

[https://mondoweiss.net/2025/07/cuny-suspends-student-activist-leader-fires-four-faculty-members-in-escalation-of-repression-against-palestine-activism/](https://mondoweiss.net/2025/07/cuny-suspends-student-activist-leader-fires-four-faculty-members-in-escalation-of-repression-against-palestine-activism/)

(Mondoweiss may not be the most impartial source of reporting)

> student organizer Hadeeqa Arzoo Malik has been suspended for a year. While she is suspended from CCNY, she is not permitted to enroll in any other CUNY college.

>  CUNY has also fired four faculty members, including Corinna Mullin. Mullin held teaching positions at CUNY as an adjunct professor at Brooklyn College and John Jay College of Criminal Justice.

> In the middle of June, Malik was notified of her suspension in a letter signed by CCNY’s Assistant Vice President of Student Affairs, Dr. Ramón De Los Santos. During Malik’s speech at the press conference, which was chanted via “the people’s mic,” a familiar call-and-response tactic used by protest organizers, Malik shared CUNY’s justification for suspending her.

> “I was suspended… for allegedly violating the CUNY Henderson Rules number one and seven and CCNY demonstration policies one and two.

> Mullin told Mondoweiss, “Over the past several years, there has been a pattern of external Zionist, far-right organizations like Camera, Betar, and Canary Mission targeting me and other CUNY workers and students for organizing in solidarity with Palestine.”

(See:
[https://www.chronicle.com/article/an-anonymous-groups-list-of-purported-critics-of-israel-helped-steer-a-u-s-crackdown-on-student-activists](https://www.chronicle.com/article/an-anonymous-groups-list-of-purported-critics-of-israel-helped-steer-a-u-s-crackdown-on-student-activists)
)

> Chancellor Matos Rodríguez was preparing to scapegoat Malik, Mullin, and the other adjunct professors whose teaching positions were terminated when presenting to the U.S. House of Representatives Committee on Education & Workforce.


## Letters

* July 4th letter from SUNY

[https://docs.google.com/document/d/1NgZBYtbE_1R0i2fyhZWPNkKtP-13qp69satQo_pcIVU/edit?tab=t.0#heading=h.ntcq7lonrt](https://docs.google.com/document/d/1NgZBYtbE_1R0i2fyhZWPNkKtP-13qp69satQo_pcIVU/edit?tab=t.0#heading=h.ntcq7lonrt)

(to sign: )

[https://docs.google.com/forms/d/1CQXwYQeXukzS-HJjCfXZXQOwV-Mgq3pPtAF88AQ8P2g/viewform?edit_requested=true](https://docs.google.com/forms/d/1CQXwYQeXukzS-HJjCfXZXQOwV-Mgq3pPtAF88AQ8P2g/viewform?edit_requested=true)

> We hold these truths to be self-evident, that the cause of higher education is in great measure the cause of all humanity, that higher education’s function is to secure human equality, expand human rights, and free human potential; and that colleges and universities were instituted, and derive their just powers, from their commitments to the following foundational principles:

> the pursuit of knowledge, truth, and wisdom for the public good;
> the cultivation of freedoms of thought, inquiry, speech, expression, assembly, and association for all students, staff, and faculty;
> the integrity of academic research, teaching, and learning;
> the provision of educational programs and services to all students in the safest and most supportive environment possible;
> the advancement of diversity, equity, and inclusion;
> the autonomy and democratic accountability of campus governance.


## Statements

* A Statement from the Eula Mae and John Baugh Foundation on the Cancellation of
LGBTQIA+ Research Grant by Baylor University

[https://www.baughfoundation.org/wp-content/uploads/Baugh-Foundation-Statement.pdf](https://www.baughfoundation.org/wp-content/uploads/Baugh-Foundation-Statement.pdf)

> This decision disserves Baylor students, faculty, and the broader Christian community. Baylor has a duty to protect and uphold the integrity of scientific inquiry, allowing its world class faculty to investigate complex issues without fear of reprisal based on shifting political winds. Pulling the rug out from under its faculty after those researchers have already put the grueling work into securing funding, work they undertook with Baylor’s full knowledge and approval, is a chilling affront to the very concept of academic freedom. Stymying research and opportunity will inevitably lead the best and brightest students and faculty to other universities where their work
and their freedom will be valued and protected.



## Freedom of expression


* To save themselves, universities must cultivate civic friendship


[https://www.washingtonpost.com/opinions/2025/06/30/universities-trump-survival-free-speech/](https://www.washingtonpost.com/opinions/2025/06/30/universities-trump-survival-free-speech/)

> We believe a fundamental reason for the decline of the pursuit of truth on campuses is the collapse in acknowledging the importance of civic friendship — which, following Aristotle, we understand to be the bond of mutual respect and willingness to cooperate for the sake of the common good, even across significant disagreements or divisions.

> The cultivation and recovery of civic friendship must necessarily undergird any successful effort by universities to regain public legitimacy and the moral high ground. Here, we hope to provide some guidance for restoring campus cultures where faculty and students feel free to speak their minds and explore ideas, no matter how unpopular or controversial on or off campus they happen to be.

> This is because universities that do not model and actively foster civic friendship become ideological seminaries, sending into the world graduates who have been trained to be zealots for particular causes rather than formed as dispassionate and determined truth-seekers.

> They call for the principled defense of freedom of speech and the consistent enforcement of rules against speech-chilling behaviors such as harassment and the shouting-down of speakers, as well as any activities that disrupt core academic priorities such as teaching, studying and research. And they demand a commitment by university leaders to ensuring that seminar rooms and lecture halls are not “safe spaces” but rather Socratic Spaces, where students are made to wrestle with ideas that challenge their preconceived assumptions and deeply held beliefs — indeed, ideas which might make them feel uncomfortable.



### Anti-woke/anti-DEI is simply racism

* NIH cancels sickle cell research grant, citing DEI, doctor says – NBC4 Washington

[https://www.nbcwashington.com/news/local/nih-cuts-study-on-disease-that-affects-mostly-black-patients-citing-dei-doctor-says/3948371/](https://www.nbcwashington.com/news/local/nih-cuts-study-on-disease-that-affects-mostly-black-patients-citing-dei-doctor-says/3948371/)

> A doctor says she’s scrambling to figure out how she’ll continue her work helping sickle cell disease patients after the National Institutes of Health cancelled her $750,000 research grant, citing diversity, equity and inclusion and divisiveness as a factor.

> Sickle cell disease affects about 100,000 people in the U.S., and 90% of patients are Black, according to NIH.

> But two weeks ago, the NIH told her it’s taking away her funding, citing a "low return on investment." It also said studies involving DEI "support unlawful discrimination on the basis of race ... which harms the health of Americans."


* Colleges, companies and philanthropic groups are retooling millions of dollars in scholarships that for years supported minority students


[https://www.wsj.com/us-news/education/anti-dei-minority-scholarships-a721ba1b?st=h3S9TL&reflink=article_gmail_share](https://www.wsj.com/us-news/education/anti-dei-minority-scholarships-a721ba1b?st=h3S9TL&reflink=article_gmail_share)


> Colleges, companies and philanthropic organizations are retooling millions of dollars in scholarships that for years supported minority students.

> Under threat from the Trump administration and activist groups over diversity programs, some are scrapping scholarships entirely. Others are broadening the programs to focus on low-income students in general or tweaking applications to try to keep their original missions.

> “We’re seeing widespread fear of litigation prompt many scholarship providers to re-evaluate,” said Jackie Bright, president of the National Scholarship Providers Association.

> Education experts said the changes could make it harder for minority students to graduate from college. “There’s going to be a decline in college affordability and completion rates for those students,” Bright said.

> Edward Blum [for your bingo card], whose group was behind the lawsuit that led to the 2023 Supreme Court decision that banned affirmative action, also brought the McDonald’s lawsuit.

* NYTimes: How Trump’s D.E.I. Cuts Are Hurting Rural, White Americans Too

[https://www.nytimes.com/2025/07/10/us/trump-science-nih-grants-dei-cuts.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/10/us/trump-science-nih-grants-dei-cuts.html?smid=nytcore-ios-share&referringSource=articleShare)


> But Mr. Trump’s push to end D.E.I. has been a blunt instrument, eliminating highly competitive grant programs that defined diversity well beyond race and gender. Those who have lost grants include not only Black and Latino scientists, but also many like Mr. Dillard, who are white and from rural areas, which are solidly Trump country. The administration has decried universities as hotbeds of liberal elitism, inhospitable to viewpoint diversity. The canceled diversity grant programs were intended to make science less elite, by developing a pipeline from poorer areas of the country that tend to be more conservative.

> “I think it’s very different in their minds, who is getting the D.E.I. stuff,” Mr. Dillard said. “People on the right, they don’t realize they’re limiting the opportunity of their own kids by supporting this.”

> Many young scientists talk about feeling betrayed by the places that raised them. “I’ve encountered a lot of callousness about my fellowship being terminated,” said Ms. Reneker, at Princeton. People back home tell her “there’s going to be some casualties along the way,” or “there must be some kind of misunderstanding.”

> “These are the kids we are supposed to be propping up,” the teacher, Greg Tucker, said. “It comes back to the whole Make America Great thing again. How did we make America great? It was through science.”

## Financial aid

* Trump ends interest subsidy for Biden’s student loan repayment plan

[https://www.washingtonpost.com/education/2025/07/09/trump-ends-interest-subsidy-bidens-student-loan-repayment-plan/](https://www.washingtonpost.com/education/2025/07/09/trump-ends-interest-subsidy-bidens-student-loan-repayment-plan/)

> The Education Department on Wednesday said it will resume collecting interest on the student loans held by 7.7 million people enrolled in a Biden-era repayment plan that is tied up in the courts.

> An analysis by the advocacy group Student Borrower Protection Center estimates that an average borrower affected by the policy change could incur more than $3,500 in interest charges in a year or roughly $300 per month.

> The department’s announcement arrives days after President Donald Trump signed into law the One Big Beautiful Bill, which, among other things, gets rid of the Save plan for new borrowers and gives current borrowers until July 2028 to exit the program. Advocacy groups see the department’s decision to end the interest subsidy as a way to hasten that departure and say the move will harm millions of borrowers.


## Funding cuts

* A Lost Generation of Researchers

[https://www.chronicle.com/article/a-lost-generation-of-researchers](https://www.chronicle.com/article/a-lost-generation-of-researchers)

> With that, Buan became one of thousands of early-career scholars who have become collateral damage amid policy changes at the National Institutes of Health, National Science Foundation, and other government agencies. As these agencies have sought to put caps on indirect funding, several doctoral programs paused or reduced admissions in February and March. Another wave of uncertainty hit weeks later, as the NIH and NSF terminated hundreds of existing grants, throwing many current doctoral and postdoctoral scholars’ funding into question. Meanwhile, the Trump administration’s proposed budget for the 2026 fiscal year contains deep cuts to the NIH, NSF, and other federal agencies that support scientific research.

> All told, the White House’s actions, many of which are tied up in court, could result in a lost generation of budding academics. Students are being forced to delay their graduate studies, continue them abroad, or forgo them entirely. The collective impact of those individual decisions is nearly impossible to measure, says Joanne Padrón Carney, chief governmental relations officer for the American Association for the Advancement of Science.

> he NSF, for instance, awarded only 1,000 of its Graduate Research Fellowships this year, half of its usual total and the lowest number of awards in 15 years, according to Nature; the NIH canceled a slate of early-career programs. In a spring survey conducted by the American Institute of Physics, 37 percent of department chairs whose programs offer graduate degrees in physics and astronomy said they expected to enroll fewer graduate students in the fall of 2025 than they did last fall,

* What Does It Cost to Run a Lab? Cancer research is expensive. Here are the price tags.

[https://www.chronicle.com/article/what-does-it-cost-to-run-a-lab](https://www.chronicle.com/article/what-does-it-cost-to-run-a-lab)

(Mass spectrometer: 1.5M to replace; 65k/yr to run; Autoclave 50K; Reagents in cold storage 100k; Liquid chromatography machine 90k; Licor imaging machine 70k; Nikon microscope 250k; etc. A 5-year 3.4M grant helps.)





### NSF

* Senate Appropriators Reject Trump’s NSF Cuts

[https://www.insidehighered.com/news/government/science-research-policy/2025/07/11/senate-rejects-trumps-cuts-nsf-other-science](https://www.insidehighered.com/news/government/science-research-policy/2025/07/11/senate-rejects-trumps-cuts-nsf-other-science)

> Signs that Congress intends to push back on the Trump administration’s wholesale slashing of federal budgets emerged during a Senate meeting Thursday that kicked off the annual appropriations process.

> However, on Thursday a subcommittee that oversees the budgets for the Justice and Commerce Departments as well as related science agencies proposed only a small cut to the National Science Foundation budget next fiscal year—a far cry from the $5 billion reduction that President Donald Trump wants to see.

> Instead, NSF will get just over $9 billion, a $16 million cut, said Sen. Jerry Moran, the Kansas Republican who chairs the subcommittee. The bill also sends about $10 million more to the National Weather Service and boosts funding for National Aeronautics and Space Administration.

(That is good news?)

> Although the science funding received bipartisan support, a fight over funding for the new Federal Bureau of Investigations headquarters could tank the legislation.


### NIH

* NYTimes: How to Wreck the Nation’s Health, by the Numbers

[https://www.nytimes.com/interactive/2025/06/30/opinion/hhs-cuts-harming-american-health.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/interactive/2025/06/30/opinion/hhs-cuts-harming-american-health.html?smid=nytcore-ios-share&referringSource=articleShare)


> The Department of Health and Human Services has terminated thousands of grants, including funding for pandemic prevention, and research grants related to cancer, vaccines and chronic diseases. The loss of research funding will delay medical discoveries. Though the agency publishes a weekly list of terminated grants, the full scope of funding cancellations has been obscured, especially at the National Institutes of Health, the major funder of medical research. A database created by Harvard researchers, Grant Watch, has helped to fill in the gaps.

(See the great infographics)

> Since President Trump has taken office, H.H.S. has cut over $9.5 billion in grant funding that had been approved but not yet distributed to programs and researchers. [5.8B to CDC, 3.2B to NIH (2600+ grants; 578M for training grants)]

> Physicians like me know from the data that lives will be lost as a consequence. More than 6,000 health professionals (myself included) have warned the public about their concerns in an open letter

[https://www.citizen.org/wp-content/uploads/A-MESSAGE-OF-CONCERN-FROM-THE-NATIONS-HEALTH-PROFESSIONALS.pdf](https://www.citizen.org/wp-content/uploads/A-MESSAGE-OF-CONCERN-FROM-THE-NATIONS-HEALTH-PROFESSIONALS.pdf)


* Trump's second presidency begins: evaluating effects on the US health system - ScienceDirect


[https://www.sciencedirect.com/science/article/pii/S2667193X25001838](https://www.sciencedirect.com/science/article/pii/S2667193X25001838)


> The first hundred days of the second Trump administration was unprecedented, with the administration taking remarkably aggressive, often questionably legal actions across health policy. This article uses the Health Systems Performance Assessment Framework to identify key policies regarding resources, financing, governance, and service delivery and their impact on the cost, quality, access, and equity of the US health system. The evaluation is largely negative. The administration, in its very energetic first hundred days, has already undermined resources, financing, and in particular governance in areas as diverse as oversight of long-term care, scientific research, and vaccination policy. Administration rhetoric and budget proposals called for severe reductions in health care access and actions to terminate services for particular groups, such as immigrants or gender minorities. Many of the particular actions, such as mass layoffs of specialist scientific and regulatory staff, will be difficult to reverse.

(On a grid with 64 options, 54 were colored *harmful*; none *beneficial*)

> Shocks to specialist research communities cause rapid attrition, with scientists exiting the workforce and even the country after as little as a month of disrupted funding, and resources diverted from high-quality basic research to privately assigned, less-impactful work.17,18 They may also increase hesitancy around research participation, particularly for groups that are already under-represented in health research. One estimate suggests that the administration's proposed NIH cuts, over 25 years, will save $500bn and cost the country $8.2 trillion in lost health-a cost more than 16 times greater than the savings, even excluding lost economic benefits from health research.

> Across Table 1, the second Trump administration's record is one of unprecedented damage. Budget proposals that were not enacted but started in the first hundred days would exacerbate the damage through enormous cuts to Medicaid, supplemental nutrition, HHS and NIH. Decentralizing responsibilities to the states will produce less efficiency (due to loss of economies of scale and specialist resources such as laboratories), more variation in state politics, resources, and risks, and more inequality between states.108 Trump is the least popular president in US polling history.109 It remains to be seen whether the majority of Americans will stand up and successfully demand that he change course to reflect their views.


* NIH Plans to Cap Publisher Fees, Dilute ‘Scientific Elite’

[https://www.insidehighered.com/news/government/science-research-policy/2025/07/10/nih-plans-cap-publisher-fees-dilute-scientific](https://www.insidehighered.com/news/government/science-research-policy/2025/07/10/nih-plans-cap-publisher-fees-dilute-scientific)

> The National Institutes of Health announced a plan Tuesday to implement a cap on the fees publishers can charge NIH-funded researchers to make their work publicly accessible.

> Both the updated open-access policy and the NIH’s newly announced publisher fee cap, which takes effect next year, are designed to put some limits on the $19 billion for-profit scholarly publishing industry, which is dominated by a small group of for-profit megapublishers, including Elsevier, Taylor & Francis and Springer Nature. The industry thrives on the unpaid work of scholars—including thousands funded by the NIH and other federal agencies—who rely on publishing their research in prestigious journals to earn tenure, promotion and recognition as leaders in their fields.

> “I expect the response to this will be that these journals will lose some of their market power,” Bhattacharya told Charlie Kirk, founder of the right-wing group Turning Point USA, in an interview Tuesday. “A lot of their market power has to do with the fact that they bully scientists into paying large fees and essentially end up bullying us.”

> During the pandemic, Bhattacharya, who was a health economist at Stanford University before Trump appointed him director of the NIH, became one of the political right’s favorite examples of how the so-called scientific elite allegedly suppressed nonconformist scientific beliefs. In 2020, he criticized public officials’ recommendations for people to stay home to mitigate the spread of the COVID-19 virus, sparking widespread backlash from other experts—including the officials running the NIH at the time.

> But now that he’s in charge of the same agency that dismissed his views as “fringe” nearly five years ago, Bhattacharya has vowed to “establish a culture of respect for free speech in science and scientific dissent at the NIH.”

### DOE

* Education Department Postpones NACIQI Summer Meeting

[https://www.insidehighered.com/news/quick-takes/2025/07/08/education-department-postpones-naciqi-summer-meeting](https://www.insidehighered.com/news/quick-takes/2025/07/08/education-department-postpones-naciqi-summer-meeting)

> The delay means that by the time the panel meets, the terms of six of its 18 members will have expired. The education secretary, House and Senate each appoint six members. In May, Education Secretary Linda McMahon requested nominations to fill six seats in October. Experts and members of the committee are worried that the Trump administration is trying to stack the panel in its favor as decisions about the future of higher education accreditation loom.

> The panel, known as the National Advisory Committee on Institutional Quality and Integrity, advises the department on which independent agencies should have the power to accredit colleges and therefore which colleges should have access to federal aid. At the next meeting, NACIQI is scheduled to decide whether to renew recognition for the Middle States Commission on Higher Education, the accreditor for Columbia University.

> Panel member and chair Zakiya Smith Ellis told the Journal that she is concerned that the Trump administration is “trying to take over this advisory group that is supposed to be in place for our expertise in higher education, not to push a certain political agenda.”

* Florida Board of Governors to Vote on New Accreditor

[https://www.insidehighered.com/news/institutions/regional-public-universities/2025/07/11/fla-board-governors-vote-creating-new](https://www.insidehighered.com/news/institutions/regional-public-universities/2025/07/11/fla-board-governors-vote-creating-new)

> The goal is to accredit six institutions by next summer and secure Department of Education recognition by June 2028, according to the business plan. (A new accreditor typically has two years to prove it is operating in accordance with federal regulations to receive federal approval.)

> The Commission for Public Higher Education would be incorporated as a nonprofit organization in Florida, initially funded by a $4 million appropriation from the Florida State Legislature, according to the business plan. Other involved higher ed systems are expected to cough up similar funds. A board of directors representing each of the founding systems would oversee the new accreditor.

> “CHEA does not believe that states are likely to be effective accreditors,” she wrote. “Historically, states have not had the staff, experience, or knowledge necessary to create a higher education accreditor. It is critically important that higher education reflects an impartial and unbiased accrediting review process that is focused on student learning outcomes. To date, there has not been a state that has accomplished this.”


## Federal Agencies

### DOE/OCR

* Court Filing Sheds Light on Civil Rights Complaints Under Trump


[https://www.insidehighered.com/news/government/politics-elections/2025/07/08/trump-admin-dismisses-34k-civil-rights-complaints-3](https://www.insidehighered.com/news/government/politics-elections/2025/07/08/trump-admin-dismisses-34k-civil-rights-complaints-3)

> The Education Department’s Office for Civil Rights dismissed more than 3,400 complaints from March 11 to June 27—a figure that advocates say is unprecedented and concerning.

> Since March 11, OCR received 4,833 complaints and opened 309 investigations, according to the filing from Rachel Oglesby, the department’s chief of staff. OCR also started 26 of what the office calls “directed investigations,” which aren’t based on a specific complaint. Another 3,424 complaints were dismissed “consistent with OCR’s Case Processing Manual,”

> “The dismissals are high and the case-resolution numbers are low, and I understand the resolutions they count reflect work completed before the [reduction in force],” she said, adding that the 290 resolutions “reflect a shocking diminution of work output from the office.”

> Oglesby didn’t provide any more information about why the complaints were dismissed or what types of violations they focused on. The department usually releases more information about OCR’s complaints and investigations as part of an annual report and in the budget process.

### OMB

* Withheld Adult Education Funds Worry Community Colleges


[https://www.insidehighered.com/news/institutions/community-colleges/2025/07/10/withheld-adult-education-funds-worry-community](https://www.insidehighered.com/news/institutions/community-colleges/2025/07/10/withheld-adult-education-funds-worry-community)

> The roughly $716 million was supposed to be disbursed to states July 1 and then divvied up among their adult education providers, such as community colleges. But the funding for high school equivalency classes, English as a second language programs and other adult education services never arrived.

> “Initial findings show that many of these grant programs have been grossly misused to subsidize a radical leftwing agenda,” wrote the OMB spokesperson, citing examples of states and schools using the money to support students in the country without proper documentation

> “If funding is not provided, there are nothing but bad options for institutions,” said David Baime, senior vice president for government relations for the American Association of Community Colleges. He predicts community colleges would have to reduce adult education services, lay off personnel and vie for funds to fill in the gap from states and other sources. But even so, “the funding is so substantial in a number of places that there’s no immediate source of replacing that money.”

## Congressional actions

* NYTimes: What the Republicans’ New Policy Bill Means for Higher Education

[https://www.nytimes.com/2025/07/03/us/trump-bill-education-college-student-loans.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/03/us/trump-bill-education-college-student-loans.html?smid=nytcore-ios-share&referringSource=articleShare)

> The bill would expand the tax on endowments that universities use for financial aid, roll back student loan protections and cap the amount students can borrow for graduate programs.

> The bill would “make college less affordable,” said Lynn Pasquerella, president of the American Association of Colleges and Universities, adding that schools could become less economically and racially diverse.

> It comes as the Trump administration has unleashed an attack on colleges and universities, cutting research grants and making it harder for international students to enroll. The administration has singled out top schools like Harvard, Columbia and the University of Pennsylvania. But the bill shows that the Republican agenda for higher education extends far beyond the Ivy League.

> The sweeping cuts to Medicaid at the center of the bill could also have ramifications for higher education. Experts say the changes, which include new work requirements, will make juggling work, education and family responsibilities even harder for low-income students.

> Getting student loans will be more difficult.

> Student loans may depend on alumni salaries.

> University endowments face higher taxes.

> Pell Grants can now be used for nondegree programs. -- The bipartisan move was welcomed by community colleges, which said it would make work-force training more accessible to nontraditional students.

## State actions

* Asm. McDonald: Assembly majority will meet on Friday to discuss federal cuts

[https://spectrumlocalnews.com/nys/central-ny/news/2025/07/07/asm--mcdonald--assembly-majority-will-meet-on-friday-to-discuss-federal-cuts](https://spectrumlocalnews.com/nys/central-ny/news/2025/07/07/asm--mcdonald--assembly-majority-will-meet-on-friday-to-discuss-federal-cuts)

> H.R. 1, the tax cut and spending bill signed into law by President Donald Trump, will have wide-ranging impacts on New York state.

> The state legislature is expected to return to Albany for a special session to deal with the fiscal impact of the cuts.

* A 4/4 Teaching Load Becomes Law at Most of Wisconsin’s Public Universities

[https://www.chronicle.com/article/a-4-4-teaching-load-becomes-law-at-most-of-wisconsins-public-universities](https://www.chronicle.com/article/a-4-4-teaching-load-becomes-law-at-most-of-wisconsins-public-universities)

> The workload requirement was folded into Wisconsin’s state budget, a bipartisan plan signed last week by Gov. Tony Evers, a Democrat. Per the legislation, full-time UW system instructors must teach at least 24 credits across the fall and spring terms, starting September 1, 2026. That requirement is halved for the state’s two R1 universities, UW-Madison and UW-Milwaukee.

> In addition to the 24 minimum credits during the fall and spring, instructors who are on a 12-month contract must teach six credits in the summer. Workloads for part-time instructors will be set in proportion to full-time requirements.

> But Michael DeCesare, a senior program officer at the national American Association of University Professors, said state-mandated minimum course loads are at odds with AAUP standards, which recommend that faculty “participate fully in the determination of workload policy.”

* Budget director says NY health care will be 'destabilized' by federal cuts

[https://www.timesunion.com/capitol/article/dob-director-ny-health-care-destabilized-no-20765002.php](https://www.timesunion.com/capitol/article/dob-director-ny-health-care-destabilized-no-20765002.php)

(Thanks MB for sharing)

>  New York’s top budget official warned of a “destabilized” state health care system after an omnibus bill signed last week by President Donald J. Trump takes effect, but said state leaders are not currently poised to raise taxes as they face the possibility of drastic cuts within the year.

> Division of Budget Director Blake Washington, one of the top officials in Gov. Kathy Hochul’s administration, said New York lawmakers will confront “hard decisions” soon after the federal bill’s sweeping changes to safety net programs including Medicaid.



## Institutional assaults

* How Trump Uses the DOJ as Tool of ‘Fear-Mongering’

[https://www.insidehighered.com/news/government/politics-elections/2025/07/07/trump-deploys-justice-dept-ramp-attacks-higher-ed](https://www.insidehighered.com/news/government/politics-elections/2025/07/07/trump-deploys-justice-dept-ramp-attacks-higher-ed)

> While traditional DOJ cases can take years to resolve, Bondi’s agency has launched and concluded investigations in a matter of months or even weeks, leaving little room for appeal, negotiation or settlement. That makes it difficult to overlook the possibility that Trump’s efforts to enforce the law on college campuses are part of his calculated clench for control, higher education advocates say.

> “The DOJ has been involved in higher education before. Up until now, though, I just don’t have a sense that it’s ever been intentionally weaponized for political purposes,” said Peter McDonough, vice president and general counsel at the American Council on Education. “We certainly can feel the intensity of focus and the desire for political messaging. There’s a fear factor that clearly has been a motivator and an objective.”

> “What we’re seeing here is less about enforcement of laws and more about government terrorism,” said Ferise of the Indiana law firm. “By definition terrorism is using intimidation to unlawfully pursue some kind of political gain or vendetta, and I can’t see how this is anything other than that.”

* How a Shadowy Online Blacklist Became a Legal Threat to Pro-Palestinian Activists – Mother Jones


[https://www.motherjones.com/politics/2025/07/canary-mission-israel-palestine-blacklist-university-trump-deportation-ozturk-khalil/](https://www.motherjones.com/politics/2025/07/canary-mission-israel-palestine-blacklist-university-trump-deportation-ozturk-khalil/)

> The goal, Canary Mission says, is to “ensure that today’s radicals are not tomorrow’s employees” and “combat the rise in anti-Semitism on college campuses.” But lawyers, activists, and critics of the site worry that the consequences could now be more serious than diminished job prospects and that foreign students like Öztürk—who have been rounded up by the Trump administration—may have been targeted for imprisonment and deportation because they were listed on an anonymous blacklisting site. (Öztürk has since been returned to Massachusetts.)

(Several CUNY community members are listed on canary)

> What’s clear, however, is that Canary Mission has been repeatedly cited in federal lawsuits against student activists and in official US government communications with universities, as the Trump administration detains students with little explanation. Canary Mission’s “about us” page claims its content meets “high standards of accuracy and authenticity,” but the spin it puts on pro-Palestinian activities is hardly objective—especially given the increasingly severe consequences for the people it describes. Attending an antiwar protest, for example, becomes “participation in a pro-Hamas rally;” criticism of Israeli policies is framed as “demonizing Israel.”

> It “is not the first,” Lockman said, “but [it is] maybe the most effective.” Today, it holds profiles of more than 1,800 students, 1,100 professors, 300 medical professionals, and 2,100 people simply labeled “professionals.”

> In 2018, an investigation by the Forward connected Canary Mission to a registered Israeli nonprofit called Megamot Shalom, or “Peace Trends.” Donations to Canary Mission, the outlet reported, were being routed through Megamot Shalom.

> The Israeli nonprofit registry shows that Megamot Shalom, still active seven years after its launch, has only 11 employees. More than 99 percent of its budget—about a million dollars, for fiscal year 2023—comes via donations from abroad.

> The Helen Diller Family Foundation listed a donation as “CANARY MISSION FOR MEGAMOT SHALOM” on its publicly accessible tax forms in 2016. (After journalists found the donations, the foundation stopped giving to either organization.) That same year, the Michael and Andrea Leven Family Foundation donated $50,000 to Megamot Shalom, and told a Jewish Currents reporter in 2021 that the money was intended for Canary Mission.

> Mother Jones identified two American foundations that have donated to Canary Mission more recently: the Natan and Lidia Peisach Family Foundation, which donated $100,000 in fiscal year 2023, and the Ann and Robert Fromer Charitable Foundation, which donated $20,000 that same year.

> As of 2016, Rabbi Ben Packer was listed as a board member of Megamot Shalom on Israel’s public charity registry. Born in the United States, Packer—who says he was a “rabbi on campus” at Duke University and the University of North Carolina—now runs an ultranationalist youth hostel in Jerusalem and lives in a West Bank settlement. He has boasted of his friendship with Stephen Miller, the Trump adviser behind many of the president’s most controversial immigration policies.

> Attempts to hold Canary Mission liable for defamation have mostly failed, in part because would-be plaintiffs cannot say conclusively whether or not it is housed in the United States. Kinza Khan, a Pakistani American Muslim woman from

> Some lawmakers, too, are treating Canary Mission as a legitimate source for triggering government investigations. Last year, the House Committee on Education and the Workforce sent letters to schools like MIT and UC Berkeley inquiring about those institutions’ responses to alleged antisemitism referenced in professors’ Canary Mission profiles.

> Now, as Republicans move to further restrict citizenship, Canary Mission is supporting a campaign by Rep. Andy Ogles to revoke New York mayoral nominee Zohran Mamdani’s citizenship and deport him from this country.



* Amicus brief by AAUP, Rutgers, Middle East Studies Association

[https://www.presidentsalliance.org/wp-content/uploads/2025/04/PA-brief.pdf](https://www.presidentsalliance.org/wp-content/uploads/2025/04/PA-brief.pdf)

(Thanks KB)

> Amicus curiae the Presidents’ Alliance on Higher Education and Immigration (the “Alliance”) submits this brief to advise the Court of the effects of the administration’s policy of targeting non-citizen students and faculty at institutions of higher education throughout the country
based on their political views.


### Harvard

* NYTimes: How Harvard’s Ties to China Helped Make It a White House Target

[https://www.nytimes.com/2025/07/07/us/harvard-china-white-house-funding.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/07/us/harvard-china-white-house-funding.html?smid=nytcore-ios-share&referringSource=articleShare)

> But American foreign policy has turned sharply hawkish against China, and even though Harvard has steadily reduced its ties there, the Trump administration has made the relationship another line of attack in its broader effort to bring the university to heel. The administration has stripped away billions of dollars in federal research funding and is trying to revoke its right to host international students and also end its nonprofit tax status.

> Alan M. Garber, the university’s president, has described the administration’s overall assault on the school as a power grab “unmoored from the law, to control teaching and learning at Harvard and to dictate how it operates.”

* Harvard’s Fight Is a Defense of Democracy and Civic Virtue


[https://www.liberalcurrents.com/harvards-fight-is-a-defense-of-democracy-and-civic-virtue/](https://www.liberalcurrents.com/harvards-fight-is-a-defense-of-democracy-and-civic-virtue/)

> To some observers, Harvard’s stand might seem like it’s just Ivy League self‑regard, an affluent institution protecting its perks. That reading gets the stakes backward. What is under attack is the rule‑of‑law scaffolding that lets any voluntary association—PTA or synagogue, start‑up or labor union—pursue its mission without waiting for White House permission slips or fearing punitive retaliation. A university that surrenders control over whom it may admit, hire, or teach ceases to be a university; it becomes a subordinate creature of politicians and the ever-changing whims of election results.

> The counterexample is on display in another venerable American institution of higher education, the University of Virginia, where president James Ryan proffered his resignation in the face of a targeted pressure campaign from the Trump administration’s Department of Justice, and UVA’s Board of Visitors accepted it. Under the thin pretense of enforcing civil rights laws, the federal government is now essentially dictating policies, curriculum, and personnel according to the political whims of the White House.

> It’s not only an outrageous attack on academic freedom, it’s also an attack on the constitutional autonomy of state governments, at the public university Thomas Jefferson was once so proud of chartering he had it inscribed on his grave.

> Yet history warns that trimming our sails in hopes of preserving research dollars often achieves neither independence nor solvency. Ask Central European University. When Hungary’s Viktor Orbán demanded curricular control in 2017, CEU hesitated, negotiated, and was ultimately driven from Budapest anyway. Appeasement bought time but not independence.

> The rest of us have a part to play. Other universities can file amicus briefs. Foundations and philanthropists can step in to help keep research going while funding cutoffs are litigated. Alumni can send the signal that integrity in this moment is what keeps their checkbooks open. Ordinary citizens can refuse to sacrifice higher principles on the altar of partisan cultural grievances. Democracy’s immune system is made of these antibodies.

* Trump administration ups pressure on Harvard with threat to accreditation

[https://www.ft.com/content/a60c469b-6c0c-49af-9c9d-6908f4ab6561](https://www.ft.com/content/a60c469b-6c0c-49af-9c9d-6908f4ab6561)

and

[https://www.wsj.com/us-news/education/harvard-accreditation-subpoena-trump-00d68304](https://www.wsj.com/us-news/education/harvard-accreditation-subpoena-trump-00d68304)

> The departments of Education and Health and Human Services notified Harvard’s accreditor that a government investigation found the school violated civil-rights law for allegedly failing to protect Jewish students from antisemitic harassment.

> The notification doesn’t remove Harvard’s accreditation—which would leave the school virtually unable to operate. Education Secretary Linda McMahon urged Harvard’s accreditor to work with the school to “keep the Department fully informed of its efforts to ensure that Harvard is in compliance with federal law and accreditor standards.”

> Also on Wednesday, the Department of Homeland Security announced it would subpoena Harvard to obtain records relevant to the enforcement of immigration laws in connection to the school’s international students.

and


[https://www.nytimes.com/2025/07/09/us/politics/trump-harvard-data-accreditation.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/09/us/politics/trump-harvard-data-accreditation.html?smid=nytcore-ios-share&referringSource=articleShare)


> The details of those offers were unclear, but Wednesday’s moves from the Trump administration suggested that the government has been dissatisfied with Harvard’s proposals.

> But Mr. Trump’s allies view the accreditation system as a potentially powerful tool in the administration’s crusade to upend higher education. Mr. Trump has described accreditation as a “secret weapon.” In April, he signed an executive order directing federal agencies to “promptly” inform accreditors about any schools his administration determines are in violation of civil rights law.

* The idea has circulated at the university for several years but gained steam after pro-Palestinian protests began disrupting campus in late 2023

[https://www.wsj.com/us-news/education/harvard-conservative-scholarship-center-trump-attacks-a187242a?st=QeDVCt&reflink=article_gmail_share](https://www.wsj.com/us-news/education/harvard-conservative-scholarship-center-trump-attacks-a187242a?st=QeDVCt&reflink=article_gmail_share)


> Harvard leaders have discussed creating a program that people briefed on the talks described as a center for conservative scholarship, possibly modeled on Stanford’s Hoover Institution, as the school fights the Trump administration’s accusations that it is too liberal.

> A spokesman for Harvard said an initiative under discussion “will ensure exposure to the broadest ranges of perspectives on issues, and will not be partisan, but rather will model the use of evidence-based, rigorous logic and a willingness to engage with opposing views.” He added that the school has been accelerating efforts to set up the initiative, which would “promote and support viewpoint diversity.”


### Columbia

*Columbia in Talks With Trump Administration Over Restoring Federal Funding


[https://www.wsj.com/us-news/education/columbia-federal-funding-negotiations-deal-trump-consent-decree-88427d9a?st=J62ErS&reflink=article_gmail_share](https://www.wsj.com/us-news/education/columbia-federal-funding-negotiations-deal-trump-consent-decree-88427d9a?st=J62ErS&reflink=article_gmail_share)

> Recent versions of a potential agreement between the school and the government haven’t included a consent decree, according to two of those people. A government task force had initially sought to put the university under a consent decree, which would have put a federal judge in charge of overseeing Columbia’s compliance.

> More recent discussions, however, have involved the possibility of a monitor or outside observer who would have less power than a federal judge.

> Columbia previously agreed to an earlier set of demands from the Trump administration, including restricting masks, empowering campus police with new powers to arrest students, and appointing a senior vice provost with broad authority to oversee the department of Middle East, South Asian and African Studies. But those concessions only kicked off formal negotiations and didn’t restore Columbia’s federal funding.

> “Our red lines remain the same,” she said. “We must maintain our autonomy and independent governance. We decide who teaches at our institution, what they teach and which students we admit.”

### Indiana

* Trump wants more apprenticeships. Indiana is going all in.


[https://www.washingtonpost.com/education/2025/07/06/trump-apprenticeship-high-school-students-college-alternative/](https://www.washingtonpost.com/education/2025/07/06/trump-apprenticeship-high-school-students-college-alternative/)

> But in the United States, the number of apprenticeships for high-schoolers is still tiny, just over one-tenth of a percent of students, according to an estimate by the think tank New America. By contrast, in Switzerland — which has been praised widely for its apprenticeship model, including by U.S. Education Secretary Linda McMahon — 70 percent of high-schoolers participate. Indiana is among several states, including Colorado, South Carolina and Washington, that have embraced the model and sent delegations to Switzerland to learn more.

### UVA

* The Trump staffers who set out to reshape their alma maters

[https://www.washingtonpost.com/politics/2025/07/11/trump-administration-reshape-alma-mater-universities-harvard/](https://www.washingtonpost.com/politics/2025/07/11/trump-administration-reshape-alma-mater-universities-harvard/)

> Less than a decade ago, Gregory W. Brown helped fundraise for the University of Virginia by posing for pictures in his old dorm room.

> Now he is central to the Trump administration’s effort to crack down on his alma mater for promoting diversity, equity and inclusion programs, as one of two Justice Department leaders and U-Va. alumni to threaten sweeping funding cuts and compel the school’s president to resign.

> Driven by personal experience, the staffers are pushing to overhaul the progressive culture they feel has come to dominate elite colleges and universities.

> Together, the staff under Trump, who prizes his degree from the University of Pennsylvania’s business school, and Vice President JD Vance, who graduated from Yale Law School, are looking to reshape academia — working to purge campuses of diversity, equity and inclusion efforts and imbue the next generations of students with their worldview.

> Just last year, Wasserman was an editor on the Harvard Law Review, one of the nation’s premier legal journals, working out of an academic building in Cambridge where he was socially alienated from his more liberal classmates and frustrated with the focus on selecting diverse voices, four of his former classmates said in interviews. This year, as a policy adviser to the president, he helped launch an investigation into that publication, the New York Times first reported.

> Harmeet Dhillon, the civil rights division director at the Justice Department who also attended U-Va., shared that frustration.

* Teaching literature is an exercise in freedom. Now ideological demands from the right are putting it in danger, writes University of VIrginia English professor Mark Edmundson.


[https://www.wsj.com/us-news/education/paradise-lost-at-the-university-of-virginia-9e59195a](https://www.wsj.com/us-news/education/paradise-lost-at-the-university-of-virginia-9e59195a)


> The members of the Jefferson Council, a conservative alumni group, have spoken much about the brainwashing and indoctrination they feel goes on in our classrooms. There may be some of that, I’ll concede, but not nearly as much as they imagine. I think that conservative students who bottle themselves up in class are more afraid of their peers’ reactions than their professors. How long before the Board of Visitors, guided by the Jefferson Council, decides it must take an active hand and begin vetting our syllabi?

> Hannah Arendt, the political philosopher, suggests that a politically unanimous condition is always something to fear. When you have a sphere without tensions, without civil conflict, tyranny is in the wings. I fear that we at UVA may be on the verge of such a condition. The road that runs from the White House, to the Justice Department, to Gov. Glenn Youngkin’s office, to our Board of Visitors looks to be all too smooth. Who is going to stop the call for political conformity as it gathers force?

### George Mason

* Trump administration increases scrutiny of another Virginia university

[https://www.washingtonpost.com/education/2025/07/10/george-mason-university-dei-probe-trump-administration/](https://www.washingtonpost.com/education/2025/07/10/george-mason-university-dei-probe-trump-administration/)


> On Thursday, the Education Department said it had opened its second civil rights investigation in two weeks into George Mason University, this one over the alleged use of race in the hiring and promotion of faculty members. The department said it had received complaints from multiple professors, including about university initiatives to make the demographics of faculty better reflect the diversity of its student body.

> “This kind of pernicious and wide-spread discrimination — packaged as ‘anti-racism’ — was allowed to flourish under the Biden Administration, but it will not be tolerated by this one,” Craig Trainor, the department’s acting assistant secretary for civil rights, said in a news release.

> This month, the Education Department notified George Mason that it had launched an investigation into the university’s alleged failure to address a hostile environment for Jewish students and faculty.

> The stacking of investigations against George Mason follows a similar pattern that occurred in the Trump administration’s inquiries into U-Va.

> Ted Mitchell, president of the American Council on Education, said the probes into George Mason show the Trump administration is not interested only in “celebrity universities” like Harvard, and that institutions of higher education nationally will be watching.

> Last week, as the Education Department’s initial inquiry into George Mason became public, Washington came under fire from various conservative commentators.

> An article in City Journal, a publication linked to the conservative think tank Manhattan Institute [Chris Rufo's fingerprints are here], called Washington a “disastrous president” whose record “warrants his resignation or dismissal.”

(also)

[https://www.propublica.org/article/george-mason-university-antisemitism-investigation-trump](https://www.propublica.org/article/george-mason-university-antisemitism-investigation-trump)

(also)

[https://www.insidehighered.com/news/quick-takes/2025/07/11/george-mason-faces-2-title-vi-investigations?utm_source=Inside+Higher+Ed](https://www.insidehighered.com/news/quick-takes/2025/07/11/george-mason-faces-2-title-vi-investigations?utm_source=Inside+Higher+Ed)

(also)

[https://www.chronicle.com/article/an-inside-job](https://www.chronicle.com/article/an-inside-job)


## Blowback

* They Want to Leave the U.S. Is a Master’s Their Ticket Out?

[https://www.insidehighered.com/news/global/study-abroad/2025/07/07/prospective-emigrants-look-higher-education-leave-us](https://www.insidehighered.com/news/global/study-abroad/2025/07/07/prospective-emigrants-look-higher-education-leave-us)

> He doesn’t speak German. He doesn’t have ancestry in Austria. And he doesn’t need a master’s—he already has one in a different field. But as one of a growing number of Americans looking to leave the U.S. due to their disagreement with President Trump’s policies, studying abroad seemed like the path of least resistance for emigrating.

> Ahead of the 2024 election, about one in five Americans said they would be interested in moving abroad if their preferred candidate did not win. Following Trump’s victory, the number of Americans searching for study abroad opportunities on the site Studyportals multiplied fivefold. CNBC reported that Google searches for “how to move to Canada” surged, especially in blue states such as Maine, Oregon, Vermont and Washington.

* What Trump’s ‘Big Beautiful’ Bill Means for NYC | THE CITY — NYC News

[https://www.thecity.nyc/2025/07/07/trump-budget-medicaid-food-stamps-local-impact/](https://www.thecity.nyc/2025/07/07/trump-budget-medicaid-food-stamps-local-impact/)

> The law punches a multi-billion dollar hole in the current state budget by reducing federal Medicaid funding, a blow that will almost certainly require Gov. Kathy Hochul to call a special legislative session in the coming months.

> The hole gets much bigger in next year’s budget, which needs to be adopted by March 31, as the governor and legislators prepare for their reelection campaigns.

> The immediate impact on the city will be less severe, but Mayor Eric Adams and the City Council will eventually be confronted with choices on whether to fill in some of the safety net gaps created by the GOP bill — or reduce aid to poor New Yorkers.

> Under the Republican law, New York will lose $7.5 billion used to cover legal immigrants in the Essential Plan, which is almost entirely paid for by the federal government. The state will then have to transfer many of those people to Medicaid, which will cost an additional $2.7 billion, since federal aid for Medicaid only covers about 56% of the actual costs.

> Since the state’s fiscal year goes to the end of March, the cost in the current budget will be about $2.5 billion. But for the 2027 fiscal year, the cost will be slightly more than $10 billion.

> New York will also immediately need to build a system to verify twice a year that Medicaid and SNAP recipients remain eligible by meeting new work requirements. The Hochul Administration estimates the cost at $500 million a year.

> The stakes are high. A survey Public Health Solutions conducted of New Yorkers with a household income of less than $60,000 found that 71% would be unable to keep insurance, and 64% said they would be unable to maintain their doctor visits.

* NYTimes: Why 1.5 Million New Yorkers Could Lose Health Insurance Under Trump Bill

[https://www.nytimes.com/2025/07/09/nyregion/trump-domestic-policy-bill-new-york-health-care.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/09/nyregion/trump-domestic-policy-bill-new-york-health-care.html?smid=nytcore-ios-share&referringSource=articleShare)

> In one key respect, the law’s impact will be felt more keenly in New York than in any other state — and it has nothing to do with Medicaid.

> Instead, it is the result of an obscure federal funding mechanism that sends billions of dollars a year to New York and nothing to most states. That money, which started flowing as a result of the Affordable Care Act, will be reduced drastically under the new law, beginning next year.

> Overall, the state could absorb a $10 billion hit annually because of the policy law. That reflects a combination of increased state expenditures and cuts in federal subsidies that support health insurance and health care for people with lower incomes.



## AI misdeeds

* Elon Musk’s Grok Is Calling for a New Holocaust

[https://www.theatlantic.com/technology/archive/2025/07/grok-anti-semitic-tweets/683463/](https://www.theatlantic.com/technology/archive/2025/07/grok-anti-semitic-tweets/683463/)

> The year is 2025, and an AI model belonging to the richest man in the world has turned into a neo-Nazi.

('nuff said)


* CEO of Elon Musk’s X, Linda Yaccarino, resigns

[https://www.washingtonpost.com/technology/2025/07/09/elon-musk-linda-yaccarino-grok-x/](https://www.washingtonpost.com/technology/2025/07/09/elon-musk-linda-yaccarino-grok-x/)




----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
