# Jul 18

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

Thanks to JC, VAC, BE for sharing links and thoughts.

## Testimony on the hill

(The testimony in front of the House Committee on Education & Workforce seems not to have dealt any serious blows to any of the three leaders, including CUNY's Chancellor -- Stefanik's predictable demand that he be fired has not been amplified, save for in the Times of India. The rope-a-dope style where responses fall back on policies and carrying them out while admitting individual tweets or comments may be reprehensible might be smart politics, but leaves a sour taste. The rope-a-dope is meant to tire people out for a counter attack, and the latter wasn't the intent. I felt there were more than a few missed opportunities:

I thought Stefanik's questioning on Abda had such a faulty premise -- she had worked at CAIR so shouldn't be employable -- needed some push back. There was not a hint of suggestion that her work for CUNY has been problematic or compromised, yet people should be fired. Plus, the NYT reported her characterization of CAIR is wholly unfounded.

Her question about CUNY clear was so poorly framed as to require a reprimand by the ranking member in his closing -- people accused deserve representation and the egregious examples of this particular case are so bad something could have been said beyond they choose their own cases.

The Hunter College questions involved showing someone's email--doxxing--and was essentially a call for punishment for involving the police in a police matter. [thanks EI]

The questions about Jewish Faculty being represented by the PSC from one congressman who tried to get the Chancellor to admit it was unfair could have had much more pushback -- this case was appealed to the supreme court which declined to hear it. Basically this congressman was asking the Chancellor to go against several judge's opinions. Maybe pointing that out shows the ridiculousness of this and other questions.

The PSC positions were mis-characterized; the PSC Chair was personally dragged and mis-characterized--the rope-a-dope that the union is an independent group could have been turned into a counterattack to the assault on faculty unions in general.

If any good came out of this, hopefully it will be the republican majority realizing these hearings have totally lost their potency. Maybe the reporting next time will pick up the consistent message of the democrats that these aren't seriously trying to understand a problem.)



* 3 College Presidents Went to Congress. Here’s What They Talked About.

[https://www.chronicle.com/article/3-college-presidents-went-to-congress-heres-what-they-talked-about](https://www.chronicle.com/article/3-college-presidents-went-to-congress-heres-what-they-talked-about)

(Thanks BE for summarizing these links, VAC for sharing)

> The congressional hearings don’t appear to pack as much punch as they once did, when it felt like college presidents’ jobs were on the line.

> The Trump administration’s campaign is like The Wizard of Oz, he [Nosanchuk, former civil-rights official] said, because it’s “projecting an intimidating, demanding, and illusory image of action, but here the man behind the curtain cancels funds for civil-rights enforcement and cancer research.”

> Rep. Virginia Foxx, a Republican of North Carolina, mentioned the fact that the influential union has passed multiple BDS resolutions, and that it has been found responsible for discrimination against a Jewish faculty member by the Equal Employment Opportunity Commission.

> In a statement Tuesday, the president of the PSC, James C. Davis, slammed Republicans’ “attempt to smear CUNY and our union as antisemitic.”

> “We do not accept the false premise that underlies today’s hearing that any campus activism in support of the Palestinian people is antisemitic, if not criminal,” Davis wrote. “As a union, we do not have a position on BDS and do not have Israel divestment policies.”


* 3 More Campus Leaders Face Congress

[https://www.insidehighered.com/news/government/politics-elections/2025/07/16/3-more-campus-leaders-face-congress](https://www.insidehighered.com/news/government/politics-elections/2025/07/16/3-more-campus-leaders-face-congress)

> For the fifth time since late 2023, congressional Republicans on Tuesday interrogated a group of university leaders about campus antisemitism. But unlike previous hearings, this one was short on fireworks and viral moments

* House Republicans Grill CUNY Chief on Campus Antisemitism Claims

[https://www.thecity.nyc/2025/07/15/cuny-felix-matos-rodriguez-antisemitism-house-elise-stefanik/](https://www.thecity.nyc/2025/07/15/cuny-felix-matos-rodriguez-antisemitism-house-elise-stefanik/)


(Grill was the headline choice of many others, mostly the slanted right side of reporting)

> Some of the toughest questioning of Matos Rodríguez again came from Stefanik, an ally of President Donald Trump who is reportedly considering a run for governor in New York after the president withdrew her nomination to be U.N. Ambassador to protect Republicans’ slim majority in the House.

> PSC president Davis then went on to decry what he saw as a clamp down on free speech across the university campuses.

> “CUNY administrators have investigated faculty for the terms in which they discuss the war in Gaza in their classes, limited the time, place, and manner for exercising the right to free expression on campus, invited police violence against non-violent student protestors, and even fired faculty in apparent retribution for their political activism,” Davis said. “It is still not enough to satisfy the new McCarthyites. Universities must stand against fascism, not accommodate it.”

* NYTimes: University Leaders Reject Republican Attacks on Campus Antisemitism

[https://www.nytimes.com/2025/07/15/us/politics/antisemitism-hearing-uc-berkeley-georgetown-cuny.html](https://www.nytimes.com/2025/07/15/us/politics/antisemitism-hearing-uc-berkeley-georgetown-cuny.html)

> On Tuesday, Republicans accused the university leaders of fostering an antisemitic climate and failing to rein in professors and students the lawmakers said were antisemitic. Democrats on the committee argued the hearing was part of a crackdown on speech that attempted to scapegoat academia for a broader societal problem.

> The university leaders, meanwhile, seemed to have learned from the past. They attempted, with apparent success, to avoid the kinds of viral moments that have characterized previous antisemitism hearings and brought down other university presidents.

> She [Stefanik] attacked CUNY for hiring a former employee of the Council on American-Islamic Relations, a Muslim civil rights organization, inaccurately suggesting that CAIR had been a “co-conspirator in a terrorist financing case.” (The group was listed as an “unindicted co-conspirator or joint venturer” in a case against a charity, the Holy Land Foundation, along with more than 200 other groups and individuals. It was not accused of a crime.)

> Responding to Ms. Stefanik’s attacks on Tuesday, CAIR’s national deputy director, Edward Ahmed Mitchell, said the “spirit of Joseph McCarthy is alive and well.” “Representing Mahmoud Khalil and others targeted by the government because they advocated for Palestinian rights is not only our prerogative as lawyers at CLEAR,” said Mr. Kassem, the CUNY law professor who founded the legal clinic, “it is also our pride and privilege.”


* Rep. Elise Stefanik skewers CUNY chancellor, calls for his ouster over ‘failed’ leadership on NYC campus antisemitism

[https://nypost.com/2025/07/15/us-news/rep-elise-stefanik-skewers-cuny-chancellor-calls-for-his-ouster-over-failed-leadership-on-nyc-campus-antisemitism/](https://nypost.com/2025/07/15/us-news/rep-elise-stefanik-skewers-cuny-chancellor-calls-for-his-ouster-over-failed-leadership-on-nyc-campus-antisemitism/)

(Cuz why? don't ask -- CUNY hired someone she didn't like who in several years has no complaints mentioned about her work; lawyers represent people before they are proven not guilty or guilty?)

> The Republican congresswoman zeroed in on Chancellor Félix Matos Rodríguez over the hiring of a chief diversity officer who previously worked for a pro-Hamas, Israel-bashing group — saying that if the CUNY boss doesn’t step down, Gov. Kathy Hochul should bounce him.

> Stefanik also asked Matos Rodríguez if he knew that law professor Ramzi Kassem, the head of CUNY Law School’s legal clinic, Creating Law Enforcement Accountability & Responsibility or CLEAR, was representing Mahmoud Khalil, the anti-Israel Columbia University protester who was detained by the Trump administration.

> In a joint press conference after the hearing with Brooklyn Councilwoman Inna Vernikov in DC, Stefanik said Matos Rodríguez had to go, and claimed Hochul was part of the problem.

(Just testing their powers; doubt either was packing today, but can't vouch for that on other days.)

(And what is wrong with the Post? In several hours of testimony they couldn't find one unflattering photo?)

* Conservatives Denounce Professor for ‘Symbolic Strike’ Post

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/07/18/republicans-denounce-georgetown-professor-post-iran](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/07/18/republicans-denounce-georgetown-professor-post-iran)

> On June 22, the United States bombed Iranian nuclear enrichment facilities. Observers wondered whether it was the start of another lengthy, destructive American war in the Middle East.

> Hours later, a conservative social media account with more than 4.3 million followers highlighted one response—allegedly from a Georgetown University professor. According to a screenshot the Libs of TikTok X account posted, Jonathan Brown, the Alwaleed bin Talal Chair of Islamic Civilization, had written on X, “I hope Iran does some symbolic strike on a base, then everyone stops.”

> What transpired is becoming a familiar story in U.S. higher education: Conservatives denounce a faculty member’s speech, members of Congress join in and eventually pressure a prestigious university’s president to publicly denounce and punish the scholar.

> Greg Afinogenov, an associate history professor and president of Georgetown’s chapter of the American Association of University Professors, said Brown has received “death threats, his family has come under attack and members of the university administration have also criticized him and disavowed him.”

> Afinogenov said the university should clarify that Brown’s post was “protected speech.”

> “This procedure of hauling members of university administrations before” a “congressional kangaroo court” harms academic freedom, he said. Administrators should push back against these “smear campaigns,” and Georgetown should articulate a policy to protect faculty and other members of the university community from retaliation for their “extramural speech,” such as on social media, he said.


* Congress attacked CUNY on falsehoods

[https://www.nydailynews.com/2025/07/18/congress-attacked-cuny-on-falsehoods/](https://www.nydailynews.com/2025/07/18/congress-attacked-cuny-on-falsehoods/)

(PSC Chair has this op-ed)

> Please, provide an email to continue reading this article for free. [Sadly]




## How best to describe the times we are in

* What Trump’s Bombast Reveals About His Vision for Higher Ed

[https://www.insidehighered.com/news/government/politics-elections/2025/07/15/how-public-attacks-harvard-harm-all-higher-ed](https://www.insidehighered.com/news/government/politics-elections/2025/07/15/how-public-attacks-harvard-harm-all-higher-ed)

> Q: Do you think the administration has a vision for higher education in particular?

> A: I think it’s a vision for America, and Trump has been remarkably clear on what that looks like. It’s an America defined pretty narrowly on racial, ethnic and religious terms. It’s an America that has a certain understanding of its history that aligns with those dominant religious, racial and ethnic groups. It’s an America that has doubled down on masculinity as its defining gender in terms of who should be in power and have power in public life. So when we talk about a vision for higher ed, it’s a higher ed that serves that.

> This is what you see in these very vague pronouncements about things like DEI. Anyone who educates or does research on anything that runs counter to that celebration of a very particularistic America is suspect and un-American. Higher ed is part of a whole set of knowledge-producing institutions in society—we can think about journalists and scientists, too— as being problematic because they serve accountability functions. They hold corporations responsible for things like polluting. They hold executives responsible for violations of democratic norms. Or, you know, they hold people in power accountable for not being good custodians of public trust. I think the administration wants to weaken that accountability function that can be played by universities because it undermines, ultimately, their ability to exercise power in the service of that larger vision of what they believe America should be.

> Q: You mentioned vague pronouncements about things like DEI. What conclusions do you draw from this tactic of sowing confusion and using unclear and undefined language?

> A: Ultimately, the end goal is control. They have a few tools to do so—legal means, regulatory means—and they have a lot of funding means to get institutions that are otherwise autonomous in civil society to comply with what they want them to do. But in the absence of those levers, what do you use? Well, you use publicity to get willing compliance or anticipatory compliance.

* Why Universities Are So Powerless in Their Fight Against Trump

[https://www.chronicle.com/article/why-universities-are-so-powerless-in-their-fight-against-trump](https://www.chronicle.com/article/why-universities-are-so-powerless-in-their-fight-against-trump)

> The administration’s moves to slash federal funding are just one part of a concerted effort to force major research universities to change how they pursue their core missions. And yet the sector’s most full-throated response — an American Association of Colleges and Universities statement signed by over 600 academic leaders — makes only vague reference to “constructive reform” while rejecting coercive uses of public funding. Widely adopted faculty resolutions calling for mutual-defense pacts amount to little more than suggestions that have yet to bear fruit. The most successful instances of collective resistance to date are four lawsuits challenging agency indirect-cost policies. By my count, 23 universities have joined at least one of those suits.

> A decentralized organizational structure puts resources and decision-making authority nearer to the ground, allowing different units of the university to prioritize the things their work requires. Faculties in business, social work, or law can make curricular, hiring, and promotion decisions largely independent of each other and of colleagues in arts and sciences, each tuning their activities to their specific needs, goals, and vision. Decentralization also explains why universities rarely articulate detailed, actionable principles that unequivocally guide institutionwide decision-making — or at least why, when they do proffer strategic plans or mission statements, the results are often anodyne.

> Universities are organized to hold contradictions, not to resolve them. Typical academic decision-making processes manage the ambiguities that multiple goals create in lieu of picking winners in the underlying conflicts. That works well in normal times, but it is disastrously bad for reaching, communicating, and acting on common priorities under threat. Yet universities’ public missions may now require them to do just that.

> Prominent conservatives generally agree that hardball tactics are necessary to compel desired changes in academe. JD Vance advocated for “honestly and aggressively” attacking universities. Leo Terrell, who heads the Task Force to Combat Antisemitism, wants financial pressures “to bring these universities to their knees.” As the conservative commentator Heather Mac Donald puts it: “The concept of academic freedom should be scaled back to allow funders — especially taxpayers — a say in how universities are run, including in what is taught.” The activist Christopher F. Rufo believes “existential terror” will provide the leverage needed to make an ultimatum stick: “Reform, or lose billions in funding.” That threat is now being carried out, and the administration’s will to back it up has been on clear display. As Robert Kelchen put it, “Every revenue source is at risk.” Federal research grants and contracts are just the beginning.

> The Columbia example shows that the decisions institutions targeted by the Trump administration face have far-reaching, complex implications that take them far outside the standard mechanisms of academic leadership. The most easily defensible choice for any institution may be to protect its interests by negotiating for the best individual deal. But, as one Harvard professor pointed out, “that might be quite bad for higher education as a whole.”

> The Harvard case has, so far, revealed this administration’s willingness to flip every policy lever available to them to reshape universities. It suggests a more complex landscape and more wrenching decisions are in store — choices that will certainly pit a university against itself, further fragmenting and undermining coordinated responses.

* NYTimes: Trump Is Winning the Race to the Bottom

[https://www.nytimes.com/2025/07/17/opinion/trump-america-china.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/17/opinion/trump-america-china.html?smid=nytcore-ios-share&referringSource=articleShare)

> Populists are anti-intellectual. President Trump isn’t pumping research money into the universities; he’s draining it out. The administration is not tripling the National Science Foundation’s budget; it’s trying to gut it. The administration is trying to cut all federal basic research funding by a third, according to the American Association for the Advancement of Science. A survey by the journal Nature of 1,600 scientists in the United States found that three-quarters of them have considered leaving the country.

> America’s leaders understood that a superpower rivalry is as much an intellectual contest as a military and economic one. It’s who can out-innovate whom. So they fought the Soviet threat with education, with the goal of maximizing talent on our side.

> “One reason the U.S. economy had such a good Cold War was that the American university had an ever better one,” the historian Hal Brands writes in his book “The Twilight Struggle.” Federal support for academic research rose to $1.45 billion in 1970 from $254 million in 1958. Earlier in that century, American universities lagged behind their “best” European peers, Brands observes; by the end of the Cold War, they dominated the globe.

## Shared governance

* New Report on the State of Academic Governance in Community Colleges

(Thanks to JC and VAC)

[https://www.aaup.org/news/new-report-state-academic-governance-community-colleges](https://www.aaup.org/news/new-report-state-academic-governance-community-colleges)

> At most responding institutions, and especially at responding institutions with tenure systems, faculty authority is consistent with AAUP-recommended governance standards in decision-making about programmatic, departmental, and institutional curricula; teaching assignments; salary policies; and faculty searches, evaluations, and tenure and promotion standards.

> However, in several decision-making areas, including budgets, buildings, provost selection, and strategic planning, community college faculty have few meaningful opportunities to participate. In these areas, community colleges deviate from the principles set forth in the AAUP’s 1966 Statement on Government of Colleges and Universities, which emphasizes faculty involvement in personnel decisions and budget preparation.

> Statistically significant differences in the level of faculty authority between unionized and nonunionized colleges appear in only three of the twenty-six areas, a finding that mirrors that in the AAUP’s 2021 Shared Governance Survey of four-year institutions. Specifically, institutions where the faculty engages in collective bargaining have higher levels of faculty authority in areas related to salary policies teaching loads, and, in the case of community colleges, full-time non-tenure-track faculty promotion decisions.

> Across most areas of academic and personnel decision-making, levels of faculty authority are lower at community colleges than at four-year institutions. However, faculty members at community colleges have more involvement in salary policies than those at four-year institutions; the difference is likely related to the higher prevalence of institutions with collective bargaining in the community college sector.

## Freedom of expression

* Texas just gutted free speech on college campuses. Is your state next?

[https://www.washingtonpost.com/opinions/2025/07/14/texas-campus-free-speech/](https://www.washingtonpost.com/opinions/2025/07/14/texas-campus-free-speech/)

>  Across the country, state legislators have been racing to exert new influence over free expression in higher education. Now, Texas has surged to the forefront, closing its 2025 legislative session by passing two alarming laws that take effect Sept. 1.

> the new laws amount to a stunningly aggressive legislative crackdown on campus protest (S.B. 2972) and academic shared governance (S.B. 37) at public colleges and universities. The laws will not just silence dissent and undermine faculty authority in Texas; they provide a blueprint for how to dismantle academic freedom and chill speech on campus state by state.

> Now, some of the same legislators have done an about-face. The campus protest law actually directs public colleges and universities to implement a version of free-speech zones and adopt sweeping limitations on protests. Encampments? Banned. Megaphones or speakers during “class hours”? Forbidden — if anyone claims your “expressive activity” is one that “intimidates others” or “interferes” with an employee’s duties. Even wearing a mask during a protest — something many do for safety — could land a student or employee a disciplinary hearing resulting in “sanctions.” And any expressive activity between 10 p.m. and 8 a.m. is off-limits altogether.

> State law defines “expressive activity” as “any speech or expressive conduct protected by the First Amendment” — speeches, writing, art, symbolic actions, even just talking to your friends. It’s problematic enough that legislators seek to prohibit nighttime or early-morning protest activity, but the language could affect late-night art events, student journalists, and even assigned research, course or thesis work for students or faculty in the habit of burning the midnight oil. The new law is so absurdly broad it could theoretically be used to stop a group of students from discussing politics on a campus bench at night. That’s not security; it’s suppression.

> And this is just half the story.

> The second new law in Texas is an outright power grab dismantling shared governance, the cornerstone of U.S. higher education. Typically, higher education institutions have democratic systems to share power and foster collaboration among administrators, governing boards and faculty. Faculty senates, whose members are typically elected by faculty, exercise authority over curricular matters, academic policies and graduation requirements. In addition, they often play a role in general institutional decisions, such as related to planning, budgeting or the evaluation of administrators.

> The Texas legislature obliterates these traditions, stripping faculty of any meaningful decision-making role in how their institutions are run. Under this law, faculty senates at public universities and colleges can now exist only if permitted by the institutions’ governing boards — the oversight bodies whose members are politically appointed by the state governor. In mockery of democratic principles, half of the faculty senate members must be chosen by the university president, and administrators can remove faculty for not conducting their duties within vague “senate parameters.”

> To make matters worse, the law installs a governor-appointed “ombudsman” with sweeping enforcement powers. This political appointee will be charged with monitoring compliance with state laws and can recommend that a public university or college lose all state funding unless it complies.


### Anti-woke/anti-DEI is simply racism

* Tech billionaire Trump adviser Marc Andreesen says universities will ‘pay the price’ for DEI


[https://www.washingtonpost.com/technology/2025/07/12/marc-andreessen-private-chat-universities-diversity/](https://www.washingtonpost.com/technology/2025/07/12/marc-andreessen-private-chat-universities-diversity/)

> The investor described a “counterattack” against universities in his messages and called for the National Science Foundation, a federal research funding agency, to receive “the bureaucratic death penalty.”

> “The universities are at Ground Zero of the counterattack” from Trump voters, Andreessen wrote, alleging colleges favored immigrants over Americans and promoted DEI, or diversity, equity, and inclusion policies intended to increase race and gender representation.

> “The combination of DEI and immigration is politically lethal,” Andreessen wrote. “When these two forms of discrimination combine, as they have for the last 60 years and on hyperdrive for the last decade, they systematically cut most of the children of the Trump voter base out of any realistic prospect of access to higher education and corporate America.”

(Yeah, right)

* * NYTimes: Inside the Conservative Campaign That Took Down the U.Va. President

[https://www.nytimes.com/2025/07/14/us/politics/university-virginia-president-trump-dei-jefferson-council.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/14/us/politics/university-virginia-president-trump-dei-jefferson-council.html?smid=nytcore-ios-share&referringSource=articleShare)

> For years, the group [The Jefferson Council] had railed against the university’s president, James E. Ryan, for his robust promotion of campus diversity initiatives.

> The Justice Department then hired a lawyer to help enforce those orders at the Office of Civil Rights: Gregory W. Brown, a University of Virginia alumnus and donor.

> The Jefferson Council and the Office of Civil Rights separately denied in interviews that they had worked in concert. But the council had at least set the table for what came next. And in his new position, Mr. Brown helped engineer an unusual and concerted pressure campaign that would lead to Mr. Ryan’s resignation.

> And in his new position, Mr. Brown helped engineer an unusual and concerted pressure campaign that would lead to Mr. Ryan’s resignation.

> That campaign showed just how far the Office of Civil Rights — which had for decades been at the center of the fight for racial equality — would go to take on universities that it views as hostile to its new agenda. By issuing a stream of demands and threats, the office essentially sped past the university board, appointed by the governor, that has oversight of its flagship public university.

> “What the Justice Department did was very similar to what President Eisenhower did,” Mr. Gardner [the Jefferson Council president] said, comparing the Trump administration’s actions to the 1957 White House decision to dispatch troops to Little Rock, Ark., to enforce the Supreme Court’s school desegregation decision, Brown v. Board of Education.

(Uhh...)

> There were other requests [In addition to the 7 letters]. The New York Times reported that the Trump administration had privately demanded Mr. Ryan’s ouster to help resolve its investigation into the school’s diversity, equity and inclusion efforts, according to three people briefed on the matter.

> Ms. Dhillon, in an interview with the Times, denied that her office had pressured the university to remove its president.



## Visas

* State Department official defends canceling visas of pro-Palestinian academics - POLITICO

[https://www.politico.com/news/2025/07/11/state-official-testimony-trump-deportations-00449634](https://www.politico.com/news/2025/07/11/state-official-testimony-trump-deportations-00449634)

> Armstrong insisted that no visas were revoked based on “protected speech,” but when asked if visas were sometimes pulled due to students’ “political viewpoints,” he gave a more complex answer.

> Former Columbia student Mahmoud Khalil’s visa was canceled due to his “role in antisemitic protests and disruptive activities that foster a hostile environment towards Jewish students in the United States,

> former Columbia student, Mohsen Mahdawi, was “involved in leadership of disruptive protests at Columbia University that included antisemitic conduct and calling for the destruction of Israel,”

> Tufts University student Rumeysa Ozturk had her visa revoked as a result of “her antisemitic activities in the U.S.” and for “creating a hostile environment for Jewish students and indicating support for a designated terrorist organization,”

(See also)

[https://knightcolumbia.org/cases/aaup-v-rubio](https://knightcolumbia.org/cases/aaup-v-rubio)



## Funding cuts

* Higher-Ed Associations Pitch an Alternative to Trump’s Cap on Research Funding

[https://www.chronicle.com/article/higher-ed-associations-pitch-an-alternative-to-trumps-cap-on-research-funding](https://www.chronicle.com/article/higher-ed-associations-pitch-an-alternative-to-trumps-cap-on-research-funding)

> The Joint Associations Group, or JAG, which includes the Association of American Universities (AAU), the American Council on Education (ACE), and the Association of Public and Land-grant Universities (APLU), announced its proposal on Friday. The coalition sees its plan as a middle ground, one that responds to long-held gripes about how indirect costs are administered while lessening the billions in lost revenue for universities under the 15-percent indirect-cost cap proposed by several federal agencies, among them the National Institutes of Health, the National Science Foundation, and the Departments of Defense and Energy.

> The plan’s true effect on how much universities would receive for indirect costs is unclear. H. Holden Thorp, editor in chief of the Science family of journals and a former university chancellor, who is not part of JAG but has reviewed the proposal, said such a fundamental change to how universities balance their research budgets will be costly. The amount of funding received under the FAIR model “absolutely will be less,” he said, but “it won’t be as bad as it was going to be” under the Trump administration’s proposed 15-percent cap.

### NSF

* House Appropriators Propose 23% Cut to NSF

[https://www.insidehighered.com/news/quick-takes/2025/07/15/house-appropriators-propose-23-cut-nsf](https://www.insidehighered.com/news/quick-takes/2025/07/15/house-appropriators-propose-23-cut-nsf)

> House Republicans want to cut the National Science Foundation’s funding by about $2 billion, according to budget documents released Monday.

> Still, funding for NSF is already one point of disagreement between House and Senate appropriators. Last week, Senate Republicans indicated that they would cut only about $16 million from NSF, leaving the agency with just over $9 billion.

> The House plan, which would give NSF about $7 billion, is just a proposal and doesn’t go as far as President Donald Trump’s proposed budget for fiscal year 2026, which cuts more than $5 billion from the agency.



### DOE

* NYTimes: Trump Administration Live Updates: Supreme Court Clears Way for Dismantling of Education Department

[https://www.nytimes.com/live/2025/07/14/us/trump-news?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/live/2025/07/14/us/trump-news?smid=nytcore-ios-share&referringSource=articleShare)

> The order is a significant victory for the administration and could ease President Trump’s efforts to sharply curtail the federal government’s role in the nation’s schools.

> It also represents an expansion of presidential power, allowing Mr. Trump to functionally eliminate a government department created by Congress, without legislators’ input.

> It comes after a decision by the justices last week that cleared the way for the Trump administration to move forward with cutting thousands of jobs across a number of federal agencies, including the Departments of Housing and Urban Development, State and Treasury.

> The order by the court was unsigned and gave no reasoning, as is typical in such emergency applications. No vote count was given, which is usual for emergency orders, but Justice Sonia Sotomayor wrote a dissent, joined by the court’s other two liberals, Justices Elena Kagan and Ketanji Brown Jackson.

> The order is technically temporary, applying while appeals proceed through the courts. In practice, thousands of fired workers whom a Boston judge had ordered be reinstated are now again subject to removal from their jobs.

(Sotamayor)

> The President must take care that the laws are faithfully executed, not set out to dismantle them. That basic rule undergirds our Constitution’s separation of powers. Yet today, the majority rewards clear defiance of that core principle with emergency relief. Because I cannot condone such abuse of our equitable authority, I respectfully dissent.

(Also)


[https://www.washingtonpost.com/politics/2025/07/14/supreme-court-education-department-/](https://www.washingtonpost.com/politics/2025/07/14/supreme-court-education-department-/)


[https://www.wsj.com/politics/policy/supreme-court-ruling-trump-education-department-workers-a2baa879?st=DhfBSW&reflink=article_gmail_share](https://www.wsj.com/politics/policy/supreme-court-ruling-trump-education-department-workers-a2baa879?st=DhfBSW&reflink=article_gmail_share)


* The Education Department Got a Green Light to Shrink. Here Are 3 Questions About What’s Next.

[https://www.chronicle.com/article/the-education-department-got-a-green-light-to-shrink-here-are-3-questions-about-whats-next](https://www.chronicle.com/article/the-education-department-got-a-green-light-to-shrink-here-are-3-questions-about-whats-next)

> McMahon said in her Monday statement that the “reduction in force to promote efficiency and accountability and to ensure resources are directed where they matter most — to students, parents, and teachers” — would be carried out promptly.

> Trump officials have said that the Office for Civil Rights’ caseload would likely be handled by the Department of Justice, while enforcement of the Individuals With Disabilities Education Act could fall to the Department of Health and Human Services.

> Whether federal money, in the form of financial aid and grants for institutions, will be doled out on time is a chief concern for higher ed. It’s a particularly sore subject after last year’s botched rollout of a new Free Application for Federal Student Aid (FAFSA), which left some students in limbo as they awaited months-late aid offers.

## Congressional actions

* President Trump’s big tax-and-spending law includes new restrictions on how much students can borrow and how they repay. Here’s a guide to what is changing.

[https://www.wsj.com/personal-finance/trump-student-loans-tax-spending-bill-9dfc96eb?st=PG4sQs&reflink=article_gmail_share](https://www.wsj.com/personal-finance/trump-student-loans-tax-spending-bill-9dfc96eb?st=PG4sQs&reflink=article_gmail_share)



## State actions

* Legislatures Require Colleges to Cut Degrees in Low Demand

[https://www.insidehighered.com/news/government/state-policy/2025/07/15/latest-legislative-directives-cut-degrees-low-demand](https://www.insidehighered.com/news/government/state-policy/2025/07/15/latest-legislative-directives-cut-degrees-low-demand)

> But at least three Republican-dominated states—Indiana, Ohio and Utah—passed specific laws this year that push institutions to eliminate degree programs that graduate few students. In a similar vein, Texas passed a law going after academic minors and certificate programs with low enrollments. It worries faculty and scholarly groups, who stress that the number of majors in a program isn’t the only or best way to gauge its worth.

> “Campuses are forced to respond to legislative mandates that have arisen from a narrow understanding of what higher education is,” said Paula Krebs, executive director of the Modern Language Association. Students who pursue public higher education will be “getting a reduced version of what a degree should be,” she said.


## Institutional assaults

* NYTimes: How Trump’s crackdown on universities is affecting the world

[https://www.nytimes.com/interactive/2025/07/13/us/2025-06-06-int-science-reaction-index.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/interactive/2025/07/13/us/2025-06-06-int-science-reaction-index.html?smid=nytcore-ios-share&referringSource=articleShare)

> Universities are an easy target for right-wing populists. Polls show that a lot of Americans consider them too liberal, too expensive and too elitist, and not entirely without reason.

(Why the lede needs to add that last bit is beyond me...)

> Today, the biggest beneficiary could be China and Chinese universities, which have been trying to recruit world-class scientific talent for years. Now Mr. Trump is doing their work for them. One indication of the success of China’s campaign to attract the best and brightest is Africa, the world’s youngest continent. Africans are learning Mandarin in growing numbers. Nearly twice as many study in China as in America.

> Could America gamble away its scientific supremacy in the service of ideology? It has happened before. Under the Nazis, Germany lost its scientific edge to America in the space of a few years. As a German, my brain may wander too readily to the lessons of the 1930s, but in this case the analogy feels instructive. Several of my colleagues covering the fallout from the crackdown on international students and researchers pointed to Hitler’s silencing of scientists and intellectuals.

> I don't sense a big change in the mood in India yet. The United States still holds a lot of soft power and remains very attractive to Indians. In fact, many Indians are seeing something that is pretty familiar to them. They’re saying, “Welcome to the world as we have experienced it for the past few years.” The government under Narendra Modi has definitely cracked down on free speech. It has tried to quash dissenting voices, and it has also leaned on academics and has tried to squeeze certain research institutions that it considers too liberal. And there has been a demonization of the Muslim minority, which make up about 15 percent of the population. There are a lot of similarities to Trump’s America. Everyone in the world is just trying to understand what Trump's actions mean for their own countries. So India's experience can be instructive in making sense of this moment. [Anupreeta Das is a South Asia correspondent for the Times,]

> China really wants to become a center for international education, because it sees that as a key ingredient for building its reputation as a global superpower. American universities have long been a source of American soft power. China wants Chinese universities to be a source of Chinese soft power. And now Trump is doing their work for them. You can see that in China’s rhetoric and messaging. It’s trying to portray itself as open and international, everything that the Trump administration is turning away from. [Vivian Wang is a correspondent for the Times in Beijing]

### Accreditation

* Trump wields his ‘secret weapon’: College accreditation

[https://www.washingtonpost.com/education/2025/07/12/trump-college-accreditation-political-influence/](https://www.washingtonpost.com/education/2025/07/12/trump-college-accreditation-political-influence/)

("his" What about just saying weaponizing ...)

> President Donald Trump and his allies are using a little-known but powerful corner of higher education — college accreditation — to exert pressure on colleges and universities, an effort that threatens the independence of accreditors and the stability of the institutions they approve.

> This week, the Education and Health and Human Services departments encouraged Harvard University’s accreditor to take action against the Ivy League school for allegedly violating the civil rights of Jewish students. The New England Commission of Higher Education, which accredits Harvard, said it has given the university until Aug. 15 to respond and will take up the matter at a previously scheduled meeting in September.

> The administration took a similar step in early June over Columbia University’s alleged civil rights violations. By the end of June, Columbia’s accreditor, the Middle States Commission on Higher Education, issued the school a noncompliance warning. Middle States did not immediately respond to requests for comment.

> “It’s unusual for [the Office of Civil Rights] to directly involve itself in accrediting matters,” said John R. Przypyszny, a lawyer who specializes in accreditation.

> While the Trump administration has no direct control over whether the schools remain accredited, it could punish accreditors for failing to act by stripping them of the authority needed to operate. And a recent move by the Education Department is raising questions about whether the administration is dangling that possibility over Harvard and Columbia’s accreditors.

> A day after notifying Columbia’s accreditor of the Ivy League school’s alleged violations in June, the Education Department postponed a meeting of the federal advisory committee that oversees accreditors from July to October. The 18-member committee was scheduled to vote this summer on whether Middle States and the New England Commission should remain certified to accredit colleges.

> By the time the committee meets this fall, the terms of six of its members will have expired. The House, Senate and education secretary take turns appointing members, and this time the secretary will fill all six seats. That gives the Trump administration a chance to select people who are aligned with its ideology on higher education.

> “It seems like they’re trying to fix the vote,” said Robert Shireman, a member of the committee who is also a senior fellow at the left-leaning Century Foundation.

> Several committee members said the Education Department flouted the rules of the panel, which says only the chair can set a meeting schedule. When Zakiya Smith Ellis, who assumed the role of chair in February, pointed that out, she said the department told her it did not recognize her as chair because she took over the position when the previous chair resigned.


* Despite Reservations, Florida Approves New Accreditor

[https://www.insidehighered.com/news/government/state-policy/2025/07/11/despite-reservations-florida-bog-approves-new-accreditor](https://www.insidehighered.com/news/government/state-policy/2025/07/11/despite-reservations-florida-bog-approves-new-accreditor)

> The decision came after about an hour of heated discussion between board members and the State University System of Florida’s chancellor regarding details of the plan.

> Chancellor Raymond Rodriguez argued that the new accreditor, called the Commission for Public Higher Education, would eliminate the bureaucracy that comes with existing accrediting agencies and focus specifically on the needs of public universities.

> “The Commission for Public Higher Education will offer an accreditation model that prioritizes academic excellence and student success while removing ideological bias and unnecessary financial burdens,” he said. “Through the CPHE, public colleges and universities across the country will have access to an accreditation process that is focused on quality, rooted in accountability and committed to continuous improvement.”

> But before voting in favor of the motion, board members repeatedly pushed back, arguing that the plans for starting an accreditor from scratch were half-baked.


### Harvard

* NYTimes: As Harvard and Trump Head to Court, the Government Piles on the Pressure

[https://www.nytimes.com/2025/07/18/us/harvard-trump-head-to-trial.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/18/us/harvard-trump-head-to-trial.html?smid=nytcore-ios-share&referringSource=articleShare)

> Last week, U.S. Immigration and Customs Enforcement served subpoenas to Harvard with sprawling demands that included payroll records, years of disciplinary files and any videos Harvard had of international students protesting on campus since 2020, according to two people familiar with the subpoenas, some of which were reviewed by The New York Times. The agency gave the university a breakneck one-week deadline for compliance.

> Also this month, the administration formally accused the school of civil rights violations, arguing that Harvard had failed to protect Jewish people on campus. The government also complained to the university’s accreditor, which could eventually jeopardize Harvard students’ access to federal financial aid.

> Harvard leaders are well aware that a long fight with the government is perilous, threatening jobs, projects, reputations and academic independence. Some inside the university have feared that civil inquiries could become criminal matters.

> Before the lawsuit, the administration sent Harvard an extraordinary list of conditions, including new policies on hiring, admissions and faculty influence, compulsory reports to the government and audits of academic programs and departments. Since then, although officials acknowledged that sending the letter was a mistake, the government has barely budged from the demands.



### Columbia

* NYTimes: Columbia and Trump Near a Deal, With School Possibly Paying Millions

[https://www.nytimes.com/2025/07/11/nyregion/columbia-university-trump-deal-antisemitism.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/11/nyregion/columbia-university-trump-deal-antisemitism.html?smid=nytcore-ios-share&referringSource=articleShare)

> The existence of a potential deal was confirmed by a third person, who, like the others, spoke on the condition of anonymity to describe sensitive negotiations.

(Methinks this may be a planted story to put pressure on Columbia, but what do I know.)

> A university spokeswoman on Friday night did not confirm details of the deal or the potential White House meeting. “The university is focused on advancing the discussions with the federal government. There is no resolution at this time,” the spokeswoman, Virginia Lam Abrams, said.


> The deal could include $200 million or more in compensation paid by Columbia for alleged civil rights violations. Columbia officials are expected to meet with Trump aides next week at the White House to finalize the deal, said one of the people familiar with the discussions.

> And Harvard, despite its litigation, has also restarted talks with the Trump administration regarding the return of billions of dollars in federal research funding that have been cut.

> The current draft of the deal, which was first reported by The Wall Street Journal and The Free Beacon, does not go as far in exerting federal authority over the university as an earlier version that was circulated in April.

> The negotiations with Columbia have been directed out of the White House by a team led by a Trump adviser, Stephen Miller, with additional involvement of an interagency task force on antisemitism.

(Also)

[https://www.wsj.com/us-news/education/trump-columbia-civil-rights-settlement-86f64531](https://www.wsj.com/us-news/education/trump-columbia-civil-rights-settlement-86f64531)

[https://freebeacon.com/campus/columbia-nears-deal-with-trump-administration-university-will-pay-discrimination-victims-reveal-more-admissions-and-hiring-data-but-will-dodge-harsher-measures-like-governance-shakeup/](https://freebeacon.com/campus/columbia-nears-deal-with-trump-administration-university-will-pay-discrimination-victims-reveal-more-admissions-and-hiring-data-but-will-dodge-harsher-measures-like-governance-shakeup/)

(From Wikipedia "The New York Times credited the Free Beacon with breaking, together with Chris Rufo,[23] and subsequently expanding, reportage on the plagiarism accusations against Harvard President Claudine Gay" which is about the nicest way to say they made mountains out of mole hills)

* NYTimes: Columbia Expands Efforts to Fight Antisemitism as Trump Deal Seems Near

[https://www.nytimes.com/2025/07/15/nyregion/columbia-plan-to-fight-antisemitism.html](https://www.nytimes.com/2025/07/15/nyregion/columbia-plan-to-fight-antisemitism.html)

> Ms. Shipman announced that the changes would include formally incorporating the International Holocaust Remembrance Alliance’s definition of antisemitism into the work of a recently established office at Columbia that considers complaints of discrimination and discriminatory harassment.

> In addition, Columbia will appoint two new coordinators to oversee investigations into claims of discrimination based on race, color, religion, sex or national origin. Those coordinators will produce a publicly available report each year about discrimination investigations and their results.

> The university will also institute new educational programs about antisemitism for students and faculty and staff members, including those developed by national organizations such as Project Shema, a training and support organization, and the Anti-Defamation League. And it will reaffirm that it has zero tolerance for discrimination and harassment based on protected traits, including Jewish and Israeli identity.

> Joseph Howley, a professor of classics and supporter of the pro-Palestinian movement on campus, was critical for different reasons. The definition of antisemitism being adopted by the university, he said, “is not informed by scholarly expertise or even best practice. So it’s not the best framework for confronting hate speech, and it’s not going to solve real problems of discrimination or harassment.”

* Anti-Semitism Gets the DEI Treatment - The Atlantic

[https://www.theatlantic.com/ideas/archive/2025/07/columbia-anti-semitism-trump/683586/](https://www.theatlantic.com/ideas/archive/2025/07/columbia-anti-semitism-trump/683586/)

> To do the same thing over and over and expect a different result is one definition of insanity. According to Robert Shibley, a special counsel of the Foundation for Individual Rights and Expression (FIRE), it’s also Columbia University’s approach to addressing anti-Semitism on campus.

> On Tuesday, Claire Shipman, Columbia’s acting president, announced in an email to the community that the university would take several steps to quell anti-Semitism on campus. Columbia will appoint Title VI and Title VII coordinators to review allegations of discrimination. It will launch new programming around anti-Jewish discrimination, send out regular messages affirming its zero-tolerance policy on hate, and use the International Holocaust Remembrance Alliance’s definition of anti-Semitism for certain disciplinary proceedings. In her message, Shipman promised that the university would continue making reforms until it had stamped out anti-Semitism. “In a recent discussion, a faculty member and I agreed that anti-Semitism at this institution has existed, perhaps less overtly, for a long while, and the work of dismantling it, especially through education and understanding, will take time,” she wrote.

> The message was notable for how closely it resembled the communications that university presidents have previously sent out about other forms of discrimination. Replace the references to “anti-Semitism” with “racism,” and Shipman’s message could practically have been lifted from the statements of summer 2020



### George Mason

* Why attack colleges? To open students’ minds or blow up institutions?

[https://www.washingtonpost.com/opinions/2025/07/16/trump-dei-george-mason-university/](https://www.washingtonpost.com/opinions/2025/07/16/trump-dei-george-mason-university/)

> Now, the mission has gone off the rails: The Trump administration is coming for George Mason University, one of Virginia’s largest colleges, which has done more than almost any other campus in the country to become conservative-friendly.

> Sadly, George Mason’s course will likely be determined not by its president or faculty, but by politicians in Richmond and judges in courtrooms. A Fairfax County judge is expected to rule later this month on a move by Democrats in the Virginia Senate to block approval of Gov. Glenn Youngkin’s (R) nominees to the school’s board. And when Virginia voters choose a new governor this fall, they will be deciding who gets to nominate board members next year.

> There was a time, not long ago, when governance of public universities was a bipartisan effort, devoted to building civic knowledge and advancing the skills of the next generation. Politics and culture wars weren’t the primary focus.

> we have unthinking attacks on any and all colleges — another example of government gone wild. Trump campaigned last year on smacking down elite colleges’ “Marxist assault on our American heritage and Western civilization itself.” What’s he delivering, perversely enough, is his own reactionary assault on the institutions that transmit our heritage to the inheritors of our democracy.


* George Mason President Defends Univ. Against Trump

[https://www.insidehighered.com/news/quick-takes/2025/07/18/gmu-president-responds-civil-rights-investigation](https://www.insidehighered.com/news/quick-takes/2025/07/18/gmu-president-responds-civil-rights-investigation)

> “I can assure you that George Mason has always operated with a commitment to equality under the law, ever since our inception,” he wrote. ”It is simply the Mason way, and in my experience, it has not discriminated based on race, color, national origin, or otherwise. Our diversity efforts are designed to expand opportunity and build inclusive excellence—not to exclude or advantage any group unlawfully.”

> He offered a brief history of Title VI—which prohibits discrimination on the basis of race, color and national origin in federally funded programs—and the rest of the Civil Rights Act of 1964. Then, without naming any names, he essentially accused the Trump administration of willfully misinterpreting the law.

> “Today, we are seeing a profound shift in how Title VI is being applied,” he wrote. “Longstanding efforts to address inequality—such as mentoring programs, inclusive hiring practices, and support for historically underrepresented groups—are in many cases being reinterpreted as presumptively unlawful. Broad terms like ‘illegal DEI’ are now used without definition, allowing virtually any initiative that touches on identity or inclusion to be painted as discriminatory.

* Trump administration expands scrutiny of George Mason University

[https://www.washingtonpost.com/education/2025/07/17/george-mason-doj-investigation/](https://www.washingtonpost.com/education/2025/07/17/george-mason-doj-investigation/)

> The investigation [into the alleged use of race in hiring and promotions at George Mason University ] is the third launched by the administration in recent weeks into the policies and practices at the Northern Virginia university, and the first inquiry into the school led by the Justice Department.

### UVA

* As U-Va. president leaves, faculty say board failed to protect university


[https://www.washingtonpost.com/education/2025/07/11/university-of-virginia-faculty-board-no-confidence-ryan/](https://www.washingtonpost.com/education/2025/07/11/university-of-virginia-faculty-board-no-confidence-ryan/)

> University of Virginia faculty passed a vote of no confidence Friday in the school’s governing body, saying it failed to protect against “outside interference” by the Trump administration that led to the eventual resignation of President James E. Ryan.

> The vote by the U-Va. faculty senate — which came on Ryan’s last day in office — called on the board to provide faculty with an “immediate and complete accounting” of its response to inquiries by the Justice Department in recent months.

> The board leaders also said the Justice Department investigations were ongoing and that they would work hard to reach a voluntary settlement with the Trump administration as soon as they could.




### Title VI

* Now Hiring: Title VI Coordinators

[https://www.insidehighered.com/news/students/diversity/2025/07/14/colleges-hire-title-vi-coordinators-amid-federal-scrutiny](https://www.insidehighered.com/news/students/diversity/2025/07/14/colleges-hire-title-vi-coordinators-amid-federal-scrutiny)


> in fiscal year 2022, before the Israel-Hamas war began, allegations of Title VI violations made up only 17.3 percent of the complaints OCR received, in comparison with Title XI (49.2 percent) and the Americans with Disabilities Act and Section 504 (33.4 percent), which protect against disability discrimination.

> The number of Title VI complaints increased 29.4 percent over the next two years. Complaints related to shared ancestry increased sevenfold from 2023 to 2024.

> In other cases, it was a proactive step. In April, the State University of New York system, the largest public college system in the nation, required each of its campuses to bring on a Title VI coordinator by fall 2025.

> “We really have tried to be very thoughtful about ensuring that all of our campuses are safe and supportive environments free from harassment and discrimination. We take Title IX enforcement seriously,” said SUNY chancellor John B. King in an interview.

## Blowback

* China “Will Blow Us Away” if Trump Destroys U.S. Universities

[https://www.insidehighered.com/news/government/science-research-policy/2025/07/17/china-will-blow-us-away-if-trump-destroys-us](https://www.insidehighered.com/news/government/science-research-policy/2025/07/17/china-will-blow-us-away-if-trump-destroys-us)

> The first Nobel Prize–winning scientist to join a White House cabinet, Steven Chu made history when he became Barack Obama’s energy secretary in 2009. But his move to Washington cost him an incredible $300 million.

> “I joined the Nvidia board in 2004, before the company took off, but I had to sell my shares in 2009 when I joined government,” Chu said about his early involvement in the microchip firm that recently became the world’s most valuable company with a $4 trillion capitalization.

> Sanguine about his lost wealth, Chu’s main takeaway from Nvidia is not his own misfortune. Instead, he worries that this American success story—co-created by a Taiwanese-born Stanford graduate, employing foreign-born engineering talent—might not have been able to happen today given the double whammy faced by U.S. academia: massive cuts to federal science budgets and an immigration crackdown deterring many students, particularly from China, from applying to U.S. institutions.

> Without America’s outstanding universities and with its foreign talent pool diminished, China’s path to global dominance will be immeasurably easier, predicted Chu. “Trump is perfectly willing to destroy institutions that any country in the world would give its eyeteeth for,” he said.


## AI misdeeds

* What Happens After A.I. Destroys College Writing?

[https://www.newyorker.com/magazine/2025/07/07/the-end-of-the-english-paper](https://www.newyorker.com/magazine/2025/07/07/the-end-of-the-english-paper)

> He opened Claude on his laptop. I noticed a chat that mentioned abolition. “We had to read Robert Wedderburn for a class,” he explained, referring to the nineteenth-century Jamaican abolitionist. “But, obviously, I wasn’t tryin’ to read that.” He had prompted Claude for a summary, but it was too long for him to read in the ten minutes he had before class started. He told me, “I said, ‘Turn it into concise bullet points.’ ” He then transcribed Claude’s points in his notebook, since his professor ran a screen-free classroom.


> I teach at a small liberal-arts college, and I often joke that a student is more likely to hand in a big paper a year late (as recently happened) than to take a dishonorable shortcut.

> There are no reliable figures for how many American students use A.I., just stories about how everyone is doing it. A 2024 Pew Research Center survey of students between the ages of thirteen and seventeen suggests that a quarter of teens currently use ChatGPT for schoolwork, double the figure from 2023. OpenAI recently released a report claiming that one in three college students uses its products. There’s good reason to believe that these are low estimates.

> Corey Robin, a writer and a professor of political science at Brooklyn College, read the early stories about ChatGPT with skepticism. Then his daughter, a sophomore in high school at the time, used it to produce an essay that was about as good as those his undergraduates wrote after a semester of work. He decided to stop assigning take-home essays. For the first time in his thirty years of teaching, he administered in-class exams.

> Barry Lam teaches in the philosophy department at the University of California, Riverside, and hosts a popular podcast, Hi-Phi Nation, which applies philosophical modes of inquiry to everyday topics. He began wondering what it would mean for A.I. to actually be a productivity tool. ... If students were learning things faster, then it stood to reason that Lam could assign them “something very hard.” He wanted to test this theory, so for final exams he gave his undergraduates a Ph.D.-level question involving denotative language and the German logician Gottlob Frege which was, frankly, beyond me.

> “They fucking failed it miserably,” he said. He adjusted his grading curve accordingly.

> When classes were over and students were moving into their summer housing, I e-mailed with Alex, who was settling in in the East Village. He’d just finished his finals, and estimated that he’d spent between thirty minutes and an hour composing two papers for his humanities classes. Without the assistance of Claude, it might have taken him around eight or nine hours. “I didn’t retain anything,” he wrote. “I couldn’t tell you the thesis for either paper hahhahaha.” He received an A-minus and a B-plus. ♦

* NYTimes: I’m Watching the Sacrifice of College’s Soul

[https://www.nytimes.com/2025/07/14/opinion/college-soul-ai-education.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/14/opinion/college-soul-ai-education.html?smid=nytcore-ios-share&referringSource=articleShare)

> And perhaps a certain idea of college — a certain ideal of college — is dying. I [Frank Bruni] keep coming back to that possibility, which seems more like a probability since President Trump returned to the White House and began his assault on higher education.

> What happened to college as a theater of intellectual betterment, character development, self-discovery? Easy A’s work against that, replacing rigor with ready affirmation. A.I. also works against that: Why spend hour upon hour synthesizing knowledge when a few keystrokes will do the trick? And measuring schools by their financial return on students’ investments ... occludes higher education’s other important functions. Colleges are supposed to nurture nimble thinkers. They’re meant to produce informed and enlightened citizens who are better equipped to leaven passion with reason. There’s a deficit of those now, as ominous as any budgetary shortfall.

> Zimmerman [renowned historian of education at the University of Pennsylvania] said. “We continue to tell a story about the mind-expanding purpose and qualities of a university, and no doubt some people who come here experience that mind expansion. The problem is that all of the other cultural and social signals around them are pointing them in the other direction.”

> The moral of those two stories is that the smartest approach to college may be precisely the one that its trajectory of late has conspired against: range widely across subject offerings and focus not on a skill that could become obsolete but on intellectual dexterity and powers of judgment with better odds of enduring relevance. “A liberal arts degree is a preprofessional degree — you just don’t know what the profession is,” said Zimmerman, who teaches a seminar for first-year students at U. Penn. called “Why College?”

> But higher education as a blessing independent of any instantly redeemable credential bucks the zeitgeist. Under Trump, blunt materialism reigns, and such concepts as human rights, diplomacy and even democracy are suspect, the precious preoccupation of idealistic chumps. Do anthropology, philosophy and history stand a chance?

* White House officials are preparing an executive order targeting tech companies with what they see as “woke” artificial-intelligence models, their latest effort to go after diversity, equity and inclusion initiatives


[https://www.wsj.com/tech/ai/white-house-prepares-executive-order-targeting-woke-ai-e68e8e24?st=eqQBGd&reflink=article_gmail_share](https://www.wsj.com/tech/ai/white-house-prepares-executive-order-targeting-woke-ai-e68e8e24?st=eqQBGd&reflink=article_gmail_share)


(As Krugman noted in a recent news letter: "So in modern Republican rhetoric, anything to the left of MAGA ideology is communist extremism. And here’s the thing: The answers you get from AI generally don’t adhere to the right-wing party line. ... it all goes back to Stephen Colbert’s dictum, almost 20 years ago, that “reality has a well-known liberal bias.”
)

> The order would dictate that AI companies getting federal contracts be politically neutral and unbiased in their AI models, an effort to combat what administration officials see as liberal bias in some models, the people said.


----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
