# Jul 4

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

Happy 4th a reminder we have a nation worth caring about despite a leadership seeking radical reversals of progress. The BBB will certainly put gas on this fire.

And for those looking to watch the July 9th congressional hearing, here is a link

[https://edworkforce.house.gov/calendar/eventsingle.aspx?EventID=412535](https://edworkforce.house.gov/calendar/eventsingle.aspx?EventID=412535)

Thanks to VAC, KB, and BE for sending along stories to share.

A new feature: to see a listing by topic in reverse chronological manner try this:

[https://cunytracker.github.io/CUNYTracker/bytopic.html](https://cunytracker.github.io/CUNYTracker/bytopic.html)


## Letters

* Four Brooklyn College adjuncts not reappointed

[https://drive.google.com/file/d/1m66vrS2Hoen6u6cqnjNtwUHZwqnBVAs7/view.](https://drive.google.com/file/d/1m66vrS2Hoen6u6cqnjNtwUHZwqnBVAs7/view.)

A PSC resolution

[https://docs.google.com/forms/d/19MhSXhvLvfJWYCjabU2mb8EBdIW4wpYZf96l-Z-HJKM/viewform?pli=1&pli=1&edit_requested=true](https://docs.google.com/forms/d/19MhSXhvLvfJWYCjabU2mb8EBdIW4wpYZf96l-Z-HJKM/viewform?pli=1&pli=1&edit_requested=true)

A letter to sign

(The XC sent a letter to the college President on Monday the 30th.)

* Letter to the Chancellor on MADCs by several CUNY faculty

[https://docs.google.com/document/d/1jd0KZzC-0Kl7koep3n0nWPyiOSsvQ66mlcpvyX48Bxc/edit?tab=t.0](https://docs.google.com/document/d/1jd0KZzC-0Kl7koep3n0nWPyiOSsvQ66mlcpvyX48Bxc/edit?tab=t.0)

> we urge you to bring the following arguments to the hearing:

> CUNY -- and higher school education more broadly -- is a public good that is well worth the investment of public dollars.

> CUNY is an engine of social mobility.

> Equally vital to this mission is the work of CUNY faculty, whose research spans disciplines and directly addresses pressing social, economic, scientific, and cultural challenges.

> we hope you will challenge the weaponization of antisemitism allegations as another tactic in an ongoing right-wing strategy to delegitimize and undermine the democratic mission of higher education

## Alliances

## Statements

## Protests

## Op eds

## How best to describe the times we are in

## Academic freedom

* A different take on academic freedom.

[https://www.insidehighered.com/opinion/views/2025/07/02/university-autonomy-stems-corporate-rights-opinion](https://www.insidehighered.com/opinion/views/2025/07/02/university-autonomy-stems-corporate-rights-opinion)

(Thanks BE for sharing)

> Rather than an individual right, academic freedom is, properly understood, what Stanley Fish called “a guild concept.” More specifically, it is a concept belonging to the incorporated guild of professors and students (and others). This theory bases academic freedom not on freedom of speech—a troublesome basis for academic freedom—but on the university’s corporate rights. These corporate rights, not infrequently finding expression in constitutions, are also sometimes constitutional rights. By substituting corporate rights for freedom of speech, we turn a foundation of sand into stone.

> It is no exaggeration to say that, in spring 2025, we may have entered the nadir of American academic freedom. Austin Sarat rightfully urged us, even before then, to find new ways to guard academic freedom “against external threats.” Now, in the face of ongoing hostility from both state and federal governments, it is imperative that universities deploy the full range of arguments at their disposal, including those based on their forgotten corporate rights. In other words, it’s time for universities to invoke their corporate rights. Allow me to explain.

> “Incorporation,” David Ciepley has written, “is a powerful tool.” Corporations can sue and be sued in their own names, hold property, enter contracts, use their own seals and legislate. Importantly, the university’s corporateness bears no necessary relationship to its current autocratic constitution, whereby, according to Timothy V. Kaufman-Osborn, universities are “ruled by external lay governing boards vested with the panoply of powers customarily granted to corporations, including the power to adopt, amend, and revoke its basic rules of institutional governance.” Thus, we can use the university’s corporateness to rebuff external attacks, while also working, as Arjun Appadurai wrote recently, “to break the unilateral power of boards of trustees.”



## Freedom of expression

### Anti-woke/anti-DEI is simply racism

* ecretly Recorded by Anti-DEI Group, ‘No Longer Employed’

[https://www.insidehighered.com/news/diversity/2025/06/30/secretly-recorded-anti-dei-group-now-no-longer-employed](https://www.insidehighered.com/news/diversity/2025/06/30/secretly-recorded-anti-dei-group-now-no-longer-employed)

> he YouTube video is titled “CAUGHT ON TAPE: UNC Administrator Admits They Ignore DEI Ban.” Heart-pumping music plays. A hidden camera records a Black woman—labeled in the video as Janique Sanders, a University of North Carolina at Charlotte employee—speaking to people out of frame.

> The woman apparently didn’t know she was speaking to someone doing their own covert work: the conservative group Accuracy in Media, or AIM [which opposes the scientific consensus on climate change], conducting a sting. Now Sanders, who was assistant director of the Office of Leadership and Community Engagement, is no longer employed by UNC Charlotte.

* Where Anti-DEI Legislation Has Been Proposed

[https://www-chronicle-com.csi.ezproxy.cuny.edu/article/here-are-the-states-where-lawmakers-are-seeking-to-ban-colleges-dei-efforts](https://www-chronicle-com.csi.ezproxy.cuny.edu/article/here-are-the-states-where-lawmakers-are-seeking-to-ban-colleges-dei-efforts)

(Thanks VAC)

* NYTimes: Trump Withholds Nearly $7 Billion for Schools, With Little Explanation

[https://www.nytimes.com/2025/07/01/us/trump-education-funds.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/01/us/trump-education-funds.html?smid=nytcore-ios-share&referringSource=articleShare)

(K-12, but still just reneging)

> The Trump administration has declined to release nearly $7 billion in federal funding that helps pay for after-school and summer programs, support for students learning English, teacher training and other services.

> The money was expected to be released by Tuesday. But in an email on Monday, the Education Department notified state education agencies that the money would not be available.

> Many school districts also rely on federal dollars to help non-English-speaking students and families, including training teachers and hiring translators.


* A Decades-Old Government Program That Supports Hispanic Students Is Under Fresh Scrutiny

[https://www-chronicle-com.csi.ezproxy.cuny.edu/article/a-decades-old-government-program-for-supporting-hispanic-students-is-under-fresh-scrutiny](https://www-chronicle-com.csi.ezproxy.cuny.edu/article/a-decades-old-government-program-for-supporting-hispanic-students-is-under-fresh-scrutiny)

> For 30 years, colleges enrolling a certain share of Hispanic students have been able to secure a title that opens up millions in federal funding. Hundreds of them now qualify as Hispanic-serving institutions, or HSIs.

> But those programs are now in the line of fire.

> The U.S. Education Department doled out about $350 million to Hispanic-serving institutions in the 2024 fiscal year across three competitive grant programs; the National Science Foundation awarded another $53.5 million. Colleges can become eligible when at least 25 percent of their undergraduate students identify as Hispanic or Latino/a.


> Students for Fair Admissions, the group responsible for the lawsuit that ended race-conscious admissions policies at selective colleges in 2023, has brought a new complaint in Tennessee arguing that federal funding designated solely for HSIs is discriminatory.




## Visas

* Chinese Students’ Vulnerable Status Has a History — and an Impact on the Future

[https://www.chronicle.com/article/chinese-students-vulnerable-status-has-a-history-and-an-impact-on-the-future](https://www.chronicle.com/article/chinese-students-vulnerable-status-has-a-history-and-an-impact-on-the-future)

> “It does seem that Chinese students are being used as bargaining chips in the trade negotiations with China,” said Jonathan Bean, a research fellow at the Independent Institute and a professor of history at Southern Illinois University at Carbondale.

> “It would be devastating. You really can’t run labs without these graduate students. You really can’t run these large courses,” said Wu. “The entire model of how universities run in the U.S. is at risk if we lose the supply of international students.”




## Loss of expertise

## Funding cuts

* DOGE loses control over government grants website, freeing up billions

[https://www.washingtonpost.com/politics/2025/06/27/doge-loses-control-federal-grants/](https://www.washingtonpost.com/politics/2025/06/27/doge-loses-control-federal-grants/)

> Three months ago, DOGE employees wrested control of a key federal grants website, grants.gov, which serves as a clearinghouse for more than $500 billion in annual awards, The Post reported. For most of the program’s existence, federal agencies including the Defense Department posted their funding opportunities directly to the site, where thousands of outside organizations could see and apply for them — until April, when DOGE staffers changed the website’s permissions to give themselves power to review and approve all grants across the government.

> But on Thursday, federal officials were instructed to stop routing the grant-making process through DOGE, according to emails obtained by The Post and the two people, both of whom spoke on the condition of anonymity to describe a sensitive situation. The decision follows fears that months of DOGE-linked delays would lead to what critics allege would be the illegal impoundment of federal funds.

* PSC, higher-ed unions slam federal research funding cuts

[https://thechiefleader.com/stories/psc-higher-ed-unions-slam-federal-research-funding-cuts,54668](https://thechiefleader.com/stories/psc-higher-ed-unions-slam-federal-research-funding-cuts,54668)

> Researchers at the city and state’s public universities affected by cuts to federal grant funding urged the state’s congressional leaders to oppose further cuts to funding proposed in President Trump’s “big beautiful bill.”

> Members of the Professional Staff Congress, the New York State United Teachers and other higher-education advocates rallied against the existing and proposed funding reductions outside of the Trump Building at 40 Wall St. Monday.

> At the City University of New York, 70 grants worth $17 million in funding have been slashed, which has put 100 jobs at risk, according to the PSC. And at SUNY, there have been $50 million in grant terminations.

> The PSC’s president, James Davis, called the cuts to SUNY and CUNY “an outrage,” adding that cuts to research could delay life-saving medical treatments.

> Kathleen Cumiskey, a psychology professor at the College of Staten Island who has worked at CUNY for 22 years, said that a $700,000 National Science Foundation grant for a three-year STEM education program aimed at improving academic outcomes at Hispanic-serving institutions was terminated on May 2, just 20 months into the program’s lifespan.

> “We believe the decision to terminate our grant was unfair. Unfortunately, under the current administration, it appears that the agency has been redirected in ways that threaten our nation’s scientific discovery and the importance of broad participation in the creation of new knowledge,” Cumiskey said.

> City Comptroller Brad Lander joined the researchers, noting that higher education contributes $35 billion to the city’s economy and employs about 140,000 people.

### NSF

### NIH

* Stalled funding, canceled grants: How the NIH crisis is affecting Duke - The Chronicle


[https://www.dukechronicle.com/article/2025/06/duke-university-national-institutes-of-health-cut-cancel-duke-research-nih-federal-funding-grants-trump-administrations](https://www.dukechronicle.com/article/2025/06/duke-university-national-institutes-of-health-cut-cancel-duke-research-nih-federal-funding-grants-trump-administrations)

>  Duke receives around $1.2 billion in research grants a year, and much of it comes from the NIH. In fiscal year 2024 NIH support totaled $580 million.

> “Most of the time, that's a point of pride, a marker of success, but it's also a point of challenge when that fundamental model is changing. This is what we’re dealing with now,” said Mary Klotman, executive vice president for health affairs and dean of the School of Medicine

> Grant Watch contains a field for “tagged_words” — which matches words from a list that The New York Times reported could trigger an automatic review of grants — to words used in a grant’s title or abstract. Noam Ross, a computational researcher part of Grant Watch, told The Chronicle that Grant Watch doesn’t know exactly how grants are flagged for termination, but “suspect that these words are part of a search process for selecting them based on [The New York Times article] and other reporting.”

> The 15 canceled NIH grants contained flagged words like “expression,” “disability,” “trans” and “systemic.” However, these words were not used in contexts to promote DEI initiatives, although some may have had diversity supplements including the two described below.

> The grant that had the word “disability” in its abstract focused on identifying biomechanical and biological factors that lead to early onset osteoarthritis following a partial meniscectomy — a surgical procedure commonly done to remove damaged meniscal tissue following a tear. The grant had over $750,000 remaining in funding at the time of termination.

> Furthermore, a grant that had both “trans” and “systemic” in its abstract was working toward editing neural circuits by engineering channel proteins to control the point of contact between two neurons. It had around $1.4 million remaining in funding at the time of termination.

> In most other cases where “trans” was flagged, the term generally referred to other words with the trans- prefix, such as disease transmission, transgenic genetic material, translational studies or signal transduction.

> Most notably, the NIH ended Duke’s Center for HIV/AIDS Vaccine Development, which was a $129 million program and a leader in its field. The program was in its sixth year of funding out of seven and was largely expected to be renewed for an additional cycle. Associated funding has not been listed as terminated in federal databases and thus was not included in the Grant Watch data analysis.

* The Scientific Research Lost Amid the Trump Administration’s NIH Cuts — ProPublica


[https://projects.propublica.org/nih-cuts-research-lost-trump/](https://projects.propublica.org/nih-cuts-research-lost-trump/)



### NEH

### NEA


### DOE

### Fulbright

### EPA

* E.P.A. Employees Are Invited to Adopt Soon-to-Be Homeless Lab Rats - The New York Times


[https://www.nytimes.com/2025/07/03/climate/epa-lab-rat-zebra-fish-adoption.html](https://www.nytimes.com/2025/07/03/climate/epa-lab-rat-zebra-fish-adoption.html)

> Employees at the Environmental Protection Agency’s research campus in North Carolina are preparing to take on a new responsibility. Bring home lab rats as pets.

> Or maybe some zebra fish.

> Both animals have long been used at the E.P.A. facility to test the toxicity of chemicals. But as the E.P.A. shuts down its research arm as part of the Trump administration’s deep cuts to government scientific work, the animals need new homes.

## Federal Agencies

### DOE/OCR

## Congressional actions

* What's in the Senate Version of Trump's Big Policy Bill? - The New York Times

[https://www.nytimes.com/interactive/2025/06/30/upshot/senate-republican-megabill.html](https://www.nytimes.com/interactive/2025/06/30/upshot/senate-republican-megabill.html)

(Terrible news on Medicaid, ICE etc, but for higher ed we see:)

> Finance Pell Grant shortfall; Set aside funding to eliminate a shortfall; $11 bil

> Allow Pell Grants for shorter-term training Allow grants for short-term professional training certificates and not just traditional higher education; $0.3bil

> Student loan limits Limit loans for graduate and professional students and parents; and eliminate graduate and professional PLUS loan program; -$44bil

(Ouch, that is money being stripped for grad students)

> Student loan repayment; Limit income-driven repayment options and allow payments made under a new program to count for people who currently use the public service loan forgiveness program; -$271bil

(Double ouch)

> Fee for nonimmigrant visas; New miniumum $250 fee imposed when a nonimmigrant visa, like for students and certain workers, is issued; -$27bil

(I'm guessing this applies to the 7000 students at CUNY on SEVIS visas)

> SNAP eligibility for certain immigrants; Limit benefits to citizens or lawful permanent residents, with some exceptions -$1.9bil

(That is just one cut to SNAP, of which there were **many**)

> Reduce Medicaid emergency payments for immigrants; Lower the share of medical bills paid by the federal government for undocumented immigrants who are treated for emergencies; -$28bil

> Medicaid eligibility rule; Allow states to require more paperwork and more frequent eligibility checks for people in Medicaid. This provision was changed after the Senate parliamentarian advised that it did not comply with the rules. It is unclear how the changes will affect its savings. -$78bill

(This is savings through paperwork. Wish is kinda like a travel reimbursal with CUNY First. Seriously though, there are even bigger cuts here and for sure CUNY's students will be caught up in them.)



* What the Senate’s Sprawling Policy Bill Means for Higher Ed

[https://www.chronicle.com/article/what-the-senates-sprawling-policy-bill-means-for-higher-ed](https://www.chronicle.com/article/what-the-senates-sprawling-policy-bill-means-for-higher-ed)

> Should the bill become law, it would contain some bitter pills for higher ed, too: an increased excise tax on the endowment income of wealthy colleges, penalties for institutions that fail to deliver an earnings bump to their graduates, and the elimination of Grad PLUS loans.

> But while advocates for the sector and its students decry those provisions, they may have dodged more damaging bullets. The Senate legislation underwent significant changes in the week leading up to its passage, several of which softened provisions in the House bill that had raised alarms across the sector. The Senate retained the House’s broad plan to raise the endowment tax, for example, but it limited the extent of the hike and opened up loopholes for small institutions.

> Senators abandoned a House plan to eliminate subsidized federal undergraduate loans. Also out: a House provision that would have required students to take 30 credit hours per academic year to receive the maximum Pell Grant award, and 15 credit hours to be eligible for Pell Grants at all. Community colleges were particularly panicked about the provision.

> The Senate kiboshed a controversial risk-sharing plan introduced in the House bill, which would have forced colleges to kick money into a new pot of federal aid when their students defaulted on federal-loan repayment. Instead, it offered an alternative approach with roots in the gainful-employment rule, a cornerstone of the Obama administration’s accountability efforts.

> The Senate-passed plan would yank federal-loan eligibility from programs that fail to deliver an earnings bump to their graduates. Senators tweaked the details in the days leading up to Tuesday’s vote so colleges would be judged on the earnings of their graduates, not dropouts.




## State actions


## Institutional assaults

* Why UVA President’s Resignation Could Be a ‘Watershed Moment’

[https://www.insidehighered.com/news/governance/executive-leadership/2025/06/30/uva-reels-after-president-resigns-under-pressure](https://www.insidehighered.com/news/governance/executive-leadership/2025/06/30/uva-reels-after-president-resigns-under-pressure)

> “I think this is a watershed moment,” said Jon Holbein, an associate professor of public policy, politics and education at UVA. “If a moderate president at a conservative–for–higher education institution who has followed the law when it comes to diversity [can be pushed out], no president is immune from the Trump administration’s ire.”

> UVA faculty, some board members, students and community say Ryan’s departure is a blow to the institution. “His loss makes us worse,” said Michael Kennedy, a UVA professor and faculty representative on the Board of Visitors, describing Ryan as a “shattering success.”

> The Jefferson Council, a conservative alumni group that publicly called for Ryan’s resignation, called the DEI efforts exclusive, discriminatory and “the new McCarthyism.”

(I think that used to be called doublespeak; ths organization seems to have been founded by someone who in March had this news: Youngkin fires Bert Ellis from University of Virginia Board of Visitors))

* The U. of Virginia’s President Was Targeted Over DEI. Now He’s Resigning.

[https://www.chronicle.com/article/university-of-virginia-president-reportedly-resigns-under-pressure-from-trump-administration](https://www.chronicle.com/article/university-of-virginia-president-reportedly-resigns-under-pressure-from-trump-administration)

> Peter McDonough, vice president and general counsel at the American Council on Education, called the government’s handling of the matter “a potentially ominous effort to control a learning environment it finds objectionable.”

> “This is unprecedented,” McDonough said in an interview. “Maybe we should have seen it coming.”

> Dhillon said that the department had told UVa representatives that the government “lacked confidence” in Ryan, given his “participation in groups” that had publicly opposed the Trump administration’s policies. (Ryan, along with hundreds of other college presidents, signed a letter condemning “unprecedented government overreach” in higher education.)

* NYTimes: What the University of Virginia Should Have Done

[https://www.nytimes.com/2025/06/30/opinion/university-of-virginia-doj-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/30/opinion/university-of-virginia-doj-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> Under investigation by the Justice Department, the university had a strong defense, if only it had the courage to assert it. Instead of fighting back against what I believe to be false accusations that the university was violating federal law, and the even more outrageous demand that Mr. Ryan resign as a remedy for those alleged violations, the university’s Board of Visitors pushed out a popular president. Instead of presenting facts and law, the board waved the white flag of surrender. Mr. Ryan’s resignation is a victory for intimidation and fear over the rule of law.

> I served as university counsel at the University of Virginia from 2018 through 2022. During that time, it was my job to defend the university from unfounded allegations and investigations. The Justice Department has alleged that the university’s actions violated Title VI of the Civil Rights Act of 1964, which states, “No person in the United States shall, on the ground of race, color, or national origin, be excluded from participation in, be denied the benefits of, or be subjected to discrimination under any program or activity receiving federal financial assistance.” Had I been university counsel last week, I would have advised my client to challenge what I believe to be a false allegation that the university’s policies are unlawful.

> Title VI prohibits racial classifications, quotas or programs that are exclusive to any one race, gender or protected class. It does not prevent federal contractors, such as universities, from pursuing the goal of creating a diverse community, one that ensures all individuals can participate in the learning environment regardless of race, ethnicity, gender, sexual orientation, national origin or political ideology. Eligibility for programs and opportunities based on those and other immutable characteristics is illegal. Programs that create a pipeline of diverse applicants are not.

> While the university’s compliance with Title VI is clear to me, it was challenged by the Justice Department. Informed by the advocacy of the America First Legal Foundation, an organization founded by the current White House deputy chief of staff, Stephen Miller, the department alleged that the university’s compliance efforts were insufficient, a mere relabeling of D.E.I. programs that broke the law. The department’s proposed remedy was the resignation of the university’s leader — a shocking move that reveals the personal animus behind the investigation. The administration would rather oust a leader than force compliance with a particular policy.

> Why? By law, the university and all state agencies are represented by the attorney general of Virginia. The current attorney general has been an outspoken opponent of D.E.I. programs. He joined Virginia’s governor, Glenn Youngkin, in applauding the university’s dismantling of D.E.I. programs in March 2025. This means rather than having an advocate loyal to the university and its interests, Mr. Ryan and the university were saddled with counsel aligned with the other side.


> The university’s governing board took a similar position. The majority of the current board was appointed by Mr. Youngkin, who has said, “D.E.I. is done at the University of Virginia.” In failing to assert these valid legal defenses, the board abdicated its responsibility to protect the university and defend it against unfounded allegations.

> Mr. Ryan was known to urge the university to be both “great and good” in all its endeavors. His departure will result in a less inclusive university community, which will harm all students who choose the University of Virginia. It is a sad day for the university, which will suffer the consequences of this bad decision.

* New York City Tech/CUNY one of the highlighted BA degree granting institutions whose faculty are increasingly integrated—race/ethnicity non-white.

[https://www.chronicle.com/article/what-is-the-share-of-minority-instructors-at-colleges-with-the-most-full-time-faculty-members](https://www.chronicle.com/article/what-is-the-share-of-minority-instructors-at-colleges-with-the-most-full-time-faculty-members)

(VAC says: This interesting graph explains too the attacks from this fed administration on higher ed)



### Harvard

* What a Harvard Deal Would Mean for Higher Ed

[https://www-chronicle-com.csi.ezproxy.cuny.edu/article/what-a-harvard-deal-would-mean-for-higher-ed](https://www-chronicle-com.csi.ezproxy.cuny.edu/article/what-a-harvard-deal-would-mean-for-higher-ed)

> In the absence of more information, some faculty members within Harvard are fearful that the government isn’t negotiating in good faith, and that any agreement would only open the door to an unlawful power grab — although not everyone is so pessimistic. Outside of Harvard, expert observers of higher education also range between faith in what Harvard could accomplish in a settlement, and worry that any such deal may set a dangerous precedent for the rest of the sector.

> Ryan D. Enos, a professor of government, can’t envision any positive outcomes from settling with the Trump administration. “It’s shortsighted to think that anything good can come from trying to negotiate your way out of extortion with an authoritarian regime,” he says.

* NYTimes: Trump Administration "Finds" Harvard Violated Civil Rights Law

[https://www.nytimes.com/2025/06/30/us/politics/trump-harvard-civil-rights-law.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/30/us/politics/trump-harvard-civil-rights-law.html?smid=nytcore-ios-share&referringSource=articleShare)

(Okay, quotes in the headline were added as this was never established beyond the walls of the white house)

> In a letter to Harvard’s president, Alan M. Garber, on Monday, officials from four federal agencies said that the university was “in violent violation of Title VI,” a portion of federal civil rights law that bars discrimination on the basis of race, color or national origin. In recent years, government officials have interpreted the provision to include “shared ancestry and ethnic characteristics” as within the law’s protections.

> In their letter, the Trump administration officials said that Harvard’s “commitment to racial hierarchies” had “enabled antisemitism to fester” at the nation’s oldest and wealthiest university. They warned that not making “adequate changes immediately will result in the loss of all federal financial resources and continue to affect Harvard’s relationship with the federal government.”

> Harvard sharply disputed the government’s account, saying in a statement on Monday that antisemitism was “a serious problem” that the school had taken significant steps to address. The university added that it was “far from indifferent on this issue” and that it “strongly disagrees with the government’s findings.”

> But Paula M. Stannard, the director of the Office for Civil Rights at the Department of Health and Human Services, said in a separate letter on Monday that Harvard’s varied steps to combat antisemitism, such as the development of a faculty panel to investigate and discipline people in connection with certain accusations of misconduct, were “too little, too late.”

> According to Ms. Stannard, “Jewish and Israeli students at Harvard University were subject to severe, pervasive and objectively offensive harassment from Oct. 7, 2023, through the present.”

(Add Paula M Stannard to your bingo card)

* The Trump administration found Harvard violated the civil rights of Jewish and Israeli students, putting the university’s federal funding further at risk

[https://www.wsj.com/us-news/education/harvard-violated-students-civil-rights-trump-administration-finds-4a0ed7aa?st=UNno8L&reflink=article_gmail_share](https://www.wsj.com/us-news/education/harvard-violated-students-civil-rights-trump-administration-finds-4a0ed7aa?st=UNno8L&reflink=article_gmail_share)

> A formal “notice of violation” of civil-rights law generally is a step that can come before either a lawsuit from the Justice Department or a voluntary resolution with the school. Under past presidential administrations, civil-rights investigations at universities usually ended with voluntary resolution agreements.



* What a Harvard Deal Would Mean for Higher Ed

[https://www.chronicle.com/article/what-a-harvard-deal-would-mean-for-higher-ed](https://www.chronicle.com/article/what-a-harvard-deal-would-mean-for-higher-ed)

(Thanks VAC for sending along; this )

> If Harvard reverses course, it would compromise that sense of common cause. “There will be a certain feeling of betrayal if they make a deal,” according to Levitsky [professor of Latin American studies].

> Ryan D. Enos, a professor of government, can’t envision any positive outcomes from settling with the Trump administration. “It’s shortsighted to think that anything good can come from trying to negotiate your way out of extortion with an authoritarian regime,” he says.

* Harvard is the wealthiest U.S. university. Can it survive a Trump standoff?

[https://www.washingtonpost.com/education/2025/07/01/harvard-trump-federal-funding/](https://www.washingtonpost.com/education/2025/07/01/harvard-trump-federal-funding/)

> “With its resources and an AAA bond rating, Harvard has financial freedom and flexibility. Still, these headwinds, and there are a lot of them, are piling up all at once,” said Howard Bunsis, an accounting professor at Eastern Michigan University.

> Since the federal government began demanding the university change how it operates in April, Harvard has lost more than $2 billion in federal funding.

> But the university has limited access to its endowment and already depends on it for a significant portion of its operating budget. And about 80 percent of Harvard’s endowment, a collection of 14,000 funds, is restricted to uses that donors stipulate, and the university cannot change the terms of those gifts — some dating back to the founding of the school — on its own.

> Harvard has about $8.2 billion in unfunded private equity commitments coming due in the near term, said Michael Markov, co-founder and chairman of the research firm Markov Processes International. Finding the money to cover those kinds of commitments could put tremendous pressure on universities with large private equity stakes, he said.

> “It’s just this perfect storm of academic freedom in the crosshairs at the same time that the universities are vulnerable because of the financial uncertainties associated with their endowments and their private equity investments,” he [Philip Casey, founder and chief executive of Institutional LPs]  said.

* Harvard would face a budget shortfall of about a billion dollars a year if President Trump follows through on all of his plans and threats spanning research funding, tax policy and student enrollment


[https://www.wsj.com/us-news/education/harvard-trump-funding-budget-cuts-1dc5bf2f?st=H5Jdr2&reflink=article_gmail_share](https://www.wsj.com/us-news/education/harvard-trump-funding-budget-cuts-1dc5bf2f?st=H5Jdr2&reflink=article_gmail_share)

(Has an excellent graphic "Harvard’s 2024 revenue and worst-case scenario losses" showing losses: -240M for endowment (of 2.4B), -700M federally funded research (max amount), -110M grad school (of 800M) )

> Harvard University would face a budget shortfall of about a billion dollars a year if President Trump follows through on all of his plans and threats spanning research funding, tax policy and student enrollment, according to an analysis by The Wall Street Journal.

> That grim math helps explain why Harvard has taken steps toward negotiating with the administration after months of defiance. The Journal’s estimate, based on publicly available data, is for a worst-case scenario in which Harvard loses all federal research funding, federal student aid and its ability to enroll international students, and Congress hikes its annual endowment tax to 8%.




### Columbia

* Middle States Gives Columbia a Warning

[https://www.insidehighered.com/news/quick-takes/2025/07/02/columbia-u-gets-warning-accreditor](https://www.insidehighered.com/news/quick-takes/2025/07/02/columbia-u-gets-warning-accreditor)

> The Middle States Commission on Higher Education warned Columbia University that its accreditation could be in jeopardy.

> The warning, sent June 26, comes after the Education Department pressured the accreditor in early June to take action against Columbia. The Trump administration has said that Columbia violated federal civil rights laws and is thus out of compliance with the accreditor’s standards. But only accreditors can say whether a college is in compliance. Middle States had already opened a review of Columbia before the department’s notice, conducting an on-site evaluation in April.

> Middle States said in the warning that it doesn’t have sufficient evidence showing Columbia is complying with its standard on ethics and integrity. The criteria for that standard includes “a climate that fosters respect among students, faculty, staff, and administration from a range of diverse backgrounds, ideas, and perspectives” and “compliance with all applicable government laws and regulations.” The accreditor requested a monitoring report, due by Nov. 3, that demonstrates the university’s compliance with the standard, and will consider Columbia’s accreditation status at a March 2026 meeting. Columbia remains accredited in the meantime.

* NYTimes: Columbia Cyberattack Appears Politically Motivated, University Says

[https://www.nytimes.com/2025/07/01/nyregion/columbia-university-hacker.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/01/nyregion/columbia-university-hacker.html?smid=nytcore-ios-share&referringSource=articleShare)

(trigger alert; graphic image accompanies article)

> The cyberattack that caused a widespread shutdown of Columbia University’s computer systems last week appears to be the work of a “hacktivist” — a hacker who also stole student data with the apparent goal of furthering a political agenda, a Columbia official said on Tuesday.

> A cyber-forensics firm hired by the university reported that the hack appeared to be highly sophisticated and targeted in its theft of documents, the official said. The official added that Columbia had not yet determined the scope of the data theft and that it could take weeks to months to do so. Columbia’s websites and internal systems, however, which went down during the attack, were up and running again within a week.


> The person who communicated with Bloomberg News provided it with 1.6 gigabytes of data representing 2.5 million student applications to Columbia dating back decades. The data included students’ and applicants’ university-issued identification numbers, their citizenship status, the decisions made on their applications and the academic programs to which they applied, among other information.

> Bloomberg reported that it was able to confirm the accuracy of the data for eight Columbia students and alumni who applied to the university between 2019 and 2024.

> Columbia was attacked about a week after its chief information officer, Gaspare LoDuca, announced that he was leaving the university and joining M.I.T. as its vice president for information systems and technology. Over his 10-year tenure at Columbia, Mr. LoDuca oversaw all information technology systems, including cybersecurity, The Columbia Spectator reported.

* Columbia University plans to steal a page from the conservative playbook


[https://www.washingtonpost.com/climate-environment/2025/07/02/states-climate-law-model-legislation/](https://www.washingtonpost.com/climate-environment/2025/07/02/states-climate-law-model-legislation/)

> “States are the front line for climate action in this moment of the second Trump administration. And one of the key needs that state legislators have is legal support for writing better laws,” said Vanessa Fajans-Turner, executive director of Environmental Advocates New York, which is also funding the initiative. “We see climate legislation ending up very consistently in the courts, being challenged. And if that is going to be the case, we need to start writing legislation with the strongest possible legal basis.”

* The acting president of Columbia University apologized Wednesday for messages in which she appeared to diminish concerns about antisemitism on campus and criticize a Jewish member of the school’s board of trustees

[https://www.wsj.com/us-news/education/columbia-president-claire-shipman-apology-3cd70dc5?st=W8PktJ&reflink=article_gmail_share](https://www.wsj.com/us-news/education/columbia-president-claire-shipman-apology-3cd70dc5?st=W8PktJ&reflink=article_gmail_share)

> Stefanik tweeted out a one-word message above a picture of Claire Shipman, the school’s acting president: “Resign.”

> In one string of messages Shipman criticized Shoshana Shendelman, an outspoken Jewish trustee, and said she should not be on the board. In a 2023 exchange, the vice chair of the board asked Shipman: “Do you believe that [Shendelman] is a mole?” Shipman said she believed she was and added that she was “so, so tired” of her.



### Indiana

Indiana Public Universities to ‘Voluntarily’ End 19% of Degrees

[https://www.insidehighered.com/news/faculty-issues/curriculum/2025/07/02/ind-public-universities-voluntarily-ending-19-degrees](https://www.insidehighered.com/news/faculty-issues/curriculum/2025/07/02/ind-public-universities-voluntarily-ending-19-degrees)

(Their quotes, not mine. Thanks VAC for sharing.)

> Indiana’s public higher education institutions plan to eliminate or consolidate over 400 programs, equaling roughly one-fifth of their degree offerings statewide, the Indiana Commission for Higher Education said Monday. The announcement came just before a new state law took effect Tuesday setting minimum requirements for how many graduates individual programs must produce at the universities and Ivy Tech Community College, or face termination.

> Republican state legislators passed the law—a state budget bill with major higher education provisions tacked on—less than two days after revealing it in April. It says institutions can ask the commission for approval to keep offering degrees that don’t meet the threshold of average annual graduates. But the universities “voluntarily submitted” the first wave of hundreds of programs to be ended or consolidated, the commission said, meaning they didn’t ask for exemptions.

> According to a list posted by the commission, among the 400 degrees to be nixed or combined into others are many foreign language and teacher-education programs. The list also includes undergraduate and graduate degrees in fine arts, English, business, economics, philosophy, history, anthropology, sociology, journalism, public administration, social work, labor studies, political science, American studies, Africana studies, women’s and gender studies, religious studies, and classical studies.

> STEM and medical disciplines aren’t being spared, either; the eliminated or consolidated degrees include some in health, biology, chemistry, math, computer science, computer engineering, electrical engineering and mechanical engineering. Indiana University at Bloomington, for instance, is ending its Ph.D. in astrophysics. More than half the programs to be eliminated or merged are in the IU system. Vincennes University is the only public institution in the state that didn’t “voluntarily” submit programs to be cut or combined.

> Indiana’s program slashing can be seen as another consequence of the broader push by red states’ legislatures to intervene in higher education by restricting teaching, attacking tenure and, now, dictating curricula.

> Heather Akou, the president-elect of the IU Bloomington Faculty Council, said the council didn’t get to vote on these “draconian” cuts and mergers at the flagship campus. “Not only did we not vote, we were not even consulted with,” Akou said.

> Balthaser, the IU South Bend AAUP member, said, “This was done very intentionally to essentially change the mission of the university—to shrink it, to essentially destroy what we understand as the public [land-grant] university.”

### UPenn

* UPenn Agrees to Ban Transgender Athletes in Women's Sports, Correct Records | National Review


[https://www.nationalreview.com/news/upenn-agrees-to-ban-transgender-athletes-in-womens-sports-correct-records/](https://www.nationalreview.com/news/upenn-agrees-to-ban-transgender-athletes-in-womens-sports-correct-records/)


[https://www.insidehighered.com/news/government/politics-elections/2025/07/01/penn-agrees-trumps-demands-will-strip-trans-athletes?utm_source=Inside+Higher+Ed&utm_campaign=e64fe0d91e-DNU_2021_COPY_02&utm_medium=email&utm_term=0_1fcbc04421-e64fe0d91e-236791398&mc_cid=e64fe0d91e&mc_eid=7f06c26dc8#](https://www.insidehighered.com/news/government/politics-elections/2025/07/01/penn-agrees-trumps-demands-will-strip-trans-athletes?utm_source=Inside+Higher+Ed&utm_campaign=e64fe0d91e-DNU_2021_COPY_02&utm_medium=email&utm_term=0_1fcbc04421-e64fe0d91e-236791398&mc_cid=e64fe0d91e&mc_eid=7f06c26dc8#)

(From VAC)


[https://www.nytimes.com/2025/07/01/us/penn-title-ix-transgender-swimmer-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/07/01/us/penn-title-ix-transgender-swimmer-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> The University of Pennsylvania said on Tuesday that it had struck a deal with the federal government that will limit how transgender people may participate in its athletic programs, bowing to the Trump administration’s new interpretation of the law that bans sex discrimination in education.

> The agreement was tied to a civil rights investigation, conducted by the Department of Education, of a transgender woman’s participation on Penn’s women’s swim team three years ago. In April, the Education Department said that Penn’s support for the swimmer, Lia Thomas, had violated the law governing sex discrimination in most educational settings.

> Penn’s president, J. Larry Jameson, noted in a statement on Tuesday that the university had been in compliance with the interpretation of federal law that was in effect when Ms. Thomas swam there. But he said that the Trump administration’s inquiry had left Penn vulnerable to “significant and lasting implications,” a reference to the possibility of a loss of federal funding.

### UVA

* UVirginia President resigns under pressure from Trump DOJ

[https://www.nytimes.com/2025/06/27/us/politics/university-of-virginia-president-resigns-trump-justice-department.html](https://www.nytimes.com/2025/06/27/us/politics/university-of-virginia-president-resigns-trump-justice-department.html)

(Thanks VAC, who is counting scalps)

> The University of Virginia’s president, James E. Ryan, has told the board overseeing the school that he will resign in the face of demands by the Trump administration that he step aside to help resolve a Justice Department inquiry into the school’s diversity, equity and inclusion efforts, according to three people briefed on the matter.

> For the leader of one of the nation’s most prominent public universities to take such an extraordinary step demonstrates President Trump’s success in harnessing the investigative powers of the federal government to accomplish his administration’s policy goals.

(Harnessing = weaponizing by another name to this group: Gregory Brown, Harmeet Dhillon, Stephen Miller)

> The University of Virginia has been considered among the top five public universities for more than two decades, according to U.S. News & World Report rankings, and has maintained that position during Mr. Ryan’s tenure. This year, the Princeton Review ranked the university as the second-best value among all public colleges. Last year, Time magazine ranked the college as the fourth-best public school at producing future leaders.

(WSJ reporting)


[https://www.wsj.com/us-news/education/uva-president-resigns-james-ryan-dei-trump-d02a60fe?st=Ce97ks&reflink=article_gmail_share](https://www.wsj.com/us-news/education/uva-president-resigns-james-ryan-dei-trump-d02a60fe?st=Ce97ks&reflink=article_gmail_share)

(The letter Ryan sent to the University)

> To the University community:

> I am writing, with a very heavy heart, to let you know that I have submitted my resignation as President of the University of Virginia. To make a long story short, I am inclined to fight for what I believe in, and I believe deeply in this University. But I cannot make a unilateral decision to fight the federal government in order to save my own job.

> To do so would not only be quixotic but appear selfish and self-centered to the hundreds of employees who would lose their jobs, the researchers who would lose their funding, and the hundreds of students who could lose financial aid or have their visas withheld.

> This is especially true because I had decided that next year would be my last, for reasons entirely separate from this episode-including the fact that we concluded our capital campaign and have implemented nearly all of the major initiatives in our strategic plan.

> While there are very important principles at play here, I would at a very practical level be fighting to keep my job for one more year while knowingly and willingly sacrificing others in this community. If this were not so distinctly tied to me personally, I may have pursued a different path. But I could not in good conscience cause real and direct harm to my colleagues and our students in order to preserve my own position.

> It has been an honor to be your President. Thanks for the outpouring of support over the last few days and weeks.

> My deepest gratitude to all of the faculty, staff, students, and alumni, who make this University and this community both great and good. This was an excruciatingly difficult decision, and I am heartbroken to be leaving this way.

> Best,

> Jim Ryan, President

(The pressure was on in at least three areas: research funding, student financial aid, or student visas).

* The Unexpected Trump Target

[https://www-chronicle-com.csi.ezproxy.cuny.edu/article/the-unexpected-trump-target](https://www-chronicle-com.csi.ezproxy.cuny.edu/article/the-unexpected-trump-target)

> Ryan’s ouster has turned UVa into an unexpected battlefield in the Trump administration’s political assault on colleges. For months, officials have wielded federal power to rebalance what they see as higher ed’s extreme leftward tilt and stamp out diversity, equity, and inclusion programs.

> Harmeet K. Dhillon, the Justice Department’s assistant attorney general for civil rights, sees things differently. Ryan “has built his entire career on what was the academic vogue, which is DEI. Now, it isn’t,” she told CNN’s Jake Tapper. “And so I think it is time for new leadership that’s willing to comply with federal law.”

> Other faculty members see Ryan’s decision as a submission to political actors who have no inclination or tendency to compromise. The professors wish that Ryan, or the university, had fought back. Deborah McDowell, a professor of English, thinks Ryan should have forced the board to fire him.

> “Capitulation is sometimes in order,” she said. “For this, I don’t think it was. This is spoken as someone who does not agree and would not represent myself as one in full agreement with the decisions Ryan has made throughout his presidency. I am not. But bullies cannot be placated. They are greedy.”

> The targeting of UVa may seem somewhat arbitrary, the result of a random commonality in the curricula vitae of two of the nation’s top civil-rights officials. In May, The Chronicle reported a story teasing out the connections between Dhillon; her deputy, Gregory Brown, who attended UVa as an undergraduate and has sued the institution in the past over a civil-rights issue; the Jefferson Council, the conservative alumni group that has been calling on Ryan to resign for months; and the Board of Visitors.

* Letters from DOJ reveal threats to U.Va. over admissions policies, Ryan’s leadership - The Cavalier Daily - University of Virginia's Student Newspaper


[https://www.cavalierdaily.com/article/2025/07/letters-from-doj-reveal-threats-to-uva-over-admissions-policies-ryans-leadership](https://www.cavalierdaily.com/article/2025/07/letters-from-doj-reveal-threats-to-uva-over-admissions-policies-ryans-leadership)

> Between April 11 and June 17, the Department of Justice’s Civil Rights Division sent seven letters to University officials, according to documents obtained by The Cavalier Daily through a Freedom of information Act request.

> In these letters, the Justice Department sought confirmation that the University had removed affirmative action from its admissions policies and had ended Diversity, Equity and Inclusion initiatives. Some letters also alleged that the University had failed to protect students against antisemitism. The letters did not confirm whether or not the Justice Department’s demands had been met.

> April 11: The first letter was sent by the Justice Department to the University April 11 and requested information regarding the University’s admissions policies. The Justice Department said it aimed to ensure the University was no longer using affirmative action, in accordance with the Supreme Court’s decision in Students for Fair Admissions vs. Harvard in 2023.

> The letter requested, among other documents, all admissions data broken down by race and ethnicity for the past five academic years, including applicant test scores, GPA, extracurricular activities, essays and admissions outcomes. It also requested that the University verify that race was not used as a factor in determining any scholarship or financial aid awards to students.

> June 17: The final letter turned up in the FOIA request was from June 17. “Time is running short, and the Department’s patience is wearing thin,” the letter read.

### Others


## The long game


## Blowback

* Europe is wooing American researchers with funding as the Trump administration cancels grants

[https://www.wsj.com/world/europe/europe-is-recruiting-academics-disenchanted-with-america-c4bae422?st=XUZ7ic&reflink=article_gmail_share](https://www.wsj.com/world/europe/europe-is-recruiting-academics-disenchanted-with-america-c4bae422?st=XUZ7ic&reflink=article_gmail_share)

(Now an evergreen story...)

* Moody’s Warns of Credit Risk for Colleges Reliant on International Enrollment

[https://www.insidehighered.com/news/global/international-students-us/2025/07/03/drops-international-student-tuition-could-pose](https://www.insidehighered.com/news/global/international-students-us/2025/07/03/drops-international-student-tuition-could-pose)

(CUNY Enrollment doesn't seem to be impacted as of now; Baruch, City, and GC are trending a bit above last year at the moment.)

> Those most at risk include the 11 percent of American institutions where international students make up more than 20 percent of the student body, the ratings agency said, as well as institutions that are already struggling financially. (In total, 6 percent of students at U.S. institutions come from other countries.)

> “The reduction in international students presents a credit risk for universities heavily reliant on this demographic because of potential declines in tuition income, as international students typically pay full tuition fees,” the report states. “Additionally, with declining numbers of high school students over the next several years in the U.S. leading to fewer domestic students, universities intending to fill the gap with more international students may fall short.”

*  Nobelist: U.S. Scientists Took Support ‘For Granted’ Before Trump Cuts

[https://www.insidehighered.com/news/faculty-issues/research/2025/07/03/nobelist-scientists-took-support-granted-trump](https://www.insidehighered.com/news/faculty-issues/research/2025/07/03/nobelist-scientists-took-support-granted-trump)

> Frances Arnold, who won the Nobel Prize in Chemistry in 2018 for her work on engineering enzymes, told an audience of young scientists in Germany that the “utter chaos” in U.S. politics of recent months, which has seen billions of dollars removed from scientific research, might be viewed in terms of a wider failure to communicate the value of scientific discovery.

> “Never take for granted that scientific achievement is celebrated—we took it for granted, and for far too long, and we are paying the price,” Arnold told the June 29 opening ceremony of the Lindau Nobel Laureate Meeting, an annual conference that brings together Nobel laureates and early-career researchers.

* Scientists warn US will lose a generation of talent because of Trump cuts

[https://www.theguardian.com/us-news/2025/jul/03/national-science-foundation-trump-cuts](https://www.theguardian.com/us-news/2025/jul/03/national-science-foundation-trump-cuts)

> The scientists warn that Trump’s assault on diversity in science is already eroding the quality of fundamental research funded at the NSF, the premier federal investor in basic science and engineering, which threatens to derail advances in tackling existential threats to food, water and biodiversity in the US.

> “Before Trump, the review process was based on merit and impact. Now, it’s like rolling the dice because a Doge person has the final say,” said one current program officer. “There has never in the history of NSF been anything like this. It’s disgusting what we’re being instructed to do.”

> Trump’s big, beautiful bill calls for a 56% cut to the current $9bn NSF budget, as well as a 73% reduction in staff and fellowships – with graduate students among the hardest hit.

> The Federal Reserve estimates that government-supported research from the NSF and other agencies has had a return on investment of 150% to 300% over the past 75 years, meaning US taxpayers have gotten back between $1.50 and $3 for every dollar invested.

(There is a great graphic titled "Democratic states have had more NSF grants cancelled" and the numbers are 917M in blue states; 583 in red -- which is a bit misleading, because TX is the 3rd hardest hit; GA in top part)


(There is another great graphic on cuts by insitution titled "Harvard NSF grants account for 10% of all cancellations, by budget")

> The sweeping cuts to the NSF come on top of Trump’s dismantling of other key scientific research departments within the National Oceanic and Atmospheric Administration (Noaa), Environmental Protection Agency (EPA), Department of Agriculture (USDA) and US Geological Service (USGS).

> Trump’s big, beautiful bill cuts the USGS budget by 39%. This includes slashing the entire budget for the agency’s ecosystems mission area (EMA), which leads federal research on species & ecosystems and houses the climate adaptation science centers.

* NIH cuts: Red states losing out as canceled grants are reinstated:

[https://www.statnews.com/2025/07/03/nih-cuts-grant-restoration-complicated-by-limits-to-court-order-trump-dei-restrictions/](https://www.statnews.com/2025/07/03/nih-cuts-grant-restoration-complicated-by-limits-to-court-order-trump-dei-restrictions/)

> After the first grant termination rolled into Professor Cheri Levinson’s inbox, her university told her it wasn’t worth taking the time to appeal the decision; the odds of success were too low. Ultimately, she had three National Institutes of Health grants terminated that were meant to support trainees from diverse backgrounds in her lab studying eating disorders at the University of Louisville.

> But her state’s Republican attorney general didn’t join AGs from other states, most of them blue states, who sued the Trump administration to block the grant cancellations. So two weeks ago, when many researchers exhaled in relief as a federal judge ruled that a wide swath of the terminations were illegal, and ordered them reinstated, Levinson wasn’t one of them.

(In blue states 2.1B reinstated; in red states 62M)


## Coming attractions?

“Disaster Looms”: Justice Jackson’s Warning for the Country – Mother Jones

[https://www.motherjones.com/politics/2025/06/injunctions-supreme-court-ketanji-brown-jackson/](https://www.motherjones.com/politics/2025/06/injunctions-supreme-court-ketanji-brown-jackson/)

> Once upon a time, there was a president who wanted to be king. His Congress was acquiescent. The high court approved. But lower federal courts held firm to the rule of law. Time and again, they blocked the president from seizing power and violating the nation’s laws. So the president turned to the justices on the Supreme Court for a favor: please stop these meddlesome little courts from getting in my way. And then one day in June, the Supreme Court granted his wish.

> This is what happened on Friday in a case about birthright citizenship before the United States Supreme Court. The Trump administration’s blatantly unconstitutional executive order from January denying birthright citizenship to the children of certain classes of immigrants quickly ran up against lower court judges, who prohibited the Trump administration from violating one of the country’s most sacred Constitutional rights.

> “The Court’s decision is nothing less than an open invitation for the Government to bypass the Constitution,” Sotomayor warned. “The Executive Branch can now enforce policies that flout settled law and violate countless individuals’ constitutional rights, and the federal courts will be hamstrung to stop its actions fully.”

> Jackson warns, this decision has altered our system of government and, sooner or later, may destroy it. “Disaster looms,” she warns. If a court cannot command the executive to follow the law, then there exists “a zone of lawlessness within which the Executive has the prerogative to take or leave the law as it wishes, and where individuals who would otherwise be entitled to the law’s protection become subject to the Executive’s whims instead.”

> “In this country, the Executive does not stand above or outside of the law,” Jackson writes. But her dissent is also a warning that this is becoming less true. A year ago, the Republican appointees exempted the president from the dictates of criminal law. Now, it suggests that even if a court finds the administration’s actions illegal or unconstitutional, it can continue to enforce them against those who haven’t challenged the action in court, either individually or as part of a class action. As a result, the president rises beyond the bounds of the law, and individuals slip from the embrace of its protection.

> “I have no doubt that, if judges must allow the Executive to act unlawfully in some circumstances, as the Court concludes today, executive lawlessness will flourish, and from there, it is not difficult to predict how this all ends,” Jackson wrote. “Eventually, executive power will become completely uncontainable, and our beloved constitutional Republic will be no more.”




## Tracking projects

## AI misdeeds

* NYTimes: A.I. Is Starting to Wear Down Democracy

[https://www.nytimes.com/2025/06/26/technology/ai-elections-democracy.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/26/technology/ai-elections-democracy.html?smid=nytcore-ios-share&referringSource=articleShare)

> Free and easy to use, A.I. tools have generated a flood of fake photos and videos of candidates or supporters saying things they did not or appearing in places they were not — all spread with the relative impunity of anonymity online.

> The technology has amplified social and partisan divisions and bolstered antigovernment sentiment, especially on the far right, which has surged in recent elections in Germany, Poland and Portugal.

> Madalina Botan, a professor at the National University of Political Studies and Public Administration in Romania’s capital, Bucharest, said there was no question that the technology was already “being used for obviously malevolent purposes” to manipulate voters.

> “These mechanics are so sophisticated that they truly managed to get a piece of content to go very viral in a very limited amount of time,” she said. “What can compete with this?”

* NYTimes: How Do You Teach Computer Science in the A.I. Era?

[https://www.nytimes.com/2025/06/30/business/computer-science-education-ai.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/30/business/computer-science-education-ai.html?smid=nytcore-ios-share&referringSource=articleShare)

> The technology has “really shaken computer science education,” said Thomas Cortina, a professor and an associate dean for the university’s [CMU] undergraduate programs.

> Still, for all its past success, the department’s faculty [CMU CS] is planning a retreat this summer to rethink what the school should be teaching to adapt to the rapid advancement of generative artificial intelligence.



## And just because it is fun

* Report Highlights Generational Benefits for CUNY Program

[https://www.insidehighered.com/news/quick-takes/2025/07/01/report-highlights-generational-benefits-cuny-program](https://www.insidehighered.com/news/quick-takes/2025/07/01/report-highlights-generational-benefits-cuny-program)

> The study, conducted by researchers at Columbia University, found that ACE students’ five-year graduation rate was 11.7 percentage points higher than the rate of students who were eligible for, but not enrolled in, the program.

> The researchers also calculated that the net social benefits for each participant in the program equal about $48,000—or $3.06 per taxpayer dollar spent on the program—most of which comes from the students’ increased earnings.




----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)

To see a listing by topic in reverse chronological manner

[https://cunytracker.github.io/CUNYTracker/bytopic.html](https://cunytracker.github.io/CUNYTracker/bytopic.html)
