# Jun 27

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

Thanks to BE and KB, for contributions this week.


## Alliances

* MADCs Tracker (U Mass Amherst)

[https://www.umass.edu/senate/madcs-tracker](https://www.umass.edu/senate/madcs-tracker)

(Lots of CUNY campuses noted herein)


## Protests

* One military ethics professor has resigned from teaching in protest, telling @RadioFreeTom that staying would have been both morally and practically untenable after chilling orders from Donald Trump and Pete Hegseth went into effect.

[https://www.theatlantic.com/ideas/archive/2025/06/academic-freedom-naval-war-college/683309/?gift=h1dV60W2A3Fojj_roXuAolYWcUkZgtqTyh3LGmPuw9Y](https://www.theatlantic.com/ideas/archive/2025/06/academic-freedom-naval-war-college/683309/?gift=h1dV60W2A3Fojj_roXuAolYWcUkZgtqTyh3LGmPuw9Y)

(Thanks BE)

## Survey results

* More Americans Trust Public Universities Than Private Ones

[https://www.insidehighered.com/news/quick-takes/2025/06/23/more-americans-trust-public-universities-private-ones](https://www.insidehighered.com/news/quick-takes/2025/06/23/more-americans-trust-public-universities-private-ones)

(Thanks BE)

>  While nearly half of respondents (46 percent) indicated they have “a great deal” or “quite a lot” of confidence in public institutions, only 30 percent reported the same for private institutions.
> Despite the public’s declining confidence in institutions of higher education, 76 percent of Americans think a college education is very or somewhat important for success. Ninety percent of Democrats, 71 percent of Republicans and 72 percent of Independents agree that a college education is at least somewhat important.

## How best to describe the times we are in

* The Republican Plot to Un-Educate America | The New Republic

[https://newrepublic.com/article/197017/budget-bill-kill-higher-education](https://newrepublic.com/article/197017/budget-bill-kill-higher-education)

> Trump’s “big, beautiful bill” is an extinction-level event for higher education that would annihilate the country’s intellectual potential.

> For colleges and universities, the potential fallout is hard to overstate. Whatever schools survive are likely to be drained of working- and middle-class families, instead populated only by society’s most wealthy. As it is, millions of people rightly consider universities to be a costly endeavor that is irrelevant to their everyday life. But rather than remaking higher ed into a vibrant and more democratic institution, this bill threatens to do the opposite. It will cement the stereotype of higher education as an elite institution into an ironclad reality. On June 25, student debtors and their allies will be protesting these devastating cuts in Washington, D.C. But so far, very few elected officials are sounding the alarm on these issues with the fever pitch they deserve, let alone doing the work required to slow down and obstruct their passage into law.

> In the words of influential conservative activist Christopher Rufo, “Reforming the student loan programs could put the whole university sector into a significant recession” and state of “existential terror.” The goal is to use economic policy to impose an unpopular and stifling ideological agenda, exacted by punitive student debt.

> These cuts won’t just harm students who rely on loans to afford college; they will take the doors off colleges’ and universities’ capacity to expand minds and redistribute opportunity. Lost revenue will encourage schools to close programs, squeeze staff, and perhaps shutter entirely. A proposed endowment tax for colleges and universities has prompted fury among higher education lobbyists, but those players have said very little about the bill’s vigorous imposition of debt as a tool of social control.

> Contemporary Republicans are even more brazen. Consider a recent report released by the Heritage Foundation that recommends terminating higher education “subsidies” and student loan cancellation in order to “increase the married birthrate.” What does this goulash mean in plain English?

## Academic freedom

* Academic Freedom Was Already Limited at U.S. Service Academies. Then Came Trump.


[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/06/23/academic-freedom-service-academies-dissipates-under](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/06/23/academic-freedom-service-academies-dissipates-under)

(Thanks BE for sharing)

> Officials are restricting education about diversity and criticism of the U.S. It’s an erosion of rights within the institutions training America’s future military officers.

> A week into his second presidential term, Donald Trump issued an executive order banning service academies under the Defense Department—the U.S Military Academy at West Point, the U.S. Naval Academy and the U.S. Air Force Academy—from “promoting, advancing, or otherwise inculcating the following un-American, divisive, discriminatory, radical, extremist, and irrational theories.” The theories listed were “divisive concepts,” “gender ideology,” race or sex “stereotyping” and “scapegoating,” and the idea “that America’s founding documents are racist or sexist.”

> The Times also reported that Christopher Barth, West Point’s senior librarian, is resigning after 14 years amid demands that he identify books that might violate Hegseth’s order. West Point didn’t answer most questions that Inside Higher Ed posed to it, including whether books have actually been removed.

> At the Naval Academy, Tom McCarthy resigned from his role as history department chair this month, The Baltimore Sun reported. The Naval Academy confirmed his resignation letter to Inside Higher Ed.

* ‘A Banner Year for Censorship’: More States Are Restricting Classroom Discussions on Race and Gender

[https://www.chronicle.com/article/a-banner-year-for-censorship-more-states-are-restricting-classroom-discussions-on-race-and-gender](https://www.chronicle.com/article/a-banner-year-for-censorship-more-states-are-restricting-classroom-discussions-on-race-and-gender)

> Teaching social work in Tuscaloosa, Ala., Cassandra E. Simon often assigns readings that describe how the families her students might one day serve have been impacted by more than a century of housing, employment, and education discrimination. The associate professor has encouraged her students to engage in spirited discussions about race, even assigning a project in which they advocate for or against a social-justice issue.

> Doing any of those things today, she argues in a federal lawsuit, could get her fired from the state flagship, where she’s taught for 25 years. Last year, the state’s Republican governor, Kay Ivey, signed into law a sweeping bill that restricts what professors can teach about race. If any of their lessons veer into what conservative politicians have deemed “divisive concepts,” faculty members risk being reported, investigated, and potentially fired.

>  But over the past two years, more than a dozen laws have been enacted that either limit which classes can be taught or imposed restrictions on what professors can say in the classroom, according to a Chronicle analysis of state legislation and a compilation of what PEN America calls “educational gag orders.”

> This year especially “has been a banner year for censorship at a state level across the country,” said Amy B. Reid, senior manager at PEN America’s Freedom to Learn program. “The point of a lot of these restrictions is to put people on guard, worried that anything or everything could be prohibited so you really have to watch what you say.”



## Freedom of expression

* Texas looks to enact restrictions on when and how students can protest

[https://www.washingtonpost.com/nation/2025/06/20/texas-campus-speech-law-palestine-protests/](https://www.washingtonpost.com/nation/2025/06/20/texas-campus-speech-law-palestine-protests/)

> Senate Bill 2972 prohibits protesting between the hours of 10 p.m. and 8 a.m., or during the last two weeks of the semester; and bans students from camping or erecting tents on campus, or wearing a disguise to conceal their identity. It also bars the use of microphones and drums.

> Republicans in Texas say the proposal will prevent campus disruption and intimidation seen during last year’s pro-Palestinian protests. But critics across the political spectrum, such as the free speech advocacy group Foundation for Individual Rights and Expression, say the proposal is too broad and threatens all forms of expressive activity.

> “Wearing a MAGA hat or a Bernie [Sanders] T-shirt would be prohibited between 10 p.m. and 8 a.m. because the political apparel is an expressive act, and therefore covered as an expressive activity,” said Tyler Coward, FIRE’s lead counsel for government affairs.

> Under the proposed law, universities could bar a guest speaker from campus if school officials believe there will be a large protest, Coward said.

* Texas Governor Signs Bill to Limit Expressive Activity on Campuses

[https://www.insidehighered.com/news/students/free-speech/2025/06/23/texas-passes-bill-limiting-expressive-activity-campus](https://www.insidehighered.com/news/students/free-speech/2025/06/23/texas-passes-bill-limiting-expressive-activity-campus)

> Texas governor Greg Abbott has signed a controversial bill that would restrict expressive activities on college campuses, reversing some of the rights afforded by a 2019 bill intended to protect Texans’ ability to protest on campuses.

* Texas Governor Signs Law Giving Presidents Control of Faculty Senates

[https://www.insidehighered.com/news/quick-takes/2025/06/24/texas-passes-law-presidents-control-faculty-senates](https://www.insidehighered.com/news/quick-takes/2025/06/24/texas-passes-law-presidents-control-faculty-senates)

(These were highlighted in an earlier digest, but worth repeating...)

> Senate Bill 37 says that only an institution’s governing board can create a faculty council or senate. If a board decides to keep one, the college or university president gets to pick the “presiding officer, associate presiding officer, and secretary” and prescribe how the body conducts meetings.

> Unless the institution’s board decides otherwise, faculty governing bodies must shrink to no more than 60 members. The Texas A&M University Faculty Senate currently has 122.

> The 60 members must include at least two representatives from each of the colleges and schools that comprise the institution—including what the law describes vaguely as “one member appointed by the president or chief executive officer of the institution,” with the rest elected by the faculty of the particular school or college. This could mean that half of a faculty senate would be chosen by the president, barring an exemption by the institution’s board.

> SB 37 also says an institution’s provost can recommend to the president that members be “immediately removed” for failing to attend meetings or not conducting their “responsibilities within the council’s or senate’s parameters,” or for “similar misconduct.”

### Anti-woke/anti-DEI is simply racism

* NYTimes: Trump Says He Wants to Fund More Trade Schools. Just Not These.

[https://www.nytimes.com/2025/06/21/business/job-corps-trump-trade-schools.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/21/business/job-corps-trump-trade-schools.html?smid=nytcore-ios-share&referringSource=articleShare)

> “The program is no longer achieving the intended outcomes that students deserve,” Labor Secretary Lori Chavez-DeRemer said in a statement announcing the shutdown.

> The abrupt decision reignited a longstanding debate over the program’s merits and effectiveness. It also created a new point of contention in President Trump’s efforts to cut costs by dismantling elements of the social safety net. As Congress debates a budget bill that would reduce funding for federal anti-poverty programs such as Medicaid and food benefits, the White House is also proposing that the Job Corps, with its nearly $1.8 billion budget, be eliminated.

* Trump DEI Purge Made Black Women in Federal Jobs an “Easy Target” — ProPublica

[https://www.propublica.org/article/trump-dei-black-women-minorities-careers-jobs-dismissed](https://www.propublica.org/article/trump-dei-black-women-minorities-careers-jobs-dismissed)

> Her experience is part of a largely untold story unfolding as Trump dismantles civil rights and inclusion programs across government: Many of those being forced out, like Crowner, are Black women who spent decades building a career of government service, only to see those careers shattered in a sudden purge.

* NYTimes: How Trump Treats Black History Differently Than Other Parts of America’s Past

[https://www.nytimes.com/2025/06/20/us/politics/trump-black-history-federal-holidays.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/20/us/politics/trump-black-history-federal-holidays.html?smid=nytcore-ios-share&referringSource=articleShare)

> Chad Williams, a historian and professor of African American and Black diaspora studies at Boston University, said Mr. Trump’s actions, taken as a whole, showed that the administration was seeking to craft a “propaganda version of history.”

> “They’re trying to erase the history of Black struggle and Black resistance by denying the realities of racism and white supremacy,” Mr. Williams said. “They’re crafting a history that romanticizes the past at the expense of a true telling of the complexities and nuances of the American experience.”

* HBCUs Reel as Trump Cuts Black-Focused Grants: ‘This Is Our Existence’

[https://www.chronicle.com/article/hbcus-reel-as-trump-cuts-black-focused-grants-this-is-our-existence](https://www.chronicle.com/article/hbcus-reel-as-trump-cuts-black-focused-grants-this-is-our-existence)

> In less than three years, Quick [Tennessee State University’s Quincy Quick] helped raise $100 million in research grants, launch an AI research center, and bring Tennessee State significantly closer to becoming the second historically Black college and university to receive Research I status. But many of those grants focused on serving Black students and Black communities, a core part of the land-grant institution’s mission.

> As the VPs fretted over how they would retain vital research grants, one administrator quipped, “HBCUs won’t be affected because they don’t look at HBCUs as DEI.”

> Quick, the only HBCU administrator in attendance, recalled thinking, “That’s ridiculous, and it’s absolutely naïve. We absolutely would get hit. … And that’s exactly what has happened.”

> In total, the National Institutes of Health and the National Science Foundation have canceled more than $140 million in grants at HBCUs since March, according to a Chronicle analysis of two databases tracking grant cancellations.

> The NIH in March said that plans to enhance diversity are no longer required in training-grant applications, and “those included in applications under review will not be evaluated or considered in funding decisions.”

> The NSF said in April that research supported by the federal government must “aim to create opportunities for all Americans everywhere.” Federally supported research on protected groups must be open to all nonprotected groups.

> The agency has not provided guidance on what initiatives are considered DEI.

* NYTimes: Trump Justice Dept. Pressuring University of Virginia President to Resign

[https://www.nytimes.com/2025/06/26/us/politics/university-of-virginia-president-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/26/us/politics/university-of-virginia-president-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> The Trump administration has privately demanded that the University of Virginia oust its president to help resolve a Justice Department investigation into the school’s diversity, equity and inclusion efforts, according to three people briefed on the matter.

> The extraordinary condition the Justice Department has put on the school demonstrates that President Trump’s bid to shift the ideological tilt of the higher education system, which he views as hostile to conservatives, is more far-reaching than previously understood.

> Justice Department officials have told University of Virginia officials that hundreds of millions of dollars in federal funding are at risk because of what the department says is the school’s disregard for civil rights law over its diversity practices, according to two of the people.

> The demand to remove Mr. Ryan was made over the past month on several occasions by Gregory Brown, the deputy assistant attorney general for civil rights

> Harmeet K. Dhillon, the Justice Department’s top civil rights lawyer, has also been involved in negotiations with the university.

> Before becoming the University of Virginia’s president, Mr. Ryan served as the dean of the Harvard Graduate School of Education, where he was praised for his commitment to D.E.I. programs.

> The administration’s attempt to assert federal influence over state university leadership decisions is also illustrative of how Mr. Trump’s political appointees continue to wield the Justice Department’s investigative powers to achieve policy goals long sought by a top Trump adviser, Stephen Miller.

> But Mr. Ryan has been singled out by the Trump administration as his steps toward compliance have been criticized by conservative groups as insufficient. America First Legal, a nonprofit started by Mr. Miller, last month accused the University of Virginia of paying lip service to Mr. Trump’s orders by simply running the same diversity programs under a different name. The group issued a news release last month that called on the Justice Department to “hold UVA accountable.”

(also here)

[https://www.chronicle.com/article/tracking-trumps-higher-ed-agenda](https://www.chronicle.com/article/tracking-trumps-higher-ed-agenda)

* NYTimes: How Trump Upended 60 Years of Civil Rights in Two Months

[https://www.nytimes.com/2025/06/27/magazine/trump-civil-rights-law-discrimination.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/27/magazine/trump-civil-rights-law-discrimination.html?smid=nytcore-ios-share&referringSource=articleShare)

> Last year, a little-known office in the U.S. Department of Labor helped Black workers at a Texas medical center recover $900,000 in back wages, and Black workers at a Caterpillar manufacturing plant in Illinois recover $800,000, each time over allegations that those applicants lost out on jobs because of their race. Called the Office of Federal Contract Compliance Programs, this division investigates and fights employment discrimination for one-fifth of the U.S. labor force. It was created in 1965 when President Lyndon B. Johnson signed an executive order strengthening the provision of the Civil Rights Act of 1964 that banned racial discrimination by employers.

> On his second day in office, President Donald Trump labeled O.F.C.C.P.’s efforts to enforce the 1964 Civil Rights Act illegal and discriminatory — presumably against white people. He signed his own executive order revoking Johnson’s on behalf of, as he put it, “hardworking Americans who deserve a shot at the American dream.”

>  Yet in the opening months of his second term, Trump has capitalized on the unpopularity of equality efforts among some Americans, glibly wielding the language of D.E.I. to initiate the broadest and most significant assault on civil rights and racial integration in this country in more than a century.

> Conservatives have spent decades chipping away both at civil rights protections and the national will to address racial inequality. Since the racial reckoning of 2020, Republicans have toppled affirmative action in college admissions and waged an enormously successful campaign to make the language of equity and inclusion anathema, to label books and lessons about the nation’s history “anti-white” and “divisive” and to prohibit everything from Black studies to university diversity offices. And earlier this month, the Supreme Court, which over the years has made it increasingly challenging for Black Americans to prove discrimination, has now made it easier for straight white people to do so.

> The Education Department sent a letter to all educational institutions receiving federal funds asserting without evidence that they were engaging in “pervasive and repugnant race-based” discrimination against white and Asian students. Federal data shows that Black students are disproportionately concentrated in schools with fewer resources and less funding, and experience significant academic disparities. And yet the letter told public schools and universities that they had 14 days to purge all diversity and equity efforts — which include programs that try to help diversify teaching staffs and help Black students close the achievement gaps they suffer from nationwide — or lose access to federal funds.

> But probably the starkest change is the redirecting of the Department of Justice away from fighting anti-Black discrimination and toward eliminating integration efforts. Harmeet Dhillon, the new head of the department’s Civil Rights Division, sent a memo to the staff making it clear the mandate going forward would be to enforce Trump’s executive orders targeting diversity programs.

(A long, well written and researched article, very much worth clicking through)

## Funding cuts

### NSF

* NSF Indirect Cost Cap Unlawful, Judge Rules


[https://www.insidehighered.com/news/quick-takes/2025/06/24/federal-judge-vacates-nsf-indirect-cost-cap](https://www.insidehighered.com/news/quick-takes/2025/06/24/federal-judge-vacates-nsf-indirect-cost-cap)

> federal judge tossed out the National Science Foundation’s policy capping reimbursements for costs indirectly related to research, finding “severe” deficiencies in the agency’s reasoning for the plan as well as “errors of law.”

> The ruling from Judge Indira Talwani of the District of Massachusetts is the first final judgment against the 15 percent cap, which three other federal agencies have also sought to implement. Judges have temporarily blocked those caps, but in this lawsuit, the plaintiffs sought summary judgement, which allows the judge to reach a final decision without a trial.

> Thirteen universities along with the Association of American Universities, the Association of Public and Land-grant Universities, and the American Council on Education sued the NSF in May to block the cap, arguing the policy would cut funding to institutions and risk the country’s standing “as a world leader in scientific discovery.” The government’s lawyers said in court filings that the cap would have meant a cut of $432.3 million for colleges and universities in fiscal year 2024.

* Trump Administration Ousts National Science Foundation from Headquarters Building

[https://www.scientificamerican.com/article/trump-administration-ousts-national-science-foundation-from-headquarters/](https://www.scientificamerican.com/article/trump-administration-ousts-national-science-foundation-from-headquarters/)

> The Department of Housing and Urban Development is expected to announce Wednesday that it’s moving into the headquarters of the National Science Foundation in Alexandria, Virginia, according to the union representing NSF employees.

> The union, Soriano wrote, “understands that there is no planning except that the HUD secretary may take over the 18th and 19th floors” and start planning the HUD move over the next two years. “There is no planning for NSF, no identified future location, appropriation for a new building or a move,” he wrote.

(A bluesky post lists HUD secretaries designs to take over the 19th floor for him; build out an executive dining room, reserve 5 personal parking spaces, have exclusive use of 1 elevator, have all assistants on the 18th floor)

Also

[https://www.washingtonpost.com/dc-md-va/2025/06/25/housing-hud-relocation/](https://www.washingtonpost.com/dc-md-va/2025/06/25/housing-hud-relocation/)

> The move will displace about 1,800 employees at the National Science Foundation, which has faced massive spending cuts under the Trump administration. Administration officials on Wednesday did not say where those NSF workers would end up, but Peters said the search for a new location would aim to minimize disruption to those employees’ lives and work.

> The frustration added to broader discontent at HUD, the backbone of the federal government’s housing policy. Since Trump’s inauguration, the department has sought to slash funding for fair housing efforts, rental assistance, housing vouchers and homelessness prevention. So many staffers took the second-round buyout offer that officials are trying to get people to voluntarily move into vacant roles.

> “This callous disregard for taxpayer dollars and NSF employees comes after the Administration already cut NSF’s budget, staff and science grants and forced NSF employees back into the office,” the union said.


### DOD

* Trump admin curtails colleges’ defense research

[Politico Weekly Education email]

> FUNDING CUTS: The Department of Defense is shrinking research funding at various colleges and universities, a move that academics say curtails projects that keep U.S. troops safe.

> Earlier this month, the administration notified universities it would cut facility and administrative reimbursements to 15 percent for all DOD research grants focused on protecting military service members and strengthening national defense. These rates are negotiated between individual institutions and the government, but often fall between 50 percent and 65 percent.

> Separate from the lawsuit, Cornell received 75 stop-work orders from DOD, which affected research pertaining to national defense, cybersecurity, and health.

[https://statements.cornell.edu/2025/20250408-federal-research-funding.cfm](https://statements.cornell.edu/2025/20250408-federal-research-funding.cfm)

### DOE

* The Education Department is paying us millions not to work

[https://www.washingtonpost.com/opinions/2025/06/23/education-department-layoffs-doge-afge/](https://www.washingtonpost.com/opinions/2025/06/23/education-department-layoffs-doge-afge/)

* Nearly two million student loan borrowers are at risk of having their wages garnished this summer

[https://www.wsj.com/personal-finance/student-loan-wage-garnishment-07fc4d2a?st=wKEnzN&reflink=article_gmail_share](https://www.wsj.com/personal-finance/student-loan-wage-garnishment-07fc4d2a?st=wKEnzN&reflink=article_gmail_share)

[https://www.insidehighered.com/news/students/financial-aid/2025/06/24/federal-cuts-could-lead-reduced-financial-aid-offers](https://www.insidehighered.com/news/students/financial-aid/2025/06/24/federal-cuts-could-lead-reduced-financial-aid-offers)

## Congressional actions

* Congress Eyes Cap on Parent PLUS Loans

[https://www.insidehighered.com/news/students/financial-aid/2025/06/25/advocates-say-parent-plus-caps-will-reduce-college-access](https://www.insidehighered.com/news/students/financial-aid/2025/06/25/advocates-say-parent-plus-caps-will-reduce-college-access)

> Both House and Senate Republicans want to cap how much parents can borrow via the Parent PLUS loan program, though they disagree about the amount. The House plan limits parents to $50,000 total, while the Senate plan would allow them to borrow up to $65,000 per dependent. Currently, the loans are uncapped, so parents can borrow as much as they need.

> (Sen. Bill Cassidy, a Louisiana Republican, said at a recent hearing that about 34 percent of those with Parent PLUS loans borrow above the House’s proposed cap of $50,000.)

> The proposed caps are just one of many cuts to student aid that Congress has included in recent proposals as part of the process known as reconciliation. The House version of the bill, which includes steeper cuts and restrictions across the board, passed in late May, while the Senate continues to finalize its proposal and is planning to vote on it as soon as this week. President Donald Trump has said he wants to sign what he’s dubbed the One Big Beautiful Bill Act by July 4.

> But college-accessibility advocates have warned that the legislation will inevitably make college less affordable and loans more difficult to pay off for millions of Americans.

* TransUnion: 5M Borrowers Could Default by September

[https://www.insidehighered.com/news/quick-takes/2025/06/25/transunion-5m-borrowers-could-default-september](https://www.insidehighered.com/news/quick-takes/2025/06/25/transunion-5m-borrowers-could-default-september)

> The TransUnion analysis found that as of April 2025, nearly one-third of borrowers were more than 90 days past due on their loans—a roughly 10-percentage-point jump compared to February 2025. Before the government paused payments in spring 2020 because of the pandemic, just 11.7 percent of borrowers fell into this category.

> Borrowers default when they are 270 days behind on their payments. TransUnion expects about 1.8 million borrowers to default in July, followed by another million in August and then another two million in September.

> The Education Department resumed debt collections in May—the first time in more than three years that borrowers who defaulted on their loans faced the harshest consequences. Since that announcement, Education Secretary Linda McMahon and other officials have worked to spread the word about the consequences of default and defended the restart as necessary to shore up the student loan system. They’ve encouraged borrowers to get in touch with their student loan servicer and urged colleges to get involved as well.

> The Trump administration did plan to withhold some federal benefits such as tax returns and Social Security checks, but officials later backed off that part of that plan.

> But so far, the department has held off on restarting its automatic wage garnishment system, in which they can dock up to 15 percent of a defaulted borrower’s paycheck. The agency plans to resume that system this summer.

* Graduate Programs Face a Federal Reckoning


[https://www.insidehighered.com/news/admissions/graduate/2025/06/26/can-graduate-programs-survive-federal-loan-caps](https://www.insidehighered.com/news/admissions/graduate/2025/06/26/can-graduate-programs-survive-federal-loan-caps)

> Congress wants to significantly cut back on federal loans for grad students. That could decimate the highly profitable graduate degree market—and limit who has access to it.

> The Senate version of the reconciliation bill, which President Donald Trump has urged Congress to pass as early as next week, would cap professional degree loans at $200,000 and all other graduate loans at $100,000. Both the House and the Senate also proposed completely eliminating Grad PLUS, an unsubsidized federal loan with no borrowing limit that has helped students from modest backgrounds pay for graduate degrees since 2006.

(This doesn't seem to have an impact on CUNY students)

* Education Department Outlines Plan to Change Debt-Relief Program for Public Servants

[https://www.insidehighered.com/news/government/student-aid-policy/2025/06/26/education-department-outlines-plan-change-pslf-rules](https://www.insidehighered.com/news/government/student-aid-policy/2025/06/26/education-department-outlines-plan-change-pslf-rules)

(This is a bit misplaced, but this would impact CUNY students)

> Critics worry that the changes could derail debt relief for borrowers and allow the administration to block funds from reaching public servants who work in fields or for employers that the president disagrees with.

> “The law does not empower the Secretary of Education to opine on the supposed illegality of a public service employer’s mission—an unprecedented exercise of executive power that extends far beyond the Higher Education Act,” said Mike Pierce, executive director of the Student Borrower Protection Center, which shared a copy of the issue paper with Inside Higher Ed.

## Institutional assaults

### Harvard

* NYTimes: Harvard and Trump Restart Talks to Potentially End Bitter Dispute

[https://www.nytimes.com/2025/06/20/us/politics/harvard-federal-funding-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/20/us/politics/harvard-federal-funding-trump.html?smid=nytcore-ios-share&referringSource=articleShare)


> It is unclear how close both sides are to a potential deal and the exact terms any final agreement would entail. In a post on Truth Social, Mr. Trump said it was “very possible that a Deal will be announced over the next week or so.”

> Harvard has been widely praised by Democrats, academics, its alumni and democracy advocates for fighting the Trump administration. But top Harvard officials, according to two people briefed on the matter, have become increasingly convinced in recent weeks that the school has little choice but to try to strike a deal with the White House.

> The Harvard officials believe that if the university remains at odds with the administration that it is likely to become far smaller and less ambitious as Mr. Trump tries to keep pummeling it with funding cuts, federal investigations and limits on visas for international students.

> In exchange, Harvard would agree to take even more aggressive action than it already has to address issues such as antisemitism, race, and viewpoint diversity. The White House has pushed Harvard to make new commitments to change its admissions and hiring practices, one of the people close to the negotiations said.

> The White House, according to one person briefed on the negotiations, hopes that an agreement with Harvard might serve as a framework for other elite colleges to strike deals with Mr. Trump. Other schools have been in discussions with the Trump administration about making deals that would keep their federal funding intact and avoid the president’s ire, two of the people said.

> Among other conditions, the administration wanted Harvard to establish “merit based” hiring and admissions policies, and to see the influence of its faculty curbed. It sought a review for “viewpoint diversity,” the shutdown of any programs related to diversity, equity and inclusion, and an outside review to examine “those programs and departments that most fuel antisemitic harassment or reflect ideological capture.”

> The government also asked for Harvard to adjust its “recruitment, screening and admissions of international students,” audits of university data and reports “at least until the end of 2028” about the university’s compliance with the Trump administration’s conditions.

> Until recently, though, Harvard’s top board resisted talks. The members directed the school’s battalion of lawyers, many of them fixtures of conservative legal circles, not to engage with the government.

> The calculus has since shifted, in parallel with a handful of courtroom successes for Harvard and Mr. Trump’s public venting that the university had drawn a favorable judge.

(Anyways, if Harvard bends it will be a gigantic blow to higher education. This article tries to narrow the "deal" to it impacting other top colleges, but this just opens the gates to asking for more and more and more, as the same threats can be reapplied by an administration that doesn't honor past "deals".)

* NYTimes: Trump Administration Live Updates: Federal Judge Blocks Efforts to Keep International Students Out of Harvard

[https://www.nytimes.com/live/2025/06/20/us/trump-news?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/live/2025/06/20/us/trump-news?smid=nytcore-ios-share&referringSource=articleShare)

> Harvard dispute: A federal judge on Friday froze the Trump administration’s effort to stop international students from enrolling at Harvard University. The preliminary injunction, from a federal court in Boston, allows about 7,000 Harvard students and recent graduates to continue to study and work legally in the United States. Read more ›

* NYTimes: What to Know About Harvard’s Legal Battles With Trump

[https://www.nytimes.com/article/harvard-trump-legal-battles.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/article/harvard-trump-legal-battles.html?smid=nytcore-ios-share&referringSource=articleShare)


* Judge Grants Harvard Injunction in International Student Case

[https://www.insidehighered.com/news/quick-takes/2025/06/20/judge-says-harvard-can-enroll-international-students-now](https://www.insidehighered.com/news/quick-takes/2025/06/20/judge-says-harvard-can-enroll-international-students-now)

> District Judge Allison Burroughs granted a preliminary injunction to Harvard University on Friday in its case challenging the Trump administration’s efforts to prevent the university from enrolling international students.

> The injunction prevents the Department of Homeland Security from stripping Harvard of its Student Exchange and Visitor Program certification until Burroughs issues a final ruling in the lawsuit. It does not address President Donald Trump’s executive proclamation from earlier this month banning the State Department from issuing visas to international students and researchers attending Harvard; a temporary restriction on that ban expired June 20.

* NYTimes: ‘Are We Past Peak Harvard?’: 3 Writers Mull Higher Education’s Woes

[https://www.nytimes.com/2025/06/22/opinion/trump-higher-education-harvard.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/22/opinion/trump-higher-education-harvard.html?smid=nytcore-ios-share&referringSource=articleShare)

> Larry Summers: Maybe, but there are countervailing forces. Harvard’s relative prestige rises with the square of the distance from Cambridge, and so a global talent competition helps it. The greatest universities are drivers of progress. The 21st century will be a center of the life sciences, and because of Harvard, M.I.T. and their affiliates, Boston and Cambridge are ground zero, creating a flywheel effect with Stanford and digital technology. If anything, the trend is toward a higher fraction of government, business, artistic elites coming from elite schools as they get better at drawing talent.

> Summers: The trend could break if Trump stays super-destructive, courts are super-tolerant and the universities don’t adapt and settle. That is a real worry. My best guess, though, is that the need for universities as economic engines, the enforcement of law and the fact that there is low-hanging fruit for cultural correction in the universities will carry the day. I don’t think there is yet evidence of leading universities losing their appeal. Yes, there is a need to walk back from crazy, as there was after the 1960s. My guess is this will happen. You will see versions of Stanford’s Hoover Institution on many campuses, more emphasis on nonideological science and a big walk back on identity politics.

> Bruni: Ross, it’s clear that Trump and his allies actually don’t want sweeping protections for free speech. They correctly called out intolerance on the left but are now replacing it with intolerance from the right. When you’re essentially banning any mention of D.E.I., detaining students for political viewpoints they’ve articulated, putting institutions on notice that you’ll punish them for any deviation from just-two-genders orthodoxy, well, Trump is swapping one cancel culture for another. No?

(But there is no convincing Ross Douthat and Larry Summers carries around grudges about faculty for who knows when)

* NYTimes: Here Is All the Science at Risk in Trump’s Clash With Harvard

[https://www.nytimes.com/interactive/2025/06/22/upshot/harvard-funding-cuts.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/interactive/2025/06/22/upshot/harvard-funding-cuts.html?smid=nytcore-ios-share&referringSource=articleShare)

> The federal government annually spends billions funding research at Harvard, part of a decades-old system that is little understood by the public but essential to American science.

> This spring, nearly every dollar of that payment was cut off by the Trump administration, endangering much of the university’s research.

> The New York Times was able to identify more than 900 terminated grants, using court records, government databases and other internal university sources — a near-complete accounting of the cuts in the Trump administration’s escalating campaign to cripple the university.


(Accompanying infographic is top notch)

* Harvard flouted the rules. Now, it’s getting a hard lesson. (Kristi Noem can write...)

[https://www.washingtonpost.com/opinions/2025/06/23/kristi-noem-harvard-foreign-students-dhs-restriction/](https://www.washingtonpost.com/opinions/2025/06/23/kristi-noem-harvard-foreign-students-dhs-restriction/)

> I remain prepared to revoke Harvard University’s Student and Exchange Visitor Program certification, which allows the university to admit foreign students, because school leadership has not complied with the Department of Homeland Security’s lawful oversight duties, has fostered antisemitic extremism and used taxpayer money to collaborate with an American adversary.

(I'd quote more, but my keyboard might melt)

* NYTimes: Judge Blocks Trump Proclamation Barring Harvard’s International Students

[https://www.nytimes.com/2025/06/23/us/harvard-trump-international-students.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/23/us/harvard-trump-international-students.html?smid=nytcore-ios-share&referringSource=articleShare)

* NYTimes: Behind Closed Doors, Harvard Officials Debate a Risky Truce With Trump

[https://www.nytimes.com/2025/06/24/us/politics/harvard-debate-settlement-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/24/us/politics/harvard-debate-settlement-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> Harvard University, battered by a devastating conflict with the Trump administration that has jeopardized its elite standing, is facing a problem as it weighs a possible truce with President Trump: how to strike a deal without compromising its values or appearing to have capitulated.

> Unlike many other powerful institutions that have struck bargains with Mr. Trump, Harvard, the nation’s oldest and richest university, spent much of this spring as the vanguard of resistance to the White House, credited by academic leaders, alumni and pro-democracy activists for fighting the administration and serving as a formidable barrier against authoritarianism.

> Despite a series of legal wins against the administration, though, Harvard officials concluded in recent weeks that those victories alone might be insufficient to protect the university.

> Lee C. Bollinger, a former president of Columbia University and the University of Michigan, said that Harvard stood at a critical juncture in the history of American academia.

> “How you conduct yourself in these moments will say a lot over the future,” he said.

> He warned that allowing the government a say in hiring was a perilous threat to “a core, core academic freedom principle.”

> Many around academia are wary of the White House’s record. ...

* With stakes high, White House pushes negotiations with Harvard


[https://www.washingtonpost.com/education/2025/06/24/with-stakes-high-white-house-pushes-negotiations-with-harvard/](https://www.washingtonpost.com/education/2025/06/24/with-stakes-high-white-house-pushes-negotiations-with-harvard/)


> The Trump administration is ramping up negotiations with Harvard University in an effort to reach an end to its months-long battle with the elite school, two senior White House officials have said, as Harvard has been racking up legal wins in court.

> The administration expects a deal to land by the end of the month, one official said, and hopes the agreement would make a big enough splash to “basically be a blueprint for the rest of higher education.” The White House officials spoke on the condition of anonymity to discuss private deliberations.

> Harvard declined to comment.

> Harvard allies, free-speech advocates and others have feared that the Trump administration would use its attacks on Harvard to exert control over universities nationwide and dismantle academic freedom. Whatever the outcome, the case will create a significant precedent, said higher education attorney Sarah Hartley.

> “This is the playbook to be used with other universities by the government going forward,” said Hartley, a partner at the Washington-based law firm BCLP. “It, in many ways, is being used as a test of democracy and what the government can force on private institutions.”

> The government may have more motivation to come to a settlement outside of court than Harvard does, said higher education attorney Jodie Ferise, who believes Harvard has a stronger legal case.

> “The White House has every incentive to want to reach some kind of compromise, because I don’t think they’ll win this case,” she said.

> “The government cannot attempt a hostile takeover of any private institution, much less a private college or university, in order to impose its preferred vision of ideological balance,” the American Civil Liberties Union wrote in a brief filed with seven other organizations, including the right-leaning Cato Institute and Rutherford Institute.

* Harvard scientist accused of smuggling frog embryos faces new charges

[https://www.washingtonpost.com/nation/2025/06/26/harvard-researcher-frog-embryos-ice/](https://www.washingtonpost.com/nation/2025/06/26/harvard-researcher-frog-embryos-ice/)

> If convicted on the felony smuggling charge, Petrova could face up to 20 years in prison and be fined as much as $250,000. The new charges related to false statements are punishable by up to five years in prison and another $250,000 fine.


### Indiana

* Hundreds of IU degree programs at risk of disappearing – WFIU/WTIU News

(Thanks KB for sharing)


[https://wfiunews.wordpress.com/2025/06/24/hundreds-of-iu-degree-programs-at-risk-of-disappearing/](https://wfiunews.wordpress.com/2025/06/24/hundreds-of-iu-degree-programs-at-risk-of-disappearing/)

> Indiana University could lose hundreds of degree programs as part of compliance with an array of new laws affecting higher education that passed at the 11th hour of the legislative session. One of the laws requires public colleges and universities to eliminate programs with low numbers of degrees averaged over a three-year period. The cutoff is 15 graduates for a bachelor’s degree, seven for a master’s and three for a doctorate.


> So far, most faculty don’t know what to expect. President-elect of the Bloomington Faculty Council Heather Akou said she hasn’t heard anything from the university but that it’s “aggressively” moving to get in line with the law. “There are going to be big changes for this university, and the pace at which this is being pushed through is not designed for positive outcomes,” she said. “I have to say that my faculty colleagues are in panic to a degree that I have never seen before.”

> Most of the degrees with low numbers of recipients are in the humanities and languages. Jewish Studies, Classical Studies and multiple language departments could lose their main offerings. From 2020 to 2022, IU Bloomington conferred more humanities doctorates than any other university in the country, according to data from Carnegie Classifications. It also ranks first for number of languages taught, for now.

> “Even tenured faculty are wondering, am I going to have a job in two months?” Akou said. “We’re scheduled to teach classes. Will I be allowed to teach the classes I’m scheduled to teach this fall? I don’t know. That’s really the level of chaos and confusion that’s going on right now.” The university declined an interview, but spokesperson Mark Bode wrote in an email that “IU is working with campus leaders to comply with the process mandated by state law.”

### Others

* Justice Dept. says it is investigating Univ. of California hiring practices


[https://www.washingtonpost.com/education/2025/06/26/university-california-trump-dei-investigation-hiring-justice/](https://www.washingtonpost.com/education/2025/06/26/university-california-trump-dei-investigation-hiring-justice/)

> In a letter to University of California President Michael Drake dated Thursday, the Justice Department claimed a strategic growth plan created by the UC system that mentions diversity in hiring suggests that the educational institution “may be engaged” in discriminatory employment practices based on race or sex.

(May be the only people who take a strategic plan so seriously; ours is here
[https://www.cuny.edu/wp-content/uploads/sites/4/page-assets/about/chancellor/strategic-roadmap/CUNY_Lifting_New_York.pdf](https://www.cuny.edu/wp-content/uploads/sites/4/page-assets/about/chancellor/strategic-roadmap/CUNY_Lifting_New_York.pdf)
)

> The antisemitism probe at the UC system is supposed to determine whether a “hostile work environment” has existed for Jewish employees on its campuses. The investigation announced Monday, under Title VII of the Civil Rights Act, will similarly seek to determine whether discrimination has existed in UC hiring.

> “It is important to note that we have not reached any conclusions about the subject matter of the investigation. We intend to consider all relevant information,” Harmeet K. Dhillon, the assistant attorney general for civil rights, said in her letter to Drake.

> Dhillon’s letter did not detail specific allegations of instances of hiring discrimination. She cited the University of California 2030 Capacity Plan as having “precipitated unlawful action,” specifically employment practices that may have discriminated against “employees, job applicants and training program participants based on race and sex.”

> In its strategic plan, the University of California says it is “committed to increasing the diversity of its faculty, both underrepresented minorities and female faculty.” The plan discusses efforts to diversify the faculty so that campuses better reflect the population of California, a goal partially rooted in helping populations who are less likely to graduate from college earn degrees.


## Blowback

* How Budget Cuts and a Loss of Trust Threaten Higher Ed’s Workforce

[https://www.insidehighered.com/news/faculty-issues/career-development/2025/06/23/budget-cuts-loss-trust-threaten-higher-eds](https://www.insidehighered.com/news/faculty-issues/career-development/2025/06/23/budget-cuts-loss-trust-threaten-higher-eds)

> The consequences of the sector’s financial instability and ongoing government attacks include anxiety among faculty and staff feeling the strain of hiring freezes, uncertainty about internal grant opportunities and even questions about having enough staff on hand to continue delivering basic services, said Kevin McClure, a professor of higher education and chair of the Department of Educational Leadership at the University of North Carolina at Wilmington.

> He added that leaders who have compromised their institutional values in response to political pressure have eroded the trust of their campus communities.

* FIU Donor Pulls Funds Over President’s Politics

[https://www.insidehighered.com/news/quick-takes/2025/06/26/fiu-donor-pulls-funds-over-presidents-politics](https://www.insidehighered.com/news/quick-takes/2025/06/26/fiu-donor-pulls-funds-over-presidents-politics)

> A Miami businessman has walked back a $1 million donation to Florida International University after lawmakers repealed in-state tuition for undocumented students, The Miami Herald reported.

## Tracking projects

* NSF Grant Terminations 2025

[https://grant-watch.us/](https://grant-watch.us/)

> Grant Watch is a project to track the termination of grants of scientific research agencies under the Trump administration in 2025. We currently are tracking terminations of grants from the National Institutes of Health (NIH) and the National Science Foundation (NSF).

> Grant Watch is a project of Noam Ross, Scott Delaney, Anthony Barente, and Emma Mairson, with input and support from additional volunteers.


[https://airtable.com/appGKlSVeXniQZkFC/shrFxbl1YTqb3AyOO?jntvk=allRecords](https://airtable.com/appGKlSVeXniQZkFC/shrFxbl1YTqb3AyOO?jntvk=allRecords)

( Division of Equity for Excellence in Stem)

[https://airtable.com/appGKlSVeXniQZkFC/shrFxbl1YTqb3AyOO?jntvk=sfs4XeBXKSQe4ON7e](https://airtable.com/appGKlSVeXniQZkFC/shrFxbl1YTqb3AyOO?jntvk=sfs4XeBXKSQe4ON7e)

(CUNY cuts; 16)

[https://airtable.com/appGKlSVeXniQZkFC/shrFxbl1YTqb3AyOO?jntvk=b%3AWzAsWyJuYk85TyIsMTEsIkNVTlkiXV0](https://airtable.com/appGKlSVeXniQZkFC/shrFxbl1YTqb3AyOO?jntvk=b%3AWzAsWyJuYk85TyIsMTEsIkNVTlkiXV0)

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
