# Jun 13

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

Of special note is the announcement that the Chancellor will be joined by the leaders from Georgetown and UC Berkeley at a congressional hearing. This will put CUNY further in the cross hairs of the federal government.

Thanks to VAC, KB for sharing links

## Protests

* What Are the ‘No Kings’ Protests? 1,800 Anti-Trump Events on June 14

[https://www.rollingstone.com/politics/politics-features/trump-no-kings-protests-june-14-los-angeles-1235359409/](https://www.rollingstone.com/politics/politics-features/trump-no-kings-protests-june-14-los-angeles-1235359409/)

(Join millions. The PSC is meeting at Guttman beforehand)

> Protest organizers have billed June 14 as a “nationwide day of defiance,” during which Americans across the country stand up to “reject authoritarianism” and reclaim patriotism in the name of democracy. “The flag doesn’t belong to President Trump. It belongs to us,” the protest website declares.

> Trump has menaced demonstrators planning to show up at his military procession: “If any protester wants to come out, they will be met with very big force,” he said Tuesday. Anticipating such a reaction, protest organizers specifically decided not to target the Trump parade route; there is not even a No Kings event planned in D.C. They envision, instead, demonstrators “showing up everywhere [Trump] isn’t — to say no thrones, no crowns, no kings.”


## Letters

* The Bethesda Declaration: A Call for NIH and HHS Leadership to Deliver on Promises of Academic Freedom and Scientific Excellence

[https://www.standupforscience.net/bethesda-declaration?utm_source=pressrel&utm_campaign=bethesdadec](https://www.standupforscience.net/bethesda-declaration?utm_source=pressrel&utm_campaign=bethesdadec)

> For staff across the National Institutes of Health (NIH), we dissent to Administration policies that undermine the NIH mission, waste public resources, and harm the health of Americans and people across the globe. Keeping NIH at the forefront of biomedical research requires our stalwart commitment to continuous improvement. But the life-and-death nature of our work demands that changes be thoughtful and vetted. We are compelled to speak up when our leadership prioritizes political momentum over human safety and faithful stewardship of public resources.

* Sign the Open Letter to Urge USC to Respect our Voice, Respect Our Vote

[https://unitedfaculty-uaw.org/sign-the-open-letter-usc-respect-our-voice-respect-our-vote/](https://unitedfaculty-uaw.org/sign-the-open-letter-usc-respect-our-voice-respect-our-vote/)

(Thanks KB)

> Over the past several weeks, many of us have been deeply concerned by the federal attacks on higher education – from catastrophic research-funding cuts to assaults on programs that make our universities more just and inclusive. Last year, a majority of us signed cards in support of forming our faculty union so that we can establish a real voice in our working lives.

> Unfortunately, USC has so far refused to honor our desire for a stronger voice.


## How best to describe the times we are in

* NYTimes: Harvard’s Battle Is Familiar to a University the Right Forced into Exile

[https://www.nytimes.com/2025/06/08/us/trump-harvard-hungary-orban-george-soros.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/08/us/trump-harvard-hungary-orban-george-soros.html?smid=nytcore-ios-share&referringSource=articleShare)

> As the Trump administration escalates its pressure campaign, more people in American higher education — and in Vienna — believe the U.S. government is borrowing from a playbook refined in recent years by Prime Minister Viktor Orban, who used state power to menace a university he disdained, upend academic independence and strengthen his ideological grip on Hungary.

> “At the abstract level, it’s the same,” said Carsten Q. Schneider, a German scholar who has worked for C.E.U. for more than 20 years and will become its interim president and rector in August.

> “These demands, these requirements, they are a scale of detail that Orban never bothered with,” Tim Crane, a Britain-born philosophy professor, said at C.E.U.

> “Universities and their allies need to speak up in defense of core values,” she [Amy Gutmann, a political scientist who led the University of Pennsylvania for nearly 18 years and then served as President Joseph R. Biden Jr.’s ambassador to Germany] said, adding that “the C.E.U. experience warns against the instinct to make concessions to an administration that’s intent on punishing the political opposition.”

> In Mr. Orban’s Hungary, sometimes described as a “propaganda state,” the government transferred control of public universities to foundations — controlled by the ruling party’s allies — and gender studies essentially became a forbidden academic discipline.

> In 2017, the Hungarian government, which some prominent figures on the American right have praised, stepped up its effort to undermine the American-accredited university. The campaign was built on legal maneuvering, including a hastily passed law, struck down years later by the European Court of Justice, effectively requiring C.E.U. to open a new campus in the United States.

> The university tried to negotiate, but talks with the Hungarian government failed in late 2018. Thousands of Hungarians protested the government’s tactics that year — “Even Voldemort didn’t kick Hogwarts out,” read one sign — but C.E.U. said it had no choice but to leave.

> Eva Kiser, a museum studies student at C.E.U. who is from Knoxville, Tenn., said she had been counting on political firewalls in the United States to hold and that things would “blow over.”

> “But that’s not really looking probable,” she said.

> “Don’t expect mercy, or that this is normal and you need to sort of be nice and then they come to their senses,” Dr. Schneider, the incoming interim rector, said. “It is unhinged. ..."

> Borrowing an idea from the economist Albert O. Hirschman, Professor Dorsch, an American, said universities had three options: leave, obey the government or speak up.

(Lots of salient quotes here, an article well worth reading, as the mafia state has learned some things from the propaganda state.)

* Notes from an Occupation

[https://www.nybooks.com/articles/2025/06/26/notes-from-an-occupation-marilynne-robinson/](https://www.nybooks.com/articles/2025/06/26/notes-from-an-occupation-marilynne-robinson/)

(Thanks VAC)

> A well-planned occupation seizes the heights of the defeated civilization, so that the people will see their leaders ousted or humiliated and made docile. It will likewise discredit and weaken those features of the culture in which its people placed confidence and pride. If this model were applied to our situation, we might expect to see the Supreme Court diminished, the Congress disempowered, and the Constitution desacralized by indifference or contempt. The press would come under attack. Our incomparable universities and research institutions would lose autonomy and resources. The mighty dollar would be weakened. Bonds with allies would be breached, and the occupied country would be held in contempt for the damage its default had done to the world order, and to democracy, having put aside its responsibility for demonstrating the viability of popular government.

> Examples of the seizing of cultural heights abound. In 70 AD the Romans utterly razed the Temple at Jerusalem and Jerusalem itself in order to deal with the Jewish population’s resistance to their oppression. In 1814 the British, still wanting to break the back of the Revolution, burned the American Capitol Building, destroying the Library of Congress.

> I am proposing, of course, that America actually is, at present, an occupied country. I will call the occupiers Red and the occupied Blue, since these colors are in general use for distinctions of this kind and seemingly cause no offense.

(More behind a paywall, I'm sure)

## Freedom of expression

* NYTimes: We Watched Dozens of Graduation Speeches. Here’s What We Found.

[https://www.nytimes.com/2025/06/08/us/graduation-speeches-2025.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/08/us/graduation-speeches-2025.html?smid=nytcore-ios-share&referringSource=articleShare)

> But plenty of others, including journalists, scientists and politicians from both parties, weighed in directly on the news of the moment. Many of them described 2025 in existential terms, warning about dire threats to free speech and democracy. Others heralded the dawn of a promising new American era.

* Mayor Adams signs executive order adopting antisemitism definition, urges Council to make it law

[https://gothamist.com/news/mayor-adams-signs-executive-order-adopting-antisemitism-definition-urges-council-to-make-it-law](https://gothamist.com/news/mayor-adams-signs-executive-order-adopting-antisemitism-definition-urges-council-to-make-it-law)

> The New York Civil Liberties Union accused Adams of "weaponizing the critical fight against antisemitism to suppress protected political speech he doesn’t like."

> "Advocates have warned for years that the IHRA definition of antisemitism recklessly conflates criticism of Israel with hate and violates the Constitution’s free speech protections," Donna Lieberman, the nonprofit's executive director, said in a statement. "It’s yet another example of the Mayor twisting to do [President Donald] Trump’s bidding."

## Visas

* NYTimes: Chinese Students Reconsider the U.S. as Republicans Threaten Their Visas

[https://www.nytimes.com/2025/06/07/us/politics/trump-chinese-students-visas.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/07/us/politics/trump-chinese-students-visas.html?smid=nytcore-ios-share&referringSource=articleShare)

> “Chinese students are practical,” he said. “They now have to consider whether, if they come to America, their studies will be disrupted. There’s no removing that uncertainty. That ship has sailed.”

## Loss of expertise

* Preserving the Federal Data Trump Is Trying to Purge

[https://www.insidehighered.com/news/government/science-research-policy/2025/06/10/preserving-federal-data-trump-trying-purge](https://www.insidehighered.com/news/government/science-research-policy/2025/06/10/preserving-federal-data-trump-trying-purge)

> Within days of taking office, the Trump administration began purging federal demographic data—on a wide range of topics, including public health, education and climate—from government websites to comply with the president’s bans on “gender ideology” and diversity, equity and inclusion initiatives.

> One of the first data sets to disappear was the White House Council on Environmental Quality’s Climate and Economic Justice Screening Tool, an interactive map of U.S. Census tracts “marginalized by underinvestment and overburdened by pollution,” according to a description written under a previous administration.

> That’s why she [Cathy Richards, a civic science fellow and data inclusion specialist at the Open Environmental Data Project] and scores of other concerned academic librarians, researchers and data whizzes are collaborating—many of them as unpaid volunteers—to preserve as much of that data as they can on nongovernment websites. Some of the groups involved include OEDP, the Data Rescue Project, Safeguarding Research and Culture, the Internet Archive, the End of Term Archive, and the Data.gov Archive, which is run by the Harvard Law School Library.

> ... “That took time,” Richards said, noting that not every data set and its accompanying metadata was easy to replicate. “Each varied significantly. Some required scraping. In one case I had to manually download 400 files, clicking each one every few minutes.”

## Funding cuts

### NIH

* NIH scientists go public with criticism over Trump cuts | AP News

[https://apnews.com/article/nih-letter-bethesda-declaration-bhattacharya-89724aee201f3e99fc1159adcbf9ac94](https://apnews.com/article/nih-letter-bethesda-declaration-bhattacharya-89724aee201f3e99fc1159adcbf9ac94)




### Fulbright

* Fulbright Board Quits, Accusing Trump Administration of Political Interference - The New York Times


[https://www.nytimes.com/2025/06/11/us/politics/fulbright-board-resign-trump.html](https://www.nytimes.com/2025/06/11/us/politics/fulbright-board-resign-trump.html)

> The dozen board members of the prestigious Fulbright program that promotes international educational exchanges resigned on Wednesday because of what they said was political interference by the Trump administration in their operations, according to people familiar with the issues and a board memo obtained by The New York Times.

[https://substack.com/inbox/post/165673358?r=17cemi](https://substack.com/inbox/post/165673358?r=17cemi)


> The members are concerned that political appointees at the State Department, which manages the program, are acting illegally by canceling the awarding of Fulbright scholarships to almost 200 American professors and researchers who are prepared to go to universities and other research institutions overseas starting this summer,

> In addition, the department is reviewing the applications of about 1,200 scholars from other countries who have already been approved by the board to come to the United States, the people said. Those foreign scholars were also supposed to receive acceptance letters around April.

> The board is also concerned that the budget that Secretary of State Marco Rubio is requesting from Congress for the next fiscal year cuts spending for the Bureau of Educational and Cultural Affairs, which includes the Fulbright program, to $50 million from $691 million this fiscal year.

> “The bipartisan Fulbright Board was mandated by Congress to be a check on the executive and to ensure that students, researchers and educators are not subjected to the blatant political favoritism that this administration is known for,” Ms. Shaheen, the top Democrat on the Senate Foreign Relations Committee, said in a statement.

> “While I understand and respect the bipartisan Fulbright Board for resigning en masse rather than grant credibility to a politicized and unlawful process,” she added, “I am painfully aware that today’s move will change the quality of Fulbright programming and the independent research that has made our country a leader in so many fields.”


## Federal Agencies

### DOE/OCR

* Colleges Can’t Trust the Federal Government. What Now?

[https://www.chronicle.com/article/colleges-cant-trust-the-federal-government-what-now](https://www.chronicle.com/article/colleges-cant-trust-the-federal-government-what-now)

> Support from the federal government has been so consistent and made such good sense that colleges and universities have built their budgets, infrastructure, and programming around the assumption of its permanence. Trump 2.0 has shown what happens when the government does not behave sensibly and has turned an essential lifeline into an existential risk.

> The scorched-earth assault on Harvard University is generating all the headlines, but it might in fact be drawing attention away from an even larger story: the tectonic shift in the future activities and financial underpinnings of American higher education and the even greater risk to institutions that have neither Harvard’s resources nor Harvard’s reputation.

> Even if universities manage to muddle through Trump’s vindictive irrationality, can they return to building budget models that assume consistently high levels of federal support? JD Vance is waiting in the wings, and who knows what new Trumps and Vances the future might bring?

> A small group of the most prestigious and selective universities might be able to substitute affluent domestic students for affluent international students at the undergraduate level, though even those institutions would likely have trouble doing so for master’s-degree programs, where costs are high and return on investment can be questionable. For most colleges, such a substitution would be impossible and tuition revenue would necessarily decline. Subtract the full-paying international students from the applicant pool and an already fragile financial structure would begin very quickly to collapse.

> For the ideologues driving the administration’s policies on education and immigration — Linda McMahon and Kristi Noem are not the brains behind this operation — the destructive effects of these various policies are very much the point. None of the consequences we are seeing are unintended.

> Devastating scientific research and systematically undermining the preeminence of American universities — like so many of the actions of the Trump administration — represents a triumph of vindictiveness and nihilism over sound public policy. But here we are, about to see how quickly and adroitly the embattled and change-resistant world of higher education can adapt to a future in which the government cannot be trusted.

### State actions

* Citing Ohio’s SB 1, College Refuses to Sign Union Contract

[https://www.insidehighered.com/news/faculty-issues/labor-unionization/2025/06/12/citing-ohios-sb-1-college-refuses-sign-union](https://www.insidehighered.com/news/faculty-issues/labor-unionization/2025/06/12/citing-ohios-sb-1-college-refuses-sign-union)

> United Faculty of Central Ohio Technical College union members and their institution are both citing state law in a dispute over whether the institution must sign a new collective bargaining agreement—or gut provisions it agreed to earlier in order to comply with the state’s sweeping new public higher education law.

## Institutional assaults

* In Texas, University Presidents May Soon Control Faculty Senates


[https://www.insidehighered.com/news/faculty-issues/shared-governance/2025/06/09/texas-presidents-may-soon-control-faculty-senates](https://www.insidehighered.com/news/faculty-issues/shared-governance/2025/06/09/texas-presidents-may-soon-control-faculty-senates)

> A bill awaiting Gov. Abbott’s signature would require college administrators to set procedures for faculty governing bodies and appoint their leaders, part of an effort to address “liberal faculty control over universities.”

> “Shared governance structures may not be used to obstruct, delay, or undermine necessary institutional reforms or serve as a mechanism for advancing ideological or political agendas,” says Senate Bill 37, which the Republican-dominated State Legislature passed May 31. Multiple states have considered GOP bills targeting shared governance, but SB 37 is a sweeping example.

> If a college or university board decides to keep a faculty governing body, the institution’s president gets to prescribe how it conducts meetings. The president also gets to pick the “presiding officer, associate presiding officer, and secretary.”

> In addition, unless the college or university’s board decides otherwise, faculty senates and councils must shrink to no more than 60 members.

> In another blow to faculty control of their own governance bodies, SB 37 establishes term limits for faculty senate and council members—and allows presidential appointees to serve longer than the elected members.

(Two years, then a two year break)

> A faculty senate or council member could also have their seat stripped at any time; the bill says the provost can recommend to the president that members be “immediately removed” for failing to attend meetings or conduct their “responsibilities within the council’s or senate’s parameters” or for “similar misconduct.”

(Will this be a national template if Abbott signs this bill? The reporting attributes the bill to one legislator, but I doubt their office drafted it.)

* Trump Ends Vital Higher Ed Data System Training

[https://www.insidehighered.com/news/government/politics-elections/2025/06/09/department-education-discontinues-ipeds-training](https://www.insidehighered.com/news/government/politics-elections/2025/06/09/department-education-discontinues-ipeds-training)

> Used to track trends in higher education enrollment, completion, financial aid usage and other institutional characteristics, IPEDS survey data has long been critical to higher education research. But in order to access and utilize the data, institutions need to know how to properly complete the survey and researchers need to know how to navigate the database.


* Project 2025 Author to Work at Education Department

[https://www.insidehighered.com/news/quick-takes/2025/06/09/project-2025-author-work-education-department](https://www.insidehighered.com/news/quick-takes/2025/06/09/project-2025-author-work-education-department)

> The Trump administration announced Friday that Lindsey Burke, the director of the Center for Education Policy at the Heritage Foundation, will be the department’s deputy chief of staff for policy and programs. Burke also authored the Education Department chapter of Project 2025, a conservative policy blueprint that called for sweeping changes to higher education policy, from privatizing student loans to rolling back LGBTQ+ protections in Title IX.

* Exclusive | Leaders of CUNY, other college antisemitism hotbeds to be grilled by House panel next month

[https://nypost.com/2025/06/09/us-news/leaders-of-cuny-other-college-antisemitism-hotbeds-to-be-grilled-by-house-panel-next-month/](https://nypost.com/2025/06/09/us-news/leaders-of-cuny-other-college-antisemitism-hotbeds-to-be-grilled-by-house-panel-next-month/)

(No need to click through. I'm sure one aisle's worth of the house panel will be as fair and factual as the publication I linked.)

* Senate Higher Ed Bill Walks Back Some House Proposals

[https://www.insidehighered.com/news/government/student-aid-policy/2025/06/12/how-senates-higher-ed-bill-differs-house](https://www.insidehighered.com/news/government/student-aid-policy/2025/06/12/how-senates-higher-ed-bill-differs-house)

> The Senate version, released late Tuesday night, is largely similar to the House’s proposal, which prompted widespread condemnation from student aid advocates when it passed in late May. Both would cap graduate loans, open up the Pell Grant program to short-term programs and cut all but one option for income-driven loan repayment.

> Most notably, the Senate bill does not include a limit on traditional Pell Grant eligibility that would have excluded thousands of part-time students, as the House version did, and it walks back the House’s controversial risk-sharing plan, which would force colleges to pay a penalty based on students’ unpaid loans.

* Republicans are keen on college sports legislation. Democrats are not.

[https://www.washingtonpost.com/sports/2025/06/12/congressional-hearing-on-college-sports/](https://www.washingtonpost.com/sports/2025/06/12/congressional-hearing-on-college-sports/)

(Compensation might be a huge financial hit for many schools, as there are additional costs related to employees.)

### Harvard

* Federal judge blocks Trump’s latest effort to ban Harvard's international students - POLITICO

[https://www.politico.com/news/2025/06/05/harvard-judge-trump-effort-ban-international-students-00391244](https://www.politico.com/news/2025/06/05/harvard-judge-trump-effort-ban-international-students-00391244)

* NYTimes: Harvard Taught This British Student About Democracy. Now Trump May Force Him Out.

[https://www.nytimes.com/2025/06/07/us/trump-harvard-international-student-ban.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/07/us/trump-harvard-international-student-ban.html?smid=nytcore-ios-share&referringSource=articleShare)

> Five weeks later, just after the end of the spring semester, Mr. Williamson [rom Wales], now at a summer abroad program, picked up his phone and saw a pileup of missed calls and messages. The threat his friends had dismissed had become a searing reality: The federal government had effectively blocked Harvard’s ability to enroll foreign students — abruptly thrusting Mr. Williamson and others into an excruciating limbo.

> He had arrived in Cambridge, Mass., intent on studying physics, drawn to its broad range of useful applications in other sciences. Then, during his first semester, he found a new passion — in a politics course taught by Steven Levitsky, the author of the best-selling book “How Democracies Die,” that featured a deep dive into authoritarianism. After that, Mr. Williamson planned to become a double major in physics and government. Maybe someday, he thought, he would make his own foray into politics or public service.

> “It was the best year of my life,” he said.

* In recent weeks, long-simmering Republican anger over Harvard’s links to China has increasingly gained traction


[https://www.wsj.com/world/china/harvards-china-ties-become-new-front-in-battle-with-trump-6eb24947?st=D2uR9P&reflink=article_gmail_share](https://www.wsj.com/world/china/harvards-china-ties-become-new-front-in-battle-with-trump-6eb24947?st=D2uR9P&reflink=article_gmail_share)

(There is always something to stir up republican anger...)

> Trump indicated that his concern about the Xinjiang corps was based on findings of a House Select Committee on China. Its chairman, Rep. John Moolenaar (R., Mich.), late last month wrote to Harvard President Alan Garber, demanding explanations about university activities that “create risks to U.S. national security and further the Chinese Communist Party’s (CCP’s) genocide in Xinjiang.”

* In Public, Harvard Is Fighting Trump. Quietly, It’s Dismantling a Program the White House Doesn’t Like.

[https://www.chronicle.com/article/in-public-harvard-is-fighting-trump-quietly-its-dismantling-a-program-the-white-house-doesnt-like](https://www.chronicle.com/article/in-public-harvard-is-fighting-trump-quietly-its-dismantling-a-program-the-white-house-doesnt-like)

> Harvard University has spent the last year slowly dismantling a religious-studies program that critics said was biased against Israel, five current and former university employees told The Chronicle. Last week, the final hammer fell: The five remaining staff members employed by the Religion and Public Life program were called, one by one, into meetings with a representative from Harvard’s human-resources department and the program’s interim director, David F. Holland. There, all learned their contracts would not be renewed.

> The program puts out a “wide range” of events and courses, McKanan said. But since the October 7 attacks, the program’s teaching around the Israeli-Palestinian conflict has drawn criticism from those who argue Harvard’s campus is a hotbed of antisemitism.

> In an internal report on antisemitism published in April, a task force of professors, students, and advisers had suggested that a lack of rigor among “nonladder” faculty at Harvard was partly to blame for programs and events that task-force members characterized as antisemitic. The task force recommended tenured Harvard faculty members exercise greater oversight of programs.

> Nonladder — or non-tenure-track — faculty deliver about half of the curriculum at the Divinity School, said McKanan, who has a nonladder contract and has been at Harvard for 17 years. “When Harvard chooses to rely on nonladder faculty,” he said, “it becomes a little bit strange and unnatural to exclude that half of the faculty from program leadership and from sponsoring public events on issues of urgent public concern.”

* NYTimes: Rubio Is Pressing to Open Sanctions Investigation Into Harvard

[https://www.nytimes.com/2025/06/11/us/politics/rubio-is-pressing-to-open-sanctions-investigation-into-harvard.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/11/us/politics/rubio-is-pressing-to-open-sanctions-investigation-into-harvard.html?smid=nytcore-ios-share&referringSource=articleShare)


(More weaponization of the federal government, err "Trump administration’s whole-of-government approach to bringing the Ivy League university to heel.")

> Secretary of State Marco Rubio is pushing to investigate whether Harvard University violated federal sanctions by collaborating on a health insurance conference in China that may have included officials blacklisted by the U.S. government, according to people familiar with the matter and documents reviewed by The New York Times.

> Mr. Trump and his allies appear determined [hell-bent] to upend nearly all aspects of the institution, which has long symbolized the pinnacle of higher learning in the country and attracted influential scholars from around the globe.

(And here we see the fingerprints of the Manhattan Institute)

> Still, the X.P.C.C.’s involvement in the conference only recently gained attention from Trump allies, after a report about Harvard’s links to China published on April 22 by Strategy Risks, a New York-based intelligence company specializing in corporate exposure to China. The report was funded by the Manhattan Institute, a conservative think tank that has advised Republican policymakers.

* NYTimes: What Happens if ‘Harvard Is Not Harvard’?

[https://www.nytimes.com/2025/06/11/us/harvard-funding-trump-administration.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/11/us/harvard-funding-trump-administration.html?smid=nytcore-ios-share&referringSource=articleShare)

> “Without its international students, Harvard is not Harvard,” school officials wrote in a lawsuit asking a judge to stop the federal government’s actions.

> It left unsaid what Harvard, if it were no longer Harvard, would become.

> But without federal dollars or international talent, experts say, Harvard could fall out of the top tier for research, where it currently sits with competitors like Stanford University and the Massachusetts Institute of Technology. By sheer dollars spent, its research budget could shrink to something similar to that of the University of Illinois Urbana-Champaign, which spent just over $800 million on research in 2023, roughly half of what Harvard spends now.

> Harvard could choose to negotiate. But inside the university, officials appear reluctant to do that, given the backlash they could face for capitulating to Mr. Trump. This spring, the university took out $750 million in debt, giving it some cash flow as court decisions play out.

> The atmosphere is particularly tense inside the Harvard T.H. Chan School of Public Health, which relies on federal funding for 46 percent of its budget and has a student body that is about 40 percent international. Senior officials there are planning for the worst, and have called the potential changes an “existential crisis” for the school’s future.

> But Harvard’s biggest source of funding is donations and payouts from its endowment, which together make up 45 percent of its revenue.


### Indiana

* At Indiana U., Professors Spar With Administrators Over Nighttime Protests

[https://www.chronicle.com/article/at-indiana-u-professors-spar-with-administrators-over-nighttime-protests](https://www.chronicle.com/article/at-indiana-u-professors-spar-with-administrators-over-nighttime-protests)

> Under a policy passed in response to a monthslong pro-Palestinian encampment at Indiana, certain forms of “expressive activity” — including holding protests, making speeches, and circulating petitions — were banned on campus between 11 p.m. and 6 a.m. Administrators argued that the changes were necessary to ensure safety after the encampment got out of hand.

> The policy banned protests between 11 p.m. and 6 a.m., required 10-day prior approval for installing “structures and/or mass physical objects,” and pushed protests 25 feet away from building entrances.

> Students and staff sued over the policy. In late May, a federal judge temporarily blocked the nighttime restrictions.

> Meanwhile, the political climate surrounding the university remains contentious. Last week, Gov. Mike Braun, a Republican, removed the three alumni-elected trustees from Indiana’s board — including two who voted against the expressive-activity policy — and replaced them with conservatives, including a prominent lawyer and a former ESPN anchor.

> Texas lawmakers just approved legislation broadly banning “any speech or expressive conduct protected by the First Amendment” between 10 p.m. and 8 a.m. at public universities. The measure now awaits the governor’s signature.

> But Indiana’s expressive-activity policy never specified how many nighttime protesters were too many. That meant even a protest involving two people — unlikely to be a threat to public safety — would require prior approval, the judge said in her order granting the preliminary injunction.

> While the decision was far from “novel or surprising,” it will hopefully send a message to universities imposing similar policies that “the courts are not going to put up with this kind of similarly open violation of the First Amendment and so they probably shouldn’t try it,” said Mary Anne Franks, a professor at the George Washington University Law School.

### Others

* Trump Administration Proposes Cutting Tribal College Funds by Nearly 90% — ProPublica


[https://www.propublica.org/article/tribal-colleges-universities-trump-cuts-funding](https://www.propublica.org/article/tribal-colleges-universities-trump-cuts-funding)

> The Trump administration has proposed cutting funding for tribal colleges and universities by nearly 90%, a move that would likely shut down most or all of the institutions created to serve students disadvantaged by the nation’s historic mistreatment of Indigenous communities.

> The document mentions only the two federally controlled tribal colleges — Haskell Indian Nations University and Southwestern Indian Polytechnic Institute — but notes the request for postsecondary programs will drop from more than $182 million this year to just over $22 million for 2026.

* Inside UNC’s Effort to Launch a New Accreditor

[https://www.insidehighered.com/news/governance/accreditation/2025/06/06/emails-shed-light-uncs-plans-create-new-accreditor](https://www.insidehighered.com/news/governance/accreditation/2025/06/06/emails-shed-light-uncs-plans-create-new-accreditor)

> Last month, Peter Hans, president of the University of North Carolina system, casually dropped a bombshell announcement that the system and others were in talks to launch a new accreditor.

> “We’ve been having a number of discussions with several other major public university systems, where we’re exploring the idea of creating an accreditor that would offer sound oversight,” Hans said at a UNC system Board of Governors meeting last month, The News & Observer reported.

> have been quietly engaged in conversations about launching a new accreditor for at least a year, including discussions with unnamed collaborators in Florida, where the effort could be headquartered. UNC officials have also spoken with officials at the U.S. Department of Education, even getting a heads-up on what an April 23 executive order from the Trump administration on accreditation would entail.

> “Everything Florida has done on accreditation over the past few years appears to be politically and ideologically driven, rather than about what is best for students and ensuring that they go to high-quality institutions and get a good education when they’re paying a lot of money for it and when taxpayers are investing a lot of money in public funding for higher education,” he said [Edward Conroy, a senior policy manager at the left-leaning think tank New America].

> Conroy worries that state lawmakers in either Florida or North Carolina would require public colleges in their state to be accredited by their new accreditor. That would undermine the current requirement that colleges get to choose their own accreditor.

### Alliances

* Harvard, Duke, Stanford and other wealthy universities are hoping to avoid a huge potential tax hike by pitching an alternative plan to Congress: a pledge to spend more of their own money


[https://www.wsj.com/us-news/education/colleges-hope-to-stave-off-big-tax-hike-by-pledging-to-spend-more-endowment-cash-353606fb?st=FTbBSQ&reflink=article_gmail_share](https://www.wsj.com/us-news/education/colleges-hope-to-stave-off-big-tax-hike-by-pledging-to-spend-more-endowment-cash-353606fb?st=FTbBSQ&reflink=article_gmail_share)

(They will spend 5% of their endowments. At CUNY the cap is 4% and some campuses spend less than this.)


## Blowback

* American students in China face a barrage of questions about Trump

[https://www.washingtonpost.com/world/2025/06/08/american-students-in-china/](https://www.washingtonpost.com/world/2025/06/08/american-students-in-china/)


> This type of “free diplomacy” was once commonplace. The number of Americans doing study abroad programs in China peaked at nearly 15,000 in 2011, before plummeting to 211 during the pandemic, when visa restrictions and rippling covid lockdowns made it hard for foreigners to enter the country.

* U.S. Curb on Chinese Students a Boon for Asian Universities

[https://www.insidehighered.com/news/admissions/2025/06/10/us-curbs-chinese-students-boon-asian-universities](https://www.insidehighered.com/news/admissions/2025/06/10/us-curbs-chinese-students-boon-asian-universities)

> “We’re not seeing sensationalist headlines in the media, and many families are watching and waiting for the final policy outcome and specific rules from the State Department,” he said. “There is an increasing awareness that the administration’s policies often start with big headlines of assertive nationalist policy, but they often end up being mitigated, reduced or overturned altogether.”

> Hongqing Yang, managing director of the Hong Kong–based consultancy The Educationist, said the Chinese government is likely “to encourage domestic institutions, including those in Hong Kong and Macao, as well as transnational education institutions and joint programs, to accommodate more students” in the wake of the news.

> In Hong Kong, the government explicitly encouraged universities to enroll Harvard students following the news.

> Laurie Pearcey, adviser to the president and college master at the University of Hong Kong Shenzhen, described the situation as a “free kick for Hong Kong.”

* NYTimes: Red-State Universities Will Get Hit by Trump’s Cuts, Too

[https://www.nytimes.com/2025/06/12/opinion/trump-harvard-scientific-research.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/12/opinion/trump-harvard-scientific-research.html?smid=nytcore-ios-share&referringSource=articleShare)


> Rather than striking a blow for red-state America, these cuts would actually take a heavy toll on many of the communities in states that went for Mr. Trump in the last election — whose research universities serve as crucial anchors for industry and innovation.

> If Mr. Trump wants to make all of America great again, he shouldn’t cut funding for scientific research. He should increase it.

(He doesn't, ed.)

> If the United States wants to compete with other countries for manufacturing jobs, our best strategy is to leverage our exceptional university research capabilities to rebuild our manufacturing base.

> Universities have long played pivotal roles in building world-class high-tech economies: Stanford University helped make Silicon Valley what it is today by fostering technological excellence in electrical engineering, establishing the Stanford Research Park and educating the founders of startups like Hewlett-Packard. Individuals from universities like M.I.T. and Harvard played central roles in transforming Boston from a center of textile and boot and shoe manufacturing to a health-sciences hub by starting the world’s first modern venture capital fund to commercialize academic research.

> Carnegie Mellon University helped revitalize Pittsburgh through targeted investments in computer science, artificial intelligence and robotics, coupled with strategic initiatives to bolster local entrepreneurship. The University of Texas at Austin mobilized local business and political leaders to transform Austin into a leading high-tech region. In all of these cases, universities led efforts to reposition their regional economies toward high-tech sectors such as computers, software, biotechnology and robotics.

## Coming attractions?

* Trump preparing large-scale cancellation of federal funding for California, sources say | CNN Politics


[https://www.cnn.com/2025/06/06/politics/trump-california-federal-funding](https://www.cnn.com/2025/06/06/politics/trump-california-federal-funding)

(Could just be a feint, but...)

> Just last month, he threatened to withhold federal funding from California over a transgender athlete’s participation in a sporting event — the latest example of the president trying to use funding as leverage to enact his agenda. The administration recently cut $126.4 million in flood prevention funding projects, and Trump repeatedly went after the state’s handling of devastating wildfires earlier this year. The president and California Gov. Gavin Newsom have also publicly feuded for years.

> Higher education in the state could be hit hard by Trump’s move. GOP Rep. Darrell Issa of California, who said he was unaware of the imminent grant cancellations, told CNN he recently met with university representatives who were concerned about the future of their funding.

## AI misdeeds

* Inside the AI Tool Used by DOGE to Review Veterans Affairs Contracts — ProPublica


[https://www.propublica.org/article/inside-ai-tool-doge-veterans-affairs-contracts-sahil-lavingia](https://www.propublica.org/article/inside-ai-tool-doge-veterans-affairs-contracts-sahil-lavingia)

(Interesting take down of the engineered AI prompts used for this particular smash-and-grab)

* NYTimes: Welcome to Campus. Here’s Your ChatGPT.

[https://www.nytimes.com/2025/06/07/technology/chatgpt-openai-colleges.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/07/technology/chatgpt-openai-colleges.html?smid=nytcore-ios-share&referringSource=articleShare)

> To spread chatbots on campuses, OpenAI is selling premium A.I. services to universities for faculty and student use. It is also running marketing campaigns aimed at getting students who have never used chatbots to try ChatGPT.

> OpenAI’s campaign is part of an escalating A.I. arms race among tech giants to win over universities and students with their chatbots. The company is following in the footsteps of rivals like Google and Microsoft that have for years pushed to get their computers and software into schools, and court students as future customers.

(Big tech's continued attempts to wrest control of education from the professoriate)

> OpenAI’s push to A.I.-ify college education amounts to a national experiment on millions of students. The use of these chatbots in schools is so new that their potential long-term educational benefits, and possible side effects, are not yet established.

> A few early studies have found that outsourcing tasks like research and writing to chatbots can diminish skills like critical thinking. And some critics argue that colleges going all-in on chatbots are glossing over issues like societal risks, A.I. labor exploitation and environmental costs.

* Chinese AI firms block features amid high-stakes university entrance exams


[https://www.washingtonpost.com/world/2025/06/10/china-exam-gaokao-ai-cheating-test/](https://www.washingtonpost.com/world/2025/06/10/china-exam-gaokao-ai-cheating-test/)

> As more than 13 million students filed into rooms across China to sit for the notoriously grueling, high-stakes gaokao college entrance exam, they already faced strict anti-cheating and real-time surveillance measures, including facial recognition technology, metal detectors, drones and cellphone-signal blockers. Vehicles transporting the test papers — classified as state secrets — are equipped with video surveillance. Copies of the test are stored in steel-reinforced rooms that can only be opened by three people, each wielding their own key. China made cheating on exams a criminal act in 2015 — punishable in some cases by prison sentences.

>  This year, AI companies joined in, adding a new layer to the ring of walls and moats around the exam.

> Chinese AI model DeepSeek did not allow users to upload photos of test papers during the same period....AI tool Kimi allowed photo recognition on Tuesday, but uploading failed when it detected a test exam or paper. Doubao, the AI app owned by TikTok’s parent company ByteDance, appeared to suspend the uploading of test paper photos or screenshots, though other photos worked fine.

> This year, some schools in China used real-time AI patrol and surveillance systems to check for suspicious behavior in the exam room: whispering, peeking, passing objects, answering early or using prohibited tools, Chinese state media outlets reported. It can detect the behavior during the exam and with a “post-exam intelligent search,” a Global Times article said.

## And just because it is fun

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
