# Jun 20

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

Thanks to MP, KB, VAC, ..., for sending along interesting things this week.

## Letters

(Thanks to MP for bringing these to my attention)

* Stand up for Science

[https://www.standupforscience.net/bethesda-declaration?utm_source=websitetakeaction&utm_campaign=bethesdadec](https://www.standupforscience.net/bethesda-declaration?utm_source=websitetakeaction&utm_campaign=bethesdadec)

* Open letter in support of Science

[https://www.standupforscience.net/open-letter-in-support-of-science](https://www.standupforscience.net/open-letter-in-support-of-science)

*  Call to Defend Federal Research Funding for CUNY and SUNY

[https://docs.google.com/forms/d/e/1FAIpQLSddGwakGE6Q2Jcg9_Wfv7oZhVK6YFNx5o7uCmW19Vz6rBp_Nw/viewform?pli=1](https://docs.google.com/forms/d/e/1FAIpQLSddGwakGE6Q2Jcg9_Wfv7oZhVK6YFNx5o7uCmW19Vz6rBp_Nw/viewform?pli=1)

* Fearing Trump, academics worldwide issue anti-fascist manifesto


[https://www.washingtonpost.com/world/2025/06/13/anti-fascist-manifesto-intellectuals-trump/](https://www.washingtonpost.com/world/2025/06/13/anti-fascist-manifesto-intellectuals-trump/)


> In the spring of 1925, a group of academics, researchers and writers in Italy published an open letter in multiple newspapers, hoping to ring alarm bells over the creeping authoritarianism of Benito Mussolini and his Fascist party. It called for “intrinsic goodness” and recognizing the value of “liberal systems and methods” over “violence and bullying and the suppression of freedom of the press.”

> But exactly a century later, a modern group of academics, researchers and writers around the world is giving it another go — fearing that the world is once again sleepwalking into dictatorship and violence. More than 400 scholars from dozens of countries, including at least 30 Nobel laureates, are reprising the 1925 Manifesto of the Anti-Fascist Intellectuals to warn that “the threat of fascism is back.”

[https://www.theguardian.com/commentisfree/2025/jun/13/nobel-laureates-fascism](https://www.theguardian.com/commentisfree/2025/jun/13/nobel-laureates-fascism)

> We call on all those who value democracy to act:

> Defend democratic, cultural and educational institutions. Call out abuses of democratic principles and human rights. Refuse pre-emptive compliance.

> Join collective actions, locally and internationally. Boycott and strike when possible. Make resistance impossible to ignore and costly to repress.

> Uphold facts and evidence. Foster critical thinking and engage with your communities on these grounds.

[https://stopreturnfascism.org/](https://stopreturnfascism.org/)


* AAUP - Tell Your Senators: Protect Higher Ed & Student Aid

[https://actionnetwork.org/letters/tell-your-senators-protect-higher-ed-student-aid](https://actionnetwork.org/letters/tell-your-senators-protect-higher-ed-student-aid)

Use this form to email to your senators telling them to protect our students and institutions from drastic cuts in student aid proposed by the Senate Committee on Health, Education, Labor, and Pensions (HELP) and in H.R. 1—The One Big Beautiful Bill Act. To make your letter more impactful, we urge you to add your hometown and place of work to the email before you send it.

(Thanks VAC)

## Protests

* NYTimes: To Protest Budget Cuts, Young Scientists Try Letters to the Editor

[https://www.nytimes.com/2025/06/16/science/science-budget-cuts-protest-letters.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/16/science/science-budget-cuts-protest-letters.html?smid=nytcore-ios-share&referringSource=articleShare)

> Hundreds of graduate students are writing to their hometown newspapers to defend their research, as the Trump administration drastically reduces science funding.


## Op eds

* NYTimes: Antisemitism Is an Urgent Problem. Too Many People Are Making Excuses.

[https://www.nytimes.com/2025/06/14/opinion/antisemitism-jewish-hate.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/14/opinion/antisemitism-jewish-hate.html?smid=nytcore-ios-share&referringSource=articleShare)


## How best to describe the times we are in

## Academic freedom

* Tulane Environmentalist Resigns Amid Research ‘Gag Order’

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/06/13/tulane-environmentalist-resigns-amid-research-gag](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/06/13/tulane-environmentalist-resigns-amid-research-gag)

> An environmental researcher at Tulane University resigned Wednesday after accusing campus officials, reportedly under pressure from Gov. Jeff Landry, of issuing a “gag order” that prevented her from publicly discussing her work, which focused on racial disparities in the petrochemical workforce.

> “Scholarly publications, not gag orders, are the currency of academia,” Kimberly Terrell, the now-former director of community engagement at Tulane’s Environmental Law Clinic, wrote in her resignation letter. “There is always room for informed debate. But Tulane leaders have chosen to abandon the principles of knowledge, education, and the greater good in pursuit of their own narrow agenda.”

> “It started with the pro-Palestinian activism on our campus and others across the country. It’s emboldened a lot of political leaders to feel they can make inroads by silencing faculty in other areas,” Michelle Lacey, a math professor and president of Tulane’s chapter of the American Association of University Professors, told Inside Higher Ed. “That was the catalyst for creating a climate where university administrators are very nervous, especially now as we see the government pulling funding for areas of research they don’t like.”

> Last summer, he [Governor Landry, Trump aligned[ enacted a law that allows him to directly appoint board chairs at the state’s public colleges and universities. And in November, following Trump’s election, Landry publicly called on officials at Louisiana State University to punish a law professor who allegedly made brief comments in class about students who voted for the president.



### Anti-woke/anti-DEI is simply racism

* What Is Replacing DEI? Racism.

[https://www.chronicle.com/article/what-is-replacing-dei-racism](https://www.chronicle.com/article/what-is-replacing-dei-racism)

(Thanks VAC)


(Uhh, Juneteenth celebrations from this administration speak volumes)

## Visas

* How many international students attend NY colleges? Here’s what to know

[https://www.democratandchronicle.com/story/news/2025/06/12/how-many-international-students-attend-ny-colleges-what-to-know/84050603007/](https://www.democratandchronicle.com/story/news/2025/06/12/how-many-international-students-attend-ny-colleges-what-to-know/84050603007/)



> Using the latest data available from Immigration and Customs Enforcement, USA TODAY found New York University had the most international students with F-1 visas in 2023 and Columbia University had the third-most.

(Thanks KB. There are around 7000 CUNY students on F1 visas, in this article we see, two campuses are listed.)

> Baruch College: 2,140
> The City University of New York — Graduate School and University Center: 1,004


* State Department pauses or delays interviews and approvals for student and exchange visitor visas

[https://www.epi.org/policywatch/state-department-pauses-interviews-for-student-and-exchange-visitor-visas-to-do-additional-vetting-of-social-media-accounts/](https://www.epi.org/policywatch/state-department-pauses-interviews-for-student-and-exchange-visitor-visas-to-do-additional-vetting-of-social-media-accounts/)

(Thanks KB)

> A State Department cable dated May 27, 2025, which is not public but has been reviewed by numerous media outlets, orders U.S. embassies and consulates abroad to pause all new interviews for foreign nationals who are applying for a nonimmigrant (i.e. temporary) visa to come to the United States in the visa categories of F-1 (for foreign students participating an academic program), J-1 (for participants in the State Department’s Exchange Visitor Program), and M-1 (for international students pursuing vocational or other non-academic studies). The ostensible reason offered is so that State Department officials can conduct additional vetting of visas applicants, by reviewing their social media accounts. According to reports, the cable reads: “Effective immediately, in preparation for an expansion of required social media screening and vetting, consular sections should not add any additional student or exchange visitor (F, M, and J) visa appointment capacity until further guidance is issued [in a separate, forthcoming telegram], which we anticipate in the coming days.”

* State Dept. restarts student visa interviews with tougher social media rules

[https://www.washingtonpost.com/national-security/2025/06/18/student-visas-social-media-vetting-state-department/](https://www.washingtonpost.com/national-security/2025/06/18/student-visas-social-media-vetting-state-department/)

> As staff members examine students’ profiles, the cable instructed, they must look to “identify applicants who bear hostile attitudes toward our citizens, culture, government, institutions, or founding principles; who advocate for, aid, or support designated foreign terrorists and other threats to U.S. national security; or who perpetrate unlawful antisemitic harassment or violence.”

> One State department official noted that the agency issued 446,000 student visas in 2023. “If everyone has to now have their social media scrubbed for derogatory information? Officers do not have that time.”

> The cable suggested that State Department officials should request that applicants make public and accessible all portions of their social media accounts and should penalize them if they refuse.

> If portions of accounts remain “set to ‘private’ or otherwise limited, you should treat the case as any other where an applicant fails to provide certain information on request,” the cable stated. It added, in a bolded sentence, “You must consider whether such failure reflects evasiveness or otherwise calls into question the applicant’s credibility.”

(Also)

[https://www.politico.com/news/2025/06/18/social-media-screening-student-visas-00413160](https://www.politico.com/news/2025/06/18/social-media-screening-student-visas-00413160)


(Also)

[https://www.nytimes.com/2025/06/18/us/politics/student-visa-applications.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/18/us/politics/student-visa-applications.html?smid=nytcore-ios-share&referringSource=articleShare)

* DOJ Targets In-State Tuition for Noncitizens in Kentucky as Texas Students Fight Back


[https://www.insidehighered.com/news/government/politics-elections/2025/06/20/after-texas-doj-targets-kentuckys-state-tuition](https://www.insidehighered.com/news/government/politics-elections/2025/06/20/after-texas-doj-targets-kentuckys-state-tuition)

> The Justice Department sued Kentucky politicians over in-state tuition benefits for undocumented students, just as Texas students and advocates are pushing back against a lawsuit that killed a similar state policy.

>  The department filed a complaint in U.S. District Court for the Eastern District of Kentucky on Tuesday challenging the in-state tuition policy for undocumented students. The lawsuit, which names Democratic governor Andy Beshear, Commissioner of Education Robbie Fletcher and the Kentucky Council on Postsecondary Education, takes issue with a policy that allows graduates of Kentucky high schools who live in the state, regardless of citizenship, to access in-state tuition benefits.


## Funding cuts

* How Universities Would Overhaul Research Funding

[https://www.insidehighered.com/news/government/science-research-policy/2025/06/18/university-leaders-weigh-changes-research](https://www.insidehighered.com/news/government/science-research-policy/2025/06/18/university-leaders-weigh-changes-research)

> Now, after just over six weeks of work, that group known as the Joint Associations Group is homing in on a plan to rework how the government funds research, and they want feedback from the university research community before they present a proposal to Congress and the Trump administration at the end of the month.

>“Unfortunately, something is going to change,” said Barbara Snyder, president of the Association of American Universities. “Either we will be part of it or it will be imposed upon us … Significant division in the research community is going to kill us.”

> Both versions of what JAG is calling the Fiscal Accountability in Research model, or FAIR, are geared toward offering more accountability and transparency about how federal research dollars are spent. JAG hopes that in the end, the new model will be simpler than the current one. They also want to nix terms like “indirect costs rate” and “overhead” for either essential research support or general research operations in an effort to underscore that the money goes toward the real costs of research.

> One model, which the group calls FAIR No. 1, would include costs related to managing the grant, general research operations and facilities as a fixed percentage of the total budget. The percentage would be based in part on the type of institution and research. This approach is designed to be simple and reasonable, according to the group’s presentation, but it’s more general, which makes it “difficult to account for the wide array of research frameworks that now exist.”

> The other model, FAIR No. 2, would more accurately reflect the actual costs of a project and make the structure for federal grants more like those from private foundations. Under this model, essential research support would be lumped into the project costs while funding for general research operations, such as payroll and procurement, would be a fixed percentage of the total budget. That change would likely increase the direct costs of the project.

* Research Grants Increasingly Require Compliance With Trump’s Orders. Here’s How Colleges Are Responding.

[https://www.chronicle.com/article/research-grants-increasingly-require-compliance-with-trumps-orders-heres-how-colleges-are-responding](https://www.chronicle.com/article/research-grants-increasingly-require-compliance-with-trumps-orders-heres-how-colleges-are-responding)

> Under the Trump administration, the conditions for accepting federal funding have become increasingly partisan. The Chronicle first reported in May that at least two notice-of-award letters from the National Institutes of Health, which are legal documents spelling out the terms of grants, mandated compliance with Trump’s executive order recognizing only two sexes, effectively excluding transgender people from U.S. policy.

> Now, according to scientists and colleges contacted by The Chronicle, an increasing number of grant letters — from the NIH and other agencies — require compliance with one or more of Trump’s executive orders and with civil-rights laws, which Trump has sought to reinterpret.

> In one striking example of the ever-changing environment, the NIH announced a policy in April that required grantees to attest that they don’t operate “illegal” diversity, equity, and inclusion programs or support boycotts of Israel when accepting federal funds. But over the past week, the policy was abruptly rescinded, then put back in place, then rescinded again without explanation.

> A federal judge announced a short-term win for scientists on Monday, ruling that Trump’s termination of hundreds of grants because they referenced DEI or LGBTQ issues was discriminatory, and ordering the government to restore the funding.

* How Senate Republicans Want to Hold Colleges Accountable

[https://www.insidehighered.com/news/government/student-aid-policy/2025/06/20/how-senate-republicans-want-hold-colleges-accountable](https://www.insidehighered.com/news/government/student-aid-policy/2025/06/20/how-senate-republicans-want-hold-colleges-accountable)

> The high chamber’s proposal, which ties a university’s access to federal loans to how much their students earn after graduation, is simpler and more productive than the House proposal, known as risk-sharing, which would require colleges to pay an annual penalty based on their students’ outstanding loan balances, they say.

> The Senate plan seems to be based on an existing regulation known as gainful employment, which uses students’ earnings and debt to measure whether for-profit and non-degree programs adequately prepare their students for the workforce. But Republicans who sponsored the bill and expanded its reach to all degree programs have been wary of drawing attention to the overlap, as lawmakers have avoided calling it anything like “gainful employment 2.0” or “gainful for all.”

> Republicans have historically opposed the Democratic policy, which was first put in place during the Obama administration, saying it unfairly targeted for-profit programs and that a free market would be the best way to regulate the quality of academic programs.

* Congressional Republicans Want to End Grad PLUS Loans. How Might It Affect Your Campus?

[https://www.chronicle.com/article/congressional-republicans-want-to-end-grad-plus-loans-how-might-it-affect-your-campus](https://www.chronicle.com/article/congressional-republicans-want-to-end-grad-plus-loans-how-might-it-affect-your-campus)

> Congressional Republicans appear set to effectively shut down the 20-year-old Grad PLUS federal student-loan program as House and Senate lawmakers seek passage of a sprawling set of budget cuts, tax adjustments, and policy changes — bundled together and branded by President Trump as the “One Big Beautiful Bill.”

>  would see the Grad PLUS loan program, which had been expected to lend out roughly $19 billion annually between 2026-34, phased out for new borrowers starting in the 2026-27 academic year. The program would eventually be mothballed for all borrowers starting in the 2029-30 academic year.

(The interactive table has some detail

|College | N   | Disbursement |
|:-------|:----|:-------------|
| CCNY   | 180 | 3.3M         |
| GC     | 193 | 2.6M         |
| Hunter | 114 | 1.7M         |
| Baruch |  79 | 1.6M         |

Brooklyn, John Jay, York, Lehman, Queens, CSI also impacted ~ 2M combined)

> But without access to Grad PLUS financing, said Suzanne Ortega, president of the Council of Graduate Schools, graduate-level education will either become unattainable for some students or “force them into high-cost private debt, exacerbating the student-debt crisis and existing work-force shortages in critical fields like teaching, law enforcement, public-health professions, and engineers.”



### NSF

* Trump is undermining U.S. science. Here’s why that’s dangerous.

[https://www.washingtonpost.com/opinions/2025/06/18/trump-science-attacks-internet/](https://www.washingtonpost.com/opinions/2025/06/18/trump-science-attacks-internet/)

> The evisceration of the National Science Foundation (NSF) — including wholesale firings, budget-slashing and arbitrary elimination of grants — is especially worrisome to those of us who understand the crucial role science has played in making America a great and powerful nation. Congress must act soon to halt this devastating attack.

> At its heart was a management ethos borrowed from successful wartime research: the idea that knowledgeable scientists could identify the most fruitful topics and the best ways to pursue them. T

> In the past, the NSF has usually enjoyed bipartisan support from both presidents and members of Congress. But the ravages currently being inflicted upon the agency may bring a truly golden era of American science to a halt. The February dismissal of 168 “probationary” NSF employees included career scientists newly arrived from academic positions to work as program managers familiar with the scientific disciplines they were to oversee. Though some have been reinstated by court order, the chilling uncertainty this ill-considered action instills in the NSF workforce and its grantees can seriously harm U.S. science.

> What’s worse, the 2026 fiscal year Trump budget calls for slashing $5 billion from the current $9 billion NSF budget. That would be the death knell of the storied agency as it has been known for decades

### NIH

* tracking site

[https://www.chronicle.com/article/tracking-trumps-higher-ed-agenda#research](https://www.chronicle.com/article/tracking-trumps-higher-ed-agenda#research)

* The Scientific Research Lost Amid the Trump Administration’s NIH Cuts — ProPublica


[https://projects.propublica.org/nih-cuts-research-lost-trump/](https://projects.propublica.org/nih-cuts-research-lost-trump/)

> The National Institutes of Health is responsible for more than 80% of the world’s grant investment in biomedical research. Its funding has sparked countless medical breakthroughs — on cancer, diabetes, strokes — and plays a fundamental role in the development of pharmaceutical drugs.


> The NIH has rarely revoked funding once it has been awarded. Out of the tens of thousands of grants overseen by the institution since 2012, it terminated fewer than five for violations of the agency’s terms and conditions.

> Then Donald Trump was reelected.

> Since his January inauguration, his administration has terminated more than 1,450 grants, withholding more than $750 million in funds; officials have said they are curbing wasteful spending and “unscientific” research.

> The mass cancellation of grants in response to political policy shifts has no precedent, former and current NIH officials told ProPublica. It threatens the stability of the institution and the scientific enterprise of the nation at large.

> To gain a deeper understanding of the toll, ProPublica reached out to more than 500 researchers, scientists and investigators whose grants were terminated. More than 150 responded to share their experiences, which reveal consequences that experts say run counter to scientific logic and even common sense.

(Well worth reading to gain a sense of scale of this sabotage)

* Trump’s NIH Axed Research Grants Despite Court Order — ProPublica


[https://www.propublica.org/article/trump-nih-cuts-transgender-research-grants](https://www.propublica.org/article/trump-nih-cuts-transgender-research-grants)


(And more details on sabotage at the NIH)

> Nearly two weeks after the court’s preliminary injunction was issued, the National Institutes of Health’s then-acting head, Dr. Matthew J. Memoli, drafted a memo that details how the agency, in response to Trump’s executive orders, cut funding for research grants that “promote or inculcate gender ideology.” An internal spreadsheet of terminated NIH grants also references “gender ideology” and lists the number associated with Trump’s executive order as the reason for the termination of more than a half dozen research grants. [Yet, "Lawyers for the federal government have repeatedly claimed in court filings that the administration has been complying with the order (stopping it from cutting funding related to gender identity and the provision of gender-affirming care in response to President Donald Trump’s executive orders)"]

> The Washington attorney general’s allegation that the Trump administration violated a court order comes as the country lurches toward a constitutional crisis amid accusations that the executive branch has defied or ignored court orders in several other cases.

> in depositions filed in the case last week, two NIH officials testified that DOGE itself gave directions in hundreds of grant terminations.


> The lawsuit offers an unprecedented view into the termination of more than 600 grants at the NIH over the past two months. Many of the canceled grants appear to have focused on subjects that the administration claims are unscientific or that the agency should no longer focus on under new priorities, such as gender identity, vaccine hesitancy and diversity, equity and inclusion. Grants related to research in China have also been cut, and climate change projects are under scrutiny.

> Mike Faulk, the deputy communications director for the Washington state attorney general’s office, told ProPublica in an email that the administration “appears to have used DOGE in this instance to keep career NIH officials in the dark about what was happening and why.” “While claiming to be transparent, DOGE has actively hidden its activities and its true motivations,” he said.

> “Their claim to have complied with the preliminary injunction is almost laughable,” said Faulk, the office’s deputy communications director. “The Trump administration is playing games with no apparent respect for the rule of law.”

> The executive order detailing DOGE’s responsibilities describes the cost-cutting team as advisers that consult agency heads on the termination of contracts and grants. No language in the orders gives the DOGE team members the authority to direct the cancellation of grants or contracts. However, the depositions portray Riley [former consultant for McKinsey & Co. and DOGE member] as giving directions on how to conduct the terminations.

> Jeremy Berg, who led the National Institute of General Medical Sciences at the NIH from 2003 to 2011, told ProPublica that the administration’s assessment of the institution was “not fair and not based on any substantial analysis or evidence,” and the proposed cuts “would be absolutely devastating to NIH and to biomedical research in the United States.”

* Judge Rejects Trump’s ‘Appalling’ NIH LGBTQ, Race Grant Cuts

[https://news.bloomberglaw.com/health-law-and-business/judge-clashes-with-trump-justice-department-over-nih-grant-cuts](https://news.bloomberglaw.com/health-law-and-business/judge-clashes-with-trump-justice-department-over-nih-grant-cuts)

(Thanks KB)

> “This represents racial discrimination and discrimination against America’s LGBTQ community. That’s what this is,” said Judge William G. Young of the US District Court for the District of Massachusetts. “I would be blind not to call it out. My duty is to call it out.”

(Also, from VAC)

[https://www.axios.com/local/boston/2025/06/16/nih-grants-ordered-restored](https://www.axios.com/local/boston/2025/06/16/nih-grants-ordered-restored)


(Also)

[https://www.nytimes.com/live/2025/06/16/us/trump-news?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/live/2025/06/16/us/trump-news?smid=nytcore-ios-share&referringSource=articleShare)


### DOD

Universities Sue, Judge Blocks DOD’s Indirect Costs Cap

[https://www.insidehighered.com/news/quick-takes/2025/06/20/universities-sue-judge-blocks-dods-indirect-costs-cap](https://www.insidehighered.com/news/quick-takes/2025/06/20/universities-sue-judge-blocks-dods-indirect-costs-cap)

> Johns Hopkins, Arizona State and Cornell Universities are among a coalition of 12 higher education institutions and three trade groups that filed a lawsuit against the Department of Defense on Monday over the agency’s plan to cap universities’ indirect research cost rates at 15 percent.

> On Tuesday, a federal judge in Boston issued a temporary restraining order, prohibiting the DOD from enacting the cap. A hearing in the case is set for July 2.

> For example, Johns Hopkins and the DOD currently have in place a negotiated indirect cost rate of 55 percent. In 2024 JHU received $32 million from the DOD to cover indirect costs, according to the lawsuit. If the DOD’s plan moves forward, however, the university would lose $22 million.

## Federal Agencies

### State actions

* Tennessee Lawsuit Puts HSIs’ Fate on the Line

[https://www.insidehighered.com/news/government/politics-elections/2025/06/13/tenn-lawsuit-puts-hispanic-servings-fate-line](https://www.insidehighered.com/news/government/politics-elections/2025/06/13/tenn-lawsuit-puts-hispanic-servings-fate-line)

> Two years after its Supreme Court victory against Harvard and UNC Chapel Hill, Students for Fair Admissions has a new target in its sights: Hispanic-serving institutions. On Wednesday, the advocacy group joined the state of Tennessee in suing the U.S. Department of Education, arguing that the criteria to become an HSI are unconstitutional and discriminatory. The move is distressing HSI advocates, who hoped to see the institutions left out of the political fray.

* Funding for Hispanic-Serving Institutions Is Discriminatory and Unconstitutional, Lawsuit Argues

[https://www.chronicle.com/article/funding-for-hispanic-serving-institution-is-discriminatory-unconstitutional-lawsuit-argues](https://www.chronicle.com/article/funding-for-hispanic-serving-institution-is-discriminatory-unconstitutional-lawsuit-argues)

(Thanks VAC)

* New state laws target job protections for college professors


[https://www.washingtonpost.com/education/2025/06/18/tenure-college-faculty-republican-challenges/](https://www.washingtonpost.com/education/2025/06/18/tenure-college-faculty-republican-challenges/)

[https://hechingerreport.org/special-reports/higher-education/](https://hechingerreport.org/special-reports/higher-education/)

> HONOLULU — The “gravy train.” That’s what a Hawaii state senator called the practice of awarding tenure to university research faculty when she proposed legislation in 2022 stripping this long-standing form of job protection from them.

> The bill got little notice at the time. Now, obscured by the turmoil of the many other challenges to higher education since the start of Donald Trump’s second presidential term, tenure has come under siege in states across the country.

> “It’s the flip side of the same assault,” said Randi Weingarten, president of the American Federation of Teachers, or AFT, which represents 400,000 faculty and other university and college employees. “Some of the assault is coming from taking away grants, and some of the assault is coming by taking away tenure.”

(But it doesn't seem to be driven by a newly appointed leader)

> “To me, it’s about the Senate wanting control over the university,” said Christian Fern, executive director of the University of Hawai‘i Professional Assembly, the faculty union.

(States mentioned: Hawaii, Nebraska, Ohio, Kentucky, Texas, Indiana, Arkansas, North Dakota, Kansas)

> “This level of attack couldn’t gain the kind of momentum it has without the declining public support for higher education,” Reuben [Harvard historian] said. “It couldn’t have happened to this magnitude before, because there was a general sense that higher education was good for society.”

## Institutional assaults

### Harvard

* NYTimes: Harvard Will Ask a Judge to Block Trump From Barring International Students

[https://www.nytimes.com/2025/06/16/us/harvard-international-students-lawsuit-injunction.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/16/us/harvard-international-students-lawsuit-injunction.html?smid=nytcore-ios-share&referringSource=articleShare)


> The hearing follows at least four different attempts by Trump administration officials to end or limit Harvard’s foreign enrollment. If they succeed, it could affect about 7,000 international scholars and potentially deliver a disabling blow to the campus’s finances, curriculum and identity.

> In their court filing, Harvard’s lawyers argued that broad language was necessary because the government had “committed to continuing — indeed to intensifying — its retaliatory campaign,” one that can “throw Harvard and its international community into turmoil.”

> The litigation, which is one of two cases Harvard has filed against the Trump administration, began last month when the Department of Homeland Security said it was revoking Harvard’s ability to host students under a system called the Student Exchange and Visitor Program.

> A lawyer for Harvard, Ian Gershengorn, accused the administration of resorting to “shenanigans” in its efforts to bar foreign students from Harvard.

> Harvard has said the actions aren’t grounded in real violations but instead are retaliation for its refusal to bend to the administration’s will.

* Judge Waits to Rule on Trump’s Effort to Bar Harvard Foreign Students

[https://www.insidehighered.com/news/government/politics-elections/2025/06/17/judge-delays-ruling-trump-ban-harvard-foreign](https://www.insidehighered.com/news/government/politics-elections/2025/06/17/judge-delays-ruling-trump-ban-harvard-foreign)

> In a hearing on Monday, a federal judge put off making a ruling on whether to continue blocking President Trump’s proclamation banning Harvard international students and researchers from entering the country. The judge, Allison Burroughs of the District Court for the District of Massachusetts, agreed to decide within a week and extended an order to temporarily halt the policy until then.

> The hearing came after Harvard swiftly filed a legal challenge to Trump’s directive in early June, a day after it was issued. Burroughs quickly granted a temporary restraining order and is now weighing a longer-lasting injunction.


### Columbia

* NYTimes: Negotiation or Capitulation? How Columbia Got Off Trump’s Hot Seat.

[https://www.nytimes.com/2025/06/16/nyregion/columbia-middle-east-studies-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/16/nyregion/columbia-middle-east-studies-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> While many in the academic world have accused Columbia of caving to Mr. Trump’s pressure, the university’s strategy — so far — has limited the bleeding, even as Harvard has absorbed cut after cut, stretching into billions of dollars. While opponents of the Trump administration’s crackdown have lauded Harvard for standing its ground, it is far from clear which school will be better off in the long run. And the question remains whether Columbia’s path can offer a road map for other universities attacked by the president.

> Still, the federal Department of Education threatened Columbia’s accreditation in early June, saying that in its eyes, the school was no longer meeting the standards necessary for the key credential, alleging it had “acted with deliberate indifference” toward the harassment of Jewish students.

> “There is a basic principle of academic freedom that is under attack, but I still believe in it,” he said. “And I think everybody in this department believes in it. And I think the students we teach believe in it.”

* Federal Judge Dismisses AAUP Lawsuit Challenging Columbia Grant Freezes

[https://www.insidehighered.com/news/quick-takes/2025/06/17/judge-dismisses-lawsuit-over-columbia-grant-freezes](https://www.insidehighered.com/news/quick-takes/2025/06/17/judge-dismisses-lawsuit-over-columbia-grant-freezes)

> Judge Mary Kay Vyskocil of the Southern District of New York, however, ruled that the unions had no standing to file the lawsuit in the first place—only the university could do that, she said.

### Others

* The Trump administration froze Northwestern’s research funding. It hasn’t offered the school a way to get it back.


[https://www.wsj.com/us-news/education/northwestern-funding-freeze-trump-85d49da2?st=fGDDU3&reflink=article_gmail_share](https://www.wsj.com/us-news/education/northwestern-funding-freeze-trump-85d49da2?st=fGDDU3&reflink=article_gmail_share)

> Through the spring, Northwestern used university money to pay bills previously covered by NIH grants, spending tens of millions of dollars monthly to keep labs and trials running without a break. Researchers and administrators now worry this stopgap can’t last.

> “The university is totally keeping us on life support,” said Dr. Daniela Matei, a Northwestern oncologist. “The big question is for how long they can do this.”

> The sudden collapse of the once-symbiotic relationship between the federal government and higher education is torpedoing a half-century-old university business model and upending how science is done.

> It’s a complete turnaround for today’s university researchers, for whom federal funding—from NIH, National Science Foundation, and other agencies—has never been in question. Billions of dollars have flowed annually to universities through competitive grants, funding basic research that can lead to cutting-edge medicine and technological innovations.

> At places like Harvard and Columbia, funding cuts or freezes have come with lists of demands spanning changes to admissions and faculty hiring.

> At others, like Northwestern, the path to restoration is less clear. In April, a Trump administration official told media that $790 million in federal funds to the Illinois university would be frozen, but that number has never been detailed or communicated directly to school officials, a school spokesman said. Nor has Trump told the university what they can do to get the money returned, the spokesman said, though the school’s president has met with Trump’s education secretary to discuss the situation on campus.

> University officials say bills to NIH have simply gone unpaid. NIH grant officers in April were told not to communicate with Northwestern and other affected universities about the freeze, according to an email viewed by The Wall Street Journal. Northwestern researchers have had grants terminated or frozen from multiple agencies, the university said.

* Facing Research Cuts, Officials at U. of Iowa Spoke of a ‘Limited Ability to Publicly Fight This’

[https://www.chronicle.com/article/facing-research-cuts-officials-at-u-of-iowa-spoke-of-a-limited-ability-to-publicly-fight-this](https://www.chronicle.com/article/facing-research-cuts-officials-at-u-of-iowa-spoke-of-a-limited-ability-to-publicly-fight-this)

> Asked by a faculty member what he and his peers could do to help, the University of Iowa’s interim vice president for research suggested only “acting as a private citizen to call our legislators and tell them what a bad idea this is (from your own phone or using your own email).” The campus’s location in a solidly red state hindered it from fighting the policy change, Lois J. Geist seemed to imply in her reply. “Being located where we are we have limited ability to publicly fight this as faculty or as an institution.”



## Blowback

* Business Leaders Call Trump Attacks on Universities a Competitive Threat


[https://www.wsj.com/livecoverage/fed-meeting-interest-rates-stock-market-06-18-2025/card/business-leaders-call-trump-attacks-on-universities-a-competitive-threat-hphDJbcZLTsaa6Bmeqwg](https://www.wsj.com/livecoverage/fed-meeting-interest-rates-stock-market-06-18-2025/card/business-leaders-call-trump-attacks-on-universities-a-competitive-threat-hphDJbcZLTsaa6Bmeqwg)


* NYTimes: Tuition Increases and Layoffs Are Coming to a Broad Set of Universities

[https://www.nytimes.com/2025/06/20/us/tuition-hikes-layoffs-universities.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/06/20/us/tuition-hikes-layoffs-universities.html?smid=nytcore-ios-share&referringSource=articleShare)


(This is the big fear being realized elsewhere)

> Public universities in the Midwest are raising prices for out-of-state students...

> Cornell and Duke are among the colleges weighing layoffs. The University of Minnesota is cutting hundreds of jobs,...

> Students and employees from coast to coast are poised to feel the squeeze. Although the exact consequences will vary by school, administrators are warning that many students may have to pay more, professors may lose their jobs, programs could vanish and support services could shrink.

> The Trump administration’s efforts to reduce research funding are siphoning cash from many campuses, sometimes by hundreds of millions of dollars. But that is just one factor contributing to higher education’s financial crunch. Colleges, like businesses and households, are facing greater costs for wages, supplies, utilities and other expenses.

> In Minnesota, students are set to pay more for less. ... Tuition at the Twin Cities campus will rise by at least 6.5 percent. But the university is also pursuing cuts of 7 percent.

(See attempts to soften here:

[https://www.chronicle.com/article/u-of-minnesota-tries-to-soften-the-blow-of-tuition-hikes-budget-cuts-with-faculty-benefits](https://www.chronicle.com/article/u-of-minnesota-tries-to-soften-the-blow-of-tuition-hikes-budget-cuts-with-faculty-benefits)
)

> To manage the financial pressures, school leaders said they “anticipate involuntary reductions in head count.”

> But Dr. Mitchell, the American Council on Education president, and a former president of Occidental College, emphasized the range of schools that were facing financial headwinds.

> “This isn’t just the Ivies, and this just isn’t the result of headline freezes on big research projects,” he said. “This reflects more uncertainty in the basic economy.”

## Tracking projects

* Tracking Trump’s Higher-Ed Agenda

[https://www.chronicle.com/article/tracking-trumps-higher-ed-agenda](https://www.chronicle.com/article/tracking-trumps-higher-ed-agenda)

(VAC shared)

## AI misdeeds

* The Handwriting Revolution

[https://www.insidehighered.com/news/faculty-issues/curriculum/2025/06/17/amid-ai-plagiarism-more-professors-turn-handwritten-work](https://www.insidehighered.com/news/faculty-issues/curriculum/2025/06/17/amid-ai-plagiarism-more-professors-turn-handwritten-work)

> Five semesters after ChatGPT changed education forever, some professors are taking their classes back to the pre-internet era.

> So now, Ryckman is switching things up. Starting next semester, she’s planning to have her students write their responses in class to deter the use of AI—and she’s even considering requiring them to write the answers out by hand.

* Your Brain on ChatGPT: Accumulation of Cognitive Debt when Using an AI Assistant for Essay Writing Task

[https://arxiv.org/pdf/2506.08872v1](https://arxiv.org/pdf/2506.08872v1)

> With today's wide adoption of LLM products like ChatGPT from OpenAI, humans and businesses engage and use LLMs on a daily basis. Like any other tool, it carries its own set of advantages and limitations. This study focuses on finding out the cognitive cost of using an LLM in the educational context of writing an essay.

> As the educational impact of LLM use only begins to settle with the general population, in this study we demonstrate the pressing matter of a likely decrease in learning skills based on the results of our study. The use of LLM had a measurable impact on participants, and while the benefits were initially apparent, as we demonstrated over the course of 4 months, the LLM group's participants performed worse than their counterparts in the Brain-only group at all levels: neural, linguistic, scoring.

* What Will Be Left of Higher Ed in Four Years?

[https://www.chronicle.com/article/what-will-be-left-of-higher-ed-in-four-years](https://www.chronicle.com/article/what-will-be-left-of-higher-ed-in-four-years)

> A recent report from the consulting firm Deloitte confirms what everyone working in higher education already knows: Donald Trump “brings a layer of complexity to questions of financial sustainability for colleges and universities.” The administration’s dizzying range of punitive measures for academe comes at an inconvenient time: Our institutions are already grappling with diminished state support and a looming demographic cliff.

> Research universities face the greatest financial pressure. Grant cancellations and planned cuts to the National Science Foundation and National Institutes of Health are creating enormous budgetary holes: The budgets for graduate programs and scientific-research staffing were developed on the assumption that federal funding was a constant.

> In red states like Florida, Indiana, and Texas, Trump-supporting Legislatures are also working to bust up faculty and administrative autonomy as a condition of public funding. The administration’s cultural agenda for higher ed is likely to be advanced most fully in states where MAGA-friendly legislatures have near-total control. This doesn’t mean blue-state public research universities are off the hook. Data shows that state financial support for higher ed has been up over the past couple of years, but we might have reached high tide. Ebbing state funding would pair dangerously with cuts to federal research.

> Regional Publics and Community Colleges

> At first glance these institutions appear to be in an enviable position: They don’t rely heavily on federal research funding, they don’t have big endowments to tax, they don’t enroll lots of international students, and they tend to fly below the political radar. Domestic undergraduate enrollment is unlikely to collapse, and a looming economic downturn could even cause an uptick in demand for these institutions since people look to increase their skills and retrain during recessions. Still, the major financial-aid reform provisions tucked away in the “Big, Beautiful” reconciliation bill recently passed by the House will clearly affect these institutions if enacted, though in mixed ways. For community colleges, their lower tuition prices, shorter program duration, and a vocational orientation might yield comparative advantages in a world with diminished federal student aid. Risk-sharing provisions that put campuses on the hook for portions of unpaid student debt might harm minority-serving institutions and campuses that serve low-income and other students with historically higher rates of loan default. Requiring full-time enrollment for Pell Grant eligibility, as proposed in the House bill, would harm these institutions too. The Senate seems less excited about the risk-sharing and full-time Pell provisions, but the financial-aid outlook remains murky.

> Regional universities and community colleges also face enrollment risks. Pennsylvania State University plans to shutter several regional campuses, and federal pressure on research universities will have knock-on effects within state university systems. Looking to secure their own budgets, research universities might employ aggressive tactics to lure students otherwise headed to regional campuses.

> Rather than forming partnerships with the federal government, colleges will now have to endure the headwinds created by federal policy and, in some cases, engage in direct confrontation with the administration. I do not believe Trump will be able to destroy American higher education, but his administration will try, and the sector will suffer. Research footprints will shrink, the number of programs and activities on offer will be reduced, and the workloads of already-overextended faculty and staff will increase. Senior administrators can’t say so, but in the next few years colleges and universities will become diminished versions of themselves. Those of us who teach or work in higher ed will watch our institutions decline.

> Campuses will look for revenue to replace federal dollars. Public research universities will increase their enrollments, often at the expense of their regional counterparts. Our wealthiest colleges may quietly roll back their need-blind admissions policies. The steady trickle of emails from university communications announcing exciting new cancer research efforts and new science facilities will slow. Departmental budgets will be slashed to the point where faculty concern is less for vanishing tenure lines than for the survival of the department itself. Teaching course loads will grow, library operational hours will shrink, and students, stung by loan restrictions and red tape, will increasingly rush from class to part-time jobs. In short, the sector will be smaller, poorer, and capable of doing fewer things.



## Off topic


* New Data Shows Attendance Fosters Student Success

[https://www.insidehighered.com/news/student-success/academic-life/2025/06/13/data-shows-attendance-improves-student-success](https://www.insidehighered.com/news/student-success/academic-life/2025/06/13/data-shows-attendance-improves-student-success)

(Some headlines write themselves)

> Who’s missing class? It’s not uncommon for a student to miss class for illness or an outside conflict, but higher rates of absence among college students in recent years are giving professors pause.

> More than 30 percent of students who attended community college in person skipped class sometimes in the past year, a 2023 study found; 4 percent said they skipped class often or very often.



## And just because it is fun

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
