# Mar 21
Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week. Sadly, there is too much to track faithfully.


For a great roundup of other actions taken, this opinion piece by Dana Millbank is recommended: [https://wapo.st/4hwKarw](https://wapo.st/4hwKarw).



## Academic Freedom


* Academic freedom statements issued after Governor Hochul demanded the removal of a job ad at Hunter College:

[https://www.dropbox.com/scl/fo/my5g55jprx5o64r4vzus0/AO9WLNUUIorJRhgTO1SupgY?rlkey=zvsqtp7ev781y4rqqjti8xaho&dl=0](https://www.dropbox.com/scl/fo/my5g55jprx5o64r4vzus0/AO9WLNUUIorJRhgTO1SupgY?rlkey=zvsqtp7ev781y4rqqjti8xaho&dl=0)

(Shared by EI)

Recent activity includes a statement by the faculty senates of Guttman, Medger Evers, the College of Staten Island, and Hostos.


* Columbia AAUP Urges University to Reject Trump’s Demands

[https://www.insidehighered.com/news/quick-takes/2025/03/19/columbia-aaup-urges-university-reject-trumps-demands](https://www.insidehighered.com/news/quick-takes/2025/03/19/columbia-aaup-urges-university-reject-trumps-demands)

> “Compliance would make Columbia complicit in its own destruction, stripping shared control of academic and student affairs from the faculty and administration and replacing the deliberative practices and structures of the university with peremptory fiats from outside the institution,” the AAUP chapter said in a statement Tuesday. “We see no evidence that compliance would assuage the hostility of the White House.”

* The Cost of the Government’s Attack on Columbia (Princeton President)


[https://www.theatlantic.com/ideas/archive/2025/03/columbia-academic-freedom/682088/](https://www.theatlantic.com/ideas/archive/2025/03/columbia-academic-freedom/682088/)

> The Trump administration’s recent attack on Columbia University puts all of that [best collection of research universities] at risk, presenting the greatest threat to American universities since the Red Scare of the 1950s. Every American should be concerned.

> The second turning point [first was development of academic freedom] came during World War II, when Vannevar Bush, the director of the Office of Scientific Research and Development, created the modern partnership between the federal government and the country’s research universities. Bush recognized that by sponsoring research at universities, the United States could lead the world in discoveries and innovations. Over time, American universities became responsible for a large portion of the government’s scientific programs, accepting tens of billions of dollars a year to perform research that would make the country stronger and improve the lives of its citizens.

> Nobody should suppose that this will stop at Columbia or with the specific academic programs targeted by the government’s letter.

* Columbia nearing agreement to give trump what he wants

[https://www.wsj.com/us-news/education/columbia-is-nearing-agreement-to-give-trump-what-he-wants-14315bb3?st=HNVvxe&reflink=article_copyURL_share](https://www.wsj.com/us-news/education/columbia-is-nearing-agreement-to-give-trump-what-he-wants-14315bb3?st=HNVvxe&reflink=article_copyURL_share)

> Discussions on the board of trustees are still fluid—with sticking points—and could turn in a different direction before Thursday.

> Agreement to the demands doesn’t guarantee the federal funds will come back. In a letter last week, the Trump administration said meeting its nine requests was a “precondition for formal negotiations.”

* Plan to strip U Penn of 175M in funding

[https://www.nytimes.com/2025/03/19/us/politics/trump-to-pause-175-million-for-university-of-pennsylvania-over-transgender-policy.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/03/19/us/politics/trump-to-pause-175-million-for-university-of-pennsylvania-over-transgender-policy.html?smid=nytcore-ios-share&referringSource=articleShare)


* Academic Freedom Index: ‘serious concern’ for US universities (Paywall; Thanks BE)

[https://www.timeshighereducation.com/news/academic-freedom-index-serious-concern-us-universities](https://www.timeshighereducation.com/news/academic-freedom-index-serious-concern-us-universities)

* Congress Eyes More Control Over Colleges

[https://www.insidehighered.com/news/government/politics-elections/2025/03/21/congress-eying-more-control-over-colleges](https://www.insidehighered.com/news/government/politics-elections/2025/03/21/congress-eying-more-control-over-colleges)

> they’ve introduced bills to crack down on immigration and foreign influence by threatening student visas and restricting international donations; to hamper flexibility for borrowers by capping student loan amounts; and to suppress “liberal ideologies,” by establishing penalties for pro-Palestinian protests. Republicans are also escalating their ongoing attacks on wealthy colleges with proposals to significantly increase the tax on university endowments.

> And all of that doesn’t even take into account the possibility that Republicans could revive parts of the College Cost Reduction Act—a comprehensive piece of legislation introduced last Congress to overhaul higher education. Although the bill itself has yet to be introduced, many of its provisions—such as requiring colleges to pay back a portion of students’ unpaid loans—could be part of the forthcoming reconciliation bill, a top priority for Congressional Republicans this spring that could mean billions in cuts to higher education.

* Northwestern Journalism Professor Says Pro-Palestinian Activism Cost Him Tenure

[https://www.insidehighered.com/news/quick-takes/2025/03/21/pro-palestinian-journalism-professor-denied-tenure](https://www.insidehighered.com/news/quick-takes/2025/03/21/pro-palestinian-journalism-professor-denied-tenure)

* "Shared Governance Is Crumbling"

[https://www.chronicle.com/article/shared-governance-is-crumbling](https://www.chronicle.com/article/shared-governance-is-crumbling)

> Academic freedom is about the freedom to choose: the freedom to research this problem and not that one, to consider or advance one argument in the classroom and to criticize another. But freedom of choice only means something if the choices themselves are meaningful. Part of how colleges and universities make sure faculty members’ choices have meaning is through shared governance. And shared governance is under attack.

> As part of the ongoing legislative attack on academic freedom and campus free speech, state-level proposals to alter university governance and remove faculty from decision-making have bubbled up across the country.


##  Funding

* CUNY Programming cut -- a private funder (Thanks MP)

[https://www.thecity.nyc/newsletter/private-funder-axes-cuny-diversity-initiative/](https://www.thecity.nyc/newsletter/private-funder-axes-cuny-diversity-initiative/)

> The country’s largest private funder of biomedical research has cut its funding for a program at Queens College that had focused on making science, technology, engineering and mathematics (STEM) education more inclusive and engaging for students of diverse backgrounds, the college confirmed to THE CITY.

> The Inclusive Excellence initiative, launched at the Flushing-based CUNY college in 2022 with funding from the Howard Hughes Medical Institute (HHMI), ended abruptly last month when the Institute cut short what was supposed to be a $505,000, six-year grant running through 2028.

> Byrd hoped that because the program wasn’t funded by the federal government, but privately, that it would continue on. An HHMI spokesperson declined to provide an explanation for why they pulled the plug.


* "The Authoritarian Endgame on Higher Education"

[https://www.nytimes.com/2025/03/15/opinion/trump-research-cuts.html?unlocked_article_code=1.4E4.keqa.qHwBu9NLKbAp&smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/03/15/opinion/trump-research-cuts.html?unlocked_article_code=1.4E4.keqa.qHwBu9NLKbAp&smid=nytcore-ios-share&referringSource=articleShare)


AKA, why would one want to kill the golden goose of Higher Ed.


Also, CUNY faculty member amongst a trio on "A Really Easy Mark for Trump: Three Columnists on the Threats to Elite Colleges":

[https://www.nytimes.com/2025/03/15/opinion/trump-research-cuts.html?unlocked_article_code=1.4E4.keqa.qHwBu9NLKbAp&smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/03/15/opinion/trump-research-cuts.html?unlocked_article_code=1.4E4.keqa.qHwBu9NLKbAp&smid=nytcore-ios-share&referringSource=articleShare)

> Better to fight like men than die like cowards, or something like that

> As I wrote above, this is a campaign of destruction. A Russian scholar I know wrote recently that he thought that Trump 2.0 would be like the Chinese Cultural Revolution, but it’s turning out to be more like the Russian Civil War — just utter devastation, the effects of which will be felt for generations.

> I think that university presidents need to gather together their administrators, faculty members and students — don’t forget the students! — and remind them of these values and call on them to unite to affirm them. This is a very hard thing to do while under attack, to get out of a defensive crouch and try to stand up and lead, but it could point the way forward, and not just for universities.

* Demands on Columbia to restore funding "Reflect Assault on Higher Ed"

[https://www.insidehighered.com/news/government/politics-elections/2025/03/14/trump-escalates-attack-columbia-his-latest-demands](https://www.insidehighered.com/news/government/politics-elections/2025/03/14/trump-escalates-attack-columbia-his-latest-demands)


These include: overhaul its discipline process, ban masks, expel some students, put an academic department under review, give its campus security "full law enforcement authority" and reform its admissions practices.

* Impact of funding cuts at Columbia

[https://www.insidehighered.com/news/faculty-issues/research/2025/03/13/trumps-columbia-cuts-start-hitting-postdocs-professors](https://www.insidehighered.com/news/faculty-issues/research/2025/03/13/trumps-columbia-cuts-start-hitting-postdocs-professors)

* Impact on hiring due to uncertainty on federal funding

[https://www.insidehighered.com/news/business/cost-cutting/2025/03/14/more-colleges-freeze-hiring-amid-federal-funding-uncertainty](https://www.insidehighered.com/news/business/cost-cutting/2025/03/14/more-colleges-freeze-hiring-amid-federal-funding-uncertainty)


* NYU Adminstration letter to faculty

(select excerpts; thanks KB)

> Based on recent federal actions, we’ve identified a number of financial risk areas for the University ranging from federal cuts to research funding to tariffs, as well as a range of other proposals that could affect our overall budget. We don’t yet know whether, when, or to what extent these or other measures may be enacted. In the meantime, we continue to vigorously advocate for robust federal support of higher education. Given the scale of potential outcomes, however, we need to address risks sooner than later.

> We are implementing an administrative hiring freeze effective immediately. Th

> We anticipate that salary increases for faculty and administrative staff will be lower than they have been in recent years.

> We are asking schools and units to prepare contingency plans for more cuts at several levels, so we can respond nimbly should additional budget adjustments be required.

> We do not want in any way to minimize the difficulties facing us, but neither will we embrace hopelessness. NYU—and its faculty, students, administrators, and staff—have navigated arduous moments before in our nearly 200-year history while preserving what is important, fulfilling our mission, supporting our community, sustaining our academic trajectory, and being good stewards of the University’s resources. We will do so again now.


## Freedom of Expression

* The Culture War Is No Longer Just a Culture War

[https://www.nytimes.com/2025/03/16/opinion/trump-khalil-columbia-speech.html](https://www.nytimes.com/2025/03/16/opinion/trump-khalil-columbia-speech.html)

> In other words, universities possess a double obligation — to protect students and faculty and staff members from discrimination and harassment, while also protecting free expression on campus. It’s not an easy task.

> federal statutes and regulations permit termination of federal financial assistance only when “compliance cannot be secured by voluntary means” and when “there has been an express finding on the record, after opportunity for hearing, of a failure to comply.”

> Columbia has become Patient Zero in an outbreak of censorship and repression. And unless it’s stopped there, expect more universities to yield to Trump’s control. Expect political repression to spread far beyond the borders of the university.

* "The End of the University as We Know It"

[https://www.nytimes.com/2025/03/16/opinion/university-defunding-trump-rufo.html](https://www.nytimes.com/2025/03/16/opinion/university-defunding-trump-rufo.html)

> The result, if all goes through, will be nothing less than the permanent diminishment of research universities and an upheaval of the free speech principles at the core of the country.



## Diversity, equity, and inclusion

* Appeals Court Overturns Block on Parts of Trump’s DEI Orders

[https://www.insidehighered.com/news/quick-takes/2025/03/17/appeals-court-overturns-block-parts-trumps-dei-orders](https://www.insidehighered.com/news/quick-takes/2025/03/17/appeals-court-overturns-block-parts-trumps-dei-orders)

> Ahead of the Fourth Circuit’s ruling, the plaintiffs who sued the Trump administration over the orders, including the American Association of University Professors and the National Association of Diversity Officers in Higher Education, told the district judge that officials weren’t complying with the injunction.


## DOE/OCR

* "Education Department Investigates Dozens of Colleges for Discrimination"

[https://www.insidehighered.com/news/diversity/race-ethnicity/2025/03/15/education-department-accuses-51-colleges-discrimination](https://www.insidehighered.com/news/diversity/race-ethnicity/2025/03/15/education-department-accuses-51-colleges-discrimination)

Perhaps due to support of the *PhD Project*

* States sue to block DOE layoffs

[https://www.insidehighered.com/news/quick-takes/2025/03/14/states-file-lawsuit-challenging-education-department-cuts](https://www.insidehighered.com/news/quick-takes/2025/03/14/states-file-lawsuit-challenging-education-department-cuts)

* Is Title VI the New Title IX?

[https://www-chronicle-com.csi.ezproxy.cuny.edu/article/is-title-vi-the-new-title-ix](https://www-chronicle-com.csi.ezproxy.cuny.edu/article/is-title-vi-the-new-title-ix)

Mentions complaints about pace of investigation process at Baruch

(CUNY had voluntary agreements for both titles.)

* Is this the end of the Department of Education?

[https://www.insidehighered.com/news/government/politics-elections/2025/03/19/trump-signs-order-break-education-department](https://www.insidehighered.com/news/government/politics-elections/2025/03/19/trump-signs-order-break-education-department)

> President Donald Trump signed the long-awaited executive order Thursday directing Education Secretary Linda McMahon to close down her department “to the maximum extent appropriate and permitted by law.”

> The order won’t result in the immediate closure of the 45-year-old agency; only Congress can get rid of the department.



### Dear Colleague

* Trump is setting the US on a path to educational authoritarianism (thanks EI)

[https://www.theguardian.com/commentisfree/2025/mar/17/trump-us-path-educational-authoritarianism](https://www.theguardian.com/commentisfree/2025/mar/17/trump-us-path-educational-authoritarianism)

> The most straightforward way to read the letter and the guidelines is as defining “school-on-student harassment” as including Black history. The letter treats teaching large swaths of Black and Indigenous history as akin to a white professor consistently referring to all of their Black students with a terrible racial slur.

## Students

* Georgetown University graduate student detained by immigration authorities

[https://www.nbcnews.com/news/us-news/georgetown-university-graduate-student-detained-immigration-authoritie-rcna197206](https://www.nbcnews.com/news/us-news/georgetown-university-graduate-student-detained-immigration-authoritie-rcna197206)

> Masked agents arrested the student, Badar Khan Suri, outside his home in Arlington, Virginia, on Monday night, attorney Hassan Ahmad said.

* Here’s a resource that specifically lists those actions that impact colleges and universities work with international students, scholars, and faculty. (Thanks SF)

[https://www.nafsa.org/executive-and-regulatory-actions-trump2admin](https://www.nafsa.org/executive-and-regulatory-actions-trump2admin)

## Tell me why

* Why might higher education be under

[https://www.nytimes.com/2025/03/18/opinion/andreessen-musk-trump-silicon-valley.html?unlocked_article_code=1.404.W7Cu.Mm09erVCtF7P&smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/03/18/opinion/andreessen-musk-trump-silicon-valley.html?unlocked_article_code=1.404.W7Cu.Mm09erVCtF7P&smid=nytcore-ios-share&referringSource=articleShare)

Thomas Edsall quotes Marc Andreessen

> no way to fix American higher education without replacement, and there is no way to replace them without letting them fail. And in a sense, this is the most obvious conclusion of all time. What happens in the business world when a company does a bad job? It fails and another company takes its place. That’s how you get progress. Below this is the process of evolution.

He goes on to quote Gil Duran on "tech oligarchs"

> are an existential threat to democracy. Look at the news. It makes no sense that a presidential administration would seek to crash the economy while allowing an unelected foreign-born billionaire to rip apart the government. This goes against every rule in politics. Trump’s poll numbers are sinking yet he’s taking no steps to correct the course. This is the logic of a suicide bomber.

* Education is a right (By Maya Wiley)

[https://msmagazine.com/2025/03/19/education-cuts-trump-project-2025-public-schools/](https://msmagazine.com/2025/03/19/education-cuts-trump-project-2025-public-schools/)

> The Trump administration’s war on public education is a war on our kids.

> Trump’s backing comes from a minority of radical ideologues who want a very different America—one that is significantly less diverse, less rich in rights, more indoctrinated to their extremist version of Christianity, steeped in a history of white-ethno-Christian nationalism. The authors want an unraveling of a system that has been partially, though not completely, transformed by the civil rights movement. The end game is clear: Charter schools, religious schools and private schools will benefit from a much greater share of public education dollars with less accountability. This

----

If you have stories you would like me to include in anticipated future digests, please send along via an email to me directly (john.verzani@csi.cuny.edu).
