# Mar 14
Dear UFS Senators and FGLs,

I thought it might be worthwhile to attempt cataloging among the myriad federal activities, those that will have an impact on Higher Education in general and CUNY in specific. Given the pace of news cycles, this is likely to be an every Friday summary.

## Academic Freedom

* Guidance issued by NY State AG Letitia James, and 13 other Attorneys General  including, but not limited to, threats to DEI related programs and funding:

[https://ag.ny.gov/press-release/2025/attorney-general-james-issues-diversity-equity-inclusion-and-accessibility](https://ag.ny.gov/press-release/2025/attorney-general-james-issues-diversity-equity-inclusion-and-accessibility)

(Thanks EI for sharing with the FGLs)

The Office of General Counsel has a presentation the UFS will try to schedule. Hopefully, we will have more to say after Tuesday.

* More responses to the Governor Hochul action re Hunter College: York, LGCC, Brooklyn College. [Links requested]. This is in addition to responses previously recorded including that of the UFS Executive Committee and Academic Freedom Committee Chairs, the PSC, SUNY Fredonia, AAUP, MESA; and articles in the New Republic and elsewhere


## Funding removal

* White House cancels 400M in grants and contracts to Columbia (NIH funding was 250M of this)

[https://www.nytimes.com/2025/03/07/nyregion/trump-administration-columbia-grants-cancelled-antisemitism.html?unlocked_article_code=1.3k4.HrQr.PMbCenBH1u9x&smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/03/07/nyregion/trump-administration-columbia-grants-cancelled-antisemitism.html?unlocked_article_code=1.3k4.HrQr.PMbCenBH1u9x&smid=nytcore-ios-share&referringSource=articleShare)

* 800M of JHU funding stripped

[https://www.cbsnews.com/baltimore/news/johns-hopkins-university-antisemitism-claims-funding-cuts-maryland/#:~:text=JHU%20funding%20cuts&text=In%20a%20letter%2C%20Daniels%20said,%2C%20Jhpiego%2C%20had%20been%20terminated.](https://www.cbsnews.com/baltimore/news/johns-hopkins-university-antisemitism-claims-funding-cuts-maryland/#:~:text=JHU%20funding%20cuts&text=In%20a%20letter%2C%20Daniels%20said,%2C%20Jhpiego%2C%20had%20been%20terminated.)

Related: Johns Hopkins laying off more than 2,000 workers after dramatic cut in USAID funding

[https://www.cnn.com/2025/03/13/politics/johns-hopkins-layoffs-usaid-funding/index.html](https://www.cnn.com/2025/03/13/politics/johns-hopkins-layoffs-usaid-funding/index.html)

* 30M of University or Maine funding stripped in effort to punish Maine's governor

[https://www.nbcnews.com/nbc-out/out-politics-and-policy/usda-suspends-maine-university-funding-trump-row-transgender-athletes-rcna196011](https://www.nbcnews.com/nbc-out/out-politics-and-policy/usda-suspends-maine-university-funding-trump-row-transgender-athletes-rcna196011)

Related: just one day later -- Donald Trump’s USDA reverses freeze on funding to Maine’s public universities

[https://www.wabi.tv/2025/03/13/university-maines-usda-funding-restored/](https://www.wabi.tv/2025/03/13/university-maines-usda-funding-restored/)

## Freedom of Expression

* "Nobody can protect you" -- advice given to some students at Columbia University

[https://www.nytimes.com/2025/03/12/nyregion/columbia-university-trump-protests.html?unlocked_article_code=1.3k4.UaS8._eQnmRK_HvH9&smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/03/12/nyregion/columbia-university-trump-protests.html?unlocked_article_code=1.3k4.UaS8._eQnmRK_HvH9&smid=nytcore-ios-share&referringSource=articleShare)

* University of Minnesota, under Federal Scrutiny, Limits Its Political Speech

[https://www.nytimes.com/2025/03/14/us/university-of-minnesota-political-speech.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/03/14/us/university-of-minnesota-political-speech.html?smid=nytcore-ios-share&referringSource=articleShare)


* Mahmoud Khalil arrested at Columbia under

[https://www.chronicle.com/article/an-ice-arrest-at-columbia-u-stokes-outrage-and-raises-legal-questions](https://www.chronicle.com/article/an-ice-arrest-at-columbia-u-stokes-outrage-and-raises-legal-questions)

NPR interview with DHS official

[https://www.npr.org/2025/03/13/nx-s1-5326015/mahmoud-khalil-deportation-arrests-trump](https://www.npr.org/2025/03/13/nx-s1-5326015/mahmoud-khalil-deportation-arrests-trump)

Michelle Goldberg's characterization: "This Is the Greatest Threat to Free Speech Since the Red Scare"

[https://www.nytimes.com/2025/03/10/opinion/mahmoud-khalil-free-speech.html](https://www.nytimes.com/2025/03/10/opinion/mahmoud-khalil-free-speech.html)

* Dept. of Homeland Security search two dorm rooms at Columbia University

[https://www.nytimes.com/2025/03/14/us/politics/dorm-search-columbia-university-dhs.html?unlocked_article_code=1.304.ZelC.P1jEoqfArcBa&smid=url-share](https://www.nytimes.com/2025/03/14/us/politics/dorm-search-columbia-university-dhs.html?unlocked_article_code=1.304.ZelC.P1jEoqfArcBa&smid=url-share)

(Thanks to my colleague Jason Bishop)

* "Exigent circumstances" allow ICE on campus without warrant

[https://publicsafety.columbia.edu/content/protocol-potential-visits-campus-us-immigration-and-customs-enforcement-ice-agents](https://publicsafety.columbia.edu/content/protocol-potential-visits-campus-us-immigration-and-customs-enforcement-ice-agents)


* Just this week, the Chancellor formed a committee to draft a freedom of expression policy co-chaired by CUNY's General Counsel and the UFS chairperson. The starting point for this discussion will be the 2016 attempt to bring forth such a policy. The time frame will be that full vetting of a draft will occur in the fall, and during the spring there will be chances for input from members of the CUNY community.

## DOE/Civil rights

* 60 campuses targeted yesterday by the DOE

[https://www.ed.gov/about/news/press-release/us-department-of-educations-office-civil-rights-sends-letters-60-universities-under-investigation-antisemitic-discrimination-and-harassment](https://www.ed.gov/about/news/press-release/us-department-of-educations-office-civil-rights-sends-letters-60-universities-under-investigation-antisemitic-discrimination-and-harassment)

(Some from New York state, but not CUNY, as of now.)


* Democratic Attorneys General sue the gutting of DOE staffing:

[https://www.nytimes.com/2025/03/13/nyregion/democratic-attorneys-general-education-department-suit.html?unlocked_article_code=1.3k4.Ard0.5bJuH-muCTXO&smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/03/13/nyregion/democratic-attorneys-general-education-department-suit.html?unlocked_article_code=1.3k4.Ard0.5bJuH-muCTXO&smid=nytcore-ios-share&referringSource=articleShare)

## Another Cultural Revolution 60 years later?

This interview with Chris Rufo was last week, but chilling enough to include here, as he appears to me as a Howard Roark aspirant willing to dynamite higher ed rather than let it work for the masses just as a matter of principle:

[https://www.nytimes.com/2025/03/07/opinion/chris-rufo-trump-anti-dei-education.html?unlocked_article_code=1.304.gkL5.LpsG7i98gHfa&smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/03/07/opinion/chris-rufo-trump-anti-dei-education.html?unlocked_article_code=1.304.gkL5.LpsG7i98gHfa&smid=nytcore-ios-share&referringSource=articleShare)

Some quotes

>  I think they should say, if you have discriminatory D.E.I. programs, if you have discriminatory admissions procedures, or discriminatory hiring and promotion practices, you’ll be stripped of federal funding, which in a sense would mean bankruptcy for many universities.

> Conservatives cannot fully staff the Department of Education. Conservatives cannot fully compete for education grants, or university-level research programs. No, conservatives can’t do any of those things. So we have to figure out what we can do. Where can we have leverage? Where can we take over or recapture an institution? And if we can’t do those things, then what do we have to shut down? Shutting things down is actually a very effective strategy.

> by spinning off, privatizing and then reforming the student loan programs, I think that you could put the university sector as a whole into a significant recession. And I think that would be a very salutary thing.

> I think that putting the universities into contraction, into a recession, into declining budgets, into a greater competitive market pressure, would discipline them in a way that you could not get through administrative oversight with 150 extra Department of Ed bureaucrats.

:::

I'm sure I missed some big ones. If you have stories/reports you would like me to include in anticipated future digests, please send along via an email to me directly (john.verzani@csi.cuny.edu).


Regards,

John
