# Mar 6

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.


## Academic freedom

* RFK Jr. Secures Pledges From Medical Schools to Beef Up Nutrition Education

[https://www.insidehighered.com/news/faculty-issues/curriculum/2026/03/06/53-medical-schools-pledge-beef-nutrition-education](https://www.insidehighered.com/news/faculty-issues/curriculum/2026/03/06/53-medical-schools-pledge-beef-nutrition-education)

(Pun intended?)

> At the Trump administration’s urging, 53 medical schools are expanding their nutrition education curriculum.

> Starting next fall, those medical schools—including programs at Tufts University, the University of Florida and George Washington University—will require students to complete at least 40 hours of nutrition education. While all of the nearly 200 medical schools in the United States already require some form of nutrition education, it averages just 1.2 hours per year.

> Kennedy and Education Secretary Linda McMahon emphasized at the event that the medical schools’ pledges were voluntary. But the administration has shown a willingness to use federal funding that universities and medical schools rely on as leverage to compel policy changes. In the last year, Kennedy has mentioned that he could cut off federal funding to those who don’t fall in line with his vision for nutrition education, but that threat doesn’t appear to have been formalized.

* Censoring Courses Isn’t the Law in Texas. Public Universities Are Doing It Anyway.

[https://www.chronicle.com/article/censoring-courses-isnt-the-law-in-texas-public-universities-are-doing-it-anyway](https://www.chronicle.com/article/censoring-courses-isnt-the-law-in-texas-public-universities-are-doing-it-anyway)

> When Texas Senate Bill 37 was approved last year, faculty groups had one reason to feel cautiously relieved. While early versions of the bill had set sharp restrictions on how faculty could teach about race and gender across the general-education curriculum, those rules, after aggressive lobbying, had been removed during the final, closed-door negotiating sessions.

> But, in recent months, Texas board members and administrators have reinserted strikingly similar requirements.

> Thousands of courses have been reviewed, hundreds altered, and an unknown number canceled for including race- and gender-related content, including on world religions and ethics in public-policy courses. College leaders say they’re complying with state law. But nothing in SB 37 requires them to censor specific content.

> Critics countered that the terms were overly vague and the restrictions too sweeping. Faculty members would be walking on eggshells, they argued, trying to avoid topics that might get them in trouble. Law professors warned that a law that censors course content could suffer the fate of Florida’s Stop WOKE Act, a 2023 law limiting how race and gender can be discussed in public university classrooms. A federal judge blocked the law after it was challenged as an unconstitutional restriction on speech. A Mississippi law banning the teaching of “divisive topics” was blocked last year for similar reasons.

> During months of debate and multiple revisions of Senate Bill 37, lobbyists from the AAUP, the American Federation of Teachers, and the Texas Faculty Association, along with civil-rights and free-speech groups, converged on the capitol to warn lawmakers that the changes could spark a faculty brain drain, hollow out education, and raise potential accreditation problems.

> The lobbyists wrote dozens of opinion pieces and trained hundreds of faculty volunteers to testify as private citizens about how the proposed legislation would affect their disciplines.

> The law went into effect September 1, and within months, the state’s major university systems announced policies asserting their governing bodies’ newly enhanced authority over the curriculum. All of the new policies extended their scrutiny to electives and graduate-level courses.




## Freedom of expression

* Florida domestic terrorism bill advances despite concerns | WUSF

[https://www.wusf.org/politics-issues/2026-02-26/florida-domestic-terrorism-designation-bill-advances-constitutional-concerns](https://www.wusf.org/politics-issues/2026-02-26/florida-domestic-terrorism-designation-bill-advances-constitutional-concerns)

> It would allow the state to designate certain groups as domestic terrorist organizations. Supporters cite public safety, and critics say it’s unconstitutional

> Those include being cut off from public funding, restrictions tied to activities at public schools and universities, and potential legal consequences for certain members.

> College students would be expelled for “promoting” such a group, and anyone who “knowingly provides material support” could trigger criminal scrutiny.

> With an executive order, Gov. Ron DeSantis recently designated the Council on American-Islamic Relations, a significant United States Muslim civil rights and advocacy group, a “foreign terrorist organization."

> CAIR Florida is urging a "no" vote on the bill, warning it could be used against Islamic schools and Muslim organizations.

* Citing Balance Issues, Catholic U Rejects Pro-Israel Group’s Speaker Requests

[https://www.insidehighered.com/news/institutions/religious-colleges/2026/03/04/catholic-u-rejects-pro-israel-groups-speaker](https://www.insidehighered.com/news/institutions/religious-colleges/2026/03/04/catholic-u-rejects-pro-israel-groups-speaker)

> The Students Supporting Israel chapter at Catholic University of America is accusing the university of discrimination after administrators denied its requests to bring speakers to campus unless the events represented “both sides.”

> University officials pushed back, saying the students can revamp their plans and try again.

> The student group had sought to invite Dany Tirza, the chief architect of Israel’s controversial security fence or barrier wall separating the West Bank, for an event about the project. And then they wanted to bring in U.S. representative Randy Fine, who’s Jewish, for an event on “ending antisemitism in America.” A sought-after conservative speaker on antisemitism and Zionism, Fine’s torrent of anti-Muslim remarks has also sparked controversy and earned him condemnations from the Congressional Jewish Caucus and multiple pro-Israel and Jewish advocacy groups.

(Randy Fine really stood out---maybe not favorably---when CUNY testified on the hill)



### Anti-woke/anti-DEI is simply racism

* The Rise and Recent Decline of Diversity in Higher Ed

[https://www.insidehighered.com/news/diversity/2026/03/03/how-diversity-gained-and-lost-its-place-higher-ed](https://www.insidehighered.com/news/diversity/2026/03/03/how-diversity-gained-and-lost-its-place-higher-ed)

> In his new book, The Diversity Principle: The Story of a Transformative Idea (Yale University Press), David Oppenheimer, a law professor at the University of California, Berkeley, traces the history of diversity as a guiding framework for institutions, largely through the people and court rulings that shaped it.

> He credits Wilhelm von Humboldt, who founded the University of Berlin in 1810, for first recognizing the value of incorporating a variety of viewpoints into education and opening his predominantly Protestant institution to Catholics and Jews. In the U.S., early proponents of diversity included philosopher John Dewey, former Harvard University president Charles Eliot and Supreme Court Justice Oliver Wendell Holmes Jr.

> Diversity was not always the partisan concept it’s become today. Oppenheimer notes that the majority opinions in three key Supreme Court decisions regarding diversity in higher education were written by conservative justices appointed by Republicans.



## Visas

* Florida Board Approves Ban on H-1B Visas

[https://www.insidehighered.com/news/quick-takes/2026/03/03/florida-board-approves-ban-h-1b-visas](https://www.insidehighered.com/news/quick-takes/2026/03/03/florida-board-approves-ban-h-1b-visas)

> The Florida Board of Governors on Monday approved an eight-month pause on H-1B visas, becoming the second state after Texas to ban public colleges and universities from hiring new faculty, researchers and medical residents through that visa program.

> Kimberly Dunn, an associate professor of accounting at Florida Atlantic University and faculty representative to the board, spoke against the motion on Monday. She and student representative Carson Dale voted against the motion.

> “A one-year pause, even if it goes away after one year, will have lasting effects” on reputation and recruiting, Dunn said during the meeting.


## Funding cuts

### NIH

* NIH Will No Longer Recognize Union of Early-Career Researchers

[https://www.insidehighered.com/news/quick-takes/2026/03/06/nih-moves-derecognize-union-early-career-researchers](https://www.insidehighered.com/news/quick-takes/2026/03/06/nih-moves-derecognize-union-early-career-researchers)

> The National Institutes of Health will no longer recognize a union of early-career researchers who work in its labs, NOTUS reported.

> NIH fellows—who typically receive term-limited grants—“are not ‘employees’” and are not “employed in an agency,” read the email the NIH sent to leaders of the NIH Fellows United-UAW union earlier this week. “The NIH/UAW bargaining unit should never have been certified.”

> Union leaders called the NIH’s move “part of a coordinated effort by the current administration to dismantle federal worker protections” in an email they sent to members. “Our contract is still in effect, and management’s attempt to evade the contract is against the law. We are moving on every available front—legal, political, and most importantly, through the organized power of our membership—to defend our rights.”


## Federal Agencies

### DoD

* NYTimes: Pentagon to Cut Ties With Top Universities and Think Tanks

[https://www.nytimes.com/2026/02/28/us/politics/pentagon-universities-think-tanks.html?smid=nytcore-ios-share](https://www.nytimes.com/2026/02/28/us/politics/pentagon-universities-think-tanks.html?smid=nytcore-ios-share)

> The Defense Department has decided to cut academic ties with nearly two dozen top universities and think tanks as part of Defense Secretary Pete Hegseth’s campaign against what he calls anti-American values and “wokeness.”

> In a video published to social media on Friday hours before the United States and Israel attacked Iran, Mr. Hegseth denounced the institutions in blistering language, calling them politically liberal institutions with “wicked ideologies” that were indoctrinating U.S. service members. He said that, beginning in the new school year in September, the Defense Department would ban service members from attending those universities.

> The Defense Department said it would also cut ties with seven high-profile think tanks in Washington known for their defense and national security analysis: the Center for Strategic and International Studies, New America, the Brookings Institution, the Atlantic Council, the Center for a New American Security, the Council on Foreign Relations and the Henry L. Stimson Center.

> In total, 93 military students are currently enrolled in graduate-level programs and fellowships at these institutions. Many of the programs offer mid- and senior-level officer’s courses on national and international security. The largest cohort goes to Harvard, with 21 enrolled in programs at the Ivy League school. Mr. Hegseth, who served as an infantry officer with the National Guard, graduated from Harvard’s Kennedy School in 2013 with a master’s degree in public policy.

> In a memo detailing the cuts, the Defense Department said it was considering replacing the programs with those at institutions including state universities and conservative Christian schools like Liberty University and Hillsdale College.

(Also)

[https://insidehighered.com/news/admissions/graduate/2026/03/06/hegseth-waging-war-colleges-his-targets-are-unclear](https://insidehighered.com/news/admissions/graduate/2026/03/06/hegseth-waging-war-colleges-his-targets-are-unclear)

>  But it remains unclear what he’s actually canceling, why specific universities have been targeted or favored and what he plans to replace these programs with.

> “I think it’s created a lot of confusion,” she said, adding that “disrupting those partnerships and those programs is not going to help meet the needs of the branches of service.”

## Institutional assaults

### Indiana

* Indiana Bill Threatening Low-Earning Degree Programs Heads to Governor’s Desk

[https://www.insidehighered.com/news/quick-takes/2026/03/03/indiana-advances-bill-threatens-low-earning-programs](https://www.insidehighered.com/news/quick-takes/2026/03/03/indiana-advances-bill-threatens-low-earning-programs)

> The Indiana Legislature on Friday passed Senate Bill 199, which threatens public college and university programs that graduate low earners, The Indiana Capital Chronicle reported.

> If signed into law by Gov. Mike Braun, the bill would direct the Indiana Commission for Higher Education to review state higher education programs whose graduates earn median salaries below the average earnings of a high school diploma holder. In Indiana, the average high school graduate earns $35,000. Programs that fail to meet this standard would be at risk of closure; at-risk programs likely include Ball State University’s bachelor’s degree in dance, Indiana University at Bloomington’s bachelor’s in music, Ivy Tech Community College’s associate degree in library and archives assisting, and Purdue Northwest’s bachelor’s in computer software and media applications, among others.



## Op eds

* The False Flag of Viewpoint Diversity

[https://www.chronicle.com/article/the-false-flag-of-viewpoint-diversity](https://www.chronicle.com/article/the-false-flag-of-viewpoint-diversity)

> How to regain public confidence in higher education? Programs developed in the name of “viewpoint diversity” are increasingly popular. But these programs risk being just as problematic as the orthodoxies and confinements they are designed to correct. “It all depends on where you are coming from” might pass for deep wisdom in dorm-room chatter, but such crude “viewpoint epistemology” fails to explain the intellectual content of the social-scientific and humanistic disciplines that are most often said to be captured by parochial, if not ideologically skewed perspectives.

> The results of inquiry matter much more than their starting points. Where you begin of course affects where you go, but learned communities are organized to ensure that inquiries go well beyond their points of origin. Academics continually interrogate each other about exactly this potential failing. Have scholars simply projected their “viewpoint” on what they are studying? Any assertion that they have failed in this way deserves a response only if critics know what they are talking about.

> Bret Stephens does not. His sweeping dismissal of Columbia and Berkeley as “essentially factories of Maoist cadres” is not a serious criticism, and The New York Times should be ashamed to have published such an ignorant and damaging libel. Public discussion of higher education today is filled with less scurrilous, but equally misleading effusions. But some criticisms do demand attention. To understand what kind, it may be helpful to review how academic professionalism actually works. This practice is so often misunderstood that its basic structure invites repeated articulation, banal as insiders will find it.



## How best to describe the times we are in

* NYTimes: America Cannot Withstand the Economic Shock That’s Coming

[https://www.nytimes.com/2026/03/06/opinion/ai-labor-unemployment.html?smid=nytcore-ios-share](https://www.nytimes.com/2026/03/06/opinion/ai-labor-unemployment.html?smid=nytcore-ios-share)

(Here we have Biden's Secretary of Commerce weighing in on Higher Education, perhaps in a way that would move it far away from what we may hope.)

> I refuse to accept that an unemployment crisis is inevitable. The answer, however, isn’t to slow down A.I. innovation and leave ourselves less competitive and less prepared. Nor is generic reskilling that pushes people into completely new roles and industries. Instead, we should build a modern transition system with better data to predict job losses and new forms of support to help workers transition between jobs.

> This can start with tearing down the wall between the business and education communities.

> The future of higher education should be modular, and employers must be active partners in shaping what gets taught. The country needs to shift focus from long and expensive degrees that risk obsolescence before completion toward short, affordable job-linked credits that offer on-ramps from education to work. People should be encouraged to pursue credentials that can stand alone or be stacked over time into degrees, bringing people back to campus over the arc of their lives. A midcareer accountant displaced by A.I. doesn’t need another master’s degree. Instead, she may be better off with a four-month credential and temporary wage insurance that bridges any pay gap and incentivizes her to accept a new role sooner.

(Call me a skeptic)

> The funding model for higher education must change, too. Public investment should hold schools to measurable labor market results, not just enrollments. Texas offers a working example: Community colleges that award credentials in high-demand fields receive greater state funding. If we take this approach, we’ll quickly see a survival of the fittest emerge: Innovative programs that meet labor market needs will be rewarded, while underperformers will shutter.



## Blowback

* Medical Residency Application Rates Fell in States That Restricted Abortion

[https://www.insidehighered.com/news/quick-takes/2026/03/04/residency-app-rates-fell-states-restricted-abortion](https://www.insidehighered.com/news/quick-takes/2026/03/04/residency-app-rates-fell-states-restricted-abortion)

> pplication rates to medical residency programs fell on average in states that passed new abortion restrictions after the overturning of Roe v. Wade compared to states that didn’t, a new scientific paper reveals.

> “This is true for all medical specialties, so it’s not just women’s health that’s under threat,” said Anisha Ganguly, the study’s lead author and an assistant professor of medicine at the University of North Carolina at Chapel Hill.

> Ganguly said the decrease is especially pronounced in primary care and emergency medicine. About half of medical residents go on to practice in the state where they receive their residency, she said.

## AI misdeeds

* In-Person Classes Aren’t Safe From the AI Cheating Boom

[https://www.insidehighered.com/news/students/academics/2026/03/05/person-classes-arent-safe-ai-cheating-boom](https://www.insidehighered.com/news/students/academics/2026/03/05/person-classes-arent-safe-ai-cheating-boom)

(The AI Cheating Boom...)

> Online courses have long bred fears of rampant academic dishonesty, exacerbated in recent years by the advent of increasingly sophisticated digital technology. But in-person courses may be just as vulnerable, according to one biology professor at Arizona State University who conducted an audit of her department’s class offerings.

> A preliminary analysis of syllabi for 21 in-person ASU biology courses during fall 2025 shows that on average, 45 percent of points for those courses can be easily earned by employing digital cheating methods, including some powered by artificial intelligence.

> “We were measuring student effort by class attendance or by having them watch a video and answering a set of questions before class. That was before every single student had access to ChatGPT at our university,” Sara Brownell, the professor who conducted the analysis, told Inside Higher Ed. “Now they can just copy and paste the question into that and get the answers. We’re using students’ grades as a reflection of their learning and effort in class, and AI, other technology and increased academic dishonesty [are] undermining that.”

> But ChatGPT and similar large language models are not the only digital cheating tools students are using, Brownell said.

> While Brownell has supported the active learning movement, she said she realized last year that many of the students enrolled in her large, in-person biology course weren’t attending class—but receiving participation points anyway by using an electronic clicker, a common tool that allows students to answer in-class questions remotely. Some students even answer questions for their absent classmates.

> “Yes, I cheat on participation,” one student told Brownell’s research group. “Participation made up a really big part of our grade. I wasn’t about to sacrifice points that I might need in the future if I’m not doing well on a test. It’s nice to have that safety blanket and there’s really no reason to not have a really good grade in participation.”

* He Vibe-Coded a Crisis for Higher Education

[https://www.chronicle.com/article/einstein-may-have-been-a-prank-but-the-agentic-ai-tool-put-higher-ed-on-notice](https://www.chronicle.com/article/einstein-may-have-been-a-prank-but-the-agentic-ai-tool-put-higher-ed-on-notice)

> When the 22-year-old engineer Advait Paliwal posted a video on X last week showing his new agentic-AI tool, named “Einstein,” retrieving a homework assignment from Canvas, answering several complicated computer-science questions, and creating a PDF of the solved worksheet, higher ed had a meltdown.

> What is the point of homework, or professors, or college itself if students can have a machine do everything for them?

> “I don’t want to live on this planet anymore,” one professor wrote.

> Theoretically, an agentic AI connected to a learning-management system like Canvas or Blackboard could take quizzes, post on discussion boards, or complete and submit homework assignments. Besides Einstein, no commercial agentic-AI tool is known to have been created explicitly for higher ed.

(Theoretically is an odd word. There is one advertised here, and the tools used were just released and open to all, so there may be *many* out there being used under the radar.)

> “It really is to the point where you’re talking about kind of putting your brain in a jar and going on autopilot,” said Marc Watkins, assistant director of academic innovation at the University of Mississippi. “We pay millions of dollars in licensing fees for course-management systems under the basic agreement that this is going to accurately gauge our students’ learning. That is not going to happen if you’re going to use the agentic tool that impersonates you.”

> “There is a fine line between a flash in the pan and a harbinger of things to come. The program is not an outlier,” wrote Jason Gulya, a professor of English and media communications at Berkeley College. “As we move forward, we need to pay close attention to the claims of developers like Paliwal.”

> Paliwal dropped out of a computer-science graduate program at Brown University in 2024, deciding it wasn’t worth paying tuition to graduate “with outdated skills” and miss out on the AI boom. He moved to San Francisco and began coding full time.

> College leaders, he said, are failing to equip students for a rapidly evolving and increasingly automated work force. Einstein is his “war cry.”


----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
