# Mar 28

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week. Sadly, there is too much to track faithfully.


## CUNY Guidance

* CUNY finally offered something like guidance on ICE and immigration enforcement to the presidents. My president made copies of this and left them for my Senators. I’m sharing with you for further distribution as you see fit. (Thanks EI)

[https://www.dropbox.com/scl/fi/vq3utczojairkvbv5ewuu/CUNY-Guidance-on-ICE-Immigration-Enforcement.pdf?rlkey=iib7oc2j7c9r7cv15c9jdtyjk&dl=0](https://www.dropbox.com/scl/fi/vq3utczojairkvbv5ewuu/CUNY-Guidance-on-ICE-Immigration-Enforcement.pdf?rlkey=iib7oc2j7c9r7cv15c9jdtyjk&dl=0)

* University URLs to Support Our Students. The Student Affairs Committee of the UFS wrote a blog canvassing many areas within CUNY's websites as regards supporting our students:

[https://www1.cuny.edu/sites/cunyufs/2025/03/21/university-urls-to-support-our-students/](https://www1.cuny.edu/sites/cunyufs/2025/03/21/university-urls-to-support-our-students/)

* Supporting Our Students Part Two

[https://www1.cuny.edu/sites/cunyufs/2025/03/25/supporting-our-students-part-two/](https://www1.cuny.edu/sites/cunyufs/2025/03/25/supporting-our-students-part-two/)

## Hunter College

* EI continues to update his archive of statements made by campuses and organizations in support of Academic Freedom as relates to its infringement at Hunter College.


[https://www.dropbox.com/scl/fo/my5g55jprx5o64r4vzus0/AO9WLNUUIorJRhgTO1SupgY?rlkey=zvsqtp7ev781y4rqqjti8xaho&dl=0](https://www.dropbox.com/scl/fo/my5g55jprx5o64r4vzus0/AO9WLNUUIorJRhgTO1SupgY?rlkey=zvsqtp7ev781y4rqqjti8xaho&dl=0)

Newly added are statements from BCC and BMCC.

* Hunter job is re-listed

[https://cuny.jobs/new-york-ny/faculty-open-rank-assistant-associate-or-full-professor-palestinian-studies-cluster-hires-2-social-science-humanities/CADBACF3795E40FDA0FB08E99A27ED40/job/](https://cuny.jobs/new-york-ny/faculty-open-rank-assistant-associate-or-full-professor-palestinian-studies-cluster-hires-2-social-science-humanities/CADBACF3795E40FDA0FB08E99A27ED40/job/)



## Freedom of Expression

* NYTimes: Immigrants and Freedom of Speech

[https://www.nytimes.com/2025/03/24/briefing/immigration-trump-constitution.html](https://www.nytimes.com/2025/03/24/briefing/immigration-trump-constitution.html)

> But Trump is taking advantage of a genuinely unsettled aspect of the law: Does the Constitution protect noncitizens’ freedom of speech?

> Immigrants do have due process rights, and Khalil’s case is currently going through the courts. But the administration has tried to bypass even those protections in other cases. It cited the Alien Enemies Act of 1798 to deport hundreds of Venezuelan migrants without any kind of hearing in court.

## ICE

* (Judge Suggests White House May Have Stretched Deportation Law Too Far

[https://www.nytimes.com/live/2025/03/21/us/trump-news#trump-cornell-student-ice](https://www.nytimes.com/live/2025/03/21/us/trump-news#trump-cornell-student-ice)

* NYTimes: Columbia Student Hunted by ICE Sues to Prevent Deportation

[https://www.nytimes.com/2025/03/24/nyregion/columbia-student-ice-suit-yunseo-chung.html](https://www.nytimes.com/2025/03/24/nyregion/columbia-student-ice-suit-yunseo-chung.html)

* WP: New Trump demand to colleges: Name protesters — and their nationalities

[https://www.washingtonpost.com/education/2025/03/25/trump-administration-campus-antisemitism-investigations/12](https://www.washingtonpost.com/education/2025/03/25/trump-administration-campus-antisemitism-investigations/12)

> An early step in civil rights investigations is always a letter to the university demanding certain information. Typically, the department asks how many discrimination complaints were received, and what school officials did in response. 

> But the Trump administration told the attorneys working on the cases to also collect the names and nationalities of students who might have harassed Jewish students or faculty, according to documents and three attorneys with the Office for Civil Rights who have direct knowledge of the situation and who spoke on the condition of anonymity because they were not authorized to discuss the cases publicly.

* DHS detains Tufts grad student who advocated for Palestine and the "humanity of all people"

[https://www.salon.com/2025/03/26/dhs-detains-grad-student-advocated-for-palestine-and-the-humanity-of-all-people/](https://www.salon.com/2025/03/26/dhs-detains-grad-student-advocated-for-palestine-and-the-humanity-of-all-people/)

(Flagged by Canary Mission which prominently features the CCNY encampment.)

* NYTimes: ICE Agents Detain University of Alabama Doctoral Student

[https://www.nytimes.com/2025/03/26/us/ice-detains-doctoral-student-university-alabama.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/03/26/us/ice-detains-doctoral-student-university-alabama.html?smid=nytcore-ios-share&referringSource=articleShare)


## Funding

* Trump Plans to Move Troubled Financial-Aid Office to Decimated Small Business Administration

[https://www.chronicle.com/article/trump-plans-to-move-troubled-financial-aid-office-to-decimated-small-business-administration](https://www.chronicle.com/article/trump-plans-to-move-troubled-financial-aid-office-to-decimated-small-business-administration)

> Jessica Thompson, senior vice president of the Institute for College Access and Success (TICAS), criticized the move. “With no clear strategy, the administration has decimated staffing and oversight capabilities at both agencies while simultaneously announcing its intent to immediately transfer a more than $1.5-trillion loan portfolio between them,” she said in a written statement. “This can only result in borrowers experiencing erratic and inconsistent management of their federal student loans. Errors will prove costly to borrowers and ultimately, to taxpayers.”

* NYTimes: ‘Chaos and Confusion’ at the Crown Jewel of American Science

[https://www.nytimes.com/2025/03/24/health/nih-doge-trump.html](https://www.nytimes.com/2025/03/24/health/nih-doge-trump.html)

> A week after Donald J. Trump was inaugurated, a senior scientist at the National Institutes of Health was preparing to give an invited talk at a scientific meeting when an urgent call came in from an administrative assistant.

> There is a total communications ban, the scientist was told, and you cannot give the speech.

> As soon as the scientist got back to the office, another ban went into effect — one that prohibited researchers from submitting papers to journals for publication.

> One said that DOGE had begun a reign of “chaos and confusion.”

> Hundreds of highly competitive grants that support research at universities and medical schools across the country have been cut. Many of the eliminated grants had descriptions that included terms like “minorities,” “transgender,” “AIDS” and “vaccine hesitancy.” But cuts have also affected research on the chronic diseases that Mr. Kennedy has made his priority; for instance, funding has been cut for a grant to Columbia University for a study that has followed people who have diabetes or are at risk of developing it for more than a quarter-century


* NYTimes: Columbia Faculty Protests as Trump Officials Hail University Concessions

[https://www.nytimes.com/2025/03/24/nyregion/columbia-trump-response.html](https://www.nytimes.com/2025/03/24/nyregion/columbia-trump-response.html)

> Earlier on Monday, at least 50 professors turned out in a steady drizzle outside the campus gates to protest the funding cuts and what they criticized as Columbia’s conciliatory response. The professors said they hoped to be the vanguard of a resistance movement among academics that remains, for now, at an early stage.

> “We need to stand up, all of us,” said Michael Thaddeus, a mathematics professor at Columbia and vice president of the campus chapter of the American Association of University Professors, speaking to the crowd. “We need to organize, from the grass roots to the national level. If we lead, our leaders will follow.”

NYTimes: ‘It Is Hard to Imagine a More Sweeping Agenda to Make Americans Less Healthy’

[https://www.nytimes.com/2025/03/25/opinion/trump-toxins-cancer-environment.html](https://www.nytimes.com/2025/03/25/opinion/trump-toxins-cancer-environment.html)

Scroll down to find

> Turning to the issue of medical research, Duke University provides a case study of the problems facing higher education institutions that are struggling to maintain research budgets under the Trump administration.

> Donald McDonnell, a professor of molecular cancer biology at Duke whose laboratory has received $40 million from N.I.H. over 30 years, told the A.P. that his lab is likely to go into the red because of the uncertainty of N.I.H. grants, forcing him to order layoffs: “The bottom line is, I can’t live, I can’t think in this chaos,” McDonnell said.

> The threatened cuts, according to McDonnell, have endangered the next generation of researchers. Duke medical school has reduced the number of Ph.D. students it will admit from 130 this year to 100 or even fewer in the next academic year.

* WP: EPA knew it wrongfully canceled dozens of environmental grants, documents show


[https://www.washingtonpost.com/climate-environment/2025/03/25/epa-environment-grants-wrongful-termination/](https://www.washingtonpost.com/climate-environment/2025/03/25/epa-environment-grants-wrongful-termination/)

> Julia Haggerty, an associate professor of geography at Montana State University, worked with local partners for almost a year to assemble a competitive application to create a program designed to provide technical assistance and resources to underserved communities.

> Beginning in January, the program’s funding oscillated between being frozen and unfrozen. The EPA terminated the grant on Feb. 21, saying the “award no longer effectuates the program goals or agency priorities,” according to an email reviewed by The Post.

## Blowback

* NYTimes: As Trump’s Policies Worry Scientists, France and Others Put Out a Welcome Mat

[https://www.nytimes.com/2025/03/25/europe-trump-science-research.html](https://www.nytimes.com/2025/03/25/europe-trump-science-research.html)

> the university [Aix Marseille University] in the south of France known for its science programs, has received about a dozen applications per day from what the school considers “scientific asylum” seekers.

> If the movement becomes a trend, it could mean the reversal of the long-term brain drain that has seen generations of scientists move to the United States.

* Fallout from Columbia capitulation fuels fears about academic freedom

[https://www.washingtonpost.com/nation/2025/03/24/fallout-columbia-capitulation-fuels-fears-about-academic-freedom/](https://www.washingtonpost.com/nation/2025/03/24/fallout-columbia-capitulation-fuels-fears-about-academic-freedom/)

> "I’m worried that the university’s decision could change how civil rights enforcement works,” Erickson said. “If the Trump administration can declare by fiat that the university is in violation of Title VI protections and withhold funding on that basis — without due process or review — every school district in this country could potentially be told that they are in violation of civil rights law and asked to negotiate.”

* Trump-Inflicted Funding Cuts Could Lead to Overworked Faculty and Staff, Larger Class Sizes

[https://www.chronicle.com/article/trump-inflicted-funding-cuts-could-lead-to-overworked-faculty-and-staff-larger-class-sizes](https://www.chronicle.com/article/trump-inflicted-funding-cuts-could-lead-to-overworked-faculty-and-staff-larger-class-sizes)

> While the federal government’s $76 billion in emergency aid to higher education from 2020 to 2022 helped colleges get through the Covid financial crisis, research universities may be facing an even more significant financial threat this time around

* Don’t visit the US – it just isn’t worth the risks right now | Arwa Mahdawi | The Guardian

[https://www.theguardian.com/commentisfree/2025/mar/25/dont-visit-the-us-it-just-isnt-worth-the-risks-right-now](https://www.theguardian.com/commentisfree/2025/mar/25/dont-visit-the-us-it-just-isnt-worth-the-risks-right-now)

(This was posted in a discussion about holding international conferences in the US.)

*What Rural Universities Stand to Lose Under Trump’s DEI, Higher Education Cuts — ProPublica


[https://www.propublica.org/article/regional-public-universities-trump-funding-dei](https://www.propublica.org/article/regional-public-universities-trump-funding-dei)

> That’s because diversity also means something more in regional public universities: Many students at SIU come from families that are poor, or barely middle class, and depend on scholarships and mentorship to succeed. Paul Frazier, SIU’s vice chancellor for anti-racism, diversity, equity and inclusion, said the way DEI has been politicized ignores what it actually does: “Poor doesn’t have a color.”

## Bent knee

* Columbia University caves to demands to restore $400m from Trump administration

[https://www.theguardian.com/us-news/2025/mar/21/columbia-university-funding-trump-demands](https://www.theguardian.com/us-news/2025/mar/21/columbia-university-funding-trump-demands)

[https://www.chronicle.com/article/facing-a-loss-of-400-million-columbia-u-concedes-to-trumps-demands](https://www.chronicle.com/article/facing-a-loss-of-400-million-columbia-u-concedes-to-trumps-demands)

* NYTimes: Adams Uses Agency ‘Tracker’ to Control Messaging on Trump

[https://www.nytimes.com/2025/03/24/nyregion/adams-trump-tracker.html](https://www.nytimes.com/2025/03/24/nyregion/adams-trump-tracker.html)

> The mayor’s office has avoided discussing “Know Your Rights” guidance on how immigrants should respond to federal immigration officials and gender-affirming health care for transgender people, according to one of the people, who spoke on the condition of anonymity for fear of retribution.

* University leaders, pinned between liberal faculty and the Trump administration, are quietly trying to make friends in Washington


[https://www.wsj.com/us-news/education/universities-trump-lobbyists-funding-washington-a2e5c77a?st=j5R8xP&reflink=article_gmail_share](https://www.wsj.com/us-news/education/universities-trump-lobbyists-funding-washington-a2e5c77a?st=j5R8xP&reflink=article_gmail_share)

> Now few House lawmakers—and virtually no Republicans—are interested in going to bat for higher education, lobbyists, trade groups and officials said.

> Dozens of schools, including the University of California system and Harvard, have paused hiring amid concerns over the future of federal funding. The National Institutes of Health normally provides billions of dollars to universities every year for medical and public-health research. Proposed cuts to that funding are now being challenged in courts. In the meantime, some schools have rescinded admission offers to graduate students.

> While many faculty members argue universities shouldn’t yield to Trump, they are in a tricky spot. It isn’t uncommon for a quarter or more of the operating budget of a large university to come from federal sources in the forms of student loans, Pell Grants and research funding—research that supporters say goes on to produce innovations and fuel the broader economy.

> Trump’s actions constitute a “war on civil society,” Roth [Wesleyan PResident] has told Connecticut lawmakers.

* Donald Trump’s insecurity state

[https://wapo.st/4izVKU2](https://wapo.st/4izVKU2)

> [Trump post] While the State of Maine has apologized for their Governor’s strong, but totally incorrect, statement about men playing in women’s sports while at the White House House Governor’s Conference,” he posted, “we have not heard from the Governor herself, and she is the one that matters in such cases. While the State of Maine has apologized for their Governor’s strong, but totally incorrect, statement about men playing in women’s sports while at the White House House Governor’s Conference,” he posted, “we have not heard from the Governor herself, and she is the one that matters in such cases.

> His administration has also gone after Columbia University, demanding that the school make concessions to not lose $400 million in federal funding. Apparently failing to understand that extortion is rarely a one-time deal, the university agreed to the concessions. (Sure enough, a senior Justice Department official indicated in a recent radio interview that more concessions would be needed.)

> So much of what orbits the president is held in place by the gravitational pull of his insecurity.


* Columbia Capitulated — But So Did the Rest of Higher Ed (Thanks Kimora)

[https://www-chronicle-com.csi.ezproxy.cuny.edu/article/columbia-capitulated-but-so-did-the-rest-of-higher-ed](https://www-chronicle-com.csi.ezproxy.cuny.edu/article/columbia-capitulated-but-so-did-the-rest-of-higher-ed)


> "Unless higher education discovers its collective nerve and collective voice, those who “threaten the very mission of the university and its values of free inquiry” will get precisely what they want. And if it allows such a thing to happen without putting up more of a fight in defense of its mission and social purpose, higher education — it deeply pains me to acknowledge — will get what it deserves."

> This is why all our statements on academic freedom are important. My hope is that they give our political and university leaders some pause before they violate academic freedom as easily as they recently did at Hunter. Moreover, they show how each governing body is dealing with the challenges to higher education, and thus preparing their constituents for the challenges to come.

(Thanks EI)

* NYTimes: University of Michigan to Scuttle Its Flagship D.E.I. Program

[https://www.nytimes.com/2025/03/27/education/university-of-michigan-dei.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/03/27/education/university-of-michigan-dei.html?smid=nytcore-ios-share&referringSource=articleShare)
## Un-bent knee

* How a University Fights an Authoritarian Regime

[https://www.chronicle.com/article/how-a-university-fights-an-authoritarian-regime](https://www.chronicle.com/article/how-a-university-fights-an-authoritarian-regime)

> Make the case to the public that these attacks are senseless assaults on institutions that promote what America is famous for: life-saving science and world-class innovation.

> At CEU we framed Orbán’s attack as an affront to academic freedom in Europe, indeed the most serious one since the 1930s.

> Faced with *Kulturkampf* waged by a ferociously ideological administration intent on neutralizing academe as a critical voice, university presidents will be inclined to hunker down and wait for the storm to pass. But it may not pass. Even if it does, the universities that survive may be weakened, frightened shadows of their former selves.

* NYTimes: ‘This Is Worse’: Trump’s Judicial Defiance Veers Beyond the Autocrat Playbook

[https://www.nytimes.com/2025/03/20/world/europe/trump-courts-defiance-autocrats-playbook.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/03/20/world/europe/trump-courts-defiance-autocrats-playbook.html?smid=nytcore-ios-share&referringSource=articleShare)

(While not about higher education, this article compares the Trump Adminstrations to other autocratic regime's approach to capturing the judicial system.)

> “We look at these comparative cases in the 21st century, like Hungary and Poland and Turkey. And in a lot of respects, this is worse,” he said. “These first two months have been much more aggressively authoritarian than almost any other comparable case I know of democratic backsliding.”

* Trump can’t fix American universities by breaking them

[https://wapo.st/4bOsq9T](https://wapo.st/4bOsq9T)

> Florida pioneered the kind of crackdown the Trump administration is attempting, and now more left-leaning students and professors in that state have begun describing exactly the kind of speech-chilling atmosphere that conservatives have been complaining about for years. Professors there have steered students away from discussing topics that seem forbidden, including “intersectionality,” and are afraid that students are recording them, the Wall Street Journal has reported. Students voiced similar fears that classmates would broadcast their remarks on social media, and one student publication trimmed its coverage to protect its funding


* NYTimes: $15 Billion Is Enough to Fight a President

[https://www.nytimes.com/2025/03/25/opinion/trump-university-endowment-spending.html](https://www.nytimes.com/2025/03/25/opinion/trump-university-endowment-spending.html)

> Thus far, university presidents have largely kept their heads down rather than uniting to oppose Mr. Trump’s assault. That is a mistake. A key authoritarian strategy is to single out prominent individuals or institutions for repression so that others, afraid, forgo legitimate criticism of the authoritarian leader. Often, universities are some of the first institutions that authoritarians attack. Make no mistake, the Trump administration’s punitive cuts to federal research grants and detention of university students or faculty, couched under the President’s grievances over diversity programs and campus protests, are early signs of this strategy at work in America.


* Legal scholars on what Columbia University should have done — and what other colleges could do next.

[https://www.chronicle.com/article/it-is-remarkable-how-quickly-the-chill-has-descended](https://www.chronicle.com/article/it-is-remarkable-how-quickly-the-chill-has-descended)

> with the exceptions of the presidents of Brown and Princeton, the leadership of academia has been pretty much absent; everyone is taking a duck-and-cover attitude. So Armstrong [Columbia's President] felt she was on her own. That’s my most sympathetic read, even though I wish she had taken a firmer stand.

>  So there’s this very rational cost-benefit analysis where administrators are thinking, “Well, if we speak up and others do not …” It’s a collective-action problem in which, in the moment, it’s always easier not to speak. This is why we have free-speech protections — speech is easily chilled. It is remarkable how quickly the chill has descended.

> A less sympathetic reading: My sense of what was motivating both the Paul Weiss and Columbia leadership is a view that the concessions being demanded were not very significant.

> That in itself is a significant indication of where we are. I’ve been reading all the free-speech policies at different schools. There’s lovely language in the policies about how universities are sites of dissent and how protest is meant to be valued. About how we want to give our students the freedom to question what is in the classroom and what’s outside the classroom. Chicago has a wonderful statement written by David Strauss, who was the head of the ad-hoc committee on protest and dissent, in which he says protest is not only integral to the life of the university because we are a community of dissent, but administrators should strive to problem-solve. So when students break the rules, don’t use discipline. Try to figure out what the cause of their concern is. Since October 7, there has been a demise of that kind of talking and that kind of imagining.

> It feels like we are saying goodbye to this beautiful democratic vision of the university and we are now thinking of the university as a place where order must be maintained.

* This Time, Higher Ed’s Resistance to Trump is Being Led by Its Associations

[https://www.chronicle.com/article/this-time-higher-eds-resistance-to-trump-is-being-led-by-its-associations](https://www.chronicle.com/article/this-time-higher-eds-resistance-to-trump-is-being-led-by-its-associations)

(The board of ACE is chaired by CUNY's Chancellor.)

> in opening remarks at ACE’s annual conference, Mitchell [ACE's President] condemned Trump’s actions in unusually strong words. “The flurry of these threats,” he said, “were designed to cow us into silence. When we face threats, we will not cower.”

> To Todd Wolfson, president of the AAUP, doing so [joining a lawsuite] was a necessity. “It’s our job to protect our members and to protect their places of employment and their sector,” he said. “If somebody wants to argue with me that’s not the role of unions and associations, I’d love to hear it. But I think this is a fundamental duty of ours, if not the fundamental duty.”

* NYTimes: David Leonhardt on How Universities Can Stop Trump’s ‘Destroying Agenda’

[https://www.nytimes.com/2025/03/27/opinion/universities-trump-fight-back.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/03/27/opinion/universities-trump-fight-back.html?smid=nytcore-ios-share&referringSource=articleShare)


> Leonhardt: It’s important to say that a lot of the conservative critics of universities, including Christopher Rufo, also don’t want a fully open debate. They want to restrict debate in many cases so that it’s just their view of the world. They want to take books out of schools about L.G.B.T. people. That’s really damaging.

> A world in which Donald Trump’s ideological enforcers are going through a course catalog or telling schools exactly what their admissions policies need to be, rather than letting schools follow the Supreme Court ruling on it, would be a really damaging world.

> I think we’re on track at a lot of universities and also law firms and other institutions that you’ve written about where people are going to say: Well, can I make a deal with Trump or can I keep my head down and stay out of the line of fire? Maybe not appreciating that this guy and the people around him like Chris Rufo are on a war footing.

* Dear Colleagues: The Time for Boldness Is Now

[https://www.insidehighered.com/opinion/views/2025/03/27/letter-faculty-self-censorship-and-boldness-opinion](https://www.insidehighered.com/opinion/views/2025/03/27/letter-faculty-self-censorship-and-boldness-opinion)

> I do not deny that we are living in perilous times, but what good are academic freedom and tenure if we do not use them? Some think, I believe mistakenly, that speaking out will only embolden the attacks on higher education institutions and faculty. I, instead, am more compelled by Frederick Douglass’s proclamation, "Find out just what any people will quietly submit to and you have found out the exact measure of injustice and wrong which will be imposed upon them, and these will continue till they are resisted …”



## Deportations

* NYTimes: U.S. Lodges New Accusations Against Detained Columbia Protest Leader

[https://www.nytimes.com/2025/03/23/nyregion/mahmoud-khalil-trump-allegations.html](https://www.nytimes.com/2025/03/23/nyregion/mahmoud-khalil-trump-allegations.html)

> The Trump administration appears to be using the new allegations in part to sidestep the First Amendment issues raised by Mr. Khalil’s case. On Sunday, in a filing opposing his release, Justice Department lawyers argued that the new allegations reduced the importance of concerns about Mr. Khalil’s right to free speech.


## Coming attractions

* How an Accreditation War Could Start

[https://www.chronicle.com/article/how-an-accreditation-war-could-start](https://www.chronicle.com/article/how-an-accreditation-war-could-start)

> Now President Trump threatens to wield accreditation as a weapon, something which, if carried out, would muzzle the creativity and innovation that has fueled America’s lead.

> What stands in Trump’s way? The federal law establishing the Department of Education prohibits federal interference in curricular matters. That federal law would change, however, if the department is eliminated.

> Another obstacle is the First Amendment: If the administration were to directly attack accreditors’ opinions or academic perspectives, they would expose themselves to legal challenges. The administration could respond to this by claiming a national-security concern (say, holding that diversity, equity, and inclusion are part of a Marxist threat to America).



----

If you have stories you would like me to include in anticipated future digests, please send along via an email to me directly (john.verzani@csi.cuny.edu).
