# May 23

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

As BE said: "The quantity of higher ed related reporting and the speed with which this is all happening can take your breath away."

Thanks to VAC, MP, EI, and BE for sharing articles.

Sorry this is a day off, but we wouldn't have got to see the full cycle of sabotage of Harvard through international students: starting with a stated block on visas for international students, to our collective uttering "that must be illegal", to a lawsuit by Harvard, to a judicial block.

## Letters

* From Lehman College

[https://docs.google.com/document/d/1TBPqh7pH3javF_m7s4T2sf6JU-YI0nP0/edit](https://docs.google.com/document/d/1TBPqh7pH3javF_m7s4T2sf6JU-YI0nP0/edit)

> We are writing to express deep concern regarding recent administrative and policy decisions at the National Science Foundation (NSF) that threaten to destabilize the U.S. scientific enterprise and undermine the principles of excellence, equity, and innovation that have long guided our national investment in STEM research and education.


> Thank you for your attention to these pressing issues and for your ongoing commitment to American science and innovation.  The signatories below represent a wide range of STEM disciplines and institutions.  If you have any questions or would like additional information, please contact Esther Isabelle Wilder (Esther.Wilder@lehman.cuny.edu) at Lehman College of the City University of New York.

(Thanks MP. I signed personally as chair)

## Alliances

* Medger Evers and CUNY Law pass resolutions adopting a attached mutual defense compact.

## Statements

* ACE, Others Call on Trump Administration to Reforge Compact with Higher Education

[https://www.acenet.edu/News-Room/Pages/ACE-Others-Trump-Admin-Reforge-Compact-Higher-Ed.aspx](https://www.acenet.edu/News-Room/Pages/ACE-Others-Trump-Admin-Reforge-Compact-Higher-Ed.aspx)

## How best to describe the times we are in

(This week I'm going with the Mob description)

## Academic freedom

* NYTimes: The Group Behind Project 2025 Has a Plan to Crush the Pro-Palestinian Movement

[https://www.nytimes.com/2025/05/18/us/project-esther-heritage-foundation-palestine.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/18/us/project-esther-heritage-foundation-palestine.html?smid=nytcore-ios-share&referringSource=articleShare)

(This article discusses the engineered backlash against protesters by the Heritage Foundation using federal funding as the cudgel. That idea has found quite wide use)

> Now the Heritage contingent was in Israel, in part, to discuss another contentious policy paper: Project Esther, the foundation’s proposal to rapidly dismantle the pro-Palestinian movement in the United States, along with its support at schools and universities, at progressive organizations and in Congress.

> Drafted in the wake of Hamas’s attack on Israel in 2023 and the mounting protests against the war in Gaza, Project Esther outlined an ambitious plan to fight antisemitism by branding a broad range of critics of Israel as “effectively a terrorist support network,” so that they could be deported, defunded, sued, fired, expelled, ostracized and otherwise excluded from what it considered “open society.”

> Project Esther’s architects envisioned outcomes that at the time might have seemed far-fetched. Curriculum it believed to be sympathetic to a “Hamas support” narrative would be taken out of schools and universities, and “supporting faculty” would be removed. Social media would be purged of content deemed to be antisemitic. Institutions would lose public funding. Foreign students who pushed for Palestinian rights would have their visas revoked, or be deported.

> Heritage national security director who coauthored Project Esther, said it was “no coincidence that we called for a series of actions to take place privately and publicly, and they are now happening.”

> But Project Esther aims to go further, equating actions such as participating in pro-Palestinian campus protests with providing “material support” for terrorism, a broad legal construct that can lead to prison time, deportations, civil penalties and other serious consequences.

> “Project Esther changed the paradigm by associating anyone who opposes Israeli policies with the ‘Hamas Support Network,’”

> Some evangelical Christians have increasingly aligned themselves with conservative political forces in Israel, supporting their claims of biblical dominion over contested Palestinian territories. Many feel a kinship with Israel because of shared religious heritage. But some also believe that supporting Israel will hasten biblical end times, or advance Christianity’s global influence.

* The Visionary of Trump 2.0 - The Atlantic

[https://www.theatlantic.com/politics/archive/2025/05/russell-vought-trump-doge/682821/](https://www.theatlantic.com/politics/archive/2025/05/russell-vought-trump-doge/682821/)

(Russel Vought takes over for Elon Musk in efforts to kill this federal government. But he is more patient and will have a longer impact)

One example is "[https://www.wired.com/story/cfpb-quietly-kills-rule-to-shield-americans-from-data-brokers/](https://www.wired.com/story/cfpb-quietly-kills-rule-to-shield-americans-from-data-brokers/)


* Trump’s Attacks on International Students Are the Start of a Wider War | The New Republic

[https://newrepublic.com/article/195142/trump-war-international-students-university](https://newrepublic.com/article/195142/trump-war-international-students-university)

> In recent months, foreign students—particularly those participating in pro-Palestine protests—have had their student visas threatened or have been detained and placed in deportation proceedings, signaling a sharp and politically charged shift in federal policy. At the same time, public and private research universities, which depend heavily on international students’ tuition and labor—especially in science, technology, engineering, and mathematics disciplines—are facing the erosion of a vital economic pillar. These developments threaten not only the foundational rights of free speech and academic freedom but also the financial stability of the institutions that anchor the U.S. higher education system and conduct the vital research on which the future will be built.

> Far from isolated incidents, these cases reflect an emerging strategy—leveraging immigration enforcement as a tool of political suppression. International students have become an ideal scapegoat: politically vulnerable, culturally diverse, and often outspoken. Immigration officials now claim broad authority to revoke visas for “supporting terrorism,” using vague, expansive definitions. The result is a chilling effect on campus expression and a stark warning to those who would protest U.S. policy.

> For academic leaders like Todd Wolfson, president of the American Association of University Professors, the strategy is transparent. “They want to undermine higher education and also heighten the new Cold War on campus,” Wolfson said.


Is the University Of Austin Betraying Its Founding Principles?

[https://quillette.com/2025/05/16/is-the-university-of-austin-betraying-its-founding-principles/](https://quillette.com/2025/05/16/is-the-university-of-austin-betraying-its-founding-principles/)

* Skilled immigration on the chopping block? Effects of eliminating "Optional Practical Training" in the US | PIIE


[https://www.piie.com/blogs/realtime-economics/2025/skilled-immigration-chopping-block-effects-eliminating-optional](https://www.piie.com/blogs/realtime-economics/2025/skilled-immigration-chopping-block-effects-eliminating-optional)

> That may soon change. The US administration is under pressure to constrict or eliminate the largest single pipeline into lawful immigration for high-skilled, university-educated workers. This pipeline is called Optional Practical Training (OPT)—a temporary work permit given to some foreign graduates of US universities.

> Optional Practical Training is a federal program that allows most international students at US universities the choice to work in the United States for a limited period after they graduate. About 72 percent of foreign graduates use OPT. The permit generally lasts one year but extends to three years for graduates at any educational level in science, technology, engineering, and mathematics (STEM). It is a work permit attached to the student visa, a bridge between university enrollment and the workforce, granted under regulations starting in 1947.

* We Don’t Need More Administrators Inspecting Our Ideas

[https://www.chronicle.com/article/we-dont-need-more-administrators-inspecting-our-ideas](https://www.chronicle.com/article/we-dont-need-more-administrators-inspecting-our-ideas)

> This [expecting a renaissance of rich controversies], of course, is politically naïve. As the historian of science Michael Hagner predicted in 2019, the commitment of right-wing populists to epistemic pluralism only lasts until they manage to establish their own views well enough to eliminate all other points of view. Consider book bans, grant cancellations, and the violation of the First Amendment rights of foreign students and faculty and you will find validated Hagner’s cynical perspective on the authoritarian promotion of viewpoint diversity.

> Both Harding and Haidt put their fingers on a very real problem: Our collective thinking benefits from looking at any given issue from multiple angles. For all sorts of historical reasons, colleges often do not represent a spectrum that is broad enough.

> This balancing act requires what Aristotle called phronesis, the capacity for good judgment, and it cannot be formalized through viewpoint-diversity audits and affirmative-action policies.

## Freedom of expression

* With Comey questioning, the Trump administration again targets speech

[https://www.washingtonpost.com/politics/2025/05/17/trump-freedom-of-speech-critics/](https://www.washingtonpost.com/politics/2025/05/17/trump-freedom-of-speech-critics/)

(Just 4 numbers is enough now...)

* College newspapers under pressure as immigration fears silence sources

[https://www.washingtonpost.com/education/2025/05/17/college-newspapers-trump-international-students/](https://www.washingtonpost.com/education/2025/05/17/college-newspapers-trump-international-students/)

* Free speech is dead at the American university. Here’s who killed it.

[https://www.inquirer.com/opinion/commentary/free-speech-american-universities-20250518.html](https://www.inquirer.com/opinion/commentary/free-speech-american-universities-20250518.html)

(Sorry, I thought this was a gift link)

* Free Speech Expert Discusses Open Expression and Trump

[https://www.insidehighered.com/news/students/free-speech/2025/05/21/free-speech-expert-discusses-open-expression-and-trump](https://www.insidehighered.com/news/students/free-speech/2025/05/21/free-speech-expert-discusses-open-expression-and-trump)

> 1. What are your biggest concerns with regard to the Trump administration and free speech and open expression in higher ed right now?

> Well, sadly, there’s kind of a long list. I think, from my vantage point, one of the greatest concerns is seeing students, and particularly international students, being, basically, taken away on what appears to be the basis of viewpoints and opinions that they might have shared, either in the form of protest or, in one case, an op-ed. That really flies in the face of exactly what the First Amendment is supposed to protect against, especially in a public institution, which is that it’s supposed to be a restraint on government.

### Anti-woke/anti-DEI is simply racism

* NYTimes: Times Sq. Sculpture Prompts Racist Backlash. To Some, That’s the Point.

[https://www.nytimes.com/2025/05/18/nyregion/times-square-black-woman-statue.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/18/nyregion/times-square-black-woman-statue.html?smid=nytcore-ios-share&referringSource=articleShare)

* NYTimes: Justice Dept. to Use False Claims Act to Pursue Institutions Over Diversity Efforts

[https://www.nytimes.com/2025/05/19/us/politics/false-claims-act-dei-harvard.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/19/us/politics/false-claims-act-dei-harvard.html?smid=nytcore-ios-share&referringSource=articleShare)

(Thanks VAC)

> “Institutions that take federal money only to allow antisemitism and promote divisive D.E.I. policies are putting their access to federal funds at risk,” Attorney General Pam Bondi said in a statement. “This Department of Justice will not tolerate these violations of civil rights — inaction is not an option.”


## ICE

* NYTimes: Judge Blocks Trump Administration From Revoking Student Visas

[https://www.nytimes.com/2025/05/22/us/politics/trump-international-student-visas.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/22/us/politics/trump-international-student-visas.html?smid=nytcore-ios-share&referringSource=articleShare)

> Judge Jeffrey S. White of the Northern District of California, who was appointed to the court by President George W. Bush, granted a temporary injunction protecting international students who were among the thousands whose visas were revoked earlier this year without clear justification, writing that government officials had “uniformly wreaked havoc” and “likely exceeded their authority and acted arbitrarily and capriciously” by the mass revocation of students’ immigration status.

> Judge White’s ruling said that the order applied to all “similarly situated individuals” who participate in the Student and Exchange Visitor Program, which is the system governing student visas. In the order, he expressed suspicion that the Trump administration was trying to place future visa “terminations beyond judicial review.”

## Funding cuts

* NYTimes: Trump Has Cut Science Funding to Its Lowest Level in Decades

[https://www.nytimes.com/interactive/2025/05/22/upshot/nsf-grants-trump-cuts.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/interactive/2025/05/22/upshot/nsf-grants-trump-cuts.html?smid=nytcore-ios-share&referringSource=articleShare)

(With a great graphic. Between less money and smaller overheads, the whole research enterprise is about to topple. These cuts are not isolated, as they will lead to shared burdens system wide.)


* ‘Every Revenue Source Is at Risk’: Under Trump, Research Universities Are Cutting Back

ttps://www.chronicle.com/article/every-revenue-source-is-at-risk-under-trump-research-universities-are-cutting-back

> At the University of Washington, where state budget cuts have collided with what administrators described as an “unstable and chaotic federal policy and funding landscape,” college leaders called for a reduction in core budgets by an average of 4.7 percent in the fiscal year starting July 1. “It is almost impossible to imagine a scenario in which layoffs will not be necessary,” college leaders wrote in a message to the university community.

> Meanwhile, Michigan State University plans to lower general-fund spending by 9 percent over the next two years, according to The State News, citing a memo by President Kevin Guskiewicz.


> Other institutions that have announced potential or actual budget cuts in recent weeks include Oregon State University, which set a universitywide target of reducing spending by 5.2 percent, effective July 1,

> Kelchen said that while universities in blue states have been most vocal about the need to slash budgets, those in red states are likely planning behind the scenes to reduce spending, but staying quiet for fear of potential retribution by trustees or state policymakers.

* Republicans’ Plan to Tax Higher Ed and Slash Funding Advances in Congress

[https://www.chronicle.com/article/republicans-plan-to-tax-higher-ed-and-slash-funding-advances-in-congress](https://www.chronicle.com/article/republicans-plan-to-tax-higher-ed-and-slash-funding-advances-in-congress)

> But the legislation will also harm low-income students everywhere, the American Council on Education (ACE) argued.

[https://www.acenet.edu/Documents/Letter-House-Reconciliation-052125.pdf](https://www.acenet.edu/Documents/Letter-House-Reconciliation-052125.pdf)

> The totality of the funding cuts, policy changes, and tax increases included in this reconciliation package will have a historic and negative impact on the ability of current and future students to access postsecondary education, as well as on colleges and universities striving to carry out their vital educational and research missions. In particular, we are concerned about the damaging proposed changes to student aid programs, including eligibility changes that will prevent many low-income students from accessing Pell Grants; the availability of federal student loans for graduate students; new and increased taxes imposed on our institutions of higher education; and significant cuts to other programs supporting millions of postsecondary students nationwide.

* NYTimes: Republicans Harness Tax Code to Punish Trump’s Political Nemeses

[https://www.nytimes.com/2025/05/23/us/politics/republicans-taxes-trump-opponents.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/23/us/politics/republicans-taxes-trump-opponents.html?smid=nytcore-ios-share&referringSource=articleShare)

> The legislation, which could change as it heads to the Senate, would raise taxes on universities like Harvard, as well as on immigrants and on companies based in countries with taxes that the Trump administration deems unfair.

> “If you’re an ideological friend of Trump, you’re in generally good shape,” said William Gale, a co-director of the Tax Policy Center, a think tank. “If you’re an ideological foe, you pay more.” The increases, he added, “feel very punitive.”

> While the tax [investment returns generated by their endowments] would represent a huge new cost for Harvard and other affected schools, it would raise less than $7 billion in government revenue over 10 years — a pittance compared with the trillions in tax cuts otherwise included in the bill.

### NSF

* NSF terminates huge number of grants and stops awarding new ones

[https://www.nature.com/articles/d41586-025-01513-1](https://www.nature.com/articles/d41586-025-01513-1)

(A podcast. Thanks MP)

### NIH

(I must have missed something here)

### NEH

* Will federal funding cuts spell the end for history documentaries?


[https://www.washingtonpost.com/style/2025/05/20/neh-grants-canceled-history-documentaries/](https://www.washingtonpost.com/style/2025/05/20/neh-grants-canceled-history-documentaries/)



### DOE

* McMahon Plays Defense on the Hill

[https://www.insidehighered.com/news/government/politics-elections/2025/05/22/mcmahon-defends-education-cuts-budget-hearing](https://www.insidehighered.com/news/government/politics-elections/2025/05/22/mcmahon-defends-education-cuts-budget-hearing)

(Thanks VAC)

> Secretary of Education McMahon, Trump loyalist, spouts Trumpline on why destroying Department of Education is necessary through massive cuts that will effectively dismantle agency and disproportionately harm working-class and students of color throughout the country.


> "As the hearing went on, Democrats grew increasingly frustrated at McMahon’s unflinching defense of the Trump administration’s proposed elimination of most of her own department. One exchange escalated when Pennsylvania Democratic representative Madeleine Dean, who was just appointed to the committee in January, repeatedly interrupted McMahon to ask why she “didn’t want to protect students” of color, with disabilities or from low-income families.

> “Why in God’s name do you want to shutter [the Education Department]?” she asked, exasperated. “Why are you in this job at all if you don’t have a dedication to the future of our children? Why?”

* Judge blocks Trump bid to dismantle Department of Education

[https://www.politico.com/news/2025/05/22/education-department-court-ruling-firings-00365170](https://www.politico.com/news/2025/05/22/education-department-court-ruling-firings-00365170)

> The judge said the administration’s planned reductions were clearly aimed at carrying out Trump’s campaign-trail promise to eliminate the department altogether.

(As well)

[https://apnews.com/article/education-department-shut-down-layoffs-576eef90c30fdaeb660f7f66644bad10](https://apnews.com/article/education-department-shut-down-layoffs-576eef90c30fdaeb660f7f66644bad10)

[https://www.washingtonpost.com/education/2025/05/22/education-department-fired-federal-workers-reinstated/](https://www.washingtonpost.com/education/2025/05/22/education-department-fired-federal-workers-reinstated/)


## Institutional assaults

### Harvard

(Harvard deserves special recognition for fighting back, as the assault if ferocious. They have been around longer than this country and will survive this with its values intact.)

* NYTimes: Trump’s Push to Defund Harvard Prompts Clash Over Veteran Suicide Research

[https://www.nytimes.com/2025/05/16/us/politics/trump-harvard-veterans-research.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/16/us/politics/trump-harvard-veterans-research.html?smid=nytcore-ios-share&referringSource=articleShare)

> Peter Kasperowicz, a V.A. spokesman, said that the department’s research contracts with Harvard were “under review.” He said the goal of the review was to ensure that “the projects best support the Trump administration’s veterans-first agenda.”

> The dispute among officials at the Department of Veterans Affairs has focused in part on a collaboration with Harvard Medical School to develop a predictive model to help V.A. emergency room physicians decide whether suicidal veterans should be hospitalized, according to the records.

* Feds yank funds from Harvard breast cancer, fertility, antibiotics research | WBUR News

[https://www.wbur.org/news/2025/05/16/harvard-medical-research-trump-2-7-billion-cuts](https://www.wbur.org/news/2025/05/16/harvard-medical-research-trump-2-7-billion-cuts)



* NYTimes: Education Secretary Wants Talks With Harvard to Resume, Without Giving Ground

[https://www.nytimes.com/2025/05/17/us/politics/linda-mcmahon-harvard-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/17/us/politics/linda-mcmahon-harvard-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> “It’s a little bit hard to have open negotiations when we’ve got a lawsuit pending,” Ms. McMahon said in an interview on Friday. “When you’re sitting and talking, do you have to have all your lawyers present, do all those things to make sure you’re not compromising the lawsuit? That’s kind of stuff I’d have to have the lawyers respond to as well.”

(Boo hoo)

* Trump administration pulls $60M in Harvard grants in third round of cuts

[https://www.washingtonpost.com/education/2025/05/20/harvard-hhs-us-grants-antisemitism/](https://www.washingtonpost.com/education/2025/05/20/harvard-hhs-us-grants-antisemitism/)

* NYTimes: All the Actions the Trump Administration Has Taken Against Harvard

[https://www.nytimes.com/2025/05/22/us/politics/harvard-university-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/22/us/politics/harvard-university-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

(From Thursday AM; and now .. Thursday PM)

* NYTimes: Trump Administration Halts Harvard’s Ability to Enroll International Students

[https://www.nytimes.com/2025/05/22/us/politics/trump-harvard-international-students.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/22/us/politics/trump-harvard-international-students.html?smid=nytcore-ios-share&referringSource=articleShare)

Also

[https://www.chronicle.com/article/trump-administration-revokes-harvards-ability-to-enroll-international-students](https://www.chronicle.com/article/trump-administration-revokes-harvards-ability-to-enroll-international-students)

* Harvard’s International Students Are People — Not Pawns

[https://www.thecrimson.com/article/2025/5/23/harvard-international-students-trump/](https://www.thecrimson.com/article/2025/5/23/harvard-international-students-trump/)

(Thanks EI who finds this salient quote:)

> "If higher education — and the rest of American civil society — doesn’t stand with Harvard’s international students now, they may find themselves alone when Trump comes for them next."

* Harvard sues Trump administration to protect international students

[https://www.washingtonpost.com/education/2025/05/23/harvard-lawsuit-international-students-trump-administration/](https://www.washingtonpost.com/education/2025/05/23/harvard-lawsuit-international-students-trump-administration/)

* NYTimes: Judge Blocks Trump Effort to Bar International Students at Harvard

[https://www.nytimes.com/2025/05/23/us/harvard-sues-trump-international-students-garber.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/23/us/harvard-sues-trump-international-students-garber.html?smid=nytcore-ios-share&referringSource=articleShare)

* NYTimes: Harvard Derangement Syndrome

[https://www.nytimes.com/2025/05/23/opinion/harvard-university-trump-administration.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/23/opinion/harvard-university-trump-administration.html?smid=nytcore-ios-share&referringSource=articleShare)

(Excellent overview of Harvard culture and efforts by Steven Pinker. Long story quite short:)

> The concern for Jews is patently disingenuous, given Mr. Trump’s sympathy for Holocaust deniers and Hitler fans. The obvious motivation is to cripple civil society institutions that serve as loci of influence outside the executive branch.

* Is Trump Trying to Destroy Harvard? - WSJ

[https://www.wsj.com/opinion/donald-trump-harvard-dhs-foreign-students-kristi-noem-b8ac80ed](https://www.wsj.com/opinion/donald-trump-harvard-dhs-foreign-students-kristi-noem-b8ac80ed)

(Uhh, yes)

### Columbia

* Trump administration says Columbia violated Jewish students’ civil rights

[https://www.washingtonpost.com/education/2025/05/23/columbia-university-trump-administration/](https://www.washingtonpost.com/education/2025/05/23/columbia-university-trump-administration/)

> In October 2023, a swastika was found drawn on a bathroom wall at the university, according to the Columbia Spectator, the school newspaper. But there have been instances in which antisemitic images from earlier periods have been erroneously linked to the more recent pro-Palestinian protests at Columbia.

> The announcement comes as the Trump administration is engaged in negotiations with Columbia over federal funding. The administration cut $400 million in contracts and grants to the school in March, saying the university had failed to sufficiently clamp down on acts of antisemitism on its campus.

(Just guessing, but that 400 number will seem quaint)

## The long game

* America and Its Universities Need a New Social Contract - The Atlantic

[https://www.theatlantic.com/ideas/archive/2025/04/stem-academia-universities-citizenship-civics/682384/](https://www.theatlantic.com/ideas/archive/2025/04/stem-academia-universities-citizenship-civics/682384/)

>  We must do what should have been done long ago: find our way to a new social contract between universities and the American people.

* Liner Note 25. The Next 100 Days: Don’t Make the Trump Damage Worse (Thanks VAC)

[https://utotherescue.blogspot.com/2025/05/liner-note-25-next-100-days-dont-make.html](https://utotherescue.blogspot.com/2025/05/liner-note-25-next-100-days-dont-make.html)

> Trump’s opening blitzkrieg has happened, the first defenses are in place, and the colossal damage has been done.  What are the university system’s next moves?

(Of these, CUNY is doing all of these; but this listing of the ten-dimensional fiscal risk is interesting:

> Blanket reductions of indirect cost recovery funds...  Cancellation of existing grants... Reduced awarding of grants ... Freezing of awarded grants. ...Non-allocation of funds for awarded and uncancelled grants ...Retaliatory bulk funding impounding at targeted universities...  Cuts to student-related federal funding.... Cuts to Medicaid and other programs

* NYTimes: On Education, DeSantis’s Florida Paved the Way for Trump’s America

[https://www.nytimes.com/2025/05/19/us/education-desantis-florida-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/19/us/education-desantis-florida-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> “Far be it for President Trump to be so foolish as to ignore a good idea,” said Tiffany Justice, a founder of Moms for Liberty, the right-wing parental-rights group that was key in shaping Mr. DeSantis’s agenda in Florida.

(In one sentence, the actions of a president, governor, and fringe group head are sanewashed.)

* NYTimes: 13 Ways to Save Health and Science

[https://www.nytimes.com/2025/05/19/opinion/save-health-science-climate.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/19/opinion/save-health-science-climate.html?smid=nytcore-ios-share&referringSource=articleShare)

> 5. Lean on other scientists. Brandon Jones, president of the American Geophysical Union: Scientific societies — professional organizations that represent researchers in specific fields — have a long history of stepping in when politics interferes with research. After the Trump administration suspended work in April on the U.S. government’s flagship report on the impacts of climate change, the American Geophysical Union and the American Meteorological Society partnered with plans to publish some of the research so the public can still access the findings.

> 7. Create a mini N.I.H. Andrew Marks, professor of physiology at Columbia University: We need a new funding model for science research. I propose the creation of the American Research Collaborative, a kind of mini-National Institutes of Health that could provide funding for universities. The A.R.C. would be led by a governing board elected by member organizations like the American Heart Association, the American Cancer Society and the Howard Hughes Medical Institute. Universities could opt in, and the collaborative’s tax-exempt status would attract private donors. a

> 11. Build new alliances. Dr. Jane Lubchenco, co-founder of United by Nature: In January, over 100 scientists outside the federal government were struggling to come to grips with the administration’s cancellation of years of work on what would have been the first ever federal assessment of nature. We refused to quit. So we created a new path to deliver the report and show why the information matters. The initiative, called United by Nature, will have a governing body, advisers and partners, independent peer review and extensive public engagement.

* NYTimes: The President Will Destroy You Now

[https://www.nytimes.com/2025/05/20/opinion/trump-musk-doge-government.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/20/opinion/trump-musk-doge-government.html?smid=nytcore-ios-share&referringSource=articleShare)

> The war on academic research will have long-lasting implications for technical innovation in America. Scientists who cannot support their labs while President Trump holds their funds hostage for the sake of MAGA theater over the next four years will take their labs elsewhere.

> China will be a winner in this. Uncertainty about government commitments will make it harder for investors to take basic and applied research in universities and move it to market. The longer the time horizon for investments, the more trust and stability matter. In the end, disrupters like Trump and Musk leave us with a much bigger legacy of doubt and uncertainty than achievement.

* Most Colleges Aren’t a Target of Trump (Yet). Here’s How Their Presidents Are Leading.


[https://www.chronicle.com/article/most-colleges-arent-a-target-of-trump-yet-heres-how-their-presidents-are-leading](https://www.chronicle.com/article/most-colleges-arent-a-target-of-trump-yet-heres-how-their-presidents-are-leading)

> Still, campus leaders at community colleges and four-year public regional and private institutions — representing the vast majority of higher ed — say they do see impacts of Trump’s policies. Fear, particularly about the future of financial aid and immigration crackdowns, is pervasive.

> But the college [Delta] is also planning for contingencies. “If somehow the government is going to withhold federal financial-aid dollars going to students based on something,” Gavin said, “then that will be where we have to change.”

> David Tandberg, president of Adams State University, said he has tried to sort the administration’s actions into several buckets based on whether they would have a direct impact on his campus — a public regional institution in rural, southern Colorado — and whether they’re probably just rhetoric. “We’re seeing all of those, and it takes a lot to sort through them,” Tandberg said. “The first month it was coming like a fire hose.”

> Similar to Delta College, an urgent concern for a university like Adams State is whether federal cuts could slow or stop the flow of student financial aid,

## Blowback

* At universities from the Ivy League to state schools, a financial reckoning has started as President Trump’s funding cuts hit home

[https://www.wsj.com/us-news/education/university-spending-cuts-layoffs-pay-budget-trump-9f261d14?st=ErRuU9&reflink=article_gmail_share](https://www.wsj.com/us-news/education/university-spending-cuts-layoffs-pay-budget-trump-9f261d14?st=ErRuU9&reflink=article_gmail_share)

* NYTimes: Republican Plan to Tax Elite Colleges Could Hit in Unexpected Places

[https://www.nytimes.com/2025/05/20/us/universities-endowment-tax-republicans.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/20/us/universities-endowment-tax-republicans.html?smid=nytcore-ios-share&referringSource=articleShare)

> The goal of the proposal, laid out in a report last week from Republicans on the House Ways and Means Committee, is to hold accountable “woke, elite universities that operate more like major corporations.” McPherson [small school that accepts the vast majority of its applicants] could be on the list because it has an endowment of $1.6 billion, thanks to an anonymous donation a few years ago.

(Don't cry for McPherson, cry that this stealing from the rich to give to the richer is even being proposed.)

* Chinese College Gives Harvard International Students 'Unconditional Offers' - Newsweek

[https://www.newsweek.com/harvard-hkust-china-college-international-students-offer-2076257](https://www.newsweek.com/harvard-hkust-china-college-international-students-offer-2076257)

## Coming attractions?

* How I Lost Faith in My University’s Mission

[https://www.insidehighered.com/opinion/views/2025/05/19/how-i-lost-faith-my-universitys-mission-opinion](https://www.insidehighered.com/opinion/views/2025/05/19/how-i-lost-faith-my-universitys-mission-opinion)

(Look at all the interventions from outside that have happened at the University of Utah)

> the State Legislature passed an anti-DEI bill, prohibiting, among other things, offices and programs related to diversity, equity or inclusion. Administrators were required to purge these three words from university websites and other documents, such as RPT—retention, promotion and tenure review—guidelines, and the university administration interpreted the law as requiring that the Women’s Resource Center, the Black Cultural Center and the LGBT Resource Center be shuttered.

> The state has also imposed a “bathroom bill” requiring trans university students to use locker rooms aligning with their sex assigned at birth, has banned Pride flags in public spaces (and in faculty offices if they can be seen through a window), and now requires faculty to post their syllabi in a publicly searchable database. It also prohibits university presidents from taking a stand on any issue that does not bear upon the “mission, role or pedagogical objectives” of the institution. And finally, as the coup de grâce for academic freedom and faculty expertise, it has funded and established the Center for Civic Excellence at Utah State University, mandating that all students take general education courses on the topics of Western civilization and the rise of Christianity. The law establishing the center identifies it as a pilot program to be rolled out to other Utah universities in the future.

> Recently passed laws dictate the process by which all post-tenure reviews of faculty must be conducted, curtail shared governance and cut state funds to all Utah public institutions by 10 percent ($60.5 million). Universities can have the funds “reallocated” if they use them for high-demand, high-wage majors. As a result, we lost our History and Philosophy of Science major, which drew some of our best students, many of them double majoring in STEM subjects and working toward careers in medicine and public health.

## And just because it is a bit funny

* Reviewing Course Evaluations: The Drinking Game - McSweeney’s Internet Tendency


[https://www.mcsweeneys.net/articles/reviewing-course-evaluations-the-drinking-game](https://www.mcsweeneys.net/articles/reviewing-course-evaluations-the-drinking-game)




----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.
