# May 1

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week. Sadly another terrible, horrible, no good, very bad week. More tricks (re) employed: monkeying with grants; tax-exempt status; accreditation; student visas; and a Draconian proposed budget. Atleast it seems clear -- resistance is the only means forward.


## Letters/Statements

* Several CUNY senates have passed alliance resolutions

[https://www.dropbox.com/scl/fo/my5g55jprx5o64r4vzus0/ABqQBAimqk_KN5t-EsUG8Ds/1.Mutual%20Defense%20Statements?dl=0&rlkey=zvsqtp7ev781y4rqqjti8xaho&subfolder_nav_tracking=1](https://www.dropbox.com/scl/fo/my5g55jprx5o64r4vzus0/ABqQBAimqk_KN5t-EsUG8Ds/1.Mutual%20Defense%20Statements?dl=0&rlkey=zvsqtp7ev781y4rqqjti8xaho&subfolder_nav_tracking=1)

These include BMCC, CCNY, Hostos, Hunter, QBCC, and the UFS XC. (Apologies if any are not included)

* PSC, UUP, and NYSUT (representing public higher education in NY State) speak out in a press statement

[https://psc-cuny.org/wp-content/uploads/2025/04/State-Ed-leaders-call-on-Chancellors-challenge-Trump-administration-attacks-on-the-public-higher-education-systems.pdf](https://psc-cuny.org/wp-content/uploads/2025/04/State-Ed-leaders-call-on-Chancellors-challenge-Trump-administration-attacks-on-the-public-higher-education-systems.pdf)


* We Must Leverage the Strength of Our Institutions and Stand Together

[https://sites.google.com/view/we-must-leverage-the-strength/home](https://sites.google.com/view/we-must-leverage-the-strength/home)

> Dear Presidents, Chancellors, and Boards of Trustees of the 60 Universities that received a March 10th warning letter from the U.S. Department of Education:


> You are on the frontlines of a war that is unfolding against U.S. higher education. We look to you for leadership and coalition-building during a time when the stakes have never been higher.

> We ask all sixty institutions under government threat to unite in a coordinated, proactive defense.

(~3009 signatories)


* Advocating for Brown – What's at stake | Office of the President | Brown University

[https://president.brown.edu/president/advocating-brown-whats-stake](https://president.brown.edu/president/advocating-brown-whats-stake)

> It's important to share what is at stake for Brown. The research funding cuts that Brown has already suffered are causing immediate harm, forcing us to reconfigure our operations and budget to address funding shortfalls. Any long-term cuts of significant magnitude would imperil, or possibly end, several areas of high-impact research at Brown. This would be devastating to Brown's research community, including the undergraduate, graduate and medical students we teach, and the people, patients and communities that benefit from the results of our research.

> Even more concerning, since early April, Brown has not been reimbursed for any expenses associated with active (i.e., not terminated) grants from the National Institutes of Health (NIH), whose grants make up roughly 70% of Brown's overall research portfolio. Again, we have not been given any official explanation for why expenses for active grants are not being reimbursed. These unreimbursed expenses, which amount to millions of dollars per week, represent a significant threat to Brown’s financial sustainability and its ability to conduct federally funded research.

> As we navigate the current environment, I continue to share a set of core principles:

> Brown will always defend the ability for students and scholars to teach and learn without fear of government intrusion or censorship, which is fundamental to efforts to protect academic freedom.

> Brown is deeply committed to following the law and maintaining an academic community where all can participate fully in the life of the institution. This means maintaining a campus that is free of all forms of harassment and discrimination for all community members, including addressing allegations of discrimination based on shared ancestry. We are proud of our initiatives to combat antisemitism, many of which we launched even before this became a major area of focus for the federal government.

> Brown will continue to provide resources and support to members of our international community.


## Alliances

* NYTimes: Emerging From a Collective Silence, Universities Organize to Fight Trump

[https://www.nytimes.com/2025/04/27/us/trump-university-presidents.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/27/us/trump-university-presidents.html?smid=nytcore-ios-share&referringSource=articleShare)

* Exclusive | Elite Universities Form Private Collective to Resist Trump Administration - WSJ

[https://www.wsj.com/us-news/education/elite-universities-form-private-collective-to-resist-trump-administration-95a14ff3](https://www.wsj.com/us-news/education/elite-universities-form-private-collective-to-resist-trump-administration-95a14ff3)

* The Resistance Is Here

[https://www.insidehighered.com/news/government/politics-elections/2025/04/29/resistance-here](https://www.insidehighered.com/news/government/politics-elections/2025/04/29/resistance-here)

> Since then [Harvard saying "no"], a group of more than 500 higher ed leaders signed a statement, released by the American Association of Colleges and Universities, opposing “undue government intrusion in the lives of those who learn, live, and work on our campuses.” Presidents of highly selective universities, threatened by some of the most severe federal funding cuts, have reportedly developed a network to agree on shared boundaries and talk strategy. And faculty members at the Big Ten universities are ramping up pressure on their institutions to collaborate and defend one another against threats from the administration.

* More and More Faculty Groups Want Their Colleges to Stand Together Against Trump

[https://www.chronicle.com/article/more-and-more-faculty-groups-want-their-colleges-to-stand-together-against-trump](https://www.chronicle.com/article/more-and-more-faculty-groups-want-their-colleges-to-stand-together-against-trump)

> Faculty senates across the nation are endorsing the idea of standing collectively against the actions of the Trump administration. Ten of the Big Ten’s 18 member institutions have adopted resolutions in recent weeks calling for an alliance among that group’s members, and on Saturday the State University of New York’s University Faculty Senate also endorsed a mutual-defense compact.


> Within the City University of New York system, the Senates at Hunter College, Hostos Community College, and the City College of New York have done the same for a New York-based effort.

> Support for mutual-defense compacts has come alongside several other efforts to stand against the Trump administration’s actions, among them the AAC&U statement condemning “unprecedented government overreach and political interference” in academe, which now has been signed by more than 500 higher-ed leaders.

> Presidents and trustees from about 10 institutions have also formed an informal private collective to discuss possible responses to the administration, the Wall Street Journal reported on Sunday. The Journal did not name those institutions but noted that they included Ivy League campuses and top private research universities, primarily in blue states.

* A call for unity among researchers, libraries, publishers, journalists and the public in fighting the Trump administration.

[https://scholarlykitchen.sspnet.org/2025/04/30/trump-v-research-how-we-could-turn-the-threats-into-opportunities/](https://scholarlykitchen.sspnet.org/2025/04/30/trump-v-research-how-we-could-turn-the-threats-into-opportunities/)

(Thanks BE!)

> "while it’s encouraging to see some organizations coming together within their existing siloes, that’s not enough. There’s a real opportunity – and imperative – for all stakeholders in the research community to join forces. Each group plays a vital role in the research endeavor. Now is the time to show our support for everyone’s contributions, and to help everyone understand that, by dismantling the research infrastructure through censorship and defunding, we hamper research progress and its benefits in the US and across the world. We call on the industry bodies that represent all these different stakeholders to leverage their relationships and networks to develop something that’s bigger than just a campaign — a movement that spans all individuals and organizations working to fund, conduct, support, and disseminate the science and scholarship essential for our survival and success.


> "So let’s set aside our usual disagreements (open access business models, pricing, copyright, etc., etc.) to focus on what’s really important right now. Let’s seize this opportunity to all stand together in the fight to #DefendResearch!

* NYTimes: This State University Has a Plan to Take on Trump

[https://www.nytimes.com/2025/04/30/nyregion/rutgers-mdc-big-10.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/30/nyregion/rutgers-mdc-big-10.html?smid=nytcore-ios-share&referringSource=articleShare)

Mentions CUNY resolutions as of time of writing.

* NYTimes: Fight Like Our Democracy Depends on It

[https://www.nytimes.com/2025/05/01/opinion/trump-100-days-opposition.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/01/opinion/trump-100-days-opposition.html?smid=nytcore-ios-share&referringSource=articleShare)

Lots here non-higher ed. but the editorial board uses this as a model

> The leaders of Harvard University have offered a model of principled opposition that maximizes the chances of success. When Mr. Trump began threatening the university with canceled funds this spring, many Harvard professors and students urged administrators to head straight to the ramparts and denounce him. Alan Garber, Harvard’s president, took a wiser approach. He acknowledged that some of Mr. Trump’s criticisms had merit. Harvard, like much of elite higher education, has, in fact, been blasé about antisemitism, and it has too often prioritized progressive ideology over an independent search for truth.

> By admitting as much, Mr. Garber strengthened Harvard’s political position. He said what many Americans believed. But when the administration issued a list of ludicrous demands, Harvard fought back hard. It filed a lawsuit, with help from a legal team that included conservative litigators, and became a national symbol of resistance to his lawlessness. Mr. Garber made Harvard look reasonable and Mr. Trump unreasonable.

## How best to describe the times we are in

* A Road Map of Trump’s Lawless Presidency, According to 35 Legal Scholars

[https://www.nytimes.com/2025/04/28/opinion/trump-constitution-rule-of-law.html?unlocked_article_code=1.DE8.cUMD.AE-5Mjxg6jlf&smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/28/opinion/trump-constitution-rule-of-law.html?unlocked_article_code=1.DE8.cUMD.AE-5Mjxg6jlf&smid=nytcore-ios-share&referringSource=articleShare)

> The disregard for law is itself part of the agenda. They do not seem to care whether they violate the Constitution and statutes, make mistakes, do irreparable harm. That recklessness itself sends a message. — Jody Freeman, professor, Harvard Law School

> Universities, law firms, public schools, et cetera, are being attacked because of their political views: their opposition to the president, their adoption of D.E.I. policies, their liberalism more generally. These moves flout the cardinal rule of the First Amendment, which is that the government can’t punish people because of their political speech. — Nicholas Stephanopoulos, professor, Harvard Law School

> Refusing to spend funds appropriated by Congress violates separation of powers in usurping Congress’s spending power and violates the Impoundment Control Act. — Erwin Chemerinsky, dean, University of California, Berkeley, School of Law

(Thanks VAC)

* The 50-Year Wwar On Higher Education

[https://www.chronicle.com/article/the-50-year-war-on-higher-education](https://www.chronicle.com/article/the-50-year-war-on-higher-education)

> To understand what’s happening, you need to see how the backlash against higher education began. You need to trace its roots in the 1960s, its evolution through the culture wars of the 1980s and ‘90s, and into the current populist fray. Then you need to do something about it. Professors, administrators, students, and concerned citizens can no longer stand on the sidelines, shaking our heads and deploring the potentially devastating consequences. The simple truth is this: For decades, outside forces have — both consciously and unintentionally — undermined the integrity and quality of public higher education in America. And time and time again, a divided academic community has failed to combat them effectively. We can and must do better. Seeds of resistance are sprouting. Together, we must nurture their growth. There is no time to lose.

(Though it was written in 2022, this is an excellent historic overview beginning with Reagan's rise on the backs of student protestors at UC Berkeley.)

## Academic freedom

* NEJM Gets Letter From DOJ | MedPage Today

[https://www.medpagetoday.com/special-reports/features/115256](https://www.medpagetoday.com/special-reports/features/115256)

(Thanks KB)

> NEJM Editor-in-Chief Eric Rubin, MD, PhD, received a letter from Edward R. Martin Jr., the interim U.S. attorney for Washington, D.C., asking "six questions, largely about alleged bias in the decision to publish unspecified content," STAT reported.

> n his letter to CHEST Editor-in-Chief Peter Mazzone, MD, MPH, of the Cleveland Clinic, Martin asked five questions, including about how the journal handles misinformation, competing viewpoints, and how it assesses the role of funders in the development of submitted articles.

* DeSantis Calls Off Search for University of Florida Dean

[https://www.insidehighered.com/news/quick-takes/2025/04/28/desantis-calls-search-university-florida-dean](https://www.insidehighered.com/news/quick-takes/2025/04/28/desantis-calls-search-university-florida-dean)

> a day  after the conservative social media account Commies on Campus claimed on X all four finalists were “radical DEI progressives.”

> In response, Bryan Griffin, DeSantis’s communications director, posted on X, “Thanks for flagging this” and said that UF leadership was “cooperative” and had “committed to holding off” on the hire.


* The Dark Ages Are Back - The Atlantic


[https://www.theatlantic.com/science/archive/2025/04/trump-academic-freedom/682648/](https://www.theatlantic.com/science/archive/2025/04/trump-academic-freedom/682648/)

> Today the concept of academic freedom may seem obvious to Americans. But the roots of academic freedom, which can be traced back to medieval European universities, were never certain. Back then, when scholars demanded autonomy from Church and state, they were often rebuked—or worse.

* Trump's War on Academic Institutions Is Even Worse Than You Think' – Byline Times


[https://bylinetimes.com/2025/04/30/trump-freedom-of-speech-universities/](https://bylinetimes.com/2025/04/30/trump-freedom-of-speech-universities/)

> The ensuing resistance from universities will have casualties; Trump will break every convention and every rule he chooses to force capitulation. Students and faculty will face arrest and deportation; funding cuts will set back critical research by decades. And yet, there is no alternative. Universities must fight back.

## Free Speech/Free Expression/Protests

* Trump Antisemitism Task Force Praises Yale Protest Crackdown

[https://www.insidehighered.com/news/students/free-speech/2025/04/28/trump-antisemitism-task-force-praises-yale-protest-crackdown](https://www.insidehighered.com/news/students/free-speech/2025/04/28/trump-antisemitism-task-force-praises-yale-protest-crackdown)

> On Tuesday night, the eve of Ben-Gvir’s (ultranationalist settler leader who transformed himself over the decades from an outlaw and provocateur into one of Israel’s most influential politicians)  visit, about 200 pro-Palestinian protesters gathered on the campus’s main plaza, according to the Yale Daily News student newspaper. Demonstrators began forming a tent encampment, the paper reported.

> A university spokesperson told the Yale Daily News the assembly was violating time, place and manner protest restrictions, and administrators gave final warnings to disperse around 11 p.m. The encampment dissolved before midnight, the paper reported.

* Senate Committee Postpones Vote on Antisemitism Awareness Act

[https://www.insidehighered.com/news/quick-takes/2025/05/01/senate-committee-postpones-vote-antisemitism-awareness-act](https://www.insidehighered.com/news/quick-takes/2025/05/01/senate-committee-postpones-vote-antisemitism-awareness-act)

> The committee’s Republican chairman, Sen. Bill Cassidy of Louisiana, called off the planned vote after the Democratic minority won enough Republican support to pass several amendments aimed at more clearly distinguishing what qualifies as discriminatory speech and protecting the First Amendment rights of pro-Palestinian protesters.

> For instance, some of the proposed amendments included clarifying that it is not antisemitic to oppose the “devastation of Gaza,” or to criticize Israeli prime minister Benjamin Netanyahu, as well as preventing the revocation of visas based on “protected conduct under the First Amendment.” Lawmakers also sought to ensure students and faculty members could protest as long as they don’t incite violence.

> But Democrats and Republican Rand Paul of Kentucky said the amendments were necessary to ensure that while objecting to bigotry and discrimination, this bill also upheld the constitutional right to peaceful protest. (Sen. Susan Collins, a Maine Republican, also supported some of the amendments.)

> “The problem is if you look at the IHRA’s examples of speech, they are going to be limiting on campuses everything on that list … protected by the First Amendment,” Paul said. “The First Amendment isn’t about protecting good speech; it protects even the most despicable and vile speech.”

## SEVIS VISA uncancellation

* Trump Administration Reverses Course on Student Visa Cancellations - The New York Times

[https://www.nytimes.com/2025/04/25/us/politics/trump-student-visa-cancellations.html](https://www.nytimes.com/2025/04/25/us/politics/trump-student-visa-cancellations.html)

* Trump administration reverses abrupt terminations of foreign students’ US visa registrations

[https://www.politico.com/news/2025/04/25/trump-admin-reverses-termination-foreign-student-visa-registrations-00309407](https://www.politico.com/news/2025/04/25/trump-admin-reverses-termination-foreign-student-visa-registrations-00309407)

> The Justice Department announced the wholesale reversal in federal court Friday after weeks of intense scrutiny by courts and dozens of restraining orders issued by judges who deemed the mass termination of students from a federal database — used by universities and the federal government to track foreign students in the U.S. — as flagrantly illegal.

Maybe they could have "illegal" in the headline; though their email reports:

>  It took more than 100 lawsuits and 50 restraining orders from dozens of federal judges. But after 20 days of court losses, the Trump administration capitulated, reversing a decision that threatened the legal status of thousands of foreign students in the United States.

* International Students Who Lost Their Immigration Status Will Have It Restored, Government Says

[https://www.chronicle.com/article/thousands-of-international-students-will-see-their-immigration-status-restored-government-says](https://www.chronicle.com/article/thousands-of-international-students-will-see-their-immigration-status-restored-government-says)

> Many of those students have already left the country. The unprecedented scale and lack of clear explanation for these changes left other students fearful that they might be next.

* At Least 15 Florida Institutions Have ICE Agreements

[https://www.insidehighered.com/news/government/politics-elections/2025/04/29/least-15-florida-institutions-have-ice-agreements](https://www.insidehighered.com/news/government/politics-elections/2025/04/29/least-15-florida-institutions-have-ice-agreements)

* Fordham, CUNY international student visas reinstated — at least temporarily

[https://politicsny.com/2025/04/30/fordham-cuny-international-student-visas-reinstated-at-least-temporarily/](https://politicsny.com/2025/04/30/fordham-cuny-international-student-visas-reinstated-at-least-temporarily/)

> International students at Fordham University whose visas were revoked during the Trump administration’s immigration crackdown have now had their status reinstated, along with at least 16 of the 17 affected CUNY students.

(But there were 27 by some count)

* ICE Expands Student Deportation Powers

[https://www.insidehighered.com/news/global/international-students-us/2025/05/02/new-ice-policy-puts-international-students-greater](https://www.insidehighered.com/news/global/international-students-us/2025/05/02/new-ice-policy-puts-international-students-greater)

> The Trump administration issued plans earlier this week for a new policy that vastly expands federal officials’ authority to terminate students’ legal residency status, according to newly released court documents.

> Immigration attorneys told Inside Higher Ed that if implemented, the new policy would enshrine broad permission for ICE to begin deporting students practically at will.

## Funding cuts

* Exclusive: NSF stops awarding new grants and funding existing ones

[https://www.nature.com/articles/d41586-025-01396-2](https://www.nature.com/articles/d41586-025-01396-2)

> Staff members at the US National Science Foundation (NSF) were told on 30 April to “stop awarding all funding actions until further notice,” according to an email seen by Nature.

> The policy prevents the NSF, one of the world’s biggest supporters of basic research, from awarding new research grants and from supplying allotted funds for existing grants, such as those that receive yearly increments of money. The email does not provide a reason for the freeze and says that it will last “until further notice”.

* U.S. attorney for D.C. accuses Wikipedia of ‘propaganda,’ threatens nonprofit status

[https://wapo.st/42J0r79](https://wapo.st/42J0r79)

(The same "hunt" for foreign money influence is the purported rational.)

> In the letter dated April 24, Ed Martin said he sought to determine whether the Wikimedia Foundation’s behavior is in violation of its Section 501(c)(3) status. Martin asked the foundation to provide detailed information about its editorial process, its trust and safety measures, and how it protects its information from foreign actors.


* Trump’s attacks on elite schools like Harvard and Columbia—using cuts to federal funding as a lever—are part of a larger campaign

[https://www.wsj.com/us-news/education/trump-college-university-fight-ae69a3e1?st=pzGMoK&reflink=article_gmail_share](https://www.wsj.com/us-news/education/trump-college-university-fight-ae69a3e1?st=pzGMoK&reflink=article_gmail_share)

> At least 60 universities across the country, some of them state schools like Eastern Washington University and Ohio State, are under investigation by the Education Department for alleged antisemitism. The task force that’s taken on Harvard and Columbia has publicly named eight other targets. And additional schools are being singled out by Republicans aligned with White House priorities.

Original reporting: https://www.thefp.com/p/trump-prosecutor-threatens-wikipedia


* Trump  order restricting foreign gifts to colleges

[https://www.politico.com/news/2025/04/23/trump-executive-order-college-foreign-funding-00306463](https://www.politico.com/news/2025/04/23/trump-executive-order-college-foreign-funding-00306463)

But guess what? (Politico email)

> — But as the administration launched an investigation into the University of California, Berkeley’s overseas funding on Friday it suggested the severity of federal sanctions universities face will depend on how schools respond to the government’s demands.

> — “If they act in good faith, I think you'll see the department meeting that with a handshake,” said a senior agency official who was granted anonymity because they were not permitted to speak publicly.

> — “Because we want compliance,” the person said. “That's what this is all about. On the other hand, I [senior agency official] will say from some of our experience before in the previous [Trump] administration … sometimes we got the middle finger.”

(Perhaps that was deserved?)

* Ex-NIH Director Says Trump Silenced Him, Others

[https://www.insidehighered.com/news/quick-takes/2025/04/29/ex-nih-director-says-trump-silenced-him-others](https://www.insidehighered.com/news/quick-takes/2025/04/29/ex-nih-director-says-trump-silenced-him-others)

> In late January, the NIH temporarily froze spending and communication and halted most reviews of grant applications; so far in 2025 it’s awarded about $2.8 billion less than usual at this point over the past five years. It’s also announced a plan to cap indirect research cost rates, which universities say would create gaping budget holes and slow the pace of medical breakthroughs. (A federal judge has since blocked the guidance.)

> The agency has also fired some 1,300 employees and terminated roughly $2 billion in grants—many focused on the health of women, LGBTQ+ people and racial minorities—that no longer effectuate “agency priorities.” (Researchers have since sued over the grant terminations). And earlier this month, The Washington Post reported that an internal White House budget proposal outlined plans to cut $20 billion from NIH’s annual budget and consolidate the NIH’s 27 institutes and centers into eight

* Another 700 NSF Grants Cut

[https://www.insidehighered.com/news/quick-takes/2025/04/29/another-700-nsf-grants-cut](https://www.insidehighered.com/news/quick-takes/2025/04/29/another-700-nsf-grants-cut)

> Another 700 National Science Foundation grants were slashed Friday, the day after the agency’s director quit and a week after the president’s Department of Government Efficiency cut 400 NSF grants for being related to diversity, equity and inclusion, USA Today reported.

* National Science Foundation eliminates hundreds of grants day after director resigns

[https://www.usatoday.com/story/news/politics/2025/04/26/national-science-foundation-doge-cuts/83282784007/](https://www.usatoday.com/story/news/politics/2025/04/26/national-science-foundation-doge-cuts/83282784007/)

> The administration reportedly told agency leaders that Trump would be seeking a 55% cut to the agency's budget and the elimination of half of its staff.

* NYTimes: Mellon Foundation Announces $15 Million for Humanities Councils

[https://www.nytimes.com/2025/04/29/arts/mellon-foundation-humanities-endowment.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/29/arts/mellon-foundation-humanities-endowment.html?smid=nytcore-ios-share&referringSource=articleShare)

> The new funding, which will support humanities councils in all 50 states and six jurisdictions, comes a month after the National Endowment for the Humanities abruptly cut off federal funding for the councils, as well as most of its existing grants. The endowment, which had a budget of $207 million last fiscal year, is the nation’s largest public funder of the humanities, providing crucial support to museums, historical sites, cultural festivals and community projects.

* ACLS, AHA, and MLA File Lawsuit Alleging Illegal Dismantling of National Endowment for the Humanities - ACLS

[https://www.acls.org/news/acls-aha-and-mla-file-lawsuit-alleging-illegal-dismantling-of-national-endowment-for-the-humanities/](https://www.acls.org/news/acls-aha-and-mla-file-lawsuit-alleging-illegal-dismantling-of-national-endowment-for-the-humanities/)

> In recent weeks, the NEH has suspended entire divisions, initiated the mass firing of 65 percent of its staff, and suspended entire grant programs. These moves threaten the future of American research into history, literature, languages, philosophy, politics, society, and culture. They restrict Americans’ ability to understand our national history and experiences.

* Executive Order Targets Undocumented Students’ In-State Tuition

[https://www.insidehighered.com/news/government/politics-elections/2025/05/02/trump-order-targets-undocumented-students-state](https://www.insidehighered.com/news/government/politics-elections/2025/05/02/trump-order-targets-undocumented-students-state)

> Immigrant rights advocates are urging state and higher ed leaders not to make any hasty changes to their in-state tuition policies after President Trump issued an executive order on Monday threatening to crack down on sanctuary cities and localities with laws that benefit undocumented immigrants.

(Another front to defend.)

## Accreditation

* ED Announces Further Changes to Accreditation

[https://www.insidehighered.com/news/governance/accreditation/2025/05/02/ed-announces-further-changes-accreditation](https://www.insidehighered.com/news/governance/accreditation/2025/05/02/ed-announces-further-changes-accreditation)

>  “President Trump’s Executive Order and our actions today will ensure this Department no longer stands as a gatekeeper to block aspiring innovators from becoming new accreditors nor will this Department unnecessarily micromanage an institution’s choice of accreditor.”

(What is the long game? Allow Ed Tech to offer more predatory degrees, then allow more admin friendly accreditors, then go after existing accreditors?)

> “As an accreditor with institutions that have been stalled in the process, this guidance will have a positive impact on the work we have been doing with several institutions. We look forward to helping our institutions understand what this may mean for them and for us,” MSCHE president Heather Perfetti wrote. “We appreciate that there are well-defined restrictions that will not allow for institutions to change accreditors to avoid accountability with an existing accreditor.”

* Are You Ready for the AI University?

[https://www.chronicle.com/article/are-you-ready-for-the-ai-university](https://www.chronicle.com/article/are-you-ready-for-the-ai-university)

> In the movie Blade Runner 2049, one of the characters (coincidentally an AI humanoid) says about the rise of AI: “You can’t hold the tide back with a broom.” We are at a tidal moment.

> Colleges have traditionally relied on economies of scale to maintain their bottom lines. With labs, dormitories, lecture halls, athletic facilities, and so much else, colleges have exorbitant fixed costs. Those fixed costs have typically been covered in large part by student enrollment. Now that enrollment is declining, higher education’s cost curve is breaking. No amount of cutting will fix the underlying problem. Many colleges have masked their operating deficiencies by using Covid-relief funds in the past few years, but now, with those funds exhausted, they are dealing with a broken economic model. The Trump administration’s cuts to research funding are adding additional stress to colleges’ already precarious cost structure.

> More damaging than the cost curve is the shift in how students view the value of higher education. Having grown up with Amazon, Netflix, and Google, students expect a speedy, on-demand, and low-friction experience. Moreover, they increasingly view college through a transactional lens: They pursue a degree to get a job. So they regard college much like any other consumer product, and like those other products, they expect it to be delivered how they want, when they want. Why wouldn’t they?

I'd quote the next line, but it ends with "AI is going to decimate faculty ranks"... But I will quote this one:

> The big mistake faculty members make is underestimating the existential threat AI represents to their livelihoods.

* Is Your Online Student a Bot?

[https://www.chronicle.com/article/is-your-online-student-a-bot](https://www.chronicle.com/article/is-your-online-student-a-bot)

(Following an article K had shared earlier)

## Can't we all just get along?

* As Harvard fights Trump, one campus quietly prepares for the worst

[https://www.washingtonpost.com/education/2025/04/27/gwu-harvard-trump-antisemitism/](https://www.washingtonpost.com/education/2025/04/27/gwu-harvard-trump-antisemitism/)

* We Don’t Have to Hand It to Harvard

[https://www.thenation.com/article/society/harvard-university-trump-lawsuit-palestine-academic-integrity/](https://www.thenation.com/article/society/harvard-university-trump-lawsuit-palestine-academic-integrity/)

> Their dismissal has been widely condemned as a flagrant act of censorship. It enacts the Trump administration’s goals for higher education: undermine intellectual autonomy and punish students and scholars for speaking out on Palestine.

(Thanks KB)

* NYTimes: Harvard Promises Changes After Reports on Antisemitism and Islamophobia

[https://www.nytimes.com/2025/04/29/us/harvard-antisemitism-islamophobia-reports.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/29/us/harvard-antisemitism-islamophobia-reports.html?smid=nytcore-ios-share&referringSource=articleShare)

> The antisemitism report was produced by a task force made up mainly of faculty, but that also included students, a former Hillel director and Harvard’s chief community and campus life officer, whose title was changed from chief diversity and inclusion officer on Tuesday. The report said that bias incidents had been occurring before the Hamas attack and were intensified by the war in Gaza. It found that antisemitism seemed to be more pronounced in branches of the university with a social justice bent, including the graduate school of education, the divinity school and the school of public health.

> A similar task force held hundreds of conversations with Muslim, Arab and Palestinian students, staff and faculty members about anti-Muslim bias. That task force summed up the feelings expressed by many of those people in two words: “abandoned and silenced.”

* NYTimes: Trump Doesn’t Want to Protect All Jewish Students — Just Those on His Team

[https://www.nytimes.com/2025/04/28/opinion/jewish-student-protesters-gaza.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/28/opinion/jewish-student-protesters-gaza.html?smid=nytcore-ios-share&referringSource=articleShare)

(For distinctions in position between different Jewish organizations like ADL and Jewish Voice for Peace)

* NYTimes: Harvard, Under Pressure, Revamps D.E.I. Office

[https://www.nytimes.com/2025/04/28/us/politics/harvard-dei-law-review.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/28/us/politics/harvard-dei-law-review.html?smid=nytcore-ios-share&referringSource=articleShare)

* Trump admin hits Harvard with race-based discrimination investigation

[https://www.axios.com/2025/04/28/harvard-law-review-trump-admin](https://www.axios.com/2025/04/28/harvard-law-review-trump-admin)

> The Trump administration is ramping up its fight against Harvard, launching investigations Monday into the university and the Harvard Law Review for alleged race-based discrimination.

> "Harvard Law Review's article selection process appears to pick winners and losers on the basis of race, employing a spoils system in which the race of the legal scholar is as, if not more, important than the merit of the submission," said Craig Trainor [JJ graduate]

"appears..." The article also references this dismissed attempt in 2019 (https://www.thecrimson.com/article/2019/8/11/fasorp-suit-dismissed/)  by the Texas-based anti-affirmative action group Faculty, Alumni, and Students Opposed to Racial Preferences to get legal action.

* ‘It’s Punishment for the Sake of Punishment’

[https://www.chronicle.com/article/its-punishment-for-the-sake-of-punishment](https://www.chronicle.com/article/its-punishment-for-the-sake-of-punishment)

> In four days [March 3-7 at Columbia], the administration had accelerated a highly codified process designed to take weeks or months. Over the next month and a half, it would turn to the same playbook to wrest billions of dollars from universities it accused of antisemitism and other forms of discrimination, ignoring legal and procedural safeguards that had been set up to ensure due process.

> President Trump’s willingness to break norms and bend the rule of law has sparked confusion and alarm on college campuses.

* Education Dept. Gives Penn 3 Demands After Finding Title IX Violation

[https://www.insidehighered.com/news/quick-takes/2025/04/29/education-dept-says-penn-violated-title-ix](https://www.insidehighered.com/news/quick-takes/2025/04/29/education-dept-says-penn-violated-title-ix)

> Issue a statement to the University community stating that the University will comply with Title IX in all of its athletic programs;

> Restore to all female athletes all individual athletic records, titles, honors, awards or similar recognition for Division I swimming competitions misappropriated by male athletes competing in female categories; and

> Send a letter to each female athlete whose individual recognition is restored expressing an apology on behalf of the University for allowing her educational experience in athletics to be marred by sex discrimination.”

(Penn was only following NCAA guidelines)

*  After Feds Warn U. of Virginia It Is Moving Too Slowly, Board Quickly Rescinds Diversity Goal


[https://www.chronicle.com/article/after-feds-warn-u-of-virginia-it-is-moving-too-slowly-board-quickly-rescinds-dei-goal](https://www.chronicle.com/article/after-feds-warn-u-of-virginia-it-is-moving-too-slowly-board-quickly-rescinds-dei-goal)

> Four years ago, the University of Virginia Board of Visitors endorsed a call to double the number of underrepresented faculty by 2030 and to develop a plan for building a student population that better reflected the state’s racial and socioeconomic diversity. The university’s president, James E. Ryan, said the move signaled that “becoming a more diverse, equitable place is both the right and the smart thing to do.”

> On Tuesday, the board voted unanimously to rescind any such numerical goals as part of a sweeping effort to wipe out evidence of diversity, equity, and inclusion efforts. The Trump administration had warned university officials, only the day before, that it had received complaints that the university wasn’t acting fast enough to carry through on its promise to “dismantle DEI apparatuses.”

> In its letter on Monday, the Justice Department said the president had failed to produce a sufficiently detailed progress report. (A campus spokesperson did not immediately respond to a question about whether the required report had been submitted.) It demanded that Ryan and Hardie certify by Friday that the vestiges of DEI have been removed from every division, department, program, and school.

> The Board of Visitors deliberated during a closed session on Tuesday. The public portion of the meeting was not live-streamed. It’s unclear whether the board brought up the fact that Ryan, who became president in 2018, was one of more than 550 higher-education leaders who signed a statement circulated by the American Association of Colleges and Universities (AAC&U) that condemned “unprecedented government overreach and political interference” in academe.

> The Faculty Senate was concerned enough about the board’s reaction that on Monday, it passed a resolution supporting Ryan and his decision to sign the AAC&U statement, saying it “expresses principles that are essential to upholding UVA’s mission, reputation, and operations.”

> The Faculty Senate had encouraged Ryan to collaborate with other university presidents to promote higher education’s contributions to the nation. Ryan’s signature, it said, reaffirmed the university’s established policies on institutional statements and free expression. The former discourages the university from commenting on social or political issues “unless the matter directly affects the university’s mission or operations.”

* Trump’s 100-Day War on Higher Ed

[https://www.insidehighered.com/news/government/politics-elections/2025/04/30/how-trumps-first-100-days-transformed-higher-ed](https://www.insidehighered.com/news/government/politics-elections/2025/04/30/how-trumps-first-100-days-transformed-higher-ed)

10 things done such as "Pursuing Punishment as Policy" and "Breeding Financial Uncertainty" and "Tanking America’s Global Stature". Read for 7 more...

* What Revoking Tax-Exempt Status Would Mean for Harvard — and the Rest of Higher Ed

[https://www.chronicle.com/article/what-revoking-tax-exempt-status-would-mean-for-harvard-and-the-rest-of-higher-ed](https://www.chronicle.com/article/what-revoking-tax-exempt-status-would-mean-for-harvard-and-the-rest-of-higher-ed)

> Reports from CNN and The Washington Post both cite unnamed administration officials who confirmed that the Internal Revenue Service has been asked to consider if the university has violated any of the requirements of charitable organizations, such as engaging in political activity.

> “Perhaps Harvard should lose its Tax Exempt Status and be Taxed as a Political Entity if it keeps pushing political, ideological, and terrorist inspired/supporting ‘Sickness?’ Remember, Tax Exempt Status is totally contingent on acting in the PUBLIC INTEREST!,”

(Guess who said that last rant)

> The loss of tax-exempt status “would endanger our ability to carry out our educational mission,” Harvard spokesperson Jason A. Newton wrote in an email. “It would result in diminished financial aid for students, abandonment of critical medical research programs, and lost opportunities for innovation. The unlawful use of this instrument more broadly would have grave consequences for the future of higher education in America,” he wrote.

Also reported here

[https://www.cnn.com/2025/05/02/us/white-house-harvard-tax-status](https://www.cnn.com/2025/05/02/us/white-house-harvard-tax-status)

* NYTimes: Harvard’s Trick for Fighting Trump? A Deep Bench of Conservative Lawyers.

[https://www.nytimes.com/2025/05/02/us/harvard-trump-conservative-lawyers.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/02/us/harvard-trump-conservative-lawyers.html?smid=nytcore-ios-share&referringSource=articleShare)

> Lee C. Bollinger, a former president of the University of Michigan, said he had used the same strategy when choosing a lawyer to argue an affirmative action case before the Supreme Court in 2003.

## Blowback


* NYTimes: White House Tech Bros Are Killing What Made Them (and America) Wealthy

[https://www.nytimes.com/2025/04/28/opinion/venture-capital-musk-investments.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/28/opinion/venture-capital-musk-investments.html?smid=nytcore-ios-share&referringSource=articleShare)

> Universities are far from perfect, and that imperfection also creates a convenient dodge for those in the administration who are complicit in the annihilation of the very seed corn of our industry and the magic of the American economy. The half-life of this administration is two years; the half-life of the damage to American competitiveness is probably measured in decades.

* NYTimes: Trump Is Laying a Potentially Deadly Trap for the U.S. Auto Industry

[https://www.nytimes.com/2025/04/28/opinion/trump-car-industry-tariffs.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/28/opinion/trump-car-industry-tariffs.html?smid=nytcore-ios-share&referringSource=articleShare)

> Mr. Trump is also undermining the base of public and private research and development that could fuel the advances that U.S. automakers will need to keep pace with foreign competitors. In recent weeks, the administration has cut $7 billion from the Department of Defense’s R&D budget, frozen billions in grants and withheld funding from leading research universities. The National Science Foundation may be next.

> Left unchecked, Mr. Trump’s approach could force the American automobile into a death spiral, consigning a symbol of national pride to permanent irrelevance.

* European Governments Back Universities’ U.S. Recruitment Drive

[https://www.insidehighered.com/news/faculty-issues/research/2025/05/01/european-governments-back-universities-us-recruitment-drive](https://www.insidehighered.com/news/faculty-issues/research/2025/05/01/european-governments-back-universities-us-recruitment-drive)

> On April 23, Norway’s education ministry announced the creation of a $9.6 million initiative, designed by the Research Council of Norway, to “make it easier to recruit experienced researchers from other countries.”

> “Academic freedom is under pressure in the U.S., and it is an unpredictable position for many researchers in what has been the world’s leading knowledge nation for many decades,” Aasland said. “We have had close dialogue with the Norwegian knowledge communities and my Nordic colleagues about developments.

## Alternate Reality

* PBS News Hour: Conservative activist Christopher Rufo on his push to scrutinize higher education

[https://www.pbs.org/newshour/show/conservative-activist-christopher-rufo-on-his-push-to-scrutinize-higher-education](https://www.pbs.org/newshour/show/conservative-activist-christopher-rufo-on-his-push-to-scrutinize-higher-education)

(And still Trump seeks to cut their funding. Thanks VAC.)



## Coming attractions?

* Indiana Budget Bill Contains Sweeping Higher Ed Changes

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/04/30/indiana-budget-bill-contains-sweeping-higher-ed](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/04/30/indiana-budget-bill-contains-sweeping-higher-ed)

> If Republican governor Mike Braun signs it into law, House Enrolled Act 1001 will require faculty at public colleges and universities to post their syllabi online and undergo “productivity” reviews.

> “I think overreach doesn’t begin to describe the actions of the Legislature,” said Russ Skiba, a professor emeritus of education at IU Bloomington. “This is really a sweeping takeover of higher education in Indiana.”

See also this article highlighting potential impact on faculty governance:

[https://www.chronicle.com/article/in-indiana-last-minute-additions-to-the-budget-take-aim-at-higher-ed](https://www.chronicle.com/article/in-indiana-last-minute-additions-to-the-budget-take-aim-at-higher-ed)

> In approving a new state budget late last week, Indiana lawmakers also gave the green light to several measures that would dramatically change public higher education in the state. Those additions, made at the 11th hour, include a post-tenure review process that measures productivity, guidance that makes faculty-governance groups “advisory only,” and a provision that gives the governor sole power to appoint trustees at Indiana University at Bloomington.



* Three Competing Visions Drive Trump’s Higher-Ed Policy

[https://www.chronicle.com/article/three-competing-visions-drive-trumps-higher-ed-policy?utm_source=Iterable&utm_medium=email&utm_campaign=campaign_13379969_nl_Academe-Today_date_20250430](https://www.chronicle.com/article/three-competing-visions-drive-trumps-higher-ed-policy?utm_source=Iterable&utm_medium=email&utm_campaign=campaign_13379969_nl_Academe-Today_date_20250430)

> . Beneath the surface, three different visions are competing to define the Trump higher-education agenda: Elon Musk’s attempt to reform government with a chainsaw, Rep. Virginia Foxx’s plans to slash student-aid spending, and Christopher F. Rufo’s culture war. Ironically, none of these three people are Trump appointees themselves. But the confluence and conflict among them will determine the course of a White House that moves forward decisively when there is internal consensus but swerves erratically when major players fight over the steering wheel.


----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.
