# May 30

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week. This was another week of mischief directed at Harvard including attempts to pull the plug on all federal contracts and disallow foreign students. As well, two red states are attempting to drastically change higher education in their states. On a good note, CUNY has announced available BRIDGE funding for those who have lost funding of late.


Thanks to SC, BE, JC for sharing links and comments!


These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)


## Letters

* Twenty-one Skytte Prize winners speak out | Skytteprize

[https://www.skytteprize.com/news/twenty-one-winners-speak-out](https://www.skytteprize.com/news/twenty-one-winners-speak-out)

> As award-winning political scientists who do not know each others’ political affiliations, we collectively fear that the current actions of the US government are a threat to the rule of law and civil peace, and we condemn the tools being used to achieve the administration’s goals. Specifically, we condemn the US government’s use of extortion to coerce independent institutions to act in accordance with the administration’s preferences; its illegal detention and deportation of hundreds of our international students and our international faculty colleagues; its deliberate fostering of bitterness among students and faculty on hundreds of university campuses in America; its punishing of researchers unrelated to the charges against their universities; its fear-mongering against those with whom the president disagrees; its short-sighted and senseless cuts to basic research that benefits the US and the world; and its encroachments on academic freedom and the core mission of American universities and colleges.


## Alliances

* New link for CUNY MADC resolutions

[https://drive.google.com/drive/folders/1SqTGsQIu-HLfc8b_oeGiBKfSOE7IAKzw](https://drive.google.com/drive/folders/1SqTGsQIu-HLfc8b_oeGiBKfSOE7IAKzw)

(Thanks EI for keeping this up to date)


## Op eds

* NYTimes: Teachers Saved My Life. Why Do We Treat Them So Poorly?

[https://www.nytimes.com/2025/05/25/opinion/teachers-education-trump-administration.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/25/opinion/teachers-education-trump-administration.html?smid=nytcore-ios-share&referringSource=articleShare)

(SUNY Chancellor on the impact of teachers.)

## How best to describe the times we are in

* The New Dark Age

[https://www.theatlantic.com/ideas/archive/2025/05/trump-defund-schools-research-republicans/682742/?gift=Je3D9AQS-C17lUTOnl2W8DWsF0Ye4dzmUZWM5fDSO2g&utm_source=copy-link&utm_medium=social&utm_campaign=share](https://www.theatlantic.com/ideas/archive/2025/05/trump-defund-schools-research-republicans/682742/?gift=Je3D9AQS-C17lUTOnl2W8DWsF0Ye4dzmUZWM5fDSO2g&utm_source=copy-link&utm_medium=social&utm_campaign=share)

(This is a crystal clear piece about where this administration is trying to steer things and it is not a good place. It is well worth getting past the paywall to read/)

> The warlords who sacked Rome did not intend to doom Western Europe to centuries of ignorance. It was not a foreseeable consequence of their actions. The same cannot be said of the sweeping attack on human knowledge and progress that the Trump administration is now undertaking—a deliberate destruction of education, science, and history, conducted with a fanaticism that recalls the Dark Ages that followed Rome’s fall.

> Every week brings fresh examples. The administration is threatening colleges and universities with the loss of federal funding if they do not submit to its demands, or even if they do. The engines of American scientific inquiry and ingenuity, such as the National Science Foundation and the National Institutes of Health, are under sustained attack. Historical institutions such as the Smithsonian and artistic ones like the Kennedy Center are being converted into homes for MAGA ideology rather than historical fact and free expression. Libraries are losing funding, government-employed scientists are being dismissed from their jobs, educators are being cowed into silence, and researchers are being warned not to broach forbidden subjects. Entire databases of public-health information collected over decades are at risk of vanishing. Any facts that contradict the gospel of Trumpism are treated as heretical.

> Like the inquisitors of old, who persecuted Galileo for daring to notice that the sun did not, in fact, revolve around the Earth, they believe that truth-seeking imperils their hold on power.

> But a massive technological stall is only the most apparent aspect of the coming damage. The attack on knowledge also threatens the country’s ability to address subtler social problems, such as racial and economic inequalities in health, opportunity, and civil rights. Research into these disparities is being cut across government and civil society in the name of defeating so-called wokeness. Invoked as a general criticism of left-wing excess, the fight against “wokeness” is destroying huge swaths of scholarship and research, for fear the results might make the case for racial or gender equality, the redistribution of wealth, or the regulation of industry.

* Donald Trump’s Politics of Plunder

[https://www.newyorker.com/magazine/2025/06/02/donald-trumps-politics-of-plunder](https://www.newyorker.com/magazine/2025/06/02/donald-trumps-politics-of-plunder)

> Historically, ruling billionaires have tried to avoid such portraits. (A publicist for J. P. Morgan used to say that he was “paid to keep the bank out of the press.”) But the Trump Presidency has embraced an unusually open marriage of politics and profit. Official filings revealed that his Inauguration fund set a new record by collecting some two hundred and fifty million dollars from corporations, C.E.O.s, and other large donors. The biggest donation, five million dollars, came from a major poultry producer called Pilgrim’s Pride. A few months later, Trump’s Agriculture Secretary delighted the industry by agreeing not to increase salmonella testing and promising to cut “unnecessary bureaucracy.” By then, Trump had already fired the director of the Office of Government Ethics and the head of the Office of Special Counsel, which investigates whistle-blower complaints.

> on-one conversations with the President have become available for five million. The return on investment is uncertain, a government-affairs executive told me: “What if he’s in a bad mood? You have no clue where the money is eventually going.” Another lobbying veteran described the frank exchange as “outer-borough Mafia shit.”

> The ultra-rich have captured more of America’s wealth than even the nineteenth-century tycoons of the Gilded Age. Scholars who study inequality as far back as the Neolithic period struggle to find precedents. Tim Kerig, an archeologist who directs the Museum Alzey, in Germany, told me, “The people who built the Egyptian pyramids were probably in a less unequal society.” He suggested that today’s richest people are simply accumulating too much wealth for the system to contain. “The economic and technical evolution is much faster than the social, mental, and ideological evolution,” he said. “We had no time to adapt to all those billionaires.”

> For fifteen years, the Patriotic Millionaires have waged an earnest battle to persuade wealthy people to lobby for higher taxes on themselves. This has often been a lonesome endeavor, but Trump’s assault on democracy, financed by some of America’s richest people, has fortified the group’s arguments. Scott Ellis, a member who used to run a consulting group at Hewlett-Packard, told me that even skeptical peers in Silicon Valley had become increasingly receptive. “Some friends used to humor me, but they’re listening more,” he said.

>  In the 2004 election, according to Americans for Tax Fairness, billionaires gave thirteen million dollars in political contributions; twenty years later, the country’s richest families spent more than two hundred times that much. Payne told the crowd, “There’s a point where money is no longer money. It is power—and they’re using that power to screw life up for everybody else.”


## Academic freedom

* Texas House OKs more state oversight of public universities | The Texas Tribune

[https://www.texastribune.org/2025/05/24/texas-governing-boards-regents-senate-bill-37/](https://www.texastribune.org/2025/05/24/texas-governing-boards-regents-senate-bill-37/)

> Senate Bill 37 passed in an 83-53 vote Saturday. It would create a state-level committee that would recommend courses that should be required for graduation and how to condense the number of those courses. Meanwhile, each public university system’s board of regents, who oversee the school’s operations and are appointed by the governor, would be charged with creating a committee to review curricula and reject any course deemed ideologically charged or that doesn’t align with the workforce demands. Specifically, the committees would ensure curricula do not “advocate or promote that any race, sex, ethnicity or religious belief is inherently superior to any other.”

(This bill if passed is much more than a glancing blow to higher education's principles.)

* In Defense of Academic Freedom - The Atlantic

[https://www.theatlantic.com/newsletters/archive/2025/05/in-defense-of-academic-freedom/682914/](https://www.theatlantic.com/newsletters/archive/2025/05/in-defense-of-academic-freedom/682914/)

> Why defend academic freedom even when the ideas in question are wrongheaded or harmful? “It is precisely because any kind of purge opens the gate to all kinds of purge, that freedom of thought necessarily means the freedom to think bad thoughts as well as good.”

> Those words, written in 1953 by Joseph Alsop, an alumnus of Harvard who later served on its Board of Overseers, are relevant today, as the Trump administration cancels the visas of foreign students for viewpoints that it deems “bad.” And they were relevant in recent years as institutions of higher education investigated and disciplined members of their communities for expressing views that ran afoul of various progressive social-justice orthodoxies. But Alsop wrote them in response to the McCarthy era’s efforts to identify and punish Communists who were working in academia.

* A Tumultuous Spring Semester Finally Comes to a Close | The New Yorker


[https://www.newyorker.com/magazine/2025/06/02/a-tumultuous-spring-semester-finally-comes-to-a-close](https://www.newyorker.com/magazine/2025/06/02/a-tumultuous-spring-semester-finally-comes-to-a-close)

> The biggest mistake that some universities have made is to presume that the White House is operating in good faith. It is not.

> Academic freedom in the United States has found itself periodically under siege. In March, Ellen Schrecker, a historian and the author of “No Ivory Tower: McCarthyism and the Universities,” spoke via Zoom to deans at Columbia (including myself) about government repression on college campuses in the nineteen-fifties. Schrecker, who has taught at both Columbia and Harvard and retired as a professor at Yeshiva University, emphasized the severity of the current climate. “I’ve studied McCarthyism’s impact on higher education for fifty years,” she said. “What’s happening now is worse.” This is in part because universities today are far more beholden to the federal government. The explosive expansion of higher education that began after the Second World War was underwritten by federal dollars. So members of Congress, and President Trump, too, have leverage that demagogues who preceded them could only dream of.

> Mordecai Johnson was a Black man leading an academic institution during Jim Crow when representatives from an almost entirely white Congress asked him whether professors with radical sympathies should be allowed to teach at Howard. Yet he firmly said that he would sooner shut down his university than allow anyone to dictate what its students could or could not learn. The principle at play—that without free inquiry there is no basis for a university to exist—still applies.

* Utah Lawmakers Flex Their Power Over Public Universities

[https://www.insidehighered.com/news/faculty-issues/shared-governance/2025/05/28/new-utah-law-prompts-program-cuts-strategic](https://www.insidehighered.com/news/faculty-issues/shared-governance/2025/05/28/new-utah-law-prompts-program-cuts-strategic)

(Thanks SC for sharing and caring)

> Public colleges and universities in Utah are set to lose roughly $60 million in July—or 10 percent of their state-funded instructional budgets—but they can earn back that money by cutting programs and positions and investing in other areas considered worthy by state lawmakers, under a law passed this spring.

> HB 265 is just one example of how Republicans in Utah’s State House are trying to exert more control over public higher education and shape colleges’ academic programs and services. The changes have raised concerns among faculty, who see their traditional academic freedom and shared governance roles in setting curricula and other areas being usurped.

> Since 2024, lawmakers have mandated post-tenure review; banned diversity, equity and inclusion initiatives and offices; and banned pride flags, Juneteenth flags and others from “prominent” campus locations. They’ve also created a Center for Civic Excellence at Utah State University, mandating that faculty appointed to that center teach all the university’s general education courses while serving on short-term, at-will contracts.

> As for university administrators, Gerdes [president of the University of Utah’s AAUP chapter] said, “Our administration wants to have a healthy working relationship with the State Legislature. I think that they are less concerned about having a healthy relationship with their own faculty.”

> The Salt Lake Tribune reported that university president Taylor R. Randall cited a 2024 law, Senate Bill 192, on the limits of faculty governance to silence an Academic Senate discussion in February that was critical of his provost.

* We Don’t Need More Administrators Inspecting Our Ideas

[https://www.chronicle.com/article/we-dont-need-more-administrators-inspecting-our-ideas](https://www.chronicle.com/article/we-dont-need-more-administrators-inspecting-our-ideas)

* RFK Jr. says he may bar scientists from publishing in top medical journals


[https://www.washingtonpost.com/health/2025/05/28/rfk-jr-ban-journals-lancet-jama/](https://www.washingtonpost.com/health/2025/05/28/rfk-jr-ban-journals-lancet-jama/)

> “We’re probably going to stop publishing in the Lancet, New England Journal of Medicine, JAMA and those other journals because they’re all corrupt,” Kennedy said during an appearance on the “Ultimate Human” podcast. He also described the journals as being under the control of pharmaceutical companies.

> On his plans for the department to create its own journals, Kennedy said they would “become the preeminent journals, because if you get [NIH] funding, it is anointing you as a good, legitimate scientist.”

### Anti-woke/anti-DEI is simply racism

* Trump addresses a West Point upended by his changes

[https://www.washingtonpost.com/politics/2025/05/24/trump-west-point-graduation-dei-military/](https://www.washingtonpost.com/politics/2025/05/24/trump-west-point-graduation-dei-military/)

>  He said that as president, he had rebuilt the military “better than ever before” and rid it of “social experiments” like the teaching of critical race theory and efforts to support transgender soldiers. And he took credit for a rise in military recruitment.

> “It’s a feeling of real whiplash,” said Graham Parsons, a former West Point professor who resigned from America’s oldest service academy after publicly criticizing the impact of Trump’s policies. “We used to raise the possibility that in the military and beyond, there are still real structural problems with racism and sexism. That would not fly now.”

* NYTimes: For Trump, Civil Rights Protections Should Help White Men

[https://www.nytimes.com/2025/05/25/us/politics/trump-race-civil-right-white-men.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/25/us/politics/trump-race-civil-right-white-men.html?smid=nytcore-ios-share&referringSource=articleShare)

> And last month, the Equal Employment Opportunity Commission launched an investigation at Harvard University, alleging that the school had engaged in discriminatory hiring because it showed a significant increase in the percentage of minority, female and nonbinary faculty earning tenure over the past decade while the rates for white men declined.

> Conservatives have denounced disparate impact because it relies on outcome data to allege and prove discrimination — the basis on which Ms. Lucas lodged her charge against Harvard.

* How Harmeet Dhillon is engineering a U-turn in the Justice Department’s civil-rights division


[https://www.wsj.com/politics/policy/harmeet-dhillons-civil-rights-revolution-comes-with-tea-and-roses-ff9b1874?st=s7pVVz&reflink=article_gmail_share](https://www.wsj.com/politics/policy/harmeet-dhillons-civil-rights-revolution-comes-with-tea-and-roses-ff9b1874?st=s7pVVz&reflink=article_gmail_share)

(An attempt at a flattering profile, but don't be put led astray)

> “What we’re seeing now is a complete gutting of all the traditional work of the civil-rights division and then a rump of the civil-rights division being used almost exclusively to pursue right-wing Trumpist agenda items,” said Samuel Bagenstos, a former senior civil-rights official in the Obama Justice Department.

* Uncle Sam’s new message to young Black Americans: I don’t want you


[https://www.washingtonpost.com/opinions/2025/05/27/trump-military-hostile-black-americans/](https://www.washingtonpost.com/opinions/2025/05/27/trump-military-hostile-black-americans/)

> Trump and his allies have pushed aggressively to defund or eliminate DEI programs across the military. One of Trump’s first actions was to fire the chairman of the Joint Chiefs of Staff, Gen. Charles Q. Brown Jr., only the second African American ever to hold that position. Training on racial bias, cultural competency and inclusive leadership has been gutted and labeled “radical.” Officers who speak up about race or systemic injustice are accused of pushing “politics,” while those promoting exclusionary rhetoric are celebrated as patriots.

> The message is clear: If you’re Black, Brown or anything other than the old guard — a White male — your presence in the military is conditional and increasingly unwelcome.

* The Era of DEI for Conservatives Has Begun

(Thanks BE)

[https://www.theatlantic.com/ideas/archive/2025/05/conservative-professors-dei-initiatives/682944/?gift=yCYg0MdUGpnvquf3En3lpjtTtgMgla5OiobYjP9Hxt4&utm_source=copy-link&utm_medium=social&utm_campaign=share](https://www.theatlantic.com/ideas/archive/2025/05/conservative-professors-dei-initiatives/682944/?gift=yCYg0MdUGpnvquf3En3lpjtTtgMgla5OiobYjP9Hxt4&utm_source=copy-link&utm_medium=social&utm_campaign=share)

> Legislatures in red and purple states across the country have shoveled money into universities to establish schools of civic thought, which are marketed as the conservative answer to academia’s leftward drift and the rise of identity-oriented disciplines.

> Republicans have unfairly smeared affirmative action as a way to hire people “based on their race and not on their qualifications.” Now they’re the ones who want to hire professors based on their politics, not their fitness for the role.


## Visas

* The U.S. has more than 1 million foreign students. Here’s who they are.

[https://www.washingtonpost.com/education/2025/05/25/international-students-harvard-trump/](https://www.washingtonpost.com/education/2025/05/25/international-students-harvard-trump/)

> NAFSA estimates that international students contributed nearly $44 billion to the U.S. economy during the 2023-2024 school year, including paying for tuition, fees, accommodations, transportation and incidentals like

> The National Foundation for American Policy estimates that if all international students were barred from studying in the U.S., undergraduate student enrollment would drop by at least 2 percent and graduate student enrollment would shrink by at least 11 percent over the next decade.

* Trump team orders stop to new student visa interviews, as it weighs expanding social media vetting

[https://www.politico.com/news/2025/05/27/trump-team-orders-stop-to-new-student-visa-interviews-as-it-weighs-expanding-social-media-vetting-00370501](https://www.politico.com/news/2025/05/27/trump-team-orders-stop-to-new-student-visa-interviews-as-it-weighs-expanding-social-media-vetting-00370501)

> In preparation for such required vetting, the administration is ordering U.S. embassies and consular sections to stop scheduling new interviews for such student visa applicants, according to the cable, dated Tuesday and signed by Secretary of State Marco Rubio.


* New Visa Policies Put America First, Not China - United States Department of State


[https://www.state.gov/releases/office-of-the-spokesperson/2025/05/new-visa-policies-put-america-first-not-china/](https://www.state.gov/releases/office-of-the-spokesperson/2025/05/new-visa-policies-put-america-first-not-china/)


(For reference, CUNY has 7000 students on SEVIS visas; The concentration is at Baruch, Hunter, the GC, City(?), and Lehman. I don't know how many are from China.)

(Also)

[https://www.washingtonpost.com/immigration/2025/05/28/chinese-visas-applicants-trump-rubio/](https://www.washingtonpost.com/immigration/2025/05/28/chinese-visas-applicants-trump-rubio/)

[https://www.nytimes.com/2025/05/28/us/politics/china-student-visas-revoke.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/28/us/politics/china-student-visas-revoke.html?smid=nytcore-ios-share&referringSource=articleShare)

[https://www.wsj.com/us-news/education/state-department-marco-rubio-chinese-student-visas-fc8b7828?st=StJhwo&reflink=article_gmail_share](https://www.wsj.com/us-news/education/state-department-marco-rubio-chinese-student-visas-fc8b7828?st=StJhwo&reflink=article_gmail_share)

* NYTimes: Trump Says Harvard Should Limit Acceptance of International Students

[https://www.nytimes.com/2025/05/28/us/politics/trump-harvard-international-students.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/28/us/politics/trump-harvard-international-students.html?smid=nytcore-ios-share&referringSource=articleShare)

> For months, the Trump administration has targeted noncitizen students who have been involved in campus protests related to the war in Gaza for arrest and removal from the country.

> Speaking to reporters in the Oval Office, Mr. Trump continued to sow doubts about foreign students by incorrectly asserting [lying?, ed.] there were open questions about who had been previously allowed into the country to study.

> In an interview this month, Linda McMahon, the education secretary, said it was time for American students to rethink whether degrees from four-year universities were necessary, save for those pursuing legal or medical professions.

* Colleges Across U.S. Fear Chill on Enrollments of Foreign Students

[https://www.chronicle.com/article/colleges-across-u-s-fear-chill-on-enrollments-of-foreign-students](https://www.chronicle.com/article/colleges-across-u-s-fear-chill-on-enrollments-of-foreign-students)

* Here’s how much international students contribute to the U.S. economy


[https://www.washingtonpost.com/education/2025/05/28/international-students-economic-impact-trump-harvard/](https://www.washingtonpost.com/education/2025/05/28/international-students-economic-impact-trump-harvard/)

> The more than 1.1 million international students who studied in the United States last year contributed nearly $44 billion to the U.S. economy during the 2023-2024 school year, according to nonpartisan nonprofit NAFSA, the Association of International Educators — from $10 million in Alaska to more than $6 billion in California — and supported more than 378,000 jobs.



## Funding cuts

* CUNY to provide bridge funding for those who have lost grants

> CUNY’s Research Bridge Fund is designed to support faculty whose research has been disrupted by recent Stop Work Orders (SWOs) issued by U.S. federal funding agencies. The program aims to provide short-term, bridge funding to sustain critical research activities  support the professional advancement of faculty, particularly junior and untenured faculty who face greater risk from funding disruptions.

(Consult your provost if this applies to you.)

* NYTimes: Funding Cuts Are a ‘Gut Punch’ for STEM Education Researchers

[https://www.nytimes.com/2025/05/22/science/trump-nsf-stem-education.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/22/science/trump-nsf-stem-education.html?smid=nytcore-ios-share&referringSource=articleShare)

> More than half of the National Science Foundation grants terminated since April fund programs that would help students train in science, engineering and math.

> One potential outcome of defunding a large portion of STEM education research is that the work may become more concentrated at larger universities that are able to provide alternative sources of funding.

> “STEM and STEM education research need to grow hand in hand,” Dr. Penuel said. “And if we stop funding education research, they won’t.”

### NSF

* New York sues National Science Foundation over research funding restrictions

(Politico Pro email by By Maya Kaufman | 05/28/2025 04:42 PM EDT; thanks JC)

> The growing list of canceled research projects includes 18 by the City University of New York to promote participation in STEM fields by women, minorities and people with disabilities, according to James’ office. Those projects were supported by $11 million in National Science Foundation funds.



> The coalition of states seeks a court order ruling that the foundation’s policies are illegal and blocking them from being implemented.

### NEA

* Trump Cancels Federal Research Grants. What Are the Consequences?

[https://www.nea.org/nea-today/all-news-articles/trump-cancels-federal-research-grants-what-are-consequences](https://www.nea.org/nea-today/all-news-articles/trump-cancels-federal-research-grants-what-are-consequences)

> Last August, Jaafar [professor in the math, engineering and computer science department at LaGuardia Community College] realized a long-held dream of hers to win a NSF grant: $530,002 aimed at boosting students’ success in STEM degrees (and consequently their success in New York City’s workplaces). This grant-funded work would have involved about 40 faculty members directly, plus many more through a robust diffusion model, says Jaafar, providing the kind of professional development that leads to “long-term behavioral change, so that faculty become change agents,” she said. “You go through this transformation and then you’re able to transform others.”

> Over the three years, Jaafar estimates that trained faculty would have influenced about 5,000 students at LaGuardia, a formally designated Hispanic-serving institution (HSI). “Without making these investments, we’re going to enforce the longstanding barriers to access—and we’ll actually be falling short in workforce needs,” she says.

> These aren’t the only NSF grants to CUNY institutions that have been terminated. Indeed, about $17 million in grants have been targeted, including the following:

> A $1 million grant to Queensborough Community College, Queens College and LaGuardia to develop a program that trains students in the emerging field of wastewater-based epidemiology. The goal was to train about 200 students for public-service jobs.

> A $1 million grant to LaGuardia, City Tech, which is a 4-year college, and the biotechnology company Schrödinger to create a program that provides hands-on, experiential learning and paid internships.

> A $700,000 grant to the College of Staten Island to increase students’ sense of belonging and retention through peer-led team learning. Already, this project was achieving dramatic increases in passing rates, but because of the grant’s termination its paid peer leaders have been dismissed.


### Fulbright

* For Fulbright Applicants, a DEI Disqualifier

[https://www.insidehighered.com/news/global/us-colleges-world/2025/05/29/fulbright-applicants-rejected-over-dei-research-proposals](https://www.insidehighered.com/news/global/us-colleges-world/2025/05/29/fulbright-applicants-rejected-over-dei-research-proposals)

> Inside Higher Ed obtained a copy of Rubio’s cable, which says that this year State Department officials would give the final sign-off; they have been tasked with rooting out any projects that could violate President Trump’s executive orders banning diversity, equity and inclusion. All candidates, whether they’d been approved by FFSB [Fulbright Foreign Scholarship Board] already or not, would have to pass.

## Institutional assaults

### Harvard

* NYTimes: Trump Seeks Extensive Student Data in Pressure Campaign to Control Harvard

[https://www.nytimes.com/2025/05/23/us/trump-harvard-international-student-records.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/23/us/trump-harvard-international-student-records.html?smid=nytcore-ios-share&referringSource=articleShare)

> Kristi Noem, the secretary of the Department of Homeland Security, sent a letter to Harvard requesting, among other things, coursework for every international student and information on any student visa holder involved in misconduct or illegal activity.

> Ms. Noem also expanded her request for records to include any videos of international students, on campus or off, involved in protests or illegal or dangerous activity.

(This is of note given CUNY's recent decision to adopt body worn cameras for its public safety officers.)

* NYTimes: Why Harvard Has No Way Out

[https://www.nytimes.com/2025/05/23/us/politics/trump-harvard-international-students.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/23/us/politics/trump-harvard-international-students.html?smid=nytcore-ios-share&referringSource=articleShare)

> Harvard has won praise for fighting back, and many legal experts believe the law is squarely on its side. But the administration holds the levers of power, and is methodically and creatively using them in a take-no-prisoners assault on the school.

> “I was dumbfounded,” Ted Mitchell, the president of the American Council on Education, told me. “What’s becoming increasingly clear is that this administration will use any tool that it can.”

> MS [Michael Schmidt]: There’s been an audacity and creativity to the way that Trump has tried to use his power in the second term, and this is the latest example. Coming into this, we concentrated on his threats to lock up his enemies, like Liz Cheney or James Comey. The use of the government’s power for purely political ends has manifested itself in ways that I think go beyond what we had imagined, and even beyond what Project 2025 contemplated.

> Harvard officials have privately determined they are in a major, major, major crisis with very few, if any, good off ramps.

(I hope we recognize that Harvard's battle is the ultimate fight for academic freedom and the independence of higher education -- the assault has no rational explanation; its destructiveness can't be rationalized.)

* Harvard Digs In for Battle, but Trump’s Blows Are Landing


[https://www.wsj.com/us-news/education/harvard-trump-lawsuits-fight-d5f8ec8a?st=27ignH&reflink=article_gmail_share](https://www.wsj.com/us-news/education/harvard-trump-lawsuits-fight-d5f8ec8a?st=27ignH&reflink=article_gmail_share)

>  Even as Harvard looks to the courts for relief, faculty and administrators are making contingency plans and preparing for a drawn-out war with the Trump administration

> Harvard’s conundrum is that it cannot trust the Trump administration to negotiate in good faith nor can it count on winning an extended battle with the federal government, says Aziz Z. Huq, a law professor at the University of Chicago.

> The result, Huq suggests, will be a reset not only for Harvard but across higher education. The current model for research universities was created during World War II, when the military outsourced its research and development to schools. That model served the nation well for decades but is increasingly under attack from MAGA conservatives who believe that higher education has become a hotbed of liberal ideology that needs to be torn down and rebuilt.

(I'd rephrase that last part, but will amplify "That model served the nation well for decades" until the mis-informed got mid-informed.)

* The government seems bent on destroying Harvard for the offense of fighting back. And for what purpose?

[https://www.wsj.com/opinion/donald-trump-harvard-dhs-foreign-students-kristi-noem-b8ac80ed?st=WwQp8f&reflink=article_gmail_share](https://www.wsj.com/opinion/donald-trump-harvard-dhs-foreign-students-kristi-noem-b8ac80ed?st=WwQp8f&reflink=article_gmail_share)

(After some back and forth, this line still hits:)

> The Trump Administration seems to think it needs to destroy Harvard to save it. This is the opposite of making America great.

* President Trump on Monday said he was considering taking billions in grant money away from Harvard University and redistributing it to trade schools across the U.S.

[https://www.wsj.com/us-news/education/trump-threatens-to-redistribute-3-billion-in-harvard-grants-to-trade-schools-a4ebc64c?st=XiKVT4&reflink=article_gmail_share](https://www.wsj.com/us-news/education/trump-threatens-to-redistribute-3-billion-in-harvard-grants-to-trade-schools-a4ebc64c?st=XiKVT4&reflink=article_gmail_share)

(rewrite? In attempt to pander to possibly supportive people, the illegally cancelled contracts are being ...)

(Also)

[https://www.nytimes.com/2025/05/26/us/harvard-trump-trade-schools.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/26/us/harvard-trump-trade-schools.html?smid=nytcore-ios-share&referringSource=articleShare)

(Also)

[https://www.reuters.com/world/us/trump-says-hes-considering-taking-3-billion-grants-harvard-giving-it-trade-2025-05-26/](https://www.reuters.com/world/us/trump-says-hes-considering-taking-3-billion-grants-harvard-giving-it-trade-2025-05-26/)

> Most of that grant money is appropriated by Congress for the National Institutes of Health to disburse to fund biomedical research after a lengthy application process by individual scientists, work that is not typically done at trade schools.


* NYTimes: Trump Intends to Cancel All Federal Funds Directed at Harvard

[https://www.nytimes.com/2025/05/27/us/harvard-trump-federal-funds.html?smid=nytcore-ios-share&referringSource=articleSharehttps://www.nytimes.com/live/2025/05/27/us/trump-news?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/27/us/harvard-trump-federal-funds.html?smid=nytcore-ios-share&referringSource=articleSharehttps://www.nytimes.com/live/2025/05/27/us/trump-news?smid=nytcore-ios-share&referringSource=articleShare)

(Also)

[https://www.washingtonpost.com/education/2025/05/27/harvard-contracts-trump-federal-funding/](https://www.washingtonpost.com/education/2025/05/27/harvard-contracts-trump-federal-funding/)


* Trump’s revenge spree on Harvard echoes well beyond education | Jan-Werner Müller | The Guardian


[https://www.theguardian.com/commentisfree/2025/may/26/trumps-revenge-spree-on-harvard-echoes-well-beyond-educationa](https://www.theguardian.com/commentisfree/2025/may/26/trumps-revenge-spree-on-harvard-echoes-well-beyond-educationa)

> Attacks will not stop, and it is naive to think that this is all primarily a Harvard problem, or even only a challenge to higher education. Noem’s letter to Harvard makes clear that Trump and his sycophants will weaponize the state against anyone who incurs their displeasure. Courts may prevent the worst, but the whole pattern has to end if we want to have any hope of living in a country free of fear and featuring at least minimum respect for the rule of law.

> As Harvard’s lawsuit against the Department of Homeland Security rightly pointed out, Noem’s revocation fits into the Trump administration’s orgy of vengeance prompted by Harvard’s refusal to comply with evidently illegal demands issued in mid-April.

> We can draw larger lessons from this – so far – failed attack (eight investigations, involving six different agencies, are still ongoing). One has to be ready – Harvard’s lawyers clearly were. Universities have to stand with each other; Noem warned all of them that they have to “get their act together” or else. Not least, university leaders have to explain to a larger public how Trumpists, in an unprecedented spree of national self-destruction, are busy preventing cancer cures, damaging American soft power, and killing one of the country’s major exports, namely higher education.

* NYTimes: Trump’s Attacks Have Helped Heal a Deeply Divided Harvard

[https://www.nytimes.com/2025/05/27/us/trump-attacks-unify-divided-harvard.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/27/us/trump-attacks-unify-divided-harvard.html?smid=nytcore-ios-share&referringSource=articleShare)

* Does the President Want to Fix Harvard or Destroy It? by @jasonrileywsj

[https://www.wsj.com/opinion/does-the-president-want-to-fix-harvard-or-destroy-it-0bf083d1?st=Ya1Vwx&reflink=article_gmail_share](https://www.wsj.com/opinion/does-the-president-want-to-fix-harvard-or-destroy-it-0bf083d1?st=Ya1Vwx&reflink=article_gmail_share)

(destroy... even the WSJ recognizes this...)

* NYTimes: Harvard and Trump Lawyers to Face Off in Court in Foreign Student Case

[https://www.nytimes.com/2025/05/29/us/harvard-trump-lawyers-hearing-foreign-students.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/29/us/harvard-trump-lawyers-hearing-foreign-students.html?smid=nytcore-ios-share&referringSource=articleShare)

> In the courtroom, Harvard’s strategy will use the president’s statements as evidence that the government is on a political crusade against the school. In briefs filed in the case, lawyers have argued Trump administration officials have unjustly singled out the university for punishment, violating its First Amendment rights. It has included the president’s aggressive comments as exhibits in its case.

> A visa ban would affect 7,000 students at Harvard. That includes 5,000 current students and another 2,000 in a program that allows students to stay and work for up to three years after they graduate.

* NYTimes: Harvard Says Many of Its Foreign Students Are Seeking to Transfer

[https://www.nytimes.com/2025/05/28/us/harvard-international-students-transfers.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/28/us/harvard-international-students-transfers.html?smid=nytcore-ios-share&referringSource=articleShare)

> The Trump administration’s efforts to halt Harvard University’s ability to enroll international students has sown “profound fear, concern, and confusion,” the university’s director of immigration services said in a court filing on Wednesday.

> Countless international students have asked about transferring, the director, Maureen Martin, wrote in the filing.

* NYTimes: Live Updates: Judge Will Block Trump From Barring Foreign Students at Harvard, For Now

[https://www.nytimes.com/live/2025/05/29/us/harvard-trump?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/live/2025/05/29/us/harvard-trump?smid=nytcore-ios-share&referringSource=articleShare)

### Columbia

* NYTimes: What to Know About Trump Officials’ Latest Move Against Columbia

[https://www.nytimes.com/2025/05/23/nyregion/columbia-trump-jewish-students.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/23/nyregion/columbia-trump-jewish-students.html?smid=nytcore-ios-share&referringSource=articleShare)


> The move on Thursday appeared to reflect the administration’s unusual approach to slashing federal funding to colleges.

> Historically, such cancellations would follow a lengthy review process. But, legal experts said, the Trump administration has not always adhered to standard procedure, taking swift action against universities’ finances and sometimes notifying news outlets before campus leaders.

(Id est: sanewashing.)

* NYTimes: Harvard Fight Illustrates Trump’s Worldview: If He Attacks, It’s Your Fault

[https://www.nytimes.com/2025/05/28/us/politics/harvard-university-trump-administration.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/28/us/politics/harvard-university-trump-administration.html?smid=nytcore-ios-share&referringSource=articleShare)

> The “last thing” he [large, orange hair] wants to do is harm the storied jewel of American higher education, he said. But he had no choice. The university was fighting back.

(By personalizing the battle, perhaps the wider assault goes unnoticed)

> It’s a constant in Mr. Trump’s worldview: If he goes after someone or something, it is their fault, not his. They are responsible for his actions. Not him.

* A federal judge has ruled that the Trump administration’s efforts to deport Columbia University demonstrator Mahmoud Khalil were likely unconstitutional

[https://www.wsj.com/us-news/mahmoud-khalil-deportation-unconstitutional-judge-194a0d4a?st=2MPd18&reflink=article_gmail_share](https://www.wsj.com/us-news/mahmoud-khalil-deportation-unconstitutional-judge-194a0d4a?st=2MPd18&reflink=article_gmail_share)


### Others

* NYTimes: Universities See Trump’s Harvard Move as a Threat to Them, Too

[https://www.nytimes.com/2025/05/24/us/harvard-trump-international-students-impact.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/24/us/harvard-trump-international-students-impact.html?smid=nytcore-ios-share&referringSource=articleShare)

> More than 5,000 miles away, Wendy Hensel, the president of the University of Hawaii, said that it was “reverberating across higher education.”

(Had to add this quote, as I miss our old provost.)

> To many academics, that was a clear signal that Mr. Trump was prepared to use any federal mechanism as leverage if he did not get what he wants.

> “While Harvard is the victim of the moment, it’s a warning and unprecedented attempt of a hostile federal government to erode the autonomy of all major universities in the U.S.,” said John Aubrey Douglass, a senior research fellow at the Center for Studies in Higher Education at the University of California, Berkeley.

(Again, this week's them. The Trump administration is all in; is higher ed?)

> While international students make up slightly more than 5 percent of university students nationwide, some of the nation’s most selective schools rely far more heavily on them. At New York University, home to nearly 60,000 students, one-third of them are international. At Columbia, about two in five students come from abroad. And at Harvard, more than a quarter of students come from across the globe.

> “This sends a signal to the rest of the world that not only is Harvard closed to the international best and brightest, but that the U.S. is not a welcome place for international students,” Mr. Lakhani said [admissions counselor in New York].

* Trump’s war on America’s Ivy League universities didn’t start with the 2023 anti-Israel protests. It was set off in 2019 by a sucker punch that left a man with a black eye.


[https://www.wsj.com/us-news/education/trump-college-university-federal-funding-fight-91c2a274?st=4xm3Hq&reflink=article_gmail_share](https://www.wsj.com/us-news/education/trump-college-university-federal-funding-fight-91c2a274?st=4xm3Hq&reflink=article_gmail_share)

(I'm sure this rationale was used by the Project 2025 authors...)


## Blowback

* Millions of Americans hit with bad credit after missed student loan payments

[https://www.washingtonpost.com/business/2025/05/25/credit-score-student-loan-elinquency-debt/](https://www.washingtonpost.com/business/2025/05/25/credit-score-student-loan-elinquency-debt/)

* House Republicans’ plan to hike taxes on university endowments could drive the biggest shift to endowments’ investment strategies in a generation

[https://www.wsj.com/us-news/education/universities-map-out-new-investment-strategies-to-deal-with-tax-hike-on-endowments-6638385a?st=KbEPvS&reflink=article_gmail_share](https://www.wsj.com/us-news/education/universities-map-out-new-investment-strategies-to-deal-with-tax-hike-on-endowments-6638385a?st=KbEPvS&reflink=article_gmail_share)

## Coming attractions?

* Medical School Accreditor Eliminates Diversity Standard

[https://www.insidehighered.com/news/quick-takes/2025/05/28/medical-school-accreditor-eliminates-diversity-standard](https://www.insidehighered.com/news/quick-takes/2025/05/28/medical-school-accreditor-eliminates-diversity-standard)

> The Liaison Committee on Medical Education, which is sponsored by the Association of American Medical Colleges and the American Medical Association, voted to stop evaluating diversity programs as a measure of a medical school's quality after “thoughtful and careful consideration and discussion,” according to a committee spokesperson.

* NYTimes: Beware: We Are Entering a New Phase of the Trump Era

[https://www.nytimes.com/2025/05/28/opinion/trump-danger-normalization-shock.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/28/opinion/trump-danger-normalization-shock.html?smid=nytcore-ios-share&referringSource=articleShare)

> I’m interested in something else: that moment when the shock fades and the (figurative) show goes on.

> Once you’ve wrapped your mind around the Trump administration’s revoking the legal status of individual international students, a blanket ban on international enrollment at Harvard isn’t entirely unexpected.

> And so just when we most need to act — while there is indeed room for action and some momentum to the resistance — we tend to be lulled into complacency by the sense of relief on the one hand and boredom on the other.

## Tracking projects

* DefendResearch

[https://docs.google.com/document/d/1Y5_fjGPNh4_1Hgc0Q68Hr2vJhVIOK1Qc-KynfIG6fZI/edit?usp=sharing](https://docs.google.com/document/d/1Y5_fjGPNh4_1Hgc0Q68Hr2vJhVIOK1Qc-KynfIG6fZI/edit?usp=sharing)

> This is a list of public statements supporting research and higher education against threats from the Trump administration. It includes a list of projects that track or monitor Trump administration actions on the same topics.


## And just because it is fun

* In Springsteen’s protest, a fitting Memorial Day plea

[https://www.washingtonpost.com/opinions/2025/05/25/springsteen-memorial-day-trump-america/](https://www.washingtonpost.com/opinions/2025/05/25/springsteen-memorial-day-trump-america/)

> Springsteen (who is apparently harder to intimidate than law firms, university presidents and media executives) decided to release an excerpt from the concert, titled “Land of Hope & Dreams,” making sure that his comments about Trump were the first things on it.

(Including)

> "They are abandoning our great allies and siding with dictators against those struggling for their freedom. They are defunding American universities that won’t bow down to their ideological demands"

(Also by a CUNY faculty)

[https://www.nytimes.com/2025/05/25/opinion/bruce-springsteen-trump-conflict.html](https://www.nytimes.com/2025/05/25/opinion/bruce-springsteen-trump-conflict.html)

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
