# May 16

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

Thanks for EI, KB, MP, VAC for sending along stories and details.


## Alliances

* More CUNY Senates have passed Mutual Defense Resolutions: Brooklyn, BMCC, LGCC, BCC, CSI,

(Wow; more than half the campuses. See the tracker the EI is keeping up to date [https://www.dropbox.com/scl/fo/my5g55jprx5o64r4vzus0/ABqQBAimqk_KN5t-EsUG8Ds/1.Mutual%20Defense%20Statements?dl=0&rlkey=zvsqtp7ev781y4rqqjti8xaho&subfolder_nav_tracking=1](https://www.dropbox.com/scl/fo/my5g55jprx5o64r4vzus0/ABqQBAimqk_KN5t-EsUG8Ds/1.Mutual%20Defense%20Statements?dl=0&rlkey=zvsqtp7ev781y4rqqjti8xaho&subfolder_nav_tracking=1))

* Mutual Academic Defense Compact tracker

[https://www.umass.edu/senate/madcs-tracker](https://www.umass.edu/senate/madcs-tracker)

(Thanks EI for sharing! Also shared is an[y] FGL whose governance body has passed an MADC wants to join the Rutgers email list, please get in touch with Paul Boxer at  pboxer@psychology.rutgers.edu. A zoom session this week was widely attended by CUNY faculty.)

## Something good for a change

* Rapid Response Bridge Funding Program

[https://www.spencer.org/grant_types/rapid-response-bridge-funding-program](https://www.spencer.org/grant_types/rapid-response-bridge-funding-program)

> we [Spencer Foundation] have developed a rapid response bridge grant opportunity for impacted scholars, in collaboration with The Kapor Foundation, The William T. Grant Foundation, and the Alfred P. Sloan Foundation. This rapid response bridge funding opportunity is for scholars and teams whose grants have recently been cancelled by NSF.

* ‘Nonsense Detectives’ Give Academic Resources New Life Online

[https://www.insidehighered.com/news/tech-innovation/libraries/2025/05/15/wikipedia-giving-academic-resources-new-life-online](https://www.insidehighered.com/news/tech-innovation/libraries/2025/05/15/wikipedia-giving-academic-resources-new-life-online)

(Thanks EI)

> Knipel: Wikipedia is one of the few places left on the internet where people with different viewpoints, including on politics, can come together and work on something positive. We share all of the facts. We’re not trying to push propaganda. I’m not trying to sell a product. I’m just trying to share as many facts as possible in as much context as possible. And that’s something that you can do on Wikipedia that you can’t do on conventional social media.

> We’re the No. 1 nonsense detectives on the internet. We try to see if information is actually backed up by a reliable source.

## How best to describe the times we are in

* America’s Great Brain Drain

[https://www.counterpunch.org/2025/05/09/americas-great-brain-drain/](https://www.counterpunch.org/2025/05/09/americas-great-brain-drain/)

(Thanks KB for this)

> “A few years ago, no one would have imagined that one of the biggest democracies in the world would cancel research programs under the pretext that the word ‘diversity’ was in this program.”  -- Macron

> The EU has officially launched a drive to attract scientists and researchers that America is discarding by the bucketful, s

> This is an extraordinary shrinking of America’s IQ in so many ways that a full understanding is nearly impossible, but it is only too obvious that deliberate destruction of science is the product of a bruised/intimidated mentality that’s seeking payback. There is no other logical explanation.

(Well, the argument of destroying competing power bases is another explanation. If a sharpie can be used to rewrite truth without pesky pushback...)

> The EU is licking its chops over this once-in-a-lifetime opportunity. According to EU Commission President Ursula von der Leyen, while on stage at Sorbonne University, the EU Executive Branch has already decided to set up a “super grant” program, aimed at “longer-term perspective to the very best in the field.”

> the Commission is authorizing additional funding of $566 million in 2025-2027, making Europe “a magnet for researchers.” This funding is in addition to the European Research Council’s budget of $18 billion for 2021-2027. Moreover, the EU will “enshrine freedom of scientific research into law” via a new enactment. Europe will not compromise on its long-standing principles of academic freedom.

> “The administration has issued a multi-pronged, anti-science attack on the health sciences. Possibly the most destructive is the recent slashing of research funding for both NIH and the National Science Foundation.” -- the Hill 3/2/2025

## Academic freedom

* Scientists Hail This Medical Breakthrough. A Political Storm Could Cripple It.

[https://www.nytimes.com/2025/05/08/us/mrna-vaccines-backlash-covid.html?unlocked_article_code=1.Gk8.5Dqo.MAoyAtC3MgsJ&smid=url-share](https://www.nytimes.com/2025/05/08/us/mrna-vaccines-backlash-covid.html?unlocked_article_code=1.Gk8.5Dqo.MAoyAtC3MgsJ&smid=url-share)

(Efforts to direct research away from something for political reasons)

> Short for messenger RNA, mRNA exists naturally in every cell of every living organism — its discovery in 1961 was also celebrated with a Nobel Prize. But its association with Covid has thrust it to the center of a political storm, buffeted by vaccine hesitancy and misinformation, anger over lockdowns and mandates, and the ascendance of the Make America Healthy Again movement in the Trump administration.

> States and federal health agencies are playing on public wariness about vaccines to cancel research into mRNA more broadly, indicating how much the lingering politicization of Covid is fueling the new attacks on science.

* Opinion | A.G. Sulzberger: A Free People Need a Free Press - The New York Times


[https://www.nytimes.com/2025/05/13/opinion/ag-sulzberger-free-press.html](https://www.nytimes.com/2025/05/13/opinion/ag-sulzberger-free-press.html)

> And the press is far from the only American institution that finds itself under pressure. We’re seeing direct efforts to go after government agencies, universities, cultural institutions, research organizations, advocacy groups and law firms. We’re even seeing challenges to the authority of Congress and the courts to serve as a check on executive power.


## Freedom of expression

* NYTimes: My Brush With Trump’s Thought Police

[https://www.nytimes.com/2025/05/13/opinion/stiglitz-trump-dei.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/13/opinion/stiglitz-trump-dei.html?smid=nytcore-ios-share&referringSource=articleShare)

(Where to categorize this ham-handed attempt to shut down discourse)

> The email arrived in early February from the U.S. Embassy in Copenhagen, carrying a blunt message. It informed the organizers of a Danish lecture series — one I was soon scheduled to speak at — that the final portion of American funding would be released only after they signed a statement essentially saying they were in compliance with a U.S. executive order banning diversity, equity and inclusion.

> Before the organizers at the University of Southern Denmark could respond, the U.S. State Department sent an even blunter message: The grant was “being terminated for the convenience of the U.S. government.” It concluded by thanking the Danes “for your partnering with the Department of State and God Bless America.”

> Second, the cutoff of funding was followed nearly two weeks later by another message to the university. (I viewed copies of all the emails.) It said that a recent court hearing prevented the State Department from holding up congressionally appropriated foreign aid funds and ordered it to make the financing available. It further ordered the department to “provide written notice of this order” to recipients of grants. Notifying the Danish university was as far as the administration went in complying with the court. The remaining funds haven’t been released yet, organizers say — typical of the Trump administration’s defiance of the courts.

> Another core element of freedom — indeed something essential to its survival — is that power must be limited; there have to be checks and balances not just within government but within society. I have long warned that the concentration of wealth among a small percentage of the population would provide a fertile field for a demagogue, and that there was an ample supply of people who might play the part.

> Universities, which protect academic freedom, are as important to this system of checks and balances as other civil rights protections like freedom of the press.

* NYU Withholds Diploma Due to Pro-Palestinian Commencement Speech

[https://www.insidehighered.com/news/quick-takes/2025/05/16/nyu-withholds-diploma-due-pro-palestinian-grad-speech](https://www.insidehighered.com/news/quick-takes/2025/05/16/nyu-withholds-diploma-due-pro-palestinian-grad-speech)

> Rozos spoke at the ceremony for the university’s Gallatin School of Individualized Study. He told the crowd he was “freaking out” about delivering the controversial speech, but that he felt a “moral and political” obligation to use the platform to speak out in support of Palestinians. Video of the speech shows graduates in caps and gowns clapping and cheering for Rozos and some giving him a standing ovation, though some boos and jeers can be heard off camera.

* NYTimes: Springsteen, in England, Blasts Trump Administration as ‘Treasonous’

[https://www.nytimes.com/2025/05/15/arts/music/bruce-springsteen-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/15/arts/music/bruce-springsteen-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

(Not anything to do with Higher Ed, but he is the boss...)

## Ownership of content


* Morelle’s Statement on Abrupt Firing of Shira Perlmutter, Register of Copyrights | Committee on House Administration

[http://democrats-cha.house.gov/media/press-releases/morelles-statement-abrupt-firing-shira-perlmutter-register-copyrights](http://democrats-cha.house.gov/media/press-releases/morelles-statement-abrupt-firing-shira-perlmutter-register-copyrights)

> no coincidence [Trump] acted less than a day after [Perlmutter] refused to rubber-stamp Elon Musk’s efforts to mine troves of copyrighted works to train AI models.” [Rep. Joe Morelle, the top Democrat on the House Administration Committee]

> Perlmutter and her office issued a lengthy report about artificial intelligence that included some questions and concerns about the usage of copyrighted materials by AI technology, an industry which Musk is heavily involved in.

> “This action once again tramples on Congress’s Article One authority and throws a trillion-dollar industry into chaos,” Morelle continued in a statement. “When will my Republican colleagues decide enough is enough?”

## Protests

* NY city and state lawmakers condemn CUNY chancellor after anti-Israel melee at Brooklyn College: ‘Step up or step down’

[https://nypost.com/2025/05/11/us-news/ny-lawmakers-condemn-cuny-chancellor-after-anti-israel-melee-at-brooklyn-college-step-up-or-step-down/](https://nypost.com/2025/05/11/us-news/ny-lawmakers-condemn-cuny-chancellor-after-anti-israel-melee-at-brooklyn-college-step-up-or-step-down/)

(The usual slanted Post take, not worth reading IMHO, save to learn that the group that beat up on CUNY last fall are back at it.)

> It is unacceptable but not surprising that almost two years after October 7th — after an investigation into CUNY and several public hearings — we are still grappling with disruptive and criminal behavior against Jewish students, encampments and masked agitators on campus,” reads a May 9 letter to Brooklyn College chancellor Félix V. Matos Rodríguez exclusively obtained by The Post.

> The letter was signed by Councilmembers Inna Vernikov, Farah Louis, Mercedes Narcisse, and Robert Holden, and Assemblymembers Kalman Yeger, Lester Chang, Eric Ari Brown, Jamie Williams and Alec Brook-Krasny.

## ICE

Opinion | I’m a Russian Scientist in ICE Detention - The New York Times


[https://www.nytimes.com/2025/05/13/opinion/ice-detention-russian-scientist.html](https://www.nytimes.com/2025/05/13/opinion/ice-detention-russian-scientist.html)

> I haven’t been in my lab or worked with my microscope since February, when I was detained by U.S. Immigration and Customs Enforcement as I was returning to Boston from a vacation in France. At Logan International Airport, I did not complete a customs declaration for frog embryos (for use in our lab’s research) in my luggage.

> Instead, my visa was revoked and I was sent to a detention center in Louisiana, where I have spent the past three months with roughly 100 other women. We share one room with dormitory-style beds.

> I’m used to spending up to 12 hours a day in the lab, talking with colleagues about tricky scientific questions and fine-tuning the algorithms used for NoRI. At the detention center, there is no access to computers and six phones are shared among all of us. The calls cost $5 for 15 minutes, at which point they cut off. It’s constantly noisy and cold. Fortunately, my beautiful colleagues have mailed me academic articles and books (I’m reading a wonderful one now about biochemistry called “Transformer” that I recommend to everyone).

## Funding cuts

* Can Scientific Research Survive Without Federal Funding?

[https://www.insidehighered.com/news/business/revenue-strategies/2025/05/12/can-scientific-research-survive-without-federal-funding](https://www.insidehighered.com/news/business/revenue-strategies/2025/05/12/can-scientific-research-survive-without-federal-funding)

> In February, the Yale School of Medicine began offering temporary funding to researchers with terminated grants—many related to topics the Trump administration has deemed unworthy of scientific inquiry, such as transgender health—to give them time to reorient their research. Yale’s Graduate School of Arts and Sciences is also investing $4 million to support graduate students who have lost training and research grants. Similarly, last month Johns Hopkins University announced that it is tapping earnings from its $13.2 billion endowment to give researchers $100,000 each for delayed grants, or $150,000 for terminated grants, during a 12-month period. And Northwestern University—which hasn’t received any grant payments from the National Institutes of Health since March—is offering faculty up to $50,000 to maintain projects for up to one year.

(Hopefully CUNY will be providing some relief in this manner as well)

> Over the past several decades, universities have already substantially increased the amount of money they spend on their own research and development—from 10 percent of the total in 1970 to 25 percent in 2023, according to federal data. Meanwhile, federal support for academic research has been on the decline, falling from 71 percent to 55 percent during that same timeframe. And support from industry, charities and other sources have always been marginal, collectively making up about 15 percent of contributions to research funding at colleges and universities in 2023.

> While that won’t cover all of the terminated grants, “the bridge has to go somewhere,” he said, explaining that the program isn’t supporting projects that don’t have viable alternative long-term funding options. Instead, “we’re providing funding for projects where the faculty member has other sources of funding and other proposals with the same or different federal agencies,” Díaz de la Rubia said. [At University of Arizona]

* Few support punitive funding cuts to colleges and universities

[https://apnorc.org/projects/few-support-punitive-funding-cuts-to-colleges-and-universities/?doing_wp_cron=1747067412.3431999683380126953125](https://apnorc.org/projects/few-support-punitive-funding-cuts-to-colleges-and-universities/?doing_wp_cron=1747067412.3431999683380126953125)

(Thanks EI)

> Six in 10 adults favor maintaining federal funding for scientific and medical research at colleges and universities while only about 3 in 10 support withholding federal funding from institutions for noncompliance with the president’s goals or removing their tax-exempt status.

> Sixty-four percent of adults think that colleges and universities make positive contributions to medical and scientific research and 63% feel they encourage new ideas and innovative technology.

(As they say in high school, are 36/37 percent of adults f***ing high)

> College graduates are more likely than those without a degree to think colleges and universities make a positive impact on medical and scientific research (79% vs. 55%),

* NYTimes: 9 Federally Funded Scientific Breakthroughs That Changed Everything

[https://www.nytimes.com/2025/05/16/science/federally-funded-science-breakthroughs.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/16/science/federally-funded-science-breakthroughs.html?smid=nytcore-ios-share&referringSource=articleShare)

(GPS,...)

### House bills

* Congress Could Make Paying for College Even More Complicated

[https://www.insidehighered.com/news/government/student-aid-policy/2025/05/12/how-congress-could-make-paying-college-more](https://www.insidehighered.com/news/government/student-aid-policy/2025/05/12/how-congress-could-make-paying-college-more)

> The reconciliation proposal would also put new limits on federal loans for students, severely restricting Parent PLUS loans and restricting the amount of federal loans students can receive.

> “If they fall below the cap, students will now have to make up the difference through private loans, around 90 percent of which require a co-signer with good enough income and assets,” she said. “So this is going to cut out low-income students, students who can’t get co-signers and people who aren’t willing to take out a private loan.”

* Significant Endowment Tax Increase Looms

[https://www.insidehighered.com/news/government/politics-elections/2025/05/10/house-republicans-propose-significant-endowment-tax](https://www.insidehighered.com/news/government/politics-elections/2025/05/10/house-republicans-propose-significant-endowment-tax)

> Under the proposed formula, institutions with endowments of $750,000 to $1.25 million per student would reportedly be hit with 7 percent excise tax. That number would climb to a 14 percent tax for colleges with endowments valued at $1.25 to $2 million per student. Colleges at the highest level with endowments of $2 million or more per student would pay 21 percent. (Currently, colleges with endowments worth $500,000 per student or more pay the 1.4 percent tax.)

(This is for private colleges. I don't know how this would compare to NYC efforts to close real-estate tax breaks at big privates)


* Here’s What Republicans’ Proposed College-Endowment Tax Could Look Like

[https://www.chronicle.com/article/heres-what-republicans-proposed-college-endowment-tax-could-look-like](https://www.chronicle.com/article/heres-what-republicans-proposed-college-endowment-tax-could-look-like)

> Republican lawmakers see expanding the college-endowment tax as a way to raise revenue and cover tax cuts elsewhere. College leaders argue that increasing the tax rate would harm students by hampering institutions’ ability to offer generous financial aid, which often comes out of endowment earnings.

> According to the National Association of College and University Business Officers, nearly half of colleges’ endowment spending in 2024 went to financial aid, with another 18 percent supporting academic programs and 11 percent paying for endowed faculty positions.

* Republicans eye major expansion of college endowment tax


[https://www.politico.com/live-updates/2025/05/09/congress/republicans-eye-massive-expansion-of-college-endowment-tax-00339060](https://www.politico.com/live-updates/2025/05/09/congress/republicans-eye-massive-expansion-of-college-endowment-tax-00339060)


> The slew of endowment taxes comes as Republicans are struggling to find revenue to fund tax cuts and other elements of a megabill carrying President Donald Trump’s policy priorities.


* GOP proposes five-fold increase in tax on college endowments

[https://www.washingtonpost.com/education/2025/05/12/gop-college-endowment-tax/](https://www.washingtonpost.com/education/2025/05/12/gop-college-endowment-tax/)

(And again...)

### Executive orders

* Trump DEI policies threaten millions in scholarships raised by Black doctors

[https://www.washingtonpost.com/nation/2025/05/13/black-doctors-scholarship-ohio/](https://www.washingtonpost.com/nation/2025/05/13/black-doctors-scholarship-ohio/)

### Research funding

* Bridge the gap’: After federal grant freeze, CUNY union seeks city funding lifeline to continue research | amNewYork

[https://www.amny.com/education/federal-grant-freeze-cuny-union-funding/](https://www.amny.com/education/federal-grant-freeze-cuny-union-funding/)

* CUNY warns $17M in research grants at risk after Trump stop-work orders

[https://www.nydailynews.com/2025/05/15/cuny-warns-17m-in-research-grants-at-risk-after-trump-stop-work-orders/](https://www.nydailynews.com/2025/05/15/cuny-warns-17m-in-research-grants-at-risk-after-trump-stop-work-orders/)

(If I have this right, 17M has been yanked so far. Thanks VAC)

### NSF

* Why I’m Resigning from the NSF and Library of Congress | TIME


[https://time.com/7285045/resigning-national-science-foundation-library-congress/](https://time.com/7285045/resigning-national-science-foundation-library-congress/)

> Freedom of expression is not merely an abstract principle, or even a constitutional right, but a practical necessity for meaningful advisory work. In Ray Bradbury's Fahrenheit 451, published as short stories in the late 1940s and as a novel in 1953, warned not only of the destruction of books, but of a society in which people had lost the desire to read them. The parallel today is not only the administration’s effort to destroy and suppress knowledge, but also the institution’s willingness to accept the cultivated irrelevance of it—a challenge that undermines any serious effort to conduct research, inform policy, or guide public institutions.

> The National Science Foundation (NSF)—established as an independent agency through the National Science Act of 1950 and marking its 75th anniversary this week—traces its roots to Vannevar Bush’s landmark report, “Science, the Endless Frontier,” addressed to President Harry S. Truman. But we might also see the establishment of this premier research institution as reflecting a response to fears depicted by Bradbury. The NSF can be understood not only as a catalyst of scientific promise for national purpose, but also as a guarded response to fears about centralized control over knowledge and thought, shaped by the dark shadows of the Third Reich and the emerging Red Scare.

> Last week, as the Board held its 494th meeting, I listened to NSF staff say that DOGE had by fiat the authority to give thumbs up or down to grant applications which had been systematically vetted by layers of subject matter experts.

> Our closed-to-the-public deliberations were observed by Zachary Terrell from the DOGE team. Through his Zoom screen, Terrell showed more interest in his water bottle and his cuticles than in the discussion. According to Nature Terrell, listed as a "consultant" in the NSF directory, had accessed the NSF awards system to block the dispersal of approved grants. The message I received was that the National Science Board had a role to play in name only.

> All of this is threatened by the creeping normalization of authoritarian approaches to knowledge management and academic freedom. The National Science Board has not been disbanded like so many other statutorily established, independent agencies in the federal government. But preservation of form provides little consolation when function has been strategically neutralized, mirroring the backsliding that scholars have thoroughly documented: maintaining legitimacy for institutions that no longer honor their founding purposes. This hollowing out is not just about governance in the abstract, it has material consequences for which research questions get asked, which datasets get produced, which knowledge gets produced, and which perspectives shape our understanding of pressing societal challenges. It has consequences for the integrity of knowledge itself.

> Last week, the Librarian of Congress, Dr. Carla Hayden, was summarily dismissed via an email addressed to “Carla” from a White House HR administrator. The Trump Administration claimed that she was fired for “things she had done at the Library of Congress in the pursuit of DEI and putting inappropriate books in the library for children.” It is true that Hayden was repeatedly on record as saying the Library should be for all Americans. And it is false that the Library, which is intended to hold all books published in the United States, lends books to children. The ouster of Hayden is part of a broader pattern of political targeting of women and Black public servants across the federal government.

* NYTimes: Trump Administration Cancels Scores of Grants to Study Online Misinformation

[https://www.nytimes.com/2025/05/15/business/trump-online-misinformation-grants.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/15/business/trump-online-misinformation-grants.html?smid=nytcore-ios-share&referringSource=articleShare)

> Last month, the National Science Foundation, a government agency that finances much of the scientific research in the United States, began canceling hundreds of grants. Most focused on studies involving issues of diversity, equity and inclusion, but scores singled out work on online content.

> The cancellation has jeopardized research in universities in virtually every state, leaving researchers scrambling to find funding for projects that in many cases are only partly completed.

> Each Friday since then, the foundation has announced new cancellations. It has now cut more than 1,400 grants, including 75 more last Friday. In all, the grants were worth more than $1 billion, according to a list compiled by two researchers, Scott W. Delaney, an epidemiologist at Harvard’s Chan School of Public Health, and Noam Ross, the executive director of rOpenSci, a nonprofit software foundation. None of the grant abstracts reviewed by The New York Times called for censoring content.

### NIH

* Trump Cuts Off Budding CUNY Scientists From Mentorship and Aid

[https://www.thecity.nyc/2025/05/14/cuny-urise-science-research-nih-trump/](https://www.thecity.nyc/2025/05/14/cuny-urise-science-research-nih-trump/)

> The Trump administration has cut off support that has sustained a teaching model that for decades has been instrumental in catapulting students into careers as scientists.

> Funded by the National Institutes of Health (NIH), the Undergraduate Research Training Initiative for Student Enhancement (U-RISE) supports the pursuit of advanced degrees by students in the biomedical field, who are offered tuition assistance, mentorship, registration to professional conferences and, crucially, lab experience.

> NIH canceled all U-RISE funding at City College, Queens College, Brooklyn College, Lehman College and Medgar Evers College. ... Professors who work with students in the program say the federal defunding will likely doom the program, and with it vital opportunities to conduct research while attending a public college — putting them on track for further academic research.

> “University leadership is working to support everyone in our community and will pursue every avenue available to sustain CUNY as a preeminent research institution,” wrote Noah Gardy.

### NEH

* NEH Announces Grant Opportunity to Create Statues of Iconic Americans for the National Garden of American Heroes | National Endowment for the Humanities


[https://www.neh.gov/news/neh-announces-grant-opportunity-create-statues-iconic-americans-national-garden-american](https://www.neh.gov/news/neh-announces-grant-opportunity-create-statues-iconic-americans-national-garden-american)


(This isn't new, but still galling)

* The NIH Is Requiring Grantees to Follow Trump’s Anti-Trans Executive Order

[https://www.chronicle.com/article/the-nih-is-requiring-grantees-to-follow-trumps-anti-trans-executive-order](https://www.chronicle.com/article/the-nih-is-requiring-grantees-to-follow-trumps-anti-trans-executive-order)

>  And she [researcher at a teaching hospital] learned that the grantee was expected to comply with the gender-equity law Title IX — “including the requirements set forth in Presidential Executive Order 14168 titled Defending Women From Gender Ideology Extremism and Restoring Biological Truth to the Federal Government.” That’s the executive order President Trump signed on the first day of his second term, directing the government to recognize two sexes, male and female.

> The new policies apply to institutions that accept funds on scientists’ behalf, according to two lawyers who reviewed the language. So if a university accepts a grant with these terms, it could be at risk if the government considers anyone at that campus — not just the scientist spending the money — to be perpetuating “DEI” or “gender ideology extremism.”

> The NIH reserves the right to “terminate financial assistance awards and recover all funds,” states its April 21 policy on diversity. And the term sheet citing the anti-transgender executive order states that payments “are predicated on compliance with the above requirements.” It says that violators can be held liable criminally as well as under the False Claims Act, the anti-government defraudment law.

> A spokesperson for the Association of American Universities, which represents research universities, said that the organization was aware of the language, but declined to comment further.

### DOE

* Trump Nominates Iowa Regent to be Assistant Secretary of Postsecondary Ed

[https://www.insidehighered.com/news/quick-takes/2025/05/12/trump-nominates-assistant-secretary-postsecondary-ed](https://www.insidehighered.com/news/quick-takes/2025/05/12/trump-nominates-assistant-secretary-postsecondary-ed)

> [David] Barker would focus on improving outcomes and accountability by reforming accreditation, improving federal student aid programs and ensuring grant programs match the Trump administration’s priorities.

> Barker was an Iowa regent for six years where he advanced cost control measures, promoted academic freedom and ended “discriminatory DEI programs,” according to the release.

(On wikipedia [https://en.wikipedia.org/wiki/David_R._Barker] we can read about what planet this guy lives on: "Barker is the author of Welcome to Free America, a book set in 2057 as a guide to immigrants coming to the former United States after the collapse of government. It describes a difficult period of transition, but eventually, private companies take over functions previously performed by governments, such as security, dispute resolution, production of money and infrastructure, and national defense.")

### DOGE

* The hidden ways Trump, DOGE are shutting down parts of the U.S. government

[https://www.washingtonpost.com/nation/2025/05/11/trump-government-operations-halt-funding-cuts/](https://www.washingtonpost.com/nation/2025/05/11/trump-government-operations-halt-funding-cuts/)

(Nothing higher ed related, but similar things are reported with grants. This speaks to slow-rolling payments; new processes of human oversight which can't possibly scale so backlogs get built.)

## Can't we all just get along?

### Harvard

* NYTimes: Harvard Adds to Legal Complaint Against Trump Administration

[https://www.nytimes.com/2025/05/13/us/harvard-trump-lawsuit.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/13/us/harvard-trump-lawsuit.html?smid=nytcore-ios-share&referringSource=articleShare)


* Trump administration strikes back at Harvard with a $450 million cut


[https://www.washingtonpost.com/education/2025/05/13/trump-administration-cuts-harvard-funding/](https://www.washingtonpost.com/education/2025/05/13/trump-administration-cuts-harvard-funding/)

* NYTimes: As Harvard Battles Trump, Its President Will Take a 25% Pay Cut

[https://www.nytimes.com/2025/05/14/us/harvard-garber-trump-pay.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/14/us/harvard-garber-trump-pay.html?smid=nytcore-ios-share&referringSource=articleShare)

* NYTimes: Harvard Law Paid $27 for a Copy of Magna Carta. Surprise! It’s an Original.

[https://www.nytimes.com/2025/05/15/world/europe/harvard-law-magna-carta-original.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/15/world/europe/harvard-law-magna-carta-original.html?smid=nytcore-ios-share&referringSource=articleShare)

(Wait a bit of cheer during all this doomscrolling?)

* Federal agencies continue terminating all funding to Harvard - Ars Technica

[https://arstechnica.com/science/2025/05/feds-continue-effort-to-defund-research-at-harvard/](https://arstechnica.com/science/2025/05/feds-continue-effort-to-defund-research-at-harvard/)

(Back to doom scrolling...)

> It's generally difficult to understand the big picture of these cuts and the reasons for them from this announcement.

(But you can try yourself)

[https://storage.courtlistener.com/recap/gov.uscourts.mad.283718/gov.uscourts.mad.283718.59.9.pdf](https://storage.courtlistener.com/recap/gov.uscourts.mad.283718/gov.uscourts.mad.283718.59.9.pdf)

* Harvard’s Battle With Trump Escalates as Research Money Is Suddenly Canceled

[https://www.chronicle.com/article/harvards-battle-with-trump-escalates-as-research-money-is-suddenly-canceled](https://www.chronicle.com/article/harvards-battle-with-trump-escalates-as-research-money-is-suddenly-canceled)

> “I think the reasoning behind this termination had more to do with the Harvard name as a symbol of elite academia than the content of our research,” Baym [wuns a Harvard Medical School lab] said. “I think this is entirely for symbolic value. It’s hard to see who in the United States benefits from cutting medical research.”

### Columbia

* NYTimes: NASA Office Above ‘Seinfeld’ Diner Is a Target of Trump Budget Shrinkage

[https://www.nytimes.com/2025/05/16/nyregion/nasa-office-columbia-seinfeld-toms-restaurant.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/16/nyregion/nasa-office-columbia-seinfeld-toms-restaurant.html?smid=nytcore-ios-share&referringSource=articleShare)

> NASA has told the more than 100 people who work at its Goddard Institute for Space Studies that they have to leave Armstrong Hall, a Columbia University-owned building at Broadway and West 112th Street, by the end of May.

> The building is better known to TV viewers as the home of Tom’s Restaurant, the diner whose facade appears in “Seinfeld” episodes, and to Gen Xers as the place that inspired Suzanne Vega’s 1980s song, “Tom’s Diner.”

### Dartmouth

* NYTimes: How One Ivy League University Has Avoided Trump’s Retribution So Far

[https://www.nytimes.com/2025/05/11/us/politics/dartmouth-college-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/11/us/politics/dartmouth-college-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> Six of the eight Ivies are facing major funding threats, to the tune of billions of dollars, as the federal government attempts to punish them over concerns about antisemitism and other issues. Harvard University alone could lose over $2 billion. And every Ivy but Dartmouth is being investigated over allegations that they have allowed antisemitism on campus.

> And Dr. Beilock appears to have carefully positioned her school in territory friendly to conservatives. She has hired a former Republican Party official for a key administrative job, focused on free expression in her public messages and taken a hard-line approach toward protesters. She has also sought friends in high places.

> “I was so impressed to learn how Dartmouth (my alma mater) is getting it right, after all these years,” Harmeet Dhillon, a Trump loyalist who heads the Justice Department’s civil rights division, wrote on social media last week. [Harmeet Dhillon is a Dartmouth Grad and overseeing the decimation at the OCR[

### Penn State

* Facing $20M Loss, Penn State Declares Support for Lawsuit Against NSF Over Research Funding Cut (Thanks MP)

[https://www.statecollege.com/articles/psu-news/facing-20m-loss-penn-state-declares-support-for-lawsuit-against-nsf-over-research-funding-cut/#google_vignette](https://www.statecollege.com/articles/psu-news/facing-20m-loss-penn-state-declares-support-for-lawsuit-against-nsf-over-research-funding-cut/#google_vignette)

> Penn State has submitted a declaration of support for a joint lawsuit that seeks to halt the Trump administration’s decision to significantly cut payments for costs associated with National Science Foundation-funded research grants and cooperative agreements.

> The university, which is not a party to the lawsuit, said in a statement that based on its NSF funding for fiscal year 2023-24, the cut would mean a $20 million loss for Penn State’s research enterprise.

> The NSF announced on May 2 that it would cap reimbursements for indirect costs — which include expenses such as specialized research equipment and facilities, operations and maintenance and administrative functions — at 15% for new grant awards made after May 5. The change, according to the NSF, “is intended to streamline funding practices, increase transparency, and ensure that more resources are directed toward direct scientific and engineering research activities.”


## The long game

* Qatar has showered money on the U.S.’s military and universities, giving the tiny Gulf state outsize geopolitical clout


[https://www.wsj.com/world/middle-east/qatar-us-influence-spending-7a64dd75?st=JmAtR8&reflink=article_gmail_share](https://www.wsj.com/world/middle-east/qatar-us-influence-spending-7a64dd75?st=JmAtR8&reflink=article_gmail_share)

> Around the same time that the base was gearing up, Qatar began paying top U.S. universities to operate campuses on Qatari territory. It is now the single largest foreign funder of American universities, according to U.S. Education Department data, providing more than $6 billion over the past 15 years through gifts or contracts with schools including Cornell, Georgetown and Northwestern.

> The outsize higher-education funding levels have drawn criticism since the start of Israel’s war in Gaza from Republican lawmakers and the Trump administration over allegations that the money from Qatar and other Arab states was skewing teaching about Israel and the region. Education Secretary Linda McMahon singled out Qatar in an April 23 statement on an executive order expanding oversight on foreign education gifts.

> Ansari denied that Qatar interferes in the curriculum of any U.S. educational institution or has any influence on U.S. universities, calling that “deliberate misinformation” by “a campaign of bad actors” aiming to weaken the U.S. relationship and undermine Qatar’s mediation role in the Gaza war.

(Not simply fake news, but bad actors)

## Blowback

* NYTimes: The World Is Wooing U.S. Researchers Shunned by Trump

[https://www.nytimes.com/2025/05/14/business/economy/trump-research-brain-drain.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/14/business/economy/trump-research-brain-drain.html?smid=nytcore-ios-share&referringSource=articleShare)

* NYTimes: We Study Fascism. And We’re Leaving the U.S.

[https://www.nytimes.com/2025/05/14/opinion/yale-canada-fascism.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/14/opinion/yale-canada-fascism.html?smid=nytcore-ios-share&referringSource=articleShare)

* NYTimes: For Some International Students, U.S. Dreams Dim Under Trump

[https://www.nytimes.com/2025/05/16/world/europe/us-international-students-college-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/16/world/europe/us-international-students-college-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> Now, Mr. Wattoo said, he plans to return to Pakistan next week, after he receives his degree. His parents, worried about being harassed at the border, decided against traveling to Berkeley to attend his graduation on Friday, he said.

> “That respect in the American system has kind of faded away and been replaced with this bitter animosity,” Mr. Wattoo said. He described the Trump administration’s tactics as “shockingly similar to what I’ve seen all my life and what I wanted to run away from.”

## Coming attractions?

* Trump admin backs Jewish professor's discrimination case against CUNY school

[https://nypost.com/2025/05/14/us-news/trump-admin-backs-jewish-professors-discrimination-case-against-cuny-school/](https://nypost.com/2025/05/14/us-news/trump-admin-backs-jewish-professors-discrimination-case-against-cuny-school/)

(This unusual amicus brief is related to student protests at Hunter College just after 10/7)

* There’s a Darker Reason Trump Is Going After Those Law Firms

[https://www.nytimes.com/2025/05/15/opinion/trump-law-firms-attacks.html?unlocked_article_code=1.Hk8.JFo6.yLdE49DTjkdG&smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/15/opinion/trump-law-firms-attacks.html?unlocked_article_code=1.Hk8.JFo6.yLdE49DTjkdG&smid=nytcore-ios-share&referringSource=articleShare)

> This is no accident. These orders use the pretense of punishing Mr. Trump’s perceived enemies to pursue the far more comprehensive goal of controlling pro bono work, the lifeblood of legal aid and public-interest law organizations, which depend on pro bono support to promote access to justice and defend the values of liberal democracy. This targeting replaces the ideal of pro bono publico, literally “for the public good,” with pro bono Trump.

(thanks VAC)

* McMahon Sharpens Tone on Accreditation

[https://www.insidehighered.com/news/governance/accreditation/2025/05/16/mcmahon-sharpens-tone-accreditation](https://www.insidehighered.com/news/governance/accreditation/2025/05/16/mcmahon-sharpens-tone-accreditation)


> “It does seem that Secretary McMahon is using some talking points from five or six years ago. The regions are history. That said, accreditation is a complicated and obscure topic, so I’m not surprised that it is taking a while for her to grasp it all while awaiting the confirmation of an undersecretary with more higher education policy experience,” Shireman wrote [senior fellow at the progressive Century Foundation ].


* The Trump Administration Widens Its Scrutiny of Colleges, With Help From the Internet

[https://www.chronicle.com/article/the-trump-administration-widens-its-scrutiny-of-colleges-with-help-from-the-internet](https://www.chronicle.com/article/the-trump-administration-widens-its-scrutiny-of-colleges-with-help-from-the-internet)

> On May 8, the Department of Education announced an investigation of Western Carolina University, a comprehensive public institution in Cullowhee, North Carolina. The university, it alleged, had violated Title IX by allowing transgender female students in women’s restrooms, locker rooms, and dorm rooms.

> Payton McNabb, a former student whose complaints about WCU’s transgender policies brought conservative media attention to the university, said she didn’t experience WCU as quiet. She felt professors treated conservative students differently, and she was hurt by a university Title IX investigation into her conduct after she posted a video of herself asking a transgender woman why she was in a women’s bathroom on campus.

> The emails that seem to have triggered the Department of Education’s investigation have been framed by Speech First [a group dedicated to protecting the expression of certain conservative stances at colleges] as evidence that WCU is deliberately defying President Donald Trump.

> The Department of Education’s scrutiny “feels punitive,” Gómez [secretary for the Faculty Senate] said. “It feels like this is part of a trend to both try to dismantle higher education and to ultimately undermine faculty governance and academic freedom.” The department’s Title IX investigation is related to faculty governance, Gómez said, because the Faculty Senate had previously supported an effort to make campus bathrooms more welcoming to transgender people.

* On Student Aid, It’s Congressional Republicans vs. DOGE

[https://www.chronicle.com/article/on-student-aid-its-congressional-republicans-vs-doge](https://www.chronicle.com/article/on-student-aid-its-congressional-republicans-vs-doge)

> The House Committee on Education & Workforce recently drafted legislation that would cut $350 billion in student aid. The savings come mostly from increasing loan-payment requirements and making it harder to qualify for Pell Grants. As others have explained, these measures will harm the lowest-income borrowers and reduce college access. If the committee has its way, the cuts will be bundled into a reconciliation bill in which these savings would pay for tax cuts tilted heavily toward the wealthy.

> another surprising roadblock to the House accountability provisions should loom large: ...DOGE. ... Now that DOGE has forced out half the Education Department’s staff and President Trump is looking to eviscerate it, such execution will be out of reach. In other words, today’s Republican Party has a lot of different factions, but they can’t all win: If conservative lawmakers mean for the department to implement the accountability ideas in their current proposal, they will need to confront the Trump administration.

## Tracking web sites

* Surely Not?

[https://www.nybooks.com/articles/2025/05/29/surely-not-manchurian-candidate-president/](https://www.nybooks.com/articles/2025/05/29/surely-not-manchurian-candidate-president/)

(VAC says this is worth reading, though it is behind a paywall.)

> Imagine that the president of the United States was a “Manchurian candidate,” an embedded foreign agent determined to wreak maximum damage on the country and limited only by the need not to act so outrageously and preposterously as to blow his cover. What are some of the things that even a Manchurian candidate would hesitate to do?


----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.
