# May 9

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week. Sadly it is just too easy to make these digest too long to digest.

Thanks to BE, VAC, EI, EST, ... for their contributions.


## Letters/Statements

* Several CUNY senates have passed alliance resolutions

[https://www.dropbox.com/scl/fo/my5g55jprx5o64r4vzus0/ABqQBAimqk_KN5t-EsUG8Ds/1.Mutual%20Defense%20Statements?dl=0&rlkey=zvsqtp7ev781y4rqqjti8xaho&subfolder_nav_tracking=1](https://www.dropbox.com/scl/fo/my5g55jprx5o64r4vzus0/ABqQBAimqk_KN5t-EsUG8Ds/1.Mutual%20Defense%20Statements?dl=0&rlkey=zvsqtp7ev781y4rqqjti8xaho&subfolder_nav_tracking=1)

Thanks to EI for maintaining this list. New this week is John Jay


## Alliances

* ‘At this point, we are a liberal democracy in decline’

[https://www.washingtonpost.com/opinions/2025/05/05/larry-diamond-trump-america-democracy/](https://www.washingtonpost.com/opinions/2025/05/05/larry-diamond-trump-america-democracy/)

Interview with Larry Diamond

> Right now, if you are not at a university, if you’re not at a law firm, if you are not a member of Congress who is getting death threats and warnings of political obliteration if you don’t vote in lockstep with the MAGA movement, if you are not a journalist getting abuse and potential exclusion from the government, if you’re not a career Foreign Service officer or a civil servant who has dedicated their lives to serving the country in nonpartisan fashion and you’re now being purged or fired — if you’re not any of those kinds of people, your life goes on, except maybe you’re paying higher prices or seeing your 401(k) fall because of Trump’s erratic policies on tariffs. So, you can say that, in terms of the loss of freedom, most people feel unaffected. But what we need to get our fellow citizens to see is that it’s all connected, and that when due process is undermined even for a noncitizen, ultimately it can put everyone’s freedom in jeopardy. What lessons do you draw from other countries such as Hungary, India, Poland, Brazil, the Philippines, Turkey and Venezuela, all of which have seen democratic backsliding over the past few decades?

> The lessons are that people should unify and coordinate as quickly as possible. The more that institutions under threat try to just go their own way or duck for cover, the more they’ll be divided and picked off one by one. The sooner that people rally in coordination and in principled defense of the Constitution and the rule of law, the better the prospect that they will be able to contain and reverse the authoritarian project.

* NYTimes: What Happened When Trump Altered the Deal With Law Firms and Universities

[https://www.nytimes.com/2025/05/06/world/europe/what-happened-when-trump-altered-the-deal-with-law-firms-and-universities.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/06/world/europe/what-happened-when-trump-altered-the-deal-with-law-firms-and-universities.html?smid=nytcore-ios-share&referringSource=articleShare)


(In short, the prisoner's dilemma doesn't apply when negotiating with the mafia.)



## How best to describe the times we are in

* NYTimes: Trump Battles Academia, but Especially the Ivy League

[https://www.nytimes.com/2025/05/04/us/politics/trump-ivy-league.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/04/us/politics/trump-ivy-league.html?smid=nytcore-ios-share&referringSource=articleShare)

> Timothy L. O’Brien, a biographer of Mr. Trump, said the president’s ire about the upper echelon of academia was not surprising. “He has a long track record of criticizing elites that he desperately wants to be accepted by,” Mr. O’Brien said. As far as the Ivy League, he said, “he could barely wait to get in himself.”

(Not sure this is why; I personally believe things are related to a desire to control competing power bases.)

### Anti-woke/anti-DEI is simply racism

* President Trump fires Librarian of Congress Carla Hayden | AP News

[https://apnews.com/article/donald-trump-library-of-congress-carla-hayden-20a1862ce6d2e0d51a84a37b264ce2ef](https://apnews.com/article/donald-trump-library-of-congress-carla-hayden-20a1862ce6d2e0d51a84a37b264ce2ef)

* NYTimes: Trump Declares High-Speed Internet Program ‘Racist’ and ‘Unconstitutional’

[https://www.nytimes.com/2025/05/08/us/politics/trump-biden-digital-equity-act.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/08/us/politics/trump-biden-digital-equity-act.html?smid=nytcore-ios-share&referringSource=articleShare)


## Academic freedom

* Texas lawmakers moving to greatly increase control of state universities


[https://wapo.st/4d48IaK](https://wapo.st/4d48IaK)

> Conservative lawmakers, who control all levers of government, are advancing a measure they say would hold institutions more accountable and ensure curriculum is “free from ideological bias.” Faculty could be removed or face civil penalties for violations. Schools that fail to comply could be barred from spending state funds.

> Opponents say the result would essentially be a takeover of the state’s 126 public universities, community college districts and medical schools, with state officials even allowed to overturn hiring decisions. They fear it could damage the institutions’ reputations and lead to a faculty brain drain.

> His (Brandon Creighton) new proposal aims to decrease the power of faculty senates, requiring that half of their members be appointed by school presidents. All would be term-limited, advisory only and removable by top administrators for “political advocacy.”

> Another provision would give the Texas Higher Education Coordinating Board — composed of nine gubernatorial appointees — the ultimate say in faculty and academic screening. The board would pay special attention to schools’ required core curriculum, to ensure they “do not require or attempt to require a student to adopt a belief that any race, sex, or ethnicity or social, political, or religious belief is inherently superior.”

> Complaints lodged against professors would be investigated by a new state ombudsman and the attorney general, currently Ken Paxton (R), an ultraconservative Trump ally.

> “Texas is as broad-reaching a legislative endeavor as we’ve seen,” he (Professor Peter Lake, Stetson University) said. And combined with Trump’s attacks on higher education, the legislation is likely to “embolden red states to experiment with even more control over institutional autonomy, right down to curriculum, hiring and firing, tenure, curriculum review.”

> UT System Chancellor James B. Milliken also is departing after seven years to become president of the University of California.

* New State Laws Target DEI, Struggling Academic Programs, and Tenure

[https://www.chronicle.com/article/new-state-laws-target-dei-struggling-academic-programs-and-tenure](https://www.chronicle.com/article/new-state-laws-target-dei-struggling-academic-programs-and-tenure)

> “It fits into a picture with many, many aspects of attempts to control higher education and intellectual and academic freedom,” said Risa Lieberwitz, a professor of labor and employment law at Cornell University and a member of the American Association of University Professors’ committee on academic freedom and tenure.

States mentioned:  Arkansas, Kentucky, Ohio, Wyoming, Kentucky, North Dakota, and Utah. (Saving Texas for later...)

## Protests

* Facing New Protests and Political Pressure, Colleges Are Taking a Harder Line

[https://www.chronicle.com/article/facing-new-protests-and-political-pressure-colleges-are-taking-a-harder-line](https://www.chronicle.com/article/facing-new-protests-and-political-pressure-colleges-are-taking-a-harder-line)

> Pro-Palestinian protests at three colleges in the past several days led to more than 100 arrests for trespassing or destruction of property. Several students were also suspended for violating their college’s policies and protest restrictions.

(This does not include 12 people arrested at Brooklyn College Thursday night)

[https://www.nytimes.com/2025/05/08/nyregion/protest-brooklyn-college-arrests.html](https://www.nytimes.com/2025/05/08/nyregion/protest-brooklyn-college-arrests.html)

> The police moved in to make arrests after demonstrators left the college grounds and gathered outside. Officers punched some students and slammed others to the ground.

> The police moved in to make arrests after demonstrators left the college grounds and gathered outside. Officers punched some students and slammed others to the ground.

> A police spokesman said college officials had requested that the police respond to the campus shortly before 5 p.m. A precise number of arrests was not available Thursday evening. He declined to comment on the physical altercations or on the officer’s apparent use of a Taser.

(It also seems to make this adminstration happy, as both the wapo and WSJ reported)

* Trump administration praises Columbia’s response to protest after arrests

[https://www.washingtonpost.com/education/2025/05/08/columbia-university-protest-trump-administration/](https://www.washingtonpost.com/education/2025/05/08/columbia-university-protest-trump-administration/)

* The Trump administration praised Columbia University’s “strong and resolute” response to a pro-Palestinian campus protest Wednesday

[https://www.wsj.com/us-news/education/columbia-protests-trump-8fc01720?st=5vTGKq&reflink=article_gmail_share](https://www.wsj.com/us-news/education/columbia-protests-trump-8fc01720?st=5vTGKq&reflink=article_gmail_share)


## SEVIS VISA uncancellation

* ICE Expands Student Deportation Powers

[https://www.insidehighered.com/news/global/international-students-us/2025/05/02/new-ice-policy-puts-international-students-greater](https://www.insidehighered.com/news/global/international-students-us/2025/05/02/new-ice-policy-puts-international-students-greater)

> It could foreshadow a new round of deportation efforts.

## Funding cuts

* NYTimes: Where Federal Dollars Flow to Universities Around the Country

[https://www.nytimes.com/interactive/2025/04/30/us/university-funding-research.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/interactive/2025/04/30/us/university-funding-research.html?smid=nytcore-ios-share&referringSource=articleShare)

(Thanks VAC)

* Documenting Trump’s ‘Arbitrary’ Cuts to Science

[https://www.insidehighered.com/news/government/science-research-policy/2025/05/06/documenting-trumps-arbitrary-cuts-science](https://www.insidehighered.com/news/government/science-research-policy/2025/05/06/documenting-trumps-arbitrary-cuts-science)

> The Trump administration has canceled close to $3 billion in NIH and NSF research grants, often without much explanation. Now researchers are crowdsourcing databases of suspended grants to shed light on what’s being lost.

* Trump Administration Cancels $1 Billion in Grants for Student Mental Health (VAC)

[https://www.nytimes.com/2025/05/01/us/politics/trump-mental-health-grants.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/01/us/politics/trump-mental-health-grants.html?smid=nytcore-ios-share&referringSource=articleShare)

(Whereas Pope wannabees still can qualify for mental health benefits, presumably)

> Lawmakers authorized the money in 2022 after a former student opened fire at an elementary school in Uvalde, Texas, killing 19 children and two teachers and injuring 17 others. The measure, known as the Bipartisan Safer Communities Act, broke a decades-long impasse between congressional Republicans and Democrats on addressing gun violence by focusing largely on improving mental health support for students.

* TRIO on the Chopping Block

[https://www.insidehighered.com/news/students/retention/2025/05/07/how-trumps-proposed-trio-cuts-could-hamper-college-access](https://www.insidehighered.com/news/students/retention/2025/05/07/how-trumps-proposed-trio-cuts-could-hamper-college-access)

> The Trump administration wants to eliminate the federally funded student support program. That could be devastating for low-income students and the institutions that serve them.

> He [sample impacted student] credits his success at Bemidji to TRIO, a federally funded initiative dating back to the 1960s that supports low-income, first-generation college students and students with disabilities as they navigate academic life—and that currently faces an existential threat from the Trump administration.

> “Today, the pendulum has swung and access to college is not the obstacle it was for students of limited means,” officials wrote in the proposal [Trump budget opening salvo]. “A renewed focus on academics and scholastic accomplishment by [institutions], rather than engaging in woke ideology with federal taxpayer subsidies, would be a welcome change.”

### House bills

* ACE's summary of "STUDENT SUCCESS AND TAXPAYER SAVINGS PLAN" that moves to the House Budget Committee (thanks CMR)

[https://www.acenet.edu/Documents/Summary-Student-Success-Taxpayer-Savings-Plan.pdf](https://www.acenet.edu/Documents/Summary-Student-Success-Taxpayer-Savings-Plan.pdf)

(Yes, the name shows the crazy stretching of the all-too elastic phrase "student success")

It includes: Pell Grant restrictions; Loan program eliminations; New repayment plan; Risk-sharing requirement; Regulatory constraints.

Key parts for Pell

> Changes full-time status from 24 semester hours or 36 quarter credit hours to 30 semester hours or 45 quarter credit hours;

(From 12 to 15 credits for CUNY making full time much more out of reach for many of our students)

> Requiring that a student who applies for federal student aid be a citizen or a national of the United States or be an alien who is lawfully admitted for permanent residence under the Immigration and Nationality Act; and

> These provisions would take effect on July 1, 2025, and apply to the 2025-2026 academic year.

### Proposed executive budget

* What Trump’s Proposed Budget Cuts Mean for Education, Research (aims to cut at least $163 billion)

[https://www.insidehighered.com/news/government/student-aid-policy/2025/05/02/trump-proposes-deep-cuts-education-and-research](https://www.insidehighered.com/news/government/student-aid-policy/2025/05/02/trump-proposes-deep-cuts-education-and-research)

(I'd argue even phrasing this as a planned cut, rather than merely an assault is a mistake, but....)

> The proposed budget plan slashes nearly $18 billion from the National Institutes of Health, $12 billion from the Education Department and nearly $5 billion from the National Science Foundation. The skinny budget also eliminates funding for the Institute of Museum and Library Sciences, AmeriCorps, the National Endowment for the Arts, and the National Endowment for the Humanities. Trump has already made deep cuts at those agencies and put most—if not all—of their employees on leave.

> To compensate for the cuts to programs that directly support students or institutions, the administration argued colleges, states and local communities should on take that responsibility. Other justifications for the cuts reflect the administration’s crackdown on diversity, equity and inclusion programs and higher ed.

(Again, "crackdown" is far too fair a term here.)

> Additionally, the administration wants to cut the Office for Civil Rights’ budget by $49 million, or 35 percent. The budget document says this cut will refocus OCR “away from DEI and Title IX transgender cases.” In recent years, the Biden administration pleaded with Congress to boost OCR’s funding in order to address an increasing number of complaints. The office received 22,687 complaints in fiscal year 2024, and the Biden administration projected that number to grow to nearly 24,000 in 2025.

> “The budget cuts funding for: climate; clean energy; woke social, behavioral, and economic sciences; and programs in low priority areas of science,” the officials wrote in budget documents. “NSF has fueled research with dubious public value, like speculative impacts from extreme climate scenarios and niche social studies.”

(There is too much there to even unpack; I'll just note that this was preceded by "we must change course and reorient taxpayer dollars toward proven programs that generate results for American students.")

> The plan would consolidate NIH programs into five areas: the National Institute on Body Systems Research, the National Institute on Neuroscience and Brain Research, the National Institute of General Medical Sciences, the National Institute of Disability Related Research, and the National Institute on Behavioral Health.

> “The administration is committed to restoring accountability, public trust, and transparency at the NIH,” officials wrote. “NIH has broken the trust of the American people with wasteful spending, misleading information, risky research, and the promotion of dangerous ideologies that undermine public health.”

(More nonsense in this "skinny budget")



### NSF

* Under Trump, National Science Foundation Cuts Off All Funding to Scientists | Scientific American


[https://www.nature.com/articles/d41586-025-01396-2](https://www.nature.com/articles/d41586-025-01396-2)

(Only until further notice, as if law breakers mean what they write)

> The policy prevents the NSF, one of the world’s biggest supporters of basic research, from awarding new research grants and from supplying allotted funds for existing grants, such as those that receive yearly increments of money. The email does not provide a reason for the freeze and says that it will last “until further notice”.

* Trump Halts Grants, Caps Indirect Costs at the National Science Foundation

[https://www.chronicle.com/article/trump-halts-grants-caps-indirect-costs-at-the-national-science-foundation](https://www.chronicle.com/article/trump-halts-grants-caps-indirect-costs-at-the-national-science-foundation)

* Universities Sue NSF Over Indirect Research Cost Policy

[https://www.insidehighered.com/news/quick-takes/2025/05/07/universities-sue-nsf-over-indirect-research-cost-policy](https://www.insidehighered.com/news/quick-takes/2025/05/07/universities-sue-nsf-over-indirect-research-cost-policy)

> Plaintiffs in the lawsuit include the American Council on Education, the Association of American Universities, the Association of Public and Land-grant Universities, and 13 universities, including Arizona State University, the University of Chicago and Princeton University.

> They attest that the NSF violated numerous aspects of the Administrative Procedure Act, including bypassing Congress to unilaterally institute an “arbitrary and capricious” 15 percent rate cap and failing to explain why it’s only imposing the policy on universities.

> The NSF awarded $6.7 billion to some 621 universities in 2023.

* Exclusive: NSF faces radical shake-up as officials abolish its 37 divisions | Science | AAAS


[https://www.science.org/content/article/exclusive-nsf-faces-radical-shake-officials-abolish-its-37-divisions](https://www.science.org/content/article/exclusive-nsf-faces-radical-shake-officials-abolish-its-37-divisions)

> [The NSF] is plunging into deeper turmoil. According to sources who requested anonymity for fear of retribution, staff were told today that the agency’s 37 divisions—across all eight NSF directorates—are being abolished and the number of programs within those divisions will be drastically reduced. The current directors and deputy directors will lose their titles and might be reassigned to other positions at the agency or elsewhere in the federal government.

> The consolidation appears to be driven in part by President Donald Trump’s proposal to cut the agency’s $9 billion budget by 55% for the 2026 fiscal year that begins on 1 October.

> The agency is also expected to issue another round of notices tomorrow terminating grants that have already been awarded, sources say. In the past 3 weeks, the agency has pulled the plug on almost 1400 grants worth more than $1 billion.

(CSI faculty were among these who lost funding this week.)


### NEH

* Lawsuit Against Humanities Endowment Offers Details on DOGE - The New York Times

[https://www.nytimes.com/2025/05/02/arts/humanities-endowment-doge-grants.html](https://www.nytimes.com/2025/05/02/arts/humanities-endowment-doge-grants.html)

> Employees from the Department of Government Efficiency started visiting the office soon after, according to the lawsuit. Citing accounts by former or current staff members at the endowment, the lawsuit says that two DOGE employees, Nate Cavanaugh and Justin Fox, asked for a list of all current grants and then “indiscriminately terminated the vast majority” on April 2. Nearly 1,500 grant recipients received cancellation letters that suggested their projects were not in keeping with “the president’s agenda.”

> Three weeks later, the agency announced it would be redirecting [stealing ed.] $17 million of its funding to create the National Garden of American Heroes,

> The lawsuit contends that those moves violate the Constitution, which reserves the power of the purse for Congress, and also the Administrative Procedure Act.

* Trump proposes eliminating the NEA and NEH as arts grants are canceled

[https://www.washingtonpost.com/style/2025/05/03/trump-budget-nea-neh-eliminate/](https://www.washingtonpost.com/style/2025/05/03/trump-budget-nea-neh-eliminate/)

(This applies going forward, the lawsuit applies to past allocations. But the keyword is "proposed", as this was just part of the Trumpian fantasy budget.)

* NYTimes: The National Endowment for the Arts Begins Terminating Grants

[https://www.nytimes.com/2025/05/03/arts/national-endowment-for-the-arts-grants.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/03/arts/national-endowment-for-the-arts-grants.html?smid=nytcore-ios-share&referringSource=articleShare)

* Guidance from MAA (https://www.medievalacademy.org/; thanks EST for sharing)

(This appeared in a news letter, so no link is available)

> With the caveat that the MAA cannot offer actual legal advice, here is the current state of affairs, as we understand it:

> 1) ACLS, AHA, and MLA have filed a lawsuit against the NEH and DOGE. The complaint is online here. The suit is likely to proceed quickly, and we will keep you apprised of its progress.



> 2) A court decision handed down earlier this week compels the government to restore terminated IMLS funding. I am hopeful that this success will serve as a strong precedent for other suits.



> 3) Those who have lost NEH funding should have filed an appeal by now, either as an individual or through their host institution. If you have not done so, the guidance we’ve received is that you should file anyway before taking any further action, following whatever guidelines you have received (and with the understanding that there is, in fact, no truly clear guidance about what is happening at NEH). More information on the appeals process can be found here. When appealing any grant termination, be sure to emphasize how this loss may impact not only your research but your reputation, opportunities passed up to take on the grant-funded project, and the loss of future opportunities that the grant might have made possible. Please remember that our colleagues at NEH – those who remain – are devastated by the current situation and are themselves overwhelmed. They are committed Federal employees who are not to blame for these terminations. I urge you to try to be patient as your appeal (and the lawsuit) move forward.



## DOT, NEA

* Department of Transportation, NEA Cut Federal Grants

[https://www.insidehighered.com/news/quick-takes/2025/05/05/department-transportation-nea-cut-federal-grants](https://www.insidehighered.com/news/quick-takes/2025/05/05/department-transportation-nea-cut-federal-grants)

> U.S. Transportation Secretary Sean P. Duffy announced Friday that the Department of Transportation eliminated seven “woke university grants,” totaling $54 million.

including:

>  about $9 million to City College of New York’s Center for Social and Economic Mobility for People and Communities through Transportation,

> The department also cut a $6 million grant to New York University to fund research on “e-bikes to low-income travelers in transit deserts”

> Hundreds of recipients of grants from the National Endowment for the Arts also received notice Friday (May 2) that their funding had been withdrawn or terminated, NPR reported.

> According to the email, Trump’s priorities include “projects that elevate the Nation’s HBCUs and Hispanic Serving Institutions, celebrate the 250th anniversary of American independence, foster AI competency, empower houses of worship to serve communities, assist with disaster recovery, foster skilled trade jobs, make America healthy again, support the military and veterans, support Tribal communities, make the District of Columbia safe and beautiful, and support the economic development of Asian American communities.”

* National Endowment for the Arts rescinds grants, dazing publishers and theaters


[https://www.washingtonpost.com/entertainment/theater/2025/05/04/trump-budget-nea-arts-grants-canceled/](https://www.washingtonpost.com/entertainment/theater/2025/05/04/trump-budget-nea-arts-grants-canceled/)

(dazing: make someone unable to think or react properly; stupefy; bewilder.)

* Every arts director at the NEA exits federal culture agency


[https://www.washingtonpost.com/entertainment/2025/05/07/nea-staff-departure/](https://www.washingtonpost.com/entertainment/2025/05/07/nea-staff-departure/)


### DOE

* The Trump administration will put millions of defaulted student-loan borrowers into collections starting Monday and is threatening to confiscate their wages and federal benefits


[https://www.wsj.com/personal-finance/student-loans-debt-payments-collections-6fd28ed3?st=fgHqWY&reflink=article_gmail_share](https://www.wsj.com/personal-finance/student-loans-debt-payments-collections-6fd28ed3?st=fgHqWY&reflink=article_gmail_share)

* Trump administration to resume collection on student loans in default : NPR

[https://www.npr.org/2025/04/21/nx-s1-5371723/trump-administration-collections-on-defaulted-student-loans](https://www.npr.org/2025/04/21/nx-s1-5371723/trump-administration-collections-on-defaulted-student-loans)

* Education Department Rolls Back Decades of Civil Rights Progress Under Trump — ProPublica

[https://www.propublica.org/article/education-department-civil-rights-donald-trump-discrimination](https://www.propublica.org/article/education-department-civil-rights-donald-trump-discrimination)

> Hollowed Out: The administration has closed Education Department civil rights offices and fired workers. Now, investigating discrimination in schools is practically “impossible.”

> In South Dakota, the OCR abruptly terminated its work with a school district that had agreed to take steps to end discrimination against its Native American students. The same office that helped craft the agreement to treat indigenous students equally made a stunning about-face and decided in March that helping Native American students would discriminate against white students.

> One OCR attorney, who asked not to be named for fear of retaliation, told ProPublica that their caseload went from 60 to 380 as they absorbed cases previously handled by employees who worked in offices that had been closed.

> “OCR is the most useless it’s ever been, and it’s the most dangerous it’s ever been. And by useless, I mean unavailable. Unable to do the work,”

> Investigating cases that allege racism, discrimination based on sexual orientation or mistreatment of students with disabilities now requires permission from Trump appointees, according to a memo from OCR leadership. As a result, thousands of discrimination investigations are idled, even ones that were nearing a resolution when Trump took office again.

> Investigations being publicized now have largely bypassed the agency’s civil rights attorneys, according to Education Department employees. McMahon and OCR head Craig Trainor created what amounts to a shadow division.

(This article is really a gut punch, but well worth reading)

* Education Dept. Cancels Fulbright-Hays Applications, at Least for Now

[https://www.insidehighered.com/news/global/study-abroad/2025/05/09/fulbright-hays-grants-canceled-year](https://www.insidehighered.com/news/global/study-abroad/2025/05/09/fulbright-hays-grants-canceled-year)

> The decision, announced Thursday on the Federal Register, will affect doctoral students and faculty who applied for the Group Projects Abroad, Doctoral Dissertation Research Abroad and Faculty Research Abroad programs—all of which focus on expanding American expertise in critical languages and are congressionally mandated.

> About 110 individuals and 22 groups from over 55 institutions benefited from these three programs, according to department data, in fiscal year 2022, the most recent year for which data is available. This year, prior to the cancellation, more than 400 applications had been submitted.

## Funding un-cuts

* NYTimes: Mellon Foundation Announces $15 Million for Humanities Councils

[https://www.nytimes.com/2025/04/29/arts/mellon-foundation-humanities-endowment.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/29/arts/mellon-foundation-humanities-endowment.html?smid=nytcore-ios-share&referringSource=articleShare)


* Gates Foundation to Spend $200B Before Closing in 2045

[https://www.insidehighered.com/news/quick-takes/2025/05/09/gates-foundation-spend-200b-closing-2045](https://www.insidehighered.com/news/quick-takes/2025/05/09/gates-foundation-spend-200b-closing-2045)

> Over the next 20 years, the Gates Foundation will focus its resources on achieving three goals: that “no mom, child or baby dies of a preventable cause”; that “the next generation grows up in a world without deadly infectious diseases”; and that “hundreds of millions of people break free from poverty, putting more countries on a path to prosperity.”

> “There are too many urgent problems to solve for me to hold onto resources that could be used to help people. That is why I have decided to give my money back to society much faster than I had originally planned,” Gates, co-founder of Microsoft, wrote in a blog post. “I will give away virtually all my wealth through the Gates Foundation over the next 20 years to the cause of saving and improving lives around the world.”

## Can't we all just get along?

### Harvard

* NYTimes: Harvard Signals It Will Resist Trump’s Efforts to Revoke Tax-Exempt Status

[https://www.nytimes.com/2025/05/02/us/politics/trump-harvard-tax-exempt-status.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/02/us/politics/trump-harvard-tax-exempt-status.html?smid=nytcore-ios-share&referringSource=articleShare)

* NYTimes: The Jewish Student Who Took On Harvard

[https://www.nytimes.com/2025/05/04/us/shabbos-kestenbaum-harvard-lawsuit-settlement.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/04/us/shabbos-kestenbaum-harvard-lawsuit-settlement.html?smid=nytcore-ios-share&referringSource=articleShare)

* NYTimes: Trump and Harvard Both Want ‘Viewpoint Diversity.’ What Does It Mean?

[https://www.nytimes.com/2025/05/05/arts/harvard-trump-viewpoint-diversity.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/05/arts/harvard-trump-viewpoint-diversity.html?smid=nytcore-ios-share&referringSource=articleShare)

The Trump Administration expects affirmative action for conservative viewpoints:

> “Each department, field or teaching unit must be individually viewpoint diverse,” the letter said. So too must be the student body, staff and leadership. A failing grade, the letter warned, would result in corrective measures, including the deliberate recruiting of “a critical mass” of new faculty and students to correct the imbalance.

> Harvard has rejected the Trump administration’s demands, calling them a threat to academic freedom and the political independence of higher education. But in a letter to Harvard affiliates informing them that the university was suing the government, Harvard’s president, Alan Garber, echoed that vocabulary.

> “We acknowledge that we have unfinished business,” Dr. Garber wrote. “We need to ensure that the university lives up to its steps to reaffirm a culture of free inquiry, viewpoint diversity and academic exploration.”

> Harvard itself has been a hotbed of diverse views about the value of viewpoint diversity and its relationship to the bedrock value of academic freedom. But there’s broad agreement that the Trump administration is weaponizing the term — which its letter never defines — in a dangerous way.

> The term viewpoint diversity began gaining currency across academia largely through the efforts of Heterodox Academy, a nonpartisan national group founded in 2015 to combat what it describes as “the rise of closed-minded orthodoxies within scholarly communities.”

> In recent years, it has been picked up by Republican politicians, as a new tool to support their longstanding argument that universities have been taken over by the left.

> A report last October by the free expression group PEN America said that viewpoint diversity, while a laudable goal, has too often served as “camouflage” for the real purpose: stifling faculty members’ speech.

* NYTimes: Trump Administration Disqualifies Harvard From Future Research Grants

[https://www.nytimes.com/2025/05/05/us/politics/trump-harvard-research-grants.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/05/us/politics/trump-harvard-research-grants.html?smid=nytcore-ios-share&referringSource=articleShare)

The letter is as they say meshuga

[https://x.com/EDSecMcMahon/status/1919517481313427594](https://x.com/EDSecMcMahon/status/1919517481313427594)

My favorite is to now blame it on the math

> Why is it, we ask, that Harvard has to teach simple and basic mathematics, when it is supposedly so hard to get into this "acclaimed university"? Who is getting in under such a low standard when others, with fabulous grades and a great understanding of the highest levels of mathematics, are being rejected?

When the NY Times calls this  "a contentious letter" they are only sane washing it. It might better be described by an AI prompt "write crazy letter on Harvard in the voice of the president, include all specious claims"

* Deciphering the Trump Administration’s Latest Letter to Harvard

[https://www.insidehighered.com/news/government/politics-elections/2025/05/07/experts-unpack-linda-mcmahons-latest-letter-harvard](https://www.insidehighered.com/news/government/politics-elections/2025/05/07/experts-unpack-linda-mcmahons-latest-letter-harvard)

Insidehighered found one Project 2025 voice here:

> “When the secretary says, ‘Don’t come to us for grants anymore,’ she means that, and she can enforce it,” said Adam Kissel, a visiting fellow in the Heritage Foundation’s Center for Education Policy. “The tone suggests that Harvard really needs to wake up and understand the dire nature of its situation.”

But by and large, this is the take they find

> But Lynn Pasquerella, president of the American Association of Colleges and Universities, described Monday’s letter as a “particularly disturbing” and “unwarranted escalation of threats.” What the Trump administration has done since day one, Pasquerella said, is launch a “politically motivated attack, not only against Harvard, but higher education as a whole,” and it’s all part of a long-standing Republican playbook.

> Multiple Inside Higher Ed sources have described the Trump administration’s approach to higher education as “fascist” or “authoritarian,” and Pasquerella even noted that the White House has positioned Viktor Orbán—Hungary’s right-wing prime minister who has long been known for his assault on academic freedom—as someone to emulate.

> “The president is so bombastic and so over-the-top that it’s hard for me to see gradations,” Hess [director of education policy studies at the American Enterprise Institute, a conservative think tank] said. “So, sure, the secretary sending a letter that declared ‘don’t bother applying for anything’ is an extraordinary declaration. And in other circumstances, I would have been like, holy cow. But given what the administration has done over the past three and a half months, it’s not clear to me that it changes the administration’s posture.”



* Trump administration calls for a freeze on all new grants to Harvard

[https://www.washingtonpost.com/education/2025/05/05/harvard-new-grants-freeze-trump/](https://www.washingtonpost.com/education/2025/05/05/harvard-new-grants-freeze-trump/)

> McMahon’s letter displays an astonishing and frankly disqualifying level of ignorance — about Harvard, about how federal research funding works, and about the plain text of the U.S. Constitution,” Weld (AAUP President of Harvard chapter) said. “The entire higher ed sector must reject this crude authoritarianism with one voice.”

> Ted Mitchell, the president of the American Council on Education, said, “I think we should all be looking at the interchange between the department, Harvard and the White House as harbingers of things to come.” 

> Larry Summers, former president of Harvard, said the Trump administration’s fight with the Ivy League university has larger implications for civil society. “This is about whether the government has the power to coerce private institutions, using all the various authorities it has to advance particular political agendas of the president,” he said. “But for higher education, this is about academic freedom, which for the better part of a century, the Supreme Court recognized as intimately connected to the First Amendment. So in a broad civic sense, it’s about our commitment to constitutional democracy as manifest in the First Amendment.”


* Trump Finally Drops the Anti-Semitism Pretext -- The latest letter to Harvard makes clear that the administration’s goal is to punish liberal institutions for the crime of being liberal. (Thanks BE for the sharing and the gift link!)

[https://www.theatlantic.com/politics/archive/2025/05/mcmahon-harvard-letter/682717/?gift=yCYg0MdUGpnvquf3En3lpkKQKFBhGvbst4TkhNQ1SSk&utm_source=email&utm_medium=social&utm_campaign=social](https://www.theatlantic.com/politics/archive/2025/05/mcmahon-harvard-letter/682717/?gift=yCYg0MdUGpnvquf3En3lpkKQKFBhGvbst4TkhNQ1SSk&utm_source=email&utm_medium=social&utm_campaign=social)

(A critique that doesn't sanewash and well worth reading)

> The intensely hostile letter that Education Secretary Linda McMahon sent to the leadership of Harvard yesterday has a lot going on. But the most notable thing about it is what it leaves out.

> To hear McMahon tell it, Harvard is a university on the verge of ruin. (I say McMahon because her signature is at the bottom of the letter, but portions of the document are written in such a distinctive idiolect—“Why is there so much HATE?” the letter asks; it signs off with “Thank you for your attention to this matter!”—that one detects the spirit of a certain uncredited co-author.)

> What you will not find in the McMahon letter is any mention of the original justification for the Trump administration’s ongoing assault on elite universities: anti-Semitism.

> Now, however, the mask is off. Aside from one oblique reference to congressional hearings about anti-Semitism (“the great work of Congresswoman Elise Stefanik”), the letter is silent on the subject. The administration is no longer pretending that it is standing up for Jewish students. The project has been revealed for what it is: an effort to punish liberal institutions for the crime of being liberal.

> “There’s no ‘We don’t like you’ authority in the federal Constitution or in statutory law. In fact, quite the opposite: You’re precluded from that.” [Derek Black, a law professor at the University of South Carolina]

* Harvard Faculty Pledge 10% of Their Salary to Defend Against Trump

[https://www.insidehighered.com/news/quick-takes/2025/05/06/harvard-faculty-pledge-10-salary-defend-against-trump](https://www.insidehighered.com/news/quick-takes/2025/05/06/harvard-faculty-pledge-10-salary-defend-against-trump)

> Nearly 100 senior faculty members at Harvard have committed to taking a pay cut to support the institution’s legal defense against the federal government.

* NYTimes: Harvard Leaders See Only Bad Outcomes Ahead as They Battle Trump

[https://www.nytimes.com/2025/05/08/us/harvard-trump-court-case-negotiation.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/08/us/harvard-trump-court-case-negotiation.html?smid=nytcore-ios-share&referringSource=articleShare)

> But behind the scenes, several senior officials at Harvard and on its top governing board believe that the university is confronting a crisis that could last until President Trump is out of power, according to three people involved in the discussions. Even if Harvard’s legal case is successful, these officials say, the school will still face enormous troubles that may force the nation’s oldest and wealthiest university to rethink its identity and scale.

So says

> They spoke on the condition of anonymity because they had not been authorized to discuss school officials’ private deliberations.

> The crosscurrents are unlike any that the university has faced in its modern history. For centuries, Harvard has cherished its independence, its swaggering pride and its record of academic excellence. But Mr. Trump has reveled in unleashing chaos that many believe will be difficult to contain as long as he sees the university as a target.

> The corporation [the board that oversees the university] has told the school’s lawyers not to engage with the Trump administration, according to the two people involved in discussions.

> Complicating matters is whether the White House will honor a deal.

> Lawrence H. Summers, a former Harvard president, said ... “It would be a tragedy if Harvard resolved this in a way that gave support and encouragement to the idea of extralegal extortion.”

> The Trump administration this week reiterated its aim to inflict as much damage as possible, when Ms. McMahon fired off a letter telling Harvard that it would not receive future federal grants. Although experts on government contracts and grants scoffed at the missive, the government can essentially blacklist contractors through a process called debarment.

> Aside from the research funding, there will be nothing to stop the administration from saddling the school with more onerous and potentially costly investigations, like the ones currently being conducted by at least five different departments and agencies, including the Justice Department and Department of Homeland Security.



### Columbia

* NYTimes: Orders to Investigate Columbia Protesters Raised Alarms in Justice Dept. (VAC)

[https://www.nytimes.com/2025/05/01/us/politics/columbia-protests-justice-department.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/01/us/politics/columbia-protests-justice-department.html?smid=nytcore-ios-share&referringSource=articleShare)

> A top Trump appointee in the Justice Department ordered an aggressive investigation in the last several months of student protesters at Columbia University, raising anger and alarm among career prosecutors and investigators who saw the demand as politically motivated and lacking legal merit, people familiar with the episode said.

(And if you guessed Ed Martin, wrong ... it was Emil Bove III)

* Columbia Lays Off 180 Amid ‘Intense’ Financial Strain

[https://www.insidehighered.com/news/quick-takes/2025/05/07/columbia-lays-180-amid-intense-financial-strain](https://www.insidehighered.com/news/quick-takes/2025/05/07/columbia-lays-180-amid-intense-financial-strain)

> university leadership wrote in a memo Tuesday morning. “We are working on and planning for every eventuality, but the strain in the meantime, financially and on our research mission, is intense.”

* Exclusive | Trump Administration Proposes Terms for Federal Oversight of Columbia University - WSJ


[https://www.wsj.com/us-news/education/trump-columbia-university-consent-decree-proposal-d21830f2](https://www.wsj.com/us-news/education/trump-columbia-university-consent-decree-proposal-d21830f2)


A *consent decree* is proposed

* NYTimes: Police Remove Pro-Palestinian Demonstrators Occupying Columbia Library

[https://www.nytimes.com/2025/05/07/nyregion/columbia-protest-library-occupied.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/07/nyregion/columbia-protest-library-occupied.html?smid=nytcore-ios-share&referringSource=articleShare)

* New York police arrest pro-Palestinian protesters at Columbia University


[https://wapo.st/3RTkJWM](https://wapo.st/3RTkJWM)

### U Penn

* Education Dept.’s Penn Demands Show Shift in Title IX

[https://www.insidehighered.com/news/diversity/sex-gender/2025/05/08/education-depts-penn-demands-show-shift-title-ix](https://www.insidehighered.com/news/diversity/sex-gender/2025/05/08/education-depts-penn-demands-show-shift-title-ix)

> Experts say the speed of the investigation, OCR’s unusual demands and the fact that Penn was in compliance with Title IX at the time Thomas competed there reflect a shift toward a more aggressive use of Title IX to further President Donald Trump’s anti-trans agenda.

> For those in the former camp, Trump’s demands of Penn are just another example of the president using any means possible to erode trans people’s rights.

### knee flexion is exceptional

* Why I Chose the University of Florida

[https://www.insidehighered.com/opinion/views/2025/05/08/why-i-chose-university-florida-santa-ono-opinion](https://www.insidehighered.com/opinion/views/2025/05/08/why-i-chose-university-florida-santa-ono-opinion)

> the alignment between the Board of Trustees, the Board of Governors, the governor and the Legislature is rare in higher education. This alignment signals seriousness of purpose, and it tells me that Florida is building something truly exceptional. I’m excited to be part of that.

## Blowback

* The Scary Implications of U.S. Government Attacks on Medical Journals | Scientific American


[https://www.scientificamerican.com/article/the-scary-implications-of-u-s-government-attacks-on-medical-journals/](https://www.scientificamerican.com/article/the-scary-implications-of-u-s-government-attacks-on-medical-journals/)

> In April, I decided to make public a leaked letter from the acting U.S. attorney for the District of Columbia to the editor-in-chief of CHEST, a leading pulmonology and critical care journal. I did so because the letter represents an authoritarian threat to science, and I knew it wasn’t an isolated, bizarre incident. It is a warning sign, another move in a broader campaign to exert control over research, medicine and media.

> The letter asserts that “publications like CHEST Journal are conceding that they are partisans in various scientific debates.” It was written by recently appointed acting U.S. attorney Edward R. Martin, Jr., who gives no examples that might demonstrate partisanship; nor does he cite any laws or legal principles to indicate a matter that should concern the U.S. government.

> Since I publicly shared this, at least four additional journals, including the New England Journal of Medicine, have confirmed receipt of similar letters, according to MedPage Today, STAT News, the New York Times and Science. Aside from Eric Rubin at the NEJM, none of the targeted editors have been willing to go on record, fearing retribution from the Trump administration.

> Why CHEST? It’s a specialty outlet—not even among the top 50 medical journals. Is this a keyword-driven campaign like those we’ve seen at the CDC and NIH? Under Robert F. Kennedy, Jr., terms like “diversity,” “minority” and “equity” have been systematically flagged.

> Kennedy frequently makes evidence-free claims on podcasts and television shows and now in government press conferences, regardless of the consequences. However, peer-reviewed journals like CHEST require extensive scrutiny as part of their evaluation process.

* How a Decades-Old Diversity Program Became Collateral Damage in Trump’s Anti-DEI Crusade

[https://www.chronicle.com/article/how-a-decades-old-diversity-program-became-collateral-damage-in-trumps-anti-dei-crusade](https://www.chronicle.com/article/how-a-decades-old-diversity-program-became-collateral-damage-in-trumps-anti-dei-crusade)

> The PhD Project has for three decades encouraged business professionals from underrepresented backgrounds to pursue doctorates in the discipline. For years, its work was seen as uncontroversial; its annual conference introduced midcareer business professionals of color to the academy, offering resources and a support network to those interested in switching jobs. Eventually, some of those prospective students would become professors themselves, helping diversify a traditionally homogenous discipline.

## Hitting replay

* NYTimes: Congress Grills College Presidents With an Old Script and New Threats

[https://www.nytimes.com/2025/05/07/us/congress-hearing-college-presidents-haverford.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/07/us/congress-hearing-college-presidents-haverford.html?smid=nytcore-ios-share&referringSource=articleShare)

* Under Republicans’ Scrutiny, College Presidents Apologize for Their Handling of Campus Antisemitism

[https://www.chronicle.com/article/under-republicans-scrutiny-college-presidents-apologize-for-their-handling-of-campus-antisemitism](https://www.chronicle.com/article/under-republicans-scrutiny-college-presidents-apologize-for-their-handling-of-campus-antisemitism)

> A three-hour-long hearing on Wednesday once again gave House Republicans the opportunity to amplify reports of antisemitic social-media posts, events, and confrontations, and to demand that institutions provide information on how they discipline students and faculty members who transgress.

> But lawmakers seeking to make a point had material to work with. The three campuses all saw pro-Palestinian protests and alleged incidents of antisemitic harassment following the October 7, 2023, Hamas attack on Israel.

> Wednesday’s hearing marked yet another expansion of Republicans’ efforts to put higher ed under pressure. Since January, the Trump administration has canceled or frozen grants at several prominent research universities, largely for alleged failures to combat antisemitism.

## Alternate Reality

* NYTimes: On California’s State Bar Exam, More Questions Than Answers

[https://www.nytimes.com/2025/04/30/us/california-state-bar-exam.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/04/30/us/california-state-bar-exam.html?smid=nytcore-ios-share&referringSource=articleShare)

> Then came the news that at least a handful of the multiple-choice questions had been developed with the help of artificial intelligence. To many of those who took the exam, it was hardly shocking — they already had suspicions that A.I. had been used, based on a few questions that they said had struck them as bizarrely worded or legally unsound.

> Kaplan, the new contractor for exam development, disputed that the study guide contained a significant number of errors.

> the State Bar of California said in a statement. “We apologize again, and we make no excuses for the failures that have occurred.”


## Coming attractions?

* Senior State Department official sought internal communications with journalists, European officials, and Trump critics | MIT Technology Review


[https://www.technologyreview.com/2025/05/01/1115988/senior-state-department-official-sought-internal-communications-with-journalists-european-officials-and-trump-critics/](https://www.technologyreview.com/2025/05/01/1115988/senior-state-department-official-sought-internal-communications-with-journalists-european-officials-and-trump-critics/)


> Fried echoes this sentiment. “I spent 40 years in the State Department, and you didn’t collect names or demand email records,” says Fried. “I’ve never heard of such a thing”—at least not in the American context, he clarifies. It did remind him of Eastern European “Communist Party minder[s] watching over the untrusted bureaucracy.”

> He adds: “It also approaches the compilation of an enemies list.”

* Cal Poly, DePaul and Haverford Head to Capitol Hill

[https://www.insidehighered.com/news/governance/executive-leadership/2025/05/07/cal-poly-depaul-and-haverford-head-capitol-hill](https://www.insidehighered.com/news/governance/executive-leadership/2025/05/07/cal-poly-depaul-and-haverford-head-capitol-hill)

> This time, lawmakers are targeting California Polytechnic State University, San Luis Obispo; DePaul University; and Haverford College. Presidents from all three institutions will testify at a congressional hearing today.

> In all three letters, the Republican-led Committee on Education and the Workforce cited alleged instances of antisemitism and noted failing grades on the Anti-Defamation League’s Campus Antisemitism Report Card: Both DePaul and Haverford received an F, while Cal Poly earned a D.

(Put aside a committee that conflates a D with failing and perhaps worry that Hunter has a "C" grade and could be up soon by these standards.)

* Higher Education Leaders Call for Greater Defense of Board Independence

[https://www.insidehighered.com/news/quick-takes/2025/05/07/higher-ed-leaders-call-defense-board-independence](https://www.insidehighered.com/news/quick-takes/2025/05/07/higher-ed-leaders-call-defense-board-independence)

(Reports on this letter https://agb.org/news/letters-and-testimony/community-letter-reaffirming-the-independence-of-higher-education-governance-a-call-to-action/)

> American higher education leaders, advocates and stakeholders must stand together to “defend the autonomy of college and university governing boards as a cornerstone of constitutional freedoms; and reject political interference that undermines academic excellence and fiduciary stewardship,” the group said.

> They also called for leaders to reaffirm the principles of institutional autonomy laid out in the 1819 Supreme Court decision Dartmouth College v. Woodward, which established safeguards to protect colleges from ideological and political interference.

> The chairs of the boards of trustees at Clark Atlanta University, Eastern Michigan University and the University of Illinois are among the signatories, as well as the heads of the Middle States and New England Commissions of Higher Education.

> Lawmakers in several states have introduced legislation that seeks to increase board oversight in processes like academic programming and tenure, as well as a governor’s ability to appoint board members.

* A Looming Crisis for Public Colleges: If the federal government cuts Medicaid spending, state funding for higher ed will evaporate.

[https://www.chronicle.com/article/a-looming-crisis-for-public-colleges](https://www.chronicle.com/article/a-looming-crisis-for-public-colleges)

> The House Republicans’ plan for reconciliation includes a cut of about $880 billion over the next decade in health-care and energy spending and $230 billion from agriculture. A budget reduction of this magnitude will require significant reductions to Medicaid and SNAP.

> That would directly harm low- and moderate-income Americans across the country, but these costs will also be passed on to states, putting pressure on already-tight budgets. And, as history has shown us time and time again, a state-budget squeeze almost always leads to skyrocketing college costs and lower-quality public education.

> Most states are required to pass balanced budgets each year. But some programs, like Medicaid, are directly tied to formulas and federal matching dollars. When revenue is tight, especially in tough economic times, states reduce the portion of their total budgets that remain “discretionary” — the portion that is not dictated by formula-derived expenses.  In almost every state, higher education is the largest discretionary-spending category.

> For just one example, look to Pennsylvania, where I [Tanya I. Garcia] previously served as deputy secretary and commissioner for postsecondary and higher education. For the 30-year period from financial year 1991 to financial year 2021, Pennsylvania increased Medicaid spending by 227 percent and decreased higher-education spending by 28 percent.

> When state funding for higher education drops, it affects open-access, less-selective colleges the most, since they are more dependent on state appropriations and less able to raise their prices than their peers at elite public and flagship institutions. This is a crucial distinction, as 86 percent of all undergraduate students pursuing a degree in the United States do not attend selective flagships or research universities.

> Make no mistake: Such massive federal funding cuts would unleash mayhem on state budgets and public colleges starved for resources. Almost 40 states will have finalized their budgets by June 30 of this year. Will we have a raft of states calling special legislative sessions to revise their budgets when all is said and done in the nation’s capital? We still have time to avoid this.


* NYTimes: I Know Trump’s Plan for Universities. It Transformed My College.

[https://www.nytimes.com/2025/05/07/opinion/trump-universities-woke.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/07/opinion/trump-universities-woke.html?smid=nytcore-ios-share&referringSource=articleShare)

> Mr. Trump has been watching what’s transpired in Florida. The architect of Project 2025’s education policies has said that Florida is “leading the way” on university overhauls. Already, Mr. Trump has threatened to pull funding from colleges that don’t purge language he considers woke. He’s demanded new oversight of certain regional studies departments. Next he could try to ban, as Florida has, “political or social activism.” He could weaken the protections provided by tenure and faculty unions. I saw this happen on my campus, and I know the toll it took. If the Trump administration has its way, my experience could offer a preview of what’s coming for other universities.

> Since Mr. DeSantis’s crackdown, I’ve seen my colleagues harassed and investigated for addressing topical issues, even outside the classroom. The climate of fear gives the government precisely the result it wants. Administrators and faculty members alike practice anticipatory obedience to avoid even the appearance of wokeness, stifling the sort of open and civil discussions that lead students to develop their own views.

> Several professors have been subjected to efforts at entrapment. Last year a man posing as a student tried to encourage Muslim faculty members to criticize Mr. DeSantis and Israel. A similar incident happened to me. ... That incident shattered my conviction that if I did my job well and followed the rules, I would be safe.

> Teaching is, above all, the creation of a community in the classroom, a web of trust and curiosity that binds students and instructors in a shared intellectual project. Mistrust, fear and self-censorship make that project impossible.

* NYTimes: West Point Is Supposed to Educate, Not Indoctrinate

[https://www.nytimes.com/2025/05/08/opinion/west-point-trump-military.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/05/08/opinion/west-point-trump-military.html?smid=nytcore-ios-share&referringSource=articleShare)

(Very good summary of how academic freedom is taken away overnight)

## Tracking web sites

* Chronicle of Higher Education

[https://www.chronicle.com/article/tracking-trumps-higher-ed-agenda](https://www.chronicle.com/article/tracking-trumps-higher-ed-agenda)

Also this one on the "dismantling" of DEI

[https://www.chronicle.com/article/tracking-higher-eds-dismantling-of-dei](https://www.chronicle.com/article/tracking-higher-eds-dismantling-of-dei)

* We Are Higher Ed

[https://www.wearehighered.org/](https://www.wearehighered.org/)

(This was mentioned in the NY Times article on the Rutgers "alliance" resolution and allows people to contribute, https://www.wearehighered.org/contact)

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.
