# Nov 7

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

## Statements


* ICE detains 2 SUNY Upstate Medical Employees – UUP, CSEA, and SUNY UFS Respond

[https://nyscaaup.org/ice-detains-suny-upstate-employees/](https://nyscaaup.org/ice-detains-suny-upstate-employees/)

ICE detained two SUNY Upstate Medical University employees in Syracuse on October 29. The two were attending an immigration hearing when they were detained. Their unions, United University Professions (UUP) and the Civil Service Employees Association (CSEA) have publicly denounced the detentions according to local media reports: “We condemn the actions taken by ICE today,” [UUP President] Kowal said in a UUP Facebook post, “we want our members to know that our union will stand shoulder to shoulder with them in the face of unlawful treatment.”[^1] SUNY University Faculty Senate (SUNY UFS) President Simon issued a statement[^2] in support of the two workers, denouncing the Trump administration’s actions as another attack on the U.S. Constitution and the American Dream.

[^1] https://www.facebook.com/uupinfo/posts/pfbid02f66vMxKWXeqXKmMZHfFV22SnJ6a1BtVmzuFEoUxnHfvJLPDFBkMdvAfELMeNQXqbl?rdid=oau6D36AlFMi73nB#

[^2] https://dspace.sunyconnect.suny.edu/server/api/core/bitstreams/f5f2be5e-1f49-495f-96b9-0fdbadc0be9c/content


## Protests

> Students, Unions to Protest Trump’s Higher Ed Agenda Friday

[https://www.insidehighered.com/news/quick-takes/2025/11/04/students-unions-protest-trumps-higher-ed-agenda-friday](https://www.insidehighered.com/news/quick-takes/2025/11/04/students-unions-protest-trumps-higher-ed-agenda-friday)

> The protests are part of a progressive movement called Students Rise Up, or Project Rise Up. The Action Network website says there will be “walkouts and protests at hundreds of schools” Friday—the start of a buildup “to a mass student strike on May 1st, 2026, when we’ll join workers in the streets to disrupt business as usual.”

> “We’re demanding free college, a fair wage for workers, and schools where everyone is safe to learn and protest—regardless of their gender or race or immigration status,” the website says.

## Academic freedom

*  ‘I Don’t Feel Safe in This Classroom'---Their teaching aimed to make white students uncomfortable. Then came the civil-rights complaint.

[https://www.chronicle.com/article/i-dont-feel-safe-in-this-classroom](https://www.chronicle.com/article/i-dont-feel-safe-in-this-classroom)

(This is an example of the intersection of academic freedom principles and Title VI principles with the added example of how IRB can be used to inhibit academic freedom)

> In the article, which was accepted for publication by the Journal of the Society for Social Work and Research, Hafen and Villescas Zamzow prominently featured their experience running two social-work courses. They draw on classroom interactions and student feedback as evidence of defensiveness exhibited by white students in response to instruction about racial injustice.

> When those students felt guilty, or sad, or angry, they “lashed out” to “re-establish white comfort,” Hafen and Villescas Zamzow concluded. That, in their view, is something to be embraced. “[We] want the tension, [we] want the discomfort among people who hold privilege,” Villescas Zamzow is quoted in the paper as saying. (A primary data source for the study is 10 recorded “processing sessions” between her and Hafen. Neither responded to my interview requests.)

> For the two instructors, unsettling their white students’ biases is a necessary condition of an antiracist education. What they call “white emotional hegemony” must be disrupted, to support the learning of all students. But to critics and skeptics, what Hafen and Villescas Zamzow depict is not only ideologically stifling. It’s potentially discriminatory.

> While teaching this content, Hafen and Villescas Zamzow used the “pedagogy of discomfort.” First conceptualized by Megan Boler, now a professor in the department of social-justice education at the University of Toronto, the methodology maintains that students and professors should challenge their previously held assumptions and self-conceptualizations and grapple with negative emotions that follow, which can be indicative of unexamined bias

> Meanwhile, the paper no longer appears on the Journal of the Society for Social Work and Research’s website. It was withdrawn at the authors’ request, Todd I. Herrenkohl, the journal’s editor in chief, said in an email.

> That withdrawal occurred “due to a failure to follow research protocols for human subjects,” a Colorado State spokesperson told me in an email. (The study says that Hafen and Villescas Zamzow sought approval from the university’s institutional review board and that the board determined they were not conducting human-subjects research.)

* Yes, colleges face a crisis. It’s also an opportunity.

[https://www.washingtonpost.com/opinions/2025/11/06/colleges-universities-trump-compact/](https://www.washingtonpost.com/opinions/2025/11/06/colleges-universities-trump-compact/)

(Not sure why this was even accepted, but..)

> First, universities should reevaluate the curriculum of the various divisions of knowledge, from the humanities to the social sciences to the natural sciences.

> Second, universities should revise the administrative arrangements that support education and research. While retaining the ability to teach classic observations and findings (the “preservation” of knowledge, after all!), the organization of university departments should evolve.


### Anti-woke/anti-DEI is simply racism

* An anti-KKK law was used to end a scholarship for Black students

[https://www.washingtonpost.com/nation/2025/11/04/ucsandiego-scholarship-black-students/](https://www.washingtonpost.com/nation/2025/11/04/ucsandiego-scholarship-black-students/)

> A scholarship once reserved for Black students at a California university is now available to all after a White student and a right-wing nonprofit alleged it violated a federal anti-Ku Klux Klan law.

> The case’s use of the Ku Klux Klan Act of 1871, signed into law to protect the rights of African Americans in the South, is a novel approach that attorneys for the plaintiffs touted as a victory for equality and a possible blueprint for future challenges.

> The Pacific Legal Foundation filed a lawsuit in July against UC San Diego and the San Diego Foundation, which administers the scholarship meant to bolster the slim Black student population on the campus. Black students make up about 3 percent of UC San Diego’s undergraduate student population. Most of the university’s students are from California, where Black people make up just above 5 percent of the population.

> The groups settled in mid-October before a judge considered the case, and the San Diego Foundation said it would rename its decades-old Black Alumni Scholarship Fund after its founder and an alumnus. The scholarship, worth up to $2,500 a year, or $10,000 total, will now be available to all students.

> Cara McClellan, a professor at the University of Pennsylvania’s Carey Law School, said the San Diego case was “flipping the purpose of the law on its face.”

> If it were taken to court, a similar case could also have wide-ranging implications for private philanthropy outside higher education, she said.

> “It’s an attack on private efforts to use money to pursue what you consider a social justice purpose,” McClellan said. “And it’s through the lens of saying that because it’s race conscious, it’s illegal.”

> “It’s their spin, right, that these types of scholarships are somehow fostering discrimination, when in reality, the intent is the exact opposite,” said Julie J. Park, a professor of education at the University of Maryland, College Park, who has researched race and diversity in higher education.


* Auburn University requires faculty to review courses to comply with anti-DEI law - al.com

[https://www.al.com/news/2025/11/auburn-university-requires-faculty-to-review-courses-for-dei-compliance.html](https://www.al.com/news/2025/11/auburn-university-requires-faculty-to-review-courses-for-dei-compliance.html)


## Funding cuts

* Trump Research Funding Plans: Penalize ‘Repeat Players,’ Reward Compact Signers

[https://www.insidehighered.com/news/government/science-research-policy/2025/11/03/trump-funding-plans-could-harm-top-research](https://www.insidehighered.com/news/government/science-research-policy/2025/11/03/trump-funding-plans-could-harm-top-research)

> And the compact isn’t the only way the president can make that shift. Back in August, he issued an executive order directing “senior appointees” to take charge of awarding, or denying, new grants. He also told them to apply certain principles in their award decisions, which could sap money from the top research institutions.

> “Discretionary grants should be given to a broad range of recipients rather than to a select group of repeat players,” the executive order said. It also said that “to the extent institutional affiliation is considered in making discretionary awards, agencies should prioritize an institution’s commitment to rigorous, reproducible scholarship over its historical reputation or perceived prestige.”

> Both he and Spreitzer expressed broader concerns about other parts of the executive order and the compact moving research funding decisions away from merit-based peer review and toward rewarding political loyalty to the administration.

> “I don’t think currently the peer-review process prioritizes a certain group of institutions over other institutions,” Spreitzer said. “It’s based on the grant application. And so, again, this seems to turn the merit-based process that we have on its head.”


## Federal Agencies

### DOE/OCR

* Under McMahon, ED Is Diminished but Not Dead, Experts Say

[https://www.insidehighered.com/news/government/politics-elections/2025/11/03/under-mcmahon-ed-diminished-not-dead-experts-say](https://www.insidehighered.com/news/government/politics-elections/2025/11/03/under-mcmahon-ed-diminished-not-dead-experts-say)

> Nine months into President Donald Trump’s second term in office, he and his education secretary Linda McMahon have essentially gutted the 45-year-old Department of Education as they work toward their “final mission” of shutting it down.

> First, they cut millions in grants and terminated hundreds of contracts. Then, they eliminated nearly 2,000 employees via buyouts and layoffs, slashing the department’s staff from just over 4,000 to about 2,400. With some offices erased entirely and others just a skeleton of what they once were, the administration started to ship certain grant programs and oversight responsibilities to other agencies entirely.

> All the while, some colleges started to experience funding delays, financial aid officers said no one was on the line to answer their questions and students said their civil rights complaints weren’t being processed. (Distribution of Pell Grants and federal student loans has remained largely unaffected.) Trump officials have also continued to use the agency as part of its pressure campaign on higher ed.

> These events, combined with the department’s latest attempt to fire another 500 employees in October, have shown how a determined executive branch can dismantle ED without congressional approval and fueled concerns about the agency’s ultimate demise. Republicans in Congress who have repeatedly stressed that only the legislative branch can shut down the department have remained largely silent.

(With quotes from SUNY Chancellor John King)


## Institutional assaults

* Are Trump’s Settlements Losing Steam?

[https://www.insidehighered.com/news/government/politics-elections/2025/11/03/are-trumps-settlements-losing-steam](https://www.insidehighered.com/news/government/politics-elections/2025/11/03/are-trumps-settlements-losing-steam)

> But the latest deal raises questions about whether such agreements are losing steam: The flurry of deals reached over the summer has given way to protracted legal battles with institutions that so far seem unwilling to settle.

> While some observers feared a Columbia-like agreement that would impose sweeping changes on UVA, the university appears to have emerged largely unscathed based on the initial agreement. However, critics have warned that the federal government could weaponize the process of compliance.

> “I do think the ultimate goal for a lot of the activity that’s going on is to engineer change of control at major institutions, and if the federal government is successful in being able to drive out a president and control who the senior leadership of the institution is, that’s probably more important in the long run than a monetary fine,” Lake [law professor at Stetson University College of Law] said. “And I’d be very cautious about the monitoring obligations, because that could easily turn into ‘we don’t think you’re complying.’”

### Cornell

* Cornell cracks

[https://statements.cornell.edu/2025/documents/cornell-settlement-agreement.pdf](https://statements.cornell.edu/2025/documents/cornell-settlement-agreement.pdf)

(10 Million a year for 3 years plus...)

(Also)

[https://www.nytimes.com/2025/11/07/us/cornell-deal-trump-administration.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/11/07/us/cornell-deal-trump-administration.html?smid=nytcore-ios-share&referringSource=articleShare)

### University of California System

* NYTimes: Trump Pressure Risks Free Speech at University of California, Judge Warns

[https://www.nytimes.com/2025/11/06/us/trump-pressure-free-speech-university-of-california-lawsuit.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/11/06/us/trump-pressure-free-speech-university-of-california-lawsuit.html?smid=nytcore-ios-share&referringSource=articleShare)


> A federal judge on Thursday excoriated the Trump administration’s blitz of hardball tactics against elite universities, warning that the government’s threats and investigations were undermining academic freedom at the University of California.

> Judge Rita F. Lin, of the Federal District Court in San Francisco, did not immediately order the government to curb its pressure campaign against the university system. But it was only minutes into a hearing on Thursday before Judge Lin, her voice crackling with anger, began depicting the Trump administration’s methods as potentially lawless and deeply detrimental.

> The next month, the American Association of University Professors and other labor groups with ties to the university system sued, pleading with the court in San Francisco to block the Trump administration “from using the threat of legal and financial sanctions in retaliation for the exercise of free speech rights” by people associated with the University of California.

> Thursday’s hearing focused on a request for Judge Lin to issue a preliminary injunction. Although the judge, an appointee of former President Joseph R. Biden Jr., said that she did not expect to rule until at least late next week, a barrage of sharp questions suggested that she was immensely skeptical of the government’s approach to schools like the University of California.

> With a Justice Department lawyer, Abhishek Kambli, before her, Judge Lin asked whether the government had followed the procedures required under assorted civil rights laws to cut research funding.

> Mr. Kambli acknowledged that the government had not, though he said the Trump administration had relied on other legal authorities.

### George Mason

* House Republicans Say George Mason’s Leader Broke the Law. His Lawyer Sees ‘a Political Lynching.’

[https://www.chronicle.com/article/house-republicans-say-george-masons-leader-broke-the-law-his-attorney-sees-a-political-lynching](https://www.chronicle.com/article/house-republicans-say-george-masons-leader-broke-the-law-his-attorney-sees-a-political-lynching)



### Others

* New Emails Show What Happened Before a Texas A&M Professor’s Firing

[https://www.chronicle.com/article/new-emails-show-what-happened-before-a-texas-a-m-professors-firing](https://www.chronicle.com/article/new-emails-show-what-happened-before-a-texas-a-m-professors-firing)

(Lots of back and forth, and then an attempt)

> Due to the president’s objection, according to McCoul, Johansen proposed reclassifying her course, which was supposed to be numbered as ENGL 361, to a higher level — retaining the same syllabus but lacking core curriculum credit. McCoul said she was told this change would sidestep a restriction on “controversial” material in the core curriculum. Texas passed a law this year that gives governing boards greater oversight of core courses, which count toward graduation requirements.

> McCoul’s new course would be ENGL 394, according to the emails. Her original ENGL 361 course would be taught by a different professor and have a different syllabus. According to one administrator’s email, the directive to change the course’s instructor at the last minute came directly from the president and provost: “There was no option to not do this.”

> According to the emails reviewed by The Chronicle, Welsh received praise from several of the students who reached out to him about their concerns with McCoul’s summer course. But his decision to discipline McCoul and her supervisors was seen by many scholars as a violation of academic freedom and a chilling window into the power dynamics of Texas. ... Ten days later, he resigned.

* U of Austin to End Tuition ‘Forever’ With Help of $100M Gift

[https://www.insidehighered.com/news/business/revenue-strategies/2025/11/05/u-austin-announces-100m-gift-end-tuition-forever](https://www.insidehighered.com/news/business/revenue-strategies/2025/11/05/u-austin-announces-100m-gift-end-tuition-forever)

> After receiving even more support from a big conservative donor, the not-yet-accredited institution announced it will neither charge tuition nor accept government funds. Some are skeptical.


> Carvalho said the university currently has 150 students in its freshman and sophomore classes, and he plans to grow total enrollment to 400 to 500 for now. “We need this first phase of growth to be small,” he said. ... “We talk about building the Navy SEALs of the mind,” he said. “The Navy SEALs are not a class of thousands and thousands.”

> Hutchens [a university research professor and faculty member in the University of Kentucky’s College of Education] said New College of Florida, a public institution taken over by Gov. Ron DeSantis’s conservative board appointees, appears to be charting “a similar iconoclastic path.” He noted New College took a public stand early against what some call wokeness.

> “That’s not necessarily been an easy fix for New College to just automatically thrive,” he said. He’s curious if such institutions are going after the same donors, he said, and they may eventually be competing more with one another than the institutions they’re setting themselves apart from.

(Let's look at the name-brand donors and founders:)

> Yass—a billionaire co-founder of financial trading firm Susquehanna International Group and a significant investor in TikTok owner ByteDance [100M + 36M]

> Harlan Crow, who controversially funded trips for U.S. Supreme Court Justice Clarence Thomas,

> Peter Thiel, a co-founder of Palantir and friend to Vice President JD Vance

> One of the university’s founders is Bari Weiss, who also founded The Free Press and recently became editor in chief of CBS News.

(Also)

[https://www.wsj.com/us-news/education/trader-jeff-yass-is-giving-100-million-to-anti-woke-university-of-austin-370ddecb?st=4hsxFC](https://www.wsj.com/us-news/education/trader-jeff-yass-is-giving-100-million-to-anti-woke-university-of-austin-370ddecb?st=4hsxFC)


* Florida DOGE Details Disproportionate Spending at New College

[https://www.insidehighered.com/news/governance/trustees-regents/2025/11/07/florida-doge-finds-disproportionate-spending-new](https://www.insidehighered.com/news/governance/trustees-regents/2025/11/07/florida-doge-finds-disproportionate-spending-new)

(Spend whatever it takes to slay the "woke" dragon, it appears)

> Data presented at Thursday’s Florida Board of Governors offers the clearest breakdown so far of what New College is spending per student compared to 11 other system members. NCF spent $83,207 per student in fiscal year 2024, the highest among state universities.

> The University of Florida, a major research institution, was the next highest at $45,765 per student, while the lowest was the University of Central Florida at $12,172 per student, according to data compiled by the Florida Department of Government Efficiency.

> New College and UF also had the highest number of administrators per 100 students. New College had 33.3 administrators per 100 students while UF had 26.9. Others in the system ranged from a low of 4.6 administrators per student at UCF to 12.6 at the University of South Florida.

## How best to describe the times we are in

* NYTimes: The Old Order Is Dead. Do Not Resuscitate.

[https://www.nytimes.com/2025/11/04/opinion/davos-neoliberalism-trump-tariffs.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/11/04/opinion/davos-neoliberalism-trump-tariffs.html?smid=nytcore-ios-share&referringSource=articleShare)

> Few things are more disconcerting than feeling the ground shift beneath you, as anyone who has experienced a serious earthquake knows. This is what we are living through. A way of ordering economic life — neoliberalism — that emerged in the 1980s is weakening rapidly.

> Once-heretical ideas such as raising tariffs have gained influence, and believers in the old order, plus almost everyone else, have become disoriented. Where are we heading? Are we subject to the whims of a madman? For the first time in most people’s memory, our economic future seems uncertain for a new reason: The immediate past cannot tell us what comes next.

(And it goes from there. For me, the most hard to believe statement is:)

> Not once was the old regime resurrected. Instead, capitalism forged ahead in entirely new directions. We had better accept this about today, as well.

## Blowback

> Out of Caution or Protest, Foreign Scholars Skip U.S. Conferences

[https://www.insidehighered.com/news/faculty-issues/career-development/2025/11/04/cautious-or-protesting-foreign-scholars-skip-us](https://www.insidehighered.com/news/faculty-issues/career-development/2025/11/04/cautious-or-protesting-foreign-scholars-skip-us)

> During President Donald Trump’s first term in office, David Murakami Wood didn’t cross the U.S.–Canada border once.

> “I refused to go largely in solidarity with the countries who Trump targeted for visa exclusions,” said Murakami Wood, a criminology professor at the University of Ottawa. “This time … it’s even worse. It’s not specific countries [being targeted], but we’re seeing people being arbitrarily arrested and taken off the streets, deportations, people being arrested in transit.”

> Several conference organizers have already canceled their U.S. meetings or moved them outside the country. For example, the International Society for Research on Aggression announced in April that it would relocate its 2026 meeting from New Jersey to St. Catharines, in Ontario, Nature reported. The Northwest Cognition & Memory conference in May was relocated from Western Washington University in Bellingham to Victoria, British Columbia. And the 2026 Cities on Volcanoes conference planned for Bend, Ore., was canceled until 2030.

* Why Trump’s cuts to scientific research are a big win for China

[https://www.washingtonpost.com/world/2025/11/05/china-brain-gain-united-states-scientists/](https://www.washingtonpost.com/world/2025/11/05/china-brain-gain-united-states-scientists/)

> Over the last decade, there has been a rush of scholars — many with some family connection to China — moving across the Pacific, drawn by Beijing’s full-throttle drive to become a scientific superpower.

> But Donald Trump’s return to the White House has turbocharged this effort. The Trump administration has cut billions in science funding, canceled grants for some of America’s most elite universities, revoked international student visas and hiked up costs for highly skilled H-1B visas.

> “The U.S. is increasingly skeptical of science — whether it’s climate, health, or other areas,” said Jimmy Goodrich, an expert on Chinese science and technology at the University of California Institute on Global Conflict and Cooperation. “While in China, science is being embraced as a key solution to move the country forward into the future.”

> The moves also provide crucial propaganda victories for the Chinese Communist Party and help leader Xi Jinping achieve his vision to turn China into a science and technology powerhouse by 2035.


* October Brought Deep Cuts at Multiple Campuses

[https://www.insidehighered.com/news/business/cost-cutting/2025/11/07/october-brought-deep-cuts-multiple-campuses](https://www.insidehighered.com/news/business/cost-cutting/2025/11/07/october-brought-deep-cuts-multiple-campuses)

> Colleges shed hundreds of jobs last month as the sector grappled with federal research funding issues, declining enrollment, state budget cuts and other pressure points.

> University of Southern California...Michigan State University...Carnegie Mellon University...University of Northern Colorado...University of Louisiana Lafayette...Eastern Illinois University...Xavier University of Louisiana...Harvard University...Siena University...Clarke University...University of Wisconsin-Madison...University of Idaho...Nebraska Wesleyan University...Rhode Island College...PennWest University

## And just because it is fun

* NYTimes: Moon Duchin on the ‘Mathematical Quagmire’ of Gerrymandering

[https://www.nytimes.com/2025/11/03/science/duchin-math-elections-gerrymandering.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/11/03/science/duchin-math-elections-gerrymandering.html?smid=nytcore-ios-share&referringSource=articleShare)

> She frames redistricting as a partition problem: Divide an object into pieces according to given rules. In this context, the object is a state and its voters; the pieces are the allotted number of districts. Although the rules vary by state, Dr. Duchin refers to “the big six”: population balance; compactness; contiguity; respect for existing civic boundaries (counties, cities, towns); respect for communities of interest and racial fairness (per the Voting Rights Act and the Constitution). Racial fairness is the crux of the Texas case, and a Louisiana case currently before the Supreme Court; it is an element of the complaint in the recently filed New York case, and many others.

> As a math problem, assembling so many tiny pieces into large districts while balancing multiple parameters quickly explodes in complexity. Even for computers, it is intractably hard to enumerate all the possible maps.

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
