# Nov 28

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

This week, just after Thanksgiving meals are done the govt. eats Northwestern's lunch.

## Academic freedom

* NYTimes: Texas A&M Was Wrong to Fire Professor Over Gender Lesson, Panel Rules

[https://www.nytimes.com/2025/11/21/us/texas-am-professor-gender-lesson-panel-ruling.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/11/21/us/texas-am-professor-gender-lesson-panel-ruling.html?smid=nytcore-ios-share)

> A Texas A&M University appeals panel has unanimously ruled that the school was “not justified” when it fired a lecturer who had been accused of teaching a course that recognized more than two genders.

> The decision does not guarantee that the lecturer, Melissa McCoul, will be reinstated. But the ruling puts pressure on the university’s administration as it decides a matter that put Texas A&M at the center of the nation’s rancorous debate about what can be taught in classrooms.

> In a four-page decision, the committee’s chairman said that the panel had been “especially concerned by the lack of a rigorous investigation into the circumstances, details, specific events and timeline leading to Dr. McCoul’s summary dismissal.” The report also cited other misgivings about the university’s handling of the episode and repeatedly said that A&M “did not meet the burden of proof that Dr. McCoul’s summary dismissal was based on good cause.”

> In a statement late on Friday, Texas A&M acknowledged it had received the “non-binding findings” from the hearing panel. The university said its interim president, Tommy Williams, would review the report “carefully before making a decision in the coming days or weeks.” Mr. Williams is not a career academic, but instead rose to power in the state when he was a Republican member of the Texas Legislature.

> If Texas A&M's administration does not accept the panel’s findings, Ms. Reichek warned, “Dr. McCoul intends to swiftly pursue her First Amendment, due process, and breach of contract claims in court.”

* Texas State Board Upholds Firing of Professor

[https://www.insidehighered.com/news/quick-takes/2025/11/24/texas-state-board-upholds-firing-professor](https://www.insidehighered.com/news/quick-takes/2025/11/24/texas-state-board-upholds-firing-professor)

> Texas State University president Kelly Damphousse accused professor Thomas Alter of inciting violence when he fired Alter and revoked his tenure in September. Alter sued and was reinstated while the university reviewed his case using the standard faculty investigatory process. The university upheld Damphousse’s decision in October, according to the American-Statesman.

> Alter, an associate professor of history, spoke at the Revolutionary Socialism Conference in part about how “insurrectionary anarchism” had gained ground recently. “Many insurrectionary anarchists are serving jail time, lost jobs and face expulsion from school,” he said. “They have truly put their bodies on the line. While their actions are laudable, it should be asked, what purpose do they serve? As anarchists, these insurrectionists explicitly reject the formation of a revolutionary party capable of leading the working class to power. Without organization, how can anyone expect to overthrow the most bloodthirsty, profit-driven mad organization in the history of the world—that of the U.S. government.”

> Alter’s firing came shortly after Texas A&M University fired a lecturer who faced accusations from a student that her gender identity lesson violated state and federal law. The university faculty council and an appeals panel have found that the university wasn’t justified in firing the lecturer.

* Indiana’s Attack on Intellectual Diversity

[https://www.insidehighered.com/opinion/columns/debatable-ideas/2025/11/26/indianas-attack-intellectual-diversity](https://www.insidehighered.com/opinion/columns/debatable-ideas/2025/11/26/indianas-attack-intellectual-diversity)

> I ndiana’s new Act 202, which advocates of free inquiry have feared would suppress academic freedom despite its claims to promote intellectual diversity, now has been implemented in real life: Citing Act 202, Indiana University (IU) officials suspended Social Work professor Jessica Adams from teaching a class called “Diversity, Human Rights and Social Justice” because U.S. Senator Jim Banks complained that she showed a chart in class that included “Make America Great Again” as a slogan that can be used as covert white supremacy.

> Obviously, banning a professor from teaching because they used a chart about white supremacy is a direct violation of this provision of Act 202. By suspending a professor from a class and invoking this law, the Indiana University administration is going far beyond the requirements and the authority of the law, and Indiana officials are violating the Bill of Rights, Act 202 and their own policies.

## Freedom of expression

* Khalil Sues for Information Regarding Government Use of Doxing Sites

[https://insidehighered.com/news/quick-takes/2025/11/24/khalil-sues-info-government-use-doxing-sites](https://insidehighered.com/news/quick-takes/2025/11/24/khalil-sues-info-government-use-doxing-sites)

> Mahmoud Khalil, the Columbia University graduate and student protester who was detained for several months by ICE earlier this year, is suing the Trump administration for information about its partnerships with organizations such as Canary Mission that dox pro-Palestinian protesters, according to an announcement released by the Center for Constitutional Rights.

> “Mr. Khalil and the public at large have the right to know about the depth of the collusion between the federal government and the shadowy groups targeting people who speak out against a genocide,” said Adina Marx-Arpadi, an attorney and Justice Fellow at the Center for Constitutional Rights, in the press release.

* A UC-Berkeley Protest of a Turning Point USA Event Has Now Prompted 2 Trump Investigations

[https://www.chronicle.com/blogs/the-trump-agenda/a-uc-berkeley-protest-of-a-turning-point-usa-event-has-now-prompted-2-trump-investigations](https://www.chronicle.com/blogs/the-trump-agenda/a-uc-berkeley-protest-of-a-turning-point-usa-event-has-now-prompted-2-trump-investigations)

> This latest investigation of a university differs from others opened by the Trump administration so far: The review is being led by the Office of Federal Student Aid and concerns alleged violations of the Clery Act, the campus-safety law.

> On November 10, students at UC-Berkeley gathered outside of a campus auditorium to protest what would have been the late Charlie Kirk’s last stop on his “American Comeback Tour.” The protesters clashed with event attendees, leading to at least one hospitalization and three arrests.

> The following day, the Justice Department announced it would investigate “potential criminal and civil aspects” of what happened at the protest.

> Secretary of Education Linda McMahon said in a Tuesday news release that the Education Department’s separate investigation is not focusing on potential violations of students’ First Amendment rights, but rather to determine if UC-Berkeley violated the Clery Act.

(Also)

[https://www.insidehighered.com/news/quick-takes/2025/11/26/ed-investigates-berkeley-over-protest-violence](https://www.insidehighered.com/news/quick-takes/2025/11/26/ed-investigates-berkeley-over-protest-violence)

### Anti-woke/anti-DEI is simply racism

* Are Diversity Essay Prompts Disappearing? Not Yet.

[https://www.insidehighered.com/news/admissions/traditional-age/2025/11/26/some-colleges-cut-diversity-essays-they-remain-popular](https://www.insidehighered.com/news/admissions/traditional-age/2025/11/26/some-colleges-cut-diversity-essays-they-remain-popular)

> Two years after the Supreme Court banned the use of race in college admissions decisions and in the wake of the Trump administration’s attacks on diversity, equity and inclusion, colleges’ use of diversity- and identity-related supplemental essay prompts is patchy.

> After a boom in prompts about applicant’s identities, several universities have scrapped the essays entirely for the 2025–2026 admission cycle. Still others, especially selective universities, have kept the prompts, saying they are the best way to get to know their applicants.

> In the majority opinion in Students for Fair Admissions v. Harvard, Chief Justice John Roberts said it was acceptable for students to continue discussing race in their essays: “Nothing in this opinion should be construed as prohibiting universities from considering an applicant’s discussion of how race affected his or her life, be it through discrimination, inspiration, or otherwise.”

(At Baruch, a job ad had this substitute language: "Additionally, applicants are required to submit a narrative statement of one to two pages describing, first, their commitment to all facets of academic freedom, including their commitment to encouraging the expression of viewpoints from all sides of the political, social, and cultural spectrums in their teaching; and second, their commitment to working effectively with faculty, staff, and students in a pluralistic urban campus environment with a substantial population of students who are among the first-generation of their family to attend college.")

* Universities May Lose State Dept. Partnership Due to Trump’s Anti-DEI Crusade

[https://www.insidehighered.com/news/diversity/2025/11/26/colleges-may-lose-state-dept-partnership-anti-dei-crusade](https://www.insidehighered.com/news/diversity/2025/11/26/colleges-may-lose-state-dept-partnership-anti-dei-crusade)

> But now the Trump administration’s domestic policy fight against diversity, equity and inclusion could upend this partnership between the State Department and universities. The Guardian reported last week that the department is planning to suspend 38 institutions from the program, effective Jan. 1, because they had what the department dubbed a “clear DEI hiring policy.” It’s unclear how the department defines that phrase or how it determined these institutions have such policies.

> On Tuesday, The Guardian—citing what it called an unfinalized “internal memo and spreadsheet”—published the list of institutions that State Department plans to kick out, keep in or add to the program. A State Department spokesperson didn’t confirm or deny the list to Inside Higher Ed or provide an interview, but sent an email reiterating the administration’s anti-DEI stance.

(The list of colleges can be seen here:)

[https://www.theguardian.com/us-news/2025/nov/25/us-universities-cuts-dei-state-department](https://www.theguardian.com/us-news/2025/nov/25/us-universities-cuts-dei-state-department)


## Federal Agencies

### DOE/OCR

* Warren Requests Investigation into ED’s Dismantling

[https://www.insidehighered.com/news/quick-takes/2025/11/24/warren-requests-investigation-eds-dismantling](https://www.insidehighered.com/news/quick-takes/2025/11/24/warren-requests-investigation-eds-dismantling)

> Massachusetts Senator Elizabeth Warren asked the Education Department Inspector General to investigate the recent agreements that outsource several grant programs to other federal agencies.

> “The dismantling of ED—including ED’s recent move to transfer a range of statutory duties to other agencies—threatens devastating consequences for students, borrowers, and families,” Warren wrote in a letter Sunday to the Office of Inspector General (OIG).


## Institutional assaults

### Accreditation

* Education Department Names Five New Accreditation Advisers

[https://www.insidehighered.com/news/government/politics-elections/2025/11/25/ed-names-five-new-naciqi-members](https://www.insidehighered.com/news/government/politics-elections/2025/11/25/ed-names-five-new-naciqi-members)

> Education Secretary Linda McMahon appointed on Tuesday five new members to the National Advisory Committee on Institutional Quality and Integrity, a body that advises on accreditation, including which organizations should be recognized by the federal government.

> Robert Eitel is president of the Defense of Freedom Institute, a conservative think tank. ... Eitel has a background in for-profit education, serving past stints at for-profit college operators Bridgepoint Education Inc. and Career Education Corp.

> Joshua Figueira is currently the deputy general counsel and managing director of the Office of Compliance, Risk, and Legal Affairs at Brigham Young University–Idaho. (Not BYU, but another mormon university)

> Jay Greene is a senior research fellow for the Center for Education Policy at the Heritage Foundation. [He] also worked for The Manhattan Institute for a decade.

> Steven Taylor is the policy director and senior fellow in economic mobility at Stand Together Trust [It began with our founder Charles Koch...].

> Emilee Reynolds is a student at Western Carolina University.

(So much for viewpoint diversity! This is from the press release)

> NACIQI is authorized under Section 114 of the Higher Education Act of 1965. The committee serves as an independent advisory body, making recommendations to the Secretary on accreditation matters, including the recognition of institutional and programmatic accrediting agencies. Recommendations from NACIQI, along with recommendations from Department staff, are provided to the Senior Department Official, who then issues a final decision on recognition matters.

### Harvard

* NYTimes: Pabst, Pamphlets and a Petition: A Harvard-Yale Tailgate in the Trump Era

[https://www.nytimes.com/2025/11/23/us/politics/yale-harvard-football-trump.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/11/23/us/politics/yale-harvard-football-trump.html?smid=nytcore-ios-share)

> As for the game, Yale upset Harvard, 45-28.

> Senator Richard Blumenthal, a Connecticut Democrat, was the celebrity ringer for the petition campaign. A graduate of Harvard in 1967 and Yale Law School in 1973, Mr. Blumenthal acknowledged that cooperation is not a natural state for schools in perpetual competition for grant money, staff members and students.

> Many college administrators are also inclined to keep their heads down when others face pressure, hoping to avoid attracting the attention of the Trump administration.

> “There’s real fear,” Mr. Blumenthal said. “I’ve urged them — there is strength in numbers.”

> Mr. Blumenthal tested out his pitch on members of the crowd for support for the petition. The 79-year-old senator plunged into a mass of 20-somethings, many of whom were drinking from red plastic cups.

> He proffered postcards and stickers, like a magician offering to perform a trick — take a card, any card.

> “No Yale stickers,” one of the Harvard men said. He was for academic freedom, but some lines could not be crossed on game day.


### Indiana

* Indiana May Reject New Degrees That Don’t Commit to “Values of American Society”

[https://www.insidehighered.com/news/quick-takes/2025/11/25/ind-may-reject-degrees-dont-commit-american-values](https://www.insidehighered.com/news/quick-takes/2025/11/25/ind-may-reject-degrees-dont-commit-american-values)

> ndiana may reject proposed degree programs at public institutions that don’t “cultivate civic responsibility and commitment to the core values of American society.” Earlier this month, the Indiana Commission for Higher Education introduced a question on “civic responsibility and commitment” in its new degree proposal form, Indiana Public Media reported Friday.

> Prominent faculty leaders told Inside Higher Ed they weren’t consulted about the change, which they denounced as a curtailment of academic freedom and an echo of President Trump’s proposed Compact for Academic Excellence in Higher Education.

> The governor-appointed commission claims it wants faculty to educate students about civic engagement, Akou said, yet “this provision was added in a rather undemocratic way.” She called the “requirement” to demonstrate “commitment to the core values of American society” a “racist and xenophobic dog whistle,” and questioned how she, a fashion design professor, would be expected to meet the criterion if her program were being newly proposed. “Only politicians could think it’s a good idea that everyone at a university should teach some version of political science,” she said. “We do actually teach a lot of other things.”

> “This is yet another rollback of academic freedom and shared governance,” O’Neill [president of the Indiana Conference of the American Association of University Professors] said. “It’s not the place of a state—it’s not the place of politicians—to tell faculty such things, and it opens a door for political reprisal, for other ways to limit academic freedom.”


### Northwestern

* NYTimes: Northwestern University Nears Deal to Resolve Its Conflict With the White House

[https://www.nytimes.com/2025/11/26/us/politics/northwestern-university-trump-deal.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/11/26/us/politics/northwestern-university-trump-deal.html?smid=nytcore-ios-share)

(Hot off a field hockey championship, the Wildcats turn tail and close on a "deal")

> The school, one of several to face pressure campaigns from the Trump administration, would pay a $75 million fine and have its research funding restored under terms of the agreement being discussed.

> President Trump has made a priority of attaching big price tags to the agreements. Critics have likened Mr. Trump’s approach to extortion, while others have chalked it up as a cost of doing business with this administration.


(The agreement)

[https://www.northwestern.edu/president/docs/resolution-agreement-united-states-northwestern.pdf](https://www.northwestern.edu/president/docs/resolution-agreement-united-states-northwestern.pdf)

(includes:)

> 9. Northwestern will ensure through clear, visible guidelines that its faculty, staff, and administration are aware of and uphold in practice the following commitments:

> a. That the protections of Title VI apply to all individuals equally, and that no groups or classes of people receive more or less protection under Title VI for their particular identity, classification, or status.

> b. That Title VI prohibits harassment on the basis of shared ancestry, including Jewish ancestry.

> c. That harassment that creates a hostile environment for students on the basis of a protected characteristic, such as shared ancestry, is a violation of Title VI.

> d. That an institution that knows or acts with deliberate indifference as to the existence of a hostile environment has an affirmative responsibility to eliminate that hostile environment, remedy its effects, and prevent its recurrence, and that these measures include disciplinary actions.

> e. That the institutional process for complaints of discrimination and harassment must include documenting investigations and decisions and ensuring that such documentation can be stored and later retrieved from the University's data systems.

(And)

> 13. Prior to the Effective Date of this Agreement, Northwestern has put in place policies and procedures relating to demonstration, protests, displays, and other expressive activities, including the Demonstration Policy, the Display and Solicitation Policy, Student Handbook, and Student Code of Conduct, as set out in the Progress Report on Northwestern University Efforts to Combat Antisemitism dated August 5, 2025. Northwestern will maintain those policies and procedures and enforce them, including with respect to the following:

> a. Prohibition on demonstrations and other protest activities that occur in academic buildings and places where academic activities take place and that impede ordinary classroom activities or studying.

> b. Prohibition on overnight demonstrations in any University locations.

> c. Prohibition on any disruption, prevention, obstruction, or attempt to prevent or obstruct (i) regularly scheduled University activities; (ii) co-curricular activities; (iii) University or public events; (iv) medical center access or business; or (v) the movement of individuals throughout the campus, including on its grounds and buildings, except in specific outdoor areas designated for demonstrations.

> d. Prohibition on demonstrations at the Rock location on the Evanston campus that violate University time, place, and manner rules which are designed to limit disruption during times when classes are offered in nearby buildings.

> e. Prohibition on the use of amplified sound at the Rock location on the Evanston campus without reservation and approval or when it violates University time, place, and manner rules which are designed to limit disruption during times when classes are offered in nearby buildings.

> f. Prohibition on on-campus displays, including flyers, banners, chalking, and 3-D installations outside of areas specifically designated by Northwestern.

> g. Prohibition on the use of tents (with exception for University-sponsored events and for the purposes of guarding and painting the Rock), light displays, and chalking on buildings.

> h. All demonstration activity is subject to Northwestern’s anti-discrimination and anti-harassment policies.

> During the Term of this Agreement, Northwestern shall not revise or modify these policies and procedures without the consent of the Assistant Attorney General.

> 17. Prior to the Effective Date of this Agreement, Northwestern has implemented mandatory antisemitism training for all students, faculty, and staff. Northwestern will continue to provide such training to all new students, faculty, and staff in each of Northwestern undergraduate, graduate, and professional schools, and revise it as appropriate.

> 18. Northwestern shall prohibit wearing of face masks or facial coverings for the purposes of concealment of an individual’s identity, and shall consistently enforce that prohibition against anyone who fails to comply with a request, directive, or instruction of University officials acting in performance of their duties to remove face masks or coverings for purposes of identification.

(And)

> 27. Northwestern will continue to provide regular specialized training on Title VI to staff of the Office of Civil Rights and Title IX Compliance, Office of Community Standards, Human Resources Office, and the admissions staff, which will incorporate the DOJ’s “Guidance for Recipients of Federal Funding Regarding Unlawful Discrimination” of July 29, 2025, as a training resource so long as that Guidance remains operative. Northwestern will also continue to ensure that faculty and staff are made aware of the applicable Executive Orders and federal guidance. As of the Effective Date, Northwestern has reviewed and, where appropriate, revised University training modules to comply with the foregoing.

(Bondi's Guidance)

[https://www.justice.gov/ag/media/1409486/dl](https://www.justice.gov/ag/media/1409486/dl)

### Others

* Nassau Community College Prepared to Sue Over Rejected Presidential Pick

[https://www.insidehighered.com/news/quick-takes/2025/11/26/nassau-cc-rejected-presidential-pick-prompts-lawsuit-threat](https://www.insidehighered.com/news/quick-takes/2025/11/26/nassau-cc-rejected-presidential-pick-prompts-lawsuit-threat)

> Trustees at Nassau Community College are poised to file a lawsuit after the State University of New York’s Board of Trustees denied their presidential pick.

> Earlier this month, SUNY trustees voted unanimously, with three members absent, to reject Maria Conzatti, who has run the college as interim or acting president for almost four years. A SUNY official told Newsday it was the first time the system’s board disapproved a presidential nominee.

> The resolution voted on asked that Conzatti’s appointment by Nassau Community College’s board be “disapproved” with no further explanation.

> The conflict comes amid broader tensions between the college’s faculty union and the administration over the consolidation of academic departments and a union contract that expired in August, among other issues. The union sued the college last year arguing the elimination of 15 department chairs violated state regulations, but a judge dismissed the case. The union has since appealed.

(Cf. this statement from the UFS Executive Committee which involved this president who was denied appointment by the SUNY board)

[https://www1.cuny.edu/sites/cunyufs/committees/executive/2025-fccc-statement-of-support/](https://www1.cuny.edu/sites/cunyufs/committees/executive/2025-fccc-statement-of-support/)


* Arizona State’s President Is Pulling Out All the Stops to Get on Trump’s Good Side

[https://www.wsj.com/us-news/education/arizona-state-university-trump-63e31b8d?mod=hp_featst_pos3](https://www.wsj.com/us-news/education/arizona-state-university-trump-63e31b8d?mod=hp_featst_pos3)

> In October, President Trump asked a handful of top universities to accept sweeping campus changes in exchange for federal-funding advantages. Most schools rejected the proposal, fearing Trump would undermine their independence.

> One college president, though, had a different response: Why wasn’t I invited?

> Michael Crow, the outspoken longtime leader of Arizona State University, was miffed he hadn’t been approached. ASU’s sister school, the University of Arizona, had been invited. Crow, who had long championed higher-education reform and had signaled willingness to work with the administration, believed he should have been included. He and his advisers wondered if officials had mixed up the two schools, people familiar with the matter said.

> “There’s always opportunity,” Crow said in an interview. “And there’s opportunity now.” ... There is opportunity for the bold amid the Trump turbulence, he says. “Carpe Diem. Seize the day, call the play.”



(Maybe worth noting, ASU has some very large financial issues)

[https://www.insidehighered.com/news/business/cost-cutting/2024/11/06/arizona-budget-woes-still-loom-large-one-year-later](https://www.insidehighered.com/news/business/cost-cutting/2024/11/06/arizona-budget-woes-still-loom-large-one-year-later)

## Op eds

* The University of Virginia and Cornell deals with Trump set a dangerous precedent | Serena Mayeri and Amanda Shanor | The Guardian

[https://www.theguardian.com/commentisfree/2025/nov/23/uva-cornell-trump](https://www.theguardian.com/commentisfree/2025/nov/23/uva-cornell-trump)

> UVA’s deal is not a deal at all. It provides that if UVA makes unspecified changes on “DEI” to the federal government’s satisfaction and provides it with data through 2028, the administration will close currently open investigations into the university. The federal government can open new inquiries at any time.

> What the agreement does do is contractually bind UVA to the Trump administration’s definition of discrimination. That definition outstrips anything the law requires and, in fact, may force UVA to violate statutory and constitutional law. Far from extricating the university from government oversight, the agreement subjects UVA to federal monitoring and the risk of draconian financial penalties if the federal government decides, at its sole discretion, that the university has not complied.

> UVA pledged to adhere to the drastically over- and under-inclusive definition of discrimination contained in non-binding July Department of Justice guidance. That guidance goes far beyond the supreme court’s 2023 decision in SFFA v Harvard, which prohibited certain uses of race in college admissions. SFFA explicitly allows schools to consider, for example, how an individual’s race – “through hardship, inspiration, or otherwise” – has affected their lives, and acknowledges diversity as a laudable goal. The government guidance, by contrast, prohibits the use of race, sex, or other protected characteristics “no matter the program’s labels, objectives, or intentions.”

> The administration’s guidance is riddled with ambiguities and internal contradictions. For example, its broad definitions of unlawful discrimination could be read to prohibit reliance on virtually any criteria other than those that tend to decrease diversity, such as standardized test scores. Practically speaking, if UVA gives an admissions boost–or even a scholarship–to students who have experienced economic hardship, or to first-generation college students, would that violate its agreement?

> Moreover, the agreement places the university in grave financial jeopardy. It purports to pause pending investigations of UVA, while still allowing new ones, but the federal government reserves the right – at any time and for any reason – to terminate the agreement and to “pursue enforcement actions, monetary fines, or grant or funding terminations”. It requires UVA’s president to certify quarterly, under penalty of perjury, that the university has complied with the agreement, and it allows the government to investigate whether the university has in fact complied to its satisfaction. The federal government already has warned that certifications it determines to be untrue risk civil and criminal liability for “civil rights fraud” under the False Claims Act, including through actions brought by private citizens.

> Cornell’s agreement, announced on 7 November, is less lopsided, perhaps thanks in part to the university’s responsiveness to community input. But it is still dangerous.

> The agreement’s fine print contains additional perils. For example, Cornell agrees to disclose a range of student information and recognizes the government’s prerogative to share that data with law enforcement, an ominous nod to potential immigration consequences. A reference to the “prevention of terrorist financing” may relate to foreign funding – but in light of Trump’s recent executive orders targeting those the federal government considers to promote “extremist” views about race, gender, and migration as “domestic terrorists”, this provision may prove more menacing to free expression.

> Both agreements affirm “academic freedom” and promise no interference with curricula or the free expression of ideas. But if universities can be subject to drastic financial penalties anytime the federal government decides “in its sole discretion” that the university is not complying, it is difficult to believe there will not be strong incentives for administrators, faculty, and students to avoid any speech or conduct that might attract negative attention from the Trump administration. Whether explicit or implicit, such federal control cuts to the heart of the freedom of inquiry that allows universities to contribute to the innovations, economic prosperity, and creation of knowledge that have made American higher education the envy of the world.

## How best to describe the times we are in

* NYTimes: Wealthy People Have Always Shaped Universities. This Time Is Different.

[https://www.nytimes.com/2025/11/24/us/billionaires-influence-universities-trump.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/11/24/us/billionaires-influence-universities-trump.html?smid=nytcore-ios-share)

> “Anyone is entitled to express their feelings about universities, to condemn universities,” said Lee C. Bollinger, who led both Columbia University and the University of Michigan. “But at some point, the level of influence is just way out of proportion to the merits of their claims.”

> Days after Mr. Trump’s inauguration last winter, Mr. Rowan told an audience at the Park Avenue Synagogue that he did not “think one needs to go and change thousands of universities. I think you need to change five.”

> Working with allies that his aides have refused to identify, Mr. Rowan helped devise a proposal that, among other conditions, called for schools to “recognize that academic freedom is not absolute” and to banish considerations like gender, political views or sexual orientation from admissions and hiring decisions.

> An unsigned copy of the proposal circulated quietly in higher education circles last winter, alarming some who wondered whether it was a blueprint for a future Trump administration move.

> It was.

> The White House has vowed to regroup in the wake of the October call and, according to four people familiar with the deliberations, has signaled that it could rewrite the proposal in significant ways. But the administration missed its original goal of having a signed deal by Friday.

> “I kind of yearn,” Mr. Nassirian [a vice president for Veterans Education Success] said, “for the gilded age when billionaires satisfied their extracurricular interests by collecting Fabergé eggs and prized ponies.”

## AI misdeeds

* NYTimes: I’m a Professor. A.I. Has Changed My Classroom, but Not for the Worse.

[https://www.nytimes.com/2025/11/25/magazine/ai-higher-education-students-teachers.html?smid=nytcore-ios-share](https://www.nytimes.com/2025/11/25/magazine/ai-higher-education-students-teachers.html?smid=nytcore-ios-share)

> An A.I.-resistant English course has three main elements: pen-and-paper and oral testing; teaching the process of writing rather than just assigning papers; and greater emphasis on what happens in the classroom. Such a course, which can’t be A.I.-proof because that would mean students do no writing or reading except under a teacher’s direct supervision, also obliges us to make the case to students that it’s in their self-interest to do their own work. Colleagues I’ve talked to around the country do discuss A.I. with their students, and some have found creative ways to bring it into the curriculum, but few have turned to high-tech solutions like A.I.-detecting software or monitoring keystroke histories.

> Many teachers have changed the way they test students. That often means returning to old-school pen-and-paper exams — thereby contributing to the comeback of the blue book, a horseshoe-crab-like relic of primordial ed tech that A.I. has saved from extinction. Assessments like tests and quizzes should reinforce the behavior you want, so mine consist of mini-essays that gauge command of the reading and of the ideas and analytical methods we’ve talked about in class, with most of the points awarded for interpretive substance. As a way to sum up in the last few minutes of a class discussion, we sometimes knock around students’ suggestions for a fair exam question about what we covered that day.

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
