# Nov 14

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

## Academic freedom

* An Instructor Showed a Graphic on White Supremacy. Did She Break the Law?

[https://www.chronicle.com/article/an-instructor-showed-a-graphic-on-white-supremacy-did-she-break-the-law](https://www.chronicle.com/article/an-instructor-showed-a-graphic-on-white-supremacy-did-she-break-the-law)

> One of the law’s provisions states that professors must refrain from stating opinions unrelated to their discipline or course material. Adams said teaching about white supremacy is appropriate to the curriculum, because discussions of racism are relevant to her field. “The social-work profession explicitly names their values of social justice, of eradicating racism, poverty, and things like that. The 202 legislation does provide protection for teaching within your discipline and I naïvely thought I would be immune to a report because of that, but I wasn’t.”

> When Adams learned the dean was the primary complainant, she reached out to the university chapter of the American Association of University Professors (AAUP). The chapter helped her arrange a news conference, and has alleged that the university is violating its own policies in how it has conducted the investigation, as well as Adams’s due-process rights.

> Joseph Varga, a labor-studies professor at IU-Bloomington who helped Adams with her case as an AAUP member, called the entire investigation a blatant violation of due process. “In my opinion, they seem to be kind of making it up as they go along,” Varga said, adding that the social-work school has its own policy for handling complaints under the law, but the university doesn’t seem to be following it here.

> “I felt very tricked,” Adams said, adding that Benner [The Dean of the Social Work School] “used my slides as evidence to support her complaint, and I willingly offered those to her because I thought she was on my team.

* Texas A&M Faculty Council Says Professor’s Dismissal Violated Academic Freedom

[https://www.insidehighered.com/news/quick-takes/2025/11/13/texas-am-faculty-finds-dismissed-profs-academic-freedom-violated](https://www.insidehighered.com/news/quick-takes/2025/11/13/texas-am-faculty-finds-dismissed-profs-academic-freedom-violated)

> Texas A&M University faculty council determined in late September that Melissa McCoul, an instructor fired for teaching about gender identity in a children’s literature class, had her academic freedom violated and that former president Mark Welsh flouted proper termination processes when he fired her, The Texas Tribune reported Monday.

> McCoul was dismissed in September after a video went viral, showing a student confronting her in class and claiming the professor’s gender identity lesson was illegal. McCoul is actively appealing her termination. The documented justification for her dismissal was that McCoul’s course content and material did not match the description in the course catalog, but the faculty council said this was false.

> “The content of the course was the reason for the dismissal and not the stated reason: failure of academic responsibility,” the council wrote in its report. “Given the timeline of dismissal, the political pressure brought to bear, and statements by Regents that the course content was illegal, President Welsh’s assertion that the firing was for failure of academic responsibility appears pretextual.”

* NYTimes: Texas A&M Tightens Rules on Talking About Race and Gender in Classes

[https://www.nytimes.com/2025/11/13/us/texas-am-gender-race-ideology-rules-classroom.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/11/13/us/texas-am-gender-race-ideology-rules-classroom.html?smid=nytcore-ios-share&referringSource=articleShare)

> Texas A&M University System regents voted Thursday to limit how instructors may discuss matters like gender identity and race ideology in classrooms, tightening the rules in a conservative state where debates over academic freedom have flared for months.

> Regents, who met in College Station on Thursday afternoon, unanimously backed a revised proposal decreeing that no courses “will advocate race or gender ideology, or topics related to sexual orientation or gender identity” without a campus president’s approval of the course and related materials.

(Yes, president's approval for each of the  over 4100 faculty...)

> A related measure that regents approved said that faculty members could not “teach material that is inconsistent with the approved syllabus for the course.”

(And the cover story is:)

> “This does not diminish academic freedom,” Dr. Hallmark [vice chancellor for academic affairs] added. “It reinforces the balance between academic freedom and academic responsibility.”

(Also)

[https://www.chronicle.com/article/texas-a-m-system-sharply-restricts-how-faculty-can-teach-about-race-and-gender](https://www.chronicle.com/article/texas-a-m-system-sharply-restricts-how-faculty-can-teach-about-race-and-gender)

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/11/13/texas-am-requires-approval-courses-advocate-certain](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/11/13/texas-am-requires-approval-courses-advocate-certain)



* U.S. Congress considers sweeping ban on Chinese collaborations | Science | AAAS

[https://www.science.org/content/article/u-s-congress-considers-sweeping-ban-chinese-collaborations](https://www.science.org/content/article/u-s-congress-considers-sweeping-ban-chinese-collaborations)

> Scientists and research advocates in the United States are mobilizing to fight a bill that would essentially prohibit researchers with any ties to China and other countries deemed hostile from receiving federal funding. Nearly 800 academics signed a 29 October letter opposing the ban, part of a bill passed recently by the U.S. House of Representatives that sets spending priorities for the Department of Defense (DOD). A coalition of higher education and research advocacy groups has also urged Congress to strike the language as members reconcile the House version of the National Defense Authorization Act (NDAA) with what the Senate adopted last month. Final passage is expected by the end of the year.

> ... would deny federal funding to any U.S. scientist who collaborates with anyone “affiliated with a hostile foreign entity,” a category that includes four countries: China, Russia, Iran, and North Korea. The prohibited activities would include joint research, co-authorship on papers, and advising a foreign graduate student or postdoctoral fellow. The language is retroactive, meaning any interactions during the previous 5 years could make a scientist ineligible for future federal funding.

> The lack of a clear definition of “affiliation” in the SAFE Act could trigger arbitrary and biased enforcement of the funding ban, warns the Asian American Scholar Forum (AASF) in a similar letter. It cites the “chilling effect” of the China Initiative launched by President Donald Trump in 2018 to prevent economic espionage, which led to the targeting of hundreds of U.S. scientists of Chinese descent for allegedly failing to disclose their ties to China.

> Steven Kivelson of Stanford University, who organized the 29 October letter from scientists, says collaboration with Chinese colleagues is vital to his research in condensed matter physics—and a net gain for U.S. science.

> Kivelson acknowledges that he’s fighting an uphill battle to stave off tougher restrictions on scientific interactions with China. “The image of tilting with windmills does come to mind,” he says. “But this issue is so important to scientists, I feel that we need to do whatever we can.”

## Funding cuts

* Billions of State and Institutional Aid Dollars Go to High-Income Students

[https://www.insidehighered.com/news/quick-takes/2025/11/07/billions-aid-dollars-go-high-income-students](https://www.insidehighered.com/news/quick-takes/2025/11/07/billions-aid-dollars-go-high-income-students)

> A new report from the Century Foundation found that state and institutional grant aid too often flows to higher-income students who don’t need it, while low-income students continue to struggle with unmet need.

> The analysis, released Thursday, shows that more than half of students from the top income quartile, 56 percent, receive grants that surpass their financial need, compared to a mere 0.2 percent of students from the bottom income quartile. That means that top income quartile students were 280 times more likely to receive grants that exceeded their level of need than their lowest income peers. The share of white students that receive grants beyond their needs (19 percent) far exceeds the share of Black of Hispanic students who receive such grants (5 percent).

> “What people think about as a pillar of the financial aid system in higher education has become a windfall for wealthy students that leaves working families paying the bill for tuition increases,” Peter Granville, the report’s author and a fellow at the Century Foundation, said in a news release.

(Which may be true, but might also give cover to just gut everything...)

* Berkeley Law Dean Urges Supreme Court to Be ‘Guardrail of Our Democracy’

[https://www.insidehighered.com/news/business/financial-health/2025/11/12/berkeley-law-dean-urges-scotus-be-guardrail-democracy](https://www.insidehighered.com/news/business/financial-health/2025/11/12/berkeley-law-dean-urges-scotus-be-guardrail-democracy)

> “The one thing we all learned on the playground is if you give in to a bully, it only makes it worse in the long term,” Chemerinsky said Tuesday, adding—to applause—that “it’s so important that institutions of higher education stand together at this moment and stand together for our shared missions.”

> The speech comes after multiple prominent universities, including a few public ones, refused to sign Trump’s proposed “Compact for Academic Excellence in Higher Education,”...

> It also follows legal victories against the administration’s grant cancellations.

> Even before the latest cuts, Chemerinsky estimated the Trump administration had already slashed close to $1 billion in funding for faculty and researchers across the UC system, a figure that he said was much higher than DOGE’s tally. The UC system didn’t confirm or deny this estimate or provide a more recent estimate Tuesday, saying the system was closed for Veterans Day.

> “I think the termination of grants that we’ve seen, whether it’s to researchers and faculty or to universities, is clearly illegal,” Chemerinsky said. But when it comes to “nonrenewal of grants in the future and funding in the future,” he added, the “government has far more discretion, and there it’s going to be much harder to bring legal challenges.”

> Chemerinsky also said federal funding cuts are just one of four financial vulnerabilities the administration has identified in universities: “they’re very dependent” on federal money, tuition, philanthropy and foreign students. Using his own institution as an example, he said Berkeley Law has an L.L.M., or master of laws, degree program that’s exclusively for foreign students and represents $20 million in its annual budget.

> “By my count, 39 matters have come to the Supreme Court since [Inauguration Day] Jan. 20, challenging actions of the Trump administration,” he said. “All are instances where the lower courts ruled against the Trump administration, and in 36 of 39, the Supreme Court has ruled in favor of the Trump administration.”

> Chemerinsky noted that “one characteristic of every authoritarian—or would-be authoritarian—rule is the way they go after universities. What we’ve seen in the last nine and a half months is unprecedented in American history.”

### DOE

* Education Department Announces Key Priorities Through Grant Fund

[https://www.insidehighered.com/news/quick-takes/2025/11/11/ed-announces-key-priorities-through-grant-fund](https://www.insidehighered.com/news/quick-takes/2025/11/11/ed-announces-key-priorities-through-grant-fund)

> The grant, otherwise known as the Fund for the Improvement of Postsecondary Education (FIPSE), is overseen by the Office of Postsecondary Education and was created by Congress in 1972 to “improve postsecondary educational opportunities.”

> Each administration can set its own priorities within the criteria outlined in the statute to determine how it will allocate FIPSE awards with each new competition. The latest competition, announced Monday, includes four categories, one for each priority, with award amounts ranging from $7 million to $60 million.

(The priorities and amounts:)

> Artificial Intelligence ($50M): This priority will support grant applicants that use AI to “enhance teaching, learning and student success in education” and “broaden access to AI and expand computer science course offerings.”

> Civil Discourse ($60M): Awards in this category will support seminars, speaker series, conferences, debates and other learning opportunities that “foster respectful deliberation and debate on college and university campuses, where free expression has too long been eroded by censorship, harassment and even violent unrest.”

> Accreditation ($7M): This priority will support college and university efforts to “change their current accrediting agency” as well as “the development and launch of new accrediting agencies.”

> Short-Term Programs ($50M): Awards in this category go toward the development of new programs that “meet the eligibility requirements of the Workforce Pell Grants program” as well as expanding existing ones.

> Applications are due Dec. 3 and the department expects to distribute final awards by Dec. 31. But it’s unclear who will conduct the competition, as the majority of OPE staff were laid off in the department’s most recent reduction in force and one of the awards focuses on workforce Pell, a new grant program that has yet to undergo regulatory negotiations.

* ED’s ‘Special Projects’ Grants Spark Concern Over Congressional Intent

[https://www.insidehighered.com/news/government/2025/11/12/ed-grants-spark-concern-over-congressional-intent](https://www.insidehighered.com/news/government/2025/11/12/ed-grants-spark-concern-over-congressional-intent)

> Congress appropriated $171 million for the Fund for the Improvement of Postsecondary Education (FIPSE) to be used toward seven established programs, including Basic Needs, Veteran Student Success and Rural Postsecondary Education Development.

> But the Department of Education announced Monday that almost all the money will instead go toward a different “special projects” program to award grants for accreditation reform, artificial intelligence, civil discourse and short-term training programs.

> Since Congress chose to outline which programs should get which amounts of funding in a supplemental guidance document—instead of writing it into the bill—reprogramming FIPSE dollars is technically legal. But Clare McCann, a former policy adviser under President Biden and now the managing director of policy at American University’s Postsecondary Education and Economics Research Center, says redirecting the money could harm hundreds of institutions and thousands of students.

## Federal Agencies

### DOE/OCR

* DOE Proposal excludes public health degrees from "professional degree" definition

[https://aspph.org/department-of-education-proposal-excludes-public-health-degrees-from-professional-degree-definition/](https://aspph.org/department-of-education-proposal-excludes-public-health-degrees-from-professional-degree-definition/)

> The decision last week has significant implications for schools and programs of public health. Excluding the MPH and DrPH from the “professional degree” category could restrict students’ access to higher federal loan limits, making public health education less financially attainable and potentially weakening the future workforce pipeline. The proposal also overlooks decades of precedent recognizing these degrees as professional credentials essential to protecting community health and advancing health equity.


## Institutional assaults

### Cornell

* Cornell Settles With the Trump Administration

[https://www.insidehighered.com/news/government/politics-elections/2025/11/07/cornell-settles-trump-administration](https://www.insidehighered.com/news/government/politics-elections/2025/11/07/cornell-settles-trump-administration)

(Nothing new since last week)

> Some outside observers, however, excoriated the settlement as capitulation to authoritarianism.

> “The Trump administration’s corrupt extortion of higher ed institutions must end. Americans want an education system that serves the public good, not a dangerously narrow far right ideology that serves billionaires,” American Association of University Professors President Todd Wolfson said in a statement, which also urged colleges to fight intrusion by the federal government.

### Yale

* President Trump has made an example of Ivy League universities, attacking, cajoling and fining them in brisk succession. There’s a notable exception: Yale University.

[https://www.wsj.com/us-news/education/yale-trump-college-university-pressure-5316d26e?st=N9enDU](https://www.wsj.com/us-news/education/yale-trump-college-university-pressure-5316d26e?st=N9enDU)

> McInnis’s [Yale President] approach has divided the campus. Some see it as conciliatory, others as pragmatic.

> Andrew Lipka, Yale class of ’78, cited a quote, attributed to Winston Churchill: An appeaser is someone who feeds a crocodile hoping it will eat him last.

> “It’s our obligation to say something,” said Lipka, an ophthalmologist. “United we stand.”

> “We’re under no obligation to get involved,” he [Yale political science professor Steven Smith] said. “Self-preservation is a noble goal.”

### UNC

After faculty raise concerns, UNC-Chapel Hill Chancellor says university will not sign Trump's higher ed compact | WUNC

[https://www.wunc.org/education/2025-11-10/unc-chapel-hill-chancellor-will-not-sign-trump-higher-ed-compact](https://www.wunc.org/education/2025-11-10/unc-chapel-hill-chancellor-will-not-sign-trump-higher-ed-compact)

>  Chancellor Lee Roberts told faculty at a council meeting last week that he believes the compact is "clearly an infringement on academic freedom."

> "There are some parts of the compact that we are already doing and there are some parts of the compact that would be difficult or impossible for us to do," Roberts said at the meeting. "There's really no way that we can sign the compact as written and we don't plan to."

(Also)

[https://www.insidehighered.com/news/quick-takes/2025/11/11/unc-chapel-hill-wont-sign-compact](https://www.insidehighered.com/news/quick-takes/2025/11/11/unc-chapel-hill-wont-sign-compact)

### University of California

* The University of California system eliminated the systemwide Department of Equity, Diversity, and Inclusion, and replaced it with a new Office of Culture and Inclusive Excellence.

[https://www.chronicle.com/article/tracking-higher-eds-dismantling-of-dei](https://www.chronicle.com/article/tracking-higher-eds-dismantling-of-dei)

> UC officials did not clarify why the change was being made, but the university system has for months faced scrutiny from the Trump administration.



### Others

* Florida Board Says Syllabi, Reading Lists Must Be Posted Publicly for 5 Years

[https://www.insidehighered.com/news/faculty-issues/teaching/2025/11/10/fla-board-says-syllabi-reading-lists-must-be-posted](https://www.insidehighered.com/news/faculty-issues/teaching/2025/11/10/fla-board-says-syllabi-reading-lists-must-be-posted)

> Faculty at all Florida public universities must now make syllabi, as well as a list of required or recommended textbooks and instructional materials for each class, available online and searchable for students and the general public for five years.

> “Many of my colleagues and I believe that this is yet another overreach by political appointees to let Florida’s faculty know that they are being watched for potentially teaching any content that the far right finds problematic,” said John White, a professor of English education and literacy at the University of North Florida. He said officials at his institution told faculty members they must upload their syllabi for 2026 spring semester classes to Simple Syllabus, an online syllabi hosting platform, by December.

> “Florida’s universities are being run in an Orwellian manner, and working as a faculty member in Florida is increasingly like living in the world of Fahrenheit 451,” he said.

> According to the approved amendment, professors must post the syllabi “as early as is feasible” but no fewer than 45 days prior to the start of class. Public syllabi must include “course curriculum, required and recommended textbooks and instructional materials, goals and student expectations of the course, and how student performance will be measured and evaluated, including the grading scale.” Individualized courses like independent study and theses are exempt from the rule.

> Texas similarly requires all faculty at public institutions to make a version of their syllabus public. Indiana implemented a law in July requiring public institutions to publish all course syllabi on their websites, and this fall, the University System of Georgia introduced a new policy requiring faculty to post syllabi and curriculum vitae on institution websites.

> Some faculty members in those states have seen firsthand the risks of posting syllabi online; several professors have been harassed and doxed over course content in their online syllabi. Florida faculty are concerned the same thing could happen to them; several faculty members believe that the board passed the rule with the intent of siccing the general public on professors who teach about topics that conservative politicians don’t like.

* NYTimes: Democrat’s Win May Upend a Conservative Push in Virginia Universities
[https://www.nytimes.com/2025/11/10/us/politics/spanberger-democrat-virginia-higher-education.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/11/10/us/politics/spanberger-democrat-virginia-higher-education.html?smid=nytcore-ios-share&referringSource=articleShare)

> When she takes office as governor of Virginia in January, Abigail Spanberger will step into a partisan war over the political direction of one of the nation’s most respected public university systems.

> In Virginia, the battle over public higher education has pitted legislative Democrats against Republican-appointed boards, primarily at the University of Virginia and two other public schools, George Mason University and the Virginia Military Institute. Virginia’s governor appoints the board members at each campus who oversee the state’s public university system, and conservative board members and alumni have engineered efforts to oust leaders of the universities, largely over disputes about diversity initiatives.

> “Her influence is going to be really important to try to undo some of the things Youngkin did,” said Dr. Letiecq, president of the campus chapter of the American Association of University Professors. She said she hoped that Ms. Spanberger will set a new tone that includes “a pushback against all the incursions by the federal government.”

> The power of Mr. Youngkin’s conservative appointees also became clear last year at Virginia Military Institute, where 10 of them voted against renewing the contract of Maj. Gen. Cedric T. Wins, successfully ousting the school’s first Black leader. General Wins supported diversity efforts at the school, where a state report in 2021 found that an atmosphere of rampant racism and sexism had existed before he took over.

> The Trump administration also set its sights on George Mason, claiming that its first Black president, Gregory Washington, unlawfully favored underserved minority candidates in hiring and promotion, and demanded that he issue a public apology. Dr. Washington has refused.

> Though there has been speculation this year that the George Mason board would move to oust Dr. Washington, a committee controlled by legislative Democrats has blocked confirmation of more than 20 of Mr. Youngkin’s nominees to university boards, including several at George Mason, leaving the school’s board without enough members to achieve a quorum.

## Blowback

* Insiders warn how dismantling federal agencies could put science at risk

[https://www.nature.com/articles/d41586-025-03575-7](https://www.nature.com/articles/d41586-025-03575-7)

> For 30 years, the US Environmental Protection Agency (EPA) has conducted controlled air-pollution studies at a state-of-the-art facility at the University of North Carolina at Chapel Hill. The facility is equipped to test numerous airborne pollutants, including ozone, diesel, wildfire smoke and chlorine. Data collected in its chambers have been pivotal to establishing stricter air-quality standards for deadly pollutants, and have been instrumental in protecting the health of people in the United States.

> However, in February, shortly after US President Donald Trump took office, the EPA — which is charged with protecting the nation’s environment and its people’s health — notified the university that it would not be renewing its lease. By May, research had ceased. “There are no other places with the capability of doing these studies on the wide range of pollutants that the Chapel Hill facility does,” says Robert Devlin, a former EPA researcher who worked at the facility until recently. In August, after almost 40 years at the agency, Devlin retired when his appointment was not renewed.

> In addition to cuts at the EPA, the administration has already cut or proposed cutting more than US$50 billion in research funding across the nation’s science agencies, with research on climate, ecosystems, renewable energy and health disparities particularly affected. Although the administration characterizes the cuts and reorganizations of federal research programmes as realigning them with the president’s priorities, critics say the aim is to remove environmental and health protections and other regulatory safeguards. The cuts to EPA staffing are “the biggest blow that agency has ever had”, says Christopher Sellers at Stony Brook University in New York, who interviews EPA scientists for the Environmental Data and Governance Initiative, a watchdog group for US federal environmental data.

> In addition to cuts at the EPA, the administration has already cut or proposed cutting more than US$50 billion in research funding across the nation’s science agencies, with research on climate, ecosystems, renewable energy and health disparities particularly affected. Although the administration characterizes the cuts and reorganizations of federal research programmes as realigning them with the president’s priorities, critics say the aim is to remove environmental and health protections and other regulatory safeguards. The cuts to EPA staffing are “the biggest blow that agency has ever had”, says Christopher Sellers at Stony Brook University in New York, who interviews EPA scientists for the Environmental Data and Governance Initiative, a watchdog group for US federal environmental data.

> “It’s not just EPA. Science is being destroyed across many agencies,” says a senior ORD official who was put on administrative leave in June. ...

> Nature spoke to 19 current and former federal agency scientists, covering the EPA, the CDC, NASA, the National Oceanic and Atmospheric Administration (NOAA), the US Geological Survey (USGS) and the National Institutes of Health (NIH), to find out what agency-directed research has been lost and what that will mean for the United States. Many of those currently employed by these agencies requested anonymity for fear of retribution. Nature contacted all six agencies for comment, but the CDC, NOAA, NIH and USGS did not respond.


## Higher Education as a Public Good

* Colleges Expand Basic Needs Support Following SNAP Freeze

[https://www.insidehighered.com/news/student-success/health-wellness/2025/11/12/colleges-expand-basic-needs-support-following-snap](https://www.insidehighered.com/news/student-success/health-wellness/2025/11/12/colleges-expand-basic-needs-support-following-snap)

> Nearly three in five college students experience some form of basic needs insecurity, and two in five experience food insecurity, according to national surveys. In addition, approximately 3.3 million college students are eligible for federal food assistance, according to 2020 data, though a large share do not utilize SNAP due to lack of awareness.

> CUNY chancellor Félix Matos Rodríguez announced the university system would allocate additional funding to all campuses “so they can stock extra supplies in their on-site food pantries or provide food assistance in other forms,” he wrote in a Nov. 7 email to students. CUNY students can visit any campus pantry in the system, regardless of their home enrollment, allowing them to access those with the most convenient hours and locations.

> The chancellor also urged students to apply for SNAP benefits for future assistance; students at the Bronx campuses (Lehman, Hostos and Bronx Community College) can also participate in a pilot program for community-based resources.

## AI misdeeds

* The Post-Plagiarism University --- Professors have tried to fit AI into old categories of academic misconduct. Students aren’t buying it.

[https://www.chronicle.com/article/the-post-plagiarism-university](https://www.chronicle.com/article/the-post-plagiarism-university)

> Given the centrality of the prohibition against plagiarism to academic self-conception, it has proved irresistibly tempting to define copying from artificial intelligence as a form of plagiarism. The University of California at Berkeley Law School was one of the first to do this, telling students that AI “never may be employed for a use that would be plagiarism if generative AI were a human or organizational author.” This has been a common approach at many institutions, including mine.

> When my staff and I at New York University, where I am vice provost for AI and technology in education, began reviewing the university’s existing academic-integrity policies in light of AI, I was struck by the simplicity and effectiveness of our definition of cheating: “Deceiving a faculty member or other individual who assesses student performance into believing that one’s mastery of a subject or discipline is greater than it is.”

> Simple, to the point: a litmus test that cuts through a whole thicket of what-ifs. If a student taking a closed-book exam writes answers on their hand or uses networked glasses with a camera in them, it’s all the same crime.

> This distinction — treating plagiarism as a special and worse form of cheating — is the source of much of the gap between faculty and students. Put simply, many students don’t regard using AI as plagiarism in the uncomplicated way many faculty do, in part because copying text from AI is not in fact copying from the work of a particular person.

> Our fundamental problem is not disobedience. Our problem is that students have to collectively approve of the strictures we are asking them to abide by. When we try to preserve our existing practices without taking AI’s strange new capabilities into account, we take too little notice of our own students’ experiences and expectations. The relationship between faculty and students is like the relationship between a river and its water: In the short term, the river tells the water where to go, but in the long term, the water tells the river where to go.

## And just because it is fun

(Err *isn't* fun)

* UC San Diego Sees Students’ Math Skills Plummet

[https://www.insidehighered.com/news/quick-takes/2025/11/12/uc-san-diego-sees-students-math-skills-plummet](https://www.insidehighered.com/news/quick-takes/2025/11/12/uc-san-diego-sees-students-math-skills-plummet)

> he number of first-year students at the University of California, San Diego, whose math skills fall below a middle school level has increased nearly 30-fold over the past five years, according to a new report from the university’s Senate–Administration Working Group on Admissions. In the 2025 fall cohort, one in eight students placed into math below a middle school level, despite having a solid math GPA.

> “This deterioration coincided with the COVID-19 pandemic and its effects on education, the elimination of standardized testing, grade inflation, and the expansion of admissions from under-resourced high schools,” the report states. “The combination of these factors has produced an incoming class increasingly unprepared for the quantitative and analytical rigor expected at UC San Diego.”

> High school grade inflation is not helping the university evaluate students’ math skills, the report states. In 2024, the average high school math GPA for students in Math 2, the middle school–level remedial math course, was 3.65—an A-minus.

(Also)

[https://www.chronicle.com/article/people-are-freaking-out-over-the-steep-decline-in-students-academic-preparation-at-uc-san-diego](https://www.chronicle.com/article/people-are-freaking-out-over-the-steep-decline-in-students-academic-preparation-at-uc-san-diego)



----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
