# Oct 17

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

Thanks to MP and KB for sharing links this week.

## Protests

* No Kings

[https://www.nokings.org/](https://www.nokings.org/)

> ANCHOR EVENT: NYC SAYS NO KINGS! 11AM Father Duffy Square Broadway & West 47th Street New York, NY 10036

[https://www.mobilize.us/nokings/event/838831/](https://www.mobilize.us/nokings/event/838831/)

> On October 18, millions of us are rising again to show the world: America has no kings, and the power belongs to the people.

(On October 18th the PSC will convene at Duarte Square, 6th Avenue & Canal Street joining other NYC unions)



* Faculty Plan National Day of Action to Protest Compact

[https://www.insidehighered.com/news/quick-takes/2025/10/16/faculty-plan-national-day-action-protest-compact](https://www.insidehighered.com/news/quick-takes/2025/10/16/faculty-plan-national-day-action-protest-compact)

> aculty and students at the nine universities first offered the Trump administration’s compact for preferential treatment will rally against it Friday in a national day of action.

> All nine universities—including the University of Arizona, Brown University, Dartmouth College, the Massachusetts Institute of Technology, the University of Pennsylvania, the University of Southern California, the University of Texas, UVA and Vanderbilt University—will participate in the day of action, though MIT officials have already said publicly they will not sign the agreement. (Brown rejected the agreement Wednesday.)

## Op eds

* Cuomo’s controversial CUNY record resurfaces as affordability concerns dominate mayor’s race

[https://www.politico.com/news/2025/10/14/cuomos-controversial-cuny-record-resurfaces-as-affordability-concerns-dominate-mayors-race-00602373](https://www.politico.com/news/2025/10/14/cuomos-controversial-cuny-record-resurfaces-as-affordability-concerns-dominate-mayors-race-00602373)

(Thanks MP for sharing!)

> “At this moment in our country’s history where communities of color are so much under attack and immigrant communities are so much under attack, CUNY is absolutely more important than ever,” said Barbara Bowen, former president of the Professional Staff Congress, CUNY’s faculty and staff union. “I am very concerned that having a mayor with that history of lack of support and active undermining of CUNY would be especially dangerous at this political moment.”

## Academic freedom

* Trump Opens Up Compact to All of Higher Ed. Now What?

[https://www.insidehighered.com/news/government/2025/10/15/trump-opens-compact-all-higher-ed-now-what](https://www.insidehighered.com/news/government/2025/10/15/trump-opens-compact-all-higher-ed-now-what)

> On Sunday, President Trump told his 10 million followers on Truth Social that, “tragically,” higher education in this country has lost its way, and he touted his administration’s efforts to fix it.

> Trump’s open invitation to colleges to sign on to the document did not come as a surprise. Several experts predicted such a development, and a White House official told Inside Higher Ed last week that other institutions had already reached out. However, the timing of Trump’s post raised some eyebrows.

> “The administration is reading the writing on the wall that they wouldn’t be able to run the table on the nine and that there would be substantial pushback,” said Ted Mitchell, president of the American Council on Education. “And they didn’t want to own that, so they looked for more buyers.”

> But who signs will affect how the document is viewed and the message it sends.

> “Depending on the names, it might wind up looking more like Walgreens than some high-end boutique,” Hess said.

* The Compact Calls for a Unified ‘F You’

[https://www.insidehighered.com/opinion/columns/editors-note/2025/10/16/compact-calls-unified-f-you](https://www.insidehighered.com/opinion/columns/editors-note/2025/10/16/compact-calls-unified-f-you)

> Boards of trustees—not presidents—will make the ultimate decision whether to sign the deal. At the IHE event, one president at a public institution in a “candy apple–red state” said a trustee urged them to sign the compact to gain a competitive advantage on federal research funds. That decision might make sense from a business point of view, but it doesn’t for someone concerned about institutional autonomy. Two state lawmakers in Iowa asked the Iowa Board of Regents to join the compact “as soon as possible.” Several leaders said if their board of trustees or state leadership made them sign it, they would quit. But individuals quitting in protest won’t stop boards from signing the deal—they’ll just hire new leaders who will comply. Disruption at the leadership level harms the entire institution. Meanwhile, thousands of faculty and staff without F You accounts will be stuck at institutions that have agreed to the terms.

> It’s very likely that some colleges will sign the compact, and that will erode the independence of the entire sector. Higher ed should look to media companies as a model of collective resistance.

> If ever there was a time for community colleges, independent nonprofits, public R-1s and the Ivy League to speak with one voice, it’s now. Trump’s compact compromises the foundations of higher education—free inquiry, academic freedom and institutional autonomy. The sector’s strength will be in a collective response, not individual presidents resigning in protest. Higher ed should pool its F You accounts and refuse the deal collectively.

* NYTimes: Trump’s ‘Compact’ With Universities Is Badly Needed

[https://www.nytimes.com/2025/10/10/opinion/trump-compact-universities-rowan.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/10/10/opinion/trump-compact-universities-rowan.html?smid=nytcore-ios-share&referringSource=articleShare)

(Gazillionaires just think different. For example, no one else is calling the compact this:)

> By agreeing to a few common-sense policies laid out in the compact.

* Universities Must Defend Their Independence by Rejecting Trump's "Compact" | Cato at Liberty Blog

[https://www.cato.org/blog/universities-must-defend-their-independence](https://www.cato.org/blog/universities-must-defend-their-independence)

(Lost the libertarians...)

> My colleague Neal McCluskey has already outlined the basics of the scheme, and I emphatically agree with his conclusion that universities that agree to it would be “selling their souls.”

* NYTimes: Universities Are Standing Up to Trump

[https://www.nytimes.com/2025/10/17/us/universities-are-standing-up-to-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/10/17/us/universities-are-standing-up-to-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> On campuses and in Washington, professors and policymakers alike are weighing whether Mr. Trump, who has reveled in his campaign to upend higher education, has overreached.

> Brown’s decision, in particular, is a case study of how the White House may have misjudged its own strength and academia’s nerve, especially once one of Mr. Trump’s top aides said that the nine schools initially chosen to consider the proposal were “good actors,” or could be.

> “The compact itself just so egregiously and blatantly violated our ability to function as the institution that we are right now that it is very easy for people to get fired up about it,” said Raya Gupta, a Brown freshman who helped organize opposition to the proposal on the campus in Providence, R.I.

> The demands also reach farther, with conditions that include accepting “that academic freedom is not absolute” and pledging to potentially shut down “institutional units that purposefully punish, belittle and even spark violence against conservative ideas.”

> “There are many colleagues who just think there is no way any president, with the possible exception of red state, public universities, could sign this,” said Michael P. Steinberg, the president of Brown’s chapter of the American Association of University Professors.

> It is not clear how the Trump administration will proceed if universities continue to reject the proposal. The White House did not respond to a request for comment for this article, though a spokeswoman, Liz Huston, warned after Penn’s announcement on Thursday that “any higher education institution unwilling to assume accountability and confront these overdue and necessary reforms will find itself without future government and taxpayers support.”

* UNC Campuses Split on Whether Syllabi Are Public Documents

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/10/17/unc-campuses-split-whether-syllabi-are-public](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/10/17/unc-campuses-split-whether-syllabi-are-public)

> After the University of North Carolina at Chapel Hill refused to proffer faculty course materials in response to an open-records request, UNC Greensboro officials made the opposite decision.

(CUNY syllabi have been FOILed)

> In July, officials at the University of North Carolina at Chapel Hill determined that the documents are not automatically subject to such requests after the Oversight Project, founded by the conservative think tank the Heritage Foundation, requested that the university hand over any course materials from more than 70 classes that contained one of 30 words or phrases, including “gender identity,” “intersectionality,” “queer” and “sexuality.” Officials ultimately denied the request, writing, “There are no existing or responsive University records subject to disclosure under the North Carolina Public Records Act. Course materials, including but not limited to exams, lectures, assignments and syllabi, are the intellectual property of the preparer.”

> The requested materials are protected by copyright policies, a UNC Chapel Hill spokesperson told Inside Higher Ed. “The university has a longstanding practice of recognizing faculty’s intellectual property rights in course materials and does not reproduce these materials in response to public records requests without first asking for faculty consent,” they wrote in an email.

> “It’s probably a matter of degree,” Stevens said. “Something that you post online for your class to read, it’s pretty hard to say those are not subject to [public records requests]. But on the other hand, the materials that you use to prepare to teach your class, but which are never published to anybody, are certainly, in my view, copyrightable and proprietary.”

> The opposing interpretations of the law from two universities in the same public system have left faculty confused and worried about their safety as right-wing groups rifle through course materials for any terminology they don’t like, usually related to gender identity, sexuality or race. Faculty members at Texas A&M University, the University of Houston and George Mason University, among others, have been targeted and sometimes threatened on social media for their instruction and teaching materials. Bolton said he knows of several UNC Greensboro faculty members who have been doxed.

(CUNY is not immune)

* Our Politics Differ, But We Agree: Trump’s ‘Compact’ Violates Academic Freedom

[https://www.chronicle.com/article/our-politics-differ-but-we-agree-trumps-compact-violates-academic-freedom](https://www.chronicle.com/article/our-politics-differ-but-we-agree-trumps-compact-violates-academic-freedom)

> The compact’s demands that universities and colleges eschew foreign students with “anti-American values” and that they impose a politically determined diversity within departments and other institutional units are incompatible with the self-determination that colleges and universities must enjoy if they are to pursue their mission as truth-seeking institutions. So also is the compact’s demand that universities and colleges select their students only on the basis of “objective” and “standardized” criteria. Colleges may of course voluntarily elect exclusively to deploy objective criteria (such as standardized-test scores and high-school or college grade-point averages), but these standards should not be imposed on institutions which, operating within the law, wish to include consideration of nonquantifiable criteria in selecting students.

> As recognized for over a century, faculty should be able to engage as individual citizens in extramural speech. Faculty should exercise these rights responsibly and professionally, but when they fail to do so, it is not the role of the government or the university to sanction them. Colleges that censor their faculty will quickly undermine the vibrancy and initiative so vital for teaching and research.

> The power to punish extramural speech has been abused against both conservative and liberal speakers in the past. The requirement of the compact that universities and colleges censor students and faculty who voice support for “entities designated by the U.S. government as terrorist organization” imposes overly intrusive regulation of constitutionally protected speech.

## Freedom of expression

* Pepperdine Closes Exhibit Featuring “Overtly Political” Art

[https://www.insidehighered.com/news/quick-takes/2025/10/13/pepperdine-closes-exhibit-featuring-overtly-political-art](https://www.insidehighered.com/news/quick-takes/2025/10/13/pepperdine-closes-exhibit-featuring-overtly-political-art)

> Last month Pepperdine University in Malibu, Calif., opened an art exhibit titled “Hold My Hand In Yours,” which was scheduled to run for six months in the on-campus Frederick R. Weisman Museum of Art. But On Oct. 6, the university closed the exhibit after artists learned their work had been removed or altered for being “overtly political.”

> Last week, one of the artists in the show learned her video had been turned off at the university’s request, and a sculpture had been modified to hide text that said “Save the Children” and “Abolish ICE,” Hyperallergic reported. The creators requested their pieces be removed from the museum, and several other contributors followed suit in solidarity with the affected artists and in opposition to the university.

* Viewpoint Diversity Is a MAGA Plot

[https://www.chronicle.com/article/viewpoint-diversity-is-a-maga-plot](https://www.chronicle.com/article/viewpoint-diversity-is-a-maga-plot)

> Intellectual diversity and its analogues have been on the right’s agenda for 60 years. As Bradford Vivian observes in his book Campus Misinformation, “viewpoint diversity performs a deft linguistic trick,” modifying an old right-wing playbook of “unscientific partisan polemics” into a seemingly new and more palatable form. As scholars have analyzed, this ideology is propped up by pseudoscience (Vivian), error-ridden studies on supposed “liberal bias” (Charlie Tyson and Naomi Oreskes), discrimination claims that cannot “withstand serious scrutiny” (Sean Kammer), and “manufactured backlash” from a coordinated network of far-right think tanks (Isaac Kamola). The fierce attacks on the humanities and social sciences have an extensive history that were never rooted in a dispassionate critique of the dangers of groupthink. Demands for viewpoint diversity are simply the form those attacks take today.

* NYTimes: Dispute Over Indiana College Newspaper Draws Censorship Accusations

[https://www.nytimes.com/2025/10/17/business/media/indiana-university-daily-student-newspaper.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/10/17/business/media/indiana-university-daily-student-newspaper.html?smid=nytcore-ios-share&referringSource=articleShare)

> The administration at Indiana University Bloomington fired the adviser to the paper and barred the publication from putting out a print edition.

> The Foundation for Individual Rights and Expression, a free speech advocacy group, said in a social media post on Wednesday that the firing of Mr. Rodenbush showed “disregard for student journalists.” The foundation had previously placed the university in the bottom three in a ranking of free speech on 257 college campuses based on student surveys.

(Also)

[https://www.insidehighered.com/news/students/free-speech/2025/10/16/indiana-censors-newspaper-fires-adviser](https://www.insidehighered.com/news/students/free-speech/2025/10/16/indiana-censors-newspaper-fires-adviser)

> The decision is the latest flare-up between student journalists and institutions. Earlier this year, Purdue University ended its partnership with the student paper, citing “institutional neutrality.” The move also echoes Texas A&M University’s unilateral decision in 2022 to end its student newspaper’s print edition.

> The IDS editors first brought attention to the firing of Director of Student Media Jim Rodenbush in a Tuesday op-ed. They accused IU of ousting Rodenbush after he refused to follow directions from administrators to censor a homecoming edition of the newspaper. Administrators reportedly told Rodenbush the newspaper was only to contain information about homecoming and “no traditional front page news coverage.” But when he resisted, and editors at the Indiana Daily Student pressed Media School administrators for clarity, Rodenbush was fired.

* Indiana Daily Student Homecoming eEdition - Thursday, Oct. 16, 2025 by Indiana Daily Student - idsnews - Issuu

[https://issuu.com/idsnews/docs/indiana_daily_student_homecoming_eedition_-_thursd](https://issuu.com/idsnews/docs/indiana_daily_student_homecoming_eedition_-_thursd)


### Anti-woke/anti-DEI is simply racism

* Under Anti-DEI Pressure, Ohio State Limits Conference Funds

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/10/15/under-anti-dei-pressure-ohio-state-limits](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/10/15/under-anti-dei-pressure-ohio-state-limits)

> The Trump administration’s investigation into allegations of racial discrimination at Ohio State University has prompted the university to limit its support for faculty and student participation in academic conferences affiliated with affinity groups.

> Earlier this month, the university told numerous faculty and students who were planning to attend an upcoming conference hosted by the Society for Advancement of Chicanos and Native Americans in Science, which happens to be in Columbus this year, that they could not use university funds to attend,

> The university also refunded the registrations—without explanation—of a group of graduate students who were planning to attend the 2025 National Society of Black Physicists and National Society of Hispanic Physicists Joint Conference next month in San Jose, according to The Columbus Dispatch.

> In March, OSU was among more than 50 colleges and universities that OCR accused of violating Title VI of the Civil Rights Act and flouting guidance from the Education Department deeming all race-conscious programs and policies unlawful. The majority of those federal investigations—including the one at OSU—revolved around institutional involvement with the PhD Project, a nonprofit that encourages people from underrepresented backgrounds to pursue doctoral degrees in business. The department said the program “limits eligibility based on the race of participants.”

> In a Sept. 23 letter to OSU president Ted Carter Jr., OCR described the PhD Project as “a blatantly discriminatory program designed to benefit certain favored students based on their race or national origin to the clear detriment of other students who did not have access to the program because of their race or national origin” and concluded the OSU’s participation violated Title VI.

> However, none of the organizations hosting the conferences in question exclude anyone from participating on the basis of race, ethnicity or any other characteristic, according to statements on their official websites.

## Funding cuts

* Survey: Americans Overwhelmingly Oppose Trump’s Higher Ed Cuts

[https://www.insidehighered.com/news/government/science-research-policy/2025/10/16/survey-americans-overwhelmingly-oppose-trump](https://www.insidehighered.com/news/government/science-research-policy/2025/10/16/survey-americans-overwhelmingly-oppose-trump)

> Amajority of Americans oppose the Trump administration’s sweeping cuts to higher ed funding, according to summer poll results released Wednesday. And several of the president’s other moves—including targeting diversity, equity and inclusion programs—aren’t popular, either.

> The researchers—from Northeastern University, Rutgers University at New Brunswick, the University of Rochester and Harvard—asked survey takers whether they supported the administration’s freezing of “billions of dollars in federal research grants to universities.” The results showed that 54 percent of Americans disapproved of the funding freeze, 34 percent of them strongly. Only 22 percent approved or strongly approved.

> The White House was the institution in which the highest share of Americans—over a third—expressed no trust. Another quarter said they have “not too much” trust in it.

* CSU Campuses Reel From Blow to HSI Funding

[https://www.insidehighered.com/news/institutions/minority-serving-institutions/2025/10/14/csu-campuses-reel-blow-hsi-funding](https://www.insidehighered.com/news/institutions/minority-serving-institutions/2025/10/14/csu-campuses-reel-blow-hsi-funding)

(Thanks MB for sharing this)

> Similar stories are playing out across the California State University system. Hispanic students account for almost half of the system’s more than 450,000 students. Out of the CSU’s 22 campuses, 21 are Hispanic-serving institutions, meaning they enroll at least 25 percent Hispanic students and at least half low-income students. In addition, 11 are AANAPISIs, which have the same low-income student threshold and enroll at least 10 percent Asian and Pacific Islander students. CSU officials estimate ED’s axing of the grant programs leaves the system $43 million short on funds it expected for the 2025–26 fiscal year.

> “This action will have an immediate impact and irreparable harm to our entire community,” García [CSU chancellor] said in a statement. “Without this funding, students will lose the critical support they need to succeed in the classroom, complete their degrees on time, and achieve social mobility for themselves and their families.”

(We will need to see how CUNY is impacted)

* Community colleges are losing millions in funding under Trump

[https://www.washingtonpost.com/nation/2025/10/14/trump-cuts-community-college-funding/](https://www.washingtonpost.com/nation/2025/10/14/trump-cuts-community-college-funding/)

> But for now, the Trump administration’s policy on cutting discretionary grants to programs that serve diverse student populations is disrupting the very type of college education that the administration says is critical for the nation’s workforce.

> Cuts to higher education this year have been spread across a variety of federal programs, but policy experts say community colleges can least afford to absorb the losses. Schools such as Pima Community College in Arizona, Green River College in Washington and Chemeketa Community College in Oregon have lost millions in discretionary grants that they say cannot be easily replaced.

> “This is an assault on our students, it’s an assault on our democracy because those students will not have the same opportunities for success as they would have just a couple of years ago,” said Mike Gavin, founder of Education for All, a grassroots group of community college administrators.

> Take the move to end $350 million in discretionary grant funding that Congress allocated for minority-serving institutions — colleges that educate a disproportionate number of students from underrepresented racial and ethnic groups. Roughly 40 percent of grant recipients are community colleges, according to the most recent data from the Education Department.

> Within days of the announcement, the Trump administration said it would reroute the money to charter schools, civics programs, tribal colleges and historically Black colleges and universities. Schools learned of the abrupt funding cut weeks before the end of the fiscal year, leaving them scrambling to keep services going.

### NIH

* Six surgeons general: It’s our duty to warn the nation about RFK Jr.

[https://www.washingtonpost.com/opinions/2025/10/07/surgeons-general-rfk-jr-robert-kennedy/](https://www.washingtonpost.com/opinions/2025/10/07/surgeons-general-rfk-jr-robert-kennedy/)

> Yet Kennedy continues to ignore science and the public’s wishes. Most recently, HHS proposed new warning labels on products containing acetaminophen (Tylenol), citing a supposed link between prenatal use and autism. This move has been widely condemned by the scientific and medical communities, who have pointed out that the available research is inconclusive and insufficient to justify such a warning. In an extraordinary and unprecedented response, the American Academy of Pediatrics, the American College of Obstetricians and Gynecologists and other leading health organizations issued public guidance urging physicians and patients to disregard HHS’s recommendation. Instead of helping pregnant women make informed decisions during a critical period in their lives, Kennedy’s decisions risk causing confusion, fear and harm.

> It’s worth reminding ourselves what Kennedy puts at risk. The FDA approves lifesaving drugs and holds pharmaceutical companies to high standards of safety and effectiveness. NIH pursues and funds cutting-edge research. CDC leads in emergencies from pandemics to opioids to natural disasters. Agencies at HHS spearhead efforts to address issues regarding mental health, substance-use disorders, primary care shortages and health insurance coverage for millions of seniors, disabled individuals, and low-income Americans. Mismanaging HHS endangers America’s health, undermines national security and damages our economic resilience and international credibility.

> Secretary Kennedy is entitled to his views. But he is not entitled to put people’s health at risk. He has rejected science, misled the public and compromised the health of Americans.

* How to navigate the impact of manipulation and removal of federal data: Expert advice, reporting tips and resources

[https://journalistsresource.org/home/how-to-navigate-the-impact-of-manipulation-and-removal-of-federal-data/](https://journalistsresource.org/home/how-to-navigate-the-impact-of-manipulation-and-removal-of-federal-data/)

(Thanks KB!)

> Federal datasets have been manipulated and removed since the beginning of the Trump administration and continue to be under threat. Shortly after President Trump took office for the second time, his administration took down several health websites that included Diversity, Equity and Inclusion initiatives and data, although some have since been restored. Researchers have also found undocumented changes to some federal health datasets. And there are many more examples.


> This loss has several critical consequences, affecting national infrastructure, accountability, data quality and public trust, explained Plyer and co-panelists Denice Ross, the U.S. chief data scientist and the deputy U.S. chief technology officer during the Biden Administration, and Erica Groshen, senior economic advisor at the Cornell University School of Industrial and Labor Relations, and the 14th commissioner of the Bureau of Labor Statistics from 2013 to 2017.

> “In the information age, our federal statistical system is as important an infrastructure as roads and bridges,” Groshen said.

> Disaster response leaders use the Census Bureau’s American Community Survey data to determine how many people are likely affected by a disaster and then measure the recovery in the years afterward,

> Companies like Zillow use the Department of Education’s Civil Rights Data Collection to help homebuyers determine which schools have the best disability resources.

> And data from the Environmental Protection Agency’s Safe Drinking Water Information System helps states deploy federal funds to improve drinking water quality where it’s needed most.

> Without performance criteria established and applied, it is unclear how decisions about the performance of statistical agencies and units would be made objectively and transparently.

> “This administration has fired all of the inspectors general and has now announced that they are eliminating the Council of Inspectors General across the government, which establishes performance criteria and coordinates the work of the inspector generals,” Groshen said.

> Eliminating the Council of Inspectors General eliminates the people who were enforcing a powerful statistical policy regulation in the federal government, “and is a threat to our statistical system as well,” Groshen said.

(Ending with large list of resources)


## Federal Agencies

### DOE/OCR

* Trump Fires More Education Dept. Employees

[https://www.insidehighered.com/news/government/student-aid-policy/2025/10/10/trump-fires-more-education-dept-employees](https://www.insidehighered.com/news/government/student-aid-policy/2025/10/10/trump-fires-more-education-dept-employees)

> A department spokesperson then confirmed in an email to Inside Higher Ed that “ED employees will be impacted by the RIF.” The spokesperson did not clarify how many employees will be affected or in which offices. Other sources say no one who works in the Office of Federal Student Aid will be laid off.

* Trump’s Layoffs Gut Office of Postsecondary Ed

[https://www.insidehighered.com/news/government/student-aid-policy/2025/10/15/trumps-latest-layoffs-gut-office-postsecondary-ed](https://www.insidehighered.com/news/government/student-aid-policy/2025/10/15/trumps-latest-layoffs-gut-office-postsecondary-ed)

> Education Secretary Linda McMahon has essentially gutted the postsecondary student services division of her department, leaving TRIO grant recipients and leaders of other college preparation programs with no one to turn to.

> The consequence, college-access advocates say, is that institutions might not be able to offer the same level of support to thousands of low-income and first-generation prospective students.

> The layoffs are another blow to the federal TRIO programs, which help underrepresented and low-income students get to and through college. President Trump unsuccessfully proposed defunding the programs earlier this year, and the administration has canceled dozens of TRIO grants. Now, those that did get funding likely will have a difficult time connecting with the department for guidance.

> At the beginning of the year, OPE included five offices but now is down to the Office of Policy, Planning and Innovation, which includes oversight of accreditation, and the group working to update new policies and regulations.

> Cottrell said the layoffs at OPE will leave grantees who relied on these officers for guidance without a clear point of contact at the department. Further, he said there won’t be nonpartisan staffers to oversee how taxpayer dollars are spent.

* White House Guts Education Department With More Layoffs

[https://www.nytimes.com/2025/10/14/us/politics/trump-education-department-federal-layoffs.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/10/14/us/politics/trump-education-department-federal-layoffs.html?smid=nytcore-ios-share&referringSource=articleShare)

> The department’s Office of Special Education Programs was decimated by the cuts, which the Trump administration issued on Friday in its latest reduction of the federal work force. The special education office has been the principal government arm overseeing billions of dollars that support about 10 percent of the nation’s school-aged children, but will have fewer than a half-dozen employees, a reduction of about 95 percent since the start of the year.

> The Office for Civil Rights in the department was also slashed. After starting the year with 12 regional sites, the civil rights office was cut in half in March and may go down to a site or two when the layoffs take effect in 60 days, according to data compiled by the union representing education workers. Over 22,600 discrimination complaints in schools were filed with the department last year, more than double the number from five years earlier.

## State actions

* We have an obligation to do more with less, and by showing true leadership and fiscal discipline, we can further support the Governor’s vision to meet the needs of the people we serve.

[https://www.budget.ny.gov/guide/brm/fy27-call-letter.pdf](https://www.budget.ny.gov/guide/brm/fy27-call-letter.pdf)

(Thanks MB for sharing the State Budget Director's call letter)

> As we enter the upcoming budget cycle, we face new challenges as we continue to fulfill Governor Hochul’s promise to make New York more affordable and safer. Unfortunately, federal assistance crucial for programs supporting New York’s most vulnerable have been curtailed, foisting new costs upon New York State. Due to imprudent federal policies, economic headwinds remain as labor markets are cooling and inflation remains elevated. Affordability continues to be a key concern for New Yorkers in every region of our state, creating pressures on the cost of food, healthcare, housing and energy. While revenues remain strong over the first half of the fiscal year, the forecasted growth will not be adequate to address structural gaps exacerbated by H.R. 1.

> Responding to federal funding cuts, Governor Hochul has already charged State agencies to exercise fiscal discipline by preparing comprehensive strategies to limit potential long-term damage to vital programs. Moving forward, agency budget requests for State Fiscal Year (SFY) 2027 should not exceed the total SFY 2026 Enacted Budget agency funding levels, excluding one-time investments.

(CUNY is entering that time of year where a budget request is formulated)

## Institutional assaults

* Trump Welcomes ‘Any Institution’ to Sign Compact Outlining His Priorities

[https://www.chronicle.com/blogs/the-trump-agenda/trump-welcomes-any-institution-to-sign-onto-compact-outlining-his-priorities](https://www.chronicle.com/blogs/the-trump-agenda/trump-welcomes-any-institution-to-sign-onto-compact-outlining-his-priorities)

> A source at the Department of Education confirmed Tuesday that a Truth Social post from President Trump was intended to be an invitation to higher ed. “We welcome any institution that wants to adopt these principles to sign the compact,” wrote the source, who declined to go on the record.

> Trump’s post said: “Those Institutions that want to quickly return to the pursuit of Truth and Achievement, they are invited to enter into a forward looking Agreement with the Federal Government to help bring about the Golden Age of Academic Excellence in Higher Education.”

### Harvard

* Majority of Harvard’s Research Funding Has Been Restored

[https://www.insidehighered.com/news/quick-takes/2025/10/15/majority-harvards-research-funding-has-been-restored](https://www.insidehighered.com/news/quick-takes/2025/10/15/majority-harvards-research-funding-has-been-restored)

> As of Tuesday, Harvard University had recouped most of the federal research funding it lost when the Trump administration froze its access to grants earlier this year, multiple local news organizations reported.

> The taxpayer dollars first started to flow last month after a federal judge ruled that the restrictions Trump had placed on grant access were unconstitutional. It remains unclear exactly how much funding has been distributed and what remains frozen, but in an email obtained by The Boston Globe, Harvard’s CFO and vice president for finance confirmed that the university has “received reinstatements of the majority of our direct federal awards.”

> “Despite this encouraging news, uncertainty about the continuation of scientific funding remains,” Andrea Baccarelli, dean of the Harvard T. H. Chan School of Public Health, wrote in an email to staff members Friday, according to the Globe.

> As a result, the public health school has instructed researchers to cap their spending at 80 percent of the total grant value, at least for now.

### Princeton

* Princeton Will Require Standardized Test Scores Again

[https://www.insidehighered.com/news/admissions/traditional-age/2025/10/13/princeton-will-require-standardized-test-scores-again](https://www.insidehighered.com/news/admissions/traditional-age/2025/10/13/princeton-will-require-standardized-test-scores-again)

> According to a university webpage about the new testing requirement, the decision was based on data collected over the past five years of test-optional admissions showing “that academic performance at Princeton was stronger for students who chose to submit test scores than for students who did not.” Like other institutions that have switched back to requiring test scores in recent years, the university said the test scores would be considered among other admissions materials and that there was no specific minimum score needed to be admitted to Princeton. Active military applicants will be exempt from submitting test scores.

### MIT

* M.I.T. Rejects a White House Offer for Special Funding Treatment - The New York Times

[https://www.nytimes.com/2025/10/10/us/mit-rejects-white-house-compact.html](https://www.nytimes.com/2025/10/10/us/mit-rejects-white-house-compact.html)

> In a letter on Friday to the Trump administration, M.I.T.’s president, Sally Kornbluth, wrote that the university has already freely met or exceeded many of the standards outlined in the proposal, but that she disagrees with other requirements it demands, including those that would restrict free expression.

> “Fundamentally, the premise of the document is inconsistent with our core belief that scientific funding should be based on scientific merit alone,” Dr. Kornbluth wrote.

(Also)

[https://www.washingtonpost.com/education/2025/10/10/mit-rejects-trump-compact-education-funding/](https://www.washingtonpost.com/education/2025/10/10/mit-rejects-trump-compact-education-funding/)

[https://www.wsj.com/opinion/trump-merit-and-mit-aaf4ac58?st=NT2Nso&reflink=article_gmail_share](https://www.wsj.com/opinion/trump-merit-and-mit-aaf4ac58?st=NT2Nso&reflink=article_gmail_share)

### Brown

* Brown U.'s President Declines Trump’s Compact, Saying It Would ‘Undermine’ the Institution

[https://www.chronicle.com/blogs/the-trump-agenda/brown-u-s-president-declines-trumps-compact-saying-it-would-undermine-the-institution](https://www.chronicle.com/blogs/the-trump-agenda/brown-u-s-president-declines-trumps-compact-saying-it-would-undermine-the-institution)

> Brown University on Wednesday rejected the Trump administration’s offer to join the proposed “Compact for Academic Excellence in Higher Education” — the second of nine prominent institutions initially approached with the wide-ranging agreement to release a formal response.

> The Massachusetts Institute of Technology’s president, Sally Kornbluth, was the first to respond to the offer; she said last week she “cannot support” the current version of the compact.

> Brown, meanwhile, had previously struck a deal with the federal government to restore millions of dollars in research funding paused in the spring and resolve several inquiries into its compliance with civil-rights law. That agreement, announced in July, required the university to commit $50 million over 10 years to work-force development in Rhode Island.

* Brown Joins MIT, Rejects Compact

[https://www.insidehighered.com/news/governance/executive-leadership/2025/10/15/brown-university-rejects-trumps-higher-ed-compact](https://www.insidehighered.com/news/governance/executive-leadership/2025/10/15/brown-university-rejects-trumps-higher-ed-compact)

> of the original nine invitees, there are no takers so far, though officials at the University of Texas system have indicated they view the proposal favorably. The system’s flagship in Austin was part of the nine.

(Also)

[https://www.nytimes.com/2025/10/15/us/brown-university-trump-compact-funding.html](https://www.nytimes.com/2025/10/15/us/brown-university-trump-compact-funding.html)

### U Penn

* NYTimes: Penn and U.S.C. Become Latest Universities to Reject White House Deal

[https://www.nytimes.com/2025/10/16/us/university-of-pennsylvania-rejects-white-house-deal.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/10/16/us/university-of-pennsylvania-rejects-white-house-deal.html?smid=nytcore-ios-share&referringSource=articleShare)

> Penn’s president, J. Larry Jameson, informed the university community in a message on Thursday that he had notified Linda McMahon, the education secretary, of Penn’s decision not to sign the agreement. The announcement followed pushback, from both members of Penn’s faculty and state elected officials. Two of the officials went so far as to propose legislation opposing the deal.

> Just hours later, a similar notice went out from Beong-Soo Kim, the interim president of the University of Southern California, advising the university community that he, too, had notified Ms. McMahon his institution would not agree to participate.

> But, he [Kim] added, “We are concerned that even though the compact would be voluntary, tying research benefits to it would, over time, undermine the same values of free inquiry and academic excellence that the compact seeks to promote.”

> The University of Texas at Austin, one of the schools invited to join the compact, had indicated an early willingness to entertain the proposal, developed in part by Marc Rowan, a billionaire private equity financier.

> Mr. Rowan, a Penn alumnus who helped drive out Dr. Jameson’s predecessor from office in 2023, was among the proposal’s leading champions and worked on drafts of the document months before the White House circulated it to schools.

(Also)

[https://www.thedp.com/article/2025/10/penn-rejects-white-house-compact](https://www.thedp.com/article/2025/10/penn-rejects-white-house-compact)

> The proposed agreement — which legal experts and civil rights groups have characterized as “blatantly unconstitutional” — faced immediate criticism following its announcement earlier this month. Over the past two weeks, nearly 2,000 members of the Penn community signed a petition urging the University to reject the proposal.

> At a Wednesday meeting, Penn’s Faculty Senate overwhelmingly passed a resolution urging the University to reject the agreement.

> “The ‘Compact’ erodes the foundation on which higher education in the United States is built,” the Oct. 15 resolution read. “The University of Pennsylvania Faculty Senate urges President Jameson and the Board of Trustees to reject it and any other proposal that similarly threatens our mission and values.”

### USC

* USC rejects Trump's compact - Daily Trojan

[https://dailytrojan.com/2025/10/17/usc-rejects-trumps-compact/](https://dailytrojan.com/2025/10/17/usc-rejects-trumps-compact/)

> In his email, Kim [USC President] cited a dedication to including diverse political opinions and fear of external influences degrading academic independence as reasons for rejecting the compact.

> “Without an environment where students and faculty can freely debate a broad range of ideas and viewpoints, we could not produce outstanding research, teach our students to think critically, or instill the civic values needed for our democracy to flourish,” Kim wrote in the letter.

### U of Virginia

* The Trump Agenda: How the U. of Virginia Is Weighing Its Response to Trump’s Proposed Compact

[https://www.chronicle.com/blogs/the-trump-agenda/how-the-u-of-virginia-is-weighing-its-response-to-trumps-proposed-compact](https://www.chronicle.com/blogs/the-trump-agenda/how-the-u-of-virginia-is-weighing-its-response-to-trumps-proposed-compact)

> The University of Virginia on Monday sent an online form to the campus community, asking survey takers whether there were aspects of the proposed “Compact for Academic Excellence in Higher Education” that they supported or opposed, and to explain their feelings. That input — due October 20, the deadline for UVa to provide feedback to the Trump administration — will be shared with the working group, responsible for examining “the financial and legal aspects of the proposal and its implications for the university’s mission and values.”

> UVa’s interim president, Paul G. Mahoney, has acknowledged publicly that certain provisions in the document would be difficult for the university to endorse.

> The Chronicle obtained the list of people advising Mahoney on the implications of the compact. The working group is co-chaired by UVa.’s interim provost and its chief operating officer and also includes the vice presidents for research, enrollment, and global affairs; the vice president and chief student-affairs officer; the vice president and chief financial officer; the executive directors for state and federal government relations; the dean of the public-policy school; the secretary to the board; and the university counsel.

> While there is no faculty or student representative to the working group, Jeri K. Seidman, an associate professor of commerce and chair of the Faculty Senate, said she hoped there would be other ways to provide input beyond just the survey. “We have a lot of surveys going on right now,” she noted, as the university searches for both a permanent president and provost.

> “Once you start saying some things are good and some things are not good, you’re conceding the principle that the federal government is allowed to tell university faculty and university students what they should think and teach,” said William I. Hitchcock, a UVa history professor and co-chair of the steering committee in the College and Graduate School of Arts and Sciences. “And if you’ve made that concession, then it’s too late.”

### Dartmouth

* Dartmouth’s President Balks at Trump Compact, Sources Say, as Feds Expand Offer to ‘Any Institution'

[https://www.chronicle.com/article/dartmouths-president-balks-at-trump-compact-sources-say-as-feds-expand-offer-to-any-institution?utm_source=Iterable&utm_medium=email&utm_campaign=campaign_15299041_nl_Academe-Today_date_20251015](https://www.chronicle.com/article/dartmouths-president-balks-at-trump-compact-sources-say-as-feds-expand-offer-to-any-institution?utm_source=Iterable&utm_medium=email&utm_campaign=campaign_15299041_nl_Academe-Today_date_20251015)

> The president of Dartmouth College, an initial recipient of the Trump administration’s much-debated “compact” for higher education, has told faculty members that she will not endorse the current version of the agreement, two sources told The Chronicle.

> “She was very firm and clear on that, but it also had that very clear ‘as written’ part attached to it,” said that faculty member.

> The administration has offered scant details about the benefits and how they might be conveyed to colleges that sign the compact, leaving institutional leaders to debate whether the document is an offer or a threat. Christopher F. Rufo, a senior fellow at the Manhattan Institute, called Kornbluth’s rejection of the current compact “preposterous” in a Tuesday essay in City Journal, and encouraged the administration to “incrementally increase both the rewards for entering into the compact and the punishments for refusing.”

> Hanlon, [Past president and faculty] at Dartmouth, said the fact that the agreement is now open to all colleges shouldn’t change any individual institution’s response. “It’s up to every campus to figure out where their red lines are and how they want to approach this compact,” he said.

### George Mason

* GMU’s Gregory Washington: ‘I’m the Most Scrutinized President’ at ‘the Most Scrutinized Campus in the Country’

[https://www.chronicle.com/article/gmus-gregory-washington-im-the-most-scrutinized-president-at-the-most-scrutinized-campus-in-the-country](https://www.chronicle.com/article/gmus-gregory-washington-im-the-most-scrutinized-president-at-the-most-scrutinized-campus-in-the-country)

> “I don’t have to tell you that we’re probably the most scrutinized campus in the country,” Washington told faculty at a town hall. “And you don’t have to tell me that I’m the most scrutinized president.”

> During the town hall, Washington maintained that he nor the university has discriminated against anyone. “It’s something that I disagree with, and we’re going through the process of mitigating that now,” Washington said. “I don’t believe in discrimination.”

> Washington said the university in the past year has made several changes to comply with federal antidiscrimination laws, including renaming its Office of Diversity, Equity, and Inclusion, ending the Anti-Racism and Inclusive Excellence task force, and closing its Center for Truth, Racial Healing, and Transformation.

> George Mason University’s faculty have also come under fire from the federal government. In July, the Justice Department accused the Faculty Senate of praising Washington for discriminatory hiring practices after it passed a resolution defending the president.

> The Justice Department has since requested all communication between the Faculty Senate and Washington.

### Others

* Judge Halts UT’s Comprehensive Ban on Student Speech

[https://www.insidehighered.com/news/quick-takes/2025/10/16/judge-halts-uts-comprehensive-ban-student-speech](https://www.insidehighered.com/news/quick-takes/2025/10/16/judge-halts-uts-comprehensive-ban-student-speech)

> A Texas district court judge on Tuesday ordered the University of Texas system to hold off on enforcing new, sweeping limits on student expression that would prohibit any “expressive activity” protected by the First Amendment between 10 p.m. and 8 a.m.

> “The First Amendment does not have a bedtime of 10 p.m.,” wrote U.S. district court judge David Alan Ezra in his order granting the plaintiff’s request for a preliminary injunction. “Giving administrators discretion to decide what is prohibited ‘disruptive’ speech gives the school the ability to weaponize the policy against speech it disagrees with. As an example, the Overnight Expression Ban would, by its terms, prohibit a sunrise Easter service. While the university may not find this disruptive, the story may change if it’s a Muslim or Jewish sunrise ceremony. The songs and prayer of the Muslim and Jewish ceremonies, while entirely harmless, may be considered ‘disruptive’ by some.”

> ... in addition to prohibiting expression overnight, also sought to ban campus public speakers, the use of drums and amplified noise during the last two weeks of the semester. The restrictive policies align with Texas Senate Bill 2972, called the Campus Protection Act, which requires public universities to adopt restrictions on student speech and expression. The bill took effect on Sept. 1.

> “Texas’ law is so overbroad that any public university student chatting in the dorms past 10 p.m. would have been in violation,” said Adam Steinbaugh, a senior attorney at the Foundation for Individual Rights and Expression, in a press release. “We’re thankful that the court stepped in and halted a speech ban that inevitably would’ve been weaponized to censor speech that administrators disagreed with.”

## Court cases

* LEAH GARRETT v CITY UNIVERSITY OF NEW YORK

[https://storage.courtlistener.com/recap/gov.uscourts.nysd.633652/gov.uscourts.nysd.633652.41.0.pdf](https://storage.courtlistener.com/recap/gov.uscourts.nysd.633652/gov.uscourts.nysd.633652.41.0.pdf)

(Motion to dismiss by CUNY is denied)

## Blowback

* 2 Nobel Prize–Winning Economists Leave U.S. for Zurich

[https://www.insidehighered.com/news/quick-takes/2025/10/15/2-nobel-prize-winning-economists-leave-us-zurich](https://www.insidehighered.com/news/quick-takes/2025/10/15/2-nobel-prize-winning-economists-leave-us-zurich)

> Nobel Prize–winning economists Abhijit Banerjee and Esther Duflo—a married team—will leave their positions at the Massachusetts Institute of Technology for the University of Zurich in the next academic year, The Bulwark reported.

> The pair, who won the Nobel in 2019, have not publicly shared why they are leaving MIT at this time, but a source told The Bulwark that they are moving due to the Trump administration’s attacks on academic freedom and university research.

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
