# Oct 31

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

Fewer items than previous weeks---perhaps stomping on higher education isn't an essential service---but still scary enough for Halloween.

## Letters

## Alliances

## Statements

* UFS passes two resolutions opposing the "compact" extended by the federal government to all US universities. One supports "Not This Compact"

[https://www1.cuny.edu/sites/cunyufs/committees/executive/executive-committee-correspondence/2025-not-this-compact/](https://www1.cuny.edu/sites/cunyufs/committees/executive/executive-committee-correspondence/2025-not-this-compact/)


## Protests

## Zoom calls

## Shared governance

## Academic freedom

* GOP Senator Accuses AAUP President of Exacerbating ‘Organizational Antisemitism’

[https://www.insidehighered.com/news/quick-takes/2025/10/28/cassidy-aaup-president-exacerbated-organizational-antisemitism](https://www.insidehighered.com/news/quick-takes/2025/10/28/cassidy-aaup-president-exacerbated-organizational-antisemitism)

> In a letter to American Federation of Teachers president Randi Weingarten, Sen. Bill Cassidy, the Louisiana Republican who chairs the education committee, accused American Association of University Professors president and AFT vice president Todd Wolfson of promoting “organizational antisemitism” within the AAUP.

> “It appears Senator Cassidy and his GOP colleagues are furious that seven universities have rejected Trump’s absurd Higher Ed Loyalty Oath. Rather than reckon with their failed attempt to strong-arm higher education, they’ve chosen to complain to our national affiliate, AFT, because AAUP dared to hold a webinar,” Wolfson wrote, referring to an AAUP webinar called “Scholasticide in Palestine” that Cassidy referenced in the letter. “I would respectfully suggest they spend less time trying to undermine my constitutional rights and more time focusing on what Americans actually care about—like reopening the government, lowering healthcare costs, and addressing the cost-of-living crisis.”

* NYTimes: How Politics Is Changing the Way History Is Taught

[https://www.nytimes.com/2025/10/27/us/history-lessons-ethnic-studies-retreat.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/10/27/us/history-lessons-ethnic-studies-retreat.html?smid=nytcore-ios-share&referringSource=articleShare)

> In the Trump era, history and civics education are under a microscope.

> Several major curriculum publishers have withdrawn products from the market, while others have found that teachers are shying away from lessons that were once uncontroversial, on topics as basic as constitutional limits on executive power.

> California, the nation’s largest Democratic-led state, has passed a law restricting what teachers can say in the classroom, and has walked back an effort to require high school students to take classes in ethnic studies.

> As recently as last year, many social studies teachers reported success in withstanding political pressure. Now, there is growing evidence that the landscape is shifting. In a September poll, more than half of the teachers who responded said that political pressure had caused them to modify their curriculums or classroom discussions, a sharp increase from March.

(Of course this includes the obligatory quote from Chris Rufo, who always seems to get his say in any Times article.)

> This spring, as Brown University was under intense pressure from the Trump administration, it shuttered Choices, the university’s 30-year-old high school social studies curriculum, overseen by its history department.


## Freedom of expression

* NYTimes: A Student Publication at Harvard Echoed Hitler. Now It Has Been Suspended.

[https://www.nytimes.com/2025/10/27/us/harvard-salient-hitler-suspended-magazine.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/10/27/us/harvard-salient-hitler-suspended-magazine.html?smid=nytcore-ios-share&referringSource=articleShare)

> The board of a conservative magazine at Harvard known for its muckraking suspended the publication on Sunday, citing the printing of “reprehensible, abusive and demeaning material.”

> The magazine, The Harvard Salient, which was founded during the Reagan era and revived four years ago after a decade-long absence, is editorially and financially independent from the university.

> ... the publication had recently been embroiled in a controversy over an article that included a line similar to one in a Hitler speech.

> “To be clear: Harvard should not censor The Salient,” Adam N. Chiocco, an opinion writer for The Harvard Crimson, wrote this month. “If the university started halting the publication of campus outlets, I worry where they would stop. But it is also obvious that any use of Nazi rhetoric is absolutely reprehensible.”

> Alex Acosta, The Harvard Salient’s board chair and a labor secretary for Mr. Trump during his first term, could not be reached for comment.

### Anti-woke/anti-DEI is simply racism

* Trump’s DEI Crackdown Closes 120 TRIO Programs

[https://www.insidehighered.com/news/admissions/traditional-age/2025/10/27/trumps-dei-crackdown-closes-120-trio-programs](https://www.insidehighered.com/news/admissions/traditional-age/2025/10/27/trumps-dei-crackdown-closes-120-trio-programs)

> When the leaders of the 26-year-old Upward Bound program at SUNY Adirondack received word earlier this fall that the Trump administration had canceled their grant, they were shocked to see the Education Department’s reason for the termination.

> In the grant application for the college-access program for high school students, they had said they wanted to ensure the program included an equal number of male and female participants, in an effort to address declining male participation in the program. But in the grant termination letter—delivered mid-September, after the program’s annual Sept. 1 start date—Department of Education officials said that that line reflected the Biden administration’s priorities and conflicted with the interests of the current administration.

> According to the Council for Opportunity in Education, the organization that advocates for TRIO programs, about 100 grants were canceled or rejected in September after the department delayed funding for thousands of TRIO grants that were slated to begin on Sept. 1. Another 23 programs lost funding earlier in the year. The cancellations represent a small portion of TRIO programs—3 percent—but they affect over 43,600 students who will now be without a slew of resources, from tutoring to assistance with financial aid. Colleges that house these programs have also had to lay off staff members.

* 21 States, D.C. Ask Court to Reverse TRIO Grant Rejections

[https://www.insidehighered.com/news/quick-takes/2025/10/31/21-states-dc-ask-court-reverse-trio-grant-rejections](https://www.insidehighered.com/news/quick-takes/2025/10/31/21-states-dc-ask-court-reverse-trio-grant-rejections)

> Democratic attorneys general from 21 states and Washington, D.C., filed briefs this week asking a court to reverse the Trump administration’s rejection of grants supporting TRIO programs, which help disadvantaged students attend and graduate from colleges and universities.

> Those terminations deprived more than 43,600 students of services such as tutoring and financial aid help. (Trump’s fiscal year 2026 budget request would end TRIO altogether, and all but a handful of staff in the TRIO grants office were fired early in the ongoing government shutdown.)

> The AGs of Nevada and Massachusetts were the briefs’ lead authors; they were joined by their counterparts in Arizona, California, Colorado, Connecticut, Delaware, D.C., Hawai‘i, Illinois, Maine, Maryland, Michigan, Minnesota, New Jersey, New Mexico, **New York**, Oregon, Rhode Island, Vermont, Washington and Wisconsin.

* These Republicans oppose DEI, but also cuts hitting Hispanic-serving colleges

[https://www.washingtonpost.com/nation/2025/10/30/hispanic-serving-institutions-republican-support/](https://www.washingtonpost.com/nation/2025/10/30/hispanic-serving-institutions-republican-support/)

> Last year, Rep. Tony Gonzales co-sponsored legislation to rid the federal government of diversity, inclusion and equity programs, arguing that such efforts create “arbitrary quotas.”

> But when the Trump administration recently ended a $350 million program that steered funding to universities with a large population of Hispanic students, Gonzales (R-Texas) objected.

> “They’re not trying to reach a quota like DEI is doing,” Gonzales said. “They’re just serving the communities in which they happen to live in, which what is what we want.”

(Not sure where these "quotas" are when diversity is discussed, but consistency is never as easy as just spinning a narrative.)

## Visas

* ASSOCIATION OF AMERICAN UNIVERSITIES and CHAMBER OF COMMERCE OF THEUNITED STATES OF AMERICA join forces to sue over H1-B visa changes

[https://www.documentcloud.org/documents/26197067-chamberaauamendcomp102425/](https://www.documentcloud.org/documents/26197067-chamberaauamendcomp102425/)

> The United States is unique in its ability to attract the brightest talent from acrossthe globe. For more than 70 years, what is now known as the H-1B visa program has enabled theUnited States to harness this magnetic draw. Tens of thousands of highly skilled people in special-ized fields boost the American economy each year after obtaining H-1B status. These workersallow businesses of all sizes, in industries across the economy, to innovate and grow. They con-tribute to ground-breaking research and educate American students at America’s leading univer-sities. The resulting innovations lead to more American jobs, higher wages, and new products andservices that improve the quality of life for all Americans. ...

* DeSantis to Fla. Universities: Pull the Plug on H-1B Workers

[https://www.insidehighered.com/news/faculty-issues/2025/10/29/desantis-fla-universities-pull-plug-h-1b-workers](https://www.insidehighered.com/news/faculty-issues/2025/10/29/desantis-fla-universities-pull-plug-h-1b-workers)

> Florida governor Ron DeSantis on Wednesday ordered the state’s public universities “to pull the plug on the use of these H-1B visas in our universities.” In doing so, the Republican appeared to call for his state to go further than President Trump in restricting entry of these foreign employees—an issue that has divided prominent conservatives.

> After mentioning a public policy professor from China, DeSantis said, “Why do we need to bring someone from China to talk about public policy?” Later—apparently looking at information on another H-1B holder—he exclaimed, “Wuhan, China!”

> Although DeSantis’s complaints focused on supposed international scholars from China, he didn’t spare those from other countries.

> “Assistant swim coach from Spain, on an H-1B visa—are you kidding me, we can’t produce an assistant swim coach in this country?” he said. He then turned to the Middle East.

> “Clinical assistant professor from the West Bank, clinical assistant professor from supposed Palestine,” he said. “Is that just social justice that they’re doing? And that’s University of Florida.”

> “We need to make sure our citizens here in Florida are first in line for job opportunities,” DeSantis said. But he also suggested he doesn’t fully know why universities are hiring H-1B workers.

(This is what it takes to try and get pole position in 2028)

## Loss of expertise

## Funding cuts

### NSF

### NIH

### NEH

### NEA

### DOE

* NYTimes: Judge Rebukes Justice Dept. Over Efforts to Obtain Confidential Patient Details

[https://www.nytimes.com/2025/10/29/us/politics/justice-dept-transgender-patients.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/10/29/us/politics/justice-dept-transgender-patients.html?smid=nytcore-ios-share&referringSource=articleShare)

> In a scathing order, a judge in Washington State said the government’s real purpose was to intimidate providers into dropping or paring back transgender care.

* Higher Ed May Be in Trouble if the Government Is Shut Down for Much Longer

[https://www.chronicle.com/article/higher-ed-may-be-in-trouble-if-the-government-is-shut-down-for-much-longer](https://www.chronicle.com/article/higher-ed-may-be-in-trouble-if-the-government-is-shut-down-for-much-longer)

> Temporary funding lapses typically have limited effects on colleges. But what happens if a shutdown persists beyond a few weeks?

> The result could be lost access to grants and support programs, serious disruptions to research, and potentially problems with financial aid, higher-ed advocates told The Chronicle.

> As Republicans and Democrats in Congress continue to spar over federal-spending limits and health-insurance subsidies, the gridlock continues. Without a resolution by the end of Tuesday, the shutdown will become the longest ever.

(At CUNY PELL has been distributed through Fall semester; grants *should* be good for upto 3 months (between the RF, the campus, and central); but on the margins there will be impacts.)

> Such problems could become more apparent down the road: Spring is the peak processing season for students filling out the Free Application for Federal Student Aid, or FAFSA, which is used to determine aid offers for the following academic year.


### Fulbright

## Federal Agencies

### DOE/OCR

* Trump’s Deportation Campaign Raises FAFSA Privacy Concerns

[https://www.insidehighered.com/news/students/diversity/2025/10/31/trumps-deportation-campaign-raises-fafsa-privacy-concerns](https://www.insidehighered.com/news/students/diversity/2025/10/31/trumps-deportation-campaign-raises-fafsa-privacy-concerns)

> College access organizations are raising concerns about students from mixed-status families—families with members who hold different immigration statuses—who are filling out the Free Application for Federal Student Aid amid the Trump administration’s mass deportation campaign.

> “Although the Higher Education Act prohibits the use of data for any purpose other than determining and awarding federal financial assistance, [the National College Attainment Network] cannot assure mixed-status students and families that data submitted to US Department of Education (ED), as part of the FAFSA process, will continue to be protected,” NCAN, which represents college access organizations across the nation, wrote in new guidance.

## Congressional actions

## State actions

* DiNapoli: Recent Federal Actions Will Have Significant Impact on Higher Education in NY | Office of the New York State Comptroller

[https://www.osc.ny.gov/press/releases/2025/10/dinapoli-recent-federal-actions-will-have-significant-impact-higher-education-ny](https://www.osc.ny.gov/press/releases/2025/10/dinapoli-recent-federal-actions-will-have-significant-impact-higher-education-ny)

> Impacts from the recently enacted federal budget law, upcoming appropriations for federal fiscal year 2026 and executive actions since January 2025 risk undermining the strength and competitiveness of New York’s higher education sector and the social and economic benefits it generates, according to a new analysis from State Comptroller Thomas P. DiNapoli.

[https://www.osc.ny.gov/reports/budget/fed-funding-ny/federal-impact-higher-education](https://www.osc.ny.gov/reports/budget/fed-funding-ny/federal-impact-higher-education)

> Almost 308,000 undergraduates in New York received federal Pell Grants in 2022-23; of these, about one-third were students at private IHEs and just over two-thirds studied at public sector institutions.18 The almost 210,000 recipients of Pell Grants in the public sector represented over 48 percent of all SUNY and CUNY degree- and certificate-seeking undergraduate enrollments with nearly 98,000 recipients representing 31.5 percent of such undergraduate enrollments at private IHEs.19


> Conclusion: Recent federal actions threaten New York’s expansive higher education sector’s ability to attract and cultivate talent and conduct the cutting-edge research and development that help spur innovation and economic growth. Limitations to aid and loans, particularly in graduate study, may make pursuit of higher education unaffordable to some, which is especially concerning since higher education costs in the State, apart from tuition at four-year public IHEs, are higher than the nationwide average. This challenge will be compounded by potential declines in international students whose full tuition payments act to subsidize charges paid by New York residents. Additionally, an increased tax on certain endowments could place additional strain on IHEs. In an environment which has become increasingly competitive for both students and research dollars, and has already seen several institutions in the State close, federal actions may hinder the State’s ability to attract talent and pose financial challenges for many of the State’s colleges and universities. Such outcomes may hinder the State’s ability to maintain its competitive advantage in the higher education sector.

* Florida wants to post more college syllabi online. Professors fear what's next - POLITICO

[https://www.politico.com/news/2025/10/26/florida-wants-to-post-more-college-syllabi-online-professors-fear-whats-next-00621570](https://www.politico.com/news/2025/10/26/florida-wants-to-post-more-college-syllabi-online-professors-fear-whats-next-00621570)

> University leaders in Florida want schools to post what textbooks, instructional materials and readings are required for most courses, similar to a policy recently adopted by Georgia colleges.

> Supporters say the change promotes openness and accountability, helping students see what they’re signing up for and encouraging professors to stay on topic. But some faculty fear the changes could invite political pressure and harassment at a time when higher education is under an intense ideological spotlight, particularly around lessons touching on gender, race and diversity.

* NYTimes: New York Survived Its 1975 Crisis. Will Trump Push It Back to the Brink?

[https://www.nytimes.com/2025/10/30/nyregion/ford-nyc-financial-crisis-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/10/30/nyregion/ford-nyc-financial-crisis-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

(More anti-Mandani slant from the times, but there are some interesting facts about the perilous budget times we live in.)

> The state comptroller, Thomas P. DiNapoli, a Democrat, has forecast that the city’s budget shortfall will be $13 billion by the 2028 fiscal year. “If this economy falters in any way or slows,” he said in an interview, the city could “really be in for some very challenging decisions on spending and taxation.”

> The state, which relies on the federal government for about a third of its funds, also has looming budget gaps; Mr. DiNapoli projects a state budget deficit of $34 billion by the 2029 fiscal year.



## Institutional assaults

*  The Little-Known Way That Trump Is Upending Community College

[https://www.chronicle.com/article/the-little-known-way-that-trump-is-upending-community-college](https://www.chronicle.com/article/the-little-known-way-that-trump-is-upending-community-college)

> The Trump administration has proposed cutting funding for adult education, a suite of programs that includes English-language learning and high-school equivalency training, which can confer GEDs.

> “Adult ed is like a little secret — nobody really knows what we do,” said Dian Organ, director of adult education at Colby Community College, in Kansas. “We serve the population that nobody wants to see.”

> The Trump administration has already canceled some individual grants for adult education, and its budget proposal for this fiscal year included cutting all $729 million within Title II of the Workforce Innovation Opportunity Act (WIOA) — the main source of federal money for adult education. While presidential budget blueprints aren’t the final word, they are a statement of an administration’s priorities.

> Trump’s budget proposal also includes repackaging all work-force preparation programs into a single “Make America Skilled Again” grant of just under $3 billion — a reduction compared to the $3.9 billion of Workforce Innovation Opportunity Act money that Congress approved last fiscal year. One aim of this revamped grant system would be to stop “funneling taxpayer dollars to progressive nonprofits finding work for illegal immigrants,” according to Trump’s proposal.

> DeRionne Pollard, president and chief executive of the American Association of Community Colleges, said certain Trump-backed changes are intended to bring adult education more in line with work-force preparation.

### The "compact"

* New College ‘First in Line’ to Sign Trump’s Higher Ed Compact

[https://www.insidehighered.com/news/quick-takes/2025/10/28/new-college-first-line-sign-higher-ed-compact](https://www.insidehighered.com/news/quick-takes/2025/10/28/new-college-first-line-sign-higher-ed-compact)

> New College of Florida wants to be the first university to sign the Trump administration’s compact for higher education, which would require institutions to make a number of changes to their policies and practices in order to receive some potential benefit.

> Officials said in a news release Monday that the college is already adhering to many of the provisions in the proposed document and highlighted their efforts to eliminate diversity, equity and inclusion and what they called discrimination in admissions. They also noted their commitment to keep costs low for students and to free speech.

> More than two years ago, Florida governor Ron DeSantis appointed six conservatives to the board of New College, and those members instituted a number of changes as part of a conservative overhaul, including cutting the gender studies program, removing LGBTQ+ materials from the library and hiring multiple figures from the conservative political sphere in administrative roles.

(Will viewpoint diversity mean they will hire non-conservatives...)

* Penn Releases Compact Rejection Letter Sent to McMahon

[https://www.insidehighered.com/news/quick-takes/2025/10/27/penn-releases-compact-rejection-letter-sent-mcmahon](https://www.insidehighered.com/news/quick-takes/2025/10/27/penn-releases-compact-rejection-letter-sent-mcmahon)

> Responding to the compact’s initial request for “limited, targeted feedback,” Jameson [U Penn President] also lays out his “areas of concern,” including the promise of preferential treatment for signatories. In language similar to that used by other campus leaders who rejected the compact, he writes, “Penn seeks no special consideration beyond fair and merit-based funding.”

> He also takes issue with the compact’s omission of academic freedom as a “foundational principle,” its prioritization of free tuition for students pursuing “hard sciences” and the punitive use of funding cuts “based on subjective standards and undefined processes.”

> “America’s great universities already have a compact with the American people. It is built on the open exchange of ideas, merit-based selection and achievement, and freedom of inquiry to yield knowledge,” the letter concludes. “Penn respectfully declines to sign the proposed Compact.”

* Americans Think Trump Is Overreaching With His Higher-Ed Compact

[https://www.chronicle.com/article/americans-think-trump-is-overreaching-on-higher-ed](https://www.chronicle.com/article/americans-think-trump-is-overreaching-on-higher-ed)

> By a wide margin, the public rejects that effort — including the White House’s most recent foray...

* Valley Forge Military College Wants to Sign Compact

[https://www.insidehighered.com/news/quick-takes/2025/10/31/valley-forge-military-college-wants-sign-compact](https://www.insidehighered.com/news/quick-takes/2025/10/31/valley-forge-military-college-wants-sign-compact)

> Now Valley Forge, a private two-year college in Pennsylvania, wants in on the compact.

> “Participation in the Compact would provide valuable opportunities for collaboration, shared learning, and continuous improvement. We are particularly eager to contribute to discussions on leadership education, student resilience, and pathways from two-year programs to four-year institutions,” officials wrote to the Education Department. “These are areas in which Valley Forge has developed effective practices and measurable outcomes that could benefit peer institutions.”

(What is a private two-year college?)

> It is unclear how Valley Forge, which does not have a research focus, would benefit. The college is also much smaller than the first invitees, enrolling 86 students in fall 2023, according to federal data.


### Admissions

### Accreditation

* Accreditors Start to Endorse Short-Term Credential Providers

[https://www.insidehighered.com/news/quick-takes/2025/10/30/accreditors-start-endorse-short-term-credential-providers](https://www.insidehighered.com/news/quick-takes/2025/10/30/accreditors-start-endorse-short-term-credential-providers)

> After years of preparation, the Higher Learning Commission is launching a new process to evaluate and endorse short-term credential providers this week, according to a Tuesday announcement from the HLC. The accreditor will be accepting applications for its first cohort of endorsed providers through Jan. 23.

> Higher Learning Commission president Barbara Gellman-Danley said in the announcement that HLC’s goal is “to expand the nation’s pool of valuable, HLC endorsed providers, thereby increasing pathways for students to gain the qualifications they need to get ahead and succeed.”

> “We know that there are increasing numbers of students enrolled in non-credit programs,” Michaele Whelan, chairperson of NECHE, said in a news release. “There has also been a growing need for quality assurance in this space. NECHE has taken the bold step to address this need and we are excited to expand our work into this area.”



### Harvard

### Columbia

### Indiana

> Indiana University Alumni Pull Donations Over Student Newspaper Censorship

[https://www.insidehighered.com/news/quick-takes/2025/10/28/iu-alumni-pull-donations-over-student-newspaper-censorship](https://www.insidehighered.com/news/quick-takes/2025/10/28/iu-alumni-pull-donations-over-student-newspaper-censorship)

> ,,, alumni aren’t buying it, IndyStar reported. Some are asking what came of donations they made to a fund dedicated to the student publication after the newspaper reported students faced hurdles to spending the money. Other alumni are pulling their donations altogether.

### UCLA

* A faculty lawsuit forced the university to release a 27-page draft “resolution agreement,” which would also require UCLA and affiliated hospitals to stop “performing hormonal interventions and ‘transgender’ surgeries” on anyone under 18.

[https://www.insidehighered.com/news/diversity/2025/10/27/trump-ucla-demand-12b-fine-nix-trans-athlete-wins-more](https://www.insidehighered.com/news/diversity/2025/10/27/trump-ucla-demand-12b-fine-nix-trans-athlete-wins-more)

> The Trump administration has demanded, among other things, that UCLA not enroll “foreign students likely to engage in anti-Western, anti-American, or antisemitic disruptions or harassment.” In the same paragraph, the proposed resolution agreement says UCLA would have to “socialize international students to the norms of a campus dedicated to free inquiry and open debate.”

> The federal government also demanded that UCLA ban overnight campus demonstrations and mandate that masked campus protesters reveal their identities when asked.

> California voters banned affirmative action in public education nearly 30 years ago, but the demand letter suggests the Trump administration doesn’t think UCLA has complied. It would require UCLA to bar providing “information about candidates’ race, sex, ethnicity, or other protected characteristics to faculty or other UCLA personnel with decision-making authority over hiring, retention, promotion or tenure.”

> It was yet another example of the Trump administration accusing a selective university of tolerating antisemitism and cutting off hundreds of millions of federal dollars. But, unlike Harvard and Columbia Universities, UCLA is a public institution, and its targeting by the federal government represents an expansion of the administration’s campaign to overhaul higher ed.

> “Accession to these demands would be to undermine everything that has made the UC the successful engine of social mobility and economic might that it has been for our state,” Anna Markowitz, president of the UCLA Faculty Association, wrote in an email. “It will harm undergraduate learning opportunities, and hamper UC’s ability to be a scholarly leader on the international stage. It enshrines ideology at the heart of the institution rather than decades of empirical and scholarly understanding. We stand against this extortion effort.”


[https://ucop.edu/communications/_files/confidential-rule-408-communication-ucla-08-08-25.pdf](https://ucop.edu/communications/_files/confidential-rule-408-communication-ucla-08-08-25.pdf)

(Also)

[https://www.chronicle.com/article/what-does-trump-want-from-ucla-the-proposed-settlement-was-just-made-public](https://www.chronicle.com/article/what-does-trump-want-from-ucla-the-proposed-settlement-was-just-made-public)


### U Chicago

* Research Is the U. of Chicago’s Lifeblood. Its Board Is Killing It.

[https://www.chronicle.com/article/research-is-the-u-of-chicagos-lifeblood-its-board-is-killing-it](https://www.chronicle.com/article/research-is-the-u-of-chicagos-lifeblood-its-board-is-killing-it)

> The University of Chicago is confronting two dangerous crises — one financial, one intellectual. The two are related.

> The university’s debt has grown rapidly in recent years. It stands today at around $6 billion, roughly 60 percent of its $10-billion endowment. (For some context, Northwestern University has roughly $3 billion in debt on a $14-billion endowment.) In financial year 2024, Chicago ran a $288-million deficit. These numbers have developed gradually — and then suddenly. The recent sale by the university of its blue-chip Center for Research in Security Prices, founded in 1960, for $375 million — and sold to a business owned by a trustee — is an especially ironic symptom of poor fiscal management.

> How did this happen? The answer lies in a national trend, which even a faculty with the financial expertise of Chicago’s could not resist. This trend is the total power of Boards of Trustees — self-appointed, self-reproducing, and answerable to no discernible public or regulatory scrutiny, not even to the presidents they hire, assess, and fire. Indeed, the growth of the power of the board is one of the most important transformations in American colleges since at least the 1990s.

> University presidents themselves live in the shadow of their boards. A remarkable amount of presidential time goes into meeting board expectations, negotiating board politics, managing board meetings and titrating news of campus tensions to boards. The provost and the deans are left to manage student recruitment, faculty hiring and promotion, curriculum, and campus life.

> In short, American universities have gradually come to be ruled by the very top of their imperial executive branches, the president and the board. The faculty, whose senates used to constitute a combined version of a legislative and judicial branch on campuses, have long been on the retreat, intimidated by the ballooning cadre of administrators and buffeted by real or imagined fiscal crises. In their diminished state, faculty are now kept busy responding to various student and parent whims about course content, grading, and campus politics. Faculty governance has largely been replaced by a governed faculty.

> The number of faculty on university boards of trustees varies from token to zero. The University of Chicago does not list a single faculty member on its board. In fact, there is not even an educator among the 23 (excluding the president),
> In the face of its debt crisis, how did the University of Chicago decide to proceed?

> It threatened to place the Division of the Arts & Humanities on the chopping block (having first clubbed the humanities and arts together last spring) through consolidation of departments and pausing graduate admissions. Here is another paradox: How could the least expensive division in the university, one of its most prestigious, be sacrificed on the altar of fiscal mismanagement? Why destroy something that not only comes cheap but brings immeasurable honor to the university? That’s the sort of decision you get when managers, not faculty, call the shots.

> But today’s draconian steps have yet another source. The enthusiasm for putting the humanities on a starvation diet and “pausing” graduate admission represents a steady move away from research as the driver of teaching and professional education toward pedagogy, where fee-paying students are seen as more useful than any research driven by curiosity and a pure devotion to new knowledge. And humanities departments represent the purest form of research itself. The social sciences, medicine, the life sciences, even mathematics, can always claim to have some utilitarian, applied, practical, or monetizable appeal, however obscure or remote. Economics creates policies, markets, and prices; political science claims to decipher elections, war, and peace; mathematics feeds physics, economics, engineering, and much else; law provides the oil for the entire world of contracts, justice, and order; medicine is, by definition, useful. The humanities as a whole, along with their cousins in history and anthropology, embody the luxury goods of pure research — knowledge for self-cultivation, exploration, exhilaration, and conscience. They are the exemplars of the ideals of research, and the conscience of the research impulse across the university. To shrink research at Chicago in favor of teaching, vocation, and utility requires this conscience to be stifled.

### Others

* Williams College Removes Diversity Language From Faculty Handbook, Will Accept Federal Funding Again

[https://www.chronicle.com/article/tracking-higher-eds-dismantling-of-dei](https://www.chronicle.com/article/tracking-higher-eds-dismantling-of-dei)

> Williams College’s faculty council approved revisions to the faculty handbook that removed mentions of affirmative action, references to “racial provisions” in the faculty-hiring process, and language stating that a fellowship was oriented toward “underrepresented groups.” The changes are part of a larger effort to review its compliance with federal regulations, college officials said.

> Williams made headlines in July for pausing its acceptance of NIH and NSF grants, which represent a small portion of the small private institution’s revenue. The college’s chief concern related to diversity-related orders and guidelines from the Trump administration. The handbook changes put the university on track to begin accepting funding again, possibly by the end of the month, The Williams Record reported.

*  ‘We as Universities Have Lost Our Way’ --- The provost at the University of Texas at Austin on Trump’s compact, higher ed’s broken social contract, and red-state reform.

[https://www.chronicle.com/article/we-as-universities-have-lost-our-way](https://www.chronicle.com/article/we-as-universities-have-lost-our-way)


>  Inboden: I think we align with the principles of conduct that they want. A lot of that is already a combination of Texas state law and university policy. But of course there’s the question of the procedures — how those would be enforced in the compact. That’s where we’re grateful that the White House is open-minded.

>  Inboden: We’re also governed by the First Amendment and by protections of particular civil liberties. And we’re certainly committed to the cardinal tenets of academic freedom. As written, some of the procedural enforcements of the compact would clash with state law and some of our other institutional prerogatives. But in the main, we’re happy to be having those discussions with them.

> Goldstein: So you’re substantively simpatico but procedurally concerned about enforcement mechanisms and some other aspects?

> Inboden: That’s a pretty accurate summary. I don’t want to say too much more because we find these discussions are best had behind the scenes.

> Goldstein: I’m hearing from UT Austin faculty members, and I would describe the level of anxiety as quite high. Some of them are certain, for instance, that women’s and gender and sexuality studies won’t survive the year. As one person put it to me, “COLA” — the College of Liberal Arts — “is fucked.” How worried should they be?

> Inboden: I’m going to keep my part of this interview PG-13.

> Inboden: ... We’re working on what we’re calling the Texas Statement on Academic Integrity, about academic freedom and teaching responsibilities. A committee of our faculty is putting this together. To be able to teach controversial subjects, that’s what our academic freedom protects, but the integrity with which we exercise that freedom means that when we are teaching about controversial subjects, we do it in a balanced way. That doesn’t mean a faculty member can’t have his or her own views on something. Of course they can. But teaching with balance means that if it’s a contested matter of public concern, we acknowledge that there are other viewpoints, maybe even present what some of the other viewpoints would be in a good-faith way.

> Inboden: The second principle is doing it in a way that students in the class who may hold a dissenting view from the professor or from other students feel free to voice those views. That they don’t feel intimidated into silence.

> Inboden: The responsibility of our academic freedom includes exposing students to multiple views. A lot of the public backlash or concern we’re seeing, or even some of the legislative measures, come from a sense that some faculty at some universities have presented these controversial topics in a dogmatic or doctrinaire way.

(Not sure where that is ever specified as a responsibility of academic freedom, having grown up in the protection from political influence in pursuing free search for truth and its free exposition.)

> Goldstein: I’m reminded of the 1915 AAUP “Declaration of Principles on Academic Freedom and Academic Tenure,” which you cite in your article, which says essentially that if faculty don’t police themselves, outside forces will come in and police you. Is the Texas statement an attempt by the university to both set a tone on campus and erect a shield against political intrusion.

> Inboden: I’m glad you mentioned the 1915 AAUP statement. When our academic-integrity statement comes out, you’ll see a lot of it is going to cite a number of precedents: the 1915 AAUP statement, the 1940 AAUP statement, some Supreme Court precedents. And I’ve recently read this fantastic book by David Rabban, one of our UT law professors, on academic freedom that came out last year — the single most magisterial treatment on academic freedom.

> Inboden: Academic freedom is a very robust right, but it’s not an unlimited right, and it includes responsibilities: How do we teach students? It doesn’t include the freedom to indoctrinate students. I know that’s a loaded term, but we can appreciate distinctions between teaching and indoctrination. There’s a great century-long tradition of both norms and laws for academic freedom in this country. But it’s all embedded in that deeper social contract between the American people and our universities. That includes universities policing ourselves better and exercising our rights responsibly. If we don’t, political leaders will get more involved, with a more heavy hand.

(I could quote more, but will leave it there. But there is a discussion about shared governance after faculty councils have been neutered.)

* Northwestern, Cornell Still Working to Unfreeze Federal Funds

[https://www.insidehighered.com/news/government/politics-elections/2025/10/29/northwestern-cornell-still-working-unfreeze-federal](https://www.insidehighered.com/news/government/politics-elections/2025/10/29/northwestern-cornell-still-working-unfreeze-federal)

> Since March, the Trump administration has said that it put nearly $6 billion on hold at nine universities. Three universities—Columbia, Penn and Brown—cut deals with the administration to restore the funding, while the University of California, Los Angeles, and Harvard got the money back via court orders. The fate of the remaining four freezes—at Duke, Cornell, Northwestern and Princeton Universities—remains uncertain.

> At Northwestern, the Trump administration reportedly froze about $790 million in early April, though officials said at the time they never received formal notification about why the funds were put on hold. Since then, Northwestern officials have said they are working to restore the grants—a process that apparently hasn’t gone smoothly.

> Northwestern University interim president Henry Bienen told The Daily Northwestern in an Oct. 17 interview that “a negotiation really requires two parties, at least, and at the present time, there’s not been anybody on the other end of the line.”

> As the freeze persists, Northwestern has said it will continue to support researchers’ “essential funding needs” at least through the end of the calendar year. Bienen told the student newspaper that supporting the research costs $30 million to $40 million a month.

> Cornell University is also in talks with the administration to find a solution to the freeze. However, President Michael Kotlikoff recently shared new information about the impact of the freeze that calls into question the Trump administration’s figures.

> Trump officials told media outlets in April that they froze more than $1 billion at Cornell. But Kotlikoff said last week in his State of the University address that Cornell is actually facing about $250 million in canceled or unpaid research funds. (The university’s research expenditures totaled $1.6 billion in the 2023–24 academic year.)

> ... Bloomberg reported that the White House wanted to reach a $100 million settlement with Cornell. ... “I want to be clear that there are established procedures in place for the government to handle such concerns,” he [Cornell President] said in his State of the University address. “Accusations of discrimination should be supported by, and adjudicated on the basis of, facts. This has not happened.”

> The administration has also said it froze about $108 million at Duke University, but neither Duke nor the National Institutes of Health responded to Inside Higher Ed’s request for an update.

* TCU Moves Race, Gender Studies Departments to English


[https://www.insidehighered.com/news/faculty-issues/curriculum/2025/10/31/tcu-moves-race-gender-studies-departments-english](https://www.insidehighered.com/news/faculty-issues/curriculum/2025/10/31/tcu-moves-race-gender-studies-departments-english)

> On June 1, Texas Christian University will close its stand-alone gender studies and race and ethnic studies departments and fold the majors and courses into the English Department, university leaders announced earlier this month.

> In a meeting with English Department faculty on Oct. 22, TCU provost Floyd Wormley cited financial reasons for the change, asserting that political pressure “had no influence” on the decision to merge the Women and Gender Studies and Comparative Race and Ethnic Studies Departments into the English Department. But some faculty aren’t convinced.

## Court cases

## The long game

## Op eds

## How best to describe the times we are in

* NYTimes: The Thread Tying Together Everything Trump Does

[https://www.nytimes.com/2025/10/26/opinion/trump-foreign-policy.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/10/26/opinion/trump-foreign-policy.html?smid=nytcore-ios-share&referringSource=articleShare)

> For Mr. Trump, the common thread weaving together so much of what he does — at home and abroad — is power. Whether he is seeking a cease-fire in Gaza or Ukraine, bombing boats off the coast of Venezuela or deploying troops to American cities, the desired result is his personal aggrandizement and the empowerment of his presidency. When he pursues peace, it is personalized — a deal made with other strongmen rarely addresses underlying causes of conflict. When he makes war, it is also personalized — there is no expectation, for instance, that Congress must authorize his actions.

> Over the past several months, events overseas have served as pretexts for power grabs within the United States. The Trump administration has used the war in Gaza as an excuse to crush free speech for pro-Palestinian protesters and compel certain universities to submit to federal dictates. Before the first boat was blown out of the water, the administration was deporting immigrants, citing the 1798 Alien Enemies Act — the justification being that we were being invaded by the Venezuelan gang Tren de Aragua, a group few Americans could name before it became omnipresent on Fox News. When Americans protested those deportation policies, Mr. Trump deployed the military to American cities to restore “order.”

> ... Ultimately, this is not peace — it is a world without the rules established after World War II to prevent a return of the lethal mix of authoritarianism and aggression that is once again ascendant. That kind of world can seem orderly for a time. On a particular day, it might even appear more peaceful. But history shows that when might makes right, things go terribly wrong.



## Blowback

* Europeans Fear Trump-Style Attacks on Higher Ed Will Spread

[https://www.insidehighered.com/news/government/2025/10/30/europeans-fear-trump-style-attacks-higher-ed-will-spread](https://www.insidehighered.com/news/government/2025/10/30/europeans-fear-trump-style-attacks-higher-ed-will-spread)

> The attacks on universities by the Trump administration have proven that higher education has “enemies” among authoritarian populist leaders and left other sectors wondering when they will be next, European leaders warn.

> Michael Ignatieff, who was rector of the Central European University between 2016 and 2021, when the institution was expelled from Viktor Orbán’s Hungary, said the Hungarian prime minister had provided enormous inspiration to politicians around the world.

> Speaking at the Going Global conference, Ignatieff, also a former opposition leader in Canada, said Orbán was “the master” who had learned that controlling the universities that recruit and train elites means they can eventually control the political system.

> “We’re in a political battle. We cannot assume that the higher education sector in any of our countries is secure going forward. If the higher education sector can be attacked in the United States, let me tell you folks, it can be attacked anywhere,” he added.

> “This sector has enemies. The American experience has shattered my confidence that the sector that I’ve spent my entire life in is safe.”


## Coming attractions?

* Loan Forgiveness Becomes Tool for Authoritarianism (opinion)

[https://www.insidehighered.com/opinion/views/2025/10/30/loan-forgiveness-becomes-tool-authoritarianism-opinion](https://www.insidehighered.com/opinion/views/2025/10/30/loan-forgiveness-becomes-tool-authoritarianism-opinion)

> By now, it’s obvious that the Trump administration’s efforts to expand Immigration and Customs Enforcement activities go far beyond enforcing federal immigration policy. The near-daily stories of inhumane detainment conditions, open violence against citizens and noncitizens alike, wanton civil rights violations, and purposeful shielding of these abuses from any form of public accountability lay bare that President Trump is now using ICE as a key component for advancing his administration’s hateful agenda.

> This context is essential to evaluate why the administration has sung such a different tune with the advertised $60,000 student loan forgiveness offers to new ICE recruits, compared to the normal song and dance about how higher education is evil incarnate. Trump and his political allies didn’t suddenly discover the societal benefits of affordable education, as evidenced by his simultaneous efforts to strip loan forgiveness pathways from those who are deemed obstructors to Trump’s political goals. What’s clear is that federal student loan forgiveness is now a poverty draft, coercing increased ICE and military enlistment from among those experiencing economic desperation.

> Weaponizing educational debt to fuel armed forces conscription from lower-income individuals is essentially socioeconomic hostage taking....

## Higher Education as a Public Good

## Tracking projects

## AI misdeeds

* NYTimes: Big Tech Makes Cal State Its A.I. Training Ground

[https://www.nytimes.com/2025/10/26/technology/cal-state-ai-amazon-openai.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/10/26/technology/cal-state-ai-amazon-openai.html?smid=nytcore-ios-share&referringSource=articleShare)

> Cal State, the largest U.S. university system with 460,000 students, recently embarked on a public-private campaign — with corporate titans including Amazon, OpenAI and Nvidia — to position the school as the nation’s “first and largest A.I.-empowered” university. One central goal is to make generative A.I. tools, which can produce humanlike texts and images, available across the school’s 22 campuses. Cal State also wants to embed chatbots in teaching and learning, and prepare students for “increasingly A.I.-driven” careers.

> As part of the effort, the university is paying OpenAI $16.9 million to provide ChatGPT Edu, the company’s tool for schools, to more than half a million students and staff — which OpenAI heralded as the world’s largest rollout of ChatGPT to date. Cal State also set up an A.I. committee, whose members include representatives from a dozen large tech companies, to help identify the skills California employers need and improve students’ career opportunities.

* NYTimes: Why Even Basic A.I. Use Is So Bad for Students

[https://www.nytimes.com/2025/10/29/opinion/ai-students-thinking-school-reading.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/10/29/opinion/ai-students-thinking-school-reading.html?smid=nytcore-ios-share&referringSource=articleShare)

(Meanwhile, a faculty viewpoint may resonate more)

> Last spring, it became clear to me that over half the students in my large general education lecture course had used artificial intelligence tools, contrary to my explicit policy, to write their final take-home exams. (Ironically, the course was titled Contemporary Moral Problems: The Value of Human Life.) I had asked them about some very recent work in philosophy, parts of which happened to share titles with entirely different ideas in medieval theology. You can guess which topics the students ended up “writing” about.

> To leave our students to their own devices — which is to say, to the devices of A.I. companies — is to deprive them of indispensable opportunities to develop their linguistic mastery, and with it their most elementary powers of thought. This means they will lack the means to understand the world they live in or navigate it effectively.

> As students’ A.I. use has proliferated, many of its critics focused on intellectual gifts. “A.I. undermines the human value of attention,” the poet Meghan O’Rourke wrote in a guest essay for Times Opinion, “and the individuality that flows from that.” Other endangered powers: “unique human expression,” “the slow deliberation of critical thinking” and the “ability to write original and interesting sentences.” As a humanities professor, all these concerns resonate with me.

> Higher education aims to create cognitively mature adults, which in turn requires us to ensure students learn to read, think and write all on their own. It is easier than we think: Creating tech-free spaces and incentivizing students to spend time in them requires no new resources. All it takes is will. Many of our students still have it. Do their teachers?

* NYTimes: Their Professors Caught Them Cheating. They Used A.I. to Apologize.

[https://www.nytimes.com/2025/10/29/us/university-illinois-students-cheating-ai.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/10/29/us/university-illinois-students-cheating-ai.html?smid=nytcore-ios-share&referringSource=articleShare)

(It can't be more clear than their lede:)

> Two professors at the University of Illinois Urbana-Champaign said they grew suspicious after receiving identical apologies from dozens of students they had accused of academic dishonesty.

* Academic Libraries Embrace AI

[https://www.insidehighered.com/news/quick-takes/2025/10/31/academic-libraries-embrace-ai](https://www.insidehighered.com/news/quick-takes/2025/10/31/academic-libraries-embrace-ai)

> Libraries worldwide are exploring or ramping up their use of artificial intelligence, according to a new report by Clarivate, a global information services company.

> The report, released Thursday, based its findings on a survey of over 2,000 librarians across 109 countries and regions. Most respondents, 77 percent, worked at academic libraries. The survey found that 67 percent of libraries were exploring or implementing AI this year, up from 63 percent last year; 35 percent were still in the evaluation stage.

(Somehow I find this all a bit hard to believe, except for this:)
DOE
> However, AI adoption, and optimism, varied by region. For example, U.S. libraries lagged in AI implementation, and only 7 percent of librarians surveyed said they felt optimistic about it;


## And just because it is fun

* Why More Colleges Should Focus on Knitting

[https://www.insidehighered.com/opinion/career-advice/teaching/2023/04/19/teaching-students-handwork-knitting-offers-many-benefits](https://www.insidehighered.com/opinion/career-advice/teaching/2023/04/19/teaching-students-handwork-knitting-offers-many-benefits)

> Why do I find knitting so relevant to my teaching? Because learning is so much more than learning skills and acquiring knowledge. It is also about the rote practice that gets learning into your muscles and brain; it is about making mistakes and fixing mistakes; it is about apprenticeship and becoming a member of a community. When thinking about knitting, learning is not just acquiring the knowledge and skills that knitters have; it is equally about taking on the identity of a knitter.

> Knitters know, for example, that if they try to learn too far out of what is their next step, it will probably miss the mark. They know that they learn particular skills, practice them and usually learn more quickly and effectively in both in-person and virtual knitting communities. Specifically, they know that they learn well by literally sitting next to one another, watching and trying and practicing—and sometimes having someone hold their hands through the moves.



----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
