# Sep 26

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

Thanks JC and BE for contributions this week.

Quote of the week:

>  the Trump administration isn’t your garden-variety conservative. The attacks they have unleashed on higher education are of historic proportion. What they’re putting on the table resembles an extinction event for the sector. So we have to fight for the survival of higher education. [AAUP President]

## Protests

* NO KINGS in New York City 10/18 12-2

[https://www.mobilize.us/nokings/event/838831/](https://www.mobilize.us/nokings/event/838831/)

## Zoom calls

* Scholars at Risk US Mid-Atlantic Regional Conference

[https://www.scholarsatrisk.org/event/sar-us-midatlantic-conference/](https://www.scholarsatrisk.org/event/sar-us-midatlantic-conference/)

(Thanks BE for sharing)

> The event, titled “Working Together to Protect Scholars and Promote Academic Freedom,” will feature SAR programming on both local and global responses to pressures on academic freedom. The meeting will offer networking opportunities, reflections on responses to attacks on higher education in both the US and worldwide, the launch of SAR’s Free to Think 2025 report, and most notably, the launch of SAR’s 25th Anniversary year themed “Truth Matters.”

## How best to describe the times we are in

* NYTimes: The Trump Vengeance Tour Is Coming to a Stadium Near You

[https://www.nytimes.com/2025/09/23/opinion/media-trump-ellison-murdoch-kirk.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/23/opinion/media-trump-ellison-murdoch-kirk.html?smid=nytcore-ios-share&referringSource=articleShare)

(Not so much about higher education, but a recommended read.)

> “Donald Trump’s goal,” Larry Diamond, a fellow at Stanford’s Hoover Institution, wrote by email, "is to create a Hungarian-style pseudo-democracy, in which he and his movement can rule indefinitely through unfree and unfair elections and utter dominance of the media and civil society landscapes, while still claiming that they are the democratic embodiment of the 'will of the people.'”

> "Everything Trump has been doing of late follows that authoritarian playbook of trying to eviscerate checks and balances, eliminate independent oversight actors, and use state power to punish and terrify critics, so they will self-censor. He is even going after the same philanthropy — the Open Society Foundations — that Orban went after."

> Trump’s favorability ratings have fallen from 50.5 percent during his first week in office this year to 46.1 percent on Sept. 22, but that has not deterred him. Just the opposite: Trump, his vice president, his aides and his cabinet members initiate daily attacks on the left, some illegal, some unfounded, but all damaging and costly.

> Trump’s actions, Westwood [a political scientist at Dartmouth] wrote, “are now escalating into a direct assault on the institutional infrastructure of the left.” However, Westwood continued. “this is more than a rhetorical move; threatening the 501(c)(3) status of these foundations aims to choke off the financial lifeblood of a vast network of opposition groups, effectively criminalizing dissent.”

> Goldstone [professor of public policy at George Mason]: We are now a country in which people can lose their jobs for making the wrong joke; where universities, media, and law firms have to defend themselves against lawsuits and investigations that threaten to bankrupt them; where people in America (even American citizens) can be rounded up, arrested, and put in detention if they have the wrong accent or work at the wrong kind of job, and where masked ICE agents and uniformed national military patrol the streets of our major cities.

## Shared governance

* On Title VI, Discrimination, and Academic Freedom

[https://www.aaup.org/reports-publications/aaup-policies-reports/topical-reports/title-vi-discrimination-and-academic?link_id=1&can_id=7972d9c8790a906a068fba11ce31c6a1&source=email-new-report-on-title-vi-out-today&email_referrer=email_2898804&email_subject=new-report-on-title-vi-out-today&&](https://www.aaup.org/reports-publications/aaup-policies-reports/topical-reports/title-vi-discrimination-and-academic?link_id=1&can_id=7972d9c8790a906a068fba11ce31c6a1&source=email-new-report-on-title-vi-out-today&email_referrer=email_2898804&email_subject=new-report-on-title-vi-out-today&&)

(Thank ET for sharing this most necessary critique of the current abuse of Title VI evaluation. This is a long, worthwhile read that I hope to summarize in blog format. For now, here are a few of the recommendations.)

> 1. Faculties, administrations, and governing boards must refuse to comply with unlawful federal government demands based on Title VI investigations that impinge on institutional autonomy, faculty academic freedom (including the faculty’s role in governance), student academic freedom, and freedom of expression of faculty members, students, and staff.

> 2. Administrations and governing boards must publicly affirm their commitment to defending academic freedom—defined as the protection of teaching, research, and intramural and extramural speech—and support faculty members under attack.

> 3. Administrations and governing boards must respect the importance of faculty involvement in shared governance processes when creating or changing institutional policies and in determining responses to governmental demands for information or institutional actions. They must entertain faculty resolutions that protect unpopular teaching and research as well as controversial speech and forms of expressive activity.

> 5. Faculties, administrations, and governing boards must not engage in anticipatory obedience, including by eliminating programs; scrubbing websites; removing particular words or phrases from syllabi, course materials, and course titles and descriptions; or reporting on community members—faculty members, staff, or students— whose political speech or intellectual work may make them targets for governmental discipline or deportation. Pressure from politicians, donors, and trustees must be resisted because it creates a slippery slope for other forms of censorship and control.

(Also)

 https://www.insidehighered.com/news/quick-takes/2025/09/23/aaup-accuses-trump-weaponizing-civil-rights-law


* Is the AAUP Too Partisan? Its President Doesn’t Think So.

[https://www.chronicle.com/article/is-the-aaup-too-partisan-its-president-doesnt-think-so](https://www.chronicle.com/article/is-the-aaup-too-partisan-its-president-doesnt-think-so)

> “We’re taking it to the courts and the streets — and we need you.” So reads the subject line of an April email from the American Association of University Professors, authored by its president, Todd Wolfson.

> The sentence encapsulates the 110-year-old membership organization’s approach to the second Trump presidency. It has filed lawsuits challenging the administration’s aggressive higher-ed agenda — most recently to contest what it called the “attempt to unlawfully stifle free speech” within the University of California system. Wolfson has advocated for a vigorous defense of the sector, saying in a recent interview that (nonviolent) “militant job actions” may be necessary.

> Before the presidential election, Wolfson, who is on leave from his job as an associate professor of journalism and media studies at Rutgers University’s New Brunswick campus, called then-vice presidential candidate JD Vance a “fascist” — a judgment he’s not backed away from since.

> The courts are an important place to try to stop the Trump administration’s attempt to illegally refashion higher education to mirror, or at least lean towards, the ideological leanings of the Trump administration, which I would say are radically right-wing leanings. We do not think that lawsuits are enough, but they’re one critical tool.

> The next ruling we expect is the AAUP v. [Secretary of State Marco] Rubio ruling. Our hope is that it will be really clear that people like President Trump or Secretary of State Rubio will not be allowed to threaten deportation because of the political speech of students or faculty or staff. That lawsuit is meant to protect the freedom of speech of people in our sector.

> First and foremost, they [general decline in public trust] exist because people like Ron DeSantis [Florida’s Republican governor] and Chris Rufo, [a right-wing anti-DEI activist], have been speaking very loudly, unfairly disparaging higher education for a very long time, without the appropriate response from higher-education workers, higher-education institutions. We’ve heard a message from a radical right-wing regime that is attempting to smear higher education, and doing a good job of it. So of course if they are over and over putting out a negative message about higher ed, then people are going to consume that message, and there hasn’t been a response to that message that’s been effective.

> We’re an economic engine. We’re a health-care engine. We’re a technological-innovation engine. And there’s one more thing that I really think is important to remind ourselves of: Kids go to college so that they can get a job and imagine that they’re going to do a little bit better than their parents. Skyrocketing tuition and skyrocketing student debt have made it so that higher education is a difficult choice for students. AAUP believes that public higher education should be free, and so we want to fight for that. We have plenty of money to do that. We have plenty of billionaires who now are becoming trillionaires that can help us pay for this, if the most wealthy are taxed a bit more.

> No, I don’t think ‘progressive.’ What AAUP defines itself as is an organization that believes that higher education should be a common public good for everyone. We align ourselves with the vast majority of Americans of any political stripe who need education for their kids, their families, in order to move forward in this country.

> First and foremost, the Trump administration isn’t your garden-variety conservative. The attacks they have unleashed on higher education are of historic proportion. What they’re putting on the table resembles an extinction event for the sector. So we have to fight for the survival of higher education.

> So you’re saying to me AAUP is partisan, because the Trump administration is slapping higher ed and we’re standing up and fighting back? No. No. We are standing for what we always stood for, which is a powerful higher-education sector that leads to innovation and social mobility and is a bedrock of democracy.

> It’s them — the radical right wing — that is politicizing higher ed. We will not shrink from that. If people have a problem with that, then they can get in line with Trump and Chris Rufo, and that’s fine. But we are gonna stand up for our institutions, and we are gonna be proud and loud about it.

> The AAUP has a very clear agenda. We are going to fight over the budget right now and try to get fully funded NIH [National Institutes of Health], NSF [National Science Foundation], NASA [National Aeronautics and Space Administration]. We are going to fight to make sure that the TRIO program, which supports first-generation college kids, is fully enshrined in this budget. ... Then we are going to pivot from there and put out a proactive vision for the future of higher education.


## Academic freedom

* Angelo State May Ban Pride Flags, Pronouns and Preferred Names

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/09/24/angelo-state-reportedly-banning-pride-flags](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/09/24/angelo-state-reportedly-banning-pride-flags)

> Employees at Angelo State University in Texas could be fired for displaying a pride flag or discussing any topic that suggests there are more gender identities than male and female.

> Spokespeople for Angelo State have not confirmed or denied details of the policies reportedly discussed at meetings Monday between faculty, staff and institutional leaders. But, local news magazine the Concho Observer reported that the policies would ban discussion of transgender topics or any topics that suggest there are more than two genders.

(Also, which says this is a done deal)

[https://www.chronicle.com/article/a-public-university-in-texas-bans-discussion-of-transgender-topics-in-class](https://www.chronicle.com/article/a-public-university-in-texas-bans-discussion-of-transgender-topics-in-class)

* Angelo State Allows LGBQ Discussions, Holds Firm on Anti-Trans Policies

[https://www.insidehighered.com/news/quick-takes/2025/09/25/angelo-state-allows-pride-flags-keeps-anti-trans-policies](https://www.insidehighered.com/news/quick-takes/2025/09/25/angelo-state-allows-pride-flags-keeps-anti-trans-policies)

> As of Monday, conversations and content about transgender identities are still prohibited, but employees are allowed to use students’ preferred names, display rainbow flags in their offices and on their cars, and talk about lesbian, gay, bisexual and queer identities, according to emails from department heads to faculty obtained by Inside Higher Ed.

> None of the policies are formalized in writing, and that is purposeful, said Brian Evans, president of the Texas Conference of the American Association of University Professors. The guidance only changed after faculty brought up questions about the policies, which deans took back to the provost and university counsel. Final details about what is and is not allowed and how the rules will be enforced are still under discussion.


## Freedom of expression

* Conservative are targeting speech. More teachers may lose their jobs. - The Washington Post

[https://www.washingtonpost.com/education/2025/09/20/conservatives-target-teachers-free-speech/](https://www.washingtonpost.com/education/2025/09/20/conservatives-target-teachers-free-speech/)

> A day after a video of the exchange began circulating [Texas A&M Children's Literature class], the instructor was fired, the department head and dean were removed from their posts, and the Justice Department said it would look into the matter. Ten days later, as cries from the right continued to echo across the internet, the university president said he was resigning, bringing the tenure of a retired four-star general to an unexpected and abrupt halt.

> Now the state lawmaker who led the campaign against them says he’s being inundated with tips about what he characterized as offensive efforts to indoctrinate students. “This is just the start,” Texas state Rep. Brian Harrison, a conservative firebrand, told The Washington Post. “I hope this puts the fear of God into every university president and chancellor in Texas.”

> Over the past several years, conservatives have focused on reshaping teachings of race, gender identity and sexual orientation, leading to a spate of state laws regulating what educators can say and to the firing of a number of teachers. That campaign mushroomed this month as conservatives pushed to oust people they say have gone too far in criticizing Charlie Kirk, the conservative activist who was fatally shot at Utah Valley University last week.

> So far, the Texas Education Agency has received 281 complaints about teacher comments in the wake of Kirk’s killing, with staff still reviewing them, spokeswoman Jake Kobersky said Friday. He said the agency had not yet punished any of these teachers, though some districts have acted and the state might step in as well.

> Randi Weingarten, president of the American Federation of Teachers, said she sees no end in sight to the scrutiny of teachers’ speech. Kirk’s killing was horrible, she said, but does not justify going after teachers who have a diversity of opinions.

* NYTimes: The Firing of Educators Over Kirk Comments Follows a Familiar Playbook

[https://www.nytimes.com/2025/09/22/us/firing-educators-kirk-free-speech.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/22/us/firing-educators-kirk-free-speech.html?smid=nytcore-ios-share&referringSource=articleShare)

(With background on Brooklyn College's non-reappointment of four adjunct faculty members for "conduct")

> The American Association of University Professors, an organization founded to defend academic freedom, said it was aware of retaliation against about 60 professors and teachers in connection with critical comments they made about Mr. Kirk or people mourning him.

> Faculty First Responders, an organization that works with the association to advise educators who are the victim of doxxing and harassment campaigns, has reached out to 35 academic workers in the past week, most of them professors, whose comments about Mr. Kirk have been spread in right-wing media, according to Heather Steffen, the group’s director.

> The Texas Education Agency has said it is investigating hundreds of employees at elementary or secondary schools for similar reasons.

> If they choose to mount a legal fight, fired employees of public institutions, which are bound by the First Amendment, probably have better chances of prevailing in court than those fired from private institutions.

> Proponents of academic freedom see the current crackdown on professors as an assault on freedom of expression that echoes dark periods in American history. At Brooklyn College, where four adjunct professors were dismissed this year for their pro-Palestinian activism, a faculty union called the movement to curb educators’ speech the “New McCarthyism.”

> One of the four, Corinna Mullin, who was an adjunct professor of political science, said that recent developments show that academic freedom is not a universal right but a conditional privilege.

> “And it seems that it’s granted or withdrawn based on the context of our speech — those who echo power are shielded,” said Dr. Mullin, who was arrested during a police raid on a Gaza Solidarity encampment at City College in 2024. Trespassing charges against her were later dropped.

> She said she believed that activists on the right will continue to expand their attacks to take in “all speech on the left associated with social justice, racial justice, all these uncomfortable truths that challenge power in this country.”

> In several instances, Mr. Kirk has used the First Amendment to sue universities that tried to block his organization’s campus presence.

> But critics have argued that Mr. Kirk’s promotion of free speech was riddled with hypocrisy. Matthew Boedy, a professor at the University of North Georgia who has written a book that focuses heavily on Mr. Kirk, “The Seven Mountains Mandate,” called Mr. Kirk’s stance “an empty support of free speech.”

* Professor in court fight over Charlie Kirk post is temporarily reinstated

[https://www.washingtonpost.com/nation/2025/09/25/charlie-kirk-shooting-professor-south-dakota/](https://www.washingtonpost.com/nation/2025/09/25/charlie-kirk-shooting-professor-south-dakota/)

> A federal court on Wednesday temporarily reinstated a University of South Dakota professor [a tenured art professor that described Kirk on facebook as a “hate spreading Nazi.” ]who was put on administrative leave after making negative comments on social media about Charlie Kirk on the same day that the conservative activist was shot.

(Also)

[https://www.insidehighered.com/news/quick-takes/2025/09/26/court-order-reinstates-sd-prof-fired-kirk-comments](https://www.insidehighered.com/news/quick-takes/2025/09/26/court-order-reinstates-sd-prof-fired-kirk-comments)

### Anti-woke/anti-DEI is simply racism

* NYTimes Gift Article: The Grand Strategy Behind Trump’s Crackdown on Academia

[https://www.nytimes.com/2025/09/25/opinion/trump-academia-victim-may-mailman.html?unlocked_article_code=1.ok8.sM5c.tGhv1r82oHx-&smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/25/opinion/trump-academia-victim-may-mailman.html?unlocked_article_code=1.ok8.sM5c.tGhv1r82oHx-&smid=nytcore-ios-share&referringSource=articleShare)

(hard-to-get-through interview with Mary Mailman the right hand person behind Stephen Miller's attempted assault on higher education, though the interviewer, Ross Douhat, doesn't bother to bring that up...)

> Douthat: What is wrong with the American university? Mailman: I don’t think it’s every university, but I would say the biggest one that comes for me is a culture of victimhood — a glorification of victimhood — that is ultimately bad for Western civilization and bad for the country.

> Mailman: It’s not necessarily that they are victims but that they should be victims. That it’s good to be a victim. That in admissions, what is it better to be? It’s better to be in a minority class, whether that’s a sexual minority class, whether that’s a racial minority class. There’s something better to being underrepresented, to being somehow downtrodden, that should be treated as preferential or better.

> but the whole idea of treating people differently based on whether they are oppressed or oppressors, and if it’s seen as Meghan Markle — why does she want to appear like a victim?

> Mailman: Yeah, there is an executive order that discusses universities. Specifically, Title VI says that for any federally funded educational institution, they can’t discriminate on the basis of race or national origin. This has been used both on the antisemitism front, which is national origin and race, and then also on what people broadly describe as the D.E.I. front. And so if you’re going to be federally funded, then we’re going to make sure that you don’t discriminate on the basis of race.

> Douthat: Pause there for a moment. First of all, how did you pick which schools you sent letters to?

> Mailman: So I think we primarily relied on the Department of Education to pick what they either knew, based on complaints that have been received, and you had House investigations. A lot of this information was public, here and there. It was in government databases. Some of them are just very out loud, like the U.C. system. So I think there was some flag waving by certain universities.

> Douthat: I mean, also, the federal government doesn’t actually have the power to shut down Harvard University.

> Mailman: No, but in theory —

> Douthat: But you can defund Harvard.

> Mailman: Right. And what’s Harvard’s special thing? It is that it’s, in theory, a leader, and the question is: A leader in what direction?

> Mailman: Right, and that’s always an option. If anybody thinks that any of this is too burdensome, especially very well-funded universities, then just do none of it. Just be Hillsdale. And it’s funny, because for research — I mean, people don’t really understand the massive amount of money that goes to research. It’s billions and billions. Harvard right now has something like $7 billion of promised grants. These are huge, huge numbers. But if all of the research was good, something that was going to cure cancer, then a donor would love to fund that. I mean, to be the person that cured cancer?

> The problem is not whether the government should or shouldn’t be funding cancer research — it absolutely should — but the unwieldiness of it has led to basically an unchecked situation. I think it is actually proper to have a right sizing, where universities are relying on the federal government to a certain extent, where these are things that are maybe not close to a breakthrough and that there is an opportunity for the private sector to spend money in ways that are beneficial to society.

> Mailman: Wealthy people funding universities, funding science, funding our future is something that has history in this country.

> So I think there’s a recognition. It’s all — of course, there’s no recognition of fault. These are settlements. But by paying some of this back, I think there is, somewhat for the public, a sense of acknowledgment of wrongdoing. Not a legal sense but sort of a moral sense

(Really, not sure that is how the payee feels)

> Not only that, but to the extent you have universities that are just hotbeds of radicalism, that’s not good for the student. That’s not good for the culture. That’s not good for the campus. That’s bad for the country. So that is all true. And I think the administration believes that intellectual diversity is a key factor to a good university that we would send our kids to.

> Douthat: I think that’s right, just based on my own experience living in a college town and speaking to people who work in higher education. There is some degree, first, to which the Trump administration is pushing on an open door and also some degree to which leaders of universities are happy to say, “Oh, we didn’t want to do this, but the Trump administration made us do it,” but in fact, it’s something that they themselves want to do.

(I could keep going here, but the whole interview is just too much, though I can't resist adding this)

> Mailman: It’s not a full comparison of all universities across the nation. But at the end of the day, Harvard reacted to a letter that asked for a few simple changes with a lawsuit that basically said: Instead of us showing any amount of good faith effort to commit ourselves to the policies that are important to the United States, we’re going to instead say we refuse to even answer you. These are billions of federal dollars, and I think that the funder of that can ask for a basic relationship.

## Visas

* Are CUNY visa applicants being told no?

Reports from one CC are that of 192 new international student admissions 92 were denied.

* Trump administration to add $100,000 fee for H-1B visas - CBS News

[https://www.cbsnews.com/news/trump-h1b-visa-bill-100000-fee/](https://www.cbsnews.com/news/trump-h1b-visa-bill-100000-fee/)

(This is hopefully going to be found illegal, because otherwise it will *seriously* impact faculty hiring.)

> The Trump administration is adding $100,000 to the existing fee for H-1B visa applications, taking aim at a program that is used to attract highly skilled workers to the U.S.

> President Trump signed an executive order late Friday adding the new visa application fee and barring H-1B workers from entering the U.S. unless they had made the $100,000 payment.

(Also)

[https://www.nytimes.com/2025/09/19/us/politics/trump-h-1b-visas-fee.html](https://www.nytimes.com/2025/09/19/us/politics/trump-h-1b-visas-fee.html)

[https://www.chronicle.com/article/what-trumps-100-000-fee-for-skilled-worker-visas-could-mean-for-higher-ed](https://www.chronicle.com/article/what-trumps-100-000-fee-for-skilled-worker-visas-could-mean-for-higher-ed)

* International-student enrollment is sagging at many U.S. universities, particularly at the master’s level

[https://www.wsj.com/us-news/education/international-student-enrollment-decline-college-ad13f943?st=FSLVfk&reflink=article_gmail_share](https://www.wsj.com/us-news/education/international-student-enrollment-decline-college-ad13f943?st=FSLVfk&reflink=article_gmail_share)

> International-student enrollment is sagging at many universities, particularly at the master’s level. School officials cite the Trump administration’s summer pause on visa appointments followed by increased scrutiny of applicants, along with other policies aimed at shrinking the number of international students. Some say shifts in the technology job market are also decreasing demand abroad for certain graduate programs.

> The U.S. enrolled a record 1.1 million international students in 2023-24—who contributed $43.8 billion to the U.S. economy through tuition, food and living expenses, according to NAFSA: Association of International Educators.

> “I feel I’m now in the middle of nowhere,” said Elham Shamiri, an Iranian citizen who has been trying to obtain a visa to start a Ph.D. program in chemistry at the University of Vermont. She and hundreds of other Iranians have been asking politicians to carve out an exception for students with admissions offers. “We have nothing to do with politics,” Shamiri said, and shouldn’t be conflated with terrorism. “We are just students truly committed to research.”

(Also)

[https://www.insidehighered.com/news/global/international-students-us/2025/09/23/international-enrollment-down-small-regional](https://www.insidehighered.com/news/global/international-students-us/2025/09/23/international-enrollment-down-small-regional)


### NSF

* Under Trump, NSF faces worst crisis in its 75-year history | Science | AAAS

[https://www.science.org/content/article/under-trump-nsf-faces-worst-crisis-its-75-year-history](https://www.science.org/content/article/under-trump-nsf-faces-worst-crisis-its-75-year-history)

> The White House has ordered the $9 billion agency to abandon long-running programs, terminate more than 2000 grants, and reverse decisions on what to fund next based on the administration’s political agenda, which excludes diversity, equity, and inclusion (DEI) efforts and climate change research. NSF is also making radical changes in its daily operations, including sharply reducing its reliance on top academic scientists on loan from their institutions and realigning the agency’s entire grantmaking apparatus to conform to Trump’s priorities (see sidebar, below).

> Many science policy experts say those changes move NSF away from its founding principles, laid out in a 1945 report to then-President Harry Truman, to maintain U.S. leadership in science by funding the best ideas across all fields and training the next generation of researchers. That compares with the more targeted missions of most government agencies, such as advancing energy, health, or space exploration. But both of NSF’s goals, as put forward by Vannevar Bush in his seminal report that led to NSF’s creation in 1950, have lost support under Trump.

> “This administration doesn’t buy the idea that the government’s investment in basic research buys us anything useful,” one former senior NSF official says. “And if they don’t agree with Bush’s assumption, then why bother to even have an NSF?”

> Keivan Stassun, who was named to NSB in January 2023, sees DOGE operating as the ultimate decision-maker at NSF, in tandem with the White House Office of Management and Budget. And OMB, he says, has discarded NSF’s well-regarded system of choosing the most worthy proposals. “If OMB is using anything like NSF’s merit review criteria,” says Stassun, an astrophysicist at Vanderbilt University, “that has not been communicated and is certainly not apparent to me.”

> For more than 4 decades, NSF has supported a network of institutes that bring together top mathematicians and rising stars for in-person workshops to explore a range of hot topics and spark new areas of research. “The math institutes are the crown jewels of our portfolio,” says mathematician Juan Meza, former director of NSF’s math division, which spends roughly 15% of its annual budget on the network. “They support the entire mathematical community.”

> The Institute for Pure and Applied Mathematics (IPAM) at the University of California Los Angeles (UCLA) has been part of that network since 2000 and is known for bridging the gap between academia and industry by working on problems that appeal to both theoretical and applied mathematicians. ... On 27 July, NSF issued an embargoed press release announcing it would fund seven institutes in the network, including IPAM, which would get another $17 million over the next 5 years. But when the news became public a week later, IPAM wasn’t on the list.

(Read the article for other specific examples of cuts ... AI ... water and oil.)


### NIH

* NYTimes: ‘The Power of Science to Solve Problems Is Almost Limitless’

[https://www.nytimes.com/2025/09/22/opinion/jay-bhattacharya-nih.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/22/opinion/jay-bhattacharya-nih.html?smid=nytcore-ios-share&referringSource=articleShare)

(A sane washing of the NIH director's comments)


## Federal Agencies

### DOE/OCR

* The Ed Department Hasn’t Even Begun to Fight (opinion)

[https://www.insidehighered.com/opinion/views/2025/09/22/ed-department-hasnt-even-begun-fight-opinion](https://www.insidehighered.com/opinion/views/2025/09/22/ed-department-hasnt-even-begun-fight-opinion)

> Despite high-profile federal actions against universities like Columbia University; the University of California, Los Angeles; and others over the past few months, many higher ed watchers, including me, have been waiting for the other shoe to drop. While civil rights investigations, demands for massive settlements, cuts to grant funding and threats to institutional accreditation have led to real-world consequences, no institution has lost access to federal student loans.

> But—as Friday’s announcement that Harvard University had been placed on heightened cash monitoring status shows—that could change quickly. And regulatory actions by the previous administration increase the likelihood of the Trump administration’s success if they choose to flex the powers provided to them.

> Biden’s regulatory changes were significant. For example, the regulations expanded the department’s interpretation of standards around an institution’s administrative capability to participate in the federal student loan program. If not satisfied to the department’s liking, these regulations grant the agency the power to kick colleges out of the loan program or make continued participation financially impossible.

> The department also has the power to conduct an invasive review of an institution’s administrative capability if it determines that the college was subject to a “significant negative action” by another federal or state agency. Notably, the Biden administration did not provide a meaningful definition of what constitutes a “significant negative action.” Arguably, even the pulling of a single federal grant, for any reason, would satisfy this provision.

> And this is just the beginning. Other changes to institutional financial standards create more ways for McMahon to turn the screws. This includes a minimum requirement of a 10 percent letter of credit—that is, a demand that colleges convince a private lender to back 10 percent of the total amount of federal student aid funds received by the institution each year—if the department merely suspects certain violations. Additional violations compound the required amounts, and there is no cap on what the agency can demand.

> While some colleges may be able to weather this fiscal hit, the vast majority would not. As a result, the Education Department can effectively destroy a college by making it impossible to find enough backup funding to survive.

> Why did the Biden administration create such a powerful set of tools? Their target was for-profit colleges, and they hardly expected that their regulatory overreach would land in the hands of a second Trump administration that would come out swinging against traditional public and private institutions.

> So, what can colleges do about this?

> For investigations based upon past events, institutions should prepare protocols for responding to government inquiries and strengthen their records-retention processes and procurement procedures.

> To insulate a college from future actions, reviewing internal compliance standards and procedures in light of these new regulations, as well as updating staff training, can help avoid some painful headaches.

> Over the past decade, the department has successfully closed colleges down based upon far weaker versions of the current regulations. Today, colleges that get crosswise with the Trump administration should prepare for an assault on their student loan eligibility, because it may be coming.

* ED Wants Grants to Advance “Patriotic Education”

[https://www.insidehighered.com/news/government/politics-elections/2025/09/19/ed-wants-grants-advance-patriotic-education](https://www.insidehighered.com/news/government/politics-elections/2025/09/19/ed-wants-grants-advance-patriotic-education)

> Last week, Education Secretary Linda McMahon outlined a new plan for how her department would promote “patriotic education” by adding it to the list of priorities that can drive decisions for discretionary grants, including those that support programs at colleges and universities.

> “It is imperative to promote an education system that teaches future generations honestly about America’s Founding principles, political institutions, and rich history,” McMahon said in a statement about the new proposal. “To truly understand American values, the tireless work it has taken to live up to them, and this country’s exceptional place in world history is the best way to inspire an informed patriotism and love of country.”

> McMahon’s other priorities for grant funding include evidence-based literacy, expanding education choice, returning education to the states and advancing AI in education.

### HHS

* The Other Office for Civil Rights

[https://www.insidehighered.com/news/diversity/2025/09/24/hhs-civil-rights-arm-joins-trumps-higher-ed-crackdown](https://www.insidehighered.com/news/diversity/2025/09/24/hhs-civil-rights-arm-joins-trumps-higher-ed-crackdown)

> In June, in an escalation of the Trump administration’s pressure on Harvard University to bow to its demands, a federal Office for Civil Rights announced that the institution was violating federal law.

> The office released a nearly 60-page report accusing Harvard of “deliberate indifference” to ongoing discrimination against Jewish and Israeli students, which is illegal under Title VI of the Civil Rights Act of 1964. “OCR’s findings document that a hostile environment existed, and continues to exist, at Harvard,” the office said in an accompanying news release.

> But this wasn’t the Education Department’s Office for Civil Rights. It was an office of the same name within the Health and Human Services Department that’s been playing a more public role as part of Trump’s crackdown on higher ed. Officials who served in previous administrations said agencies used to generally defer to the Education Department when it came to civil rights issues in higher ed. But since Trump retook office, colleges and universities are facing increased pressure from probes by HHS and other agencies enforcing the new administration’s right-wing interpretation of civil rights.

> For universities, Trump’s HHS OCR represents a new threat to their funding if they’re accused of promoting diversity, equity and inclusion; fostering antisemitism; or letting transgender women play on women’s sports teams.

> “As we feared, the Trump administration is abusing civil rights tools to advance a radical and divisive agenda that aggressively hoards access to education, living wage jobs, and so much more,” the NAACP Legal Defense Fund said in a statement. “Unfortunately, HHS and many other federal agencies are being used as one of the vehicles to carry out that agenda.”

> "There are 13 federal agencies with external civil rights enforcement, of which HHS is one, and it’s relatively large.” [former director of the Education Department’s OCR ] ... “The administration has used every agency in a contemporaneous, simultaneous assault on universities,” ... “It’s unnecessary to do what the administration is doing now, unless one is operating like a mob boss,”

(After listing several examples the article ends with)

> Lhamon, the former Education Department OCR head, said what the administration has called civil rights investigations into Harvard, Columbia and other universities aren’t really investigations. She noted the administration has used a “mob theory” by going ahead and pulling HHS and other funding from multiple institutions before the investigations are over.

> Instead, she said, this is “an assault on universities, which is a very different thing from ensuring compliance with the civil rights laws as Congress has enacted them.”


## Institutional assaults

### Admissions

* Why Did College Board End Best Admissions Product? (opinion)

[https://www.insidehighered.com/opinion/views/2025/09/22/why-did-college-board-end-best-admissions-product-opinion](https://www.insidehighered.com/opinion/views/2025/09/22/why-did-college-board-end-best-admissions-product-opinion)

> Earlier this month, College Board announced its decision to kill Landscape, a race-neutral tool that allowed admissions readers to better understand a student’s context for opportunity. After an awkward 2019 rollout as the “Adversity Score,” Landscape gradually gained traction in many selective admissions offices. Among other items, the dashboard provided information on the applicant’s high school, including the economic makeup of their high school class, participation trends for Advanced Placement courses and the school’s percentile SAT scores, as well as information about the local community.

> If College Board was worried that somehow people were using the tool as a proxy for race (and they weren’t), well, it wasn’t a very good one. In the most comprehensive study of Landscape being used on the ground, researchers found that it didn’t do anything to increase racial/ethnic diversity in admissions. Things are different when it comes to economic diversity. Use of Landscape is linked with a boost in the likelihood of admission for low-income students. As such, it was a helpful tool given the continued underrepresentation of low-income students at selective institutions.

> While race and class are correlated, they certainly aren’t interchangeable. Admissions officers weren’t using Landscape as a proxy for race; they were using it to compare a student’s SAT score or AP course load to those of their high school classmates. Ivy League institutions that have gone back to requiring SAT/ACT scores have stressed the importance of evaluating test scores in the student’s high school context. Eliminating Landscape makes it harder to do so.


### Harvard

* NYTimes: Harvard’s Former President Criticizes Its Approach to Trump

[https://www.nytimes.com/2025/09/19/us/harvard-claudine-gay-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/19/us/harvard-claudine-gay-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

> Harvard’s former president, Claudine Gay, offered a blunt assessment of the university’s current administration this month, criticizing it for complying with demands from the Trump White House.

> “The posture of the institution seems to be one of compliance,” Dr. Gay said in an address on Sept. 3, first reported in The Harvard Crimson, the student newspaper, on Friday. “This is distressing, not only for those of us who are on campus and facing the consequences directly, but also for all of those in higher ed who look to Harvard for leadership and guidance.”

> “The number of $500 million is arbitrary, and it will solve nothing,” Dr. Gay said. “There is no justification.”

* NYTimes: Trump Officials Question Harvard’s Stability, Saying Federal Inquiries Raise Financial Risk

[https://www.nytimes.com/2025/09/19/us/politics/trump-harvard-financial-risk.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/19/us/politics/trump-harvard-financial-risk.html?smid=nytcore-ios-share&referringSource=articleShare)

(This can't be a serious request, almost any single building alone is worth more than the 36M reported.)

> The Trump administration on Friday opened a new front in its pressure campaign on Harvard University, demanding proof of the financial stability of the nation’s oldest and wealthiest college as well as a guarantee that federal debts will be paid if the school “closes or terminates classes.”

> Still, the administration is insisting on a guarantee of more than $36 million, representing about 30 percent of the federal financial aid that has flowed to the university during the past year, because of financial risks posed by more than a dozen government investigations targeting the university.

> The aggressive actions from the Trump admini stration come as negotiations between Harvard and the White House have stalled over a landmark settlement that would restore the university’s research funding and resolve the multitude of federal investigations aimed at addressing a perceived liberal bias on campus.

> The letter from the student aid office also said Harvard’s sale of $750 million in bonds in April, layoffs of staff over the summer and a salary freeze initiated this year “call into question the ability of Harvard to meet its financial responsibility obligations.”

(Also)

[https://www.insidehighered.com/news/government/student-aid-policy/2025/09/19/education-dept-subjects-harvard-more-financial](https://www.insidehighered.com/news/government/student-aid-policy/2025/09/19/education-dept-subjects-harvard-more-financial)

[https://www.chronicle.com/blogs/the-trump-agenda/trump-administration-turns-up-heat-on-harvard-with-financial-lever](https://www.chronicle.com/blogs/the-trump-agenda/trump-administration-turns-up-heat-on-harvard-with-financial-lever)

* ED Gives Harvard 20 Days to Provide Admissions Info

[https://www.insidehighered.com/news/quick-takes/2025/09/23/ed-gives-harvard-20-days-provide-admissions-info](https://www.insidehighered.com/news/quick-takes/2025/09/23/ed-gives-harvard-20-days-provide-admissions-info)

> The Department of Education’s Office for Civil Rights said Friday that it issued a letter giving Harvard University 20 days to submit documents related to admissions that it says the university has been refusing to provide.

> “Despite OCR’s repeated requests for data, Harvard has refused to provide the requested information necessary for OCR to make a compliance determination,” the office continued, adding that the university will “face further enforcement action” if the information is not provided.

### Texas A&M

* ‘Heartbreaking’ and ‘Cruel’: A Texas State Professor on His Firing and Why He’s Suing

[https://www.chronicle.com/article/heartbreaking-and-cruel-a-texas-state-professor-on-his-firing-and-why-hes-suing](https://www.chronicle.com/article/heartbreaking-and-cruel-a-texas-state-professor-on-his-firing-and-why-hes-suing)

> Alter, an associate professor of history at Texas State University, was perplexed. He knew remarks he had made at a conference three days earlier about a hypothetical “overthrow” of the U.S. government, documented on the internet, had provoked an online campaign against him, but the last time he checked, the posts had received very little attention.

> This stunning turnaround time is at the core of Alter’s lawsuit against the university, which he filed Tuesday and shared with The Chronicle. In Alter’s telling, he was fired “without an ounce of due process,” a loaded term in the American judicial system but one that carries an added weight for someone of Alter’s status: He was tenured — as of 10 days before his firing.

> When he began his remarks on that Sunday, Alter introduced himself by name and by his membership with Socialist Horizon, one of the groups organizing the conference, and his union, the Texas State Employees Union. Alter told The Chronicle said he was “very conscious” not to identify himself as a Texas State professor, and while a participant identified Alter’s employment as part of an “innocuous conversation” about how many teachers Texas State educates, Alter would probably have been just another participant had it not been for Borysenko.

> An online influencer who calls herself an “anti-communist fascist leading the revolution against the revolution,” Borysenko recorded Alter’s remarks in full. The next day, September 8, she uploaded several videos across social media, including YouTube and X, with pointed captions identifying Alter and her interpretation of his remarks.

* Partisan Fury Got Him a Presidency. And Then It Took Him Down.

[https://www.chronicle.com/article/partisan-fury-got-him-a-presidency-and-then-it-took-him-down](https://www.chronicle.com/article/partisan-fury-got-him-a-presidency-and-then-it-took-him-down)

> Welsh was hastily named A&M’s interim president in 2023 after the proposed hiring of a new journalism director, Kathleen O. McElroy, infuriated conservatives who saw her as a champion of the kinds of diversity programs that, in Texas, were already on the outs. Replacing M. Katherine Banks, who had resigned the A&M presidency over the McElroy ordeal, Welsh faced a politically tricky task: making himself both palatable to conservatives, who were skeptical of creeping liberalism at A&M, and acceptable to beleaguered university faculty, who felt academic freedom was under threat. For a while, at least, Welsh seemed to pull it off.

> In recent days, however, Welsh’s juggling act fell apart. In trying to appease both conservatives and faculty, he managed to satisfy neither. The politics that engulfed Welsh are indicative of a larger national trend, in which college leaders are struggling — to varying degrees — to uphold fundamental values of institutional autonomy and academic freedom in the face of a broad conservative effort to reshape higher education. Very few, it seems, are striking a balance that pleases either side.

> This [several dismissals] still was not enough. Harrison continued to make media appearances and post about the events, often tagging the Republican Gov. Greg Abbott, and the Texas A&M University System chancellor, Glenn Hegar. Abbott-appointed regents, Harrison wrote, were “pushing transgender indoctrination on students.” The state’s lieutenant governor, Dan Patrick, said last week that Welsh “did not handle the recent situation … as he should have,” but said his fate should be left up to the regents.

> It was the regents, along with Hegar, who announced Thursday that Welsh would resign. But it was Harrison [Republican state elected] who took the credit, telling The Texas Tribune that his social-media posts hastened Welsh’s resignation. Swift action like this, Harrison told the outlet, is what “I firmly believe Texans want.”

### West Point

* Professor sues West Point, says the academy is restricting free speech | AP News

[https://apnews.com/article/west-point-lawsuit-first-amendment-professor-a4db138011c6fb9c8b445ce5a106aac2](https://apnews.com/article/west-point-lawsuit-first-amendment-professor-a4db138011c6fb9c8b445ce5a106aac2)

> The U.S. Military Academy at West Point is banning opinions by professors in the classroom and some books and courses in a crackdown that violates the First Amendment, a law professor at the military school said in a lawsuit Monday seeking class action status.

> Bakken also noted in the lawsuit that he has a contract with a publisher for a book that is critical of some aspects of West Point and doesn’t want to seek approval from the school’s leadership prior to its publication because “it is very likely such approval will be withheld.”

> Bakken’s lawsuit said the school began to scrutinize faculty speech after a January executive order from President Donald Trump to “carefully review the leadership, curriculum and instructors of the United States Service Academies and other defense academic institutions.”

> The lawsuit said the academy in the spring withdrew books from its library, removed words and phrases from faculty members’ syllabi, eliminated courses and majors and threatened or punished faculty members for teaching, speaking and writing without prior approval from the school.

> During the summer, the academy removed information about faculty members’ published books, articles, essays and scholarship entries from all faculty members’ webpages on the school’s website, the lawsuit said. It also directed instructors not to express opinions in the classroom, it said.

### UCLA

* Federal judge orders Trump to restore $500 million in frozen UCLA medical research grants - Los Angeles Times

[https://www.latimes.com/california/story/2025-09-22/rita-lin-federal-judge-restores-ucla-nih-grants](https://www.latimes.com/california/story/2025-09-22/rita-lin-federal-judge-restores-ucla-nih-grants)

> A federal judge Monday ordered the Trump administration to restore $500 million in UCLA medical research grants, halting for now a nearly two-month funding crisis that UC leaders said threatened the future of the nation’s premier public university system.

> Lin’s order provides the biggest relief to UCLA but affects federal funding awarded to all 10 UC campuses. Lin ruled that the NIH grants were suspended by form letters that were unspecific to the research, a likely violation of the Administrative Procedure Act, which regulates executive branch rulemaking.

> In addition to the medical grant freezes — which had prompted talks of possible UCLA layoffs or closures of labs conducting cancer and stroke research, among other studies — Lin said the government would have to restore millions of dollars in Department of Defense and Department of Transportation grants to UC schools.

> Lin explained her thinking during a hearing last week. She said the Trump administration committed a “fundamental sin” in its “un-reasoned mass terminations” of grants using “letters that don’t go through the required factors that the agency is supposed to consider.”

> Erwin Chemerinsky, dean of the UC Berkeley law school, worked with Polsky and argued the case in front of Lin.

(Also)

[https://www.chronicle.com/blogs/the-trump-agenda/500-million-in-grant-funding-should-be-restored-to-uc-system-judge-rules](https://www.chronicle.com/blogs/the-trump-agenda/500-million-in-grant-funding-should-be-restored-to-uc-system-judge-rules)

[https://www.insidehighered.com/news/quick-takes/2025/09/24/judge-restores-another-batch-frozen-grants-ucla](https://www.insidehighered.com/news/quick-takes/2025/09/24/judge-restores-another-batch-frozen-grants-ucla)

### George Washington University

* The Campus With a Front-Row Seat to Trump’s Attack on Higher Ed

[https://www.chronicle.com/article/the-campus-with-a-front-row-seat-to-trumps-attack-on-higher-ed](https://www.chronicle.com/article/the-campus-with-a-front-row-seat-to-trumps-attack-on-higher-ed)

> The influx of officers and troops can leave the impression of a campus under siege, an impression also reinforced by less visible interactions. The day after President Trump announced the deployment of the National Guard in Washington, GW received a letter from the Justice Department announcing it had found the campus administration responsible for “deliberate indifference” to the “hostile environment” for Jewish, American-Israeli, and Israeli students and faculty.

> A week after the DOJ letter [Department of Justice’s “deliberate indifference” letter in August] was published, the GW student socialist organization released its own demands, co-signed by 45 student organizations, and posted an open letter about them. The six demands include banning all external law enforcement from campus, refusing compliance and capitulation with the Trump administration, and calling for the university to publicly declare its support for free speech. The demands also call for more communication and guidelines from the university regarding interacting with ICE and immigration authorities.


## Blowback

* U.K. Weighs Streamlining Visa Process for Researchers

[https://www.insidehighered.com/news/global/2025/09/26/uk-weighs-streamlining-visa-process-researchers](https://www.insidehighered.com/news/global/2025/09/26/uk-weighs-streamlining-visa-process-researchers)

> The U.K. is reportedly considering removing fees for its global talent visa in response. The Campaign for Science and Engineering (CaSE) warned that high visa costs are already a significant barrier but said it is not the only change that needs to be made.

## Higher Education as a Public Good

* Colleges have had a tough year. Confidence in them is rising.

[https://www.washingtonpost.com/education/2025/09/24/college-confidence-poll-politics-higher-education/](https://www.washingtonpost.com/education/2025/09/24/college-confidence-poll-politics-higher-education/)

> But a national poll [Vanderbilt Unity Poll], released Wednesday signals a shift [increase in confidence]: Nearly half of respondents said they had “a great deal” or “quite a lot” of confidence in higher education. Nearly 80 percent said that a college education is very or somewhat important for a young person to succeed.

> That question, like others, reflected a split along party lines, with 87 percent of Democrats and 68 percent of Republicans expressing that a college education has some importance for success.

> The real divide was expressed by the 20 percent of respondents who said they identify with President Donald Trump’s “Make America Great Again” movement.


| Group | no confidence | some confidence | confidence |
|:-----:|:-------------:|:---------------:|:----------:|
| MAGA  |     31        |      45         |     24     |
| Dems  |     21        |      10         |     69     |
| Indies|     18        |      37         |     45     |


## And just because it is fun

* NYTimes: Eric Adams, Donald Trump and the Case That Broke American Justice

[https://www.nytimes.com/2025/09/20/opinion/trump-eric-adams-corruption.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/20/opinion/trump-eric-adams-corruption.html?smid=nytcore-ios-share&referringSource=articleShare)

(Not fun but is very informative about reported corruption in our own backyard.)

> The purported corruption ran from the grand scale of global politics to the most parochial, penny-ante payoffs. Ingrid Lewis-Martin, a former top aide whom Mr. Adams describes as his “sister,” was indicted on money laundering and bribery charges for allegedly calling in favors in exchange for a bit part in an MGM+ streaming show and cash that her son used to buy a new Porsche.

> And it swept up almost every department in Mr. Adams’s administration — especially, and most importantly, the New York Police Department. The culture of impunity described in dozens of lawsuits, indictments and whistle-blower complaints was so widespread that one of the mayor’s own former police commissioners sued him for enforcing what the commissioner characterized as a culture of “lawlessness.”

> Mr. Adams, a former police captain, has called himself the department’s “overbearing dad.” He installed his former cop friends at the top levels of the department and of his administration generally. Many of them padded out their entourages and gave their buddies cushy assignments and huge overtime payouts.

> She responded with a shocking accusation in a complaint to the U.S. Equal Employment Opportunity Commission: Her boss, the chief of department, Jeff Maddrey, had pressured her into serving that overtime with him at 1 Police Plaza, where he repeatedly sexually abused her. “I keep saying, ‘stop, stop, stop, stop, stop.’ And he just kept on,” the lieutenant, a 19-year veteran of the force and a mother of three, recalled, heaving with tears, in a televised interview last March. “This guy is a monster.” She said Chief Maddrey, a friend and an ally of Mr. Adams’s for more than 20 years, demanded a kickback from the overtime pay and even told her to pay for a vacation for him and his wife.

>  After the lieutenant came forward with her accusations, nude videos of her circulated on police group chats. Then the Police Department tried to claw back the overtime money that her predator boss allegedly coerced her into taking.

* “I’m a former creationist. Here’s why ‘follow the science’ failed. The moment I finally admitted that Darwin was right didn’t feel liberating. It felt like grief.”

[https://www.washingtonpost.com/opinions/2025/09/22/muslim-missionary-evolutionary-biologist-human/](https://www.washingtonpost.com/opinions/2025/09/22/muslim-missionary-evolutionary-biologist-human/)

(Thanks BE!)

> As an 18-year-old Muslim missionary, I enrolled at University College London intent on destroying the theory of evolution. I arrived on a mission: I wanted to prove that Charles Darwin was wrong. Like so many other creationists, I believed scientists were either lying to us or they were so biased that they were unknowingly misreading the data. The only way to dismantle their theory was to inspect the data for myself and prove it wrong.

> Two decades later, I am an evolutionary biologist. Working on a documentary about our species’ 300,000-year-old story made me reflect on my own evolution — and how, when you ask people to do something simple such as “believe the science,” you might actually be asking them to pay an almost unimaginable price.

> By and large, we share the opinions of our tribe. So when we ask people to believe in climate modeling or vaccine science, what we are really asking people to do is choose between their community’s beliefs and an abstract dataset. It’s a direct referendum on the people they know and love. Most people will not betray their tribe for a stranger in a lab coat.

> In biological terms, this is an extremely rational predisposition — or, put another way, it’s human nature. And it’s the main reason simply shouting “trust the science” will never truly change people’s minds.

> In many ways, I traded a warm religious community for a cold and often selfish secular world.

> Understanding these dynamics can illuminate the current quagmire of science and politics. When people of faith and political conservatives see their views mocked, dismissed or ostracized, they begin to see science not as a method but as a tribe they’re not a part of. And once science becomes just another tribe, its authority collapses.

> In the 13 years since I left my missionary world, many Muslims have embraced evolution. That progress didn’t come from outsiders or even nonpracticing Muslims like me; it came from scholars, thinkers and activists who argued for the compatibility of Islam and evolution. It is why we must tolerate religious and, for that matter, right-wing viewpoints more. Not only is more robust science achieved when all biases are represented, but the perception of left-wing atheists having a monopoly on science is a disaster. The best ambassadors to skeptical communities are people from within those communities.

> Evolution is the underlying assumption of biology; nothing in the field makes sense without it. It should trouble us that so many people still reject it. Paradigm shifts are possible, although parting with the beliefs of one’s tribe is an enormous decision. Empathy for that hesitation, not scorn for it, is the way forward.



----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
