# Sep 5

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

Quote of the week: "difficult to conclude anything other than that defendants used antisemitism as a smokescreen for a targeted, ideologically-motivated assault on this country’s premier universities."

Thanks to EI, ET, BE, JC, VAC for sharing things this week!


## Alliances

* The CUNY Alliance to Defend Higher Education

[https://cadhe.commons.gc.cuny.edu/](https://cadhe.commons.gc.cuny.edu/)

(Thank EI for posting to the listserv)

> CADHE is a coalition of CUNY faculty and staff formed from a broader campaign to create a Mutual Academic Defense Compact (MADC) between CUNY, SUNY, and other universities. Membership is open to all CUNY faculty and staff who support its mission.

> CADHE aims to:

> * Establish a NY State MADC: Promote collaboration between CUNY and SUNY to defend against political attacks.

> *Counter misinformation: Share accurate narratives about CUNY’s role, history, and campus environments.

> *Engage with government: Work with city, regional, and state officials to strengthen public higher education.

> * Promote public education: Advocate for its importance to New York’s economy, culture, and democracy.

> * Collaborate nationally: Partner with unions, academic bodies, and student organizations defending higher education.

> * Address antisemitism misuse: Oppose its weaponization as a political tool to undermine universities.

> * Protect academic freedom: Defend faculty and staff from delegitimization efforts, upholding free expression.


* It’s Not a ‘Mutual-Defense Compact.’ But a New Ad From 18 Universities Aims to Send a Message.

[https://www.chronicle.com/article/its-not-a-mutual-defense-compact-but-a-new-ad-from-18-universities-aims-to-send-a-message](https://www.chronicle.com/article/its-not-a-mutual-defense-compact-but-a-new-ad-from-18-universities-aims-to-send-a-message)

> Now the 18 universities in the Big Ten, which represent both an athletic conference and an academic alliance, have collaborated on an advertisement defending higher ed that will air during college football games. The 30-second spot blends a healthy dose of agrarian charm and shots of high-tech laboratories, highlighting the universities’ contributions to research, health care, and their communities.

> In the same week that the new ad was announced, the chancellor of the University of Illinois at Urbana-Champaign acknowledged that reality in an interview with Illinois Public Media. “I am assuming that we will eventually find ourselves a target, as is everyone in higher ed,” said Charles L. Isbell Jr.

> Though the joint ad has been in the works for a while, Martin said he — along with representatives from Ohio State University, Illinois, and the Association of American Universities — formally pitched the idea during a May meeting of the Big Ten’s presidents and chancellors. Martin and several colleagues worked on the ad through the Big Ten Academic Alliance, a collaboration unit that’s funded by each member university’s provost.

> “The chancellors and presidents were so supportive that they asked for two more spots,” Martin said.

## Zoom calls

* Webinar to share details about the services offered and provide legal updates and resources for he CUNY Immigration Assistance Program

[https://ybephbsyus.formstack.com/forms/cuny_immigration_assistance_program_september2025_webinar](https://ybephbsyus.formstack.com/forms/cuny_immigration_assistance_program_september2025_webinar)

(Thanks JC for sending out on the listserv)

(Also)

[https://www.cuny.edu/about/administration/offices/communications-marketing/immigrationresourcesandinformation/cuny-immigration-assistance-project-ciap/](https://www.cuny.edu/about/administration/offices/communications-marketing/immigrationresourcesandinformation/cuny-immigration-assistance-project-ciap/)

## How best to describe the times we are in

* NYTimes: Trump Wants to Drown Us in a Sea of Chaos

[https://www.nytimes.com/2025/09/02/opinion/trump-winning-imperial-presidency.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/02/opinion/trump-winning-imperial-presidency.html?smid=nytcore-ios-share&referringSource=articleShare)

> Universities retreat under pressure, law firms submit to extortion, scientific and medical research funding has been decimated, federal employees face ideological purges, tariffs are imposed as political weapons, the military has become a domestic police force and the administration is demanding that cultural institutions mute or even eliminate criticism of the worst aspects of America’s past.

> It is an asymmetric struggle without precedent in American political history, creating a predicament for all those opposed to a president who acts without regard to law, constitutional limits or congressional authorization, who disdains due process, prosecutes political adversaries and weaponizes regulatory agencies to attack the media, academia, the legal profession and liberal democracy itself.

> While Trump thrives on the wreckage he leaves in his wake, he is guided by Russell Vought, head of the Office of Management and Budget, and Stephen Miller, the White House deputy chief of staff for policy and homeland security adviser. Vought and Miller are coldblooded, ideologically driven strategists who have spent nearly a decade developing the foundations for this MAGA takeover of what was once a familiar American way of life.

> I wrote to Bob Bauer, a professor of practice at N.Y.U. law school and a Democratic expert in the structuring and financing of political organizations, asking for his views on the strategic options available to opponents of the MAGA agenda.

> He replied by email, arguing that “there is an urgent opposition to be mounted and effectively articulated.”

> Mittelstadt [historian of 20th-century America at Rutgers] said she spoke at the Aug. 14-15 conference on Liberalism for the 21st Century sponsored by the Institute for the Study of Modern Authoritarianism, where many participants supported a strategy of “Never Trumpers, liberals, libertarians all agreeing on a lowest common denominator of a rules-based order of some kind and fighting on that basis. While most on the center or left would, of course, endorse a rules-based order, I’m not certain it will capture the imagination of people who can’t pay for college or find a place to live affordably.”


* The Battle for “Viewpoint Diversity”

[https://www.insidehighered.com/news/faculty-issues/curriculum/2025/09/02/battle-viewpoint-diversity](https://www.insidehighered.com/news/faculty-issues/curriculum/2025/09/02/battle-viewpoint-diversity)

> Now the White House is fueling their push, demanding viewpoint diversity under threat of huge funding cuts. Some say universities need to reform themselves to regain public and governmental support.

> To take one example of conservatives forcing change, Indiana Republicans last year passed Senate Enrolled Act 202, which threatens the jobs of even tenured faculty at public universities who don’t foster intellectual diversity.

> The Trump administration has also wielded intellectual diversity as a weapon in its demands of some of the nation’s wealthiest universities. In a letter to Harvard in April, government officials said that in order to get its federal research funding restored, the university must, among other things, employ a federally approved external party to “audit the student body, faculty, staff, and leadership for viewpoint diversity.” It didn’t define the term.

> State legislators tasked West Virginia University’s new Washington Center for Civics, Culture and Statesmanship with expanding “intellectual diversity,” offering “programming related to the values of open inquiry and civil discourse” and enriching the curriculum with the “great debates of western civilization.” Iowa’s Legislature created a “center for intellectual freedom” at the University of Iowa, ordering it to offer “civil discourse” programming and expand “intellectual diversity.” Similarly, Utah’s Legislature created a civic center at Utah State University committed to “viewpoint diversity and civil discourse” and mandated that all general ed courses be taught by faculty appointed to that center by its director.

> “Intellectual diversity works one way, and it always works in the way of conservative thought,” said Isaac Kamola, director of the American Association of University Professors’ Center for the Defense of Academic Freedom and an associate political science professor at Trinity College in Connecticut. Those who say they favor intellectual diversity never say, “We need Marx in the business school,” he added.

* Despots at Home and Abroad Want to Silence Our Campuses

[https://www.chronicle.com/article/despots-at-home-and-abroad-want-to-silence-our-campuses](https://www.chronicle.com/article/despots-at-home-and-abroad-want-to-silence-our-campuses)

> It’s a dangerous time to be an international student in the United States. Writing an op-ed in a student newspaper. Joining a campus protest. Even just posting on social media. Legal and protected speech now puts international students at risk of deportation if the Trump administration doesn’t like what they have to say.

> Foreign students studying in the United States with the dream of walking at commencement now instead risk the nightmare of being dragged by masked agents into an unmarked van, all because they engaged in the same speech their citizen classmates are free to voice without punishment or consequence.

### Anti-woke/anti-DEI is simply racism

* In Trump’s Federal Work Force Cuts, Black Women Are Among the Hardest Hit - The New York Times

[https://www.nytimes.com/2025/08/31/us/politics/trump-federal-work-force-black-women.html](https://www.nytimes.com/2025/08/31/us/politics/trump-federal-work-force-black-women.html)

> While tens of thousands of employees have lost their jobs in Mr. Trump’s slash-and-burn approach to shrinking the federal work force, experts say the cuts disproportionately affect Black employees — and Black women in particular. Black women make up 12 percent of the federal work force, nearly double their share of the labor force overall.

> The most recent labor statistics show that nationwide, Black women lost 319,000 jobs in the public and private sectors between February and July of this year, the only major female demographic to experience significant job losses during this five-month period, according to an analysis by Katica Roy, a gender economist.

* Senator Who Banned DEI Set to Be Texas Tech Chancellor

[https://www.insidehighered.com/news/government/politics-elections/2025/09/03/senator-who-banned-dei-set-be-texas-tech-chancellor](https://www.insidehighered.com/news/government/politics-elections/2025/09/03/senator-who-banned-dei-set-be-texas-tech-chancellor)

> Following pro-Palestinian protests and a police crackdown on an encampment at the University of Texas at Austin in 2024, the Texas Legislature this year passed another law restricting free speech on public campuses, including banning all expressive activities from 10 p.m. to 8 a.m.

> The Legislature also this year passed a wide-ranging bill that allows public college and university presidents to take over faculty senates and councils, prohibits faculty elected to those bodies from serving more than two years in a row, and creates an “ombudsman” position that can threaten universities’ funding if they don’t follow that law or the DEI ban.

> The lead author listed on all three laws is Sen. Brandon Creighton, chair of the Texas Senate education committee. Having overhauled higher ed statewide, he’s about to get the chance to further his vision at one large university system: On Thursday, the Texas Tech University System named Creighton the system chancellor and chief executive officer job.

* Clemson Ends Several Faculty and Staff Affinity Commissions

[https://www.insidehighered.com/news/quick-takes/2025/09/04/clemson-ends-several-faculty-and-staff-affinity-commissions](https://www.insidehighered.com/news/quick-takes/2025/09/04/clemson-ends-several-faculty-and-staff-affinity-commissions)

> The now-sunsetted groups included the Accessibility Commission, the Asian Pacific Islander DESI American Commission, the Commission on the Black Experience, the Commission on Latino Affairs, the LGBTQ Commission, the Veterans Commission and the Commission on Women, according to the Internet Archive.

> The right-wing think tank the Heritage Foundation, in a report released Tuesday, listed the Clemson commissions as an example of ways that universities and K–12 schools are continuing “DEI activities” following Trump’s crackdown on diversity, equity and inclusion programs, officers and personnel.


* NYTimes: College Board Cancels Tool for Finding Low-Income High Achievers

[https://www.nytimes.com/2025/09/04/us/college-board-diversity-landscape.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/04/us/college-board-diversity-landscape.html?smid=nytcore-ios-share&referringSource=articleShare)

> When the Supreme Court banned affirmative action in college admissions in 2023, many universities began looking more closely at socioeconomic status to admit more diverse classes without considering race.

> Scores of schools turned to a tool created by the College Board, which administers the SAT exam, to identify promising high school students from disadvantaged neighborhoods and schools.

> This week, the College Board quietly notified schools that it was eliminating the tool, called Landscape. The board provided little explanation for its decision.

(Also)

[https://www.nytimes.com/2025/09/05/opinion/math-dei.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/05/opinion/math-dei.html?smid=nytcore-ios-share&referringSource=articleShare)

> NYTimes: What I Got Wrong About D.E.I---As my career has advanced, what I’ve learned is that D.E.I. initiatives helped others see value in my abilities and experience that would have been missed otherwise.



## Visas

NYTimes: Trump Administration Targets Financial Relief for Undocumented Students

[https://www.nytimes.com/2025/09/04/us/politics/trump-tuition-undocumented-students.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/04/us/politics/trump-tuition-undocumented-students.html?smid=nytcore-ios-share&referringSource=articleShare)

> Although her tuition previously cost about $5,000 a semester and was covered entirely by state [Texas] financial aid, Berenice said her tuition costs jumped to $21,000 this semester.

> The challenge against Texas was one of several efforts by the Trump administration to clamp down on programs that provide financial relief for undocumented students. After the Justice Department filed a complaint against Texas, it challenged similar policies in Kentucky, Minnesota and Oklahoma. On Tuesday, the department also filed a complaint against Illinois for offering in-state tuition and scholarships to unauthorized immigrants.

* DOJ Sues Illinois Over In-State Tuition for Noncitizens

[https://www.insidehighered.com/news/quick-takes/2025/09/04/doj-sues-illinois-over-state-tuition-noncitizens](https://www.insidehighered.com/news/quick-takes/2025/09/04/doj-sues-illinois-over-state-tuition-noncitizens)

> The DOJ filed a complaint in the Southern District of Illinois against the state, Gov. JB Pritzker, the state attorney general and boards of trustees of state universities. The complaint argues that it’s illegal to offer lower tuition rates to undocumented students if out-of-state citizens can’t also benefit.

> Illinois passed a law in 2003 that grants in-state tuition to undocumented students who meet certain criteria. To qualify, students need to reside and attend high school in the state for three years, graduate from an Illinois high school, and sign an affidavit promising to apply to become a permanent resident as soon as possible. Pritzker then signed a bill into law last year that would loosen these criteria, starting in July 2026. Students will be able to pay in-state tuition rates if they meet one of two sets of requirements, including attending an Illinois high school for at least two years or a combination of high school and community college in the state for at least three years.

## Funding cuts

* Range of Reasons for Latest Job and Program Cuts

[https://www.insidehighered.com/news/business/financial-health/2025/09/05/range-factors-spurred-campus-cutbacks-august](https://www.insidehighered.com/news/business/financial-health/2025/09/05/range-factors-spurred-campus-cutbacks-august)

> For some institutions, belt-tightening measures are directly tied to the economic forces battering the sector as a whole: declining enrollments, rising operating costs and broad economic uncertainty. For others, financial pressure from the Trump administration, which has frozen federal research funding at multiple institutions, prompted cuts. State lawmakers have also forced program reductions at some public institutions.

> **Middlebury College:** The private liberal arts college in Vermont is shutting down the Middlebury Institute of International Studies at Monterey, across the country in California, officials announced last week.  Middlebury president Ian Baucom said the university is winding down graduate programs at the campus over a period of two years. Managing such graduate programs was “no longer feasible,” said Baucom, who added that the decision was made for financial reasons.

> **University of New Hampshire** The layoffs are part of an effort to cut $17.5 million from UNH’s budget. University president Elizabeth Chilton also announced other cost-cutting efforts last month, including “scaling back professional development, student employment, building hours, dining hall hours, travel, printing, and other support services.”

> **University of California, Los Angeles** One of the wealthiest institutions on this list, UCLA announced last month that it has temporarily paused faculty hiring and is making other belt-tightening moves. ... The public university’s move comes at least partly in response to its standoff with the Trump administration, which froze hundreds of millions in research funding to the university last month as it pressured administrators over alleged antisemitism on campus. (Some funding has been restored by a court order.) The Trump administration has also demanded a $1 billion payout from the university, which California governor Gavin Newsom called “extortion.”

> **University of Kansas**:  The public university announced last month that it was implementing a temporary hiring freeze as administrators aim to reduce spending by $32 million, The Lawrence Journal-World reported. ... “We are again navigating an uncertain fiscal environment because of external factors, such as disruptions to federal funding, changes in federal law, stagnant state funding, rising costs, changes in international enrollments, and a projected nationwide decline in college enrollment,” KU officials wrote in a message to campus.

(And others)

### NIH

* HHS Lawyer: NIH Shouldn’t Re-Terminate Grants

[https://www.insidehighered.com/news/quick-takes/2025/09/02/hhs-lawyer-nih-shouldnt-re-terminate-grants](https://www.insidehighered.com/news/quick-takes/2025/09/02/hhs-lawyer-nih-shouldnt-re-terminate-grants)

> The National Institutes of Health shouldn’t cut off funding to 900 grants that the agency previously canceled and then had to restore thanks to a June court order, lawyers for the Department of Health and Human Services said last week.

> “For those grants reinstated by NIH in response to the June judgements, we would strongly recommend against re-terminating such grants, because it will likely be viewed as a reapplication of the now-vacated challenged directives,” wrote NIH legal adviser David Lankford.

> Science noted that political appointees at NIH could ignore the legal advice and re-terminate the grants. Additionally, the agency might have more latitude next fiscal year to cut off funding for grants that officials say don’t align with the administration’s priorities.


## Federal Agencies

### DOE/OCR

* How Trump is using civil rights laws to bring schools to heel : NPR

[https://www.npr.org/2025/09/04/nx-s1-5500262/trump-civil-rights-schools-students](https://www.npr.org/2025/09/04/nx-s1-5500262/trump-civil-rights-schools-students)

> The country's federal civil rights laws, written to protect marginalized groups from discrimination, have become an unlikely tool in the Trump administration's efforts to end targeted support for students of color and protections for transgender students.

> "This interpretation [of the law] doesn't bear any relationship to the actual charge of Title IX," says Catherine Lhamon, who oversaw OCR during both the Obama and Biden administrations.

## Congressional actions

* What to Know About House Republicans’ Education Budget

[https://www.insidehighered.com/news/government/student-aid-policy/2025/09/04/what-know-about-house-republicans-education-budget](https://www.insidehighered.com/news/government/student-aid-policy/2025/09/04/what-know-about-house-republicans-education-budget)

> Released Tuesday, the House’s spending plan would cut the Department of Education’s budget by 15 percent. That gives the agency $67 billion, down from $79 billion in fiscal year 2025. Funding for key student aid programs like the Pell Grant and the TRIO college-access initiative would remain stable, but others could face steep cuts or be zeroed out entirely.

> The bill also includes a $456 million cut to the National Institutes of Health, a ban on enforcing certain Biden-era regulations and an attempt to rename the new workforce Pell Grant as the Trump Grant.

(Ha Ha)

> Still, in many ways, House Republicans on the appropriations committee stuck with Trump. Certain grants focused on bolstering teacher preparation, aiding extremely low-income learners, providing childcare to student parents and promoting foreign language instruction would be zeroed out entirely. And other offices like the Education Department’s Office for Civil Rights could lose millions.

### Admissions

* NYTimes: The Excruciating Question Confronting Black College Applicants

[https://www.nytimes.com/2025/09/01/opinion/college-essay-post-affirmative-action.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/01/opinion/college-essay-post-affirmative-action.html?smid=nytcore-ios-share&referringSource=articleShare)

> For striving Black high school seniors, the generalized essay anxiety arrives in a particular, acute form: Should my personal statement address race? The Supreme Court decision two years ago eliminating affirmative action in college admissions fomented considerable uncertainty about the transformed admissions landscape, and the second Trump administration’s recent assaults on higher education have only exacerbated the confusion.

> President Trump, Attorney General Pam Bondi and Education Secretary Linda McMahon have repeatedly brandished the court’s decision, seeking to prohibit universities from considering race in any way whatsoever, even though the opinion plainly requires no such thing.


### Accreditation

* How UNC Led a First-of-Its-Kind Plan to Shake Up College Accreditation

[https://www.chronicle.com/article/how-unc-led-a-first-of-its-kind-plan-to-shake-up-college-accreditation](https://www.chronicle.com/article/how-unc-led-a-first-of-its-kind-plan-to-shake-up-college-accreditation)

(Thanks BE for sharing)

> In July 2024, the UNC system and the American Enterprise Institute, a conservative think tank, convened representatives from Florida, Georgia, Iowa, South Carolina, Tennessee, and Virginia to talk about alternatives to the current model for accreditation, documents show. The UNC system then recommended in a September 2024 report that North Carolina “establish an accreditation agency formed by state university systems.” The report laid out steps that are now the game plan for the new multistate accreditor.

> This spring, Dan Harrison, the UNC system’s vice president for academic affairs, sent a document to the system’s president describing himself and another UNC official, Andrew Kelly, as crucial to shaping how the accreditor would operate. “Currently, we enjoy some free ridership in that Florida is funding the effort, but the group relies on Kelly and Harrison for subject matter expertise,” the document stated. “There have not been major decision points where North Carolina’s preference has not been followed.”

> The tension between DeSantis’s public posturing and North Carolina officials’ influential role behind the scenes underscores a crucial question for many faculty members and other skeptics: whether the new organization will be a non-ideological auditor focused on public universities’ particular needs, as UNC system leaders have pledged, or become a tool for conservatives to remake higher education.

> Under the 1965 Higher Education Act, accreditors must evaluate 10 broadly defined areas in assessing an institution’s quality, such as student achievement, curriculum, faculty, finances, and compliance with federal laws. In the United States, most colleges belong to independent accreditors that used to oversee particular regions. While it is technically a voluntary process, federal financial aid is so crucial to most colleges that accreditation is in practice a requirement.

> Over the years, however, conservative lawmakers and think tanks have increasingly accused accreditors of stepping on institutions’ and states’ toes over governance issues. Critics also argue the bodies force colleges to adopt progressive ideologies. While some large accreditors have diversity, equity, and inclusion standards, the main accreditor for colleges in the South — the Southern Association of Colleges and Schools Commission on Colleges, known as SACS — does not.

> ... Kevin Kinser, an education-policy professor at Pennsylvania State University who studies accreditation, said the draft leaves many questions about how the standards will be evaluated. For example, if “viewpoint diversity” is a standard, he questioned how institutions would prove that they have faculty across the ideological spectrum.


### Harvard

* NYTimes: Harvard Secures a Court Victory in Its Fight With Trump

[https://www.nytimes.com/2025/09/03/us/harvard-trump-funding-ruling.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/03/us/harvard-trump-funding-ruling.html?smid=nytcore-ios-share&referringSource=articleShare)

(Thanks ET and VC for sharing. Not this does not include Mike Schmidt as a co-author as the many articles leaking possibly false details about Harvard imminently settling)

> Harvard University won a crucial legal victory in its clash with the Trump administration on Wednesday, when a federal judge said that the government had broken the law by freezing billions of dollars in research funds in the name of stamping out antisemitism.

> Although the ruling was a milestone for Harvard, the only university to sue over the administration’s targeted assault on its research funding, President Trump had vowed to appeal any decision that went against him. His administration has spent months seeking to pressure Harvard in ways beyond research money, and while Judge Burroughs’s ruling may not put an end to that campaign, her opinion was a bracing rebuke.

> Judge Burroughs wrote on Wednesday that it was “difficult to conclude anything other than that defendants used antisemitism as a smokescreen for a targeted, ideologically-motivated assault on this country’s premier universities.”


(Also)

[https://www.insidehighered.com/news/government/politics-elections/2025/09/03/judge-rules-harvard-funding-freeze-illegal](https://www.insidehighered.com/news/government/politics-elections/2025/09/03/judge-rules-harvard-funding-freeze-illegal)

[https://www.wsj.com/us-news/education/harvard-ruling-trump-court-funding-8cc5026c?st=QwTyoE&reflink=article_gmail_share](https://www.wsj.com/us-news/education/harvard-ruling-trump-court-funding-8cc5026c?st=QwTyoE&reflink=article_gmail_share)


> President Trump said last month that he wants no less than $500 million from Harvard, telling Education Secretary Linda McMahon during a cabinet meeting: “They’ve been very bad. Don’t negotiate.”

(Also Harvard President's email to the community)

> A few hours ago, the US District Court granted Harvard’s motion for summary judgment, finding that the federal government’s freeze of University research funding was unlawful. The ruling affirms Harvard’s First Amendment and procedural rights, and validates our arguments in defense of the University’s academic freedom, critical scientific research, and the core principles of American higher education.

>  Our principles will guide us on the path forward. We will continue to champion open inquiry and the free exchange of ideas, and to build a community in which all can thrive. I look forward to working with you in the months ahead as we join together, with renewed commitment, in the pursuit of excellence in teaching, learning, and research.

* Harvard Got a Big Win. Here Are 4 Key Quotes.

[https://www.chronicle.com/article/harvard-got-a-big-win-here-are-4-key-quotes](https://www.chronicle.com/article/harvard-got-a-big-win-here-are-4-key-quotes)

(Here are the quotes they highlight)

> [The Trump administration] used antisemitism as a smokescreen for a targeted, ideologically-motivated assault on this country’s premier universities.

> The idea that fighting antisemitism is [the Trump administration’s] true aim is belied by the fact that the majority of the demands they are making of Harvard to restore its research funding are directed, on their face, at Harvard’s governance, staffing and hiring practices, and admissions policies, which have … everything to do with [the administration’s] power and political views.

> The idea that fighting antisemitism is [the Trump administration’s] true aim is belied by the fact that the majority of the demands they are making of Harvard to restore its research funding are directed, on their face, at Harvard’s governance, staffing and hiring practices, and admissions policies, which have … everything to do with [the administration’s] power and political views.

> Congress has, however, passed a law that explicitly provides for when and how an agency can terminate federal funding to address this type of discrimination — and that law is Title VI, which dictates that ‘no such action shall be taken until the department or agency’ has gone through the appropriate procedures.

> Consistent with these obligations, this Court (and likely all district courts) endeavors to follow the Supreme Court’s rulings, ‘no matter how misguided [it] may think [them] to be.

### George Mason

* Virginia Democrats Block College Board Appointees, Leaving George Mason’s Without a Quorum

[https://www-chronicle-com.csi.ezproxy.cuny.edu/article/virginia-democrats-block-college-board-appointees-leaving-george-masons-without-a-quorum](https://www-chronicle-com.csi.ezproxy.cuny.edu/article/virginia-democrats-block-college-board-appointees-leaving-george-masons-without-a-quorum)

### Northwestern

* NYTimes: President of Northwestern, a School Attacked by the G.O.P., Will Resign

[https://www.nytimes.com/2025/09/04/us/northwestern-president-resigns.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/04/us/northwestern-president-resigns.html?smid=nytcore-ios-share&referringSource=articleShare)

> The president of Northwestern University, Michael H. Schill, announced Thursday that he would resign, ending a difficult tenure that included attacks on the school from Republicans in Congress and cuts in funding by the Trump administration that forced the university to lay off hundreds of employees.

> Northwestern became a target of Trump administration officials this year after months of intense scrutiny from Republican lawmakers.

> Jewish groups including the Anti-Defamation League and the Brandeis Center have called for Mr. Schill to resign, faulting him for negotiating with the protesters.

> In a message to Northwestern students, employees and alumni that was issued Thursday, Mr. Schill alluded, but only glancingly, to the troubles of the last two years. “Our community has made significant progress while simultaneously facing extraordinary challenges,” he said. “Together, we have made decisions that strengthened the institution and helped safeguard its future.”

> Attacking elite colleges has become central to Mr. Trump’s agenda in his second term.

(And that about sums it up---most all of this is just ginned up)

(Also)

[https://www.chronicle.com/article/northwestern-u-s-president-was-singled-out-by-republican-critics-now-hes-resigning](https://www.chronicle.com/article/northwestern-u-s-president-was-singled-out-by-republican-critics-now-hes-resigning)

[https://www.insidehighered.com/news/governance/executive-leadership/2025/09/04/northwestern-president-step-down](https://www.insidehighered.com/news/governance/executive-leadership/2025/09/04/northwestern-president-step-down)

### Brown

* Brown to Fund Grad Students Who Lost Grants

[https://www.insidehighered.com/news/quick-takes/2025/09/05/brown-fund-grad-students-who-lost-grants](https://www.insidehighered.com/news/quick-takes/2025/09/05/brown-fund-grad-students-who-lost-grants)

> The National Institutes of Health, the National Science Foundation and other federal agencies have terminated thousands [at least 91 at CUNY] of academic researchers’ grants—including many at Brown—that don’t align with the Trump administration’s ideological agenda.

> Blume [interim dean of the graduate school] said Brown is also reducing its graduate student admissions target this year to allow “time to work out issues of the federal financial landscape and also shifts in the job market.”

> Brown University will give money to some of its graduate students whose federal research grants were cut by the Trump administration, The Brown Daily Herald reported.

### Others

* UC sends a warning

[https://www.chronicle.com/article/tracking-trumps-higher-ed-agenda](https://www.chronicle.com/article/tracking-trumps-higher-ed-agenda)

The University of California system’s chancellor told state lawmakers on Wednesday that if the Trump administration cuts federal funding to its 10 campuses, it “would devastate our university.” The system currently receives $17 billion from the federal government each year. Making up the difference, James B. Milliken said in a letter to legislators, could require a $5-billion infusion from the California Legislature.

(Also)

[https://www.insidehighered.com/news/quick-takes/2025/09/05/uc-system-warns-broader-risks-federal-funding-fight](https://www.insidehighered.com/news/quick-takes/2025/09/05/uc-system-warns-broader-risks-federal-funding-fight)

## Blowback

* A Leader of UNC’s Civic Life School Is Fired, Adding to Turmoil

[https://www.chronicle.com/article/a-leader-of-uncs-civic-life-school-is-fired-adding-to-turmoil](https://www.chronicle.com/article/a-leader-of-uncs-civic-life-school-is-fired-adding-to-turmoil)

> The School of Civic Life and Leadership at the University of North Carolina at Chapel Hill — created by trustees and state legislators to offer a more traditional civic education — is experiencing more leadership turnover.

(See, just like in real higher ed)


----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. (They are  now back!!!) I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
