# Sep 12

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.


## Protests

* The Gaza Protests Are Still Haunting College Leaders. A Candid Interview With One President Shows How.

[https://www.chronicle.com/article/the-gaza-protests-are-still-haunting-college-leaders-a-candid-interview-with-one-president-shows-how](https://www.chronicle.com/article/the-gaza-protests-are-still-haunting-college-leaders-a-candid-interview-with-one-president-shows-how)

> As the beginnings of a pro-Palestinian encampment formed on Northwestern University’s Deering Meadow in April 2024, then-President Michael H. Schill faced three choices: let the encampment continue; bring in the campus police to break it up; or negotiate with the student activists.

> But that quickly ran into a snag. Schill was wary of sending in Northwestern’s small police force, so he asked the Evanston Police Department for help. The night they were going to take action, Schill said, “the mayor of Evanston called me and said he would not be sending in the police. I said to him, ‘We have a mutual-aid agreement.’ He said, ‘You know, you can sue me if you want.’”

> So Schill took the third option: negotiation.

> But Schill’s remarks reflect the inescapable fact that the encampments that sprung up a year and a half ago are still haunting college leaders, particularly as Republican lawmakers apply aggressive scrutiny to campuses’ handling of antisemitism.

> In his interview, Schill told the assembled group of investigators and attorneys that negotiating was the only choice he had. “A lot of people find what we did distasteful. A lot of Jewish people in particular find what we did … distasteful,” said Schill, who is Jewish. “I then ask them what they would do. No one has given me — and I’ve had this conversation probably 300 times where we go through everything. I tell them, ‘What would you have done differently?’ And they just get frustrated because they don’t have another option, unless just let it go on forever, and they don’t like that either.”


## Zoom calls

* NYTimes: Antisemitic Slurs Disrupt Queens College Zoom Lecture About Israel

[https://www.nytimes.com/2025/09/12/nyregion/antisemitic-slurs-queens-college-lecture.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/12/nyregion/antisemitic-slurs-queens-college-lecture.html?smid=nytcore-ios-share&referringSource=articleShare)

> An Israeli law professor was only minutes into her online lecture about the erosion of the rights of women and sexual minorities in her country on Monday when an eruption of hate and misogyny filled the screen.

> The Queens College event — which was happening over Zoom — was abruptly interrupted by what appeared to be a group of attendees who turned on their cameras and microphones and began yelling slurs, including “kill all the Jews” and “go back to Auschwitz.” Instead of faces on the screen, pornographic and disturbing images appeared, including pictures of dead bodies and video clips of male masturbation.

> The event, an annual lecture sponsored by the Center for Jewish Studies at Queens College, illustrated how even Israeli academics critical of the war in Gaza such as Professor Tirosh, a law professor at Tel Aviv University, are being hit with antisemitic attacks as they deliver their views, presumably because they are Israeli.

> The lecture had been advertised online and was open to the public. In an email, a Queens College spokeswoman said an investigation had determined that one person had registered as multiple attendees, then exploited a wrongly configured screen-sharing setting in the Zoom lecture to make the disruption happen from all those accounts at once. The college added that it would take immediate steps to reinforce its security protocols to prevent future incidents. Another similar disruption, which happened earlier this month during a Zoom lecture about an archaeological expedition in Africa, was also being investigated.

> Though several antisemitic incidents were reported on campus in the past two years, Queens College has earned praise from Jewish organizations for its defense of Jewish students. It earned an “A” grade this year from the Anti-Defamation League for its efforts and initiatives to combat antisemitism, one of 11 schools in the nation to do so.

(From Queens College)

> Queens College has longstanding Zoom security measures in place to prevent unauthorized disruptions. These include:
> - Restricting screen sharing to the host only.
> - Requiring meeting passcodes and waiting rooms for all sessions.
> - Enabling authentication, requiring attendees to log in using verified CUNY credentials.
> - Disabling file transfers and private chat to minimize opportunities for disruption.
> Following these incidents, we are working to review these procedures with the college community to ensure that all online events are configured according to these security protocols.

*  What Can You Say on Campus at a Public University or College?  Free Speech, The Constitution, and College Life

(Website Link:)

[https://cvent.me/eAbLDP](https://cvent.me/eAbLDP)

(Registration Link: )

[https://cvent.me/NLV1Ev](https://cvent.me/NLV1Ev)

> Constitution Day 2025

> Wednesday, September 17, 2:00pm to 3:30pm (90 minutes) Eastern Time Zone

> In addition to fulfilling their research and education mission, public colleges and universities have always had an important role in supporting American democracy. Central to achieving their vision is the open exchange of ideas through civic discourse. Please join us as we explore the civic mission of public higher education, the importance of nurturing students' civic discourse skills, and recent challenges to free speech and civic discourse on American campuses.

* A&M Dean removed following student complaints over curriculum

[https://www.kbtx.com/2025/09/09/am-dean-professor-removed-following-student-complaints-over-curriculum/](https://www.kbtx.com/2025/09/09/am-dean-professor-removed-following-student-complaints-over-curriculum/)

(Related. In Texas you can't even say the facts.)

(Also)

[https://www.nytimes.com/2025/09/10/us/texas-professor-fired-gender-ideology.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/10/us/texas-professor-fired-gender-ideology.html?smid=nytcore-ios-share&referringSource=articleShare)


(Also)

> A Classroom Clash Over Course Content Went Viral. Texas A&M Fired the Instructor and Removed 2 Administrators.

[https://www.chronicle.com/article/a-classroom-clash-over-course-content-went-viral-texas-a-m-fired-the-instructor-and-removed-2-administrators](https://www.chronicle.com/article/a-classroom-clash-over-course-content-went-viral-texas-a-m-fired-the-instructor-and-removed-2-administrators)

(Also)

> Texas A&M fires instructor involved in viral video on gender teachings

[https://www.washingtonpost.com/nation/2025/09/09/texasam-gender-teachings/](https://www.washingtonpost.com/nation/2025/09/09/texasam-gender-teachings/)

> A video of a student accusing an instructor of illegally teaching “gender ideology” at Texas A&M has also led to the removal of a dean and department head.

(And yes, that was about it.)

> The instructor referred the student to a department head, noting that officials were aware of the concerns, had responded by inviting an observer into the class and added that “I’m not convinced that your proposal will be effective in stopping me from teaching things that are biologically true, because I do have the legal and ethical authority, professional expertise in this classroom,” before telling the student to leave.

> “This isn’t about academic freedom; it’s about academic responsibility. Our degree programs and courses go through extensive approval processes, and we must ensure that what we ultimately deliver to students is consistent with what was approved,” he [A&M president] wrote.

> The Texas Legislature's Least Favorite Member

[https://www.texasmonthly.com/news-politics/texas-lege-brian-harrison-2025/](https://www.texasmonthly.com/news-politics/texas-lege-brian-harrison-2025/)

(Paywalled article about The state politician fanning these flames ... "cockroach")


* Texas State professor fired for comments at socialism meeting | The Texas Tribune

[https://www.texastribune.org/2025/09/10/texas-state-university-professor-fired/](https://www.texastribune.org/2025/09/10/texas-state-university-professor-fired/)

> A Texas State University professor was fired on Wednesday after he was accused of inciting violence in a video of him speaking at a socialism conference posted on social media.

> In a video circulated on social media platform X, Thomas Alter, an associate history professor, can be seen talking during a Zoom meeting as part of the Revolutionary Socialism Conference, an online meeting organized by several socialist groups. During his talk, Alter explains how he feels socialists in the United States can organize an effective party, and criticizes the Democratic Party, the Democratic Socialists of America, China and anarchists for their methods of organization.

> The video circulated on X cuts one portion of Alter’s speech in half, during which he criticized “insurrectional anarchists” for their method of protesting, urging organization into a party to better reach people. In the full speech posted on YouTube, he notes that some anarchists have faced jail time for their methods of protest, praising their efforts but questioning whether they can achieve their goals.

## Op eds

* University Trustees Have Their Heads in the Sand by Ben Sasse

[https://www.wsj.com/opinion/university-trustees-have-their-heads-in-the-sand-fb1c31e8?st=gW6hoW&reflink=article_gmail_share](https://www.wsj.com/opinion/university-trustees-have-their-heads-in-the-sand-fb1c31e8?st=gW6hoW&reflink=article_gmail_share)

(Care to read what Ben Sasse thinks? Not me, but here is the link. He left U Florida in a heartbeat after overspending out the wazzoo...)

## Shared governance

* After a Messy Shared-Governance Effort, U. of Oregon Spares Programs and Some Faculty

[https://www.chronicle.com/article/after-a-messy-shared-governance-effort-u-of-oregon-spares-programs-and-some-faculty](https://www.chronicle.com/article/after-a-messy-shared-governance-effort-u-of-oregon-spares-programs-and-some-faculty)

> The University of Oregon will lay off 60 employees in order to close a structural deficit, administrators announced Monday, but it will not eliminate any degree programs or terminate any tenure-track professors, as faculty previously feared.

> The layoffs follow 57 others in June, administrators said; the university will also eliminate 59 vacant positions. The latest round will affect nontenure-track faculty, administrators, and staff. The university will also cut about $4.3 million in other expenses to eliminate a total of $29.2 million in recurring spending.

> Administrators have said the structural deficit resulted from factors including out-of-state enrollment that was lower than expected, growing compensation costs, and anemic state funding.

> In the weeks leading up to the announcement, faculty members pressed administrators to hold off on their plans, including holding an emergency meeting with the executive committee of the University Senate and gaining support from the American Association of University Professors and some state legislators, among other measures. University leaders announced in June that the Board of Trustees had directed them to put plans in place by mid-September to close a structural deficit of $25 million to $30 million. That timeline meant most of the budget deliberations took place over the summer, when many faculty members were off contract and off campus.

> The University of Oregon is not alone in struggling to implement shared governance. As many colleges around the country are working to close budget gaps, the question of what role faculty members should have in conversations about an institution’s future will emerge again.

## Academic freedom

* Mamdani Offers Support for Fired CUNY Professors at Brooklyn College Rally - Left Voice

[https://www.leftvoice.org/mamdani-offers-support-for-fired-cuny-professors-at-brooklyn-college-rally/](https://www.leftvoice.org/mamdani-offers-support-for-fired-cuny-professors-at-brooklyn-college-rally/)

> Part of Sanders’s “Fighting Oligarchy” tour, the talk focused largely on the senator’s populist economic policy, his critique of inequality, and the need for the Democratic Party to confront Trump’s ultra-reactionary second-term agenda.

> Before introducing Sanders, Mamdani took a moment to directly speak about the ongoing repression at the university, calling out the CUNY administration for its McCarthyist attacks on faculty and speaking out in defense of the Fired Four:

> "I cannot begin my remarks this evening without first acknowledging PSC-CUNY and the fact that no faculty member should be disciplined for supporting Palestinian human rights. I want to thank PSC-CUNY for standing alongside their rank and file."

> His statement was met with thunderous applause and a standing ovation from the crowd in support of the Fired Four and in defiance of the CUNY administration’s attacks against the Palestine movement.

(And from the Post... who slant everything they say about CUNY)

[https://nypost.com/2025/09/06/us-news/mamdani-sanders-use-brooklyn-college-event-to-push-pro-palestine-anti-israel-agenda/](https://nypost.com/2025/09/06/us-news/mamdani-sanders-use-brooklyn-college-event-to-push-pro-palestine-anti-israel-agenda/)

> The Democratic mayoral nominee was referring to at least four adjunct professors at Brooklyn College who claim they were canned in June – not over job performance, but over their pro-Palestine advocacy – but he failed to mention these same lecturers are also accused of enabling antisemitism at a college with a huge Jewish population.

(And can only quote one former trustee from over a decade ago)

“This is a political event,” former CUNY trustee Jeffery Wiesenfeld told The Post.

(BC's response was calm)

> The college in a statement said “the Leonard and Claire Tow Center is a part of the Brooklyn College campus. Any candidate is welcome to rent this facility.”

## Freedom of expression

* CUNY Colleges to Get Anti-Discrimination Coordinators

[https://www.thecity.nyc/2025/09/08/cuny-antisemitism-palestine-hochul-title-vi/](https://www.thecity.nyc/2025/09/08/cuny-antisemitism-palestine-hochul-title-vi/)

> The governor, who recently signed a law that mandates a Title VI staffer for every college in the state, has aggressively sought to address allegations of antisemitism on CUNY campuses.

> Gov. Kathy Hochul signed the legislation into law in August. The amendment to the state’s education law requires these “coordinators” to ensure there is a centralized review, investigation and resolution process for alleged violations of Title VI of the 1964 Civil Rights Act, which prohibits discrimination on the basis of race, color, or national origin, including shared ancestry or ethnic characteristics. It also requires the state Division of Human Services to develop compliance training for students and employees that will be delivered annually.

> CUNY leadership says the university has already invested millions into doing the work to combat hate crimes and antisemitism.

> CUNY has invested more than $2 million to combat hate crimes and antisemitism, including mandatory Title VI training for its faculty and staff, Chancellor Felix Matos Rodriguez said in a statement included in Hochul’s announcement..

> “Every college is required to have a Chief Diversity Officer on campus who is responsible for addressing allegations of discrimination, including Title VI complaints,” CUNY spokesperson Noah Gardy told THE CITY in a written statement. “CUNY will work with all the campuses to ensure that a Title VI coordinator is in place to comply with the law, which goes into effect next year.”

(Also touches on Hunter College Job ad,  former Chief Judge of New York Jonathan Lippman's report, and the governor's view on the definition from IRHA of antisemitism.

* Students Report Less Tolerance for Controversial Speakers

[https://www.insidehighered.com/news/students/free-speech/2025/09/09/tolerance-controversial-campus-speakers-declines](https://www.insidehighered.com/news/students/free-speech/2025/09/09/tolerance-controversial-campus-speakers-declines)

> College students—particularly those who identify as conservative—are less likely to tolerate controversial speech than they were last year, according to the Foundation for Individual Rights and Expression’s annual survey.

> But changes on both issues were driven primarily by conservative students’ decreased willingness to allow controversial speech on campus; liberal students reported a level of tolerance similar to previous years. Sean Stevens, FIRE’s chief research adviser and the report’s author, said it’s unclear why conservative students have had a change in attitude.

* A ‘Volatile Climate’ for Campus Speech Has Worsened Under Trump, New FIRE Report Says

[https://www.chronicle.com/article/a-volatile-climate-for-campus-speech-has-worsened-under-trump-new-fire-report-says](https://www.chronicle.com/article/a-volatile-climate-for-campus-speech-has-worsened-under-trump-new-fire-report-says)

> Pressure from the Trump administration to crack down on pro-Palestinian student protests and diversity, equity, and inclusion practices has “deepened an already volatile climate for campus expression,” according to a new, controversial ranking by the Foundation for Individual Rights and Expression, or FIRE, a free-speech advocacy organization that tracks campus free-speech climates annually.


(Same report as the last one, but a bit more clear in the headline)

[https://rankings.thefire.org/](https://rankings.thefire.org/)

> The rankings have also been weaponized by politicians as higher education has come under attack by the Trump administration, critics point out.

> Jay Bhattacharya, director of the National Institutes of Health, considered using FIRE’s rankings when evaluating institutions’ applications for research grants,...

> Harvard University’s last-place finish in FIRE’s 2024 and 2025 rankings were also cited by U.S. Rep. Elise Stefanik, Republican of New York, and Reps. Jake Auchincloss and Seth Moulton, both Democrats of Massachusetts, in the leadup and aftermath of the December 2023 congressional antisemitism hearings,...

## Visas

* Even as Classes Begin, Some Foreign Students Are Still in Visa Limbo

[https://www.chronicle.com/article/even-as-classes-begin-some-foreign-students-are-still-in-visa-limbo](https://www.chronicle.com/article/even-as-classes-begin-some-foreign-students-are-still-in-visa-limbo)

> Days, and even weeks, after classes have begun, many foreign students are still struggling to get visa appointments, holding out hope of salvaging the semester as colleges try to find ways to accommodate late arrivals. At the same time, institutions are working to reassure those stuck in their home countries that their American educational dream isn’t ended, only deferred. They are offering online courses and activities to keep students engaged and on track to enroll when bottlenecks ease.

(Is this happening at CUNY? I haven't heard)

* Supporting Our Students: Part Four

[https://www1.cuny.edu/sites/cunyufs/2025/09/08/supporting-our-students-part-four/](https://www1.cuny.edu/sites/cunyufs/2025/09/08/supporting-our-students-part-four/)

(Emily Sohmer Tai's blog post on a new resource, funded by the  Carroll and Milton Petrie Foundation, that has been established to assist first-and second-generation immigrant students, faculty, and staff.)

## Funding cuts

### NIH

* Former NIH Leaders Allege Retaliation for Whistleblowing

[https://www.insidehighered.com/news/quick-takes/2025/09/08/former-nih-leaders-allege-retaliation-whistleblowing](https://www.insidehighered.com/news/quick-takes/2025/09/08/former-nih-leaders-allege-retaliation-whistleblowing)

> Two former National Institutes of Health leaders are alleging the agency illegally put them on leave in April for speaking up against research grant cancellations and antivaccine efforts.

> Jeanne Marrazzo, former director of the National Institute of Allergy and Infectious Diseases, and Kathleen Neuzil, former director of the NIH’s Fogarty International Center and former associate director for international research, filed complaints Thursday with the U.S. Office of Special Counsel, seeking reinstatement. They allege they faced retaliation for whistleblowing and other protected activity.

> They both specifically allege that Matthew Memoli—who was NIH’s acting director after Trump returned to power and is now NIH’s principal deputy director—retaliated against them. An NIH spokesperson said in an email Friday that Memoli emphasizes that each vaccine “must be assessed on its own merits.”

* NIH Cuts Mean Job Losses in College Towns

[https://www.insidehighered.com/news/government/science-research-policy/2025/09/11/nih-cuts-mean-job-losses-college-towns](https://www.insidehighered.com/news/government/science-research-policy/2025/09/11/nih-cuts-mean-job-losses-college-towns)

> New report from the Brookings Institution shows that National Institutes of Health funding increases can boost labor markets in college towns. But if Trump’s proposed budget cuts takes effect, some will lose thousands of jobs.

> In 2024, the federal agency spent $26 billion of its $47 billion budget on research grants to more than 500 higher education institutions or their affiliated research centers. The paper found that about 80 percent of the NIH’s budget goes to cities where universities with large medical facilities account for a significant share of the local economy.

### DOE

* ED Rule-Making Agenda Includes Accreditation, Title VI

[https://www.insidehighered.com/news/quick-takes/2025/09/08/ed-rule-making-agenda-includes-accreditation-title-vi](https://www.insidehighered.com/news/quick-takes/2025/09/08/ed-rule-making-agenda-includes-accreditation-title-vi)

> Changing the interpretation of race-based discrimination, increasing flexibility within the college accreditation system and reworking the process to yank federal financial aid eligibility for certain civil rights violations are top priorities for Linda McMahon and the Department of Education, according to the agency’s rule-making agenda released Thursday.

> Civil Rights Investigations: The department is attempting to amend the rules that govern how the Office for Civil Rights enforces Title VI of the Civil Rights Act of 1964, which bars discrimination based on race and national origin, and Title IX of the Education Amendments of 1972, which prohibits sex-based discrimination.

> Specifically, officials wrote that they want to streamline “the process by which OCR seeks termination of Federal financial assistance to institutions that intentionally violate Federal civil rights laws and refuse to voluntarily come into compliance.”

> Eliminating Disparate Impact Theory: This legal theory, codified into law in 1991, states that even if a policy or practice is seemingly neutral, it can be declared discriminatory if it disproportionately harms a specific group of people. The Trump administration is attempting to repeal that theory.

> Accreditation: The department wants to change the regulations for accreditation to clarify a college’s ability to change accreditors and to make it easier for the department to recognize new accreditors.

> Title IV Eligibility: The department wants to change the rules to make it easier for certain for-profit and religious institutions to access federal student aid.

* McMahon to Higher Ed Leaders: Join Us to ‘Make Higher Ed Great Again’

[https://www.insidehighered.com/news/government/politics-elections/2025/09/09/mcmahon-dings-university-leaders-cites-hillsdale](https://www.insidehighered.com/news/government/politics-elections/2025/09/09/mcmahon-dings-university-leaders-cites-hillsdale)

(The woman who wants to bring everyone A1 ...)

> Education Secretary Linda McMahon denounced higher education as broken in a speech Monday at Hillsdale College in Michigan, directing her remarks primarily at four-year institutions and pitching her vision for how to improve American colleges and universities.

> McMahon largely directed her speech to college leaders, arguing that “the crisis of higher education is first and foremost a crisis of leadership.” She called on them to work with the Trump administration to “make higher education great again.”

> She wants to see a system of higher education that’s rigorous and prepares students for a career, but is also dedicated to truth-seeking and committed to treating institutions as “repositories of our civilizational inheritance,” according to a transcript of her remarks. She raised concerns about colleges allegedly taking “real American history” out of the curriculum and questioned whether tax dollars should go to institutions that detract from “our nation’s strength.”

> McMahon’s stop at Hillsdale is part of her nationwide Returning Education to the States tour.

(Hillsdale is a safe space to dismantle education)

> Ross Mugler, acting president of the Association of Governing Boards of Universities and Colleges, and others said McMahon’s comments “misrepresent the reality on college campuses today” and reflect an “unrealistic approach and assessment of higher education in this country.” ... “Higher ed isn’t broken; it’s adapting,” he said.

* Trump Administration Takes Next Step in Dismantling ED

[https://www.insidehighered.com/news/quick-takes/2025/09/09/trump-administration-takes-next-step-dismantling-ed](https://www.insidehighered.com/news/quick-takes/2025/09/09/trump-administration-takes-next-step-dismantling-ed)

> The Trump administration has taken another step toward dismantling the Department of Education, creating a new integrated “state plan portal” that will allow the Department of Labor to jointly administer adult education programs with ED.

> “To prepare our next generation of American workers, the Trump Administration is taking decisive action to streamline unnecessary bureaucracy and advance the skills needed to fill jobs of the future,” Secretary of Labor Lori Chavez-DeRemer said in a news release.

> “Donald Trump and Linda McMahon are continuing their attempts to illegally dismantle the Department of Education—and they are risking critical career and technical and adult education programs,” Democratic Senators Patty Murray and Tammy Baldwin, and Democratic Congresswoman Rosa DeLauro said in a statement. “Linda McMahon and Donald Trump need to follow the plain text of the law—period. Republicans should join us in insisting that the laws we pass get followed—and to stand up for students and families nationwide in the face of this administration’s continued attacks on our public education system.”

* Education Department ends some aid aimed at minority college students

[https://www.washingtonpost.com/education/2025/09/10/trump-grants-minority-students-college/](https://www.washingtonpost.com/education/2025/09/10/trump-grants-minority-students-college/)

> The Trump administration said Wednesday that it will withhold $350 million in grants to hundreds of colleges that serve large populations of minority students, calling the decades-old programs discriminatory.

> The Education Department said it would cease funding eight discretionary grant programs that individually support Black, Native, Hispanic and Asian American students across the country.

> “Ripping away these resources at the tail end of the fiscal year is yet another example of how President Trump is putting politics ahead of students,” Sen. Patty Murray (Washington), the top Democrat on the Senate Appropriations Committee, said in a statement.

(Also)

[https://www.insidehighered.com/news/government/politics-elections/2025/09/11/education-department-moves-end-msi-programs](https://www.insidehighered.com/news/government/politics-elections/2025/09/11/education-department-moves-end-msi-programs)

(Also)

[https://www.nytimes.com/2025/09/10/us/politics/linda-mcmahon-federal-grants-colleges-universities.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/10/us/politics/linda-mcmahon-federal-grants-colleges-universities.html?smid=nytcore-ios-share&referringSource=articleShare)

> “These are longstanding programs that Congress has authorized and provided funding for on an annual basis that the Trump administration — empowered by the yearlong slush fund spending bill passed in March — is unilaterally deciding to eliminate funding for at the end of the year,” Ms. Murray [Senator Patty Murray of Washington] said in a statement. “This is another important reminder of why Congress needs to pass funding bills, like the one the Senate marked up this summer, that ensure Congress — not Donald Trump or Linda McMahon — decides how limited taxpayer dollars are spent.”

## Federal Agencies

* Commerce Secretary Says He Wants Half of University Patent Money

[https://www.insidehighered.com/news/quick-takes/2025/09/11/commerce-sec-wants-half-university-patent-money](https://www.insidehighered.com/news/quick-takes/2025/09/11/commerce-sec-wants-half-university-patent-money)

> Commerce Secretary Howard Lutnick told Axios he wants the federal government to get half the dollars generated from patents that universities and their researchers develop with federal funding, the outlet reported Wednesday.

> As Axios noted in its article about the interview, the Bayh-Dole Act generally gives universities the right to own patents developed with federal funding. The Commerce Department didn’t return requests for comment Wednesday about how the Trump administration could legally get around that law.

> “The proposal would obliterate the progress that university tech transfer has enjoyed in the 45 years since the passage of the seminal Bayh-Dole Act, which facilitated new university-industry partnerships and led to an explosion of technological progress and substantial economic gains,” Hudson said. “If enacted, the proposal would stifle the U.S. innovation pipeline, with the American people, not universities, being the ultimate losers.”

## Congressional actions

* Work-Study Funding, Child Care at Risk of Severe Cuts in House Bill, Advocates Warn

[https://www.chronicle.com/article/work-study-funding-child-care-at-risk-of-severe-cuts-in-house-bill-advocates-warn](https://www.chronicle.com/article/work-study-funding-child-care-at-risk-of-severe-cuts-in-house-bill-advocates-warn)

> College advocates warn that a series of cuts tucked into a U.S. House of Representatives budget bill could have serious consequences for struggling students and institutions. The House is expected to vote Tuesday on the bill, which contains language threatening programs that support adult students and canceling work-study funding. The bill must be combined with its Senate counterpart and passed before becoming law.

> “We know that there is a strong current of support in some corners for reducing spending in these programs,” said David Baime, senior vice president for government relations at the American Association of Community Colleges.

> * The House bill proposes eliminating the federal Supplemental Educational Opportunity Grant program, which provides additional financial support to students who receive Pell Grants.

> * The bill proposes cutting federal funding for work study from $1.2 billion in 2024 to $779 million, a reduction of about 37 percent.

> * The bill proposes cutting all support for the federal Child Care Access Means Parents in School program, known as CCAMPIS, which provides child care for adult students who are parents at about 200 colleges. T

## Institutional assaults

* NYTimes: What Has the Trump Administration Gotten From Law Firms and Universities?

[https://www.nytimes.com/interactive/2025/09/06/us/trump-deals-law-firms-universities-concessions.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/interactive/2025/09/06/us/trump-deals-law-firms-universities-concessions.html?smid=nytcore-ios-share&referringSource=articleShare)


* NYTimes: We Are Watching a Scientific Superpower Destroy Itself

[https://www.nytimes.com/2025/09/08/opinion/universities-science-trump-china.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/08/opinion/universities-science-trump-china.html?smid=nytcore-ios-share&referringSource=articleShare)

> We are currently governed by a leader indifferent to scientific consensus if it contradicts his political or economic interests, hostile to immigrants and intent on crippling the research universities that embody our collective hope for the future. The menace now is within. And with very few exceptions, the leaders of American universities have done little more than duck and cover.

> In 1958, by a bipartisan vote, Congress passed and President Dwight Eisenhower signed the National Defense Education Act, one of the most consequential federal interventions in education in the nation’s history. Together with the National Science Foundation and the National Institutes of Health, it made America into the world’s undisputed leader in science and technology.

> The N.D.E.A. reflected the widespread realization that something had to be done in schools and universities besides teaching students to hide under their desks. The country urgently needed more trained physicists, chemists, mathematicians, aerospace engineers, electrical engineers, material scientists and a host of other experts in STEM fields, and the government grasped that to get them would take a massive infusion of money pumped into schools and universities: roughly $1 billion, the equivalent of more than $11 billion today.

> Until 1962, recipients of N.D.E.A. funds had to sign an affidavit affirming that they did not support any organization that sought to overthrow the U.S. government. But in one of those moments in which the right policy is chosen for the wrong reason, Southern segregationists in Congress, worried that some of the funds might be used to further desegregation efforts, added a provision stipulating that no part of the act would allow the federal government to dictate school curriculum, instruction, administration or personnel.

> These transformations wound up playing a significant role in my own career. When I went back to Yale for graduate work, the N.D.E.A. funded my Ph.D. The government was not under the illusion that studying Shakespeare was rocket science. But Title IV of the act, calling for an increase in the number of university professors, extended support to the humanities as well as the sciences. Sputnik had turned out to include me in its orbit.

> Should the Trump administration settle for one-time fines, universities, chastened by the threats of the past few months, may yet recover their footing. But if, as seems entirely possible, the administration is determined to reshape the intellectual life and values of faculty members and students alike, then such recovery will be impossible.

> Why on earth would we abandon institutions that have genuinely made America great? Why would we squander the world’s admiration for this magnificent achievement of ours? Why would we put at risk laboratories that are working to cure cancers or perfecting artificial limbs or exploring deep space or testing the limits of artificial intelligence?



### Accreditation

* Accreditors Venture Into the Microcredential Landscape

[https://www.insidehighered.com/news/governance/accreditation/2025/09/08/accreditors-venture-microcredential-landscape](https://www.insidehighered.com/news/governance/accreditation/2025/09/08/accreditors-venture-microcredential-landscape)

> The microcredential landscape is often called a “wild west” in higher ed circles.

> The field is crowded with tens of thousands of program providers, in and outside of academia, online and in person. Short-term programs vary widely, from certificates to badges to boot camps, spanning weeks to months to over a year. And while some programs offer high returns, others yield little to none or insufficiently track outcomes.

> Now, two accrediting agencies are stepping into that murky terrain, hoping to bring some order—and branch out into a new market. Both the New England Commission of Higher Education and the Higher Learning Commission, which has been researching short-term programs for eight years, are gearing up to assess whether providers of these programs meet their standards.

(MSCHE?)

### Harvard

* When the next Democratic President uses Donald Trump’s precedent to target campus conservatives or climate “deniers,” the right will be singing Harvard’s current fight song.

[https://www.wsj.com/opinion/donald-trump-harvard-judge-allison-burroughs-first-amendment-4c00709e?st=XuU53K&reflink=article_gmail_share](https://www.wsj.com/opinion/donald-trump-harvard-judge-allison-burroughs-first-amendment-4c00709e?st=XuU53K&reflink=article_gmail_share)


(The WSJ almost gets it, but always trips on its bias)

* NYTimes: Settlement Talks Stall Between Harvard and the Trump Administration

[https://www.nytimes.com/2025/09/06/us/politics/harvard-trump-negotiations-stall.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/06/us/politics/harvard-trump-negotiations-stall.html?smid=nytcore-ios-share&referringSource=articleShare)

(The same bylines for some 3 months now trying to peddle a story with slant that only helps one side... Now the message they carry---settle or the terms will ge t worse)

> One major reason is an emerging divide within the administration between aides eager to deliver President Trump a political victory by announcing a deal and those who contend the current framework is too favorable to Harvard. Some Trump advisers argue that one way to strengthen the agreement would be to subject Harvard to an independent monitor who would ensure compliance. Harvard has consistently opposed that idea.

> Talks have also slowed in recent weeks with Cornell University and Northwestern University, although the reasons are unclear.

> The government’s tactics — cutting research grants, opening investigations and demanding hundreds of millions of dollars or more in settlement payments — have plunged campuses into financial and political crises. Some schools, like Columbia University, negotiated deals with the Trump administration.

> The slowdown in talks with universities is a signal that the administration is still acclimating to the departure of May Mailman, who, as the White House’s senior policy strategist, was a driving force behind Mr. Trump’s pressure campaign. She stepped back from that position last month as part of a long-planned return home to Texas.

(Huh? Perhaps they are slowing due to the illegality of the approach being declared in the courts?)

> A deal with Harvard was nearing the finish line only a month ago. [As reported just by these three writers]

> Mr. Trump’s enthusiasm for an agreement has been clear since June, when he posted on social media that a “mindbogglingly historic” agreement with Harvard could be finalized within days.

* Harvard beat Trump in court. Here’s what could happen next.

[https://www.washingtonpost.com/education/2025/09/05/harvard-trump-funding-battle](https://www.washingtonpost.com/education/2025/09/05/harvard-trump-funding-battle)
/

> The challenges are unprecedented: They include a promised appeal in court, worry that the government will slow-walk restoring frozen research funds, threats to future grants, complicated settlement negotiations — and the prospect of another 3½ years of a hostile White House with a bevy of arrows in its quiver and a proven willingness to aim them at its opponents.

* Harvard Was Cleared To Get Some Federal Funds. Then DOGE Stepped In. | News | The Harvard Crimson

[https://www.thecrimson.com/article/2025/9/8/doge-blocks-nih-grants/](https://www.thecrimson.com/article/2025/9/8/doge-blocks-nih-grants/)

> The National Institutes of Health began allocating some grants to Harvard in July to comply with a federal court ruling. But Department of Government Efficiency officials have quietly blocked all the funds at the last mile, withholding money because the University has not reached a settlement, according to four people familiar with the matter, including NIH staff.

> The NIH resumed issuing some grants in mid-July to schools, including Harvard, that had been barred from receiving federal dollars under April guidance, according to an internal memo obtained by The Crimson. But officials from DOGE, the government cost-cutting group, used their control over the NIH’s payment system to keep the money out of researchers’ hands.

> The extent of DOGE’s role in quietly obstructing NIH grant disbursements to universities — even after the agency was legally compelled to begin restoring some awards in July — has not been previously reported. And it suggests that, even in the absence of a formal stay or injunction, DOGE may use its power over federal payments to continue to quietly sidestep the Wednesday ruling that directs the Trump administration to reinstate the more than $2.7 billion in federal grants to Harvard that the administration froze or terminated in the spring.

(Table By Saketh Sundar — Crimson Designer)

| University   | Size of Freeze | Settled? | Status of NIH Funds  |
|:-------------|----------------|:---------|:---------------------|
| Harvard      | 2.6 billion    | No       | Restricted           |
| Brown        | 510 million    | Yes      | Flowing post-deal    |
| Northwestern | 790 million    | No       | Restricted**         |
| Penn         | 175 million    | Yes      | Flowing post-deal    |
| Columbia     | 400 million    | Yes      | Flowing post-deal    |
| UCLA         | 584 million    | No       | Flowing post-cut     |
| Duke         | 108 million    | No       | Flowing post-cut     |
| Cornell      | 1 billion      | No       | Partially restricted |
|              |                |          |                      |

* How Harvard Can Out-Negotiate Trump | TIME

[https://time.com/7314798/harvard-can-out-negotiate-trump/](https://time.com/7314798/harvard-can-out-negotiate-trump/)

(By leaders from Yale and past president of Dartmouth)

> President Donald Trump, the self-proclaimed great negotiator, has fumbled at the bargaining table once more.

> He failed to intimidate India and China in trade talks, setting the stage for inflation to rise and for America’s greatest rivals to unite. His ingratiating groveling to Russian President Vladimir Putin was unable to bring about the ceasefire he promised—despite entering negotiations with the upper hand. Now, the “great negotiator” seems to have lost his cards again in his epic standoff with the world’s top-rated university.

> For an administration that claims to be concerned about maintaining technological and scientific supremacy against international rivals, the political warfare on higher education makes no sense. As widely documented, American universities serve as the strongest engines for research, innovation, and economic growth. The direct, and indirect, economic impact of U.S. universities on the national GDP is significant and undeniable. Sectors that American schools underpin such as digital commerce, biotechnology, and artificial intelligence account for nearly half of the U.S. GDP, drive almost all GDP growth, and total twice the size of federal government spending.

> In the context of America’s trade deficit, universities are a major export for the U.S., and one of the few sectors in which we have a large trade surplus. Universities, particularly through the influx of international students, contribute significantly to the U.S. trade surplus, with international students contributing $44 billion to the economy and the trade surplus in education accounting for about 15% of total U.S. services trade surplus—comparable to the combined exports of soybeans, coal, and natural gas.

* NYTimes: Harvard Is Told Research Money Could Flow Again, for Now

[https://www.nytimes.com/2025/09/10/us/harvard-research-funding-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/10/us/harvard-research-funding-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

(The three writers on the Harvard beat who have been consistently premature, have this to add)

> The Trump administration says it will restart the flow of federal research money to Harvard University, following a judge’s ruling that a sweeping blockade of funds was illegal, according to five people familiar with the matter and documents reviewed by The New York Times.

> Harvard received at least one letter this week from the Trump administration saying that hundreds of grants were being restored, according to a person briefed on the matter, who spoke on the condition of anonymity to discuss private correspondence. Individual researchers have begun receiving notices from the government about restored funding, including an astronomy professor, whose $3.7 million NASA grant seems to have been resurrected.

> It is possible that funding will be disrupted again, even if the government begins making payments. The Justice Department, for example, could seek a stay of last week’s decision by Judge Allison D. Burroughs, who sits on the federal bench in Boston, and ask the court for permission to suspend the funding once again while its appeal proceeds.

> Harvard officials were surprised by the development, and unsure whether the White House knew that federal agencies seemed set to restore Harvard’s money, according to a person familiar with the university officials’ thinking. They wondered whether the West Wing would intervene to cut the funding off again.


### George Mason

* NYTimes: At George Mason University, Trump Has Found an Unbending Adversary

[https://www.nytimes.com/2025/09/06/us/george-mason-university-gregory-washington-trump-attack.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/06/us/george-mason-university-gregory-washington-trump-attack.html?smid=nytcore-ios-share&referringSource=articleShare)

(An "adversary"?)

> President Trump’s interpretation of the Civil Rights Act, historically aimed at protecting Black people and members of other minority groups from discrimination, has infuriated his critics. And as if to twist the knife, the Trump administration has also demanded a personal public apology from Dr. Washington over his efforts to support racial diversity — which it described as unlawful and discriminatory.

> The refusal has made the George Mason president one of the few university leaders who has explicitly, and publicly, challenged the Trump administration. He joins a short list of other higher education leaders, including the presidents of Harvard and Princeton.

> But unlike many of his peers, Dr. Washington has been targeted as an individual, and so his choice to resist the Trump administration’s demands leaves him in an uncommonly precarious position.

> “Singling out a Black leader in this way is not only unprecedented but also deeply troubling,” the university chapter of the American Association of University Professors said in a statement last week.

(And they can write this without better phrasing, such as "Without reason...")

> The Trump administration has made attacking universities central to its agenda.

> The Education Department’s assistant secretary for civil rights, Craig Trainor, upped the pressure in a statement last month, saying Dr. Washington “waged a university-wide campaign to implement unlawful D.E.I. policies that intentionally discriminate on the basis of race,” the statement said, adding, “You can’t make this up.”

> “They are literally investigating me for what they call offenses I made back in 2020, 2021 and that’s problematic,” he [GM President Washington] said. “It’s like changing the speed limit and charging you for speeding four years ago.”



* Virginia Democrats Accuse GMU Rector of Conflict of Interest

[https://www.insidehighered.com/news/governance/trustees-regents/2025/09/09/virginia-democrats-accuse-gmu-rector-conflict-interest](https://www.insidehighered.com/news/governance/trustees-regents/2025/09/09/virginia-democrats-accuse-gmu-rector-conflict-interest)

> Virginia Democrats want George Mason University board rector Charles Stimson to recuse himself from federal investigations into the university as well as discussions about the university president’s future, saying that his role at the Heritage Foundation, which recently released a report critical of GMU, presents a conflict of interest.

> The letter comes almost two weeks after a state Senate committee blocked 14 gubernatorial appointments to university boards, including six at GMU, which left the Board of Visitors without a quorum. The letter also follows the Heritage report that accused GMU of attempting to hide diversity, equity and inclusion programs. Stimson has had several jobs at Heritage, where he’s currently deputy director of the organization’s legal and judicial studies center.

> “This creates an untenable ethical conflict where your employer’s published position is diametrically opposed to your duties as Rector,” the lawmakers wrote to Stimson.

(Also)

[https://www.chronicle.com/article/virginia-democrats-decry-george-mason-board-leaders-role-with-the-heritage-foundation](https://www.chronicle.com/article/virginia-democrats-decry-george-mason-board-leaders-role-with-the-heritage-foundation)

### UCLA

* The world’s greatest mathematician avoided politics. Then Trump cut science funding.

[https://www.washingtonpost.com/science/2025/09/07/science-math-trump-federal-cuts-grants/](https://www.washingtonpost.com/science/2025/09/07/science-math-trump-federal-cuts-grants/)

> A court order restored National Science Foundation grants, including Tao’s. But no new awards can be made, putting at risk the Institute for Pure and Applied Mathematics (IPAM), where he is director of special projects. Tao works in esoteric realms, which can lead to tangible real world benefits. For example, some of his work at IPAM has helped make MRI scans faster.

> Because of previous delays in funding, I didn’t have enough money to fund my own summer salary. I was already delaying that for one month. And so, yeah, it’s still delayed, but that’s fine. I can take it. But IPAM, they didn’t have the reserves to operate for more than a few months. So basically, for the past two weeks or so, we’ve been in an emergency fundraising mode. I’ve been meeting with lots of donors.

> The NSF grant that I had, I mean its primary purpose was to support my graduate students, give them the opportunity to travel to a conference, which is really important for career development at that stage,

> Q: If things do go back to normal, why does the uncertainty make a difference? A: In order to do the best science, you also need to have a somewhat tranquil mental state. Just to give it an analogy, suppose it’s a little bit chilly. It’s 60 degrees in your home, and so you set your heater to 72. But suppose that your thermostat suddenly changes the temperature to 100 degrees and then to 40 degrees and finally it’s back to 72 degrees. On paper, you now have the right temperature, but you’re not feeling too good after this. And somehow you can’t relax and sort of be productive, especially if you are worried that it’s going to do that again.

### U Chicago

* How the U. of Chicago’s Financial Strains Are a Warning for Higher Ed

[https://www.chronicle.com/article/how-the-u-of-chicagos-financial-strains-are-a-warning-for-higher-ed](https://www.chronicle.com/article/how-the-u-of-chicagos-financial-strains-are-a-warning-for-higher-ed)

> And then, just over a week ago, the university revealed a wide-ranging cost-saving plan aimed at reducing spending by $100 million, including:
> - a 30-percent reduction in its rate of tenure-track hiring
> - a 30-percent reduction in internally funded Ph.D. candidates by 2030–31
> - a pause on certain new capital projects, along with a reduced footprint for the university’s planned engineering and science building
> - a staff reduction of 100–150 nonclinical employees
> - a 20-percent reduction in unrestricted funding toward campus centers
> **Reviews of smaller programs are also planned.**

> Although red ink isn’t new to the university — its academic operations have run operating deficits since 2011 — the scale of its deficits worsened sharply in late 2021-22, surging to over $225 million annually and coinciding with rising inflation rates. As for Chicago’s most recently completed fiscal year, which ended six months after the second inauguration of Donald Trump — heralding a dramatic shift in the federal government’s relationship with higher ed — President Paul Alivisatos told faculty the university’s annual income had once again fallen short of expenses.

## Blowback

* Has Trump Ended Staten Island’s Wind Power Dreams?

[https://www.motherjones.com/politics/2025/09/staten-island-offshore-wind-trump/](https://www.motherjones.com/politics/2025/09/staten-island-offshore-wind-trump/)

> For over a decade, New York has worked to bring wind power jobs to Staten Island as part of an ambitious plan to establish the state as the biggest hub of offshore wind. A centerpiece of the effort, situated in the southwest of the island, is the Arthur Kill Terminal (AKT), an envisioned staging and assembly port.


> But on Friday, the Trump administration’s Department of Transportation rescinded a 2022 $48 million grant supporting the project that had been funded by President Joe Biden’s Bipartisan Infrastructure Law.

> “There’s a lot of money invested in this industry already, and these companies can’t take the hit.”

> The construction of the facility would create 600 jobs, according to Charles Dougherty, AKT’s chief commercial officer, and once up and running, manufacturing work would sustain 100 to 150 jobs, all union. The project would also add nearly $400 billion in “direct economic impact” according to Empire State Development.

> Bringing wind power to Staten Island, which has only voted for a Democrat presidential candidate four times in history, used to be a bipartisan project. Staten Island’s GOP representative, Nicole Malliotakis, has supported AKT, while boasting of the economic and environmental benefits of expanding wind power facilities in her district. She voted for Biden’s infrastructure package, and on Earth Day 2022 introduced legislation to create a program to share federal offshore wind revenue with states. In April, despite Trump’s order halting offshore wind development, Rep. Malliotakis petitioned the Army Corp of Engineers to nonetheless expedite the remaining federal permit for AKT. Her office did not respond to a request for comment, but after the Department of Transportation announced on Friday that it would pull its financial support of the terminal, Malliotakis told the Staten Island Advance she would push the agency “to get the funding repurposed to another maritime, port infrastructure or economic development project that would benefit Staten Island.”

> Beyond investments in infrastructure, local officials also worked to build the island’s workforce. Beginning in 2023, New York City’s Economic Development Corporation gave over half a million to the College of Staten Island to “train the next generation of professionals for offshore wind careers.” The day before the 2024 election, AKT provided the college another $1 million to develop a future offshore wind industry workforce.

* NYTimes: Happy Birthday, LIGO. Now Drop Dead.

[https://www.nytimes.com/2025/09/10/science/gravitational-waves-ligo-black-holes.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/10/science/gravitational-waves-ligo-black-holes.html?smid=nytcore-ios-share&referringSource=articleShare)

> It’s been 10 years since astronomers first felt the universe tremble.

> The whole encounter lasted one-fifth of a second. But that instant changed astrophysics, opening a window onto previously inaccessible realms of nature in which space could rip, bend, puff up, crumple and even vanish.

> It was the first direct proof that ripples in space-time, predicted by Albert Einstein a century earlier, actually existed. In the decade since, LIGO and other experiments have logged more than 300 of these violent collisions, providing astronomers with clues regarding the evolution of black holes across cosmic history.

> ...President Trump has proposed slashing LIGO’s operating budget in 2026 by 40 percent, to $29 million from $48 million, and eliminating one of the antennas. That could spell disaster, as it takes two antennas to triangulate the origins of gravitational waves.

> The impact on performance and future upgrades would be devastating, he [David Reitze, a physicist at Caltech and director of the LIGO Laboratory] added: “It would be nearly impossible for LIGO to recover from a cut of this magnitude.”

* The Rise of ‘Conspiracy Physics’

[https://www.wsj.com/science/physics/the-rise-of-conspiracy-physics-dd79fe36?st=9CAcc5](https://www.wsj.com/science/physics/the-rise-of-conspiracy-physics-dd79fe36?st=9CAcc5)

> This resentment of scientific authority figures is the major attraction of what might be called “conspiracy physics.” Most fringe theories are too arcane for listeners to understand, but anyone can grasp the idea that academic physics is just one more corrupt and self-serving establishment. The German physicist Sabine Hossenfelder has attracted 1.72 million YouTube subscribers in part by attacking her colleagues: “Your problem is that you’re lying to the people who pay you,” she declared. “Your problem is that you’re cowards without a shred of scientific integrity.”




## Coming attractions?

* States face massive new costs under Trump budget cuts

[https://www.washingtonpost.com/politics/2025/09/08/states-medicaid-snap-cuts-trump/](https://www.washingtonpost.com/politics/2025/09/08/states-medicaid-snap-cuts-trump/)

> States are scrambling to prepare for an unprecedented shift of costs and responsibilities under President Donald Trump’s sweeping tax and spending plan, which will force them to make difficult decisions about cuts to state programs to offset the new financial burdens.

> Unlike the federal government, states must balance their budgets each year. That means deep cuts and changes to Medicaid and the Supplemental Nutrition Assistance Program (SNAP) will require state legislatures and governors to cope with hundreds of millions of dollars in new costs each year.

> The changes mean that about 10 million fewer people are expected to have health insurance over the next decade and 2.4 million fewer people are expected to participate in SNAP during an average month, according to the nonpartisan Congressional Budget Office.

> The bill also sharply limits the provider tax, which states collect from hospitals and other providers to boost Medicaid payments and receive federal matching funds. The change, along with others in the bill, will cause an additional $366 billion in cuts to federal Medicaid spending, according to the CBO.

> The Washington Post conducted a survey of all 50 states and the District of Columbia about how much they expected to incur in additional costs from the Republican bill, how many residents are expected to lose health care and access to food stamps, and what services might be cut as a result. Only 15 states and D.C. replied, with responses that varied largely along partisan lines. ... Three GOP-led states — Arkansas, Ohio and North Dakota — said they did not anticipate cuts to other programs as a result of Medicaid and SNAP changes  ... Democratic-run states say the effects of the federal cutbacks will be severe, and several Democratic governors have said there is no way for states to backfill the scale of the cuts.


## And just because it is fun

* How Much Are Public-College Presidents Paid? (2024)

[https://www.chronicle.com/article/president-pay-public-colleges/](https://www.chronicle.com/article/president-pay-public-colleges/)

(And no CUNY listed, but SUNY seems to pay much better)

----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)
