# Sep 19

Dear All,

Please find a partial summary of some of the actions taken by the federal government as relates to Higher Education in general and CUNY in specific in the past week.

(Thanks to K, VAC for sharing stories this week.)

The aftermath of a murder has reached farther faster than could have been imagined. This week the Freedom of expression category is far to full of items.

## Op eds

* Thoughts on Education and Freedom as Fall Begins (opinion)

[https://www.insidehighered.com/opinion/views/2025/09/12/thoughts-education-and-freedom-fall-begins-opinion](https://www.insidehighered.com/opinion/views/2025/09/12/thoughts-education-and-freedom-fall-begins-opinion)

> As a Jewish teacher and university president, it pains me to see the fight against antisemitism used as a cudgel with which to attack centers of teaching and research. I’ve been very aware of antisemitism since I was a little boy,...I am genuinely startled, though, by the ways Christian nationalists in the American government use Jew hatred as a vehicle to advance their authoritarian agenda. That’s what we are witnessing today: the exploitation of anti-antisemitism by a White House determined to extort money and expressions of loyalty from higher education.

> This environment is threatened by the enormous pressure the federal government is putting on higher education to “align its priorities” with those of the president. I am worried about the normalization of this authoritarian effort to reshape the ecosystem of higher education. Too many opportunists and collaborators have been responding by noisily preaching neutrality or just keeping their heads down.

> Some faculty, student and alumni groups, however, have begun to stand up and make their voices heard. Whether refusing to apologize for diversity efforts or simply standing up for the freedom of scientific inquiry, there is growing resistance to the administration’s attempt to control civil society in general and higher education in particular.

> We don’t want the government thinking for us, telling us what the president’s priorities are so that we can imitate them. We want to learn to think for ourselves in the company of others, leaving behind a dependence on authority. Authoritarians would see us impose immaturity upon ourselves. As the new school year begins, we in higher education must redouble our efforts to model and defend the enlightenment ideals of education and freedom—while we still can.

## Freedom of expression

* Staff Members Fired, Grad Student Punished for Cheering Charlie Kirk’s Death

[https://www.insidehighered.com/news/quick-takes/2025/09/12/staff-members-fired-grad-student-punished-cheering-charlie-kirks-death](https://www.insidehighered.com/news/quick-takes/2025/09/12/staff-members-fired-grad-student-punished-cheering-charlie-kirks-death)

> Late Wednesday, a student affairs administrator at Middle Tennessee State University was fired after posting “insensitive” remarks on Facebook in response to Kirk’s death.

> “Looks like ol’ Charlie spoke his fate into existence. Hate begets hate. ZERO sympathy,” Sosh-Lightsy wrote in a Facebook post  ... Tennessee senator Marsha Blackburn, a Republican, called for Sosh-Lightsy’s firing on X,

> On Thursday afternoon, University of Mississippi chancellor Glenn Boyce confirmed the firing of an unnamed staff member who he said “re-shared hurtful, insensitive comments on social media regarding the tragic murder of Charlie Kirk.”

> At Baylor University, officials distanced the university from a graduate student who wrote “this made me giggle” in response to a social media post sharing the news of Kirk’s death.

> The Foundation for Individual Rights and Expression is monitoring which universities are censoring employee speech, said Lindsie Rank, director of campus rights advocacy at FIRE. “It may not be moral to speak ill of the dead, but it is protected by the First Amendment so we’re going to be keeping our eyes open for those situations,” she said.

* 6 More Faculty, Staff Removed for Kirk Comments

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/09/12/6-more-faculty-staff-removed-kirk-comments](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/09/12/6-more-faculty-staff-removed-kirk-comments)


> Republican politicians and other conservatives are calling for employees, including those in higher ed, to be terminated for their social media posts about Kirk's killing.

> At least eight faculty and staff members have been fired or suspended so far for comments they made

* Workers are getting fired, placed on leave over Charlie Kirk posts

[https://www.washingtonpost.com/business/2025/09/12/workers-fired-charlie-kirk-reaction-online/](https://www.washingtonpost.com/business/2025/09/12/workers-fired-charlie-kirk-reaction-online/)

* NYTimes: Right-Wing Activists Urge Followers to Expose Those Celebrating Kirk Killing

[https://www.nytimes.com/2025/09/12/us/politics/charlie-kirk-shooting-firings-celebration.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/12/us/politics/charlie-kirk-shooting-firings-celebration.html?smid=nytcore-ios-share&referringSource=articleShare)

>  and at least one Trump administration official have actively encouraged people to scour the internet for remarks celebrating the killing and to expose those who have posted them online.

> Christopher Landau, the deputy secretary of state, issued a separate call on Thursday morning, asking his more than 200,000 followers on X to reach out to him with information about “foreigners who glorify violence and hatred.”

> A Secret Service employee was placed on administrative leave after stating on Facebook that Mr. Kirk had “spewed hate and racism on his show,”

> After Michael Mann, a prominent climate scientist who works at the University of Pennsylvania, reposted a message referring to Mr. Kirk as the “head of Trump’s Hitler Youth,” Dave McCormick, the state’s Republican senator, called it “despicable” and urged the university to “take immediate, decisive action.”

> Rose Pugliese, a Colorado state lawmaker who is a Republican, asked Gov. Jared Polis, a Democrat, on Thursday to fire a state employee who had accused Mr. Kirk online of being “a white man who spews horrid” words “against every marginalized community.”

> Representative Clay Higgins, Republican of Louisiana, said that he planned to use “Congressional authority” to force tech companies to “ban for life” any person who “belittled the assassination of Charlie Kirk.”

> John C. Phelan, the secretary of the Navy, posted a message saying that sailors or Marines found to be “displaying contempt toward a fellow American who was assassinated” would be “dealt with swiftly and decisively.”

> Tim Weninger, a professor at the University of Notre Dame who studies the ways social media is used to dehumanize people and incite violence, described the targeting campaign as a new front in online rhetoric. “I haven’t seen something like this on social media in America, really ever — it’s a unique moment,” he said.

> Anastasios Kamoutsas, the commissioner of education in Florida, said in a memo to state superintendents on Thursday that some teachers had made “despicable comments” about Mr. Kirk’s killing and that he intended to investigate every teacher who posted vile, inappropriate messages.

(Also)

* Right-Wing Activists Are Targeting People for Allegedly Celebrating Charlie Kirk’s Death

[https://www.wired.com/story/right-wing-activists-are-targeting-people-for-allegedly-celebrating-charlie-kirks-death/?_sp=1522a619-e680-429d-9e8c-504e29747171.1757700164905](https://www.wired.com/story/right-wing-activists-are-targeting-people-for-allegedly-celebrating-charlie-kirks-death/?_sp=1522a619-e680-429d-9e8c-504e29747171.1757700164905)

* MAGA’s Doxing War Over Charlie Kirk Is Already Going Off the Rails | The New Republic

[https://newrepublic.com/post/200472/maga-doxxing-charlie-kirk-going-off-rails?utm_campaign=SF_TNR&utm_medium=social&utm_source=Bluesky](https://newrepublic.com/post/200472/maga-doxxing-charlie-kirk-going-off-rails?utm_campaign=SF_TNR&utm_medium=social&utm_source=Bluesky)

> Ali Nasrati, 30, said he hadn’t posted anything about Kirk but was still publicly doxed over an account using his name and photograph that made posts mocking the right-wing activist,

> Other instances of doxing appear to have been prompted by unverified information. Ryan Fournier, the national chair of Students for Trump, was forced to walk back accusations of anti-Kirk comments against an elementary school teacher in Wisconsin. “

> On Sunday night, an anonymous website collecting reports of anti-Kirk “political extremism” said it had received more than 63,000 submissions.

* Doxing Campaign Endangers Faculty and Free Speech

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/09/19/right-wing-doxing-campaign-endangers-faculty-and](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/09/19/right-wing-doxing-campaign-endangers-faculty-and)

> The force and scale of the doxing campaigns—and the speed with which institutions have moved to suspend or terminate their targets—paints a grim picture of free speech rights on public college campuses. Widespread doxing as a political tool to punish universities and academics is not a new phenomenon, but right now it’s particularly virulent, explained Keith Whittington, a professor at Yale Law School and an expert on free speech. “The size of the activity, the pressure campaign and the … short period of time is highly unusual,” he said. “Universities feel like they’re under intense pressure to mollify right-wing activists and try not to draw negative attention from the [Trump] administration.”

(This *is* happening at CUNY)


* Texas State professor fired for comments at socialism meeting | The Texas Tribune

[https://www.texastribune.org/2025/09/10/texas-state-university-professor-fired/](https://www.texastribune.org/2025/09/10/texas-state-university-professor-fired/)

(Also)

* A Tenured Professor Spoke Hypothetically About Overthrowing the Government. He Was Fired 3 Days Later.

[https://www.chronicle.com/article/a-tenured-professor-spoke-hypothetically-about-overthrowing-the-government-he-was-fired-3-days-later](https://www.chronicle.com/article/a-tenured-professor-spoke-hypothetically-about-overthrowing-the-government-he-was-fired-3-days-later)

> A Texas State University professor was fired days after he made remarks the institution’s president described as advocating for “inciting violence,” becoming the second faculty member in the state this week to be swiftly terminated following the release of a viral video.

> But experts say there’s an important distinction between the two cases: The Texas State faculty member was an associate professor with tenure, which typically grants several layers of due process before termination, while a Texas A&M senior lecturer who was terminated earlier this week didn’t have the same protections. Two people with knowledge of the situation confirmed to The Chronicle that the Texas State professor had earned tenure at the start of this academic year.

> The Texas State Employees Union, of which Alter is a member, said that he was fired “without a hearing or any meaningful opportunity to respond,” and that he only found out about his termination when Damphousse publicly announced it.

> The speed of Alter’s termination was legally dubious, higher-ed legal experts told The Chronicle, and violated the principles of academic freedom. While there have been many examples in the past dozen years of social-media campaigns calling for professors to be disciplined or even fired over their speech, Texas State’s near-instant decision to dismiss a tenured professor is rare, said Samantha Harris, a lawyer who defends college professors in disciplinary proceedings.

> “What Texas State is doing seems to me to be so obviously unlawful — and so likely to lead to a successful lawsuit — that they must be more afraid of something else, like running afoul of the political priorities of state or federal officials,” Harris said.

* University of Tennessee looks to terminate faculty member over social media post | wbir.com

[https://www.wbir.com/article/news/local/downtown-ut/ut-employee-charlie-kirk-investigation/51-2b6e9ad8-d0f8-4114-899d-dfccfd4db044](https://www.wbir.com/article/news/local/downtown-ut/ut-employee-charlie-kirk-investigation/51-2b6e9ad8-d0f8-4114-899d-dfccfd4db044)

> The University of Tennessee announced it placed one of its faculty members on administrative leave and is beginning termination proceedings against her after Tennessee lawmakers began looking into a social media post claiming she celebrated Charlie Kirk's assassination on social media.

* Clemson U. Touted Free Speech After 3 Employees Posted About Charlie Kirk. Then It Reversed Course.

[https://www.chronicle.com/article/clemson-u-touted-free-speech-after-3-employees-posted-about-charlie-kirk-then-it-reversed-course](https://www.chronicle.com/article/clemson-u-touted-free-speech-after-3-employees-posted-about-charlie-kirk-then-it-reversed-course)

(Ditto)

* Employees and Students at These Colleges Have Been Punished for Comments on Charlie Kirk’s Death

[https://www.chronicle.com/article/employees-and-students-at-these-colleges-have-been-punished-for-comments-on-charlie-kirks-death](https://www.chronicle.com/article/employees-and-students-at-these-colleges-have-been-punished-for-comments-on-charlie-kirks-death)

> A pattern has emerged: The college employee or student says something negative about Kirk — mostly online, but occasionally in class or on campus. State and congressional lawmakers and right-wing social-media accounts amplify the comments and advocate for the colleges to take disciplinary action. Some lawmakers have threatened to pull funding or enact other consequences if the colleges don’t fire the employees.

(Map of 24 faculty, 13 staff, 3 students; see appendix)


* Opinion | The Assassination That Broke Campus Free Speech

[https://www.chronicle.com/article/the-assassination-that-broke-campus-free-speech](https://www.chronicle.com/article/the-assassination-that-broke-campus-free-speech)

> This was already a theme before Kirk’s murder. Texas A&M University fired a lecturer seemingly at the behest of the governor after politicians objected to the content of her children’s-literature class. Texas State University fired a history professor for his personal advocacy of the organization of a revolutionary socialist party that would aid the working class to “overthrow” the United States government.

> But the pressure to patrol speech on college campuses has since reached new intensity. An assistant dean in the Office of Student Care and Conduct at Middle Tennessee State University was fired for a “callous and insensitive” social-media post after Kirk’s death. An English professor at Cumberland University was fired after a U.S. senator called attention to his posts about “a Nazi getting shot.” An art professor at the University of South Dakota was fired after calling Kirk a “hate-spreading Nazi” after his murder. A College of the Sequoias biology professor is under investigation for allegedly telling his class that he hoped Kirk’s whole family would meet the same fate. A Guilford Technical Community College English instructor was fired for praising the assassin to her class. An audio-technology professor at Clemson University has been suspended for mocking Kirk’s death in social-media posts.

> Public colleges are legally constrained by the First Amendment in how they can respond to demands to punish students and employees for hateful, morally depraved, or politically incendiary speech. Private colleges have more flexibility, though many have voluntarily tied themselves to First Amendment norms through their own policies. Everyone on campus, including senior university officials, should understand what speech is — and is not — protected under such rules.

> Given the misinformation about First Amendment rules routinely spread in public discourse — including by university officials — it is worth clarifying that in the United States, constitutional protections for speech are expansive, a fact not always reflected in the official statements from colleges. Texas State University suggested that speech that “advocates for inciting violence” is unprotected. Clemson claimed that the right to free speech does not extend to expression that “incites harm or undermines the dignity of others.” The chairman of the board at Southern University implied that “distasteful statements” about death are “tantamount to participating and inciting violence and spewing hate,” and thus unprotected. None of this is really true.

* NYTimes: The Kirk Crackdown Is Underway

[https://www.nytimes.com/2025/09/16/opinion/trump-charlie-kirk-crackdown.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/16/opinion/trump-charlie-kirk-crackdown.html?smid=nytcore-ios-share&referringSource=articleShare)

> President Trump and his allies are capitalizing on the assassination of Charlie Kirk to open up fresh attacks on liberal institutions, donors and foundations. They seek to portray many on the left as traitors.

> Trump and his allies have long exploited “emergencies” to push divisive measures. Now he claims that left-wing terrorism is a greater threat than terror perpetrated by the right, a demonstrably false assertion.

> Trump and his MAGA followers have not just turned Kirk’s murder into a political weapon; they are trying, with some success, to use it to build a national movement to publicly out everyone who criticized Kirk on social media after his death. They are also trying to persuade  employers to fire Kirk’s critics.

> Trump and Miller have claimed that the Ford Foundation and George Soros’s Open Society Foundations are financing violence on the left.

> The political right in the United States has long tried to argue that the political left is responsible for more violence than the political right. That simply hasn’t been true for decades. Lots of folks have surfaced a lot of evidence to illustrate that the far right has been responsible for more violence in the U.S. than the far left, including violent deaths. [Sam Jackson, a professor of emergency management and homeland security at SUNY-Albany]

> Violent far-right extremist have been responsible for 94 of the 108 terrorism fatalities (87 percent) in the United States in the past five years. This included 2022, when 18 of the 19 fatalities occurred during far-right terrorist attacks.

> Of the 71 terrorist attacks in 2022, 69 percent were perpetrated by those on the violent far right, 20 percent by the violent far left, 3 percent by Salafi-jihadists and 8 percent by ethnonationalists. [nonpartisan Center for Strategic and International Studies study from February 2024]

[https://www.csis.org/analysis/global-terrorism-threat-assessment-2024](https://www.csis.org/analysis/global-terrorism-threat-assessment-2024)


* Some Conservatives Blame Higher Ed for Political Violence

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/09/16/some-conservatives-blame-higher-ed-political](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/09/16/some-conservatives-blame-higher-ed-political)

> While Cox [Utah Governor] took pains [At least for one day] not to explicitly point fingers before receiving more evidence, some conservatives and right-leaning media organizations are blaming higher ed for “political violence” in the wake of Kirk’s death. Referencing the killing—and sometimes what they say are offensive comments various university staff and faculty have since allegedly made about the shooting—they’ve called for defunding universities, increasing the number of conservatives on campus, firing professors and more.

(But they go on to name check Kari Lake, Fox News host Rachel Campos-Duffy, editors of The Free Press, The Federalist (Breccan F. Thies), Laura Loomer, Harmeet K. Dhillon, Secretary Linda McMahon, Rep. Nancy Mace, Elon Musk, Stephen Miller, before getting to an AAUP response by it president Todd Wolfson)

> “What [Robinson allegedly] did—which we condemn in the strongest possible terms—they have blamed it on left voices, they have blamed it on higher education consistently,” said Todd Wolfson, president of the American Association of University Professors.

> Wolfson noted it’s currently unknown why Robinson allegedly shot Kirk, but it seems pretty clear it’s unrelated to universities.

> “We’re seeing people making broad claims not based on evidence in order to move forward political agendas, and so I find that very dangerous,” Wolfson said. “I think we need cooler heads to prevail.”


* All of This Because of Political Speech

[https://jacobin.com/2025/09/political-speech-antisemitism-universities-mccarthyism](https://jacobin.com/2025/09/political-speech-antisemitism-universities-mccarthyism)

(Brooklyn's Corey Robin Brings CUNY into focus with Berkeley)

> In the last three months, four adjunct instructors at Brooklyn College have been fired, and administrators have additionally called in for questioning five full-time faculty and one staff member.

> At any time, the Trump administration could ask CUNY to hand over “comprehensive documents, including files and reports” that simply involve these individuals’ “potential connection” to reports of alleged antisemitism.

> In my book on fear, I argued that regimes of fear critically depend on two types of individuals: careerists and collaborators. Today the word we hear is “complicity.” What all of these words are meant to suggest is that regimes of fear are never simply top-down affairs. They have a strong bottom-up component as well.

> Unfortunately, in our discourse today, including on the Left, that bottom-up element is often construed to be a mob of racist randos on social media or rubes in the red states. But that’s a comfort and a conceit. The truth is that collaborators are particular agents, trusted with discrete responsibility and concrete power at various levels, in multiple institutions, making choices, sometimes for the best of reasons, with consequences that they may not intend but that are likely to result anyway.

* Kirk’s Slaying Prompts College Leaders to Speak Out

[https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/09/17/kirks-slaying-prompts-college-leaders-speak-out](https://www.insidehighered.com/news/faculty-issues/academic-freedom/2025/09/17/kirks-slaying-prompts-college-leaders-speak-out)

> Universities are making exceptions to institutional neutrality policies to issue statements on Charlie Kirk’s death as some take aggressive action against some faculty remarks.

> Multiple universities adopted institutional neutrality policies amid the fallout [of the deadly Oct. 7, 2023, terrorist attacks], essentially agreeing to refrain from making statements on political matters and to show more restraint, generally, on issuing statements on current events.

> The University of Wyoming adopted institutional neutrality in late 2023.

> But last week, President Ed Seidel released a statement “expressing disgust, outrage and sadness at this apparent politically motivated attack”

> Although Middlebury does not have an institutional neutrality policy and Baucom [Middlebury President] emphasized he was speaking in his personal capacity, he said that he takes “broad guidance from the University of Chicago’s Kalven principles,” which essentially serve as the bedrock for such policies. But he also noted that the Kalven Report concluded that universities will need to defend their interests and values when “instances will arise” that threaten institutional missions and free inquiry.

> While Greenberg [Lawyer at FIRE] said Clemson’s statement ["“We stand firmly on the principles of the U.S. Constitution, including the protection of free speech,..However, that right does not extend to speech that incites harm or undermines the dignity of others.”] was rare, colleges punishing employees for their speech is not. He noted that FIRE is currently receiving tips on “dozens of cases” every day.

> “We’re in the cancel culture part of the tragedy cycle,” Greenberg said.

* Abbott Targets Students Who Allegedly Mocked Kirk’s Death

[https://www.insidehighered.com/news/students/free-speech/2025/09/18/abbott-targets-students-who-allegedly-mocked-kirks-death](https://www.insidehighered.com/news/students/free-speech/2025/09/18/abbott-targets-students-who-allegedly-mocked-kirks-death)

> Top Republican politicians have fueled the ongoing national repression of higher ed employees and others who have allegedly made offensive statements about last week’s shooting death of conservative activist Charlie Kirk. But Texas governor Greg Abbott has taken the campaign to another level: going after individual students.

> Abbott, who has more than 1.4 million followers on X, used that social media website to call for Texas State University to expel a student who appeared to mime Kirk’s shooting at a vigil for Kirk. Shortly after, university president Kelly Damphousse announced that a student in a “disturbing” video “is no longer a student at TXST.”

> In another post on X, Abbott applauded Texas Tech University for allegedly expelling and arresting a student. Reposting a photo of the student being handcuffed, Abbott posted, “FAFO,”

* McMahon Speaks Out About Kirk’s Death and Campus Culture

[https://www.insidehighered.com/news/quick-takes/2025/09/18/mcmahon-speaks-out-about-kirks-death-and-campus-culture](https://www.insidehighered.com/news/quick-takes/2025/09/18/mcmahon-speaks-out-about-kirks-death-and-campus-culture)

> McMahon began by praising those who have honored Kirk’s memory and the “values he held so dearly,” but she quickly turned her attention to denouncing the “small but vocal fringe” that has “sought to excuse, justify and even celebrate his murder.”

> “Alarmingly, many of these advocates of political violence are teachers, professors and administrators,” she said. “Make no mistake, ideological capture can lead to political violence by demonizing people with dissenting views.”

* NYTimes: The Dangers of the Charlie Kirk Aftermath

[https://www.nytimes.com/2025/09/18/opinion/trump-vance-bondi-douglassfree-speech.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/18/opinion/trump-vance-bondi-douglassfree-speech.html?smid=nytcore-ios-share&referringSource=articleShare)

(Good article with these salient quotes from Frederick Douglass)

> “No right was deemed by the fathers of the government more sacred than the right of speech. It was in their eyes, as in the eyes of all thoughtful men, the great moral renovator of society and government.”

> “of all rights, is the dread of tyrants. It is the right which they first of all strike down ... Thrones, dominions, principalities and powers, founded in injustice and wrong,” Douglass said, “are sure to tremble, if men are allowed to reason of righteousness, temperance, and of a judgment to come in their presence.”

> “Equally clear is the right to hear to suppress free speech is a double wrong. It violates the rights of the hearer as well as those of the speaker.”

* NYTimes: Trump Pressures Broadcasters Over Critical Coverage, Escalating Attack on Speech

[https://www.nytimes.com/2025/09/18/us/politics/trump-fcc-licenses.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/18/us/politics/trump-fcc-licenses.html?smid=nytcore-ios-share&referringSource=articleShare)

> President Trump said on Thursday that regulators should consider revoking the licenses of broadcasters that air negative coverage or commentary of him, indicating that his assault on critics’ language is motivated at least in part by personal animus.

* NYTimes: Trump Has Freedom of Speech. Do You?

[https://www.nytimes.com/2025/09/19/opinion/trump-freedom-of-speech-crackdown-kimmel.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/19/opinion/trump-freedom-of-speech-crackdown-kimmel.html?smid=nytcore-ios-share&referringSource=articleShare)

> Now he [one guess] is taking his campaign against free speech to a new level by using the assassination of Charlie Kirk as a justification to promise the repression of groups that he describes as liberal. Mr. Trump’s aides are drafting an executive order that could come as soon as this week, The Times reported, and it will most likely target left-leaning organizations. On Monday, Vice President JD Vance mentioned both the Ford Foundation and George Soros’s Open Society Foundations, saying that they benefited from a “generous tax treatment,” the same tax treatment that benefits nonprofit groups like religious charities and the National Rifle Association Foundation.

> The intimidation campaign is already having an effect.

* NYTimes: We Can No Longer Tell Ourselves This Isn’t Really Happening

[https://www.nytimes.com/2025/09/19/opinion/jimmy-kimmel-trump-media-government.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/19/opinion/jimmy-kimmel-trump-media-government.html?smid=nytcore-ios-share&referringSource=articleShare)

> Until Wednesday’s shocking announcement that ABC was cancelling Jimmy Kimmel’s late-night show because of comments he made about Charlie Kirk’s killing, it was possible, if one squinted hard enough, to pretend that a broad free speech crackdown was not underway. The down-the-road cancellation of Stephen Colbert’s late-night show on CBS was chalked up to financial concerns, though anyone in the business not paid to think otherwise believes Mr. Colbert’s elegant skewerings of President Trump and MAGA were the real reason.

> The silencing of Mr. Kimmel, following an explicit threat by Brendan Carr, the head of ABC’s regulator, the Federal Communications Commission, is the mask of “free speech” coming off for good.

> The complaint about so-called big media, historically, was that it was too commercial. Is it possible that these purveyors of popular culture will ignore the 50 percent or more of this country that want television, film and music that doesn’t feel like it was extruded directly from the president’s brain?

## Funding cuts

* ED Reallocates MSI Funding to HBCUs, Tribal Colleges

[https://www.insidehighered.com/news/institutions/minority-serving-institutions/2025/09/15/ed-reallocates-msi-funding-hbcus-tribal](https://www.insidehighered.com/news/institutions/minority-serving-institutions/2025/09/15/ed-reallocates-msi-funding-hbcus-tribal)

> When the U.S. Department of Education abruptly ended grants for most minority-serving institutions last week, it raised questions about what the department would do with the hundreds of millions of dollars already slated for these programs. The department offered an answer Monday, announcing plans to repurpose funds from programs “not in the best interest of students and families” to historically Black colleges and universities, tribal colleges, charter schools, and civics education.

(At CUNY some 35 projects impacted by the new DOE directive and the future funding of those projects is $14.1 million; the amount seriously at risk.)

### NIH

* NIH Now On Track to Spend Its Full Budget by Sept. 30

[https://www.insidehighered.com/news/quick-takes/2025/09/15/nih-now-track-spend-its-full-budget-sept-30](https://www.insidehighered.com/news/quick-takes/2025/09/15/nih-now-track-spend-its-full-budget-sept-30)

> The National Institutes of Health now appears on track to spend its full $47 billion budget by Sept. 30, the end of the federal fiscal year, STAT News reported Friday. That reflects “a frenzy of grantmaking activity during August,” worth more than $8 billion, STAT noted; the agency was far behind on awarding grants going into the summer, due to delays in the grant review process, the fight over the cap on indirect cost rates and widespread layoffs at the Department of Health and Human Services.

> However, STAT’s analysis showed that while the value of the grants awarded is roughly the same, the NIH is funding many fewer new projects this year than in the past. That’s because earlier this year the White House Office of Management and Budget mandated a shift in the way the agency distributes research dollars to a multiyear model, meaning that at least half of all new projects will be funded up front for multiple years rather than receive a new tranche of funding each year.

* NYTimes: Trump Is Shutting Down the War On Cancer

[https://www.nytimes.com/2025/09/14/magazine/cancer-research-grants-funds-trump.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/14/magazine/cancer-research-grants-funds-trump.html?smid=nytcore-ios-share&referringSource=articleShare)

(Damning story showing the effects of political malfeasance at the NIH)

> When America declared war on cancer more than 50 years ago, there was a misguided assumption outside the scientific community that it would be only a matter of years before the disease was eradicated — that defeating cancer would be no different than building an atomic bomb or putting a man on the moon. But there would be no miracle cure: As of this writing, some 40 percent of Americans will be diagnosed with cancer at some point in their life.

> According to a recent study in The Journal of Clinical Oncology, every $326 that our government spends researching cancer extends a human life by one year. Now an extraordinarily successful scientific research system — one that took decades to build, has saved millions of lives and generated billions of dollars in profits for American companies and investors — is being dismantled before our eyes.

> In a matter of months, the Trump administration has canceled hundreds of millions of dollars in cancer-related research grants and contracts, arguing that they were part of politically driven D.E.I. initiatives, and suspended or delayed payments for hundreds of millions more. It is trying to sharply reduce the percentage of expenses that the government will cover for federally funded cancer-research labs. It has terminated hundreds of government employees who helped lead the country’s cancer-research system and ensured that new discoveries reached clinicians, cancer patients and the American public. And the president’s proposed budget for the next fiscal year calls for a more-than-37-percent cut to the National Cancer Institute — the N.I.H. agency that leads most of the nation’s cancer research — reducing it to $4.5 billion from $7.2 billion. Adjusting for inflation, you have to go back more than 30 years to find a comparably sized federal cancer-research budget.

> In the absence of any such plan [neither he nor anyone inside his administration has spoken explicitly about its intention to radically rethink how America funds and directs cancer research], it’s hard not to see the ongoing dismantling of the cancer research system as collateral damage in a larger, partisan war against both the predominantly Democratic scientific establishment and the predominantly Democratic academic institutions where much of the country’s biomedical research takes place. And yet the term “collateral damage” suggests a lack of agency; this has been a deliberate and targeted attack. “They have studied how N.I.H. works, studied it hard and learned it well,” says Sarah Kobrin, head of the Health Systems and Interventions Research Branch at the National Cancer Institute. “And they have put sand in the gears in ways that are very effective, devastating.”

* NYTimes: California’s $23 Billion Plan to Restore Federal Cuts to Scientific Research

[https://www.nytimes.com/2025/09/13/us/california-scientific-research-bond.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/13/us/california-scientific-research-bond.html?smid=nytcore-ios-share&referringSource=articleShare)

> Supporters of the proposal said it would effectively create a state version of the National Institutes of Health or the National Science Foundation, two of the nation’s largest institutional funders of scientific and public health research. The move follows California, Washington and Oregon’s announcement that they would form a health alliance to review scientific data and make vaccine recommendations for their residents, in an attempt to bypass vaccine skeptics in the Trump administration.

> The plan to back scientific research calls for lawmakers to pass, and for voters to approve in a 2026 ballot measure, a proposed $23 billion in bonds, financing that will allow the state to make grants and loans to universities, research companies and health care organizations.

> It would be the largest state effort of its kind, and is considerably more aggressive than one floated in Massachusetts in July, when Gov. Maura Healey made a $400 million proposal for research there.

### NEH

* NEH grant to fight antisemitism is largest ever, signaling Trump-era shift

[https://www.washingtonpost.com/entertainment/2025/09/16/neh-grant-tikvah-jewish-civilization-project/](https://www.washingtonpost.com/entertainment/2025/09/16/neh-grant-tikvah-jewish-civilization-project/)

> The grant was not part of a competition, and Tikvah was invited to apply, according to two people with direct knowledge of the grantmaking process

> Tikvah is a New York-based think tank and nonprofit that describes its mission as advancing “Jewish excellence and Western civilization through education and ideas.” The group has been associated with conservative U.S. politics. At an upcoming conference, it will award prizes to right-wing commentator Ben Shapiro, Free Press editor Bari Weiss and former Republican adviser Dan Senor.

> One of the people said the NEH has justified the large awards because of limited staff resources at the agency, which drastically slashed its workforce in June.

(I have other answers more in line with the Occam's razor principle)

### DOE

* Education Department Ends Grant Funding Worth $350 Million for Minority-Serving Colleges

[https://www.nytimes.com/2025/09/10/us/politics/linda-mcmahon-federal-grants-colleges-universities.html](https://www.nytimes.com/2025/09/10/us/politics/linda-mcmahon-federal-grants-colleges-universities.html)

(Thanks K!)

> U.S. Education Secretary Linda McMahon announced Wednesday that she was halting $350 million in federal funding for some of America’s most diverse colleges and universities, saying programs aimed at supporting specific enrollment requirements for minority students were inherently racist.

* NYTimes: Trump Redirects Millions to Historically Black Colleges, Charter Schools

[https://www.nytimes.com/2025/09/15/us/hbcus-trump-administration-funding.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/15/us/hbcus-trump-administration-funding.html?smid=nytcore-ios-share&referringSource=articleShare)

> The Trump administration on Monday announced that it would inject nearly $500 million into historically Black colleges and tribal universities, a windfall funded largely by cuts to programs elsewhere for minority students.

> The administration will also redirect money to other political priorities for President Trump, including an extra $137 million for American history and civics education and $60 million more for charter schools.

> To pay for the changes, the administration cut money from other parts of the education budget The details of the changes were described by three people familiar with the department’s plans who insisted on anonymity to speak about private discussions.

> The biggest cut, announced by the department last week, is a $350 million hit to programs that support minority students in science and engineering programs, schools with significant Hispanic enrollment, and other federal grants at minority-serving institutions.

> President Trump has routinely sought to align himself with historically Black colleges and universities as a way to earn good will from Black voters, who have long been skeptical of his leadership.

* Education Dept. Halts Funds to Programs for Deafblind Students Over DEI Concerns — ProPublica

[https://www.propublica.org/article/trump-dei-students-education-deaf-blind-grant-funding](https://www.propublica.org/article/trump-dei-students-education-deaf-blind-grant-funding)

> The U.S. Department of Education has pulled funding for programs in eight states aimed at supporting students who have both hearing and vision loss, a move that could affect some of the country’s most vulnerable students.

> The programs are considered vital in those states but represent only a little over $1 million a year in federal money. Nonetheless, they got caught in the Trump administration’s attacks on diversity, equity and inclusion, with an Education Department spokesperson citing concerns about “divisive concepts” and “fairness” in acknowledging the decision to withhold the funding.

> “I was told that apparently the administration is going through past grants and two words were flagged: One was transition and one was privilege,” Klenz said. “Transition — transitioning from childhood to adulthood. Privilege came up because a parent wrote a glowing review of staff that said what a privilege it was to work with them.” ProPublica obtained a copy of the grant application and confirmed that those words were included.


## Federal Agencies

* Trump Administration Withholds Millions for TRIO Programs

[https://www.insidehighered.com/news/government/student-aid-policy/2025/09/12/trump-administration-withholds-millions-trio-programs](https://www.insidehighered.com/news/government/student-aid-policy/2025/09/12/trump-administration-withholds-millions-trio-programs)

> this month, the Trump administration has frozen hundreds of millions of dollars in TRIO grants, creating uncertainty for thousands of programs....Over all, the Council for Opportunity in Education, a nonprofit advocacy group that focuses on supporting TRIO programs, estimates that the Trump administration has withheld about $660 million worth of aid for more than 2,000 TRIO programs.

> Roughly 650,000 college students and high school seniors will lack vital access to academic advising, financial guidance and assistance with college applications if the freeze persists, they say.


### DOE/OCR

* Provosts Agree Antisemitism on Campus Is a Problem

[https://www.insidehighered.com/news/diversity/religion/2025/09/12/provosts-agree-antisemitism-campus-problem](https://www.insidehighered.com/news/diversity/religion/2025/09/12/provosts-agree-antisemitism-campus-problem)

> The judge who delivered a legal win to Harvard University in its battle with the Trump administration wrote in her opinion last week, “We must fight against antisemitism, but we equally need to protect our rights, including our right to free speech, and neither goal should nor needs to be sacrificed on the altar of the other.”

> It seems most provosts would concur: In Inside Higher Ed’s forthcoming annual survey of College and University Chief Academic Officers with Hanover Research, 88 percent of some 478 respondents agree that antisemitism is a problem in higher education today. But just 20 percent agree that recent federal interventions into campus climates, such as those seen at Harvard and Columbia University—which are unprecedented in scope and speed, and have resulted in the suspension of billions of dollars in unrelated research funding—may be justified.

> Nadell [ Patrick Clendenen Chair in Women’s and Gender History at American University and author of the new book Antisemitism, an American Tradition] continued, “It’s also really important to understand that the leadership of the Republican Party had, well before Oct. 7, been planning an attack on the university.” And there’s “no question, as I see it, that antisemitism has become instrumentalized to do something that the administration and the current leadership has long wanted to achieve.”

> “This administration is hiding the ball, making it even more combative and more difficult,” Gellman-Beer [a civil rights compliance consultant who handled all manner of shared ancestry complaints under Republican and Democratic administrations through the Office for Civil Rights’ Philadelphia branch] said. “The administration is changing the legal standard with every new letter that comes out. It’s confusing, and it makes senior leaders not necessarily have trust in the process and trust in this administration that what they’re doing is to help the school.”


## Institutional assaults

### Harvard

* Lutnick: Trump Wants Harvard to Build Vocational School

[https://www.insidehighered.com/news/quick-takes/2025/09/12/lutnick-trump-wants-harvard-build-vocational-school](https://www.insidehighered.com/news/quick-takes/2025/09/12/lutnick-trump-wants-harvard-build-vocational-school)

> While President Trump has proposed slashing the federal workforce development budget, a potential settlement between Harvard University and the Trump administration could involve the a plan to use $500 million the government is demanding to build vocational schools, Bloomberg reported Thursday.

> “If Harvard settles with Donald Trump, you know what he’s going to do with the $500 million?” Lutnick said. “He’s going to have Harvard build vocational schools. The Harvard vocational school, because that’s what America needs.”

### UCLA

* Trump Proposes $1.2B Fine in UCLA Settlement Letter

[https://www.insidehighered.com/news/quick-takes/2025/09/16/trump-proposes-12b-fine-ucla-settlement-letter](https://www.insidehighered.com/news/quick-takes/2025/09/16/trump-proposes-12b-fine-ucla-settlement-letter)

> The Trump administration is looking to fine the University of California, Los Angeles, $1.2 billion for the institution’s alleged practices of antisemitism, according to the Los Angeles Times.

> The fine is just one element of Trump’s 28-page settlement proposal to the university; other provisions include overhauling the institution’s admissions procedures and hiring practices as well as its policies surrounding athletics, scholarships, gender identity and discrimination, the Times reported. In exchange, the Trump administration would release about $500 million in stalled research grants from the National Institutes of Health and the Department of Energy.

> The paper also noted that the letter seemed thrown together quickly, contained a number of typos and made erroneous references to other universities.

(re-read that last quote. Is this really possible?)


### UC Berkeley

* UC Berkeley shares 160 names with Trump administration in ‘McCarthy era’ move | US universities | The Guardian

[https://www.theguardian.com/us-news/2025/sep/12/uc-berkeley-trump-administration-antisemitism](https://www.theguardian.com/us-news/2025/sep/12/uc-berkeley-trump-administration-antisemitism)

> The University of California, Berkeley has given the Trump administration the names of 160 faculty members and students as part of an investigation into “alleged antisemitic incidents”, a move a targeted scholar likened to a “practice from the McCarthy era”.

> UC Berkeley, a top-ranked public institution, sent a letter to affected members of campus last week disclosing that university lawyers had included their names in reports to the Department of Education’s office for civil rights (OCR). The education department has been targeting colleges across the country as part of Donald Trump’s aggressive crackdown on pro-Palestinian activism, international students and academic freedom.

> Judith Butler, a prominent feminist philosopher and queer theorist, received the letter from David Robinson, UC Berkeley’s chief campus counsel, which said OCR was investigating “allegations of antisemitic harassment and discrimination” and “required production of comprehensive documents”.

> Butler, a Jewish scholar who has been critical of Israel, said on Friday that they had questioned Robinson about the disclosures and said he provided no information on the specific allegations.

> “We have a right to know the charges against us, to know who has made the charges and to review them and defend ourselves,” they said. “But none of that has happened, which is why we’re in Kafka-land … It is an enormous breach of trust.”

(Also)

[https://www.nytimes.com/2025/09/13/us/politics/trump-berkeley-antisemitism-investigation.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/13/us/politics/trump-berkeley-antisemitism-investigation.html?smid=nytcore-ios-share&referringSource=articleShare)

(Also)

[https://www.chronicle.com/article/uc-berkeley-hands-over-160-names-to-the-federal-government-for-potential-connection-to-antisemitism](https://www.chronicle.com/article/uc-berkeley-hands-over-160-names-to-the-federal-government-for-potential-connection-to-antisemitism)

### University of California System

* NYTimes: University of California Leaders to Meet as Trump Increases Pressure

[https://www.nytimes.com/2025/09/17/us/university-of-california-berkeley-regents-meeting.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/17/us/university-of-california-berkeley-regents-meeting.html?smid=nytcore-ios-share&referringSource=articleShare)

> University of California leaders, besieged by a billion-dollar demand from the Trump administration, will meet Wednesday as they weigh how to confront Washington’s campaign to remake American campuses.

> The consequences of that effort have become increasingly vivid inside the university, which has been contending with an uproar over its decision last month to comply with federal investigators’ request for information. The university gave the Department of Education the names of scores of students and employees connected to allegations of antisemitism, a move that infuriated people throughout the 10-campus system after word of it emerged this month.

> The disclosure deepened the sense of turmoil inside U.C., which is facing an escalating effort from the Trump administration to force changes to one of the nation’s largest and most distinguished university systems. The full Board of Regents has not met in public since mid-July, and the Trump administration’s tactics have gathered far greater force since then.

> For example, the government demanded last month that the university pay about $1.2 billion to settle accusations of antisemitism at its Los Angeles campus, and it has pressured administrators there to accept conditions that include steps to ensure “that foreign students likely to engage in anti-Western, anti-American or antisemitic disruptions or harassment are not recruited or admitted.”

> Ahead of Wednesday’s regents’ meeting in San Francisco, Mr. Milliken acknowledged in a statement that threats to the system could metastasize and warned that the federal authorities were “pursuing investigations and actions in various stages against all 10 U.C. campuses.”

> In a statement on Tuesday, the system’s general counsel, Charles F. Robinson, argued that the university had only followed its regular practice of responding to “information requests arising from audits, compliance reviews and investigations.” Mr. Robinson said the university had also made sure to comply with “applicable privacy laws.”

> “U.C. will continue to meet its legal obligations,” he added, “while exploring all legal avenues to safeguard the privacy and trust of our community members.”

> But the litigation from the workers’ groups nevertheless underscored the measured approach that U.C. has adopted so far. Some inside the university are wary of taking steps that could further rile the Trump administration, which has repeatedly cut federal funding to universities to try to bring them to heel.

> Like other major American universities, U.C. relies on vast sums of federal funding to operate. More than $7 billion goes to research and federal student aid, Mr. Milliken noted this week, while roughly $10 billion more flows from the Medicare and Medicaid programs. (U.C. has six academic medical centers.)

* Groups sue administration over funding freeze at University of California

[https://www.washingtonpost.com/education/2025/09/16/groups-sue-administration-over-funding-freeze-university-california/](https://www.washingtonpost.com/education/2025/09/16/groups-sue-administration-over-funding-freeze-university-california/)

> The complaint was filed Tuesday in federal district court by the American Association of University Professors, Democracy Forward, and numerous other labor unions and organizations that represent tens of thousands of faculty members, students and staff members across the large public university system.

> The lawsuit details numerous demands, also reported Monday by the Los Angeles Times, made by the Trump administration of UCLA. They include eliminating diversity, equity and inclusion programs; ceding control over university admissions, hiring and curriculum to an outside monitor; reporting student disciplinary records; and other measures.

> The Trump administration has sought to exert ideological control over higher education, the lawsuit contends, “through a scheme of targeting, bullying and unconstitutional actions aimed at institutions of higher education across the country.”

(Also)

[https://www.insidehighered.com/news/quick-takes/2025/09/17/california-unions-sue-trump-admin-over-threats-uc-system](https://www.insidehighered.com/news/quick-takes/2025/09/17/california-unions-sue-trump-admin-over-threats-uc-system)

### Texas A&M

*
Texas A&M president resigns after instructor’s firing over gender teachings

[https://www.washingtonpost.com/nation/2025/09/18/texasam-president-resign-mark-welsh-gender/](https://www.washingtonpost.com/nation/2025/09/18/texasam-president-resign-mark-welsh-gender/)

(Thanks VAC)

> Welsh took over at Texas A&M two years ago after M. Katherine Banks retired as university president in the wake of a scandal involving the botched hiring of journalism professor Kathleen McElroy. That job offer provoked backlash from the Texas GOP because of McElroy’s work on diversity, equity and inclusion programs, which Texas has since banned.

> “Today, President Welsh has submitted his resignation, and both the Board of Regents and I agree that this is the right moment for change,” Texas A&M Chancellor Glenn Hegar said

> “It was the right decision for him to do for himself, the university, students, and faculty,” said Leonard Bright, a professor at Texas A&M’s Bush School of Government and Public Service, in a text message. “Now, we look to the university and (board of regents) to conduct an earnest search for a replacement who will fully support the values of academic freedom and protect the university from political interference in our classrooms.”

(Also)

[https://www.insidehighered.com/news/governance/executive-leadership/2025/09/18/texas-am-president-steps-down-under-pressure](https://www.insidehighered.com/news/governance/executive-leadership/2025/09/18/texas-am-president-steps-down-under-pressure)

[https://www.nytimes.com/2025/09/18/us/texas-am-president-gender-ideology-controversy.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/2025/09/18/us/texas-am-president-gender-ideology-controversy.html?smid=nytcore-ios-share&referringSource=articleShare)

> The case also raised serious questions about academic freedom at Texas A&M and prompted pushback from faculty members who argued that McCoul’s termination was unnecessary and unjust. The American Association of University Professors also released a statement arguing that the “firings set a dangerous new precedent for partisan interference in Texas higher education.”


## Coming attractions?

* Charlie Kirk’s Death Is a Catastrophe for Higher Ed---Things were already bad. They’re about to get worse.

[https://www.chronicle.com/article/charlie-kirks-death-is-a-catastrophe-for-higher-ed](https://www.chronicle.com/article/charlie-kirks-death-is-a-catastrophe-for-higher-ed)

> Colleges and universities have been under pressure by Kirk and his political allies for years. Turning Point USA launched its Professor Watchlist in 2016 to intimidate professors whom the organizations claims “discriminate against conservative students, promote anti-American values, and advance leftist propaganda in the classroom.” (Full disclosure: I am on the Professor Watchlist myself, apparently on the basis of my scholarship on the conservative movement and the far right and teaching a class on fascism and antifascism.)

> But TPUSA’s attacks on academic freedom have paled in comparison to the Trump administration’s assaults on higher education through funding freezes for basic scientific research, legal attacks on diversity, equity, and inclusion initiatives, and the targeting of dozens of universities by the Department of Justice for transparently political reasons. At the University of Virginia, my home institution, DOJ pressure was instrumental in prompting the resignation of the university’s president, Jim Ryan, at the end of June.

> It is practically inevitable that there will be dire policy consequences from Kirk’s assassination, regardless of the actual ideology of his killer, because his death fits a pre-existing narrative about left-wing campus radicalism that is already the driver of federal policy. We can expect to see an intensification of the Trump administration’s political and legal battles with universities, even tighter scrutiny for faculty and staff (particularly those teaching controversial or sensitive subjects), and the continued erosion of academic freedom on campuses targeted by the administration.

> There is also the very real threat of further violence. Scores of prominent MAGA influencers reacted to Kirk’s death by calling for violence against their political enemies. Chaya Raichik, who runs the infamous LibsOfTikTok X account, which before Elon Musk’s Twitter takeover was suspended multiple times for inciting death threats, declared that “THIS IS WAR.” Musk, for his part, wrote that “The Left is the party of murder.” There have already been consequences: On Thursday, at least five HBCUs in Alabama, Florida, Louisiana, and Virginia locked down their campuses due to terroristic threats.

* Chris Rufo Floats Calling in ‘Troops’---The conservative activist says President Trump should consider using the military to dismantle college DEI programs.

[https://www.chronicle.com/podcast/college-matters-from-the-chronicle/chris-rufo-floats-calling-in-troops](https://www.chronicle.com/podcast/college-matters-from-the-chronicle/chris-rufo-floats-calling-in-troops)

> And for me, the frame of reference is the campaign to desegregate universities in the 1960s, the early 1960s. And your listeners may recall that in fact, the president of the United States, President Kennedy, actually sent in armed … sent in the 101st Airborne troops to forcibly desegregate universities. I think he established an important precedent and I think the president to this day still retains all remedies up to and including parachuting in the 101st Airborne if these universities continue to discriminate on the basis of race, scapegoat students on the basis of race, and segregate students on basis of race.

> But the principle is still the same. Discrimination is discrimination, segregation is segregation, scapegoating is scapegoating. And the precedent is still the same. The president under Article II of the Constitution retains the power to enforce the law, to make sure that universities are adhering with the Constitution and the Civil Rights Act. And I’m not saying that the president should send in the 101st Airborne. I’m merely saying that he retains the right to do so under the Constitution and longstanding precedent.


## Tracking projects

* NYTimes: What You Need to Know About Police Surveillance

[https://www.nytimes.com/interactive/2025/09/15/opinion/nypd-surveillance.html?smid=nytcore-ios-share&referringSource=articleShare](https://www.nytimes.com/interactive/2025/09/15/opinion/nypd-surveillance.html?smid=nytcore-ios-share&referringSource=articleShare)

(Starts with:)

> Wherever you go in New York City, there’s a good chance the police are tracking you. Enter the subway system, for instance, and your identity, banking information and location trickle into city databases.

(and gets more scary from there.)


----

Again, some links are behind paywalls. The shortened wapo links are gift articles; the Chronicle links should be available through a CUNY library. I have online access to the WSJ articles through CUNY.

These digests are now archived at

[https://cunytracker.github.io/CUNYTracker/](https://cunytracker.github.io/CUNYTracker/)


----

Appendix:

Data from https://www.chronicle.com/article/employees-and-students-at-these-colleges-have-been-punished-for-comments-on-charlie-kirks-death

| **College affiliate**<br>`String`            | **Action taken**<br>`String31` | **Details**<br>`String`                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|---------------------------------------------:|-------------------------------:|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| Clemson U. faculty                           | Terminated                     | Reposted on Facebook: “Karma is sometimes swift and ironic. As Kirk said, ‘play certain games, win certain prizes.’”                                                                                                                                                                                                                                                                                                                                                                      |
| Clemson U. faculty                           | Terminated                     | Wrote on X: “Racism and white supremacy age you,” in response to a comment saying Kirk looked old at 31. Reposted on X: “According to Kirk, empathy is a made-up new age term, so keep the jokes coming. it’s what he would have wanted.”                                                                                                                                                                                                                                                 |
| Clemson U. staff                             | Terminated                     | Wrote on Facebook: “In a world of Charlie Kirks and Brian Thompsons, be a Tyler Robinson or a Luigi Mangione," adding that Kirk was a “cancer on our constitution that has now thankfully been ameliorated.”\n                                                                                                                                                                                                                                                                            |
| Austin Peay State U. faculty                 | Terminated                     | Shared on Facebook: a screenshot of a 2023 Newsweek headline in which Kirk said gun deaths were “unfortunately” worth it to preserve the Second Amendment.                                                                                                                                                                                                                                                                                                                                |
| Middle Tennessee State U. faculty            | Terminated                     | Wrote on Facebook: "Looks like ol’ Charlie spoke his fate into existence. Hate begets hate. ZERO sympathy.”                                                                                                                                                                                                                                                                                                                                                                               |
| Cumberland U. faculty                        | Terminated                     | Wrote on Facebook: "Crying about a Nazi getting shot while staying silent about the school shooting in Colorado today is peak Republican." Wrote on Facebook: "On Charlie Kirk: Thoughts & Prayers Oh AND Kharma is a beautiful bitch."                                                                                                                                                                                                                                                   |
| Cumberland U. staff                          | Terminated                     | Wrote on X: "God comes to collect no matter how rich and politically powerful you are. If you live a life of SIN and bask in it, you deserve whatever judgement god deems fit. One less Pedophile supporter on this planet."                                                                                                                                                                                                                                                              |
| Texas Tech U. student                        | Expelled                       | Captured on video at a Kirk vigil: "F--k y'all homie dead, he got shot in the head."                                                                                                                                                                                                                                                                                                                                                                                                      |
| U. of Mississippi staff                      | Terminated                     | Reposted on Instagram stories: Kirk is a "reimagined Klan member" who has "wreaked havoc on our communities," and added, "So no, I have no prayers to offer Kirk or respectable statements against violence."                                                                                                                                                                                                                                                                             |
| U. of Miami staff                            | Terminated                     | Reposted on Instagram stories: "What was done to Charlie Kirk has been done to countless Palestinian babies, children, girls, boys, women and men... And whenever it happened... Charlie Kirk came out to say: I love this, I want more of this. The people who did this are great and I love them and they should keep doing it forever. As Malcolm said, the chickens have come home to roost.”                                                                                         |
| Florida Atlantic U. faculty                  | Suspended                      | Reposted on X: several posts describing Kirk's public statements as racist, anti-gay, and anti-woman.                                                                                                                                                                                                                                                                                                                                                                                     |
| Guilford Technical Community College faculty | Terminated                     | Captured on video during an online class: “I’ll praise the shooter; he had good aim."                                                                                                                                                                                                                                                                                                                                                                                                     |
| U. of Tennessee at Knoxville faculty         | Terminated                     | Commented on Facebook: "The world is better off without him in it," criticizing Kirk's wife for marrying him.                                                                                                                                                                                                                                                                                                                                                                             |
| Baylor U. student                            | Terminated                     | Commented on Instagram: "This made me giggle," under a post about Kirk's death. (Lost a teaching role but remains enrolled as a student.)                                                                                                                                                                                                                                                                                                                                                 |
| East Tennessee State U. faculty              | Suspended                      | Posted on Facebook: "You can't be upset if one of those deaths in [sic] yours," resharing a 2023 headline suggesting that "some gun deaths" an acceptable consequence of the Second Amendment. Commented on Facebook: "He reaped what he sowed."                                                                                                                                                                                                                                          |
| East Tennessee State U. faculty              | Suspended                      | Unknown                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| Columbus State U. faculty                    | Resigned                       | Commented on a news website: Kirk "spewed hate constantly" and "reveled in putting down younger people," and "his debates were filled with falsehoods, racism, homophobia, and white supremacist rhetoric." (Resigned from two roles but remains on the faculty.)                                                                                                                                                                                                                         |
| Coastal Carolina U. staff                    | Terminated                     | Wrote on Facebook: "Saying 'violence is never the answer' ignores reality. Violence freed slaves. Violence stopped Hitler. Violence protects families from attackers when police can't get there in time. The truth is, violence has ended more evils than peaceful words ever have. It's not about whether violence is the answer -- it's about when it becomes the only answer." Wrote on Facebook: a post suggesting that South Carolina Rep. Nancy Mace "might not be to far behind." |
| Coastal Carolina U. staff                    | Suspended                      | Reposted on Instagram stories: "The controversy isn't about being 'politically incorrect,' 'having a difference of opinion,' or 'preaching the gospel,' it is about repeating bigoted ideas on a stage that reached tens of millions."                                                                                                                                                                                                                                                    |
| Texas State U. student                       | Expelled                       | Captured on video at a Kirk memorial event: "Charlie Kirk got hit in the neck, b--ch," gesturing to his neck, and then imitated Kirk falling over after being shot.                                                                                                                                                                                                                                                                                                                       |
| U. of South Dakota faculty                   | Suspended                      | Wrote on Facebook: "I don't give a flying f--k about this Kirk person. Apparently he was a hate-spreading Nazi. ... I'm sorry for his family ... But geez, where was all this concern when the politicians in Minnesota were shot? And the school shootings? And Capital Police?"                                                                                                                                                                                                         |
| Enterprise State Community College faculty   | Terminated                     | Posted on TikTok: criticism of the attention Kirk's death received, saying, "Let us not forget some other children were shot in another f--king shooting today," in reference to a September 10 incident at a Colorado high school. Posted on TikTok: "Am I trying to indoctrinate my students in my liberal, progressive values? Sure the f--k am."                                                                                                                                      |
| U. of Arkansas at Little Rock faculty        | Suspended                      | Wrote on Facebook: "I will not pull back from CELEBRATING that an evil man died by the method he chose to embrace. Don't tell people who have been targeted by someone like him how to feel, how not to post, how not to celebrate that he can no longer inflict his brand of evil."                                                                                                                                                                                                      |
| U. of California at Los Angeles staff        | Suspended                      | Commented on Bluesky: "You can’t force people to mourn someone who hated us — no matter how he died." Commented on Bluesky: "It is OKAY to be happy when someone who hated you and called for your people’s death dies — even if they are murdered.”                                                                                                                                                                                                                                      |
| Fresno State U. faculty                      | Suspended                      | Captured on video during a class, before Kirk passed away: “You want to know what I think? It’s too bad he’s not dead ... Gonna put my political views right out there. And that’s exactly what I thought. He’s just shot? I was like, he’s not dead. I don’t even know who he is. Just the description of him – it’s like – don’t care.”                                                                                                                                                 |
| College of the Sequoias faculty              | Suspended                      | Captured on video during a class: "I hope everyone in his family dies, and their children, and their grandchildren, and their grandchildren, and their grandchildren, to eternity."                                                                                                                                                                                                                                                                                                       |
| Southern U. Law Center faculty               | Suspended                      | Commented on Facebook: "I will 1000% wish death on people like him. He is the epitome of evil, and I have no compassion not even a minute ounce of it for people like him who go around spewing hate the way he does.”                                                                                                                                                                                                                                                                    |
| U. of Kentucky staff                         | Suspended                      | Commented on Facebook (citing a quote): "I have never wished a man dead, but I have read some obituaries with great satisfaction. Clarence Darrow."                                                                                                                                                                                                                                                                                                                                       |
| U. of Louisville staff                       | Investigated                   | Posted on Facebook: A 2023 quote from Kirk about gun violence deaths being “worth it” to protect Second Amendment rights, and wrote alongside, "Presented without comment."                                                                                                                                                                                                                                                                                                               |
| Mississippi College faculty                   | Suspended                      | Posted on Facebook: that Kirk’s killing is like a “Greek tragedy, full of irony and self-fulfilling prophecies," and that Kirk "lived his life advocating for gun rights without concern for gun deaths,” and “died from gun violence."                                                                                                                                                                                                                                                   |
| Florida Atlantic U. faculty                  | Suspended                      | Wrote on X (seeming to address the person who shot Kirk): “You think you are anonymous, you COWARD. You spread your hate speech. We are going to hunt you down. We are going to identify you. Then we are going to make you radioactive to polite society. And we will make you both unemployed and unemployable."                                                                                                                                                                        |
| Montana State University-Northern faculty    | Suspended                      | Wrote on Facebook: "He was a mysogynistic, homophobic, xenophobic asshole. He spread hate. He harmed society. He cut down women at every turn. No, I do not mourn the man" and "Holy shit! Someone shot Charlie Kirk in the neck! Not condoning violence, but maybe people are sick of the garbage he spews, perhaps?"                                                                                                                                                                    |
| Gannon University staff                      | Terminated                     | Employee of the university was fired for "deeply troubling social media posts and other inappropriate reactions about the killing of Charlie Kirk"                                                                                                                                                                                                                                                                                                                                        |
| Auburn University staff                      | Terminated                     | An unnamed number of employees engaged in posting “hurtful” content on social media. The employees in question were terminated for violating "the school’s Code of Conduct," President Christopher Roberts wrote.                                                                                                                                                                                                                                                                         |
| North Idaho College faculty                  | Suspended                      | Instructor was placed on leave following "insensitive remarks about the killing of conservative activist Charlie Kirk"                                                                                                                                                                                                                                                                                                                                                                     |
| Iowa State University staff                  | Investigated (only)            | The Board of Regents gave a two-week deadline for the investigation of a post she wrote on Facebook: “Given Charlie’s previous comments about their ‘necessity’ to protect 2nd amendment rights though, this (expletive) got what was coming and I’m happy he’s rotting in hell now."                                                                                                                                                                                                     |
| Iowa State University faculty                | Investigated (only)            | The Board of Regents gave a two-week deadline for the investigation of a post he wrote on Facebook: “Yeah sorry pretty sure we’re all OK with political violence. Every. One. Of. Us.”                                                                                                                                                                                                                                                                                                    |
| Ball State University staff                  | Terminated                     | Posted on Facebook: "If you think Charlie Kirk was a wonderful person, we can't be friends." Described his his death "a tragedy" for his family, but also "a reflection of the violence, fear, and hatred he sowed."                                                                                                                                                                                                                                                                      |
| Ball State University faculty                | Investigated (only)            | Commented on a social media post: "Feels like karma paid a visit" and “I mean he condoned killing immigrants and trans people. He was quoted as saying mass shootings are the process you pay for the second amendment and it was worth it. Don’t go clutching your pearls… what the hell do you people expect?”                                                                                                                                                                          |
| Emory University faculty                     | Terminated                     | A non-clinical faculty member at the medical school made a social media post generating "concern" across the community. The content of the post was not made public by the university.                                                                                                                                                                                                                                                                                                    |
